ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: angle.hpp File Reference
angle.hpp File Reference
Routines to calculate the angle energy or/and and force for a particle triple.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "grid.hpp"
Functions
int angle_set_params (int bond_type, double bend, double phi0)
set parameters for the angle potential.
int calc_angle_force (Particle *p_mid, Particle *p_left, Particle *p_right, Bonded_ia_parameters *iaparams, double force1[3], double force2[3])
Computes the three body angle interaction force and adds this force to the particle forces (see tclcommand_inter).
void calc_angle_3body_forces (Particle *p_mid, Particle *p_left, Particle *p_right, Bonded_ia_parameters *iaparams, double force1[3], double force2[3], double force3[3])
int angle_energy (Particle *p_mid, Particle *p_left, Particle *p_right, Bonded_ia_parameters *iaparams, double *_energy)
Computes the three body angle interaction energy (see tclcommand_inter, tclcommand_analyze).
Detailed Description
Routines to calculate the angle energy or/and and force for a particle triple.
forces.cpp
Definition in file angle.hpp.
Function Documentation
int angle_energy (Particle * p_mid, Particle * p_left, Particle * p_right, Bonded_ia_parameters * iaparams, double * _energy) inline
Computes the three body angle interaction energy (see tclcommand_inter, tclcommand_analyze).
Parameters
p_mid Pointer to first particle.
p_left Pointer to second/middle particle.
p_right Pointer to third particle.
iaparams bond type number of the angle interaction (see tclcommand_inter).
_energy return energy pointer.
Returns
0.
Definition at line 204 of file angle.hpp.
References Bond_parameters::angle, Angle_bond_parameters::bend, Angle_bond_parameters::cos_phi0, get_mi_vector(), ParticlePosition::p, Bonded_ia_parameters::p, Angle_bond_parameters::phi0, Particle::r, scalar(), Angle_bond_parameters::sin_phi0, SQR(), sqrlen(), and TINY_COS_VALUE.
Referenced by add_bonded_energy().
int angle_set_params (int bond_type, double bend, double phi0)
set parameters for the angle potential.
Todo:
The type of the angle potential is chosen via config.hpp and cannot be changed at runtime.
Todo:
The type of the angle potential is chosen via config.hpp and cannot be changed at runtime.
Definition at line 35 of file angle.cpp.
References Bond_parameters::angle, Angle_bond_parameters::bend, BONDED_IA_ANGLE_OLD, bonded_ia_params, Angle_bond_parameters::cos_phi0, ES_ERROR, ES_OK, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Angle_bond_parameters::phi0, Angle_bond_parameters::sin_phi0, and Bonded_ia_parameters::type.
void calc_angle_3body_forces (Particle * p_mid, Particle * p_left, Particle * p_right, Bonded_ia_parameters * iaparams, double force1[3], double force2[3], double force3[3]) inline
Definition at line 107 of file angle.hpp.
References Bond_parameters::angle, Angle_bond_parameters::bend, Angle_bond_parameters::cos_phi0, get_mi_vector(), ParticlePosition::p, Bonded_ia_parameters::p, Angle_bond_parameters::phi0, Particle::r, scalar(), Angle_bond_parameters::sin_phi0, SQR(), sqrlen(), and TINY_COS_VALUE.
Referenced by calc_three_body_bonded_forces().
int calc_angle_force (Particle * p_mid, Particle * p_left, Particle * p_right, Bonded_ia_parameters * iaparams, double force1[3], double force2[3]) inline
Computes the three body angle interaction force and adds this force to the particle forces (see tclcommand_inter).
Parameters
p_mid Pointer to second/middle particle.
p_left Pointer to first/left particle.
p_right Pointer to third/right particle.
iaparams bond type number of the angle interaction (see tclcommand_inter).
force1 returns force of particle 1
force2 returns force of particle 2
Returns
0
Definition at line 55 of file angle.hpp.
References Bond_parameters::angle, Angle_bond_parameters::bend, Angle_bond_parameters::cos_phi0, get_mi_vector(), ParticlePosition::p, Bonded_ia_parameters::p, Angle_bond_parameters::phi0, Particle::r, scalar(), Angle_bond_parameters::sin_phi0, SQR(), sqrlen(), TINY_COS_VALUE, and TINY_SIN_VALUE.
Referenced by add_bonded_force().