ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: angledist_tcl.cpp File Reference
angledist_tcl.cpp File Reference
Implementation of angledist_tcl.hpp.
#include "angledist_tcl.hpp"
#include "angledist.hpp"
Functions
int tclcommand_inter_parse_angledist (Tcl_Interp *interp, int bond_type, int argc, char **argv)
parse parameters for the angle potential
int tclprint_to_result_angledistIA (Tcl_Interp *interp, Bonded_ia_parameters *params)
Detailed Description
Implementation of angledist_tcl.hpp.
Definition in file angledist_tcl.cpp.
Function Documentation
int tclcommand_inter_parse_angledist (Tcl_Interp * interp, int bond_type, int argc, char ** argv)
parse parameters for the angle potential
Definition at line 30 of file angledist_tcl.cpp.
References angledist_set_params(), ARG_IS_D, and CHECK_VALUE.
Referenced by tclcommand_inter_parse_bonded().
int tclprint_to_result_angledistIA (Tcl_Interp * interp, Bonded_ia_parameters * params)
Definition at line 75 of file angledist_tcl.cpp.
References Bond_parameters::angledist, Angledist_bond_parameters::bend, Angledist_bond_parameters::distmax, Angledist_bond_parameters::distmin, Bonded_ia_parameters::p, Angledist_bond_parameters::phimax, and Angledist_bond_parameters::phimin.
Referenced by tclprint_to_result_BondedIA().