ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: area_force_global_tcl.hpp File Reference
area_force_global_tcl.hpp File Reference
#include "tcl/parser.hpp"
#include "interaction_data.hpp"
Functions
int tclprint_to_result_areaforceglobalIA (Tcl_Interp *interp, Bonded_ia_parameters *params)
int tclcommand_inter_parse_area_force_global (Tcl_Interp *interp, int bond_type, int argc, char **argv)
parse parameters for the area_force_global potential
Function Documentation
int tclcommand_inter_parse_area_force_global (Tcl_Interp * interp, int bond_type, int argc, char ** argv)
parse parameters for the area_force_global potential
Definition at line 42 of file area_force_global_tcl.cpp.
References area_force_global_set_params(), ARG_IS_D, and CHECK_VALUE.
Referenced by tclcommand_inter_parse_bonded().
int tclprint_to_result_areaforceglobalIA (Tcl_Interp * interp, Bonded_ia_parameters * params)
Definition at line 31 of file area_force_global_tcl.cpp.
References Area_force_global_bond_parameters::A0_g, Bond_parameters::area_force_global, Area_force_global_bond_parameters::ka_g, and Bonded_ia_parameters::p.
Referenced by tclprint_to_result_BondedIA().