ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: area_force_global.hpp File Reference
area_force_global.hpp File Reference
Routines to calculate the AREA_FORCE_GLOBAL energy or/and and force for a particle triple (triangle from mesh).
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "cells.hpp"
#include "lb.hpp"
#include "grid.hpp"
#include "errorhandling.hpp"
Functions
int area_force_global_set_params (int bond_type, double A0_g, double ka_g)
set parameters for the AREA_FORCE_GLOBAL potential.
void calc_area_global (double *area, int molType)
called in force_calc() from within forces.cpp calculates the global area for a cell before the forces are handled sums up parts for area with mpi_reduce from local triangles synchronization with allreduce
void add_area_global_force (double area, int molType)
Detailed Description
Routines to calculate the AREA_FORCE_GLOBAL energy or/and and force for a particle triple (triangle from mesh).
(Dupin2007) forces.cpp
Definition in file area_force_global.hpp.
Function Documentation
void add_area_global_force (double area, int molType) inline
loop over particles
Definition at line 165 of file area_force_global.hpp.
References Area_force_global_bond_parameters::A0_g, Bond_parameters::area_force_global, Particle::bl, BONDED_IA_AREA_FORCE_GLOBAL, bonded_ia_params, CellPList::cell, IntList::e, ParticleForce::f, Particle::f, get_mi_vector(), ParticleLocal::ghost, i, ParticleLocal::i, ParticleProperties::identity, Area_force_global_bond_parameters::ka_g, Particle::l, local_cells, local_particles, IntList::max, ParticleProperties::mol_id, IntList::n, CellPList::n, ParticleList::n, normr(), Bonded_ia_parameters::num, ParticlePosition::p, Particle::p, Bonded_ia_parameters::p, ParticleList::part, Particle::r, runtimeError, Bonded_ia_parameters::type, unfold_position(), and vecsub().
Referenced by force_calc().
int area_force_global_set_params (int bond_type, double A0_g, double ka_g)
set parameters for the AREA_FORCE_GLOBAL potential.
Definition at line 32 of file area_force_global.cpp.
References Area_force_global_bond_parameters::A0_g, Bond_parameters::area_force_global, BONDED_IA_AREA_FORCE_GLOBAL, bonded_ia_params, ES_ERROR, ES_OK, Area_force_global_bond_parameters::ka_g, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_area_force_global().
void calc_area_global (double * area, int molType) inline
called in force_calc() from within forces.cpp calculates the global area for a cell before the forces are handled sums up parts for area with mpi_reduce from local triangles synchronization with allreduce
!!! loop over particles from domain_decomposition !!!
loop over particles
Definition at line 49 of file area_force_global.hpp.
References area_triangle(), Particle::bl, BONDED_IA_AREA_FORCE_GLOBAL, bonded_ia_params, CellPList::cell, IntList::e, get_mi_vector(), ParticleLocal::ghost, i, ParticleLocal::i, ParticleProperties::identity, Particle::l, local_cells, local_particles, IntList::max, ParticleProperties::mol_id, MPI_Allreduce(), MPI_COMM_WORLD, MPI_DOUBLE, MPI_SUM, IntList::n, CellPList::n, ParticleList::n, Bonded_ia_parameters::num, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, runtimeError, Bonded_ia_parameters::type, and unfold_position().
Referenced by force_calc().