ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: bending_force.hpp File Reference
bending_force.hpp File Reference
Routines to calculate the bending_force energy or/and and force for a particle quadruple (two triangles that have 2 particles in common)
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "grid.hpp"
Functions
int bending_force_set_params (int bond_type, double phi0, double kb)
set bending_force parameters
int calc_bending_force (Particle *p2, Particle *p1, Particle *p3, Particle *p4, Bonded_ia_parameters *iaparams, double force1[3], double force2[2])
Computes the bending force (Dupin2007 eqn.
Detailed Description
Routines to calculate the bending_force energy or/and and force for a particle quadruple (two triangles that have 2 particles in common)
Definition in file bending_force.hpp.
Function Documentation
int bending_force_set_params (int bond_type, double phi0, double kb)
set bending_force parameters
Definition at line 28 of file bending_force.cpp.
References Bond_parameters::bending_force, BONDED_IA_BENDING_FORCE, bonded_ia_params, ES_ERROR, ES_OK, Bending_force_bond_parameters::kb, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Bending_force_bond_parameters::phi0, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_bending_force().
int calc_bending_force (Particle * p2, Particle * p1, Particle * p3, Particle * p4, Bonded_ia_parameters * iaparams, double force1[3], double force2[2]) inline
Computes the bending force (Dupin2007 eqn.
20 and 21) and adds this force to the particle forces (see tclcommand_inter).
Parameters
p1,p2,p3 Pointers to particles of triangle 1.
p2,p3,p4 Pointers to particles of triangle 2. (triangles have particles p2 and p3 in common)
iaparams bending stiffness kb, initial rest angle phi0 (see tclcommand_inter).
force1 returns force on particles of triangle 1
force2 returns force on particles of triangle 2 (p1 += force1; p2 += 0.5*force1+0.5*force2; p3 += 0.5*force1+0.5*force2; p4 += force2;
Returns
0
Definition at line 44 of file bending_force.hpp.
References angle_btw_triangles(), Bond_parameters::bending_force, get_mi_vector(), get_n_triangle(), ParticleLocal::ghost, i, ParticleLocal::i, Bending_force_bond_parameters::kb, Particle::l, M_PI, normr(), ParticlePosition::p, Bonded_ia_parameters::p, Bending_force_bond_parameters::phi0, Particle::r, and unfold_position().
Referenced by add_bonded_force().