ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: bin_tcl.cpp File Reference
bin_tcl.cpp File Reference
#include "utils.hpp"
#include "parser.hpp"
#include <strings.h>
Functions
static void setup_linear_bins (DoubleList *dl, double min_bin, double max_bin, int bins)
static void setup_log_bins (DoubleList *dl, double min_bin, double max_bin, int bins)
int tclcommand_bin (ClientData cdata, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl command bin, which can be used to bin data into arbitrary bins.
Function Documentation
static void setup_linear_bins (DoubleList * dl, double min_bin, double max_bin, int bins) static
Definition at line 25 of file bin_tcl.cpp.
References DoubleList::e, i, DoubleList::n, and realloc_doublelist().
Referenced by tclcommand_bin().
static void setup_log_bins (DoubleList * dl, double min_bin, double max_bin, int bins) static
Definition at line 33 of file bin_tcl.cpp.
References DoubleList::e, i, DoubleList::n, and realloc_doublelist().
Referenced by tclcommand_bin().
int tclcommand_bin (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl command bin, which can be used to bin data into arbitrary bins.
See bin_tcl.cpp
Definition at line 41 of file bin_tcl.cpp.
References alloc_doublelist(), ARG1_IS_DOUBLELIST, ARG1_IS_S, ARG_IS_D, ARG_IS_DOUBLELIST, ARG_IS_I, DoubleList::e, i, init_doublelist(), DoubleList::n, realloc_doublelist(), setup_linear_bins(), and setup_log_bins().
Referenced by tcl_register_commands().