ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: binary_file_tcl.cpp File Reference
binary_file_tcl.cpp File Reference
Implementation of binary_file_tcl.h.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "utils.hpp"
#include "binary_file_tcl.hpp"
#include "global.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "interaction_data.hpp"
Functions
int tclcommand_writemd (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implements the writemd Tcl command.
int tclcommand_readmd (ClientData dummy, Tcl_Interp *interp, int argc, char **argv)
Implements the readmd Tcl command.
Detailed Description
Implementation of binary_file_tcl.h.
Definition in file binary_file_tcl.cpp.
Function Documentation
int tclcommand_readmd (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implements the readmd Tcl command.
Note that for reading in new particles, all three position fields are mandatory. It doesn't matter where they are put, readmd searches for them. readmd also takes care to initialize the particle_node map and the node_grid, if necessary.
Definition at line 191 of file binary_file_tcl.cpp.
References build_particle_node(), free, FX, FY, FZ, i, MDHeader::magic, malloc, MASSES, max_seen_particle, MDMAGIC, MX, MY, MZ, MDHeader::n_rows, particle_node, place_particle(), POSX, POSY, POSZ, Q, set_particle_dip(), set_particle_f(), set_particle_mass(), set_particle_q(), set_particle_solvation(), set_particle_type(), set_particle_v(), SOLVATION, TYPE, VX, VY, and VZ.
Referenced by tcl_register_commands().
int tclcommand_writemd (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implements the writemd Tcl command.
The first argument gives the channel to write to, all subsequent arguments give the fields to write. The order of the data in the file is given by the argument order. The names of the field are the same as above in lowercase.
Definition at line 34 of file binary_file_tcl.cpp.
References build_particle_node(), ParticlePosition::dip, ES_OK, ParticleForce::f, Particle::f, free, free_particle(), FX, FY, FZ, get_particle_data(), i, ParticleLocal::i, Particle::l, Particle::m, MDHeader::magic, malloc, ParticleProperties::mass, MASSES, max_seen_particle, MDMAGIC, MX, MY, MZ, MDHeader::n_rows, ParticlePosition::p, Particle::p, particle_node, POSX, POSY, POSZ, Q, ParticleProperties::q, Particle::r, ParticleProperties::type, TYPE, unfold_position(), ParticleMomentum::v, VX, VY, and VZ.
Referenced by tcl_register_commands().