ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: bonded_coulomb.hpp File Reference
bonded_coulomb.hpp File Reference
Routines to calculate the BONDED_COULOMB Energy or/and BONDED_COULOMB force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
Functions
int bonded_coulomb_set_params (int bond_type, double prefactor)
set the parameters for the bonded_coulomb potential
int calc_bonded_coulomb_pair_force (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double force[3])
Computes the BONDED_COULOMB pair force and adds this force to the particle forces (see interaction_data.cpp).
int bonded_coulomb_pair_energy (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double *_energy)
Detailed Description
Routines to calculate the BONDED_COULOMB Energy or/and BONDED_COULOMB force for a particle pair.
forces.cpp
Definition in file bonded_coulomb.hpp.
Function Documentation
int bonded_coulomb_pair_energy (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double * _energy) inline
Definition at line 66 of file bonded_coulomb.hpp.
References Bond_parameters::bonded_coulomb, Particle::p, Bonded_ia_parameters::p, Bonded_coulomb_bond_parameters::prefactor, ParticleProperties::q, and sqrlen().
Referenced by add_bonded_energy().
int bonded_coulomb_set_params (int bond_type, double prefactor)
set the parameters for the bonded_coulomb potential
Definition at line 30 of file bonded_coulomb.cpp.
References Bond_parameters::bonded_coulomb, BONDED_IA_BONDED_COULOMB, bonded_ia_params, ES_ERROR, ES_OK, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Bonded_coulomb_bond_parameters::prefactor, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_bonded_coulomb().
int calc_bonded_coulomb_pair_force (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double force[3]) inline
Computes the BONDED_COULOMB pair force and adds this force to the particle forces (see interaction_data.cpp).
Parameters
p1 Pointer to first particle.
p2 Pointer to second/middle particle.
iaparams bond type number of the angle interaction (see interaction_data.cpp).
dx particle distance vector
force returns force of particle 1
Returns
0.
Definition at line 49 of file bonded_coulomb.hpp.
References Bond_parameters::bonded_coulomb, check_id, ParticleForce::f, Particle::f, i, ParticleProperties::identity, ONEPART_TRACE, Particle::p, Bonded_ia_parameters::p, Bonded_coulomb_bond_parameters::prefactor, ParticleProperties::q, sqrlen(), and this_node.
Referenced by add_bonded_force().