ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: buckingham.hpp File Reference
buckingham.hpp File Reference
Routines to calculate the Buckingham energy and/or force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "mol_cut.hpp"
#include "forcecap.hpp"
Functions
int buckingham_set_params (int part_type_a, int part_type_b, double A, double B, double C, double D, double cut, double discont, double shift, double cap_radius, double F1, double F2)
void calc_buck_cap_radii ()
calculate buck_capradius from force_cap
double buck_force_r (double A, double B, double C, double D, double r)
Resultant Force due to a buckingham potential between two particles at interatomic separation r greater than or equal to discont.
double buck_energy_r (double A, double B, double C, double D, double shift, double r)
Potential Energy due to a buckingham potential between two particles at interatomic separation r greater than or equal to discont.
void add_buck_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double force[3])
Calculate Buckingham force between particle p1 and p2 and add it to their force.
double buck_pair_energy (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist)
calculate Buckingham energy between particle p1 and p2.
Detailed Description
Routines to calculate the Buckingham energy and/or force for a particle pair.
forces.cpp
Definition in file buckingham.hpp.
Function Documentation
void add_buck_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double force[3]) inline
Calculate Buckingham force between particle p1 and p2 and add it to their force.
Definition at line 57 of file buckingham.hpp.
References IA_parameters::BUCK_A, IA_parameters::BUCK_B, IA_parameters::BUCK_C, IA_parameters::BUCK_capradius, IA_parameters::BUCK_D, IA_parameters::BUCK_discont, IA_parameters::BUCK_F2, buck_force_r(), BUCK_TRACE, check_id, CUTOFF_CHECK, ParticleForce::f, Particle::f, ParticleProperties::identity, ONEPART_TRACE, Particle::p, and this_node.
Referenced by calc_non_bonded_pair_force_parts().
double buck_energy_r (double A, double B, double C, double D, double shift, double r) inline
Potential Energy due to a buckingham potential between two particles at interatomic separation r greater than or equal to discont.
Definition at line 50 of file buckingham.hpp.
Referenced by buck_pair_energy(), and buckingham_set_params().
double buck_force_r (double A, double B, double C, double D, double r) inline
Resultant Force due to a buckingham potential between two particles at interatomic separation r greater than or equal to discont.
Definition at line 45 of file buckingham.hpp.
Referenced by add_buck_pair_force(), and buckingham_set_params().
double buck_pair_energy (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist) inline
calculate Buckingham energy between particle p1 and p2.
Definition at line 113 of file buckingham.hpp.
References IA_parameters::BUCK_A, IA_parameters::BUCK_B, IA_parameters::BUCK_C, IA_parameters::BUCK_capradius, IA_parameters::BUCK_D, IA_parameters::BUCK_discont, buck_energy_r(), IA_parameters::BUCK_F1, IA_parameters::BUCK_F2, IA_parameters::BUCK_shift, and CUTOFF_CHECK.
Referenced by calc_non_bonded_pair_energy().
int buckingham_set_params (int part_type_a, int part_type_b, double A, double B, double C, double D, double cut, double discont, double shift, double cap_radius, double F1, double F2)
Definition at line 30 of file buckingham.cpp.
References IA_parameters::BUCK_A, IA_parameters::BUCK_B, IA_parameters::BUCK_C, IA_parameters::BUCK_capradius, IA_parameters::BUCK_cut, IA_parameters::BUCK_D, IA_parameters::BUCK_discont, buck_energy_r(), IA_parameters::BUCK_F1, IA_parameters::BUCK_F2, buck_force_r(), IA_parameters::BUCK_shift, ES_ERROR, ES_OK, force_cap, get_ia_param_safe(), mpi_bcast_ia_params(), and mpi_cap_forces().
Referenced by tclcommand_inter_parse_buckingham().
void calc_buck_cap_radii ()
calculate buck_capradius from force_cap
Definition at line 68 of file buckingham.cpp.
References IA_parameters::BUCK_A, IA_parameters::BUCK_B, IA_parameters::BUCK_C, IA_parameters::BUCK_capradius, IA_parameters::BUCK_cut, IA_parameters::BUCK_D, IA_parameters::BUCK_discont, IA_parameters::BUCK_F2, BUCK_TRACE, errexit(), force_cap, FORCE_TRACE, get_ia_param(), i, n_particle_types, params, SQR(), and this_node.
Referenced by mpi_cap_forces_slave().