ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: cells_tcl.hpp File Reference
cells_tcl.hpp File Reference
#include "parser.hpp"
Functions
Exported Functions
int tclcommand_cellsystem (ClientData data, Tcl_Interp *interp, int argc, char **argv)
implementation of the Tcl command cellsystem.
int tclcommand_sort_particles (ClientData data, Tcl_Interp *interp, int argc, char **argv)
implementation of the Tcl command sort_particles.
Function Documentation
int tclcommand_cellsystem (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
implementation of the Tcl command cellsystem.
See cells_tcl.cpp
by default use verlet list
Definition at line 42 of file cells_tcl.cpp.
References ARG1_IS_S, ARG_IS_I, ARG_IS_S, CELL_STRUCTURE_DOMDEC, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, dd, determine_n_layers, err, FIELD_NODEGRID, gather_runtime_errors(), mpi_bcast_cell_structure(), mpi_bcast_parameter(), n_layers, n_nodes, node_grid, and DomainDecomposition::use_vList.
Referenced by tcl_register_commands().
int tclcommand_sort_particles (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
implementation of the Tcl command sort_particles.
See cells_tcl.cpp
Definition at line 37 of file cells_tcl.cpp.
References mpi_bcast_event(), and SORT_PARTICLES.
Referenced by tcl_register_commands().