ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: EwaldgpuForce Class Reference
EwaldgpuForce Class Reference
#include <EwaldgpuForce.hpp>
Public Member Functions
EwaldgpuForce (SystemInterface &s, double r_cut, int num_kx, int num_ky, int num_kz, double alpha)
~EwaldgpuForce ()
void setup (SystemInterface &s)
void computeForces (SystemInterface &s)
void computeEnergy (SystemInterface &s)
int set_params (double rcut, int num_kx, int num_ky, int num_kz, double alpha)
int set_params_tune (double accuracy, double precision, int K_max, int time_calc_steps)
int adaptive_tune (char **log, SystemInterface &s)
double error_estimate_r (double q_sqr, int N, double r_cut, double V, double alpha, double accuracy) const
double error_estimate_k (double q_sqr, int N, int K, double V, double alpha, double accuracy) const
double tune_alpha (double accuracy, double precision, int K, double V, double q_sqr, int N)
double tune_rcut (double accuracy, double precision, double alpha, double V, double q_sqr, int N)
int determine_calc_time_steps ()
double compute_E_error_estimate_r (double alpha, double rcut, double q_sqr, double box_l[3])
double compute_E_error_estimate_k (double alpha, int num_kx, int num_ky, int num_kz, double q_sqr, double box_l[3])
double E_estimate_error (double rcut, int num_kx, int num_ky, int num_kz, double alpha, double q_sqr, double box_l[3])
double compute_optimal_alpha (double rcut, int num_kx, int num_ky, int num_kz, double q_sqr, double box_l[3], double precision)
double compute_q_sqare (Particle *particle)
Public Member Functions inherited from Actor
virtual void computeTorques (SystemInterface &s)
virtual ~Actor ()
Protected Member Functions
void compute_num_k ()
void compute_k_AND_influence_factor ()
void GPU_Forces (SystemInterface &s)
void GPU_Energy (SystemInterface &s)
void GPU_q_sqr (SystemInterface &s)
int nextPow2 (int x)
bool isPow2 (int x)
void getNumBlocksAndThreads (int Size, int maxBlocks, int maxThreads, int &blocks, int &threads)
void Output ()
void EwaldCPU_EnergySelf ()
Protected Attributes
double m_box_l [3]
double m_V
double m_coulomb_prefactor
int m_N
ewaldgpu_real * m_k
ewaldgpu_real * m_dev_k
ewaldgpu_real * m_forces_reci
ewaldgpu_real * m_dev_forces_reci
ewaldgpu_real * m_infl_factor
ewaldgpu_real * m_dev_infl_factor
ewaldgpu_real * m_rho_hat
ewaldgpu_real * m_dev_rho_hat
ewaldgpu_real * m_energy_reci
ewaldgpu_real * m_dev_energy_reci
ewaldgpu_real * m_q_sqr
ewaldgpu_real * m_dev_q_sqr
ewaldgpu_real m_energy_self
ewaldgpu_real m_energy_tot
double m_alpha
double m_rcut
int m_num_kx
int m_num_ky
int m_num_kz
int m_num_k
bool m_isTuned
SystemInterface * System
Detailed Description
Definition at line 34 of file EwaldgpuForce.hpp.
Constructor & Destructor Documentation
EwaldgpuForce::EwaldgpuForce (SystemInterface & s, double r_cut, int num_kx, int num_ky, int num_kz, double alpha)
Definition at line 517 of file EwaldgpuForce_cuda.cu.
References compute_num_k(), determine_calc_time_steps(), m_alpha, m_isTuned, m_num_kx, m_num_ky, m_num_kz, m_rcut, SystemInterface::requestFGpu(), SystemInterface::requestQGpu(), SystemInterface::requestRGpu(), set_params(), and Ewaldgpu_params::time_calc_steps.
EwaldgpuForce::~EwaldgpuForce ()
Definition at line 544 of file EwaldgpuForce_cuda.cu.
References HANDLE_ERROR, m_dev_energy_reci, m_dev_forces_reci, m_dev_infl_factor, m_dev_k, m_dev_q_sqr, m_dev_rho_hat, m_energy_reci, m_forces_reci, m_infl_factor, m_k, m_q_sqr, and m_rho_hat.
Member Function Documentation
int EwaldgpuForce::adaptive_tune (char ** log, SystemInterface & s)
Definition at line 102 of file EwaldgpuForce.cpp.
References Ewaldgpu_params::accuracy, Ewaldgpu_params::alpha, box_l, compute_q_sqare(), ES_DOUBLE_SPACE, ES_ERROR, ES_INTEGER_SPACE, ES_OK, Ewaldgpu_params::isTuned, Ewaldgpu_params::K_max, malloc, mpi_bcast_coulomb_params(), mpi_get_particles(), n_part, Ewaldgpu_params::num_kx, Ewaldgpu_params::num_ky, Ewaldgpu_params::num_kz, Ewaldgpu_params::precision, Ewaldgpu_params::rcut, set_params(), skin, strcat_alloc(), Ewaldgpu_params::time_calc_steps, time_force_calc(), tune_alpha(), and tune_rcut().
Referenced by tclcommand_inter_coulomb_parse_ewaldgpu_tune().
double EwaldgpuForce::compute_E_error_estimate_k (double alpha, int num_kx, int num_ky, int num_kz, double q_sqr, double box_l[3])
Definition at line 289 of file EwaldgpuForce.cpp.
References M_PI, and SQR().
Referenced by compute_optimal_alpha(), and E_estimate_error().
double EwaldgpuForce::compute_E_error_estimate_r (double alpha, double rcut, double q_sqr, double box_l[3])
Definition at line 281 of file EwaldgpuForce.cpp.
References SQR().
Referenced by compute_optimal_alpha(), and E_estimate_error().
void EwaldgpuForce::compute_k_AND_influence_factor () protected
Definition at line 42 of file EwaldgpuForce.cpp.
References Index, iy, m_alpha, m_box_l, m_infl_factor, m_k, m_num_k, m_num_kx, m_num_ky, m_num_kz, M_PI, m_V, and SQR().
Referenced by setup().
void EwaldgpuForce::compute_num_k () protected
Definition at line 19 of file EwaldgpuForce.cpp.
References Index, iy, m_num_k, m_num_kx, m_num_ky, m_num_kz, and SQR().
Referenced by EwaldgpuForce(), and setup().
double EwaldgpuForce::compute_optimal_alpha (double rcut, int num_kx, int num_ky, int num_kz, double q_sqr, double box_l[3], double precision)
Definition at line 301 of file EwaldgpuForce.cpp.
References compute_E_error_estimate_k(), and compute_E_error_estimate_r().
Referenced by tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha().
double EwaldgpuForce::compute_q_sqare (Particle * particle)
Definition at line 336 of file EwaldgpuForce.cpp.
References i, n_part, and SQR().
Referenced by adaptive_tune(), and tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha().
void EwaldgpuForce::computeEnergy (SystemInterface & s) virtual
Reimplemented from Actor.
Definition at line 673 of file EwaldgpuForce_cuda.cu.
References SystemInterface::box(), coulomb, COULOMB_EWALD_GPU, SystemInterface::eGpu(), EwaldCPU_EnergySelf(), GPU_Energy(), HANDLE_ERROR, m_box_l, m_dev_energy_reci, m_energy_reci, m_energy_self, m_energy_tot, Coulomb_parameters::method, and setup().
void EwaldgpuForce::computeForces (SystemInterface & s) virtual
Reimplemented from Actor.
Definition at line 655 of file EwaldgpuForce_cuda.cu.
References SystemInterface::box(), coulomb, COULOMB_EWALD_GPU, GPU_Forces(), HANDLE_ERROR, m_box_l, m_dev_rho_hat, m_num_k, Coulomb_parameters::method, and setup().
int EwaldgpuForce::determine_calc_time_steps ()
Definition at line 256 of file EwaldgpuForce.cpp.
References CellPList::cell, i, local_cells, CellPList::n, ParticleList::n, and ParticleList::part.
Referenced by EwaldgpuForce().
double EwaldgpuForce::E_estimate_error (double rcut, int num_kx, int num_ky, int num_kz, double alpha, double q_sqr, double box_l[3])
Definition at line 296 of file EwaldgpuForce.cpp.
References compute_E_error_estimate_k(), and compute_E_error_estimate_r().
double EwaldgpuForce::error_estimate_k (double q_sqr, int N, int K, double V, double alpha, double accuracy) const inline
Definition at line 189 of file EwaldgpuForce.cpp.
References M_PI.
Referenced by tune_alpha().
double EwaldgpuForce::error_estimate_r (double q_sqr, int N, double r_cut, double V, double alpha, double accuracy) const inline
Definition at line 184 of file EwaldgpuForce.cpp.
Referenced by tune_rcut().
void EwaldgpuForce::EwaldCPU_EnergySelf () protected
Definition at line 75 of file EwaldgpuForce.cpp.
References coulomb, m_alpha, m_energy_self, M_PI, m_q_sqr, and Coulomb_parameters::prefactor.
Referenced by computeEnergy().
void EwaldgpuForce::getNumBlocksAndThreads (int Size, int maxBlocks, int maxThreads, int & blocks, int & threads) protected
Definition at line 1092 of file EwaldgpuForce_cuda.cu.
References HANDLE_ERROR, and nextPow2().
Referenced by GPU_Energy(), GPU_Forces(), and GPU_q_sqr().
void EwaldgpuForce::GPU_Energy (SystemInterface & s) protected
Definition at line 870 of file EwaldgpuForce_cuda.cu.
References coulomb, cuda_check_error(), SystemInterface::eGpu(), getNumBlocksAndThreads(), HANDLE_ERROR, isPow2(), m_coulomb_prefactor, m_dev_infl_factor, m_dev_rho_hat, m_energy_reci, m_N, m_num_k, m_V, and stream0.
Referenced by computeEnergy().
void EwaldgpuForce::GPU_Forces (SystemInterface & s) protected
Definition at line 700 of file EwaldgpuForce_cuda.cu.
References cuda_check_error(), SystemInterface::fGpuBegin(), getNumBlocksAndThreads(), HANDLE_ERROR, isPow2(), m_coulomb_prefactor, m_dev_infl_factor, m_dev_k, m_dev_rho_hat, m_N, m_num_k, m_rho_hat, m_V, SystemInterface::qGpuBegin(), SystemInterface::rGpuBegin(), and stream0.
Referenced by computeForces().
void EwaldgpuForce::GPU_q_sqr (SystemInterface & s) protected
Definition at line 972 of file EwaldgpuForce_cuda.cu.
References cuda_check_error(), getNumBlocksAndThreads(), HANDLE_ERROR, isPow2(), m_dev_q_sqr, m_N, m_q_sqr, SystemInterface::qGpuBegin(), and stream0.
Referenced by setup().
bool EwaldgpuForce::isPow2 (int x) protected
Definition at line 1087 of file EwaldgpuForce_cuda.cu.
Referenced by GPU_Energy(), GPU_Forces(), and GPU_q_sqr().
int EwaldgpuForce::nextPow2 (int x) protected
Definition at line 1077 of file EwaldgpuForce_cuda.cu.
Referenced by getNumBlocksAndThreads().
void EwaldgpuForce::Output () protected
int EwaldgpuForce::set_params (double rcut, int num_kx, int num_ky, int num_kz, double alpha)
Definition at line 81 of file EwaldgpuForce.cpp.
References Ewaldgpu_params::alpha, Ewaldgpu_params::num_kx, Ewaldgpu_params::num_ky, Ewaldgpu_params::num_kz, and Ewaldgpu_params::rcut.
Referenced by adaptive_tune(), EwaldgpuForce(), setup(), and tclcommand_inter_coulomb_parse_ewaldgpu_notune().
int EwaldgpuForce::set_params_tune (double accuracy, double precision, int K_max, int time_calc_steps)
Definition at line 91 of file EwaldgpuForce.cpp.
References Ewaldgpu_params::accuracy, Ewaldgpu_params::K_max, Ewaldgpu_params::precision, and Ewaldgpu_params::time_calc_steps.
Referenced by tclcommand_inter_coulomb_parse_ewaldgpu_tune().
void EwaldgpuForce::setup (SystemInterface & s)
Definition at line 567 of file EwaldgpuForce_cuda.cu.
References Ewaldgpu_params::alpha, SystemInterface::box(), compute_k_AND_influence_factor(), compute_num_k(), coulomb, GPU_q_sqr(), HANDLE_ERROR, Ewaldgpu_params::isTuned, Ewaldgpu_params::isTunedFlag, m_alpha, m_box_l, m_coulomb_prefactor, m_dev_energy_reci, m_dev_infl_factor, m_dev_k, m_dev_q_sqr, m_dev_rho_hat, m_energy_reci, m_infl_factor, m_k, m_N, m_num_k, m_num_kx, m_num_ky, m_num_kz, m_q_sqr, m_rcut, m_rho_hat, m_V, malloc, SystemInterface::npart_gpu(), Ewaldgpu_params::num_kx, Ewaldgpu_params::num_ky, Ewaldgpu_params::num_kz, Coulomb_parameters::prefactor, Ewaldgpu_params::rcut, set_params(), start, stop, and stream0.
Referenced by computeEnergy(), and computeForces().
double EwaldgpuForce::tune_alpha (double accuracy, double precision, int K, double V, double q_sqr, int N)
Definition at line 194 of file EwaldgpuForce.cpp.
References error_estimate_k().
Referenced by adaptive_tune().
double EwaldgpuForce::tune_rcut (double accuracy, double precision, double alpha, double V, double q_sqr, int N)
Definition at line 227 of file EwaldgpuForce.cpp.
References box_l, and error_estimate_r().
Referenced by adaptive_tune().
Field Documentation
double EwaldgpuForce::m_alpha protected
Definition at line 79 of file EwaldgpuForce.hpp.
Referenced by compute_k_AND_influence_factor(), EwaldCPU_EnergySelf(), EwaldgpuForce(), and setup().
double EwaldgpuForce::m_box_l[3] protected
Definition at line 60 of file EwaldgpuForce.hpp.
Referenced by compute_k_AND_influence_factor(), computeEnergy(), computeForces(), and setup().
double EwaldgpuForce::m_coulomb_prefactor protected
Definition at line 62 of file EwaldgpuForce.hpp.
Referenced by GPU_Energy(), GPU_Forces(), and setup().
ewaldgpu_real* EwaldgpuForce::m_dev_energy_reci protected
Definition at line 73 of file EwaldgpuForce.hpp.
Referenced by computeEnergy(), setup(), and ~EwaldgpuForce().
ewaldgpu_real* EwaldgpuForce::m_dev_forces_reci protected
Definition at line 67 of file EwaldgpuForce.hpp.
Referenced by ~EwaldgpuForce().
ewaldgpu_real* EwaldgpuForce::m_dev_infl_factor protected
Definition at line 69 of file EwaldgpuForce.hpp.
Referenced by GPU_Energy(), GPU_Forces(), setup(), and ~EwaldgpuForce().
ewaldgpu_real* EwaldgpuForce::m_dev_k protected
Definition at line 65 of file EwaldgpuForce.hpp.
Referenced by GPU_Forces(), setup(), and ~EwaldgpuForce().
ewaldgpu_real* EwaldgpuForce::m_dev_q_sqr protected
Definition at line 75 of file EwaldgpuForce.hpp.
Referenced by GPU_q_sqr(), setup(), and ~EwaldgpuForce().
ewaldgpu_real* EwaldgpuForce::m_dev_rho_hat protected
Definition at line 71 of file EwaldgpuForce.hpp.
Referenced by computeForces(), GPU_Energy(), GPU_Forces(), setup(), and ~EwaldgpuForce().
ewaldgpu_real* EwaldgpuForce::m_energy_reci protected
Definition at line 72 of file EwaldgpuForce.hpp.
Referenced by computeEnergy(), GPU_Energy(), setup(), and ~EwaldgpuForce().
ewaldgpu_real EwaldgpuForce::m_energy_self protected
Definition at line 76 of file EwaldgpuForce.hpp.
Referenced by computeEnergy(), and EwaldCPU_EnergySelf().
ewaldgpu_real EwaldgpuForce::m_energy_tot protected
Definition at line 77 of file EwaldgpuForce.hpp.
Referenced by computeEnergy().
ewaldgpu_real* EwaldgpuForce::m_forces_reci protected
Definition at line 66 of file EwaldgpuForce.hpp.
Referenced by ~EwaldgpuForce().
ewaldgpu_real* EwaldgpuForce::m_infl_factor protected
Definition at line 68 of file EwaldgpuForce.hpp.
Referenced by compute_k_AND_influence_factor(), setup(), and ~EwaldgpuForce().
bool EwaldgpuForce::m_isTuned protected
Definition at line 85 of file EwaldgpuForce.hpp.
Referenced by EwaldgpuForce().
ewaldgpu_real* EwaldgpuForce::m_k protected
Definition at line 64 of file EwaldgpuForce.hpp.
Referenced by compute_k_AND_influence_factor(), setup(), and ~EwaldgpuForce().
int EwaldgpuForce::m_N protected
Definition at line 63 of file EwaldgpuForce.hpp.
Referenced by GPU_Energy(), GPU_Forces(), GPU_q_sqr(), and setup().
int EwaldgpuForce::m_num_k protected
Definition at line 81 of file EwaldgpuForce.hpp.
Referenced by compute_k_AND_influence_factor(), compute_num_k(), computeForces(), GPU_Energy(), GPU_Forces(), and setup().
int EwaldgpuForce::m_num_kx protected
Definition at line 81 of file EwaldgpuForce.hpp.
Referenced by compute_k_AND_influence_factor(), compute_num_k(), EwaldgpuForce(), and setup().
int EwaldgpuForce::m_num_ky protected
Definition at line 81 of file EwaldgpuForce.hpp.
Referenced by compute_k_AND_influence_factor(), compute_num_k(), EwaldgpuForce(), and setup().
int EwaldgpuForce::m_num_kz protected
Definition at line 81 of file EwaldgpuForce.hpp.
Referenced by compute_k_AND_influence_factor(), compute_num_k(), EwaldgpuForce(), and setup().
ewaldgpu_real* EwaldgpuForce::m_q_sqr protected
Definition at line 74 of file EwaldgpuForce.hpp.
Referenced by EwaldCPU_EnergySelf(), GPU_q_sqr(), setup(), and ~EwaldgpuForce().
double EwaldgpuForce::m_rcut protected
Definition at line 80 of file EwaldgpuForce.hpp.
Referenced by EwaldgpuForce(), and setup().
ewaldgpu_real* EwaldgpuForce::m_rho_hat protected
Definition at line 70 of file EwaldgpuForce.hpp.
Referenced by GPU_Forces(), setup(), and ~EwaldgpuForce().
double EwaldgpuForce::m_V protected
Definition at line 61 of file EwaldgpuForce.hpp.
Referenced by compute_k_AND_influence_factor(), GPU_Energy(), GPU_Forces(), and setup().
SystemInterface* EwaldgpuForce::System protected
Definition at line 86 of file EwaldgpuForce.hpp.
The documentation for this class was generated from the following files:
EwaldgpuForce.hpp
EwaldgpuForce.cpp
EwaldgpuForce_cuda.cu