ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: HarmonicOrientationWell Class Reference
HarmonicOrientationWell Class Reference
#include <HarmonicOrientationWell.hpp>
Public Member Functions
HarmonicOrientationWell (float x1, float x2, float x3, float _k, SystemInterface &s)
virtual void computeTorques (SystemInterface &s)
virtual ~HarmonicOrientationWell ()
Public Member Functions inherited from Actor
virtual void computeForces (SystemInterface &s)
virtual void computeEnergy (SystemInterface &s)
virtual ~Actor ()
Protected Attributes
float x
float y
float z
float k
Detailed Description
Definition at line 32 of file HarmonicOrientationWell.hpp.
Constructor & Destructor Documentation
HarmonicOrientationWell::HarmonicOrientationWell (float x1, float x2, float x3, float _k, SystemInterface & s)
Definition at line 26 of file HarmonicOrientationWell.cpp.
References SystemInterface::requestQuatuGpu(), and SystemInterface::requestTorqueGpu().
virtual HarmonicOrientationWell::~HarmonicOrientationWell () inline virtual
Definition at line 40 of file HarmonicOrientationWell.hpp.
Member Function Documentation
virtual void HarmonicOrientationWell::computeTorques (SystemInterface & s) inline virtual
Reimplemented from Actor.
Definition at line 36 of file HarmonicOrientationWell.hpp.
References HarmonicOrientationWell_kernel_wrapper(), k, SystemInterface::npart_gpu(), SystemInterface::quatuGpuBegin(), SystemInterface::torqueGpuBegin(), x, y, and z.
Field Documentation
float HarmonicOrientationWell::k protected
Definition at line 43 of file HarmonicOrientationWell.hpp.
Referenced by computeTorques().
float HarmonicOrientationWell::x protected
Definition at line 42 of file HarmonicOrientationWell.hpp.
Referenced by computeTorques().
float HarmonicOrientationWell::y protected
Definition at line 42 of file HarmonicOrientationWell.hpp.
Referenced by computeTorques().
float HarmonicOrientationWell::z protected
Definition at line 42 of file HarmonicOrientationWell.hpp.
Referenced by computeTorques().
The documentation for this class was generated from the following files:
HarmonicOrientationWell.hpp
HarmonicOrientationWell.cpp