ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: SystemInterface Class Reference
SystemInterface Class Reference abstract
#include <SystemInterface.hpp>
Data Structures
class const_iterator
class const_iterator_stl
class null_real_iterator
class null_vec_iterator
Public Types
typedef Vector3d Vector3
typedef double Real
typedef const_iterator< Vector3 > const_vec_iterator
typedef const_iterator< Real > const_real_iterator
typedef const_iterator< int > const_int_iterator
Public Member Functions
SystemInterface ()
virtual void init ()=0
virtual void update ()=0
virtual const_vec_iterator & rBegin ()
virtual const const_vec_iterator & rEnd ()
virtual bool hasR ()
virtual bool requestR ()
virtual float * rGpuBegin ()
virtual float * rGpuEnd ()
virtual bool hasRGpu ()
virtual bool requestRGpu ()
virtual float * vGpuBegin ()
virtual float * vGpuEnd ()
virtual bool hasVGpu ()
virtual bool requestVGpu ()
virtual float * qGpuBegin ()
virtual float * qGpuEnd ()
virtual bool hasQGpu ()
virtual bool requestQGpu ()
virtual float * fGpuBegin ()
virtual float * fGpuEnd ()
virtual float * eGpu ()
virtual bool hasFGpu ()
virtual bool requestFGpu ()
virtual float * torqueGpuBegin ()
virtual float * torqueGpuEnd ()
virtual bool hasTorqueGpu ()
virtual bool requestTorqueGpu ()
virtual const_real_iterator & qBegin ()
virtual const const_real_iterator & qEnd ()
virtual bool hasQ ()
virtual bool requestQ ()
virtual const_vec_iterator & quatuBegin ()
virtual const const_vec_iterator & quatuEnd ()
virtual bool hasQuatu ()
virtual bool requestQuatu ()
virtual float * quatuGpuBegin ()
virtual float * quatuGpuEnd ()
virtual bool hasQuatuGpu ()
virtual bool requestQuatuGpu ()
virtual unsigned int npart ()=0
virtual unsigned int npart_gpu ()
virtual Vector3 box ()=0
virtual bool needsR ()
virtual bool needsRGpu ()
virtual bool needsQGpu ()
virtual bool needsQ ()
virtual bool needsQuatuGpu ()
virtual bool needsQuatu ()
virtual bool needsFGpu ()
virtual bool needsTorqueGpu ()
Data Fields
null_vec_iterator null_vector
null_real_iterator null_scalar
Protected Attributes
bool m_needsR
bool m_needsV
bool m_needsQ
bool m_needsQuatu
bool m_needsRGpu
bool m_needsVGpu
bool m_needsQGpu
bool m_needsQuatuGpu
bool m_needsFGpu
bool m_needsTorqueGpu
Detailed Description
Todo:
: Turn needsXY in getter/setter
Definition at line 27 of file SystemInterface.hpp.
Member Typedef Documentation
typedef const_iterator<int> SystemInterface::const_int_iterator
Definition at line 108 of file SystemInterface.hpp.
typedef const_iterator<Real> SystemInterface::const_real_iterator
Definition at line 107 of file SystemInterface.hpp.
typedef const_iterator<Vector3> SystemInterface::const_vec_iterator
Definition at line 106 of file SystemInterface.hpp.
typedef double SystemInterface::Real
Definition at line 31 of file SystemInterface.hpp.
typedef Vector3d SystemInterface::Vector3
Definition at line 29 of file SystemInterface.hpp.
Constructor & Destructor Documentation
SystemInterface::SystemInterface () inline
Definition at line 29 of file SystemInterface.hpp.
Member Function Documentation
virtual Vector3 SystemInterface::box () pure virtual
Implemented in EspressoSystemInterface.
Referenced by EwaldgpuForce::computeEnergy(), EwaldgpuForce::computeForces(), EwaldgpuForce::setup(), and Mmm1dgpuForce::setup().
virtual float* SystemInterface::eGpu () inline virtual
Definition at line 132 of file SystemInterface.hpp.
Referenced by Mmm1dgpuForce::computeEnergy(), EwaldgpuForce::computeEnergy(), and EwaldgpuForce::GPU_Energy().
virtual float* SystemInterface::fGpuBegin () inline virtual
Definition at line 130 of file SystemInterface.hpp.
Referenced by Mmm1dgpuForce::computeForces(), and EwaldgpuForce::GPU_Forces().
virtual float* SystemInterface::fGpuEnd () inline virtual
Definition at line 131 of file SystemInterface.hpp.
virtual bool SystemInterface::hasFGpu () inline virtual
Definition at line 133 of file SystemInterface.hpp.
Referenced by requestFGpu().
virtual bool SystemInterface::hasQ () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 143 of file SystemInterface.hpp.
Referenced by requestQ().
virtual bool SystemInterface::hasQGpu () inline virtual
Definition at line 127 of file SystemInterface.hpp.
Referenced by requestQGpu().
virtual bool SystemInterface::hasQuatu () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 148 of file SystemInterface.hpp.
Referenced by requestQuatu().
virtual bool SystemInterface::hasQuatuGpu () inline virtual
Definition at line 153 of file SystemInterface.hpp.
Referenced by requestQuatuGpu().
virtual bool SystemInterface::hasR () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 112 of file SystemInterface.hpp.
Referenced by requestR().
virtual bool SystemInterface::hasRGpu () inline virtual
Definition at line 117 of file SystemInterface.hpp.
Referenced by requestRGpu().
virtual bool SystemInterface::hasTorqueGpu () inline virtual
Definition at line 138 of file SystemInterface.hpp.
Referenced by requestTorqueGpu().
virtual bool SystemInterface::hasVGpu () inline virtual
Definition at line 122 of file SystemInterface.hpp.
Referenced by requestVGpu().
virtual void SystemInterface::init () pure virtual
Implemented in EspressoSystemInterface.
virtual bool SystemInterface::needsFGpu () inline virtual
Definition at line 166 of file SystemInterface.hpp.
References m_needsFGpu.
virtual bool SystemInterface::needsQ () inline virtual
Definition at line 163 of file SystemInterface.hpp.
References m_needsQ.
Referenced by EspressoSystemInterface::gatherParticles().
virtual bool SystemInterface::needsQGpu () inline virtual
Definition at line 162 of file SystemInterface.hpp.
References m_needsQGpu.
virtual bool SystemInterface::needsQuatu () inline virtual
Definition at line 165 of file SystemInterface.hpp.
References m_needsQuatu.
Referenced by EspressoSystemInterface::gatherParticles().
virtual bool SystemInterface::needsQuatuGpu () inline virtual
Definition at line 164 of file SystemInterface.hpp.
References m_needsQuatuGpu.
virtual bool SystemInterface::needsR () inline virtual
Definition at line 160 of file SystemInterface.hpp.
References m_needsR.
Referenced by EspressoSystemInterface::gatherParticles().
virtual bool SystemInterface::needsRGpu () inline virtual
Definition at line 161 of file SystemInterface.hpp.
References m_needsRGpu.
virtual bool SystemInterface::needsTorqueGpu () inline virtual
Definition at line 167 of file SystemInterface.hpp.
References m_needsTorqueGpu.
virtual unsigned int SystemInterface::npart () pure virtual
Implemented in EspressoSystemInterface.
virtual unsigned int SystemInterface::npart_gpu () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 157 of file SystemInterface.hpp.
Referenced by Mmm1dgpuForce::computeEnergy(), Mmm1dgpuForce::computeForces(), HarmonicOrientationWell::computeTorques(), EwaldgpuForce::setup(), and Mmm1dgpuForce::setup().
virtual const_real_iterator& SystemInterface::qBegin () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 141 of file SystemInterface.hpp.
References null_scalar.
virtual const const_real_iterator& SystemInterface::qEnd () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 142 of file SystemInterface.hpp.
References null_scalar.
virtual float* SystemInterface::qGpuBegin () inline virtual
Definition at line 125 of file SystemInterface.hpp.
Referenced by Mmm1dgpuForce::computeEnergy(), Mmm1dgpuForce::computeForces(), EwaldgpuForce::GPU_Forces(), and EwaldgpuForce::GPU_q_sqr().
virtual float* SystemInterface::qGpuEnd () inline virtual
Definition at line 126 of file SystemInterface.hpp.
virtual const_vec_iterator& SystemInterface::quatuBegin () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 146 of file SystemInterface.hpp.
References null_vector.
virtual const const_vec_iterator& SystemInterface::quatuEnd () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 147 of file SystemInterface.hpp.
References null_vector.
virtual float* SystemInterface::quatuGpuBegin () inline virtual
Definition at line 151 of file SystemInterface.hpp.
Referenced by HarmonicOrientationWell::computeTorques().
virtual float* SystemInterface::quatuGpuEnd () inline virtual
Definition at line 152 of file SystemInterface.hpp.
virtual const_vec_iterator& SystemInterface::rBegin () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 110 of file SystemInterface.hpp.
References null_vector.
virtual const const_vec_iterator& SystemInterface::rEnd () inline virtual
Reimplemented in EspressoSystemInterface.
Definition at line 111 of file SystemInterface.hpp.
References null_vector.
virtual bool SystemInterface::requestFGpu () inline virtual
Definition at line 134 of file SystemInterface.hpp.
References hasFGpu(), and m_needsFGpu.
Referenced by EwaldgpuForce::EwaldgpuForce(), and Mmm1dgpuForce::Mmm1dgpuForce().
virtual bool SystemInterface::requestQ () inline virtual
Definition at line 144 of file SystemInterface.hpp.
References hasQ(), and m_needsQ.
virtual bool SystemInterface::requestQGpu () inline virtual
Definition at line 128 of file SystemInterface.hpp.
References hasQGpu(), and m_needsQGpu.
Referenced by EwaldgpuForce::EwaldgpuForce(), and Mmm1dgpuForce::Mmm1dgpuForce().
virtual bool SystemInterface::requestQuatu () inline virtual
Definition at line 149 of file SystemInterface.hpp.
References hasQuatu(), and m_needsQuatu.
virtual bool SystemInterface::requestQuatuGpu () inline virtual
Definition at line 154 of file SystemInterface.hpp.
References hasQuatuGpu(), and m_needsQuatuGpu.
Referenced by HarmonicOrientationWell::HarmonicOrientationWell().
virtual bool SystemInterface::requestR () inline virtual
Definition at line 113 of file SystemInterface.hpp.
References hasR(), and m_needsR.
virtual bool SystemInterface::requestRGpu () inline virtual
Definition at line 118 of file SystemInterface.hpp.
References hasRGpu(), and m_needsRGpu.
Referenced by EwaldgpuForce::EwaldgpuForce(), and Mmm1dgpuForce::Mmm1dgpuForce().
virtual bool SystemInterface::requestTorqueGpu () inline virtual
Definition at line 139 of file SystemInterface.hpp.
References hasTorqueGpu(), and m_needsTorqueGpu.
Referenced by HarmonicOrientationWell::HarmonicOrientationWell().
virtual bool SystemInterface::requestVGpu () inline virtual
Definition at line 123 of file SystemInterface.hpp.
References hasVGpu(), and m_needsVGpu.
virtual float* SystemInterface::rGpuBegin () inline virtual
Definition at line 115 of file SystemInterface.hpp.
Referenced by Mmm1dgpuForce::computeEnergy(), Mmm1dgpuForce::computeForces(), and EwaldgpuForce::GPU_Forces().
virtual float* SystemInterface::rGpuEnd () inline virtual
Definition at line 116 of file SystemInterface.hpp.
virtual float* SystemInterface::torqueGpuBegin () inline virtual
Definition at line 136 of file SystemInterface.hpp.
Referenced by HarmonicOrientationWell::computeTorques().
virtual float* SystemInterface::torqueGpuEnd () inline virtual
Definition at line 137 of file SystemInterface.hpp.
virtual void SystemInterface::update () pure virtual
Implemented in EspressoSystemInterface.
virtual float* SystemInterface::vGpuBegin () inline virtual
Definition at line 120 of file SystemInterface.hpp.
virtual float* SystemInterface::vGpuEnd () inline virtual
Definition at line 121 of file SystemInterface.hpp.
Field Documentation
bool SystemInterface::m_needsFGpu protected
Definition at line 179 of file SystemInterface.hpp.
Referenced by needsFGpu(), and requestFGpu().
bool SystemInterface::m_needsQ protected
Definition at line 173 of file SystemInterface.hpp.
Referenced by needsQ(), and requestQ().
bool SystemInterface::m_needsQGpu protected
Definition at line 177 of file SystemInterface.hpp.
Referenced by needsQGpu(), requestQGpu(), and EspressoSystemInterface::split_particle_struct().
bool SystemInterface::m_needsQuatu protected
Definition at line 174 of file SystemInterface.hpp.
Referenced by needsQuatu(), and requestQuatu().
bool SystemInterface::m_needsQuatuGpu protected
Definition at line 178 of file SystemInterface.hpp.
Referenced by needsQuatuGpu(), requestQuatuGpu(), and EspressoSystemInterface::split_particle_struct().
bool SystemInterface::m_needsR protected
Definition at line 167 of file SystemInterface.hpp.
Referenced by needsR(), and requestR().
bool SystemInterface::m_needsRGpu protected
Definition at line 175 of file SystemInterface.hpp.
Referenced by needsRGpu(), requestRGpu(), and EspressoSystemInterface::split_particle_struct().
bool SystemInterface::m_needsTorqueGpu protected
Definition at line 180 of file SystemInterface.hpp.
Referenced by needsTorqueGpu(), and requestTorqueGpu().
bool SystemInterface::m_needsV protected
Definition at line 172 of file SystemInterface.hpp.
bool SystemInterface::m_needsVGpu protected
Definition at line 176 of file SystemInterface.hpp.
Referenced by requestVGpu(), and EspressoSystemInterface::split_particle_struct().
null_real_iterator SystemInterface::null_scalar
Definition at line 66 of file SystemInterface.hpp.
Referenced by qBegin(), and qEnd().
null_vec_iterator SystemInterface::null_vector
Definition at line 55 of file SystemInterface.hpp.
Referenced by quatuBegin(), quatuEnd(), rBegin(), and rEnd().
The documentation for this class was generated from the following file:
SystemInterface.hpp