ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ActorList Class Reference
ActorList Class Reference
#include <ActorList.hpp>
Public Member Functions
void add (Actor *actor)
void remove (Actor *actor)
Detailed Description
Definition at line 25 of file ActorList.hpp.
Member Function Documentation
void ActorList::add (Actor * actor)
Definition at line 24 of file ActorList.cpp.
Referenced by tclcommand_inter_coulomb_parse_ewaldgpu_notune(), tclcommand_inter_coulomb_parse_ewaldgpu_tune(), tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha(), and tclcommand_inter_coulomb_parse_mmm1dgpu().
void ActorList::remove (Actor * actor)
Definition at line 28 of file ActorList.cpp.
The documentation for this class was generated from the following files:
ActorList.hpp
ActorList.cpp