ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: le_dd_comms_manager Class Reference
le_dd_comms_manager Class Reference
Class to manage rebuilds of the communicators after a Lees-Edwards offset change.
#include <lees_edwards_comms_manager.hpp>
Public Member Functions
void init (int neighbor_count)
Setup the comms order.
int update_on_le_offset_change ()
change some state based on a new lees-edwards offset
int wrap_fill_comm_cell_lists (Cell **part_lists, int lc[3], int hc[3], int lower_xIndex, int upper_xIndex, int amUpper, int amSender)
Update a y-direction comm after a Lees-Edwards offset change.
~le_dd_comms_manager ()
destructor for the comms manager
Data Fields
unsigned short int * comms_order
Array of neighbour indexes in order to carry out the comms.
Detailed Description
Class to manage rebuilds of the communicators after a Lees-Edwards offset change.
Definition at line 57 of file lees_edwards_comms_manager.hpp.
Constructor & Destructor Documentation
le_dd_comms_manager::~le_dd_comms_manager () inline
destructor for the comms manager
Definition at line 78 of file lees_edwards_comms_manager.hpp.
References comms_order.
Member Function Documentation
void le_dd_comms_manager::init (int neighbor_count)
Setup the comms order.
Allocate and fill a short int array with the order of comms.
The neighbor index is into node_neighbors is stored, not the actual node id (a comms system with one node only will have 6 entries in node_neighbours, all pointing to itself).
Definition at line 47 of file lees_edwards_comms_manager.cpp.
References comms_order, i, and update_on_le_offset_change().
Referenced by dd_topology_init().
int le_dd_comms_manager::update_on_le_offset_change ()
change some state based on a new lees-edwards offset
Change some state based on a new lees-edwards offset, variables saved are total_xcells, le_offset_cells_down, le_offset_cells_up.
Definition at line 77 of file lees_edwards_comms_manager.cpp.
References box_l, DomainDecomposition::cell_grid, dd, DomainDecomposition::inv_cell_size, LE_CELLS_SAME, LE_CELLS_SHIFTED, lees_edwards_offset, and node_grid.
Referenced by dd_on_geometry_change(), and init().
int le_dd_comms_manager::wrap_fill_comm_cell_lists (Cell ** part_lists, int lc[3], int hc[3], int lower_xIndex, int upper_xIndex, int amUpper, int amSender)
Update a y-direction comm after a Lees-Edwards offset change.
Sending or receiving cells in Y direction with LE wrap means looking at the existing cell list with an offset.
This function fills the comm list using cells with an offset or no cells at all, depending on what is required.
Definition at line 116 of file lees_edwards_comms_manager.cpp.
References DomainDecomposition::cell_grid, DomainDecomposition::cell_size, CELL_TRACE, cells, dd, get_linear_index(), DomainDecomposition::ghost_cell_grid, i, lees_edwards_offset, and this_node.
Referenced by le_dd_dynamic_update_comm(), and le_dd_prepare_comm().
Field Documentation
unsigned short int* le_dd_comms_manager::comms_order
Array of neighbour indexes in order to carry out the comms.
Definition at line 75 of file lees_edwards_comms_manager.hpp.
Referenced by init(), le_dd_dynamic_update_comm(), le_dd_prepare_comm(), le_dd_update_communicators_w_boxl(), and ~le_dd_comms_manager().
The documentation for this class was generated from the following files:
lees_edwards_comms_manager.hpp
lees_edwards_comms_manager.cpp