ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: RuntimeErrorCollector Class Reference
RuntimeErrorCollector Class Reference
#include <RuntimeErrorCollector.hpp>
Public Member Functions
RuntimeErrorCollector (MPI_Comm comm)
void warning (const std::string &msg, const char *function, const char *file, const int line)
void warning (const char *msg, const char *function, const char *file, const int line)
void warning (const std::ostringstream &mstr, const char *function, const char *file, const int line)
void error (const std::string &msg, const char *function, const char *file, const int line)
void error (const char *msg, const char *function, const char *file, const int line)
void error (const std::ostringstream &mstr, const char *function, const char *file, const int line)
int count ()
void clear ()
std::list< std::string > gather ()
void gatherSlave ()
Detailed Description
Definition at line 28 of file RuntimeErrorCollector.hpp.
Constructor & Destructor Documentation
RuntimeErrorCollector::RuntimeErrorCollector (MPI_Comm comm)
Definition at line 26 of file RuntimeErrorCollector.cpp.
Member Function Documentation
void RuntimeErrorCollector::clear ()
Definition at line 86 of file RuntimeErrorCollector.cpp.
int RuntimeErrorCollector::count ()
Definition at line 80 of file RuntimeErrorCollector.cpp.
References MPI_Allreduce(), MPI_IN_PLACE, MPI_INT, and MPI_SUM.
Referenced by check_runtime_errors().
void RuntimeErrorCollector::error (const std::string & msg, const char * function, const char * file, const int line)
Referenced by _runtimeError().
void RuntimeErrorCollector::error (const char * msg, const char * function, const char * file, const int line)
Definition at line 67 of file RuntimeErrorCollector.cpp.
void RuntimeErrorCollector::error (const std::ostringstream & mstr, const char * function, const char * file, const int line)
list< string > RuntimeErrorCollector::gather ()
Definition at line 91 of file RuntimeErrorCollector.cpp.
References i, MPI_ANY_SOURCE, MPI_ANY_TAG, MPI_CHAR, MPI_Get_count(), MPI_Probe(), MPI_Recv(), and MPI_STATUS_IGNORE.
Referenced by mpiRuntimeErrorCollectorGather().
void RuntimeErrorCollector::gatherSlave ()
Definition at line 124 of file RuntimeErrorCollector.cpp.
References MPI_CHAR, and MPI_Send().
Referenced by mpiRuntimeErrorCollectorGatherSlave().
void RuntimeErrorCollector::warning (const std::string & msg, const char * function, const char * file, const int line)
Referenced by _runtimeWarning().
void RuntimeErrorCollector::warning (const char * msg, const char * function, const char * file, const int line)
Definition at line 43 of file RuntimeErrorCollector.cpp.
void RuntimeErrorCollector::warning (const std::ostringstream & mstr, const char * function, const char * file, const int line)
The documentation for this class was generated from the following files:
RuntimeErrorCollector.hpp
RuntimeErrorCollector.cpp