ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: Vector< n, Scalar > Class Template Reference
Vector< n, Scalar > Class Template Reference
#include <Vector.hpp>
Public Member Functions
Vector ()
Vector (Scalar *a)
~Vector ()
Vector (const Vector &rhs)
void swap (Vector &rhs)
Vector & operator= (Vector &rhs)
Scalar & operator[] (int i)
Scalar dot (const Vector< n, Scalar > &b) const
Scalar norm2 (void) const
Scalar norm (void) const
void normalize (void)
void cross (const Vector< 3, Scalar > &a, const Vector< 3, Scalar > &b, Vector< 3, Scalar > &c) const
Vector< 3, Scalar > cross (const Vector< 3, Scalar > &a, const Vector< 3, Scalar > &b) const
Vector< 3, Scalar > cross (const Vector< 3, Scalar > &a) const
Detailed Description
template<int n, typename Scalar>
class Vector< n, Scalar >
Definition at line 23 of file Vector.hpp.
Constructor & Destructor Documentation
template<int n, typename Scalar> Vector< n, Scalar >::Vector () inline
Definition at line 27 of file Vector.hpp.
template<int n, typename Scalar> Vector< n, Scalar >::Vector (Scalar * a) inline explicit
Definition at line 29 of file Vector.hpp.
References i.
template<int n, typename Scalar> Vector< n, Scalar >::~Vector () inline
Definition at line 34 of file Vector.hpp.
template<int n, typename Scalar> Vector< n, Scalar >::Vector (const Vector< n, Scalar > & rhs) inline
Definition at line 38 of file Vector.hpp.
Member Function Documentation
template<int n, typename Scalar> void Vector< n, Scalar >::cross (const Vector< 3, Scalar > & a, const Vector< 3, Scalar > & b, Vector< 3, Scalar > & c) const inline
Definition at line 77 of file Vector.hpp.
Referenced by Vector< n, Scalar >::cross().
template<int n, typename Scalar> Vector<3, Scalar> Vector< n, Scalar >::cross (const Vector< 3, Scalar > & a, const Vector< 3, Scalar > & b) const inline
Definition at line 83 of file Vector.hpp.
References Vector< n, Scalar >::cross().
template<int n, typename Scalar> Vector<3, Scalar> Vector< n, Scalar >::cross (const Vector< 3, Scalar > & a) const inline
Definition at line 88 of file Vector.hpp.
References Vector< n, Scalar >::cross().
template<int n, typename Scalar> Scalar Vector< n, Scalar >::dot (const Vector< n, Scalar > & b) const inline
Definition at line 54 of file Vector.hpp.
References i.
Referenced by Vector< n, Scalar >::norm2().
template<int n, typename Scalar> Scalar Vector< n, Scalar >::norm (void) const inline
Definition at line 65 of file Vector.hpp.
References Vector< n, Scalar >::norm2().
Referenced by Vector< n, Scalar >::normalize().
template<int n, typename Scalar> Scalar Vector< n, Scalar >::norm2 (void) const inline
Definition at line 61 of file Vector.hpp.
References Vector< n, Scalar >::dot().
Referenced by Vector< n, Scalar >::norm().
template<int n, typename Scalar> void Vector< n, Scalar >::normalize (void) inline
Definition at line 69 of file Vector.hpp.
References i, and Vector< n, Scalar >::norm().
template<int n, typename Scalar> Vector& Vector< n, Scalar >::operator= (Vector< n, Scalar > & rhs) inline
Definition at line 46 of file Vector.hpp.
References Vector< n, Scalar >::swap().
template<int n, typename Scalar> Scalar& Vector< n, Scalar >::operator[] (int i) inline
Definition at line 50 of file Vector.hpp.
References i.
template<int n, typename Scalar> void Vector< n, Scalar >::swap (Vector< n, Scalar > & rhs) inline
Definition at line 42 of file Vector.hpp.
Referenced by Vector< n, Scalar >::operator=().
The documentation for this class was generated from the following file:
Vector.hpp