ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: PdbParser::PdbParser Class Reference
PdbParser::PdbParser Class Reference
#include <PdbParser.hpp>
Public Member Functions
bool parse_pdb_file (std::string filename)
bool parse_itp_file (std::string filename)
bool parse_file (std::string pdb_filename, std::string itp_filename)
BoundingBox calc_bounding_box () const
Data Fields
std::vector< pdb_atom > pdb_atoms
std::map< int, itp_atom > itp_atoms
std::map< std::string, itp_atomtype > itp_atomtypes
Detailed Description
Definition at line 59 of file PdbParser.hpp.
Member Function Documentation
BoundingBox PdbParser::PdbParser::calc_bounding_box () const
Definition at line 30 of file PdbParser.cpp.
References PdbParser::BoundingBox::llx, PdbParser::BoundingBox::lly, PdbParser::BoundingBox::llz, PdbParser::BoundingBox::urx, PdbParser::BoundingBox::ury, and PdbParser::BoundingBox::urz.
Referenced by add_particles(), and populate_lattice().
bool PdbParser::PdbParser::parse_file (std::string pdb_filename, std::string itp_filename)
Definition at line 183 of file PdbParser.cpp.
Referenced by pdb_parse().
bool PdbParser::PdbParser::parse_itp_file (std::string filename)
Definition at line 79 of file PdbParser.cpp.
References PdbParser::itp_atom::charge, PdbParser::itp_atomtype::epsilon, PdbParser::itp_atom::i, PdbParser::itp_atomtype::id, PdbParser::itp_atomtype::sigma, and PdbParser::itp_atom::type.
Referenced by pdb_add_particles_from_file().
bool PdbParser::PdbParser::parse_pdb_file (std::string filename)
Definition at line 51 of file PdbParser.cpp.
References PdbParser::pdb_atom::i, PdbParser::pdb_atom::x, PdbParser::pdb_atom::y, and PdbParser::pdb_atom::z.
Referenced by pdb_add_particles_from_file().
Field Documentation
std::map<int, itp_atom> PdbParser::PdbParser::itp_atoms
Definition at line 66 of file PdbParser.hpp.
Referenced by add_particles(), pdb_add_particles_from_file(), and populate_lattice().
std::map<std::string, itp_atomtype> PdbParser::PdbParser::itp_atomtypes
Definition at line 67 of file PdbParser.hpp.
Referenced by add_particles(), pdb_add_particles_from_file(), and populate_lattice().
std::vector<pdb_atom> PdbParser::PdbParser::pdb_atoms
Definition at line 65 of file PdbParser.hpp.
Referenced by add_particles(), and populate_lattice().
The documentation for this class was generated from the following files:
PdbParser.hpp
PdbParser.cpp