ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: collision.cpp File Reference
collision.cpp File Reference
#include "collision.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
Macros
#define TRACE(a)
Functions
int collision_detection_set_params (int mode, double d, int bond_centers, int bond_vs, int t)
set the parameters for the collision detection
void detect_collision (Particle *p1, Particle *p2)
Detect a collision between two particles.
void prepare_collision_queue ()
void handle_collisions ()
Handle the collisions recorded in the queue.
Variables
static collision_struct * collision_queue = 0
static int number_of_collisions
Collision_parameters collision_params = { 0, }
Parameters for collision detection.
Macro Definition Documentation
#define TRACE (a)
Definition at line 32 of file collision.cpp.
Referenced by detect_collision().
Function Documentation
int collision_detection_set_params (int mode, double d, int bond_centers, int bond_vs, int t)
set the parameters for the collision detection
Parameters
mode is a bitset out of the COLLISION_MODE_* bits
d is the collision distance, below that a bond is generated
bond_centers is the type of the bond between the real particles
bond_vs is the type of the bond between the virtual particles, if using noslip bonds
t is the type of the virtual sites, if using noslip bonds
Definition at line 54 of file collision.cpp.
References Collision_parameters::bond_centers, Collision_parameters::bond_vs, bonded_ia_params, COLLISION_MODE_BOND, COLLISION_MODE_VS, Collision_parameters::distance, make_particle_type_exist(), Collision_parameters::mode, mpi_bcast_collision_params(), n_bonded_ia, n_nodes, and Collision_parameters::vs_particle_type.
Referenced by tclcommand_on_collision().
void detect_collision (Particle * p1, Particle * p2)
Detect a collision between two particles.
In case of collision, a bond between the particles is added as marker and the collision is recorded in the queue for later processing.
Definition at line 102 of file collision.cpp.
References Particle::bl, Collision_parameters::bond_centers, bonded_ia_params, COLLISION_MODE_BOND, COLLISION_MODE_EXCEPTION, COLLISION_MODE_VS, collision_queue, Collision_parameters::distance, distance2vec(), IntList::e, ParticleLocal::ghost, i, ParticleProperties::identity, ParticleProperties::isVirtual, Particle::l, local_change_bond(), local_particles, Collision_parameters::mode, Bonded_ia_parameters::num, number_of_collisions, ParticlePosition::p, Particle::p, Particle::r, realloc, this_node, and TRACE.
Referenced by add_non_bonded_pair_force().
void handle_collisions ()
Handle the collisions recorded in the queue.
Definition at line 216 of file collision.cpp.
References announce_resort_particles(), Collision_parameters::bond_vs, bonded_ia_params, COLLISION_MODE_EXCEPTION, COLLISION_MODE_VS, collision_queue, free, i, local_change_bond(), local_particles, max_seen_particle, Collision_parameters::mode, Bonded_ia_parameters::num, number_of_collisions, place_particle(), runtimeError, Collision_parameters::vs_particle_type, and vs_relate_to().
Referenced by force_calc(), integrate_sd(), and integrate_vv().
void prepare_collision_queue ()
Definition at line 206 of file collision.cpp.
References collision_queue, malloc, and number_of_collisions.
Referenced by force_calc().
Variable Documentation
Collision_parameters collision_params = { 0, }
Parameters for collision detection.
Definition at line 52 of file collision.cpp.
Referenced by add_non_bonded_pair_force(), mpi_bcast_collision_params_slave(), and tclcommand_on_collision().
collision_struct* collision_queue = 0 static
Definition at line 47 of file collision.cpp.
Referenced by detect_collision(), handle_collisions(), and prepare_collision_queue().
int number_of_collisions static
Definition at line 49 of file collision.cpp.
Referenced by detect_collision(), handle_collisions(), and prepare_collision_queue().