ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: comforce.hpp File Reference
comforce.hpp File Reference
Routines for center of mass forces.
#include "utils.hpp"
#include "particle_data.hpp"
#include "statistics.hpp"
Functions
int comforce_set_params (int part_type_a, int part_type_b, int flag, int dir, double force, double fratio)
void calc_comforce ()
calculate the center of mass forces
Detailed Description
Routines for center of mass forces.
Definition in file comforce.hpp.
Function Documentation
void calc_comforce ()
calculate the center of mass forces
Definition at line 53 of file comforce.cpp.
References calc_eigenvalues_3x3(), calc_eigenvector_3x3(), CellPList::cell, centermass(), IA_parameters::COMFORCE_dir, IA_parameters::COMFORCE_flag, IA_parameters::COMFORCE_force, IA_parameters::COMFORCE_fratio, ParticleForce::f, Particle::f, get_ia_param(), i, ia_params, local_cells, momentofinertiamatrix(), CellPList::n, ParticleList::n, n_particle_types, ParticleList::part, scalar(), unit_vector(), and vector_product().
Referenced by force_calc().
int comforce_set_params (int part_type_a, int part_type_b, int flag, int dir, double force, double fratio)
Definition at line 31 of file comforce.cpp.
References IA_parameters::COMFORCE_dir, IA_parameters::COMFORCE_flag, IA_parameters::COMFORCE_force, IA_parameters::COMFORCE_fratio, get_ia_param_safe(), mpi_bcast_ia_params(), and n_nodes.
Referenced by tclcommand_inter_parse_comforce().