ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: communication.cpp File Reference
communication.cpp File Reference
#include <mpi.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "utils.hpp"
#include "communication.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "integrate.hpp"
#include "cells.hpp"
#include "global.hpp"
#include "grid.hpp"
#include "initialize.hpp"
#include "forces.hpp"
#include "rotation.hpp"
#include "p3m.hpp"
#include "statistics.hpp"
#include "energy.hpp"
#include "pressure.hpp"
#include "random.hpp"
#include "lj.hpp"
#include "lb.hpp"
#include "lb-boundaries.hpp"
#include "morse.hpp"
#include "buckingham.hpp"
#include "tab.hpp"
#include "overlap.hpp"
#include "ljcos.hpp"
#include "ljangle.hpp"
#include "gb.hpp"
#include "mmm1d.hpp"
#include "mmm2d.hpp"
#include "maggs.hpp"
#include "actor/EwaldgpuForce.hpp"
#include "elc.hpp"
#include "iccp3m.hpp"
#include "statistics_chain.hpp"
#include "statistics_fluid.hpp"
#include "virtual_sites.hpp"
#include "topology.hpp"
#include "errorhandling.hpp"
#include "molforces.hpp"
#include "mdlc_correction.hpp"
#include "reaction.hpp"
#include "galilei.hpp"
#include "external_potential.hpp"
#include "statistics_correlation.hpp"
#include "cuda_interface.hpp"
#include "EspressoSystemInterface.hpp"
#include "statistics_observable.hpp"
#include "minimize_energy.hpp"
Macros
#define CALLBACK_LIST
#define CB(name) void name(int node, int param);
#define CB(name) name,
#define CB(name) #name,
#define SOME_TAG 42
Functions
void mpi_core (MPI_Comm *comm, int *errcode,...)
void mpi_init (int *argc, char ***argv)
Initialize MPI and determine n_nodes and this_node.
void mpi_call (SlaveCallback cb, int node, int param)
void mpi_stop ()
Stop Espresso, all slave nodes exit.
void mpi_stop_slave (int node, int param)
static void common_bcast_parameter (int i)
int mpi_bcast_parameter (int i)
Issue REQ_BCAST_PAR: broadcast a parameter from datafield.
void mpi_bcast_parameter_slave (int node, int i)
void mpi_who_has ()
Issue REQ_WHO_HAS: ask nodes for their attached particles.
void mpi_who_has_slave (int node, int param)
void mpi_bcast_event (int event)
Issue REQ_EVENT: tells all clients of some system change.
void mpi_bcast_event_slave (int node, int event)
void mpi_place_particle (int pnode, int part, double p[3])
Issue REQ_PLACE: move particle to a position on a node.
void mpi_place_particle_slave (int pnode, int part)
void mpi_place_new_particle (int pnode, int part, double p[3])
Issue REQ_PLACE: create particle at a position on a node.
void mpi_place_new_particle_slave (int pnode, int part)
void mpi_send_v (int pnode, int part, double v[3])
Issue REQ_SET_V: send particle velocity.
void mpi_send_v_slave (int pnode, int part)
void mpi_send_swimming (int pnode, int part, ParticleParametersSwimming swim)
Issue REQ_SET_SWIMMING: send particle swimming properties.
void mpi_send_swimming_slave (int pnode, int part)
void mpi_send_f (int pnode, int part, double F[3])
Issue REQ_SET_F: send particle force.
void mpi_send_f_slave (int pnode, int part)
void mpi_send_q (int pnode, int part, double q)
Issue REQ_SET_Q: send particle charge.
void mpi_send_q_slave (int pnode, int part)
void mpi_send_mu_E (int pnode, int part, double mu_E[3])
Issue REQ_SET_MU_E: send particle electrophoretic mobility.
void mpi_send_mu_E_slave (int pnode, int part)
void mpi_send_solvation (int pnode, int part, double *solvation)
issue req_set_solv: send particle solvation free energy also calls on_particle_change.
void mpi_send_solvation_slave (int pnode, int part)
void mpi_send_mass (int pnode, int part, double mass)
Issue REQ_SET_M: send particle mass.
void mpi_send_mass_slave (int pnode, int part)
void mpi_send_rotational_inertia (int pnode, int part, double rinertia[3])
Issue REQ_SET_ROTATIONAL_INERTIA: send particle rotational inertia.
void mpi_send_rotational_inertia_slave (int pnode, int part)
void mpi_send_type (int pnode, int part, int type)
Issue REQ_SET_TYPE: send particle type.
void mpi_send_type_slave (int pnode, int part)
void mpi_send_mol_id (int pnode, int part, int mid)
Issue REQ_SET_MOL_ID: send molecule id.
void mpi_send_mol_id_slave (int pnode, int part)
void mpi_send_quat (int pnode, int part, double quat[4])
Issue REQ_SET_QUAT: send particle orientation.
void mpi_send_quat_slave (int pnode, int part)
void mpi_send_omega (int pnode, int part, double omega[3])
void mpi_send_omega_slave (int pnode, int part)
void mpi_send_torque (int pnode, int part, double torque[3])
Issue REQ_SET_TORQUE: send particle torque.
void mpi_send_torque_slave (int pnode, int part)
void mpi_send_dip (int pnode, int part, double dip[3])
Issue REQ_SET_DIP: send particle dipole orientation.
void mpi_send_dip_slave (int pnode, int part)
void mpi_send_dipm (int pnode, int part, double dipm)
Issue REQ_SET_DIPM: send particle dipole moment.
void mpi_send_dipm_slave (int pnode, int part)
void mpi_send_virtual (int pnode, int part, int isVirtual)
Issue REQ_SET_DIPM: send particle dipole moment.
void mpi_send_virtual_slave (int pnode, int part)
void mpi_send_vs_relative (int pnode, int part, int vs_relative_to, double vs_distance)
void mpi_send_vs_relative_slave (int pnode, int part)
void mpi_send_rotation (int pnode, int part, int rot)
Issue REQ_SET_ROTATION: send particle rotation flag Also calls on_particle_change.
void mpi_send_rotation_slave (int pnode, int part)
void mpi_observable_lb_radial_velocity_profile ()
void mpi_observable_lb_radial_velocity_profile_slave (int pnode, int part)
int mpi_send_bond (int pnode, int part, int *bond, int _delete)
Issue REQ_SET_BOND: send bond.
void mpi_send_bond_slave (int pnode, int part)
void mpi_recv_part (int pnode, int part, Particle *pdata)
Issue REQ_GET_PART: recv particle data.
void mpi_recv_part_slave (int pnode, int part)
void mpi_remove_particle (int pnode, int part)
Issue REQ_REM_PART: remove a particle.
void mpi_remove_particle_slave (int pnode, int part)
int mpi_minimize_energy (void)
Issue REQ_MIN_ENERGY: start energy minimization.
void mpi_minimize_energy_slave (int a, int b)
int mpi_integrate (int n_steps, int reuse_forces)
Issue REQ_INTEGRATE: start integrator.
void mpi_integrate_slave (int n_steps, int reuse_forces)
void mpi_bcast_ia_params (int i, int j)
Issue REQ_BCAST_IA: send new ia params.
void mpi_bcast_ia_params_slave (int i, int j)
void mpi_bcast_n_particle_types (int ns)
Issue REQ_BCAST_IA_SIZE: send new size of ia_params.
void mpi_bcast_n_particle_types_slave (int pnode, int ns)
void mpi_gather_stats (int job, void *result, void *result_t, void *result_nb, void *result_t_nb)
Issue REQ_GATHER: gather data for analysis in analyze.
void mpi_gather_stats_slave (int ana_num, int job)
void mpi_local_stress_tensor (DoubleList *TensorInBin, int bins[3], int periodic[3], double range_start[3], double range[3])
Issue GET_LOCAL_STRESS_TENSOR: gather the contribution to the local stress tensors from each node.
void mpi_local_stress_tensor_slave (int ana_num, int job)
void mpi_get_particles (Particle *result, IntList *bi)
Issue REQ_GETPARTS: gather all particle informations (except bonds).
void mpi_get_particles_slave (int pnode, int bi)
void mpi_set_time_step (double time_s)
Issue REQ_SET_TIME_STEP: send new time_step and rescale the velocities accordingly.
void mpi_set_time_step_slave (int node, int i)
void mpi_set_smaller_time_step (double time_s)
Issue REQ_SET_SMALLER_TIME_STEP: send new smaller_time_step.
void mpi_set_smaller_time_step_slave (int node, int i)
void mpi_send_smaller_timestep_flag (int pnode, int part, int smaller_timestep)
Issue REQ_SET_SMALLER_TIMESTEP: send smaller time step value.
void mpi_send_smaller_timestep_flag_slave (int pnode, int part)
void mpi_send_configtemp_flag (int pnode, int part, int configtemp)
void mpi_send_configtemp_flag_slave (int pnode, int part)
void mpi_bcast_coulomb_params ()
Issue REQ_BCAST_COULOMB: send new coulomb parameters.
void mpi_bcast_coulomb_params_slave (int node, int parm)
void mpi_bcast_collision_params ()
send new collision parameters.
void mpi_bcast_collision_params_slave (int node, int parm)
void mpi_send_ext_torque (int pnode, int part, int flag, int mask, double torque[3])
Issue REQ_SEND_EXT_TORQUE: send nex external flag and external torque.
void mpi_send_ext_torque_slave (int pnode, int part)
void mpi_send_ext_force (int pnode, int part, int flag, int mask, double force[3])
Issue REQ_SEND_EXT_FORCE: send nex external flag and external force.
void mpi_send_ext_force_slave (int pnode, int part)
void mpi_bcast_constraint (int del_num)
Issue REQ_BCAST_COULOMB: send new coulomb parameters.
void mpi_bcast_constraint_slave (int node, int parm)
void mpi_bcast_lbboundary (int del_num)
Issue REQ_LB_BOUNDARY: set up walls for lb fluid.
void mpi_bcast_lbboundary_slave (int node, int parm)
void mpi_random_seed (int cnt, long *seed)
Issue REQ_RANDOM_SEED: read/set seed of random number generators on each node.
void mpi_random_seed_slave (int pnode, int cnt)
void mpi_random_stat (int cnt, RandomStatus *stat)
Issue REQ_RANDOM_STAT: read/set status of random number generators on each node.
void mpi_random_stat_slave (int pnode, int cnt)
void mpi_cap_forces (double fc)
Issue REQ_BCAST_LJFORCECAP: initialize LJ force capping.
void mpi_cap_forces_slave (int node, int parm)
void mpi_get_constraint_force (int cons, double force[3])
Issue REQ_BCAST_MORSEFORCECAP: initialize Morse force capping.
void mpi_get_constraint_force_slave (int node, int parm)
void mpi_get_configtemp (double cfgtmp[2])
void mpi_get_configtemp_slave (int node, int cnt)
void mpi_bit_random_seed (int cnt, int *seed)
Issue REQ_BIT_RANDOM_SEED: read/set seed of the bit random number generators on each node.
void mpi_bit_random_seed_slave (int pnode, int cnt)
void mpi_bit_random_stat (int cnt, BitRandomStatus *stat)
Issue REQ_BIT_RANDOM_STAT: read/set status of the bit random number generators on each node.
void mpi_bit_random_stat_slave (int pnode, int cnt)
void mpi_rescale_particles (int dir, double scale)
Issue REQ_RESCALE_PART: rescales all particle positions in direction 'dir' by a factor 'scale'.
void mpi_rescale_particles_slave (int pnode, int dir)
void mpi_bcast_cell_structure (int cs)
Issue REQ_BCAST_CS: change the cell structure on all nodes.
void mpi_bcast_cell_structure_slave (int pnode, int cs)
void mpi_bcast_nptiso_geom ()
Issue REQ_BCAST_NPTISO_GEOM: broadcast nptiso geometry parameter to all nodes.
void mpi_bcast_nptiso_geom_slave (int node, int parm)
void mpi_update_mol_ids ()
Issue REQ_BCAST_LJANGLEFORCECAP: initialize LJANGLE force capping.
void mpi_update_mol_ids_slave (int node, int parm)
int mpi_sync_topo_part_info ()
Issue REQ_SYNC_TOPO: Update the molecules ids to that they correspond to the topology.
void mpi_sync_topo_part_info_slave (int node, int parm)
void mpi_bcast_lb_params (int field)
Issue REQ_BCAST_LBPAR: Broadcast a parameter for Lattice Boltzmann.
void mpi_bcast_lb_params_slave (int node, int field)
void mpi_bcast_cuda_global_part_vars ()
Issue REQ_BCAST_cuda_global_part_vars: Broadcast a parameter for CUDA.
void mpi_bcast_cuda_global_part_vars_slave (int node, int dummy)
void mpi_send_exclusion (int part1, int part2, int _delete)
Issue REQ_SET_EXCLUSION: send exclusions.
void mpi_send_exclusion_slave (int part1, int part2)
void mpi_send_fluid (int node, int index, double rho, double *j, double *pi)
Issue REQ_SEND_FLUID: Send a single lattice site to a processor.
void mpi_send_fluid_slave (int node, int index)
void mpi_recv_fluid (int node, int index, double *rho, double *j, double *pi)
Issue REQ_GET_FLUID: Receive a single lattice site from a processor.
void mpi_recv_fluid_slave (int node, int index)
void mpi_recv_fluid_boundary_flag (int node, int index, int *boundary)
Issue REQ_LB_GET_BOUNDARY_FLAG: Receive a single lattice sites boundary flag from a processor.
void mpi_recv_fluid_boundary_flag_slave (int node, int index)
int mpi_iccp3m_iteration (int dummy)
Issue REQ_ICCP3M_ITERATION: performs iccp3m iteration.
void mpi_iccp3m_iteration_slave (int dummy, int dummy2)
int mpi_iccp3m_init (int n_induced_charges)
Issue REQ_ICCP3M_INIT: performs iccp3m initialization.
void mpi_iccp3m_init_slave (int node, int dummy)
void mpi_recv_fluid_populations (int node, int index, double *pop)
Issue REQ_RECV_FLUID_POPULATIONS: Send a single lattice site to a processor.
void mpi_recv_fluid_populations_slave (int node, int index)
void mpi_send_fluid_populations (int node, int index, double *pop)
Issue REQ_SEND_FLUID_POPULATIONS: Send a single lattice site to a processor.
void mpi_send_fluid_populations_slave (int node, int index)
void mpi_bcast_max_mu ()
Part of MDLC.
void mpi_bcast_max_mu_slave (int node, int dummy)
void mpi_set_particle_temperature (int pnode, int part, double _T)
Issue REQ_SEND_PARTICLE_T: send particle type specific temperature.
void mpi_set_particle_temperature_slave (int pnode, int part)
void mpi_set_particle_gamma (int pnode, int part, double gamma)
Issue REQ_SEND_PARTICLE_T: send particle type specific frictional coefficient.
void mpi_set_particle_gamma_slave (int pnode, int part)
void mpi_kill_particle_motion (int rotation)
Galilei and other: set all particle velocities and rotational inertias to zero.
void mpi_kill_particle_motion_slave (int pnode, int rotation)
void mpi_kill_particle_forces (int torque)
void mpi_kill_particle_forces_slave (int pnode, int torque)
void mpi_system_CMS ()
void mpi_system_CMS_slave (int node, int index)
void mpi_system_CMS_velocity ()
void mpi_system_CMS_velocity_slave (int node, int index)
void mpi_galilei_transform ()
void mpi_galilei_transform_slave (int pnode, int i)
void mpi_setup_reaction ()
Issue REQ_CATALYTIC_REACTIONS: notify the system of changes to the reaction parameters.
void mpi_setup_reaction_slave (int pnode, int i)
void mpi_thermalize_cpu (int temp)
CPU Thermostat.
void mpi_thermalize_cpu_slave (int node, int temp)
void mpi_loop ()
Process requests from master node.
void mpi_abort ()
Abort Espresso using MPI_Abort.
void mpi_external_potential_broadcast (int number)
void mpi_external_potential_broadcast_slave (int node, int number)
void mpi_external_potential_tabulated_read_potential_file (int number)
void mpi_external_potential_tabulated_read_potential_file_slave (int node, int number)
void mpi_external_potential_sum_energies ()
void mpi_external_potential_sum_energies_slave (int dummy1, int dummy2)
void mpi_gather_cuda_devices_slave (int dummy1, int dummy2)
Variables
int this_node = -1
The number of this node.
int n_nodes = -1
The total number of nodes.
MPI_Comm comm_cart
int graceful_exit = 0
static int terminated = 0
static SlaveCallback *const slave_callbacks []
const int N_CALLBACKS = sizeof(slave_callbacks)/sizeof(SlaveCallback*)
const char * names []
static int request [3]
The requests are compiled statically here, so that after a crash you can get the last issued request from the debugger.
Macro Definition Documentation
#define CALLBACK_LIST
Definition at line 83 of file communication.cpp.
#define CB (name) void name(int node, int param);
Definition at line 182 of file communication.cpp.
#define CB (name) name,
Definition at line 182 of file communication.cpp.
#define CB (name) #name,
Definition at line 182 of file communication.cpp.
#define SOME_TAG 42
Definition at line 189 of file communication.cpp.
Referenced by mpi_get_particles(), mpi_get_particles_slave(), mpi_place_new_particle(), mpi_place_new_particle_slave(), mpi_place_particle(), mpi_place_particle_slave(), mpi_recv_fluid(), mpi_recv_fluid_boundary_flag(), mpi_recv_fluid_boundary_flag_slave(), mpi_recv_fluid_populations(), mpi_recv_fluid_populations_slave(), mpi_recv_fluid_slave(), mpi_recv_part(), mpi_recv_part_slave(), mpi_rescale_particles(), mpi_rescale_particles_slave(), mpi_send_bond(), mpi_send_bond_slave(), mpi_send_configtemp_flag(), mpi_send_configtemp_flag_slave(), mpi_send_dip(), mpi_send_dip_slave(), mpi_send_dipm(), mpi_send_dipm_slave(), mpi_send_ext_force(), mpi_send_ext_force_slave(), mpi_send_ext_torque(), mpi_send_ext_torque_slave(), mpi_send_f(), mpi_send_f_slave(), mpi_send_fluid(), mpi_send_fluid_populations(), mpi_send_fluid_populations_slave(), mpi_send_fluid_slave(), mpi_send_mass(), mpi_send_mass_slave(), mpi_send_mol_id(), mpi_send_mol_id_slave(), mpi_send_mu_E(), mpi_send_mu_E_slave(), mpi_send_omega(), mpi_send_omega_slave(), mpi_send_q(), mpi_send_q_slave(), mpi_send_quat(), mpi_send_quat_slave(), mpi_send_rotation(), mpi_send_rotation_slave(), mpi_send_rotational_inertia(), mpi_send_rotational_inertia_slave(), mpi_send_smaller_timestep_flag(), mpi_send_smaller_timestep_flag_slave(), mpi_send_solvation(), mpi_send_solvation_slave(), mpi_send_swimming(), mpi_send_swimming_slave(), mpi_send_torque(), mpi_send_torque_slave(), mpi_send_type(), mpi_send_type_slave(), mpi_send_v(), mpi_send_v_slave(), mpi_send_virtual(), mpi_send_virtual_slave(), mpi_send_vs_relative(), mpi_send_vs_relative_slave(), mpi_set_particle_gamma(), mpi_set_particle_gamma_slave(), mpi_set_particle_temperature(), mpi_set_particle_temperature_slave(), mpi_system_CMS(), mpi_system_CMS_slave(), mpi_system_CMS_velocity(), mpi_system_CMS_velocity_slave(), mpi_who_has(), and mpi_who_has_slave().
Function Documentation
static void common_bcast_parameter (int i) static
Definition at line 293 of file communication.cpp.
References comm_cart, fields, MPI_Bcast(), MPI_DOUBLE, MPI_INT, on_parameter_change(), TYPE_BOOL, TYPE_DOUBLE, and TYPE_INT.
Referenced by mpi_bcast_parameter(), and mpi_bcast_parameter_slave().
void mpi_abort ()
Abort Espresso using MPI_Abort.
Definition at line 3058 of file communication.cpp.
References comm_cart, MPI_Abort(), and terminated.
Referenced by errexit().
void mpi_bcast_cell_structure (int cs)
Issue REQ_BCAST_CS: change the cell structure on all nodes.
Definition at line 2407 of file communication.cpp.
References cells_re_init(), mpi_bcast_cell_structure_slave(), and mpi_call().
Referenced by tclcommand_cellsystem().
void mpi_bcast_cell_structure_slave (int pnode, int cs)
Definition at line 2413 of file communication.cpp.
References cells_re_init().
Referenced by mpi_bcast_cell_structure().
void mpi_bcast_collision_params ()
send new collision parameters.
Definition at line 1957 of file communication.cpp.
References mpi_bcast_collision_params_slave(), and mpi_call().
Referenced by collision_detection_set_params().
void mpi_bcast_collision_params_slave (int node, int parm)
Definition at line 1965 of file communication.cpp.
References collision_params, comm_cart, MPI_Bcast(), MPI_BYTE, and recalc_forces.
Referenced by mpi_bcast_collision_params().
void mpi_bcast_constraint (int del_num)
Issue REQ_BCAST_COULOMB: send new coulomb parameters.
Definition at line 2074 of file communication.cpp.
References comm_cart, constraints, MPI_Bcast(), mpi_bcast_constraint_slave(), MPI_BYTE, mpi_call(), n_constraints, on_constraint_change(), and realloc.
Referenced by tclcommand_constraint().
void mpi_bcast_constraint_slave (int node, int parm)
Definition at line 2098 of file communication.cpp.
References comm_cart, constraints, MPI_Bcast(), MPI_BYTE, n_constraints, on_constraint_change(), and realloc.
Referenced by mpi_bcast_constraint().
void mpi_bcast_coulomb_params ()
Issue REQ_BCAST_COULOMB: send new coulomb parameters.
Definition at line 1873 of file communication.cpp.
References mpi_bcast_coulomb_params_slave(), and mpi_call().
Referenced by EwaldgpuForce::adaptive_tune(), coulomb_set_bjerrum(), dawaanr_set_params(), dh_set_params(), dipolar_set_Dbjerrum(), maggs_set_parameters(), mdds_set_params(), mdlc_set_params(), MMM1D_set_params(), mmm1d_tune(), MMM2D_set_params(), rf_set_params(), tclcommand_inter_coulomb_parse_ewaldgpu_notune(), tclcommand_inter_coulomb_parse_ewaldgpu_tune(), tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha(), tclcommand_inter_coulomb_parse_mmm1dgpu(), tclcommand_inter_parse_coulomb(), and tclcommand_inter_parse_magnetic().
void mpi_bcast_coulomb_params_slave (int node, int parm)
Definition at line 1881 of file communication.cpp.
References comm_cart, coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_EWALD_GPU, COULOMB_INTER_RF, COULOMB_MAGGS, COULOMB_MMM1D, COULOMB_MMM1D_GPU, COULOMB_MMM2D, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, dh_params, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, dlc_params, Coulomb_parameters::Dmethod, errexit(), ewaldgpu_params, maggs, Coulomb_parameters::method, mmm1d_params, mmm2d_params, MPI_Bcast(), MPI_BYTE, on_coulomb_change(), rf_params, and this_node.
Referenced by mpi_bcast_coulomb_params().
void mpi_bcast_cuda_global_part_vars ()
Issue REQ_BCAST_cuda_global_part_vars: Broadcast a parameter for CUDA.
Definition at line 2554 of file communication.cpp.
References mpi_bcast_cuda_global_part_vars_slave(), and mpi_call().
void mpi_bcast_cuda_global_part_vars_slave (int node, int dummy)
Definition at line 2561 of file communication.cpp.
References comm_cart, espressoSystemInterface, gpu_get_global_particle_vars_pointer_host(), MPI_Bcast(), and MPI_BYTE.
Referenced by mpi_bcast_cuda_global_part_vars().
void mpi_bcast_event (int event)
Issue REQ_EVENT: tells all clients of some system change.
The events are:
PARTICLE_CHANGED
INTERACTION_CHANGED
Then all nodes execute the respective on_* procedure from initialize.cpp Note that not all of these codes are used. Since some actions (like placing a particle) include communication anyways, this is handled by the way.
Definition at line 398 of file communication.cpp.
References mpi_bcast_event_slave(), and mpi_call().
Referenced by tclcommand_part_parse_cmd(), and tclcommand_sort_particles().
void mpi_bcast_event_slave (int node, int event)
Definition at line 404 of file communication.cpp.
References check_particles(), CHECK_PARTICLES, local_sort_particles(), maggs_count_charged_particles(), MAGGS_COUNT_CHARGES, P3M_COUNT_CHARGES, P3M_COUNT_DIPOLES, and SORT_PARTICLES.
Referenced by mpi_bcast_event().
void mpi_bcast_ia_params (int i, int j)
Issue REQ_BCAST_IA: send new ia params.
Also calls on_short_range_ia_change.
mpi_bcast_ia_params is used for both, bonded and non-bonded interaction parameters. Therefor i and j are used depending on their value:
Parameters
i particle type for non bonded interaction parameters / bonded interaction type number.
j if not negative: particle type for non bonded interaction parameters / if negative: flag for bonded interaction
Definition at line 1288 of file communication.cpp.
References BONDED_IA_OVERLAPPED, bonded_ia_params, BONDED_IA_TABULATED, comm_cart, copy_ia_params(), DoubleList::e, get_ia_param(), i, DoubleList::max, MPI_Bcast(), mpi_bcast_ia_params_slave(), MPI_BYTE, mpi_call(), MPI_DOUBLE, MPI_INT, Overlap_bond_parameters::noverlaps, Tabulated_bond_parameters::npoints, on_short_range_ia_change(), Bond_parameters::overlap, Bonded_ia_parameters::p, Bond_parameters::tab, tabulated_energies, and tabulated_forces.
Referenced by affinity_set_params(), angle_cosine_set_params(), angle_cossquare_set_params(), angle_harmonic_set_params(), angle_set_params(), angledist_set_params(), area_force_global_set_params(), area_force_local_set_params(), bending_force_set_params(), BMHTF_set_params(), bonded_coulomb_set_params(), buckingham_set_params(), comfixed_set_params(), comforce_set_params(), cos2_set_params(), dihedral_set_params(), endangledist_set_params(), fene_set_params(), gaussian_set_params(), gay_berne_set_params(), harmonic_dumbbell_set_params(), harmonic_set_params(), hat_set_params(), hertzian_set_params(), hydrogen_bond_set_params(), IBM_InitVolumeConservation(), IBM_Tribend_ResetParams(), IBM_Tribend_SetParams(), IBM_Triel_ResetParams(), IBM_Triel_SetParams(), IBM_VolumeConservation_ResetParams(), IBM_VolumeConservation_SetParams(), inter_dpd_set_params(), interrf_set_params(), lennard_jones_set_params(), lj_cos_set_params(), ljangle_set_params(), ljcos2_set_params(), ljgen_set_params(), local_setup_reaction(), molcut_set_params(), morse_set_params(), overlapped_bonded_set_params(), quartic_set_params(), rigid_bond_set_params(), smooth_step_set_params(), soft_sphere_set_params(), stretching_force_set_params(), stretchlin_force_set_params(), subt_lj_set_params(), tabulated_bonded_set_params(), tabulated_set_params(), tunable_slip_set_params(), twist_stack_set_params(), umbrella_set_params(), virtual_set_params(), and volume_force_set_params().
void mpi_bcast_ia_params_slave (int i, int j)
Definition at line 1341 of file communication.cpp.
References BONDED_IA_OVERLAPPED, bonded_ia_params, BONDED_IA_TABULATED, comm_cart, copy_ia_params(), DoubleList::e, Tabulated_bond_parameters::e, Tabulated_bond_parameters::f, get_ia_param(), i, make_bond_type_exist(), malloc, MPI_Bcast(), MPI_BYTE, MPI_DOUBLE, MPI_INT, Overlap_bond_parameters::noverlaps, Tabulated_bond_parameters::npoints, on_short_range_ia_change(), Bond_parameters::overlap, Bonded_ia_parameters::p, Overlap_bond_parameters::para_a, Overlap_bond_parameters::para_b, Overlap_bond_parameters::para_c, realloc_doublelist(), Bond_parameters::tab, tabulated_energies, and tabulated_forces.
Referenced by mpi_bcast_ia_params().
void mpi_bcast_lb_params (int field)
Issue REQ_BCAST_LBPAR: Broadcast a parameter for Lattice Boltzmann.
Parameters
field References the parameter field to be broadcasted. The references are defined in lb.hpp
Definition at line 2535 of file communication.cpp.
References mpi_bcast_lb_params_slave(), and mpi_call().
Referenced by lb_lbfluid_load_checkpoint(), lb_lbfluid_set_agrid(), lb_lbfluid_set_bulk_visc(), lb_lbfluid_set_density(), lb_lbfluid_set_ext_force(), lb_lbfluid_set_friction(), lb_lbfluid_set_gamma_even(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_tau(), and lb_lbfluid_set_visc().
void mpi_bcast_lb_params_slave (int node, int field)
Definition at line 2543 of file communication.cpp.
References comm_cart, lbpar, MPI_Bcast(), MPI_BYTE, and on_lb_params_change().
Referenced by mpi_bcast_lb_params().
void mpi_bcast_lbboundary (int del_num)
Issue REQ_LB_BOUNDARY: set up walls for lb fluid.
Definition at line 2122 of file communication.cpp.
References comm_cart, lb_boundaries, MPI_Bcast(), mpi_bcast_lbboundary_slave(), MPI_BYTE, mpi_call(), n_lb_boundaries, on_lbboundary_change(), and realloc.
Referenced by tclcommand_lbboundary().
void mpi_bcast_lbboundary_slave (int node, int parm)
Definition at line 2151 of file communication.cpp.
References comm_cart, lb_boundaries, MPI_Bcast(), MPI_BYTE, n_lb_boundaries, on_lbboundary_change(), and realloc.
Referenced by mpi_bcast_lbboundary().
void mpi_bcast_max_mu ()
Part of MDLC.
Definition at line 2784 of file communication.cpp.
References calc_mu_max(), mpi_bcast_max_mu_slave(), and mpi_call().
Referenced by mdlc_tune().
void mpi_bcast_max_mu_slave (int node, int dummy)
Definition at line 2793 of file communication.cpp.
References calc_mu_max().
Referenced by mpi_bcast_max_mu().
void mpi_bcast_n_particle_types (int s)
Issue REQ_BCAST_IA_SIZE: send new size of ia_params.
Parameters
s the new size for ia_params.
Definition at line 1401 of file communication.cpp.
References mpi_bcast_n_particle_types_slave(), and mpi_call().
Referenced by make_particle_type_exist().
void mpi_bcast_n_particle_types_slave (int pnode, int ns)
Definition at line 1408 of file communication.cpp.
References realloc_ia_params().
Referenced by mpi_bcast_n_particle_types().
void mpi_bcast_nptiso_geom (void)
Issue REQ_BCAST_NPTISO_GEOM: broadcast nptiso geometry parameter to all nodes.
Definition at line 2420 of file communication.cpp.
References mpi_bcast_nptiso_geom_slave(), and mpi_call().
Referenced by integrate_set_npt_isotropic(), and tclcommand_integrate_set_npt_isotropic().
void mpi_bcast_nptiso_geom_slave (int node, int parm)
Definition at line 2427 of file communication.cpp.
References comm_cart, nptiso_struct::cubic_box, nptiso_struct::dimension, nptiso_struct::geometry, MPI_Bcast(), MPI_INT, nptiso_struct::non_const_dim, and nptiso.
Referenced by mpi_bcast_nptiso_geom().
int mpi_bcast_parameter (int i)
Issue REQ_BCAST_PAR: broadcast a parameter from datafield.
Parameters
i the number from global.hpp referencing the datafield.
Returns
nonzero on error
Definition at line 314 of file communication.cpp.
References check_runtime_errors(), common_bcast_parameter(), mpi_bcast_parameter_slave(), and mpi_call().
Referenced by dpd_switch_off(), ghmc_mc(), integrate_set_npt_isotropic(), integrate_set_nvt(), python_integrate(), remove_particle(), rescale_boxl(), rigid_bond_set_params(), tclcallback_box_l(), tclcallback_max_num_cells(), tclcallback_min_global_cut(), tclcallback_min_num_cells(), tclcallback_node_grid(), tclcallback_npt_p_diff(), tclcallback_npt_piston(), tclcallback_p_ext(), tclcallback_periodicity(), tclcallback_sd_radius(), tclcallback_sd_random_precision(), tclcallback_sd_random_state(), tclcallback_sd_seed(), tclcallback_sd_viscosity(), tclcallback_skin(), tclcallback_time(), tclcommand_cellsystem(), tclcommand_integrate(), tclcommand_integrate_set_npt_isotropic(), tclcommand_integrate_set_nvt(), tclcommand_lbfluid(), tclcommand_lees_edwards_offset(), tclcommand_thermostat_parse_bd(), tclcommand_thermostat_parse_cpu(), tclcommand_thermostat_parse_dpd(), tclcommand_thermostat_parse_ghmc(), tclcommand_thermostat_parse_inter_dpd(), tclcommand_thermostat_parse_langevin(), tclcommand_thermostat_parse_lb(), tclcommand_thermostat_parse_npt_isotropic(), tclcommand_thermostat_parse_off(), and tclcommand_thermostat_parse_sd().
void mpi_bcast_parameter_slave (int node, int i)
Definition at line 323 of file communication.cpp.
References check_runtime_errors(), and common_bcast_parameter().
Referenced by mpi_bcast_parameter().
void mpi_bit_random_seed (int cnt, int * seed)
Issue REQ_BIT_RANDOM_SEED: read/set seed of the bit random number generators on each node.
Definition at line 2326 of file communication.cpp.
References comm_cart, init_bit_random_generator(), mpi_bit_random_seed_slave(), mpi_call(), MPI_Gather(), MPI_INT, MPI_Scatter(), print_bit_random_seed(), RANDOM_TRACE, and this_node.
Referenced by tclcommand_bit_random().
void mpi_bit_random_seed_slave (int pnode, int cnt)
Definition at line 2341 of file communication.cpp.
References comm_cart, init_bit_random_generator(), MPI_Gather(), MPI_INT, MPI_Scatter(), print_bit_random_seed(), RANDOM_TRACE, and this_node.
Referenced by mpi_bit_random_seed().
void mpi_bit_random_stat (int cnt, BitRandomStatus * stat)
Issue REQ_BIT_RANDOM_STAT: read/set status of the bit random number generators on each node.
Definition at line 2355 of file communication.cpp.
References comm_cart, init_bit_random_stat(), mpi_bit_random_stat_slave(), MPI_BYTE, mpi_call(), MPI_Gather(), MPI_Scatter(), print_bit_random_stat(), BitRandomStatus::random_pointer_1, BitRandomStatus::random_pointer_2, RANDOM_TRACE, and this_node.
Referenced by tclcommand_bit_random().
void mpi_bit_random_stat_slave (int pnode, int cnt)
Definition at line 2370 of file communication.cpp.
References comm_cart, init_bit_random_stat(), MPI_BYTE, MPI_Gather(), MPI_Scatter(), print_bit_random_stat(), BitRandomStatus::random_pointer_1, BitRandomStatus::random_pointer_2, RANDOM_TRACE, and this_node.
Referenced by mpi_bit_random_stat().
void mpi_call (SlaveCallback cb, int node, int param)
Definition at line 263 of file communication.cpp.
Referenced by mpi_bcast_cell_structure(), mpi_bcast_collision_params(), mpi_bcast_constraint(), mpi_bcast_coulomb_params(), mpi_bcast_cuda_global_part_vars(), mpi_bcast_event(), mpi_bcast_ia_params(), mpi_bcast_lb_params(), mpi_bcast_lbboundary(), mpi_bcast_max_mu(), mpi_bcast_n_particle_types(), mpi_bcast_nptiso_geom(), mpi_bcast_parameter(), mpi_bit_random_seed(), mpi_bit_random_stat(), mpi_cap_forces(), mpi_external_potential_broadcast(), mpi_external_potential_sum_energies(), mpi_external_potential_tabulated_read_potential_file(), mpi_galilei_transform(), mpi_gather_stats(), mpi_get_configtemp(), mpi_get_constraint_force(), mpi_get_particles(), mpi_iccp3m_init(), mpi_iccp3m_iteration(), mpi_integrate(), mpi_kill_particle_forces(), mpi_kill_particle_motion(), mpi_local_stress_tensor(), mpi_minimize_energy(), mpi_observable_lb_radial_velocity_profile(), mpi_place_new_particle(), mpi_place_particle(), mpi_random_seed(), mpi_random_stat(), mpi_recv_fluid(), mpi_recv_fluid_boundary_flag(), mpi_recv_fluid_populations(), mpi_recv_part(), mpi_remove_particle(), mpi_rescale_particles(), mpi_send_bond(), mpi_send_configtemp_flag(), mpi_send_dip(), mpi_send_dipm(), mpi_send_exclusion(), mpi_send_ext_force(), mpi_send_ext_torque(), mpi_send_f(), mpi_send_fluid(), mpi_send_fluid_populations(), mpi_send_mass(), mpi_send_mol_id(), mpi_send_mu_E(), mpi_send_omega(), mpi_send_q(), mpi_send_quat(), mpi_send_rotation(), mpi_send_rotational_inertia(), mpi_send_smaller_timestep_flag(), mpi_send_solvation(), mpi_send_swimming(), mpi_send_torque(), mpi_send_type(), mpi_send_v(), mpi_send_virtual(), mpi_send_vs_relative(), mpi_set_particle_gamma(), mpi_set_particle_temperature(), mpi_set_smaller_time_step(), mpi_set_time_step(), mpi_setup_reaction(), mpi_stop(), mpi_sync_topo_part_info(), mpi_system_CMS(), mpi_system_CMS_velocity(), mpi_thermalize_cpu(), mpi_update_mol_ids(), mpi_who_has(), and mpiRuntimeErrorCollectorGather().
void mpi_cap_forces (double force_cap)
Issue REQ_BCAST_LJFORCECAP: initialize LJ force capping.
Definition at line 2246 of file communication.cpp.
References force_cap, mpi_call(), and mpi_cap_forces_slave().
Referenced by buckingham_set_params(), forcecap_set_params(), lennard_jones_set_params(), ljangle_set_params(), ljcos2_set_params(), ljforcecap_set_params(), ljgen_set_params(), morse_set_params(), and tabulated_set_params().
void mpi_cap_forces_slave (int node, int parm)
Definition at line 2253 of file communication.cpp.
References calc_buck_cap_radii(), calc_lj_cap_radii(), calc_ljangle_cap_radii(), calc_ljcos2_cap_radii(), calc_ljgen_cap_radii(), calc_morse_cap_radii(), comm_cart, force_cap, MPI_Bcast(), MPI_DOUBLE, and on_short_range_ia_change().
Referenced by mpi_cap_forces().
void mpi_core (MPI_Comm * comm, int * errcode, ...)
Definition at line 200 of file communication.cpp.
References core(), MPI_Error_string(), and this_node.
Referenced by mpi_init().
void mpi_external_potential_broadcast (int number)
Definition at line 3068 of file communication.cpp.
References comm_cart, external_potentials, MPI_Bcast(), MPI_BYTE, mpi_call(), MPI_DOUBLE, mpi_external_potential_broadcast_slave(), and n_particle_types.
Referenced by external_potential_tabulated_init().
void mpi_external_potential_broadcast_slave (int node, int number)
Definition at line 3074 of file communication.cpp.
References comm_cart, external_potentials, generate_external_potential(), malloc, MPI_Bcast(), MPI_BYTE, MPI_DOUBLE, n_particle_types, and ExternalPotential::scale.
Referenced by mpi_external_potential_broadcast().
void mpi_external_potential_sum_energies ()
Definition at line 3093 of file communication.cpp.
References comm_cart, ExternalPotential::energy, external_potentials, free, i, malloc, mpi_call(), MPI_DOUBLE, mpi_external_potential_sum_energies_slave(), MPI_Reduce(), MPI_SUM, and n_external_potentials.
void mpi_external_potential_sum_energies_slave (int dummy1, int dummy2)
Definition at line 3109 of file communication.cpp.
References comm_cart, ExternalPotential::energy, external_potentials, free, i, malloc, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, and n_external_potentials.
Referenced by mpi_external_potential_sum_energies().
void mpi_external_potential_tabulated_read_potential_file (int number)
Definition at line 3084 of file communication.cpp.
References external_potential_tabulated_read_potential_file(), mpi_call(), and mpi_external_potential_tabulated_read_potential_file_slave().
Referenced by external_potential_tabulated_init().
void mpi_external_potential_tabulated_read_potential_file_slave (int node, int number)
Definition at line 3089 of file communication.cpp.
References external_potential_tabulated_read_potential_file().
Referenced by mpi_external_potential_tabulated_read_potential_file().
void mpi_galilei_transform ()
Definition at line 2981 of file communication.cpp.
References galilei_struct::cms_vel, comm_cart, gal, local_galilei_transform(), MPI_Bcast(), mpi_call(), MPI_DOUBLE, mpi_galilei_transform_slave(), mpi_system_CMS_velocity(), and on_particle_change().
Referenced by tclcommand_galilei_transform().
void mpi_galilei_transform_slave (int pnode, int i)
Definition at line 2996 of file communication.cpp.
References comm_cart, local_galilei_transform(), MPI_Bcast(), MPI_DOUBLE, and on_particle_change().
Referenced by mpi_galilei_transform().
void mpi_gather_cuda_devices_slave (int dummy1, int dummy2)
Definition at line 3125 of file communication.cpp.
References cuda_gather_gpus().
void mpi_gather_stats (int job, void * result, void * result_t, void * result_nb, void * result_t_nb)
Issue REQ_GATHER: gather data for analysis in analyze.
Parameters
job what to do:
1 calculate and reduce (sum up) energies, using energy_calc.
2 calculate and reduce (sum up) pressure, stress tensor, using pressure_calc.
3 calculate and reduce (sum up) instantaneous pressure, using pressure_calc.
result where to store the gathered value(s):
job=1 unused (the results are stored in a global energy array of type Observable_stat)
job=2 unused (the results are stored in a global virials array of type Observable_stat)
job=3 unused (the results are stored in a global virials array of type Observable_stat)
result_t where to store the gathered value(s):
job=1 unused (the results are stored in a global energy array of type Observable_stat)
job=2 unused (the results are stored in a global p_tensor tensor of type Observable_stat)
job=3 unused (the results are stored in a global p_tensor tensor of type Observable_stat)
result_nb where to store the gathered value(s):
job=1 unused (the results are stored in a global energy array of type Observable_stat_non_bonded)
job=2 unused (the results are stored in a global virials_non_bonded array of type Observable_stat_non_bonded)
job=3 unused (the results are stored in a global virials_non_bonded array of type Observable_stat_non_bonded)
result_t_nb where to store the gathered value(s):
job=1 unused (the results are stored in a global energy array of type Observable_stat_non_bonded)
job=2 unused (the results are stored in a global p_tensor_non_bonded tensor of type Observable_stat_non_bonded)
job=3 unused (the results are stored in a global p_tensor_non_bonded tensor of type Observable_stat_non_bonded)
Definition at line 1414 of file communication.cpp.
References energy_calc(), errexit(), lb_calc_fluid_mass(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_collect_boundary_forces(), mpi_call(), mpi_gather_stats_slave(), predict_momentum_particles(), pressure_calc(), and this_node.
Referenced by calc_linear_momentum(), lb_master_calc_densprof(), lb_master_calc_velprof(), lbboundary_get_force(), master_energy_calc(), master_pressure_calc(), momentum_calc(), tclcommand_analyze_fluid_parse_mass(), tclcommand_analyze_fluid_parse_momentum(), tclcommand_analyze_fluid_parse_temp(), and tclcommand_analyze_parse_and_print_momentum().
void mpi_gather_stats_slave (int ana_num, int job)
Definition at line 1463 of file communication.cpp.
References energy_calc(), errexit(), lb_calc_fluid_mass(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_collect_boundary_forces(), predict_momentum_particles(), pressure_calc(), and this_node.
Referenced by mpi_gather_stats().
void mpi_get_configtemp (double cfgtmp[2])
Definition at line 2308 of file communication.cpp.
References comm_cart, configtemp, mpi_call(), MPI_DOUBLE, mpi_get_configtemp_slave(), MPI_Reduce(), and MPI_SUM.
void mpi_get_configtemp_slave (int node, int cnt)
Definition at line 2317 of file communication.cpp.
References comm_cart, configtemp, MPI_DOUBLE, MPI_Reduce(), and MPI_SUM.
Referenced by mpi_get_configtemp().
void mpi_get_constraint_force (int constraint, double force[3])
Issue REQ_BCAST_MORSEFORCECAP: initialize Morse force capping.
Issue REQ_BCAST_BUCKFORCECAP: initialize Buckingham force capping. Issue REQ_BCAST_TABFORCECAP: initialize tabulated force capping. Issue REQ_GET_CONSFOR: get force acting on constraint
Definition at line 2292 of file communication.cpp.
References comm_cart, constraints, mpi_call(), MPI_DOUBLE, mpi_get_constraint_force_slave(), MPI_Reduce(), and MPI_SUM.
Referenced by tclprint_to_result_ConstraintForce().
void mpi_get_constraint_force_slave (int node, int parm)
Definition at line 2300 of file communication.cpp.
References comm_cart, constraints, MPI_DOUBLE, MPI_Reduce(), and MPI_SUM.
Referenced by mpi_get_constraint_force().
void mpi_get_particles (Particle * result, IntList * il)
Issue REQ_GETPARTS: gather all particle informations (except bonds).
This is slow and may use huge amounts of memory. If il is non-NULL, also the bonding information is also fetched and stored in a single intlist pointed to by il. The particles bonding information references this array, which is the only data you have to free later (besides the result array you allocated). YOU MUST NOT CALL free_particle on any of these particles!
Parameters
result where to store the gathered particles
il if non-NULL, the integerlist where to store the bonding info
Definition at line 1578 of file communication.cpp.
References Particle::bl, CellPList::cell, cells_get_n_particles(), comm_cart, COMM_TRACE, ParticlePosition::dip, IntList::e, errexit(), free, i, init_intlist(), local_cells, malloc, MPI_BYTE, mpi_call(), MPI_Gather(), mpi_get_particles_slave(), MPI_INT, MPI_Recv(), MPI_STATUS_IGNORE, IntList::n, CellPList::n, ParticleList::n, n_nodes, n_part, ParticlePosition::p, Particle::p, ParticleList::part, ParticleProperties::q, Particle::r, realloc_intlist(), SOME_TAG, this_node, and ParticleProperties::type.
Referenced by EwaldgpuForce::adaptive_tune(), collectBonds(), mindist3(), mindist4(), tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha(), and updatePartCfg().
void mpi_get_particles_slave (int pnode, int bi)
Definition at line 1692 of file communication.cpp.
References Particle::bl, CellPList::cell, cells_get_n_particles(), comm_cart, COMM_TRACE, IntList::e, free, init_intlist(), local_cells, malloc, MPI_BYTE, MPI_Gather(), MPI_INT, MPI_Send(), IntList::n, CellPList::n, ParticleList::n, n_part, ParticleList::part, realloc_intlist(), SOME_TAG, and this_node.
Referenced by mpi_get_particles().
int mpi_iccp3m_init (int dummy)
Issue REQ_ICCP3M_INIT: performs iccp3m initialization.
Returns
nonzero on error
Definition at line 2702 of file communication.cpp.
References bcast_iccp3m_cfg(), check_runtime_errors(), COMM_TRACE, mpi_call(), mpi_iccp3m_init_slave(), and this_node.
Referenced by tclcommand_iccp3m().
void mpi_iccp3m_init_slave (int node, int dummy)
Definition at line 2722 of file communication.cpp.
References bcast_iccp3m_cfg(), check_runtime_errors(), COMM_TRACE, iccp3m_init(), iccp3m_initialized, and this_node.
Referenced by mpi_iccp3m_init().
int mpi_iccp3m_iteration (int dummy)
Issue REQ_ICCP3M_ITERATION: performs iccp3m iteration.
Returns
nonzero on error
Definition at line 2675 of file communication.cpp.
References check_runtime_errors(), COMM_TRACE, iccp3m_iteration(), mpi_call(), mpi_iccp3m_iteration_slave(), and this_node.
Referenced by tclcommand_iccp3m().
void mpi_iccp3m_iteration_slave (int dummy, int dummy2)
Definition at line 2691 of file communication.cpp.
References check_runtime_errors(), COMM_TRACE, and iccp3m_iteration().
Referenced by mpi_iccp3m_iteration().
void mpi_init (int * argc = NULL, char *** argv = NULL)
Initialize MPI and determine n_nodes and this_node.
Definition at line 209 of file communication.cpp.
References comm_cart, initRuntimeErrorCollector(), MPI_Cart_coords(), MPI_Cart_create(), MPI_Comm_create_errhandler(), MPI_Comm_rank(), MPI_Comm_set_errhandler(), MPI_Comm_size(), MPI_COMM_WORLD, mpi_core(), MPI_Dims_create(), MPI_Init(), n_nodes, node_grid, node_pos, periodic, and this_node.
Referenced by main().
int mpi_integrate (int n_steps, int reuse_forces)
Issue REQ_INTEGRATE: start integrator.
Parameters
n_steps how many steps to do.
reuse_forces whether to trust the old forces for the first half step
Returns
nonzero on error
Definition at line 1255 of file communication.cpp.
References autoupdate_correlations(), check_runtime_errors(), COMM_TRACE, correlations_autoupdate, i, integrate_vv(), mpi_call(), mpi_integrate_slave(), and this_node.
Referenced by python_integrate(), tclcommand_integrate(), and time_force_calc().
void mpi_integrate_slave (int n_steps, int reuse_forces)
Definition at line 1279 of file communication.cpp.
References check_runtime_errors(), COMM_TRACE, integrate_vv(), and this_node.
Referenced by mpi_integrate().
void mpi_kill_particle_forces (int torque)
Definition at line 2886 of file communication.cpp.
References local_kill_particle_forces(), mpi_call(), mpi_kill_particle_forces_slave(), and on_particle_change().
Referenced by tclcommand_kill_particle_forces().
void mpi_kill_particle_forces_slave (int pnode, int torque)
Definition at line 2893 of file communication.cpp.
References local_kill_particle_forces(), and on_particle_change().
Referenced by mpi_kill_particle_forces().
void mpi_kill_particle_motion (int rotation)
Galilei and other: set all particle velocities and rotational inertias to zero.
set all forces and torques on the particles to zero calculate the centre of mass (CMS) calculate the velocity of the CMS remove the CMS velocity from the system
Definition at line 2873 of file communication.cpp.
References local_kill_particle_motion(), mpi_call(), mpi_kill_particle_motion_slave(), and on_particle_change().
Referenced by tclcommand_kill_particle_motion().
void mpi_kill_particle_motion_slave (int pnode, int rotation)
Definition at line 2880 of file communication.cpp.
References local_kill_particle_motion(), and on_particle_change().
Referenced by mpi_kill_particle_motion().
void mpi_local_stress_tensor (DoubleList * TensorInBin, int bins[3], int periodic[3], double range_start[3], double range[3])
Issue GET_LOCAL_STRESS_TENSOR: gather the contribution to the local stress tensors from each node.
Definition at line 1504 of file communication.cpp.
References alloc_doublelist(), comm_cart, DoubleList::e, i, init_doublelist(), local_stress_tensor_calc(), malloc, MPI_Bcast(), mpi_call(), MPI_DOUBLE, MPI_INT, mpi_local_stress_tensor_slave(), MPI_Reduce(), MPI_SUM, PTENSOR_TRACE, and this_node.
Referenced by analyze_local_stress_tensor(), and tclcommand_analyze_parse_local_stress_tensor().
void mpi_local_stress_tensor_slave (int ana_num, int job)
Definition at line 1538 of file communication.cpp.
References alloc_doublelist(), comm_cart, DoubleList::e, free, i, init_doublelist(), local_stress_tensor_calc(), malloc, MPI_Bcast(), MPI_DOUBLE, MPI_INT, MPI_Reduce(), MPI_SUM, periodic, PTENSOR_TRACE, realloc_doublelist(), and this_node.
Referenced by mpi_local_stress_tensor().
void mpi_loop ()
Process requests from master node.
Slave nodes main loop.
Definition at line 3036 of file communication.cpp.
References comm_cart, COMM_TRACE, errexit(), MPI_Barrier(), MPI_Bcast(), MPI_INT, slave_callbacks, and this_node.
Referenced by main().
int mpi_minimize_energy (void)
Issue REQ_MIN_ENERGY: start energy minimization.
Returns
nonzero on error
Definition at line 1245 of file communication.cpp.
References minimize_energy(), mpi_call(), and mpi_minimize_energy_slave().
Referenced by tclcommand_minimize_energy().
void mpi_minimize_energy_slave (int a, int b)
Definition at line 1250 of file communication.cpp.
References minimize_energy().
Referenced by mpi_minimize_energy().
void mpi_observable_lb_radial_velocity_profile ()
Definition at line 1091 of file communication.cpp.
References mpi_call(), and mpi_observable_lb_radial_velocity_profile_slave().
Referenced by observable_calc_lb_radial_velocity_profile().
void mpi_observable_lb_radial_velocity_profile_slave (int pnode, int part)
Definition at line 1097 of file communication.cpp.
References mpi_observable_lb_radial_velocity_profile_slave_implementation().
Referenced by mpi_observable_lb_radial_velocity_profile().
void mpi_place_new_particle (int node, int id, double pos[3])
Issue REQ_PLACE: create particle at a position on a node.
Also calls on_particle_change.
Parameters
id the particle to create.
node the node to attach it to.
pos the particles position.
Definition at line 460 of file communication.cpp.
References added_particle(), comm_cart, local_place_particle(), mpi_call(), MPI_DOUBLE, mpi_place_new_particle_slave(), MPI_Send(), on_particle_change(), SOME_TAG, and this_node.
Referenced by place_particle().
void mpi_place_new_particle_slave (int pnode, int part)
Definition at line 474 of file communication.cpp.
References added_particle(), comm_cart, local_place_particle(), MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), SOME_TAG, and this_node.
Referenced by mpi_place_new_particle().
void mpi_place_particle (int node, int id, double pos[3])
Issue REQ_PLACE: move particle to a position on a node.
Also calls on_particle_change.
Parameters
id the particle to move.
node the node to attach it to.
pos the particles position.
Definition at line 436 of file communication.cpp.
References comm_cart, local_place_particle(), mpi_call(), MPI_DOUBLE, mpi_place_particle_slave(), MPI_Send(), on_particle_change(), SOME_TAG, and this_node.
Referenced by place_particle().
void mpi_place_particle_slave (int pnode, int part)
Definition at line 448 of file communication.cpp.
References comm_cart, local_place_particle(), MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), SOME_TAG, and this_node.
Referenced by mpi_place_particle().
void mpi_random_seed (int cnt, long * seed)
Issue REQ_RANDOM_SEED: read/set seed of random number generators on each node.
Definition at line 2183 of file communication.cpp.
References comm_cart, init_random_seed(), mpi_call(), MPI_Gather(), MPI_LONG, mpi_random_seed_slave(), MPI_Scatter(), print_random_seed(), RANDOM_TRACE, and this_node.
Referenced by tclcommand_t_random().
void mpi_random_seed_slave (int pnode, int cnt)
Definition at line 2198 of file communication.cpp.
References comm_cart, init_random_seed(), MPI_Gather(), MPI_LONG, MPI_Scatter(), print_random_seed(), RANDOM_TRACE, and this_node.
Referenced by mpi_random_seed().
void mpi_random_stat (int cnt, RandomStatus * stat)
Issue REQ_RANDOM_STAT: read/set status of random number generators on each node.
Definition at line 2212 of file communication.cpp.
References comm_cart, RandomStatus::idum, init_random_stat(), RandomStatus::iy, MPI_BYTE, mpi_call(), MPI_Gather(), mpi_random_stat_slave(), MPI_Scatter(), print_random_stat(), RANDOM_TRACE, and this_node.
Referenced by tclcommand_t_random().
void mpi_random_stat_slave (int pnode, int cnt)
Definition at line 2227 of file communication.cpp.
References comm_cart, RandomStatus::idum, init_random_stat(), RandomStatus::iy, MPI_BYTE, MPI_Gather(), MPI_Scatter(), print_random_stat(), RANDOM_TRACE, and this_node.
Referenced by mpi_random_stat().
void mpi_recv_fluid (int node, int index, double * rho, double * j, double * pi)
Issue REQ_GET_FLUID: Receive a single lattice site from a processor.
Parameters
node processor to send to
index index of the lattice site
rho local fluid density
j local fluid velocity
pi local fluid pressure
Definition at line 2617 of file communication.cpp.
References comm_cart, lb_calc_local_fields(), mpi_call(), MPI_DOUBLE, MPI_Recv(), mpi_recv_fluid_slave(), MPI_STATUS_IGNORE, SOME_TAG, and this_node.
Referenced by lb_lbnode_get_pi_neq(), lb_lbnode_get_rho(), lb_lbnode_get_u(), lb_lbnode_set_rho(), and lb_lbnode_set_u().
void mpi_recv_fluid_boundary_flag (int node, int index, int * boundary)
Issue REQ_LB_GET_BOUNDARY_FLAG: Receive a single lattice sites boundary flag from a processor.
Parameters
node processor to send to
index index of the lattice site
boundary local boundary flag
Definition at line 2651 of file communication.cpp.
References comm_cart, lb_local_fields_get_boundary_flag(), mpi_call(), MPI_INT, MPI_Recv(), mpi_recv_fluid_boundary_flag_slave(), MPI_STATUS_IGNORE, SOME_TAG, and this_node.
Referenced by lb_lbnode_get_boundary().
void mpi_recv_fluid_boundary_flag_slave (int node, int index)
Definition at line 2664 of file communication.cpp.
References comm_cart, lb_local_fields_get_boundary_flag(), MPI_INT, MPI_Send(), SOME_TAG, and this_node.
Referenced by mpi_recv_fluid_boundary_flag().
void mpi_recv_fluid_populations (int node, int index, double * pop)
Issue REQ_RECV_FLUID_POPULATIONS: Send a single lattice site to a processor.
Parameters
node processor to send to
index index of the lattice site
pop local fluid population
Definition at line 2738 of file communication.cpp.
References comm_cart, lb_get_populations(), lbpar, mpi_call(), MPI_DOUBLE, MPI_Recv(), mpi_recv_fluid_populations_slave(), MPI_STATUS_IGNORE, LB_Parameters::resend_halo, SOME_TAG, and this_node.
Referenced by lb_lbnode_get_pop().
void mpi_recv_fluid_populations_slave (int node, int index)
Definition at line 2750 of file communication.cpp.
References comm_cart, lb_get_populations(), lbpar, MPI_DOUBLE, MPI_Send(), LB_Parameters::resend_halo, SOME_TAG, and this_node.
Referenced by mpi_recv_fluid_populations().
void mpi_recv_fluid_slave (int node, int index)
Definition at line 2640 of file communication.cpp.
References comm_cart, lb_calc_local_fields(), MPI_DOUBLE, MPI_Send(), SOME_TAG, and this_node.
Referenced by mpi_recv_fluid().
void mpi_recv_part (int node, int part, Particle * part_data)
Issue REQ_GET_PART: recv particle data.
The data has to be freed later using free_particle, otherwise the dynamically allocated parts, bonds and exclusions are left over.
Parameters
part the particle.
node the node it is attached to.
part_data where to store the received data.
Note
Gets a copy of the particle data not a pointer to the actual particle used in integration
Definition at line 1154 of file communication.cpp.
References alloc_intlist(), Particle::bl, comm_cart, IntList::e, Particle::el, local_particles, IntList::max, MPI_BYTE, mpi_call(), MPI_INT, MPI_Recv(), mpi_recv_part_slave(), MPI_STATUS_IGNORE, IntList::n, SOME_TAG, and this_node.
Referenced by get_particle_data().
void mpi_recv_part_slave (int pnode, int part)
Definition at line 1200 of file communication.cpp.
References Particle::bl, comm_cart, IntList::e, Particle::el, local_particles, MPI_BYTE, MPI_INT, MPI_Send(), IntList::n, SOME_TAG, and this_node.
Referenced by mpi_recv_part().
void mpi_remove_particle (int node, int id)
Issue REQ_REM_PART: remove a particle.
Also calls on_particle_change.
Parameters
id the particle to remove.
node the node it is attached to.
Definition at line 1221 of file communication.cpp.
References mpi_call(), and mpi_remove_particle_slave().
Referenced by remove_all_particles(), and remove_particle().
void mpi_remove_particle_slave (int pnode, int part)
Definition at line 1227 of file communication.cpp.
References local_remove_all_particles(), local_remove_particle(), n_part, on_particle_change(), remove_all_bonds_to(), and this_node.
Referenced by mpi_remove_particle().
void mpi_rescale_particles (int dir, double scale)
Issue REQ_RESCALE_PART: rescales all particle positions in direction 'dir' by a factor 'scale'.
Definition at line 2385 of file communication.cpp.
References comm_cart, local_rescale_particles(), mpi_call(), MPI_DOUBLE, mpi_rescale_particles_slave(), MPI_Send(), n_nodes, on_particle_change(), SOME_TAG, and this_node.
Referenced by rescale_boxl().
void mpi_rescale_particles_slave (int pnode, int dir)
Definition at line 2398 of file communication.cpp.
References comm_cart, local_rescale_particles(), MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), and SOME_TAG.
Referenced by mpi_rescale_particles().
int mpi_send_bond (int pnode, int part, int * bond, int _delete)
Issue REQ_SET_BOND: send bond.
Also calls on_particle_change.
Parameters
pnode node it is attached to.
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secundary atoms of the bond).
_delete if true, do not add the bond, rather delete it if found
Returns
1 on success or 0 if not (e. g. bond to delete does not exist)
Definition at line 1108 of file communication.cpp.
References bonded_ia_params, comm_cart, local_change_bond(), mpi_call(), MPI_INT, MPI_Recv(), MPI_Send(), mpi_send_bond_slave(), MPI_STATUS_IGNORE, on_particle_change(), SOME_TAG, and this_node.
Referenced by change_particle_bond().
void mpi_send_bond_slave (int pnode, int part)
Definition at line 1131 of file communication.cpp.
References comm_cart, free, local_change_bond(), malloc, MPI_INT, MPI_Recv(), MPI_Send(), MPI_STATUS_IGNORE, on_particle_change(), SOME_TAG, and this_node.
Referenced by mpi_send_bond().
void mpi_send_configtemp_flag (int pnode, int part, int configtemp)
Definition at line 1840 of file communication.cpp.
References comm_cart, configtemp, local_particles, mpi_call(), MPI_INT, MPI_Send(), mpi_send_configtemp_flag_slave(), on_particle_change(), Particle::p, SOME_TAG, and this_node.
void mpi_send_configtemp_flag_slave (int pnode, int part)
Definition at line 1857 of file communication.cpp.
References comm_cart, local_particles, MPI_INT, MPI_Recv(), on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by mpi_send_configtemp_flag().
void mpi_send_dip (int node, int part, double dip[3])
Issue REQ_SET_DIP: send particle dipole orientation.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
dip its new dipole orientation.
Definition at line 906 of file communication.cpp.
References comm_cart, convert_dip_to_quat(), convert_quat_to_quatu(), ParticlePosition::dip, ParticleProperties::dipm, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_dip_slave(), on_particle_change(), Particle::p, ParticlePosition::quat, ParticlePosition::quatu, Particle::r, SOME_TAG, and this_node.
Referenced by set_particle_dip().
void mpi_send_dip_slave (int pnode, int part)
Definition at line 931 of file communication.cpp.
References comm_cart, convert_dip_to_quat(), convert_quat_to_quatu(), ParticlePosition::dip, ParticleProperties::dipm, local_particles, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, ParticlePosition::quat, ParticlePosition::quatu, Particle::r, SOME_TAG, and this_node.
Referenced by mpi_send_dip().
void mpi_send_dipm (int node, int part, double dipm)
Issue REQ_SET_DIPM: send particle dipole moment.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
dipm its new dipole moment (absolut value).
Definition at line 952 of file communication.cpp.
References comm_cart, convert_quatu_to_dip(), ParticlePosition::dip, ParticleProperties::dipm, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_dipm_slave(), on_particle_change(), Particle::p, ParticlePosition::quatu, Particle::r, SOME_TAG, and this_node.
Referenced by set_particle_dipm().
void mpi_send_dipm_slave (int pnode, int part)
Definition at line 972 of file communication.cpp.
References comm_cart, convert_quatu_to_dip(), ParticlePosition::dip, ParticleProperties::dipm, local_particles, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, ParticlePosition::quatu, Particle::r, SOME_TAG, and this_node.
Referenced by mpi_send_dipm().
void mpi_send_exclusion (int part, int part2, int _delete)
Issue REQ_SET_EXCLUSION: send exclusions.
Also calls on_particle_change.
Parameters
part identity of first particle of the exclusion.
part2 identity of secnd particle of the exclusion.
_delete if true, do not add the exclusion, rather delete it if found
Definition at line 2571 of file communication.cpp.
References comm_cart, local_change_exclusion(), MPI_Bcast(), mpi_call(), MPI_INT, mpi_send_exclusion_slave(), and on_particle_change().
Referenced by change_exclusion(), and remove_all_exclusions().
void mpi_send_exclusion_slave (int part1, int part2)
Definition at line 2582 of file communication.cpp.
References comm_cart, local_change_exclusion(), MPI_Bcast(), MPI_INT, and on_particle_change().
Referenced by mpi_send_exclusion().
void mpi_send_ext_force (int pnode, int part, int flag, int mask, double force[3])
Issue REQ_SEND_EXT_FORCE: send nex external flag and external force.
Definition at line 2027 of file communication.cpp.
References comm_cart, ParticleProperties::ext_flag, ParticleProperties::ext_force, local_particles, mpi_call(), MPI_DOUBLE, MPI_INT, MPI_Send(), mpi_send_ext_force_slave(), on_particle_change(), Particle::p, PARTICLE_EXT_FORCE, SOME_TAG, and this_node.
Referenced by set_particle_ext_force(), and set_particle_fix().
void mpi_send_ext_force_slave (int pnode, int part)
Definition at line 2053 of file communication.cpp.
References comm_cart, ParticleProperties::ext_flag, ParticleProperties::ext_force, local_particles, MPI_DOUBLE, MPI_INT, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, PARTICLE_EXT_FORCE, SOME_TAG, and this_node.
Referenced by mpi_send_ext_force().
void mpi_send_ext_torque (int pnode, int part, int flag, int mask, double torque[3])
Issue REQ_SEND_EXT_TORQUE: send nex external flag and external torque.
Definition at line 1976 of file communication.cpp.
References comm_cart, ParticleProperties::ext_flag, ParticleProperties::ext_torque, local_particles, mpi_call(), MPI_DOUBLE, MPI_INT, MPI_Send(), mpi_send_ext_torque_slave(), on_particle_change(), Particle::p, PARTICLE_EXT_TORQUE, SOME_TAG, and this_node.
Referenced by set_particle_ext_torque().
void mpi_send_ext_torque_slave (int pnode, int part)
Definition at line 2005 of file communication.cpp.
References comm_cart, ParticleProperties::ext_flag, ParticleProperties::ext_torque, local_particles, MPI_DOUBLE, MPI_INT, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, PARTICLE_EXT_TORQUE, SOME_TAG, and this_node.
Referenced by mpi_send_ext_torque().
void mpi_send_f (int node, int part, double F[3])
Issue REQ_SET_F: send particle force.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
F its new force.
Definition at line 546 of file communication.cpp.
References comm_cart, ParticleForce::f, Particle::f, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_f_slave(), on_particle_change(), PMASS, SOME_TAG, and this_node.
Referenced by set_particle_f().
void mpi_send_f_slave (int pnode, int part)
Definition at line 563 of file communication.cpp.
References comm_cart, ParticleForce::f, Particle::f, local_particles, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), PMASS, SOME_TAG, and this_node.
Referenced by mpi_send_f().
void mpi_send_fluid (int node, int index, double rho, double * j, double * pi)
Issue REQ_SEND_FLUID: Send a single lattice site to a processor.
Parameters
node processor to send to
index index of the lattice site
rho local fluid density
j local fluid velocity
pi local fluid pressure
Definition at line 2593 of file communication.cpp.
References comm_cart, lb_calc_n_from_rho_j_pi(), mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_fluid_slave(), SOME_TAG, and this_node.
Referenced by lb_lbnode_set_rho(), and lb_lbnode_set_u().
void mpi_send_fluid_populations (int node, int index, double * pop)
Issue REQ_SEND_FLUID_POPULATIONS: Send a single lattice site to a processor.
Parameters
node processor to send to
index index of the lattice site
pop local fluid population
Definition at line 2761 of file communication.cpp.
References comm_cart, lb_set_populations(), mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_fluid_populations_slave(), SOME_TAG, and this_node.
Referenced by lb_lbnode_set_pop().
void mpi_send_fluid_populations_slave (int node, int index)
Definition at line 2772 of file communication.cpp.
References comm_cart, lb_set_populations(), MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, SOME_TAG, and this_node.
Referenced by mpi_send_fluid_populations().
void mpi_send_fluid_slave (int node, int index)
Definition at line 2605 of file communication.cpp.
References comm_cart, lb_calc_n_from_rho_j_pi(), MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, SOME_TAG, and this_node.
Referenced by mpi_send_fluid().
void mpi_send_mass (int node, int part, double mass)
Issue REQ_SET_M: send particle mass.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
mass its new mass.
Definition at line 676 of file communication.cpp.
References comm_cart, local_particles, ParticleProperties::mass, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_mass_slave(), on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by set_particle_mass().
void mpi_send_mass_slave (int pnode, int part)
Definition at line 693 of file communication.cpp.
References comm_cart, local_particles, ParticleProperties::mass, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by mpi_send_mass().
void mpi_send_mol_id (int node, int part, int mid)
Issue REQ_SET_MOL_ID: send molecule id.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
mid its new mol_id.
Definition at line 767 of file communication.cpp.
References comm_cart, local_particles, ParticleProperties::mol_id, mpi_call(), MPI_INT, MPI_Send(), mpi_send_mol_id_slave(), on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by set_particle_mol_id().
void mpi_send_mol_id_slave (int pnode, int part)
Definition at line 781 of file communication.cpp.
References comm_cart, local_particles, ParticleProperties::mol_id, MPI_INT, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by mpi_send_mol_id().
void mpi_send_mu_E (int node, int part, double mu_E[3])
Issue REQ_SET_MU_E: send particle electrophoretic mobility.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
mu_E its new mobility.
Definition at line 609 of file communication.cpp.
References comm_cart, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_mu_E_slave(), ParticleProperties::mu_E, on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by set_particle_mu_E().
void mpi_send_mu_E_slave (int pnode, int part)
Definition at line 628 of file communication.cpp.
References comm_cart, local_particles, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, ParticleProperties::mu_E, on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by mpi_send_mu_E().
void mpi_send_omega (int pnode, int part, double omega[3])
Definition at line 837 of file communication.cpp.
References comm_cart, local_particles, Particle::m, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_omega_slave(), ParticleMomentum::omega, on_particle_change(), SOME_TAG, and this_node.
Referenced by set_particle_omega_body(), and set_particle_omega_lab().
void mpi_send_omega_slave (int pnode, int part)
Definition at line 857 of file communication.cpp.
References comm_cart, local_particles, Particle::m, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, ParticleMomentum::omega, on_particle_change(), SOME_TAG, and this_node.
Referenced by mpi_send_omega().
void mpi_send_q (int node, int part, double q)
Issue REQ_SET_Q: send particle charge.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
q its new charge.
Definition at line 578 of file communication.cpp.
References comm_cart, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_q_slave(), on_particle_change(), Particle::p, ParticleProperties::q, SOME_TAG, and this_node.
Referenced by set_particle_q().
void mpi_send_q_slave (int pnode, int part)
Definition at line 595 of file communication.cpp.
References comm_cart, local_particles, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, ParticleProperties::q, SOME_TAG, and this_node.
Referenced by mpi_send_q().
void mpi_send_quat (int node, int part, double quat[4])
Issue REQ_SET_QUAT: send particle orientation.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
quat its new quaternions.
Definition at line 794 of file communication.cpp.
References comm_cart, convert_quat_to_quatu(), convert_quatu_to_dip(), ParticlePosition::dip, ParticleProperties::dipm, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_quat_slave(), on_particle_change(), Particle::p, ParticlePosition::quat, ParticlePosition::quatu, Particle::r, SOME_TAG, and this_node.
Referenced by set_particle_quat().
void mpi_send_quat_slave (int pnode, int part)
Definition at line 818 of file communication.cpp.
References comm_cart, convert_quat_to_quatu(), convert_quatu_to_dip(), ParticlePosition::dip, ParticleProperties::dipm, local_particles, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, ParticlePosition::quat, ParticlePosition::quatu, Particle::r, SOME_TAG, and this_node.
Referenced by mpi_send_quat().
void mpi_send_rotation (int pnode, int part, int rot)
Issue REQ_SET_ROTATION: send particle rotation flag Also calls on_particle_change.
Parameters
part the particle.
pnode the node it is attached to.
rot the rotation flag
Definition at line 1060 of file communication.cpp.
References local_particles, mpi_call(), MPI_COMM_WORLD, MPI_INT, MPI_Send(), mpi_send_rotation_slave(), on_particle_change(), Particle::p, ParticleProperties::rotation, SOME_TAG, and this_node.
Referenced by set_particle_rotation().
void mpi_send_rotation_slave (int pnode, int part)
Definition at line 1077 of file communication.cpp.
References local_particles, MPI_COMM_WORLD, MPI_INT, MPI_Recv(), on_particle_change(), Particle::p, ParticleProperties::rotation, SOME_TAG, and this_node.
Referenced by mpi_send_rotation().
void mpi_send_rotational_inertia (int node, int part, double rinertia[3])
Issue REQ_SET_ROTATIONAL_INERTIA: send particle rotational inertia.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
rinertia its new rotational inertia.
Definition at line 708 of file communication.cpp.
References comm_cart, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_rotational_inertia_slave(), on_particle_change(), Particle::p, ParticleProperties::rinertia, SOME_TAG, and this_node.
Referenced by set_particle_rotational_inertia().
void mpi_send_rotational_inertia_slave (int pnode, int part)
Definition at line 727 of file communication.cpp.
References comm_cart, local_particles, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, ParticleProperties::rinertia, SOME_TAG, and this_node.
Referenced by mpi_send_rotational_inertia().
void mpi_send_smaller_timestep_flag (int node, int part, int smaller_timestep_flag)
Issue REQ_SET_SMALLER_TIMESTEP: send smaller time step value.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
smaller_timestep its new smaller_timestep.
Definition at line 1809 of file communication.cpp.
References comm_cart, local_particles, mpi_call(), MPI_INT, MPI_Send(), mpi_send_smaller_timestep_flag_slave(), on_particle_change(), Particle::p, ParticleProperties::smaller_timestep, SOME_TAG, and this_node.
Referenced by set_particle_smaller_timestep().
void mpi_send_smaller_timestep_flag_slave (int pnode, int part)
Definition at line 1826 of file communication.cpp.
References comm_cart, local_particles, MPI_INT, MPI_Recv(), on_particle_change(), Particle::p, ParticleProperties::smaller_timestep, SOME_TAG, and this_node.
Referenced by mpi_send_smaller_timestep_flag().
void mpi_send_solvation (int node, int part, double * solvation)
issue req_set_solv: send particle solvation free energy also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
solvation its new solvation free energy.
Definition at line 642 of file communication.cpp.
References comm_cart, LB_COMPONENTS, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_solvation_slave(), on_particle_change(), Particle::p, ParticleProperties::solvation, SOME_TAG, and this_node.
Referenced by set_particle_solvation().
void mpi_send_solvation_slave (int pnode, int part)
Definition at line 661 of file communication.cpp.
References comm_cart, LB_COMPONENTS, local_particles, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, ParticleProperties::solvation, SOME_TAG, and this_node.
Referenced by mpi_send_solvation().
void mpi_send_swimming (int node, int part, ParticleParametersSwimming swim)
Issue REQ_SET_SWIMMING: send particle swimming properties.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
swim struct containing swimming parameters
Definition at line 515 of file communication.cpp.
References comm_cart, local_particles, MPI_BYTE, mpi_call(), MPI_Send(), mpi_send_swimming_slave(), on_particle_change(), SOME_TAG, Particle::swim, and this_node.
Referenced by set_particle_swimming().
void mpi_send_swimming_slave (int pnode, int part)
Definition at line 532 of file communication.cpp.
References comm_cart, local_particles, MPI_BYTE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), SOME_TAG, Particle::swim, and this_node.
Referenced by mpi_send_swimming().
void mpi_send_torque (int node, int part, double torque[3])
Issue REQ_SET_TORQUE: send particle torque.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
torque its new torque.
Definition at line 872 of file communication.cpp.
References comm_cart, Particle::f, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_torque_slave(), on_particle_change(), SOME_TAG, this_node, and ParticleForce::torque.
Referenced by set_particle_torque_body(), and set_particle_torque_lab().
void mpi_send_torque_slave (int pnode, int part)
Definition at line 891 of file communication.cpp.
References comm_cart, Particle::f, local_particles, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), SOME_TAG, this_node, and ParticleForce::torque.
Referenced by mpi_send_torque().
void mpi_send_type (int node, int part, int type)
Issue REQ_SET_TYPE: send particle type.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
type its new type.
Definition at line 741 of file communication.cpp.
References comm_cart, local_particles, mpi_call(), MPI_INT, MPI_Send(), mpi_send_type_slave(), on_particle_change(), Particle::p, SOME_TAG, this_node, and ParticleProperties::type.
Referenced by set_particle_type().
void mpi_send_type_slave (int pnode, int part)
Definition at line 755 of file communication.cpp.
References comm_cart, local_particles, MPI_INT, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, SOME_TAG, this_node, and ParticleProperties::type.
Referenced by mpi_send_type().
void mpi_send_v (int node, int part, double v[3])
Issue REQ_SET_V: send particle velocity.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
v its new velocity.
Definition at line 489 of file communication.cpp.
References comm_cart, local_particles, Particle::m, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_send_v_slave(), on_particle_change(), SOME_TAG, this_node, and ParticleMomentum::v.
Referenced by set_particle_v().
void mpi_send_v_slave (int pnode, int part)
Definition at line 503 of file communication.cpp.
References comm_cart, local_particles, Particle::m, MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), SOME_TAG, this_node, and ParticleMomentum::v.
Referenced by mpi_send_v().
void mpi_send_virtual (int node, int part, int isVirtual)
Issue REQ_SET_DIPM: send particle dipole moment.
Also calls on_particle_change.
Parameters
part the particle.
node the node it is attached to.
isVirtual its new isVirtual.
Definition at line 990 of file communication.cpp.
References comm_cart, ParticleProperties::isVirtual, local_particles, mpi_call(), MPI_INT, MPI_Send(), mpi_send_virtual_slave(), on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by set_particle_virtual().
void mpi_send_virtual_slave (int pnode, int part)
Definition at line 1007 of file communication.cpp.
References comm_cart, ParticleProperties::isVirtual, local_particles, MPI_INT, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by mpi_send_virtual().
void mpi_send_vs_relative (int pnode, int part, int vs_relative_to, double vs_distance)
Definition at line 1022 of file communication.cpp.
References comm_cart, local_particles, mpi_call(), MPI_DOUBLE, MPI_INT, MPI_Send(), mpi_send_vs_relative_slave(), on_particle_change(), Particle::p, SOME_TAG, this_node, ParticleProperties::vs_relative_distance, and ParticleProperties::vs_relative_to_particle_id.
Referenced by set_particle_vs_relative().
void mpi_send_vs_relative_slave (int pnode, int part)
Definition at line 1043 of file communication.cpp.
References comm_cart, local_particles, MPI_DOUBLE, MPI_INT, MPI_Recv(), MPI_STATUS_IGNORE, on_particle_change(), Particle::p, SOME_TAG, this_node, ParticleProperties::vs_relative_distance, and ParticleProperties::vs_relative_to_particle_id.
Referenced by mpi_send_vs_relative().
void mpi_set_particle_gamma (int pnode, int part, double gamma)
Issue REQ_SEND_PARTICLE_T: send particle type specific frictional coefficient.
Definition at line 2838 of file communication.cpp.
References comm_cart, ParticleProperties::gamma, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_set_particle_gamma_slave(), on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by set_particle_gamma().
void mpi_set_particle_gamma_slave (int pnode, int part)
Definition at line 2855 of file communication.cpp.
References comm_cart, ParticleProperties::gamma, local_particles, MPI_DOUBLE, MPI_Recv(), on_particle_change(), Particle::p, SOME_TAG, and this_node.
Referenced by mpi_set_particle_gamma().
void mpi_set_particle_temperature (int pnode, int part, double _T)
Issue REQ_SEND_PARTICLE_T: send particle type specific temperature.
Definition at line 2804 of file communication.cpp.
References comm_cart, local_particles, mpi_call(), MPI_DOUBLE, MPI_Send(), mpi_set_particle_temperature_slave(), on_particle_change(), Particle::p, SOME_TAG, ParticleProperties::T, and this_node.
Referenced by set_particle_temperature().
void mpi_set_particle_temperature_slave (int pnode, int part)
Definition at line 2821 of file communication.cpp.
References comm_cart, local_particles, MPI_DOUBLE, MPI_Recv(), on_particle_change(), Particle::p, SOME_TAG, ParticleProperties::T, and this_node.
Referenced by mpi_set_particle_temperature().
void mpi_set_smaller_time_step (double smaller_time_step)
Issue REQ_SET_SMALLER_TIME_STEP: send new smaller_time_step.
Requires MULTI_TIMESTEP feature.
Definition at line 1790 of file communication.cpp.
References comm_cart, FIELD_SMALLERTIMESTEP, MPI_Bcast(), mpi_call(), MPI_DOUBLE, mpi_set_smaller_time_step_slave(), on_parameter_change(), and smaller_time_step.
Referenced by tclcallback_smaller_time_step().
void mpi_set_smaller_time_step_slave (int node, int i)
Definition at line 1801 of file communication.cpp.
References comm_cart, FIELD_SMALLERTIMESTEP, MPI_Bcast(), MPI_DOUBLE, on_parameter_change(), and smaller_time_step.
Referenced by mpi_set_smaller_time_step().
void mpi_set_time_step (double time_s)
Issue REQ_SET_TIME_STEP: send new time_step and rescale the velocities accordingly.
Definition at line 1759 of file communication.cpp.
References comm_cart, FIELD_TIMESTEP, MPI_Bcast(), mpi_call(), MPI_DOUBLE, mpi_set_time_step_slave(), on_parameter_change(), rescale_velocities(), time_step, time_step_half, time_step_squared, and time_step_squared_half.
Referenced by tclcallback_time_step().
void mpi_set_time_step_slave (int node, int i)
Definition at line 1777 of file communication.cpp.
References comm_cart, FIELD_TIMESTEP, MPI_Bcast(), MPI_DOUBLE, on_parameter_change(), rescale_velocities(), time_step, time_step_half, time_step_squared, and time_step_squared_half.
Referenced by mpi_set_time_step().
void mpi_setup_reaction ()
Issue REQ_CATALYTIC_REACTIONS: notify the system of changes to the reaction parameters.
Definition at line 3007 of file communication.cpp.
References local_setup_reaction(), mpi_call(), and mpi_setup_reaction_slave().
Referenced by tclcommand_reaction().
void mpi_setup_reaction_slave (int pnode, int i)
Definition at line 3015 of file communication.cpp.
References local_setup_reaction().
Referenced by mpi_setup_reaction().
void mpi_stop ()
Stop Espresso, all slave nodes exit.
Definition at line 269 of file communication.cpp.
References comm_cart, MPI_Barrier(), mpi_call(), MPI_Finalize(), mpi_stop_slave(), regular_exit, and terminated.
Referenced by on_program_start().
void mpi_stop_slave (int node, int param)
Definition at line 282 of file communication.cpp.
References comm_cart, COMM_TRACE, MPI_Barrier(), MPI_Finalize(), regular_exit, and this_node.
Referenced by mpi_stop().
int mpi_sync_topo_part_info (void)
Issue REQ_SYNC_TOPO: Update the molecules ids to that they correspond to the topology.
Definition at line 2450 of file communication.cpp.
References comm_cart, i, IsTrapped, MPI_Bcast(), mpi_call(), MPI_DOUBLE, MPI_INT, mpi_sync_topo_part_info_slave(), IntList::n, n_molecules, Molecule::part, sync_topo_part_info(), topology, and Molecule::type.
Referenced by tclcommand_analyze_set_parse_topo_part_sync().
void mpi_sync_topo_part_info_slave (int node, int parm)
Definition at line 2492 of file communication.cpp.
References comm_cart, i, IsTrapped, MPI_Bcast(), MPI_DOUBLE, MPI_INT, IntList::n, n_molecules, Molecule::part, realloc_intlist(), realloc_topology(), sync_topo_part_info(), topology, and Molecule::type.
Referenced by mpi_sync_topo_part_info().
void mpi_system_CMS ()
Definition at line 2899 of file communication.cpp.
References galilei_struct::cms, comm_cart, gal, local_system_CMS(), MPI_ANY_SOURCE, mpi_call(), MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, mpi_system_CMS_slave(), n_nodes, SOME_TAG, and this_node.
Referenced by tclcommand_system_CMS().
void mpi_system_CMS_slave (int node, int index)
Definition at line 2933 of file communication.cpp.
References comm_cart, local_system_CMS(), MPI_DOUBLE, MPI_Send(), and SOME_TAG.
Referenced by mpi_system_CMS().
void mpi_system_CMS_velocity ()
Definition at line 2940 of file communication.cpp.
References galilei_struct::cms_vel, comm_cart, gal, local_system_CMS_velocity(), MPI_ANY_SOURCE, mpi_call(), MPI_DOUBLE, MPI_Recv(), MPI_STATUS_IGNORE, mpi_system_CMS_velocity_slave(), n_nodes, SOME_TAG, and this_node.
Referenced by mpi_galilei_transform(), and tclcommand_system_CMS_velocity().
void mpi_system_CMS_velocity_slave (int node, int index)
Definition at line 2974 of file communication.cpp.
References comm_cart, local_system_CMS_velocity(), MPI_DOUBLE, MPI_Send(), and SOME_TAG.
Referenced by mpi_system_CMS_velocity().
void mpi_thermalize_cpu (int temp)
CPU Thermostat.
Definition at line 3023 of file communication.cpp.
References mpi_call(), mpi_thermalize_cpu_slave(), and set_cpu_temp().
Referenced by integrate_vv().
void mpi_thermalize_cpu_slave (int node, int temp)
Definition at line 3029 of file communication.cpp.
References set_cpu_temp().
Referenced by mpi_thermalize_cpu().
void mpi_update_mol_ids (void)
Issue REQ_BCAST_LJANGLEFORCECAP: initialize LJANGLE force capping.
Issue REQ_UPDATE_MOL_IDS: Update the molecule ids so that they are in sync with the topology. Note that this only makes sense if you have a simple topology such that each particle can only belong to a single molecule
Definition at line 2438 of file communication.cpp.
References mpi_call(), and mpi_update_mol_ids_slave().
void mpi_update_mol_ids_slave (int node, int parm)
Definition at line 2444 of file communication.cpp.
References update_mol_ids_setchains().
Referenced by mpi_update_mol_ids().
void mpi_who_has ()
Issue REQ_WHO_HAS: ask nodes for their attached particles.
Definition at line 331 of file communication.cpp.
References CellPList::cell, cells_get_n_particles(), comm_cart, COMM_TRACE, free, i, ParticleProperties::identity, local_cells, malloc, max_seen_particle, mpi_call(), MPI_Gather(), MPI_INT, MPI_Recv(), MPI_STATUS_IGNORE, mpi_who_has_slave(), CellPList::n, ParticleList::n, n_nodes, n_part, Particle::p, ParticleList::part, particle_node, realloc, SOME_TAG, and this_node.
Referenced by build_particle_node().
void mpi_who_has_slave (int node, int param)
Definition at line 374 of file communication.cpp.
References CellPList::cell, cells_get_n_particles(), comm_cart, free, i, ParticleProperties::identity, local_cells, malloc, MPI_Gather(), MPI_INT, MPI_Send(), CellPList::n, ParticleList::n, n_part, Particle::p, ParticleList::part, and SOME_TAG.
Referenced by mpi_who_has().
Variable Documentation
MPI_Comm comm_cart
Definition at line 77 of file communication.cpp.
Referenced by add_z_force(), announce_resort_particles(), bcast_iccp3m_cfg(), calc_kinetic(), calc_mu_max(), calc_node_neighbors(), CalcVolumes(), check_particles(), common_bcast_parameter(), correct_pos_shake(), correct_vel_shake(), dd_exchange_and_sort_particles(), dd_topology_init(), distribute(), energy_calc(), finalize_p_inst_npt(), gather_image_contributions(), get_DLC_dipolar(), get_DLC_energy_dipolar(), ghost_communicator(), grid_changed_n_nodes(), halo_communication(), halo_push_communication(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_get_particles_slave(), IBM_cuda_mpi_send_velocities(), IBM_cuda_mpi_send_velocities_slave(), iccp3m_iteration(), integrate_sd(), integrate_vv(), layered_exchange_and_sort_particles(), layered_prepare_comm(), layered_topology_init(), lb_calc_average_rho(), lb_calc_densprof(), lb_calc_fluid_mass(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_calc_velprof(), lb_check_halo_regions(), lb_collect_boundary_forces(), local_setup_reaction(), maggs_calc_init_e_field(), maggs_check_curl_E(), maggs_compute_dipole_correction(), maggs_count_charged_particles(), maggs_electric_energy(), maggs_exchange_surface_patch(), map_array_node(), map_node_array(), minimize_energy(), mpi_abort(), mpi_bcast_collision_params_slave(), mpi_bcast_constraint(), mpi_bcast_constraint_slave(), mpi_bcast_coulomb_params_slave(), mpi_bcast_cuda_global_part_vars_slave(), mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), mpi_bcast_lb_params_slave(), mpi_bcast_lbboundary(), mpi_bcast_lbboundary_slave(), mpi_bcast_nptiso_geom_slave(), mpi_bit_random_seed(), mpi_bit_random_seed_slave(), mpi_bit_random_stat(), mpi_bit_random_stat_slave(), mpi_cap_forces_slave(), mpi_comm_mol_info(), mpi_comm_mol_info_slave(), mpi_external_potential_broadcast(), mpi_external_potential_broadcast_slave(), mpi_external_potential_sum_energies(), mpi_external_potential_sum_energies_slave(), mpi_galilei_transform(), mpi_galilei_transform_slave(), mpi_get_configtemp(), mpi_get_configtemp_slave(), mpi_get_constraint_force(), mpi_get_constraint_force_slave(), mpi_get_particles(), mpi_get_particles_slave(), mpi_init(), mpi_local_stress_tensor(), mpi_local_stress_tensor_slave(), mpi_loop(), mpi_observable_lb_radial_velocity_profile_slave_implementation(), mpi_place_new_particle(), mpi_place_new_particle_slave(), mpi_place_particle(), mpi_place_particle_slave(), mpi_random_seed(), mpi_random_seed_slave(), mpi_random_stat(), mpi_random_stat_slave(), mpi_recv_fluid(), mpi_recv_fluid_boundary_flag(), mpi_recv_fluid_boundary_flag_slave(), mpi_recv_fluid_populations(), mpi_recv_fluid_populations_slave(), mpi_recv_fluid_slave(), mpi_recv_part(), mpi_recv_part_slave(), mpi_rescale_particles(), mpi_rescale_particles_slave(), mpi_send_bond(), mpi_send_bond_slave(), mpi_send_configtemp_flag(), mpi_send_configtemp_flag_slave(), mpi_send_dip(), mpi_send_dip_slave(), mpi_send_dipm(), mpi_send_dipm_slave(), mpi_send_exclusion(), mpi_send_exclusion_slave(), mpi_send_ext_force(), mpi_send_ext_force_slave(), mpi_send_ext_torque(), mpi_send_ext_torque_slave(), mpi_send_f(), mpi_send_f_slave(), mpi_send_fluid(), mpi_send_fluid_populations(), mpi_send_fluid_populations_slave(), mpi_send_fluid_slave(), mpi_send_mass(), mpi_send_mass_slave(), mpi_send_mol_id(), mpi_send_mol_id_slave(), mpi_send_mu_E(), mpi_send_mu_E_slave(), mpi_send_omega(), mpi_send_omega_slave(), mpi_send_q(), mpi_send_q_slave(), mpi_send_quat(), mpi_send_quat_slave(), mpi_send_rotational_inertia(), mpi_send_rotational_inertia_slave(), mpi_send_smaller_timestep_flag(), mpi_send_smaller_timestep_flag_slave(), mpi_send_solvation(), mpi_send_solvation_slave(), mpi_send_swimming(), mpi_send_swimming_slave(), mpi_send_torque(), mpi_send_torque_slave(), mpi_send_type(), mpi_send_type_slave(), mpi_send_v(), mpi_send_v_slave(), mpi_send_virtual(), mpi_send_virtual_slave(), mpi_send_vs_relative(), mpi_send_vs_relative_slave(), mpi_set_particle_gamma(), mpi_set_particle_gamma_slave(), mpi_set_particle_temperature(), mpi_set_particle_temperature_slave(), mpi_set_smaller_time_step(), mpi_set_smaller_time_step_slave(), mpi_set_time_step(), mpi_set_time_step_slave(), mpi_stop(), mpi_stop_slave(), mpi_sync_topo_part_info(), mpi_sync_topo_part_info_slave(), mpi_system_CMS(), mpi_system_CMS_slave(), mpi_system_CMS_velocity(), mpi_system_CMS_velocity_slave(), mpi_who_has(), mpi_who_has_slave(), nsq_balance_particles(), nsq_prepare_comm(), observable_calc_lb_radial_velocity_profile(), on_coulomb_change(), on_integration_start(), predict_momentum_particles(), pressure_calc(), propagate_press_box_pos_and_rescale_npt(), recv_particles(), send_particles(), slab_dip_count_mu(), steepest_descent_step(), and z_energy().
int graceful_exit = 0
Definition at line 78 of file communication.cpp.
const int N_CALLBACKS = sizeof(slave_callbacks)/sizeof(SlaveCallback*)
Definition at line 178 of file communication.cpp.
int n_nodes = -1
The total number of nodes.
Definition at line 76 of file communication.cpp.
Referenced by build_verlet_lists(), build_verlet_lists_and_calc_verlet_ia(), build_verlet_lists_and_calc_verlet_ia_iccp3m(), clear_image_contributions(), collision_detection_set_params(), comfixed_set_params(), comforce_set_params(), dawaanr_calculations(), dawaanr_set_params(), dd_exchange_and_sort_particles(), distribute(), gather_image_contributions(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_send_velocities(), layered_exchange_and_sort_particles(), layered_prepare_comm(), layered_topology_init(), lb_calc_fluid_temp(), lb_check_halo_regions(), lb_viscous_coupling(), maggs_calc_init_e_field(), magnetic_dipolar_direct_sum_calculations(), mdds_set_params(), meta_init(), MMM2D_dielectric_layers_energy_contribution(), MMM2D_dielectric_layers_force_contribution(), MMM2D_init(), MMM2D_set_params(), mpi_comm_mol_info(), mpi_get_particles(), mpi_init(), mpi_rescale_particles(), mpi_system_CMS(), mpi_system_CMS_velocity(), mpi_who_has(), nemd_init(), nsq_balance_particles(), nsq_prepare_comm(), nsq_topology_init(), observable_calc_lb_radial_velocity_profile(), setup_P(), setup_PQ(), setup_Q(), setup_z_energy(), setup_z_force(), tclcallback_node_grid(), tclcommand_analyze_parse_aggregation(), tclcommand_bit_random(), tclcommand_cellsystem(), and tclcommand_t_random().
const char* names[]
Initial value:
= {
  CALLBACK_LIST
}
Definition at line 184 of file communication.cpp.
Referenced by tclcommand_analyze_parse_cylindrical_average().
int request[3] static
The requests are compiled statically here, so that after a crash you can get the last issued request from the debugger.
Definition at line 193 of file communication.cpp.
Referenced by halo_communication(), and maggs_exchange_surface_patch().
SlaveCallback* const slave_callbacks[] static
Initial value:
= {
  CALLBACK_LIST
}
Definition at line 174 of file communication.cpp.
Referenced by mpi_loop().
int terminated = 0 static
Definition at line 80 of file communication.cpp.
Referenced by mpi_abort(), and mpi_stop().
int this_node = -1
The number of this node.
Definition at line 75 of file communication.cpp.
Referenced by __free(), __malloc(), __realloc(), _cuda_check_errors(), add_buck_pair_force(), add_ewald_gpu_coulomb_pair_force(), add_forces_from_recv_buffer(), add_hat_pair_force(), add_interrf_pair_force(), add_lj_pair_force(), add_ljangle_pair_force(), add_ljcos2_pair_force(), add_ljcos_pair_force(), add_ljgen_pair_force(), add_mdlc_energy_corrections(), add_morse_pair_force(), add_non_bonded_pair_force(), add_non_bonded_pair_force_iccp3m(), add_P_force(), add_PQ_force(), add_Q_force(), add_rf_coulomb_pair_force_no_cutoff(), add_soft_pair_force(), add_tunable_slip_pair_force(), add_z_force(), analyze_local_stress_tensor(), announce_resort_particles(), bcast_iccp3m_cfg(), build_verlet_lists(), build_verlet_lists_and_calc_verlet_ia(), build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_bonded_coulomb_pair_force(), calc_buck_cap_radii(), calc_endangledist_pair_force(), calc_fene_pair_force(), calc_fluctuations(), calc_harmonic_dumbbell_pair_force(), calc_harmonic_pair_force(), calc_lj_cap_radii(), calc_ljangle_cap_radii(), calc_ljcos2_cap_radii(), calc_ljgen_cap_radii(), calc_long_range_forces(), calc_mol_info(), calc_morse_cap_radii(), calc_node_neighbors(), calc_overlap_bond_force(), calc_quartic_pair_force(), calc_stretching_force_pair_force(), calc_stretchlin_force_pair_force(), calc_subt_lj_pair_force(), calc_tab_bond_force(), calc_umbrella_pair_force(), calculate_link_cell_energies(), calculate_link_cell_virials(), calculate_verlet_energies(), calculate_verlet_virials(), cell_cell_transfer(), cells_on_geometry_change(), cells_re_init(), cells_resort_particles(), check_cells_consistency(), check_particle_consistency(), check_particles(), clear_image_contributions(), convert_initial_torques(), convert_torques_propagate_omega(), copy_forces_from_GPU(), copy_part_data_to_gpu(), copy_v_cs_from_GPU(), core(), correct_pos_shake(), correct_vel_shake(), cuda_check_error(), dd_append_particles(), dd_create_cell_grid(), dd_exchange_and_sort_particles(), dd_fill_comm_cell_lists(), dd_init_cell_interactions(), dd_on_geometry_change(), dd_prepare_comm(), dd_revert_comm_order(), dd_topology_init(), dd_topology_release(), detect_collision(), distribute(), distribute_tensors(), does_line_go_through_cube(), dump_particle_ordering(), finalize_p_inst_npt(), force_and_velocity_check(), force_and_velocity_display(), force_calc(), free_comm(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), gather_image_contributions(), EspressoSystemInterface::gatherParticles(), get_DLC_energy_dipolar(), get_name_of_bonded_ia(), ghmc_close(), ghmc_init(), ghmc_mc(), ghmc_momentum_update(), ghost_communicator(), gpu_change_number_of_part_to_comm(), gpu_init_particle_comm(), grid_changed_box_l(), grid_changed_n_nodes(), halo_communication(), halo_copy_vector(), halo_dtcopy(), hamiltonian_calc(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_get_particles_slave(), IBM_cuda_mpi_send_velocities(), IBM_cuda_mpi_send_velocities_slave(), IBM_ForcesIntoFluid_GPU(), IBM_ResetLBForces_GPU(), Lattice::init(), init_bit_random(), init_random(), init_random_seed(), InitCUDA_IBM(), integrate_ensemble_init(), integrate_sd(), integrate_vv(), is_recv_op(), is_send_op(), layered_append_particles(), layered_calculate_energies(), layered_calculate_ia(), layered_calculate_ia_iccp3m(), layered_exchange_and_sort_particles(), layered_prepare_comm(), layered_topology_init(), layered_topology_release(), lb_calc_densprof(), lb_calc_velprof(), lb_GPU_sanity_checks(), lb_init_boundaries(), lb_reinit_parameters(), lb_viscous_coupling(), le_dd_dynamic_update_comm(), le_dd_init_cell_interactions(), le_dd_prepare_comm(), le_dd_update_communicators_w_boxl(), local_place_particle(), local_remove_particle(), local_sort_particles(), local_stress_tensor_calc(), maggs_calc_init_e_field(), maggs_exchange_surface_patch(), main(), Lattice::map_position_to_lattice(), map_to_2dgrid(), mdlc_set_params(), mdlc_tune(), MMM2D_dielectric_layers_energy_contribution(), MMM2D_dielectric_layers_force_contribution(), MMM2D_setup_constants(), modes2d(), momentum_flip(), mpi_bcast_coulomb_params_slave(), mpi_bit_random_seed(), mpi_bit_random_seed_slave(), mpi_bit_random_stat(), mpi_bit_random_stat_slave(), mpi_core(), mpi_gather_stats(), mpi_gather_stats_slave(), mpi_get_particles(), mpi_get_particles_slave(), mpi_iccp3m_init(), mpi_iccp3m_init_slave(), mpi_iccp3m_iteration(), mpi_init(), mpi_integrate(), mpi_integrate_slave(), mpi_local_stress_tensor(), mpi_local_stress_tensor_slave(), mpi_loop(), mpi_place_new_particle(), mpi_place_new_particle_slave(), mpi_place_particle(), mpi_place_particle_slave(), mpi_random_seed(), mpi_random_seed_slave(), mpi_random_stat(), mpi_random_stat_slave(), mpi_recv_fluid(), mpi_recv_fluid_boundary_flag(), mpi_recv_fluid_boundary_flag_slave(), mpi_recv_fluid_populations(), mpi_recv_fluid_populations_slave(), mpi_recv_fluid_slave(), mpi_recv_part(), mpi_recv_part_slave(), mpi_remove_particle_slave(), mpi_rescale_particles(), mpi_send_bond(), mpi_send_bond_slave(), mpi_send_configtemp_flag(), mpi_send_configtemp_flag_slave(), mpi_send_dip(), mpi_send_dip_slave(), mpi_send_dipm(), mpi_send_dipm_slave(), mpi_send_ext_force(), mpi_send_ext_force_slave(), mpi_send_ext_torque(), mpi_send_ext_torque_slave(), mpi_send_f(), mpi_send_f_slave(), mpi_send_fluid(), mpi_send_fluid_populations(), mpi_send_fluid_populations_slave(), mpi_send_fluid_slave(), mpi_send_mass(), mpi_send_mass_slave(), mpi_send_mol_id(), mpi_send_mol_id_slave(), mpi_send_mu_E(), mpi_send_mu_E_slave(), mpi_send_omega(), mpi_send_omega_slave(), mpi_send_q(), mpi_send_q_slave(), mpi_send_quat(), mpi_send_quat_slave(), mpi_send_rotation(), mpi_send_rotation_slave(), mpi_send_rotational_inertia(), mpi_send_rotational_inertia_slave(), mpi_send_smaller_timestep_flag(), mpi_send_smaller_timestep_flag_slave(), mpi_send_solvation(), mpi_send_solvation_slave(), mpi_send_swimming(), mpi_send_swimming_slave(), mpi_send_torque(), mpi_send_torque_slave(), mpi_send_type(), mpi_send_type_slave(), mpi_send_v(), mpi_send_v_slave(), mpi_send_virtual(), mpi_send_virtual_slave(), mpi_send_vs_relative(), mpi_send_vs_relative_slave(), mpi_set_particle_gamma(), mpi_set_particle_gamma_slave(), mpi_set_particle_temperature(), mpi_set_particle_temperature_slave(), mpi_stop_slave(), mpi_system_CMS(), mpi_system_CMS_velocity(), mpi_who_has(), nemd_change_momentum(), nemd_free(), nemd_init(), nemd_store_velocity_profile(), nsq_balance_particles(), nsq_topology_init(), nsq_topology_release(), on_boxl_change(), on_cell_structure_change(), on_constraint_change(), on_coulomb_change(), on_ghost_flags_change(), on_integration_start(), on_lb_params_change(), on_lb_params_change_gpu(), on_lbboundary_change(), on_observable_calc(), on_parameter_change(), on_particle_change(), on_program_start(), on_resort_particles(), on_short_range_ia_change(), on_temperature_change(), p3m_gpu_init(), ParticleVelocitiesFromLB_GPU(), prepare_comm(), prepare_halo_communication(), prepare_recv_buffer(), prepare_send_buffer(), print_bond_len(), print_ghost_positions(), print_local_particle_positions(), print_particle_forces(), print_particle_positions(), printAllComms(), propagate_omega_quat_particle(), propagate_pos(), propagate_pos_sd(), propagate_press_box_pos_and_rescale_npt(), propagate_vel(), propagate_vel_pos(), put_recv_buffer(), python_integrate(), realloc_cells(), realloc_particlelist(), recalc_maximal_cutoff_nonbonded(), recv_particles(), reduce_forces_sum(), remove_all_bonds_to(), rescale_forces(), rescale_forces_propagate_vel(), send_particles(), setup_P(), setup_PQ(), setup_Q(), setup_z_energy(), setup_z_force(), tclcommand_analyze_parse_bilayer_set(), tclcommand_analyze_parse_get_folded_positions(), tclcommand_analyze_parse_get_lipid_orients(), tclcommand_analyze_parse_local_stress_tensor(), tclcommand_analyze_parse_modes2d(), tclcommand_ghmc(), tclcommand_integrate(), tclcommand_integrate_sd(), tclcommand_inter_magnetic_parse_mdlc_params(), tclcommand_load_state(), tclcommand_nemd(), tclcommand_nemd_parse_and_print_profile(), tclcommand_nemd_parse_and_print_viscosity(), tclcommand_save_state(), tclcommand_thermostat(), thermo_init_dpd(), thermo_init_ghmc(), thermo_init_langevin(), thermo_init_npt_isotropic(), le_dd_comms_manager::wrap_fill_comm_cell_lists(), and write_local_lattice_to_file().