ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: constraint_tcl.cpp File Reference
constraint_tcl.cpp File Reference
#include <limits>
#include "constraint.hpp"
#include "communication.hpp"
#include "parser.hpp"
#include "TclOutputHelper.hpp"
Functions
static int tclprint_to_result_Constraint (Tcl_Interp *interp, int i)
int tclcommand_constraint_print (Tcl_Interp *interp)
static void tclprint_to_result_ConstraintForce (Tcl_Interp *interp, int con)
static void tclprint_to_result_n_constraints (Tcl_Interp *interp)
static int tclcommand_constraint_parse_wall (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_sphere (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_cylinder (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_rhomboid (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_pore (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_slitpore (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_rod (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_plate (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_stomatocyte (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_hollow_cone (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_maze (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_constraint_parse_ext_magn_field (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_parse_plane_cell (Constraint *con, Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_constraint_mindist_position (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_constraint_mindist_position_vec (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_constraint (ClientData _data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the Tcl function constraint.
Function Documentation
int tclcommand_constraint (ClientData _data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the Tcl function constraint.
This function allows to set and delete constraints.
Definition at line 1850 of file constraint_tcl.cpp.
References gather_runtime_errors(), generate_constraint(), mpi_bcast_constraint(), n_constraints, tclcommand_constraint_mindist_position(), tclcommand_constraint_mindist_position_vec(), tclcommand_constraint_parse_cylinder(), tclcommand_constraint_parse_ext_magn_field(), tclcommand_constraint_parse_hollow_cone(), tclcommand_constraint_parse_maze(), tclcommand_constraint_parse_plane_cell(), tclcommand_constraint_parse_plate(), tclcommand_constraint_parse_pore(), tclcommand_constraint_parse_rhomboid(), tclcommand_constraint_parse_rod(), tclcommand_constraint_parse_slitpore(), tclcommand_constraint_parse_sphere(), tclcommand_constraint_parse_stomatocyte(), tclcommand_constraint_parse_wall(), tclcommand_constraint_print(), tclprint_to_result_Constraint(), tclprint_to_result_ConstraintForce(), and tclprint_to_result_n_constraints().
Referenced by tcl_register_commands().
static int tclcommand_constraint_mindist_position (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1671 of file constraint_tcl.cpp.
References ARG_IS_D, calculate_cylinder_dist(), calculate_hollow_cone_dist(), calculate_maze_dist(), calculate_plane_dist(), calculate_pore_dist(), calculate_rhomboid_dist(), calculate_slitpore_dist(), calculate_sphere_dist(), calculate_stomatocyte_dist(), calculate_wall_dist(), CONSTRAINT_CYL, CONSTRAINT_HOLLOW_CONE, CONSTRAINT_MAZE, CONSTRAINT_PLANE, CONSTRAINT_PORE, CONSTRAINT_RHOMBOID, CONSTRAINT_SLITPORE, CONSTRAINT_SPH, CONSTRAINT_STOMATOCYTE, CONSTRAINT_WAL, constraints, Constraint::cyl, Constraint::hollow_cone, Constraint::maze, mindist(), n_constraints, Constraint_wall::penetrable, Constraint_sphere::penetrable, Constraint_cylinder::penetrable, Constraint_rhomboid::penetrable, Constraint_maze::penetrable, Constraint_stomatocyte::penetrable, Constraint_hollow_cone::penetrable, Constraint::plane, Constraint::pore, Constraint::rhomboid, Constraint::slitpore, Constraint::sph, Constraint::stomatocyte, and Constraint::wal.
Referenced by tclcommand_constraint().
int tclcommand_constraint_mindist_position_vec (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1753 of file constraint_tcl.cpp.
References ARG_IS_D, calculate_cylinder_dist(), calculate_hollow_cone_dist(), calculate_maze_dist(), calculate_plane_dist(), calculate_pore_dist(), calculate_rhomboid_dist(), calculate_slitpore_dist(), calculate_sphere_dist(), calculate_stomatocyte_dist(), calculate_wall_dist(), CONSTRAINT_CYL, CONSTRAINT_HOLLOW_CONE, CONSTRAINT_MAZE, CONSTRAINT_PLANE, CONSTRAINT_PORE, CONSTRAINT_RHOMBOID, CONSTRAINT_SLITPORE, CONSTRAINT_SPH, CONSTRAINT_STOMATOCYTE, CONSTRAINT_WAL, constraints, Constraint::cyl, Constraint::hollow_cone, Constraint::maze, mindist(), n_constraints, Constraint_wall::penetrable, Constraint_sphere::penetrable, Constraint_cylinder::penetrable, Constraint_rhomboid::penetrable, Constraint_maze::penetrable, Constraint_stomatocyte::penetrable, Constraint_hollow_cone::penetrable, Constraint::plane, Constraint::pore, Constraint::rhomboid, Constraint::slitpore, Constraint::sph, Constraint::stomatocyte, and Constraint::wal.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_cylinder (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 489 of file constraint_tcl.cpp.
References Constraint_cylinder::axis, Constraint::c, CONSTRAINT_CYL, Constraint::cyl, Constraint_cylinder::direction, i, Constraint_cylinder::length, make_particle_type_exist(), Particle::p, Constraint::part_rep, Constraint_cylinder::penetrable, Constraint_cylinder::pos, Constraint_cylinder::rad, Constraint_cylinder::reflecting, SQR(), ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
int tclcommand_constraint_parse_ext_magn_field (Constraint * con, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1598 of file constraint_tcl.cpp.
References Constraint::c, CONSTRAINT_EXT_MAGN_FIELD, Constraint::emfield, Constraint_ext_magn_field::ext_magn_field, i, Particle::p, Constraint::part_rep, ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_hollow_cone (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1320 of file constraint_tcl.cpp.
References ARG_IS_D, ARG_IS_I, ARG_IS_S, Constraint::c, CONSTRAINT_HOLLOW_CONE, Constraint_hollow_cone::direction, Constraint::hollow_cone, Constraint_hollow_cone::inner_radius, M_PI, make_particle_type_exist(), Constraint_hollow_cone::opening_angle, Constraint_hollow_cone::orientation_x, Constraint_hollow_cone::orientation_y, Constraint_hollow_cone::orientation_z, Constraint_hollow_cone::outer_radius, Particle::p, Constraint::part_rep, Constraint_hollow_cone::penetrable, Constraint_hollow_cone::position_x, Constraint_hollow_cone::position_y, Constraint_hollow_cone::position_z, Constraint_hollow_cone::reflecting, ParticleProperties::type, Constraint::type, and Constraint_hollow_cone::width.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_maze (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1514 of file constraint_tcl.cpp.
References Constraint::c, CONSTRAINT_MAZE, Constraint_maze::cylrad, Constraint_maze::dim, make_particle_type_exist(), Constraint::maze, Constraint_maze::nsphere, Particle::p, Constraint::part_rep, Constraint_maze::penetrable, Constraint_maze::sphrad, ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_plane_cell (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1622 of file constraint_tcl.cpp.
References Constraint::c, CONSTRAINT_PLANE, make_particle_type_exist(), Particle::p, Constraint::part_rep, Constraint::plane, Constraint_plane::pos, ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_plate (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1104 of file constraint_tcl.cpp.
References Constraint::c, CONSTRAINT_PLATE, Particle::p, Constraint::part_rep, Constraint::plate, Constraint_plate::pos, Constraint_plate::sigma, ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_pore (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 790 of file constraint_tcl.cpp.
References Constraint_pore::axis, Constraint::c, CONSTRAINT_PORE, i, Constraint_pore::length, make_particle_type_exist(), Constraint_pore::outer_rad_left, Constraint_pore::outer_rad_right, Particle::p, Constraint::part_rep, Constraint::pore, Constraint_pore::pos, Constraint_pore::rad_left, Constraint_pore::rad_right, Constraint_pore::reflecting, Constraint_pore::smoothing_radius, SQR(), ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_rhomboid (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 617 of file constraint_tcl.cpp.
References Constraint_rhomboid::a, Constraint_rhomboid::b, Constraint_rhomboid::c, Constraint::c, CONSTRAINT_RHOMBOID, Constraint_rhomboid::direction, make_particle_type_exist(), Particle::p, Constraint::part_rep, Constraint_rhomboid::penetrable, Constraint_rhomboid::pos, Constraint_rhomboid::reflecting, Constraint::rhomboid, ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_rod (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1063 of file constraint_tcl.cpp.
References Constraint::c, CONSTRAINT_ROD, Constraint_rod::lambda, Particle::p, Constraint::part_rep, Constraint_rod::pos, Constraint::rod, ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_slitpore (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 945 of file constraint_tcl.cpp.
References Constraint::c, Constraint_slitpore::channel_width, CONSTRAINT_SLITPORE, Constraint_slitpore::lower_smoothing_radius, make_particle_type_exist(), Particle::p, Constraint::part_rep, Constraint_slitpore::pore_length, Constraint_slitpore::pore_mouth, Constraint_slitpore::pore_width, Constraint_slitpore::reflecting, Constraint::slitpore, ParticleProperties::type, Constraint::type, and Constraint_slitpore::upper_smoothing_radius.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_sphere (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 398 of file constraint_tcl.cpp.
References Constraint::c, CONSTRAINT_SPH, Constraint_sphere::direction, make_particle_type_exist(), Particle::p, Constraint::part_rep, Constraint_sphere::penetrable, Constraint_sphere::pos, Constraint_sphere::rad, Constraint_sphere::reflecting, Constraint::sph, ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_stomatocyte (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1136 of file constraint_tcl.cpp.
References ARG_IS_D, ARG_IS_I, ARG_IS_S, Constraint::c, CONSTRAINT_STOMATOCYTE, Constraint_stomatocyte::direction, Constraint_stomatocyte::inner_radius, Constraint_stomatocyte::layer_width, M_PI, make_particle_type_exist(), Constraint_stomatocyte::orientation_x, Constraint_stomatocyte::orientation_y, Constraint_stomatocyte::orientation_z, Constraint_stomatocyte::outer_radius, Particle::p, Constraint::part_rep, Constraint_stomatocyte::penetrable, Constraint_stomatocyte::position_x, Constraint_stomatocyte::position_y, Constraint_stomatocyte::position_z, Constraint_stomatocyte::reflecting, Constraint::stomatocyte, ParticleProperties::type, and Constraint::type.
Referenced by tclcommand_constraint().
static int tclcommand_constraint_parse_wall (Constraint * con, Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 300 of file constraint_tcl.cpp.
References Constraint::c, CONSTRAINT_WAL, Constraint_wall::d, i, make_particle_type_exist(), Constraint_wall::n, norm(), Constraint_wall::only_positive, Particle::p, Constraint::part_rep, Constraint_wall::penetrable, Constraint_wall::reflecting, SQR(), Constraint_wall::tunable_slip, ParticleProperties::type, Constraint::type, and Constraint::wal.
Referenced by tclcommand_constraint().
int tclcommand_constraint_print (Tcl_Interp * interp)
Definition at line 265 of file constraint_tcl.cpp.
References i, n_constraints, and tclprint_to_result_Constraint().
Referenced by tclcommand_constraint().
static int tclprint_to_result_Constraint (Tcl_Interp * interp, int i) static
Definition at line 31 of file constraint_tcl.cpp.
References Constraint_rhomboid::a, Constraint_cylinder::axis, Constraint_rhomboid::b, Constraint_rhomboid::c, Constraint::c, CONSTRAINT_CYL, CONSTRAINT_EXT_MAGN_FIELD, CONSTRAINT_HOLLOW_CONE, CONSTRAINT_MAZE, CONSTRAINT_PLANE, CONSTRAINT_PLATE, CONSTRAINT_PORE, CONSTRAINT_RHOMBOID, CONSTRAINT_ROD, CONSTRAINT_SPH, CONSTRAINT_STOMATOCYTE, CONSTRAINT_WAL, constraints, Constraint::cyl, Constraint_maze::cylrad, Constraint_wall::d, Constraint_maze::dim, Constraint_sphere::direction, Constraint_cylinder::direction, Constraint_rhomboid::direction, Constraint_stomatocyte::direction, Constraint_hollow_cone::direction, Constraint::emfield, Constraint_ext_magn_field::ext_magn_field, Constraint::hollow_cone, i, Constraint_stomatocyte::inner_radius, Constraint_hollow_cone::inner_radius, Constraint_rod::lambda, Constraint_stomatocyte::layer_width, Constraint_cylinder::length, Constraint::maze, Constraint_wall::n, Constraint_maze::nsphere, Constraint_wall::only_positive, Constraint_hollow_cone::opening_angle, Constraint_stomatocyte::orientation_x, Constraint_hollow_cone::orientation_x, Constraint_stomatocyte::orientation_y, Constraint_hollow_cone::orientation_y, Constraint_stomatocyte::orientation_z, Constraint_hollow_cone::orientation_z, Constraint_stomatocyte::outer_radius, Constraint_hollow_cone::outer_radius, Particle::p, Constraint::part_rep, Constraint_wall::penetrable, Constraint_sphere::penetrable, Constraint_cylinder::penetrable, Constraint_rhomboid::penetrable, Constraint_maze::penetrable, Constraint_stomatocyte::penetrable, Constraint_hollow_cone::penetrable, Constraint::plane, Constraint::plate, Constraint_sphere::pos, Constraint_cylinder::pos, Constraint_rhomboid::pos, Constraint_rod::pos, Constraint_plate::pos, Constraint_plane::pos, Constraint_stomatocyte::position_x, Constraint_hollow_cone::position_x, Constraint_stomatocyte::position_y, Constraint_hollow_cone::position_y, Constraint_stomatocyte::position_z, Constraint_hollow_cone::position_z, Constraint_sphere::rad, Constraint_cylinder::rad, Constraint_stomatocyte::reflecting, Constraint_hollow_cone::reflecting, Constraint::rhomboid, Constraint::rod, Constraint_plate::sigma, Constraint::sph, Constraint_maze::sphrad, Constraint::stomatocyte, Constraint_wall::tunable_slip, ParticleProperties::type, Constraint::type, Constraint::wal, and Constraint_hollow_cone::width.
Referenced by tclcommand_constraint(), and tclcommand_constraint_print().
static void tclprint_to_result_ConstraintForce (Tcl_Interp * interp, int con) static
Definition at line 277 of file constraint_tcl.cpp.
References mpi_get_constraint_force().
Referenced by tclcommand_constraint().
static void tclprint_to_result_n_constraints (Tcl_Interp * interp) static
Definition at line 293 of file constraint_tcl.cpp.
References n_constraints.
Referenced by tclcommand_constraint().