ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: constraint.hpp File Reference
constraint.hpp File Reference
Routines for handling of constraints.
#include "particle_data.hpp"
#include "interaction_data.hpp"
Functions
Constraint * generate_constraint ()
Exported functions.
void calculate_wall_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_wall *c, double *dist, double *vec)
void calculate_sphere_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_sphere *c, double *dist, double *vec)
void calculate_maze_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_maze *c, double *dist, double *vec)
void calculate_cylinder_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_cylinder *c, double *dist, double *vec)
void calculate_spherocylinder_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_spherocylinder *c, double *dist, double *vec)
void calculate_rhomboid_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_rhomboid *c, double *dist, double *vec)
void calculate_pore_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_pore *c, double *dist, double *vec)
void calculate_slitpore_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_slitpore *c, double *dist, double *vec)
void calculate_plane_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_plane *c, double *dist, double *vec)
void calculate_stomatocyte_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_stomatocyte *cons, double *dist, double *vec)
void calculate_hollow_cone_dist (Particle *p1, double ppos[3], Particle *c_p, Constraint_hollow_cone *cons, double *dist, double *vec)
void add_rod_force (Particle *p1, double ppos[3], Particle *c_p, Constraint_rod *c)
double rod_energy (Particle *p1, double ppos[3], Particle *c_p, Constraint_rod *c)
void add_plate_force (Particle *p1, double ppos[3], Particle *c_p, Constraint_plate *c)
double plate_energy (Particle *p1, double ppos[3], Particle *c_p, Constraint_plate *c)
void add_ext_magn_field_force (Particle *p1, Constraint_ext_magn_field *c)
double ext_magn_field_energy (Particle *p1, Constraint_ext_magn_field *c)
void reflect_particle (Particle *p1, double *distance_vec, int reflecting)
void add_constraints_forces (Particle *p1)
double add_constraints_energy (Particle *p1)
void init_constraint_forces ()
Variables
int n_constraints
number of constraints.
Constraint * constraints
field containing constraints.
int reflection_happened
Detailed Description
Routines for handling of constraints.
Only active if the feature CONSTRAINTS is activated. see also interaction_data.hpp
Definition in file constraint.hpp.
Function Documentation
double add_constraints_energy (Particle * p1)
Definition at line 2639 of file constraint.cpp.
References calc_non_bonded_pair_energy(), calculate_cylinder_dist(), calculate_hollow_cone_dist(), calculate_maze_dist(), calculate_pore_dist(), calculate_rhomboid_dist(), calculate_sphere_dist(), calculate_stomatocyte_dist(), calculate_wall_dist(), checkIfInteraction(), CONSTRAINT_CYL, CONSTRAINT_EXT_MAGN_FIELD, CONSTRAINT_HOLLOW_CONE, CONSTRAINT_MAZE, CONSTRAINT_NONE, CONSTRAINT_PLANE, CONSTRAINT_PLATE, CONSTRAINT_PORE, CONSTRAINT_RHOMBOID, CONSTRAINT_ROD, CONSTRAINT_SLITPORE, CONSTRAINT_SPH, CONSTRAINT_STOMATOCYTE, CONSTRAINT_WAL, Observable_stat::coulomb, Constraint::cyl, Observable_stat::dipolar, Constraint::emfield, energy, errexit(), ext_magn_field_energy(), fold_position(), get_ia_param(), Constraint::hollow_cone, ParticleLocal::i, ia_params, ParticleProperties::identity, Particle::l, Constraint::maze, n_constraints, Observable_stat::n_coulomb, Observable_stat::n_dipolar, obsstat_nonbonded(), ParticlePosition::p, Particle::p, Constraint::part_rep, Constraint_wall::penetrable, Constraint_sphere::penetrable, Constraint_cylinder::penetrable, Constraint_rhomboid::penetrable, Constraint_maze::penetrable, Constraint_stomatocyte::penetrable, Constraint_hollow_cone::penetrable, Constraint::plate, plate_energy(), Constraint::pore, Particle::r, Constraint::rhomboid, Constraint::rod, rod_energy(), runtimeError, Constraint::sph, Constraint::stomatocyte, ParticleProperties::type, Constraint::wal, and warnings.
Referenced by calculate_link_cell_energies(), calculate_verlet_energies(), layered_calculate_energies(), and nsq_calculate_energies().
void add_constraints_forces (Particle * p1)
Definition at line 2308 of file constraint.cpp.
References add_ext_magn_field_force(), add_plate_force(), add_rod_force(), add_tunable_slip_pair_force(), calc_non_bonded_pair_force(), calculate_cylinder_dist(), calculate_hollow_cone_dist(), calculate_maze_dist(), calculate_plane_dist(), calculate_pore_dist(), calculate_rhomboid_dist(), calculate_slitpore_dist(), calculate_sphere_dist(), calculate_stomatocyte_dist(), calculate_wall_dist(), checkIfInteraction(), CONSTRAINT_CYL, CONSTRAINT_EXT_MAGN_FIELD, CONSTRAINT_HOLLOW_CONE, CONSTRAINT_MAZE, CONSTRAINT_NONE, CONSTRAINT_PLANE, CONSTRAINT_PLATE, CONSTRAINT_PORE, CONSTRAINT_RHOMBOID, CONSTRAINT_ROD, CONSTRAINT_SLITPORE, CONSTRAINT_SPH, CONSTRAINT_STOMATOCYTE, CONSTRAINT_WAL, Constraint::cyl, Constraint::emfield, errexit(), ParticleForce::f, Particle::f, fold_position(), get_ia_param(), Constraint::hollow_cone, ParticleLocal::i, ia_params, ParticleProperties::identity, Particle::l, Constraint::maze, n_constraints, Constraint_wall::only_positive, ParticlePosition::p, Particle::p, Constraint::part_rep, Constraint_wall::penetrable, Constraint_sphere::penetrable, Constraint_cylinder::penetrable, Constraint_rhomboid::penetrable, Constraint_maze::penetrable, Constraint_stomatocyte::penetrable, Constraint_hollow_cone::penetrable, Constraint::plane, Constraint::plate, Constraint::pore, Particle::r, reflect_particle(), Constraint_wall::reflecting, Constraint_sphere::reflecting, Constraint_cylinder::reflecting, Constraint_rhomboid::reflecting, Constraint_pore::reflecting, Constraint_stomatocyte::reflecting, Constraint_hollow_cone::reflecting, Constraint::rhomboid, Constraint::rod, runtimeError, Constraint::slitpore, Constraint::sph, Constraint::stomatocyte, ParticleForce::torque, Constraint_wall::tunable_slip, ParticleProperties::type, and Constraint::wal.
Referenced by build_verlet_lists_and_calc_verlet_ia(), calc_link_cell(), calculate_verlet_ia(), layered_calculate_ia(), and nsq_calculate_ia().
void add_ext_magn_field_force (Particle * p1, Constraint_ext_magn_field * c)
Definition at line 2237 of file constraint.cpp.
References ParticlePosition::dip, Constraint_ext_magn_field::ext_magn_field, Particle::f, Particle::r, and ParticleForce::torque.
Referenced by add_constraints_forces().
void add_plate_force (Particle * p1, double ppos[3], Particle * c_p, Constraint_plate * c)
Definition at line 2212 of file constraint.cpp.
References coulomb, ParticleForce::f, Particle::f, M_PI, Particle::p, Constraint_plate::pos, Coulomb_parameters::prefactor, ParticleProperties::q, and Constraint_plate::sigma.
Referenced by add_constraints_forces().
void add_rod_force (Particle * p1, double ppos[3], Particle * c_p, Constraint_rod * c)
Definition at line 2172 of file constraint.cpp.
References coulomb, ParticleForce::f, Particle::f, i, Constraint_rod::lambda, Particle::p, Constraint_rod::pos, Coulomb_parameters::prefactor, ParticleProperties::q, and SQR().
Referenced by add_constraints_forces().
void calculate_cylinder_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_cylinder * c, double * dist, double * vec)
Definition at line 170 of file constraint.cpp.
References Constraint_cylinder::axis, Constraint_cylinder::direction, i, Constraint_cylinder::length, Constraint_cylinder::pos, Constraint_cylinder::rad, and SQR().
Referenced by add_constraints_energy(), add_constraints_forces(), calculate_spherocylinder_dist(), constraint_collision(), lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
void calculate_hollow_cone_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_hollow_cone * cons, double * dist, double * vec)
Definition at line 1690 of file constraint.cpp.
References Constraint_hollow_cone::direction, distance(), i, Constraint_hollow_cone::inner_radius, mindist(), normalize(), Constraint_hollow_cone::opening_angle, Constraint_hollow_cone::orientation_x, Constraint_hollow_cone::orientation_y, Constraint_hollow_cone::orientation_z, Constraint_hollow_cone::outer_radius, Constraint_hollow_cone::position_x, Constraint_hollow_cone::position_y, Constraint_hollow_cone::position_z, time2, and Constraint_hollow_cone::width.
Referenced by add_constraints_energy(), add_constraints_forces(), lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
void calculate_maze_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_maze * c, double * dist, double * vec)
Definition at line 106 of file constraint.cpp.
References box_l, Constraint_maze::cylrad, Constraint_maze::dim, i, Constraint_maze::nsphere, Constraint_maze::sphrad, and SQR().
Referenced by add_constraints_energy(), add_constraints_forces(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
void calculate_plane_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_plane * c, double * dist, double * vec)
Definition at line 1121 of file constraint.cpp.
References i, Constraint_plane::pos, and SQR().
Referenced by add_constraints_forces(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
void calculate_pore_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_pore * c, double * dist, double * vec)
Definition at line 915 of file constraint.cpp.
References Constraint_pore::axis, i, Constraint_pore::length, norm(), Constraint_pore::outer_rad_left, Constraint_pore::outer_rad_right, Constraint_pore::pos, Constraint_pore::rad_left, Constraint_pore::rad_right, sign(), Constraint_pore::smoothing_radius, and SQR().
Referenced by add_constraints_energy(), add_constraints_forces(), lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
void calculate_rhomboid_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_rhomboid * c, double * dist, double * vec)
Definition at line 271 of file constraint.cpp.
References Constraint_rhomboid::a, Constraint_rhomboid::b, Constraint_rhomboid::c, Constraint_rhomboid::direction, and Constraint_rhomboid::pos.
Referenced by add_constraints_energy(), add_constraints_forces(), lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
void calculate_slitpore_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_slitpore * c, double * dist, double * vec)
Definition at line 2889 of file constraint.cpp.
References box_l, Constraint_slitpore::channel_width, Constraint_slitpore::lower_smoothing_radius, Constraint_slitpore::pore_length, Constraint_slitpore::pore_mouth, Constraint_slitpore::pore_width, SQR(), and Constraint_slitpore::upper_smoothing_radius.
Referenced by add_constraints_forces(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
void calculate_sphere_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_sphere * c, double * dist, double * vec)
Definition at line 80 of file constraint.cpp.
References Constraint_sphere::direction, i, Constraint_sphere::pos, Constraint_sphere::rad, and SQR().
Referenced by add_constraints_energy(), add_constraints_forces(), constraint_collision(), lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
void calculate_spherocylinder_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_spherocylinder * c, double * dist, double * vec)
Definition at line 235 of file constraint.cpp.
References Constraint_spherocylinder::axis, calculate_cylinder_dist(), Constraint_spherocylinder::direction, i, Constraint_spherocylinder::length, Constraint_spherocylinder::pos, Constraint_spherocylinder::rad, and sign().
Referenced by lb_init_boundaries(), and lbboundary_mindist_position().
void calculate_stomatocyte_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_stomatocyte * cons, double * dist, double * vec)
Definition at line 1145 of file constraint.cpp.
References Constraint_stomatocyte::direction, distance(), i, Constraint_stomatocyte::inner_radius, Constraint_stomatocyte::layer_width, M_PI, mindist(), Constraint_stomatocyte::orientation_x, Constraint_stomatocyte::orientation_y, Constraint_stomatocyte::orientation_z, Constraint_stomatocyte::outer_radius, Constraint_stomatocyte::position_x, Constraint_stomatocyte::position_y, and Constraint_stomatocyte::position_z.
Referenced by add_constraints_energy(), add_constraints_forces(), lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
void calculate_wall_dist (Particle * p1, double ppos[3], Particle * c_p, Constraint_wall * c, double * dist, double * vec)
Definition at line 68 of file constraint.cpp.
References Constraint_wall::d, i, and Constraint_wall::n.
Referenced by add_constraints_energy(), add_constraints_forces(), constraint_collision(), lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
double ext_magn_field_energy (Particle * p1, Constraint_ext_magn_field * c)
Definition at line 2248 of file constraint.cpp.
References ParticlePosition::dip, Constraint_ext_magn_field::ext_magn_field, Particle::r, and scalar().
Referenced by add_constraints_energy().
Constraint* generate_constraint ()
Exported functions.
Definition at line 41 of file constraint.cpp.
References CONSTRAINT_NONE, ParticleProperties::identity, n_constraints, Particle::p, Constraint::part_rep, realloc, and Constraint::type.
Referenced by tclcommand_constraint().
void init_constraint_forces ()
Definition at line 51 of file constraint.cpp.
References i, and n_constraints.
Referenced by init_forces().
double plate_energy (Particle * p1, double ppos[3], Particle * c_p, Constraint_plate * c)
Definition at line 2227 of file constraint.cpp.
References coulomb, M_PI, Particle::p, Constraint_plate::pos, Coulomb_parameters::prefactor, ParticleProperties::q, and Constraint_plate::sigma.
Referenced by add_constraints_energy().
void reflect_particle (Particle * p1, double * distance_vec, int reflecting)
Definition at line 2257 of file constraint.cpp.
References fold_position(), ParticleLocal::i, Particle::l, Particle::m, norm(), ParticlePosition::p, Particle::r, reflection_happened, and ParticleMomentum::v.
Referenced by add_constraints_forces().
double rod_energy (Particle * p1, double ppos[3], Particle * c_p, Constraint_rod * c)
Definition at line 2194 of file constraint.cpp.
References box_l_i, C_GAMMA, coulomb, i, Constraint_rod::lambda, M_LN2, Particle::p, Constraint_rod::pos, Coulomb_parameters::prefactor, ParticleProperties::q, and SQR().
Referenced by add_constraints_energy().
Variable Documentation
Constraint* constraints
field containing constraints.
Definition at line 39 of file constraint.cpp.
Referenced by calc_angledist_param(), calc_endangledist_pair_force(), calc_pwangle(), calc_pwdist(), constraint_collision(), mpi_bcast_constraint(), mpi_bcast_constraint_slave(), mpi_get_constraint_force(), mpi_get_constraint_force_slave(), tclcommand_constraint_mindist_position(), tclcommand_constraint_mindist_position_vec(), tclcommand_polymer(), and tclprint_to_result_Constraint().
int n_constraints
number of constraints.
Definition at line 38 of file constraint.cpp.
Referenced by add_constraints_energy(), add_constraints_forces(), calc_angledist_param(), calc_pwdist(), constraint_collision(), generate_constraint(), init_constraint_forces(), mpi_bcast_constraint(), mpi_bcast_constraint_slave(), tclcommand_constraint(), tclcommand_constraint_mindist_position(), tclcommand_constraint_mindist_position_vec(), tclcommand_constraint_print(), tclcommand_polymer(), and tclprint_to_result_n_constraints().
int reflection_happened
Definition at line 34 of file constraint.cpp.
Referenced by reflect_particle().