ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: particle_data.cpp File Reference
core/particle_data.cpp File Reference
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <mpi.h>
#include "utils.hpp"
#include "particle_data.hpp"
#include "global.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "interaction_data.hpp"
#include "integrate.hpp"
#include "cells.hpp"
#include "rotation.hpp"
#include "virtual_sites.hpp"
Macros
#define PART_INCREMENT 8
granularity of the particle buffers in particles
#define REQ_SNDRCV_PART 0xaa
my magic MPI code for send/recv_particles
Functions
int try_delete_bond (Particle *part, int *bond)
Remove bond from particle if possible.
void try_delete_exclusion (Particle *part, int part2)
Remove exclusion from particle if possible.
void try_add_exclusion (Particle *part, int part2)
Insert an exclusion if not already set.
void auto_exclusion (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
void init_particle (Particle *part)
Initialize a particle.
void free_particle (Particle *part)
Deallocate the dynamic storage of a particle.
int updatePartCfg (int bonds_flag)
Get the complete unsorted informations on all particles into partCfg if something's changed.
int sortPartCfg ()
sorts the partCfg array.
void freePartCfg ()
release the partCfg array.
void realloc_local_particles (int part)
resize local_particles.
static void realloc_particle_node (int part)
resize particle_node.
void particle_invalidate_part_node ()
Invalidate particle_node.
void build_particle_node ()
Rebuild particle_node from scratch.
void init_particlelist (ParticleList *pList)
Initialize a particle list.
int realloc_particlelist (ParticleList *l, int size)
Allocate storage for local particles and ghosts.
void update_local_particles (ParticleList *pl)
Update the entries in local_particles for all particles in the list pl.
Particle * got_particle (ParticleList *l, int id)
Search for a specific particle.
Particle * append_unindexed_particle (ParticleList *l, Particle *part)
Append a particle at the end of a particle List.
Particle * append_indexed_particle (ParticleList *l, Particle *part)
Append a particle at the end of a particle List.
Particle * move_unindexed_particle (ParticleList *dl, ParticleList *sl, int i)
Remove a particle from one particle List and append it to another.
Particle * move_indexed_particle (ParticleList *dl, ParticleList *sl, int i)
Remove a particle from one particle List and append it to another.
int get_particle_data (int part, Particle *data)
Get particle data.
int place_particle (int part, double p[3])
Call only on the master node.
int set_particle_v (int part, double v[3])
Call only on the master node: set particle velocity.
int set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the master node: set particle velocity.
int set_particle_f (int part, double F[3])
Call only on the master node: set particle force.
int set_particle_solvation (int part, double *solvation)
Call only on the master node: set particle solvation free energy.
int set_particle_mass (int part, double mass)
Call only on the master node: set particle mass.
int set_particle_rotational_inertia (int part, double rinertia[3])
Call only on the master node: set particle rotational inertia.
int set_particle_rotation (int part, int rot)
Call only on the master node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
int set_particle_dipm (int part, double dipm)
Call only on the master node: set particle dipole moment (absolut value).
int set_particle_dip (int part, double dip[3])
Call only on the master node: set particle dipole orientation.
int set_particle_virtual (int part, int isVirtual)
Call only on the master node: set particle dipole moment (absolut value).
int set_particle_vs_relative (int part, int vs_relative_to, double vs_distance)
int set_particle_smaller_timestep (int part, int smaller_timestep)
Call only on the master node: set particle smaller time step flag.
int set_particle_q (int part, double q)
Call only on the master node: set particle charge.
int set_particle_mu_E (int part, double mu_E[3])
Call only on the master node: set particle electrophoretic mobility.
int set_particle_type (int part, int type)
Call only on the master node: set particle type.
int set_particle_mol_id (int part, int mid)
Call only on the master node: set particle's molecule id.
int set_particle_quat (int part, double quat[4])
Call only on the master node: set particle orientation using quaternions.
int set_particle_omega_lab (int part, double omega_lab[3])
Call only on the master node: set particle angular velocity from lab frame.
int set_particle_omega_body (int part, double omega[3])
Call only on the master node: set particle angular velocity in body frame.
int set_particle_torque_lab (int part, double torque_lab[3])
Call only on the master node: set particle torque from lab frame.
int set_particle_torque_body (int part, double torque[3])
Call only on the master node: set particle torque in body frame.
int set_particle_temperature (int part, double T)
Call only on the master node: set particle temperature.
int set_particle_gamma (int part, double gamma)
Call only on the master node: set particle frictional coefficient.
int set_particle_ext_torque (int part, int flag, double torque[3])
Call only on the master node: set particle external torque.
int set_particle_ext_force (int part, int flag, double force[3])
Call only on the master node: set particle external force.
int set_particle_fix (int part, int flag)
Call only on the master node: set coordinate axes for which the particles motion is fixed.
int change_particle_bond (int part, int *bond, int _delete)
Call only on the master node: change particle bond.
void remove_all_particles ()
remove all particles.
int remove_particle (int part)
remove particle with a given identity.
void local_remove_particle (int part)
Used by mpi_remove_particle, should not be used elsewhere.
void local_place_particle (int part, double p[3], int _new)
Used by mpi_place_particle, should not be used elsewhere.
void local_remove_all_particles ()
Used by mpi_remove_particle, should not be used elsewhere.
void local_rescale_particles (int dir, double scale)
Used by mpi_rescale_particles, should not be used elsewhere.
void added_particle (int part)
Used by mpi_place_particle, should not be used elsewhere.
int local_change_bond (int part, int *bond, int _delete)
Used by mpi_send_bond, should not be used elsewhere.
void remove_all_bonds_to (int identity)
for all local particles, remove bonds incorporating the specified particle.
void local_change_exclusion (int part1, int part2, int _delete)
Used for example by mpi_send_exclusion.
void send_particles (ParticleList *particles, int node)
Synchronous send of a particle buffer to another node.
void recv_particles (ParticleList *particles, int node)
Synchronous receive of a particle buffer from another node.
void add_partner (IntList *il, int i, int j, int distance)
int change_exclusion (int part1, int part2, int _delete)
Call only on the master node: change particle constraints.
void remove_all_exclusions ()
remove all exclusions.
int init_gc (void)
int init_type_array (int type)
init particle lists
int reallocate_type_array (int type)
resize the array for the list of ids for a certain type
int remove_id_type_array (int part_id, int type)
int update_particle_array (int type)
int reallocate_global_type_list (int size)
make more type_arrays available
int find_particle_type (int type, int *id)
int find_particle_type_id (int type, int *id, int *in_id)
return an array with real particle id and the corresponding index of typelist
int delete_particle_of_type (int type)
delete one randomly chosen particle of given type returns ES_OK if succesful or else ES_ERROR
int add_particle_to_list (int part_id, int type)
int gc_status (int type)
int free_particle_lists (void)
free particle lists
int number_of_particles_with_type (int type, int *number)
void pointer_to_omega_body (Particle *p, double *&res)
void pointer_to_torque_lab (Particle *p, double *&res)
void pointer_to_quat (Particle *p, double *&res)
void pointer_to_quatu (Particle *p, double *&res)
void pointer_to_q (Particle *p, double *&res)
void pointer_to_virtual (Particle *p, int *&res)
void pointer_to_vs_relative (Particle *p, int *&res1, double *&res2)
void pointer_to_mass (Particle *p, double *&res)
void pointer_to_dip (Particle *p, double *&res)
void pointer_to_dipm (Particle *p, double *&res)
void pointer_to_ext_force (Particle *p, int *&res1, double *&res2)
void pointer_to_ext_torque (Particle *p, int *&res1, double *&res2)
void pointer_to_fix (Particle *p, int *&res)
void pointer_to_gamma (Particle *p, double *&res)
void pointer_to_temperature (Particle *p, double *&res)
void pointer_to_rotation (Particle *p, int *&res)
void pointer_to_exclusions (Particle *p, int *&res1, int *&res2)
void pointer_to_swimming (Particle *p, ParticleParametersSwimming *&swim)
void pointer_to_rotational_inertia (Particle *p, double *&res)
Variables
TypeOfIndex Type
IndexOfType Index
TypeList * type_array
int number_of_type_lists
int GC_init
int Type_array_init
int max_seen_particle = -1
Highest particle number seen so far.
int n_part = 0
total number of particles on all nodes.
int max_particle_node = 0
Capacity of the particle_node / local_particles.
int * particle_node = NULL
Used only on master node: particle->node mapping.
int max_local_particles = 0
Particle ** local_particles = NULL
id->particle mapping on all nodes.
Particle * partCfg = NULL
Particles' current configuration.
int partCfgSorted = 0
if non zero, partCfg is sorted by particle order, and the particles are stored consecutively starting with 0.
IntList partCfg_bl = { NULL, 0, 0 }
bondlist for partCfg, if bonds are needed
Macro Definition Documentation
#define PART_INCREMENT 8
granularity of the particle buffers in particles
Definition at line 51 of file core/particle_data.cpp.
Referenced by realloc_local_particles(), realloc_particle_node(), and realloc_particlelist().
#define REQ_SNDRCV_PART 0xaa
my magic MPI code for send/recv_particles
Definition at line 54 of file core/particle_data.cpp.
Referenced by recv_particles(), and send_particles().
Function Documentation
int add_particle_to_list (int part_id, int type)
Definition at line 1968 of file core/particle_data.cpp.
References ES_ERROR, ES_OK, i, TypeList::id_list, TypeOfIndex::index, TypeOfIndex::max_entry, TypeList::max_entry, NOT_INDEXED, reallocate_type_array(), and IndexOfType::type.
Referenced by set_particle_type().
void add_partner (IntList * il, int i, int j, int distance)
Definition at line 1620 of file core/particle_data.cpp.
References distance(), IntList::e, IntList::n, and realloc_intlist().
Referenced by auto_exclusion(), and tclcommand_part_print_bond_partners().
void added_particle (int part)
Used by mpi_place_particle, should not be used elsewhere.
Called if on a different node a new particle was added.
Parameters
part the identity of the particle added
Definition at line 1341 of file core/particle_data.cpp.
References i, n_part, and realloc_local_particles().
Referenced by mpi_place_new_particle(), and mpi_place_new_particle_slave().
Particle* append_indexed_particle (ParticleList * plist, Particle * part)
Append a particle at the end of a particle List.
reallocates particles if necessary! This procedure cares for local_particles.
Parameters
plist List to append the particle to.
part Particle to append.
Returns
Pointer to new location of the particle.
Definition at line 488 of file core/particle_data.cpp.
References ParticleProperties::identity, ParticleList::n, Particle::p, ParticleList::part, realloc_particlelist(), and update_local_particles().
Referenced by dd_append_particles().
Particle* append_unindexed_particle (ParticleList * plist, Particle * part)
Append a particle at the end of a particle List.
reallocates particles if necessary! This procedure does not care for local_particles.
Parameters
plist List to append the particle to.
part Particle to append.
Returns
Pointer to new location of the particle.
Definition at line 477 of file core/particle_data.cpp.
References ParticleList::n, ParticleList::part, and realloc_particlelist().
Referenced by dd_topology_init(), layered_topology_init(), and nsq_topology_init().
void auto_exclusion (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
This uses the bond topology obtained directly from the particles, since only this contains the full topology, in contrast to topology::topology. To easily setup the bonds, all data should be on a single node, therefore the partCfg array is used. With large amounts of particles, you should avoid this function and setup exclusions manually.
Definition at line 1656 of file core/particle_data.cpp.
References add_partner(), Particle::bl, bonded_ia_params, change_exclusion(), distance(), IntList::e, free, i, ia_params, ParticleProperties::identity, init_intlist(), malloc, max_seen_particle, IntList::n, n_part, Bonded_ia_parameters::num, Particle::p, realloc_intlist(), updatePartCfg(), and WITH_BONDS.
Referenced by tclcommand_part().
void build_particle_node ()
Rebuild particle_node from scratch.
After a simulation step particle_node has to be rebuild since the particles might have gone to a different node.
Definition at line 419 of file core/particle_data.cpp.
References max_seen_particle, mpi_who_has(), and realloc_particle_node().
Referenced by change_exclusion(), change_particle_bond(), get_particle_data(), place_particle(), remove_particle(), set_particle_dip(), set_particle_dipm(), set_particle_ext_force(), set_particle_ext_torque(), set_particle_f(), set_particle_fix(), set_particle_gamma(), set_particle_mass(), set_particle_mol_id(), set_particle_mu_E(), set_particle_omega_body(), set_particle_omega_lab(), set_particle_q(), set_particle_quat(), set_particle_rotation(), set_particle_rotational_inertia(), set_particle_smaller_timestep(), set_particle_solvation(), set_particle_swimming(), set_particle_temperature(), set_particle_torque_body(), set_particle_torque_lab(), set_particle_type(), set_particle_v(), set_particle_virtual(), set_particle_vs_relative(), tclcommand_part_parse_bond(), tclcommand_part_parse_cmd(), tclcommand_part_parse_exclusion(), tclcommand_part_print_all(), tclcommand_readmd(), and tclcommand_writemd().
int change_exclusion (int part, int part2, int _delete)
Call only on the master node: change particle constraints.
Parameters
part identity of particle for which the exclusion is set.
part2 identity of particle for which the exclusion is set. If -1, delete all exclusions.
_delete if true, do not add the exclusion, rather delete it if found
Returns
ES_OK on success or ES_ERROR if no success (e. g. particles do not exist / did not have exclusion set)
Definition at line 1634 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_send_exclusion(), and particle_node.
Referenced by auto_exclusion(), and tclcommand_part_parse_exclusion().
int change_particle_bond (int part, int * bond, int _delete)
Call only on the master node: change particle bond.
Parameters
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secundary atoms of the bond). If NULL, delete all bonds.
_delete if true, do not add the bond, rather delete it if found
Returns
ES_OK on success or ES_ERROR if no success (e. g. particle or bond to delete does not exist)
Definition at line 1143 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, mpi_send_bond(), n_bonded_ia, particle_node, and runtimeError.
Referenced by crosslinkC(), diamondC(), icosaederC(), polymerC(), and tclcommand_part_parse_bond().
int delete_particle_of_type (int type)
delete one randomly chosen particle of given type returns ES_OK if succesful or else ES_ERROR
Definition at line 1948 of file core/particle_data.cpp.
References ES_ERROR, ES_OK, find_particle_type_id(), malloc, TypeList::max_entry, remove_particle(), and IndexOfType::type.
Referenced by part_parse_gc().
int find_particle_type (int type, int * id)
Definition at line 1902 of file core/particle_data.cpp.
References ES_ERROR, ES_OK, i, i_random(), TypeList::id_list, TypeOfIndex::index, TypeOfIndex::max_entry, TypeList::max_entry, and IndexOfType::type.
Referenced by part_parse_gc().
int find_particle_type_id (int type, int * id, int * in_id)
return an array with real particle id and the corresponding index of typelist
Definition at line 1923 of file core/particle_data.cpp.
References ES_ERROR, ES_OK, i, i_random(), TypeList::id_list, TypeOfIndex::index, TypeOfIndex::max_entry, TypeList::max_entry, and IndexOfType::type.
Referenced by delete_particle_of_type().
void free_particle (Particle * part)
Deallocate the dynamic storage of a particle.
Definition at line 305 of file core/particle_data.cpp.
References Particle::bl, Particle::el, and realloc_intlist().
Referenced by local_remove_particle(), prepare_ghost_cell(), send_particles(), tclcommand_analyze_parse_reference_point(), tclcommand_part_parse_print(), tclcommand_writemd(), and tclprint_to_result_Particle().
int free_particle_lists (void)
free particle lists
Definition at line 2024 of file core/particle_data.cpp.
References ES_OK, free, i, TypeOfIndex::index, TypeOfIndex::max_entry, and IndexOfType::type.
void freePartCfg ()
release the partCfg array.
Use this function, since it also frees the bonds, if they are used.
Definition at line 377 of file core/particle_data.cpp.
References free, and realloc_intlist().
Referenced by on_integration_start(), on_particle_change(), and tclcommand_analyze_parse_get_folded_positions().
int gc_status (int type)
Definition at line 2005 of file core/particle_data.cpp.
References ES_ERROR, ES_OK, i, TypeOfIndex::index, TypeOfIndex::max_entry, TypeList::max_entry, and IndexOfType::type.
int get_particle_data (int part, Particle * data)
Get particle data.
Note that the bond intlist is allocated so that you are responsible to free it later.
Parameters
part the identity of the particle to fetch
data where to store its contents.
Returns
ES_OK if particle existed
Definition at line 550 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_recv_part(), and particle_node.
Referenced by IBM_Tribend_SetParams(), IBM_Triel_SetParams(), remove_particle(), set_particle_omega_lab(), set_particle_torque_lab(), set_particle_type(), tclcommand_analyze_parse_and_print_check_mol(), tclcommand_analyze_parse_reference_point(), tclcommand_part_parse_print(), tclcommand_part_parse_swimming(), tclcommand_writemd(), tclprint_to_result_Particle(), and vs_relate_to().
Particle* got_particle (ParticleList * plist, int id)
Search for a specific particle.
Parameters
plist the list on which to operate
id the identity of the particle to search
Returns
a pointer to the particle structure or NULL if particle is not in this list
Definition at line 465 of file core/particle_data.cpp.
References i, ParticleProperties::identity, ParticleList::n, Particle::p, and ParticleList::part.
int init_gc (void)
Definition at line 1730 of file core/particle_data.cpp.
References ES_ERROR, ES_OK, GC_init, malloc, IndexOfType::max_entry, TypeOfIndex::max_entry, number_of_type_lists, and Type_array_init.
Referenced by init_type_array().
void init_particle (Particle * part)
Initialize a particle.
This function just sets all values to the defaults (mostly zeros)! Do NOT use this without setting the values of the identity and position to reasonable values. Also make sure that you update local_particles.
Add here all initializations you need to be done !!! If dynamic memory allocation is involved, also look at free_particle.
Definition at line 103 of file core/particle_data.cpp.
References Particle::bl, ParticleProperties::catalyzer_count, ParticlePosition::composition, ParticlePosition::dip, ParticleProperties::dipm, ParticleParametersSwimming::dipole_length, Particle::el, ParticleProperties::ext_flag, ParticleProperties::ext_force, ParticleProperties::ext_torque, ParticleForce::f, Particle::f, ParticleParametersSwimming::f_swim, ParticleProperties::gamma, ParticleLocal::ghost, ParticleLocal::i, ParticleProperties::identity, init_intlist(), ParticleProperties::isVirtual, Particle::l, LB_COMPONENTS, Particle::m, ParticleLocal::m_ls, ParticleProperties::mass, ParticleProperties::mol_id, ParticleProperties::mu_E, ParticleMomentum::omega, ParticlePosition::p, Particle::p, ParticlePosition::p_old, ParticleLocal::p_old, ParticleParametersSwimming::push_pull, ParticleProperties::q, ParticlePosition::quat, ParticlePosition::quatu, Particle::r, ParticleLocal::r_ls, ParticleProperties::rinertia, ParticleProperties::rotation, ParticleParametersSwimming::rotational_friction, ParticleProperties::smaller_timestep, ParticleProperties::solvation, Particle::swim, ParticleParametersSwimming::swimming, ParticleProperties::T, ParticleForce::torque, ParticleProperties::type, ParticleMomentum::v, ParticleParametersSwimming::v_swim, ParticleProperties::vs_relative_distance, and ParticleProperties::vs_relative_to_particle_id.
Referenced by local_place_particle().
void init_particlelist (ParticleList * pList)
Initialize a particle list.
Use with care and ONLY for initialization!
Definition at line 425 of file core/particle_data.cpp.
References ParticleList::max, ParticleList::n, and ParticleList::part.
Referenced by dd_exchange_and_sort_particles(), layered_exchange_and_sort_particles(), nsq_balance_particles(), and realloc_cells().
int init_type_array (int type)
init particle lists
Definition at line 1748 of file core/particle_data.cpp.
References TypeList::cur_size, ES_ERROR, ES_OK, i, TypeList::id_list, ParticleProperties::identity, TypeOfIndex::index, init_gc(), malloc, IndexOfType::max_entry, TypeOfIndex::max_entry, TypeList::max_entry, n_part, number_of_type_lists, Particle::p, realloc, reallocate_global_type_list(), IndexOfType::type, Type_array_init, updatePartCfg(), and WITHOUT_BONDS.
Referenced by number_of_particles_with_type(), and part_parse_gc().
int local_change_bond (int part, int * bond, int _delete)
Used by mpi_send_bond, should not be used elsewhere.
Modify a bond.
Parameters
part the identity of the particle to change
bond the bond to do
_delete if true, delete the bond instead of add
Returns
ES_OK for add or successful delete, ES_ERROR else
Definition at line 1356 of file core/particle_data.cpp.
References Particle::bl, bonded_ia_params, IntList::e, ES_OK, i, IntList::n, Bonded_ia_parameters::num, realloc_intlist(), and try_delete_bond().
Referenced by detect_collision(), handle_collisions(), mpi_send_bond(), and mpi_send_bond_slave().
void local_change_exclusion (int part1, int part2, int _delete)
Used for example by mpi_send_exclusion.
Locally add a exclusion to a particle.
Parameters
part1 the identity of the first exclusion partner
part2 the identity of the second exclusion partner
_delete if true, delete the exclusion instead of add
Definition at line 1446 of file core/particle_data.cpp.
References CellPList::cell, local_cells, CellPList::n, ParticleList::n, ParticleList::part, realloc_intlist(), try_add_exclusion(), and try_delete_exclusion().
Referenced by mpi_send_exclusion(), and mpi_send_exclusion_slave().
void local_place_particle (int part, double p[3], int _new)
Used by mpi_place_particle, should not be used elsewhere.
Move a particle to a new position. If it does not exist, it is created. the position must be on the local node!
Parameters
part the identity of the particle to move
p its new position
_new if true, the particle is allocated, else has to exists already
Definition at line 1247 of file core/particle_data.cpp.
References cell_structure, errexit(), fold_position(), i, ParticleLocal::i, ParticleProperties::identity, init_particle(), Particle::l, Particle::m, ParticleList::n, ParticlePosition::p, Particle::p, ParticlePosition::p_old, ParticleList::part, PART_TRACE, CellStructure::position_to_cell, Particle::r, realloc_particlelist(), this_node, update_local_particles(), and ParticleMomentum::v.
Referenced by mpi_place_new_particle(), mpi_place_new_particle_slave(), mpi_place_particle(), and mpi_place_particle_slave().
void local_remove_all_particles ()
Used by mpi_remove_particle, should not be used elsewhere.
Locally remove all particles.
Definition at line 1301 of file core/particle_data.cpp.
References CellPList::cell, i, local_cells, CellPList::n, ParticleList::n, n_part, ParticleList::part, and realloc_intlist().
Referenced by mpi_remove_particle_slave().
void local_remove_particle (int part)
Used by mpi_remove_particle, should not be used elsewhere.
Remove a particle on this node.
Parameters
part the identity of the particle to remove
Definition at line 1209 of file core/particle_data.cpp.
References CellPList::cell, errexit(), free_particle(), ParticleProperties::identity, local_cells, CellPList::n, ParticleList::n, Particle::p, ParticleList::part, and this_node.
Referenced by mpi_remove_particle_slave().
void local_rescale_particles (int dir, double scale)
Used by mpi_rescale_particles, should not be used elsewhere.
Locally rescale all particles on current node.
Parameters
dir direction to scale (0/1/2 = x/y/z, 3 = x+y+z isotropically)
scale factor by which to rescale (>1: stretch, <1: contract)
Definition at line 1319 of file core/particle_data.cpp.
References CellPList::cell, local_cells, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleList::part, and Particle::r.
Referenced by mpi_rescale_particles(), and mpi_rescale_particles_slave().
Particle* move_indexed_particle (ParticleList * destList, ParticleList * sourceList, int ind)
Remove a particle from one particle List and append it to another.
Refill the sourceList with last particle and update its entry in local_particles. Reallocates particles if necessary. This procedure cares for local_particles.
Parameters
destList List where the particle is appended.
sourceList List where the particle will be removed.
ind Index of the particle in the sourceList.
Returns
Pointer to new location of the particle.
Definition at line 521 of file core/particle_data.cpp.
References i, ParticleProperties::identity, ParticleList::n, Particle::p, ParticleList::part, realloc_particlelist(), and update_local_particles().
Referenced by dd_exchange_and_sort_particles(), layered_append_particles(), and layered_exchange_and_sort_particles().
Particle* move_unindexed_particle (ParticleList * destList, ParticleList * sourceList, int ind)
Remove a particle from one particle List and append it to another.
Refill the sourceList with last particle and update its entry in local_particles. reallocates particles if necessary. This procedure does not care for local_particles. NOT IN USE AT THE MOMENT.
Parameters
destList List where the particle is appended.
sourceList List where the particle will be removed.
ind Index of the particle in the sourceList.
Returns
Pointer to new location of the particle.
Definition at line 505 of file core/particle_data.cpp.
References i, ParticleList::n, ParticleList::part, and realloc_particlelist().
int number_of_particles_with_type (int type, int * number)
Definition at line 2038 of file core/particle_data.cpp.
References ES_OK, i, TypeOfIndex::index, init_type_array(), TypeOfIndex::max_entry, TypeList::max_entry, NOT_INDEXED, and IndexOfType::type.
Referenced by part_parse_gc().
void particle_invalidate_part_node ()
Invalidate particle_node.
This has to be done at the beginning of the integration.
Definition at line 409 of file core/particle_data.cpp.
References free, max_particle_node, and particle_node.
Referenced by cells_re_init(), and cells_resort_particles().
int place_particle (int part, double p[3])
Call only on the master node.
Move a particle to a new position. If it does not exist, it is created.
Parameters
part the identity of the particle to move
p its new position
Returns
ES_PART_OK if particle existed, ES_PART_CREATED if created and ES_PART_ERROR if id is illegal
Definition at line 566 of file core/particle_data.cpp.
References build_particle_node(), cell_structure, ES_PART_CREATED, ES_PART_ERROR, ES_PART_OK, i, max_seen_particle, mpi_place_new_particle(), mpi_place_particle(), particle_node, CellStructure::position_to_node, and realloc_particle_node().
Referenced by add_particles(), analyze_activate(), counterionsC(), diamondC(), handle_collisions(), icosaederC(), polymerC(), saltC(), tclcommand_part_parse_pos(), and tclcommand_readmd().
void pointer_to_dip (Particle * p, double *& res)
Definition at line 2121 of file core/particle_data.cpp.
References ParticlePosition::dip, and Particle::r.
void pointer_to_dipm (Particle * p, double *& res)
Definition at line 2126 of file core/particle_data.cpp.
References ParticleProperties::dipm, and Particle::p.
void pointer_to_exclusions (Particle * p, int *& res1, int *& res2)
Definition at line 2171 of file core/particle_data.cpp.
References IntList::e, Particle::el, and IntList::n.
void pointer_to_ext_force (Particle * p, int *& res1, double *& res2)
Definition at line 2133 of file core/particle_data.cpp.
References ParticleProperties::ext_flag, ParticleProperties::ext_force, and Particle::p.
void pointer_to_ext_torque (Particle * p, int *& res1, double *& res2)
Definition at line 2139 of file core/particle_data.cpp.
References ParticleProperties::ext_flag, ParticleProperties::ext_torque, and Particle::p.
void pointer_to_fix (Particle * p, int *& res)
Definition at line 2145 of file core/particle_data.cpp.
References ParticleProperties::ext_flag, and Particle::p.
void pointer_to_gamma (Particle * p, double *& res)
Definition at line 2152 of file core/particle_data.cpp.
References ParticleProperties::gamma, and Particle::p.
void pointer_to_mass (Particle * p, double *& res)
Definition at line 2113 of file core/particle_data.cpp.
References ParticleProperties::mass, and Particle::p.
void pointer_to_omega_body (Particle * p, double *& res)
Definition at line 2068 of file core/particle_data.cpp.
References Particle::m, and ParticleMomentum::omega.
void pointer_to_q (Particle * p, double *& res)
Definition at line 2090 of file core/particle_data.cpp.
References Particle::p, and ParticleProperties::q.
void pointer_to_quat (Particle * p, double *& res)
Definition at line 2078 of file core/particle_data.cpp.
References ParticlePosition::quat, and Particle::r.
void pointer_to_quatu (Particle * p, double *& res)
Definition at line 2083 of file core/particle_data.cpp.
References ParticlePosition::quatu, and Particle::r.
void pointer_to_rotation (Particle * p, int *& res)
Definition at line 2164 of file core/particle_data.cpp.
References Particle::p, and ParticleProperties::rotation.
void pointer_to_rotational_inertia (Particle * p, double *& res)
Definition at line 2186 of file core/particle_data.cpp.
References Particle::p, and ParticleProperties::rinertia.
void pointer_to_swimming (Particle * p, ParticleParametersSwimming *& swim)
Definition at line 2179 of file core/particle_data.cpp.
References Particle::swim.
void pointer_to_temperature (Particle * p, double *& res)
Definition at line 2157 of file core/particle_data.cpp.
References Particle::p, and ParticleProperties::T.
void pointer_to_torque_lab (Particle * p, double *& res)
Definition at line 2073 of file core/particle_data.cpp.
References Particle::f, and ParticleForce::torque.
void pointer_to_virtual (Particle * p, int *& res)
Definition at line 2097 of file core/particle_data.cpp.
References ParticleProperties::isVirtual, and Particle::p.
void pointer_to_vs_relative (Particle * p, int *& res1, double *& res2)
Definition at line 2104 of file core/particle_data.cpp.
References Particle::p, ParticleProperties::vs_relative_distance, and ParticleProperties::vs_relative_to_particle_id.
void realloc_local_particles (int part)
resize local_particles.
Parameters
part the highest existing particle
Definition at line 387 of file core/particle_data.cpp.
References max_local_particles, PART_INCREMENT, and realloc.
Referenced by added_particle().
static void realloc_particle_node (int part) static
resize particle_node.
This procedure is only used on the master node in Tcl mode.
Parameters
part the highest existing particle
Definition at line 400 of file core/particle_data.cpp.
References max_particle_node, PART_INCREMENT, particle_node, and realloc.
Referenced by build_particle_node(), place_particle(), and remove_all_particles().
int realloc_particlelist (ParticleList * plist, int size)
Allocate storage for local particles and ghosts.
This version does not care for the bond information to be freed if necessary.
Parameters
plist the list on which to operate
size the size to provide at least. It is rounded up to multiples of PART_INCREMENT.
Returns
true iff particle adresses have changed
Definition at line 432 of file core/particle_data.cpp.
References ParticleList::max, ParticleList::n, ParticleList::part, PART_INCREMENT, PART_TRACE, realloc, and this_node.
Referenced by append_indexed_particle(), append_unindexed_particle(), cells_re_init(), dd_exchange_and_sort_particles(), layered_exchange_and_sort_particles(), local_place_particle(), move_indexed_particle(), move_unindexed_particle(), nsq_balance_particles(), prepare_ghost_cell(), realloc_cells(), recv_particles(), and send_particles().
int reallocate_global_type_list (int size)
make more type_arrays available
Definition at line 1891 of file core/particle_data.cpp.
References ES_ERROR, ES_OK, number_of_type_lists, realloc, and type_array.
Referenced by init_type_array().
int reallocate_type_array (int type)
resize the array for the list of ids for a certain type
Definition at line 1823 of file core/particle_data.cpp.
References TypeList::cur_size, ES_ERROR, ES_OK, TypeList::id_list, realloc, and IndexOfType::type.
Referenced by add_particle_to_list(), and update_particle_array().
void recv_particles (ParticleList * particles, int node)
Synchronous receive of a particle buffer from another node.
The other node MUST call send_particles when this is called. The particles are APPENDED to the list, so it has to be a valid one
Definition at line 1554 of file core/particle_data.cpp.
References alloc_intlist(), Particle::bl, comm_cart, IntList::e, Particle::el, errexit(), ParticleProperties::identity, init_intlist(), MPI_BYTE, MPI_INT, MPI_Recv(), MPI_STATUS_IGNORE, IntList::n, ParticleList::n, Particle::p, ParticleList::part, PART_TRACE, realloc_intlist(), realloc_particlelist(), REQ_SNDRCV_PART, this_node, and update_local_particles().
Referenced by dd_exchange_and_sort_particles(), layered_exchange_and_sort_particles(), and nsq_balance_particles().
void remove_all_bonds_to (int part)
for all local particles, remove bonds incorporating the specified particle.
Parameters
part identity of the particle to free from bonds
Definition at line 1408 of file core/particle_data.cpp.
References Particle::bl, bonded_ia_params, CellPList::cell, IntList::e, errexit(), i, local_cells, IntList::n, CellPList::n, ParticleList::n, Bonded_ia_parameters::num, ParticleList::part, realloc_intlist(), and this_node.
Referenced by mpi_remove_particle_slave().
void remove_all_exclusions ()
remove all exclusions.
Definition at line 1650 of file core/particle_data.cpp.
References mpi_send_exclusion().
Referenced by tclcommand_part().
void remove_all_particles ()
remove all particles.
Definition at line 1169 of file core/particle_data.cpp.
References mpi_remove_particle(), and realloc_particle_node().
Referenced by tclcommand_part().
int remove_id_type_array (int part_id, int type)
Definition at line 1832 of file core/particle_data.cpp.
References ES_OK, i, TypeList::id_list, TypeOfIndex::index, TypeOfIndex::max_entry, TypeList::max_entry, and IndexOfType::type.
Referenced by remove_particle(), and set_particle_type().
int remove_particle (int part)
remove particle with a given identity.
Also removes all bonds to the particle.
Parameters
part identity of the particle to remove
Returns
ES_OK on success or ES_ERROR if particle does not exist
Definition at line 1175 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, FIELD_MAXPART, free, get_particle_data(), malloc, mpi_bcast_parameter(), mpi_remove_particle(), Particle::p, particle_node, remove_id_type_array(), and ParticleProperties::type.
Referenced by delete_particle_of_type(), and tclcommand_part_parse_delete().
void send_particles (ParticleList * particles, int node)
Synchronous send of a particle buffer to another node.
The other node MUST call recv_particles when this is called. The particles data is freed.
Definition at line 1510 of file core/particle_data.cpp.
References Particle::bl, comm_cart, IntList::e, Particle::el, free_particle(), ParticleProperties::identity, init_intlist(), MPI_BYTE, MPI_INT, MPI_Send(), IntList::n, ParticleList::n, Particle::p, ParticleList::part, PART_TRACE, realloc_intlist(), realloc_particlelist(), REQ_SNDRCV_PART, and this_node.
Referenced by dd_exchange_and_sort_particles(), layered_exchange_and_sort_particles(), and nsq_balance_particles().
int set_particle_dip (int part, double dip[3])
Call only on the master node: set particle dipole orientation.
Parameters
part the particle.
dip its new dipole orientation.
Returns
ES_OK if particle existed
Definition at line 743 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_dip(), and particle_node.
Referenced by tclcommand_part_parse_dip(), and tclcommand_readmd().
int set_particle_dipm (int part, double dipm)
Call only on the master node: set particle dipole moment (absolut value).
Parameters
part the particle.
dipm its new dipole moment.
Returns
ES_OK if particle existed
Definition at line 727 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_dipm(), and particle_node.
Referenced by tclcommand_part_parse_dipm().
int set_particle_ext_force (int part, int flag, double force[3])
Call only on the master node: set particle external force.
Parameters
part the particle.
flag new value for ext_flag.
force new value for ext_force.
Returns
ES_OK if particle existed
Definition at line 1108 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_send_ext_force(), PARTICLE_EXT_FORCE, and particle_node.
Referenced by tclcommand_part_parse_ext_force().
int set_particle_ext_torque (int part, int flag, double torque[3])
Call only on the master node: set particle external torque.
Parameters
part the particle.
flag new value for ext_flag.
torque new value for ext_torque.
Returns
ES_OK if particle existed
Definition at line 1090 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_send_ext_torque(), PARTICLE_EXT_TORQUE, and particle_node.
Referenced by tclcommand_part_parse_ext_torque().
int set_particle_f (int part, double F[3])
Call only on the master node: set particle force.
Parameters
part the particle.
F its new force.
Returns
ES_OK if particle existed
Definition at line 635 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_f(), and particle_node.
Referenced by tclcommand_part_parse_f(), and tclcommand_readmd().
int set_particle_fix (int part, int flag)
Call only on the master node: set coordinate axes for which the particles motion is fixed.
Parameters
part the particle.
flag new value for flagged coordinate axes to be fixed
Returns
ES_OK if particle existed
Definition at line 1125 of file core/particle_data.cpp.
References build_particle_node(), COORDS_FIX_MASK, ES_ERROR, ES_OK, mpi_send_ext_force(), and particle_node.
Referenced by tclcommand_part_parse_fix(), and tclcommand_part_parse_unfix().
int set_particle_gamma (int part, double gamma)
Call only on the master node: set particle frictional coefficient.
Parameters
part the particle.
gamma its new frictional coefficient.
Returns
ES_OK if particle existed
Definition at line 1068 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_set_particle_gamma(), and particle_node.
Referenced by part_parse_gamma().
int set_particle_mass (int part, double mass)
Call only on the master node: set particle mass.
Parameters
part the particle.
mass its new mass.
Returns
ES_OK if particle existed
Definition at line 672 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_mass(), and particle_node.
Referenced by tclcommand_part_parse_mass(), and tclcommand_readmd().
int set_particle_mol_id (int part, int mid)
Call only on the master node: set particle's molecule id.
Parameters
part the particle.
mid its new mol id.
Returns
ES_OK if particle existed
Definition at line 913 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_send_mol_id(), and particle_node.
Referenced by tclcommand_part_parse_mol_id().
int set_particle_mu_E (int part, double mu_E[3])
Call only on the master node: set particle electrophoretic mobility.
Parameters
part the particle.
mu_E its new mobility.
Returns
ES_OK if particle existed
Definition at line 855 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_send_mu_E(), and particle_node.
Referenced by tclcommand_part_parse_mu_E().
int set_particle_omega_body (int part, double omega[3])
Call only on the master node: set particle angular velocity in body frame.
Parameters
part the particle.
omega its new angular velocity.
Returns
ES_OK if particle existed
Definition at line 978 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_send_omega(), and particle_node.
Referenced by tclcommand_part_parse_omega_body().
int set_particle_omega_lab (int part, double omega[3])
Call only on the master node: set particle angular velocity from lab frame.
Parameters
part the particle.
omega its new angular velocity.
Returns
ES_OK if particle existed
Definition at line 947 of file core/particle_data.cpp.
References build_particle_node(), define_rotation_matrix(), ES_ERROR, ES_OK, get_particle_data(), mpi_send_omega(), and particle_node.
Referenced by tclcommand_part_parse_omega_lab().
int set_particle_q (int part, double q)
Call only on the master node: set particle charge.
Parameters
part the particle.
q its new charge.
Returns
ES_OK if particle existed
Definition at line 838 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_send_q(), and particle_node.
Referenced by add_particles(), counterionsC(), diamondC(), icosaederC(), polymerC(), saltC(), tclcommand_part_parse_q(), and tclcommand_readmd().
int set_particle_quat (int part, double quat[4])
Call only on the master node: set particle orientation using quaternions.
Parameters
part the particle.
quat its new value for quaternions.
Returns
ES_OK if particle existed
Definition at line 931 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_send_quat(), and particle_node.
Referenced by tclcommand_part_parse_quat(), and vs_relate_to().
int set_particle_rotation (int part, int rot)
Call only on the master node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
If set to zero, the content of the torque and omega variables are meaningless
Parameters
part the particle.
rot the degrees of freedom flag.
Returns
ES_OK if particle existed
Definition at line 709 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_rotation(), and particle_node.
Referenced by tclcommand_part_parse_rotation().
int set_particle_rotational_inertia (int part, double rinertia[3])
Call only on the master node: set particle rotational inertia.
Parameters
part the particle.
rinertia its new inertia.
Returns
ES_OK if particle existed
Definition at line 690 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_rotational_inertia(), and particle_node.
Referenced by tclcommand_part_parse_rotational_inertia().
int set_particle_smaller_timestep (int part, int small_timestep)
Call only on the master node: set particle smaller time step flag.
Parameters
part the particle.
small_timestep its new smaller time step.
Returns
TCL_OK if particle existed
Definition at line 803 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_smaller_timestep_flag(), and particle_node.
Referenced by tclcommand_part_parse_smaller_timestep().
int set_particle_solvation (int part, double * solvation)
Call only on the master node: set particle solvation free energy.
Parameters
part the particle.
solvation its new solvation free energy.
Returns
ES_OK if particle existed
Definition at line 652 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_solvation(), and particle_node.
Referenced by tclcommand_part_parse_solvation(), and tclcommand_readmd().
int set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the master node: set particle velocity.
Parameters
part the particle.
swim struct containing swimming parameters
Returns
ES_OK if particle existed
Definition at line 618 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_swimming(), and particle_node.
Referenced by tclcommand_part_parse_swimming().
int set_particle_temperature (int part, double T)
Call only on the master node: set particle temperature.
Parameters
part the particle.
T its new temperature.
Returns
ES_OK if particle existed
Definition at line 1050 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_set_particle_temperature(), and particle_node.
Referenced by part_parse_temp().
int set_particle_torque_body (int part, double torque[3])
Call only on the master node: set particle torque in body frame.
Parameters
part the particle.
torque its new torque.
Returns
ES_OK if particle existed
Definition at line 1028 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, mpi_send_torque(), and particle_node.
Referenced by tclcommand_part_parse_torque_body().
int set_particle_torque_lab (int part, double torque[3])
Call only on the master node: set particle torque from lab frame.
Parameters
part the particle.
torque its new torque.
Returns
ES_OK if particle existed
Definition at line 997 of file core/particle_data.cpp.
References build_particle_node(), define_rotation_matrix(), ES_ERROR, ES_OK, get_particle_data(), mpi_send_torque(), and particle_node.
Referenced by tclcommand_part_parse_torque_lab().
int set_particle_type (int part, int type)
Call only on the master node: set particle type.
Parameters
part the particle.
type its new type.
Returns
ES_OK if particle existed
Definition at line 872 of file core/particle_data.cpp.
References add_particle_to_list(), build_particle_node(), ES_ERROR, ES_OK, free, get_particle_data(), make_particle_type_exist(), malloc, mpi_send_type(), Particle::p, particle_node, remove_id_type_array(), ParticleProperties::type, and Type_array_init.
Referenced by add_particles(), counterionsC(), diamondC(), icosaederC(), polymerC(), saltC(), tclcommand_part_parse_type(), and tclcommand_readmd().
int set_particle_v (int part, double v[3])
Call only on the master node: set particle velocity.
Parameters
part the particle.
v its new velocity.
Returns
ES_OK if particle existed
Definition at line 601 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_v(), and particle_node.
Referenced by maxwell_velocitiesC(), tclcommand_part_parse_v(), tclcommand_readmd(), and velocitiesC().
int set_particle_virtual (int part, int isVirtual)
Call only on the master node: set particle dipole moment (absolut value).
Parameters
part the particle.
isVirtual its new dipole moment.
Returns
ES_OK if particle existed
Definition at line 764 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_virtual(), and particle_node.
int set_particle_vs_relative (int part, int vs_relative_to, double vs_distance)
Definition at line 782 of file core/particle_data.cpp.
References build_particle_node(), ES_ERROR, ES_OK, max_seen_particle, mpi_send_vs_relative(), and particle_node.
Referenced by part_parse_vs_relative(), and vs_relate_to().
int sortPartCfg ()
sorts the partCfg array.
This is indicated by setting partCfgSorted to 1. Note that for this to work the particles have to be stored consecutively starting with 0. This function is lazy.
Returns
1 iff sorting was possible, i. e. the particles were stored consecutively.
Definition at line 352 of file core/particle_data.cpp.
References free, i, malloc, max_seen_particle, n_part, partCfgSorted, updatePartCfg(), and WITHOUT_BONDS.
Referenced by analyze_fold_molecules(), bilayer_density_profile_sphere(), calc_fluctuations(), convert_types_to_ids(), get_lipid_orients(), modes2d(), observable_calc_blocked_com_force(), observable_calc_blocked_com_position(), observable_calc_blocked_com_velocity(), observable_calc_com_force(), observable_calc_com_position(), observable_calc_com_velocity(), observable_calc_currents(), observable_calc_density_profile(), observable_calc_dipole_moment(), observable_calc_flux_density_profile(), observable_calc_force_density_profile(), observable_calc_interacts_with(), observable_calc_particle_angular_momentum(), observable_calc_particle_body_angular_momentum(), observable_calc_particle_body_velocities(), observable_calc_particle_currents(), observable_calc_particle_forces(), observable_calc_particle_positions(), observable_calc_particle_velocities(), observable_calc_radial_density_profile(), observable_calc_radial_flux_density_profile(), observable_calc_rdf(), observable_calc_stress_tensor_acf_obs(), observable_calc_structure_factor(), observable_calc_structure_factor_fast(), observable_persistence_length(), observable_polymer_k_distribution(), observable_radial_density_distribution(), observable_spatial_polymer_properties(), observable_stress_tensor(), orient_order(), parse_id_list(), tclcommand_analyze_parse_activate(), tclcommand_analyze_parse_and_print_dipmom_mol(), tclcommand_analyze_parse_and_print_dipole(), tclcommand_analyze_parse_and_print_energy_kinetic_mol(), tclcommand_analyze_parse_and_print_pressure_mol(), tclcommand_analyze_parse_append(), tclcommand_analyze_parse_density_profile_av(), tclcommand_analyze_parse_diffusion_profile(), tclcommand_analyze_parse_get_folded_positions(), tclcommand_analyze_parse_necklace(), tclcommand_analyze_parse_push(), tclcommand_analyze_parse_rdf(), tclcommand_analyze_parse_remove(), tclcommand_analyze_parse_replace(), tclcommand_analyze_parse_vanhove(), tclcommand_analyze_print_MSD(), tclcommand_analyze_set_parse_chain_topology_check(), tclcommand_observable_rdf(), and updatePartCfg().
void try_add_exclusion (Particle * part, int part2)
Insert an exclusion if not already set.
Definition at line 1483 of file core/particle_data.cpp.
References IntList::e, Particle::el, i, IntList::n, and realloc_intlist().
Referenced by local_change_exclusion().
int try_delete_bond (Particle * part, int * bond)
Remove bond from particle if possible.
Definition at line 1375 of file core/particle_data.cpp.
References Particle::bl, bonded_ia_params, IntList::e, ES_ERROR, ES_OK, i, IntList::n, Bonded_ia_parameters::num, and realloc_intlist().
Referenced by local_change_bond().
void try_delete_exclusion (Particle * part, int part2)
Remove exclusion from particle if possible.
Definition at line 1494 of file core/particle_data.cpp.
References IntList::e, Particle::el, i, IntList::n, and realloc_intlist().
Referenced by local_change_exclusion().
void update_local_particles (ParticleList * pl)
Update the entries in local_particles for all particles in the list pl.
Parameters
pl the list to put in.
Definition at line 457 of file core/particle_data.cpp.
References i, ParticleList::n, and ParticleList::part.
Referenced by append_indexed_particle(), dd_topology_init(), layered_topology_init(), local_place_particle(), local_sort_particles(), move_indexed_particle(), nsq_balance_particles(), nsq_topology_init(), and recv_particles().
int update_particle_array (int type)
Definition at line 1869 of file core/particle_data.cpp.
References TypeList::cur_size, ES_ERROR, ES_OK, i, TypeList::id_list, ParticleProperties::identity, TypeList::max_entry, n_part, Particle::p, reallocate_type_array(), IndexOfType::type, updatePartCfg(), and WITHOUT_BONDS.
int updatePartCfg (int bonds_flag)
Get the complete unsorted informations on all particles into partCfg if something's changed.
This is a severe performance drawback and might even fail for lack of memory for large systems. If you need the particle info sorted, call sortPartCfg instead. This function is lazy. If you would like the bonding information in partCfg to be valid you should set the value of to WITH_BONDS.
Definition at line 317 of file core/particle_data.cpp.
References ParticleLocal::i, Particle::l, Particle::m, malloc, mpi_get_particles(), n_part, Particle::p, partCfgSorted, runtimeError, sortPartCfg(), unfold_position(), updatePartCfg(), ParticleMomentum::v, and WITH_BONDS.
Referenced by angularmomentum(), auto_exclusion(), bilayer_density_profile_sphere(), calc_cylindrical_average(), calc_fluctuations(), calc_gyration_tensor(), calc_radial_density_map(), centermass(), centermass_vel(), distto(), get_lipid_orients(), init_type_array(), mindist(), modes2d(), momentofinertiamatrix(), nbhood(), orient_order(), sortPartCfg(), tclcommand_analyze_current(), tclcommand_analyze_parse_and_print_check_mol(), tclcommand_analyze_parse_and_print_dipmom_mol(), tclcommand_analyze_parse_and_print_dipole(), tclcommand_analyze_parse_and_print_energy_kinetic(), tclcommand_analyze_parse_and_print_energy_kinetic_mol(), tclcommand_analyze_parse_and_print_pressure_mol(), tclcommand_analyze_parse_cluster_size_dist(), tclcommand_analyze_parse_cwvac(), tclcommand_analyze_parse_distribution(), tclcommand_analyze_parse_get_folded_positions(), tclcommand_analyze_parse_holes(), tclcommand_analyze_parse_nbhood(), tclcommand_analyze_parse_rdfchain(), tclcommand_analyze_parse_structurefactor(), tclcommand_analyze_parse_vel_distr(), tclcommand_analyze_wallstuff(), tclcommand_imd_parse_pos(), tclcommand_part_print_bond_partners(), update_particle_array(), and updatePartCfg().
Variable Documentation
int GC_init
Definition at line 64 of file core/particle_data.cpp.
Referenced by init_gc(), and observable_radial_density_distribution().
IndexOfType Index
Definition at line 61 of file core/particle_data.cpp.
Referenced by EwaldgpuForce::compute_k_AND_influence_factor(), EwaldgpuForce::compute_num_k(), observable_radial_density_distribution(), and part_parse_gc().
Particle** local_particles = NULL
id->particle mapping on all nodes.
This is used to find partners of bonded interactions.
Definition at line 72 of file core/particle_data.cpp.
Referenced by add_area_global_force(), add_bonded_energy(), add_bonded_force(), add_bonded_virials(), add_ljangle_pair_force(), add_three_body_bonded_stress(), add_volume_force(), calc_area_global(), calc_mol_pos(), calc_mol_vel(), calc_volume(), CalcVolumeForce(), CalcVolumes(), check_particle_consistency(), check_particles(), compute_pos_corr_vec(), compute_vel_corr_vec(), dd_exchange_and_sort_particles(), detect_collision(), force_and_velocity_display(), get_mol_com_particle(), handle_collisions(), invalidate_ghosts(), ljangle_pair_energy(), local_stress_tensor_calc(), mpi_recv_part(), mpi_recv_part_slave(), mpi_send_configtemp_flag(), mpi_send_configtemp_flag_slave(), mpi_send_dip(), mpi_send_dip_slave(), mpi_send_dipm(), mpi_send_dipm_slave(), mpi_send_ext_force(), mpi_send_ext_force_slave(), mpi_send_ext_torque(), mpi_send_ext_torque_slave(), mpi_send_f(), mpi_send_f_slave(), mpi_send_mass(), mpi_send_mass_slave(), mpi_send_mol_id(), mpi_send_mol_id_slave(), mpi_send_mu_E(), mpi_send_mu_E_slave(), mpi_send_omega(), mpi_send_omega_slave(), mpi_send_q(), mpi_send_q_slave(), mpi_send_quat(), mpi_send_quat_slave(), mpi_send_rotation(), mpi_send_rotation_slave(), mpi_send_rotational_inertia(), mpi_send_rotational_inertia_slave(), mpi_send_smaller_timestep_flag(), mpi_send_smaller_timestep_flag_slave(), mpi_send_solvation(), mpi_send_solvation_slave(), mpi_send_swimming(), mpi_send_swimming_slave(), mpi_send_torque(), mpi_send_torque_slave(), mpi_send_type(), mpi_send_type_slave(), mpi_send_v(), mpi_send_v_slave(), mpi_send_virtual(), mpi_send_virtual_slave(), mpi_send_vs_relative(), mpi_send_vs_relative_slave(), mpi_set_particle_gamma(), mpi_set_particle_gamma_slave(), mpi_set_particle_temperature(), mpi_set_particle_temperature_slave(), nemd_change_momentum(), nemd_get_velocity(), print_bond_len(), put_mol_force_on_parts(), put_recv_buffer(), sync_topo_part_info(), and vs_relative_get_real_particle().
int max_local_particles = 0
Definition at line 71 of file core/particle_data.cpp.
Referenced by realloc_local_particles().
int max_particle_node = 0
Capacity of the particle_node / local_particles.
Definition at line 69 of file core/particle_data.cpp.
Referenced by particle_invalidate_part_node(), and realloc_particle_node().
int max_seen_particle = -1
Highest particle number seen so far.
If you leave out some particle numbers, this number might be higher than the true number of particles. On the other hand, if you start your particle numbers at 0, the total number of particles is larger by 1.
Definition at line 67 of file core/particle_data.cpp.
Referenced by auto_exclusion(), build_particle_node(), check_particle_consistency(), check_particles(), get_particle_data(), handle_collisions(), mpi_who_has(), place_particle(), set_particle_dip(), set_particle_dipm(), set_particle_f(), set_particle_mass(), set_particle_rotation(), set_particle_rotational_inertia(), set_particle_smaller_timestep(), set_particle_solvation(), set_particle_swimming(), set_particle_v(), set_particle_virtual(), set_particle_vs_relative(), sortPartCfg(), tclcommand_imd_parse_pos(), tclcommand_metadynamics_parse_distance(), tclcommand_metadynamics_parse_relative_z(), tclcommand_part_parse_bond(), tclcommand_part_parse_print(), tclcommand_part_print_all(), tclcommand_part_print_bond_partners(), tclcommand_readmd(), and tclcommand_writemd().
int n_part = 0
total number of particles on all nodes.
Definition at line 68 of file core/particle_data.cpp.
Referenced by EwaldgpuForce::adaptive_tune(), add_ljangle_pair_force(), add_mdlc_force_corrections(), added_particle(), analyze_activate(), analyze_append(), analyze_cwvac(), analyze_push(), analyze_replace(), angularmomentum(), assign_charges(), assign_forces(), auto_exclusion(), bilayer_density_profile(), bilayer_density_profile_sphere(), build_verlet_lists(), build_verlet_lists_and_calc_verlet_ia(), build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_cylindrical_average(), calc_diffusion_profile(), calc_fluctuations(), calc_gyration_tensor(), calc_part_distribution(), calc_radial_density_map(), calc_rdf(), calc_rdf_av(), calc_rdf_intermol_av(), calc_structurefactor(), calc_vanhove(), calc_zref(), centermass(), centermass_conf(), centermass_vel(), check_particle_consistency(), check_particles(), collectBonds(), EwaldgpuForce::compute_q_sqare(), convert_types_to_ids(), crosslinkC(), density_profile_av(), distto(), fold_all(), gpu_change_number_of_part_to_comm(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_get_particles_slave(), IBM_cuda_mpi_send_velocities(), IBM_cuda_mpi_send_velocities_slave(), init_g123(), init_type_array(), lb_realloc_particles_gpu(), ljangle_pair_energy(), local_remove_all_particles(), magnetic_dipolar_direct_sum_calculations(), mark_neighbours(), mdlc_tune(), mindist(), mindist3(), mindist4(), momentofinertiamatrix(), mpi_get_particles(), mpi_get_particles_slave(), mpi_remove_particle_slave(), mpi_who_has(), mpi_who_has_slave(), nbhood(), nsq_balance_particles(), observable_calc_blocked_com_force(), observable_calc_blocked_com_position(), observable_calc_blocked_com_velocity(), observable_calc_com_force(), observable_calc_com_position(), observable_calc_com_velocity(), observable_calc_currents(), observable_calc_density_profile(), observable_calc_dipole_moment(), observable_calc_flux_density_profile(), observable_calc_force_density_profile(), observable_calc_interacts_with(), observable_calc_particle_angular_momentum(), observable_calc_particle_body_angular_momentum(), observable_calc_particle_body_velocities(), observable_calc_particle_currents(), observable_calc_particle_forces(), observable_calc_particle_positions(), observable_calc_particle_velocities(), observable_calc_radial_density_profile(), observable_calc_radial_flux_density_profile(), observable_calc_structure_factor(), observable_calc_structure_factor_fast(), parse_id_list(), pdb_add_particles_from_file(), sortPartCfg(), tclcommand_analyze_current(), tclcommand_analyze_parse_activate(), tclcommand_analyze_parse_and_print_check_mol(), tclcommand_analyze_parse_and_print_dipole(), tclcommand_analyze_parse_and_print_energy(), tclcommand_analyze_parse_and_print_energy_kinetic(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_parse_append(), tclcommand_analyze_parse_cluster_size_dist(), tclcommand_analyze_parse_diffusion_profile(), tclcommand_analyze_parse_distribution(), tclcommand_analyze_parse_distto(), tclcommand_analyze_parse_g123(), tclcommand_analyze_parse_get_folded_positions(), tclcommand_analyze_parse_lipid_orient_order(), tclcommand_analyze_parse_mindist(), tclcommand_analyze_parse_modes2d(), tclcommand_analyze_parse_nbhood(), tclcommand_analyze_parse_necklace(), tclcommand_analyze_parse_push(), tclcommand_analyze_parse_replace(), tclcommand_analyze_print_MSD(), tclcommand_analyze_print_vel_distr(), tclcommand_analyze_set_parse_topo_part_sync(), tclcommand_counterions(), tclcommand_crosslink(), tclcommand_imd_parse_pos(), tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha(), tclcommand_maxwell_velocities(), tclcommand_part_print_bond_partners(), tclcommand_readpdb(), tclcommand_salt(), tclcommand_velocities(), test_mesh_elements(), tscale_momentum_update(), update_mol_pos_cfg(), update_particle_array(), updatePartCfg(), and wall_sort_particles().
int number_of_type_lists
Definition at line 63 of file core/particle_data.cpp.
Referenced by init_gc(), init_type_array(), and reallocate_global_type_list().
Particle* partCfg = NULL
Particles' current configuration.
Before using that call updatePartCfg or sortPartCfg to allocate the data if necessary (which is decided by updatePartCfg).
Definition at line 73 of file core/particle_data.cpp.
Referenced by analyze_append(), analyze_cwvac(), analyze_formfactor(), analyze_push(), analyze_rdfchain(), analyze_replace(), angularmomentum(), bilayer_density_profile(), bilayer_density_profile_sphere(), calc_bond_dist(), calc_bond_l(), calc_cylindrical_average(), calc_diffusion_profile(), calc_dipole_of_molecule(), calc_fluctuations(), calc_force_between_mol(), calc_g123(), calc_g2_av(), calc_g3_av(), calc_gyration_tensor(), calc_internal_dist(), calc_mol_center_of_mass(), calc_mol_gyr_radius2(), calc_mol_hydro_radius(), calc_mol_pos_cfg(), calc_part_distribution(), calc_radial_density_map(), calc_rdf(), calc_rdf_av(), calc_rdf_intermol_av(), calc_re(), calc_rg(), calc_rg_av(), calc_rh(), calc_scaling(), calc_scaling2(), calc_structurefactor(), calc_vanhove(), calc_wallbondyz(), calc_wallrdfyz(), calc_zref(), centermass(), centermass_conf(), centermass_vel(), convert_types_to_ids(), density_profile_av(), distto(), fold_all(), get_lipid_orients(), get_mol_com_particle_from_molid_cfg(), init_g123(), mark_neighbours(), mindist(), momentofinertiamatrix(), nbhood(), observable_calc_blocked_com_force(), observable_calc_blocked_com_position(), observable_calc_blocked_com_velocity(), observable_calc_com_force(), observable_calc_com_position(), observable_calc_com_velocity(), observable_calc_currents(), observable_calc_density_profile(), observable_calc_dipole_moment(), observable_calc_flux_density_profile(), observable_calc_force_density_profile(), observable_calc_interacts_with(), observable_calc_particle_angular_momentum(), observable_calc_particle_body_angular_momentum(), observable_calc_particle_body_velocities(), observable_calc_particle_currents(), observable_calc_particle_forces(), observable_calc_particle_positions(), observable_calc_particle_velocities(), observable_calc_radial_density_profile(), observable_calc_radial_flux_density_profile(), observable_calc_structure_factor(), observable_calc_structure_factor_fast(), observable_persistence_length(), observable_polymer_k_distribution(), observable_radial_density_distribution(), observable_spatial_polymer_properties(), orient_order(), tclcommand_analyze_current(), tclcommand_analyze_parse_and_print_check_mol(), tclcommand_analyze_parse_and_print_dipole(), tclcommand_analyze_parse_and_print_energy_kinetic(), tclcommand_analyze_parse_cluster_size_dist(), tclcommand_analyze_parse_get_folded_positions(), tclcommand_analyze_parse_necklace(), tclcommand_analyze_print_MSD(), tclcommand_analyze_print_vel_distr(), tclcommand_imd_parse_pos(), tclcommand_part_print_bond_partners(), test_mesh_elements(), update_mol_pos_cfg(), and wall_sort_particles().
IntList partCfg_bl = { NULL, 0, 0 }
bondlist for partCfg, if bonds are needed
Definition at line 77 of file core/particle_data.cpp.
int partCfgSorted = 0
if non zero, partCfg is sorted by particle order, and the particles are stored consecutively starting with 0.
Definition at line 74 of file core/particle_data.cpp.
Referenced by sortPartCfg(), and updatePartCfg().
int* particle_node = NULL
Used only on master node: particle->node mapping.
Definition at line 70 of file core/particle_data.cpp.
Referenced by change_exclusion(), change_particle_bond(), check_particles(), get_particle_data(), mpi_who_has(), particle_invalidate_part_node(), place_particle(), realloc_particle_node(), remove_particle(), set_particle_dip(), set_particle_dipm(), set_particle_ext_force(), set_particle_ext_torque(), set_particle_f(), set_particle_fix(), set_particle_gamma(), set_particle_mass(), set_particle_mol_id(), set_particle_mu_E(), set_particle_omega_body(), set_particle_omega_lab(), set_particle_q(), set_particle_quat(), set_particle_rotation(), set_particle_rotational_inertia(), set_particle_smaller_timestep(), set_particle_solvation(), set_particle_swimming(), set_particle_temperature(), set_particle_torque_body(), set_particle_torque_lab(), set_particle_type(), set_particle_v(), set_particle_virtual(), set_particle_vs_relative(), tclcommand_part_parse_bond(), tclcommand_part_parse_cmd(), tclcommand_part_parse_exclusion(), tclcommand_part_print_all(), tclcommand_readmd(), and tclcommand_writemd().
TypeOfIndex Type
Definition at line 60 of file core/particle_data.cpp.
Referenced by part_parse_gc().
TypeList* type_array
Definition at line 62 of file core/particle_data.cpp.
Referenced by observable_radial_density_distribution(), part_parse_gc(), and reallocate_global_type_list().
int Type_array_init
Definition at line 65 of file core/particle_data.cpp.
Referenced by init_gc(), init_type_array(), observable_radial_density_distribution(), part_parse_gc(), and set_particle_type().