ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: cos2.hpp File Reference
cos2.hpp File Reference
Routines to calculate a flat potential with cosine tail energy and/or force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "mol_cut.hpp"
#include "forcecap.hpp"
#include <cmath>
Functions
int cos2_set_params (int part_type_a, int part_type_b, double eps, double offset, double w)
void add_cos2_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double force[3])
Calculate cos2 force between particle p1 and p2.
double cos2_pair_energy (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist)
calculate cos2 energy between particle p1 and p2.
Detailed Description
Routines to calculate a flat potential with cosine tail energy and/or force for a particle pair.
Cosine tail is different from that in ljcos.hpp Used for attractive tail/tail interactions in lipid bilayer calculations. Same potential as ljcos2 without Lennard-Jones part. forces.cpp
Definition in file cos2.hpp.
Function Documentation
void add_cos2_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double force[3]) inline
Calculate cos2 force between particle p1 and p2.
Definition at line 45 of file cos2.hpp.
References IA_parameters::COS2_eps, IA_parameters::COS2_offset, IA_parameters::COS2_w, CUTOFF_CHECK, and M_PI.
double cos2_pair_energy (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist) inline
calculate cos2 energy between particle p1 and p2.
Definition at line 60 of file cos2.hpp.
References IA_parameters::COS2_eps, IA_parameters::COS2_offset, IA_parameters::COS2_w, CUTOFF_CHECK, and M_PI.
int cos2_set_params (int part_type_a, int part_type_b, double eps, double offset, double w)
Definition at line 37 of file cos2.cpp.
References IA_parameters::COS2_cut, IA_parameters::COS2_eps, IA_parameters::COS2_offset, IA_parameters::COS2_w, ES_ERROR, ES_OK, get_ia_param_safe(), and mpi_bcast_ia_params().
Referenced by tclcommand_inter_parse_cos2().