ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: cuda_common_cuda.cu File Reference
cuda_common_cuda.cu File Reference
#include "cuda_utils.hpp"
#include "cuda_interface.hpp"
#include "config.hpp"
#include "random.hpp"
#include "particle_data.hpp"
#include "interaction_data.hpp"
#include "cuda_init.hpp"
Functions
void _cuda_safe_mem (cudaError_t err, const char *file, unsigned int line)
erroroutput for memory allocation and memory copy
void _cuda_check_errors (const dim3 &block, const dim3 &grid, const char *function, const char *file, unsigned int line)
__device__ unsigned int getThreadIndex ()
__global__ void init_particle_force (float *particle_forces_device, CUDA_particle_seed *particle_seeds_device)
kernel for the initalisation of the particle force array
__global__ void init_fluid_composition (CUDA_fluid_composition *fluid_composition_device)
kernel for the initalisation of the fluid composition
__global__ void reset_particle_force (float *particle_forces_device)
kernel for the initalisation of the partikel force array
void gpu_change_number_of_part_to_comm ()
change number of particles to be communicated to the GPU Note that in addition to calling this function the parameters must be broadcast with either: 1) cuda_bcast_global_part_params(); (when just being executed on the master node) or 2) MPI_Bcast(gpu_get_global_particle_vars_pointer_host(), sizeof(CUDA_global_part_vars), MPI_BYTE, 0, comm_cart); (when executed on all nodes)
void gpu_init_particle_comm ()
setup and call particle reallocation from the host Note that in addition to calling this function the parameters must be broadcast with either: 1) cuda_bcast_global_part_params(); (when just being executed on the master node) or 2) MPI_Bcast(gpu_get_global_particle_vars_pointer_host(), sizeof(CUDA_global_part_vars), MPI_BYTE, 0, comm_cart); (when executed on all nodes)
CUDA_particle_data * gpu_get_particle_pointer ()
CUDA_global_part_vars * gpu_get_global_particle_vars_pointer_host ()
CUDA_global_part_vars * gpu_get_global_particle_vars_pointer ()
float * gpu_get_particle_force_pointer ()
CUDA_energy * gpu_get_energy_pointer ()
CUDA_particle_seed * gpu_get_particle_seed_pointer ()
CUDA_fluid_composition * gpu_get_fluid_composition_pointer ()
void copy_part_data_to_gpu ()
void copy_forces_from_GPU ()
setup and call kernel to copy particle forces to host
void copy_v_cs_from_GPU ()
void clear_energy_on_GPU ()
void copy_energy_from_GPU ()
void cuda_copy_to_device (void *host_data, void *device_data, size_t n)
Generic copy functions from an to device.
void cuda_copy_to_host (void *host_device, void *device_host, size_t n)
Variables
static int max_ran = 1000000
static CUDA_global_part_vars global_part_vars_host = {0,0,0}
static __device__ __constant__ CUDA_global_part_vars global_part_vars_device
static float * particle_forces_device = NULL
struct for particle force
static CUDA_particle_data * particle_data_device = NULL
struct for particle position and veloctiy
static CUDA_particle_seed * particle_seeds_device = NULL
struct for storing particle rn seed
static CUDA_fluid_composition * fluid_composition_device = NULL
struct for fluid composition
static CUDA_energy * energy_device = NULL
struct for energies
CUDA_particle_data * particle_data_host = NULL
float * particle_forces_host = NULL
CUDA_energy energy_host
CUDA_fluid_composition * fluid_composition_host = NULL
CUDA_v_cs * host_v_cs = NULL
cudaStream_t stream [1]
cuda streams for parallel computing on cpu and gpu
cudaError_t err
Function Documentation
void _cuda_check_errors (const dim3 & block, const dim3 & grid, const char * function, const char * file, unsigned int line)
Definition at line 79 of file cuda_common_cuda.cu.
References err, errexit(), and this_node.
Referenced by assign_charges(), and assign_forces().
void _cuda_safe_mem (cudaError_t err, const char * file, unsigned int line)
erroroutput for memory allocation and memory copy
Parameters
err cuda error code
*file .cu file were the error took place
line line of the file were the error took place
Definition at line 60 of file cuda_common_cuda.cu.
References errexit().
void clear_energy_on_GPU ()
Definition at line 330 of file cuda_common_cuda.cu.
References cuda_safe_mem, energy_device, and global_part_vars_host.
Referenced by energy_calc().
void copy_energy_from_GPU ()
Definition at line 338 of file cuda_common_cuda.cu.
References cuda_safe_mem, energy_device, energy_host, and global_part_vars_host.
Referenced by energy_calc().
void copy_forces_from_GPU ()
setup and call kernel to copy particle forces to host
Copy result from device memory to host memory
values for the particle kernel
reset part forces with zero
Definition at line 287 of file cuda_common_cuda.cu.
References cuda_safe_mem, fluid_composition_device, fluid_composition_host, global_part_vars_host, KERNELCALL, particle_forces_device, particle_forces_host, reset_particle_force(), and this_node.
Referenced by force_calc().
void copy_part_data_to_gpu ()
get espresso md particle values
Definition at line 274 of file cuda_common_cuda.cu.
References COMM_TRACE, global_part_vars_host, particle_data_device, particle_data_host, stream, and this_node.
Referenced by EspressoSystemInterface::gatherParticles().
void copy_v_cs_from_GPU ()
Definition at line 317 of file cuda_common_cuda.cu.
References cuda_safe_mem, global_part_vars_host, host_v_cs, particle_data_device, and this_node.
Referenced by convert_torques_propagate_omega().
void cuda_copy_to_device (void * host_data, void * device_data, size_t n)
Generic copy functions from an to device.
Definition at line 347 of file cuda_common_cuda.cu.
References cuda_safe_mem.
void cuda_copy_to_host (void * host_device, void * device_host, size_t n)
Definition at line 351 of file cuda_common_cuda.cu.
References cuda_safe_mem.
__device__ unsigned int getThreadIndex ()
Definition at line 90 of file cuda_common_cuda.cu.
Referenced by init_fluid_composition(), init_particle_force(), and reset_particle_force().
void gpu_change_number_of_part_to_comm ()
change number of particles to be communicated to the GPU Note that in addition to calling this function the parameters must be broadcast with either: 1) cuda_bcast_global_part_params(); (when just being executed on the master node) or 2) MPI_Bcast(gpu_get_global_particle_vars_pointer_host(), sizeof(CUDA_global_part_vars), MPI_BYTE, 0, comm_cart); (when executed on all nodes)
pinned memory mode - use special function to get OS-pinned memory
values for the particle kernel
Definition at line 155 of file cuda_common_cuda.cu.
References cuda_safe_mem, fluid_composition_device, fluid_composition_host, global_part_vars_device, global_part_vars_host, host_v_cs, i_random(), init_fluid_composition(), init_particle_force(), KERNELCALL, max_ran, n_part, particle_data_device, particle_data_host, particle_forces_device, particle_forces_host, particle_seeds_device, and this_node.
Referenced by gpu_init_particle_comm(), and on_integration_start().
CUDA_energy* gpu_get_energy_pointer ()
Definition at line 262 of file cuda_common_cuda.cu.
References energy_device.
CUDA_fluid_composition* gpu_get_fluid_composition_pointer ()
Definition at line 270 of file cuda_common_cuda.cu.
References fluid_composition_device.
Referenced by lb_calc_particle_lattice_ia_gpu().
CUDA_global_part_vars* gpu_get_global_particle_vars_pointer ()
Definition at line 256 of file cuda_common_cuda.cu.
References global_part_vars_device.
CUDA_global_part_vars* gpu_get_global_particle_vars_pointer_host ()
Definition at line 253 of file cuda_common_cuda.cu.
References global_part_vars_host.
Referenced by EspressoSystemInterface::gatherParticles(), IBM_ForcesIntoFluid_GPU(), mpi_bcast_cuda_global_part_vars_slave(), on_coulomb_change(), on_integration_start(), p3m_gpu_add_farfield_force(), p3m_gpu_init(), ParticleVelocitiesFromLB_GPU(), and EspressoSystemInterface::split_particle_struct().
float* gpu_get_particle_force_pointer ()
Definition at line 259 of file cuda_common_cuda.cu.
References particle_forces_device.
Referenced by lb_calc_particle_lattice_ia_gpu(), and p3m_gpu_add_farfield_force().
CUDA_particle_data* gpu_get_particle_pointer ()
Definition at line 250 of file cuda_common_cuda.cu.
References particle_data_device.
Referenced by lb_calc_particle_lattice_ia_gpu(), p3m_gpu_add_farfield_force(), and EspressoSystemInterface::split_particle_struct().
CUDA_particle_seed* gpu_get_particle_seed_pointer ()
Definition at line 266 of file cuda_common_cuda.cu.
References particle_seeds_device.
Referenced by lb_calc_particle_lattice_ia_gpu().
void gpu_init_particle_comm ()
setup and call particle reallocation from the host Note that in addition to calling this function the parameters must be broadcast with either: 1) cuda_bcast_global_part_params(); (when just being executed on the master node) or 2) MPI_Bcast(gpu_get_global_particle_vars_pointer_host(), sizeof(CUDA_global_part_vars), MPI_BYTE, 0, comm_cart); (when executed on all nodes)
Definition at line 230 of file cuda_common_cuda.cu.
References cuda_check_gpu(), cuda_get_n_gpus(), errexit(), ES_OK, global_part_vars_host, gpu_change_number_of_part_to_comm(), and this_node.
Referenced by lb_init_gpu().
__global__ void init_fluid_composition (CUDA_fluid_composition * fluid_composition_device)
kernel for the initalisation of the fluid composition
Parameters
*fluid_composition_device Pointer to local fluid composition (Output)
Definition at line 120 of file cuda_common_cuda.cu.
References getThreadIndex(), global_part_vars_device, and LB_COMPONENTS.
Referenced by gpu_change_number_of_part_to_comm().
__global__ void init_particle_force (float * particle_forces_device, CUDA_particle_seed * particle_seeds_device)
kernel for the initalisation of the particle force array
Parameters
*particle_forces_device Pointer to local particle force (Output)
*particle_seeds_device Pointer to the particle rn seed storearray (Output)
Definition at line 103 of file cuda_common_cuda.cu.
References getThreadIndex(), and global_part_vars_device.
Referenced by gpu_change_number_of_part_to_comm().
__global__ void reset_particle_force (float * particle_forces_device)
kernel for the initalisation of the partikel force array
Parameters
*particle_forces_device pointer to local particle force (Input)
Definition at line 139 of file cuda_common_cuda.cu.
References getThreadIndex(), and global_part_vars_device.
Referenced by copy_forces_from_GPU().
Variable Documentation
CUDA_energy* energy_device = NULL static
struct for energies
Definition at line 45 of file cuda_common_cuda.cu.
Referenced by clear_energy_on_GPU(), copy_energy_from_GPU(), and gpu_get_energy_pointer().
CUDA_energy energy_host
Definition at line 49 of file cuda_common_cuda.cu.
Referenced by copy_energy_from_GPU().
cudaError_t err
Definition at line 58 of file cuda_common_cuda.cu.
Referenced by _cuda_check_error(), _cuda_check_errors(), _cudaCheckError(), acf_cmd(), besselTuneKernel(), correlation_print_average1(), cuda_check_error(), MMM2D_init(), MMM2D_set_params(), MMM2D_tune_far(), MMM2D_tune_near(), prepare_polygamma_series(), tclcommand_analyze(), tclcommand_analyze_parse_fluid_cpu(), tclcommand_analyze_parse_fluid_gpu(), tclcommand_blockfile(), tclcommand_cellsystem(), tclcommand_electrokinetics(), tclcommand_inter_coulomb_parse_mmm2d(), tclcommand_lbfluid(), tclcommand_lbnode_extforce_gpu(), tclcommand_metadynamics(), tclcommand_part_parse_cmd(), tclcommand_part_parse_swimming(), and tclcommand_thermostat().
CUDA_fluid_composition* fluid_composition_device = NULL static
struct for fluid composition
Definition at line 43 of file cuda_common_cuda.cu.
Referenced by copy_forces_from_GPU(), gpu_change_number_of_part_to_comm(), and gpu_get_fluid_composition_pointer().
CUDA_fluid_composition* fluid_composition_host = NULL
Definition at line 50 of file cuda_common_cuda.cu.
Referenced by copy_forces_from_GPU(), and gpu_change_number_of_part_to_comm().
__device__ __constant__ CUDA_global_part_vars global_part_vars_device static
Definition at line 34 of file cuda_common_cuda.cu.
Referenced by gpu_change_number_of_part_to_comm(), gpu_get_global_particle_vars_pointer(), init_fluid_composition(), init_particle_force(), and reset_particle_force().
CUDA_global_part_vars global_part_vars_host = {0,0,0} static
Definition at line 33 of file cuda_common_cuda.cu.
Referenced by clear_energy_on_GPU(), copy_energy_from_GPU(), copy_forces_from_GPU(), copy_part_data_to_gpu(), copy_v_cs_from_GPU(), gpu_change_number_of_part_to_comm(), gpu_get_global_particle_vars_pointer_host(), and gpu_init_particle_comm().
CUDA_v_cs* host_v_cs = NULL
Definition at line 52 of file cuda_common_cuda.cu.
Referenced by copy_v_cs_from_GPU(), and gpu_change_number_of_part_to_comm().
int max_ran = 1000000 static
Definition at line 32 of file cuda_common_cuda.cu.
Referenced by gpu_change_number_of_part_to_comm().
CUDA_particle_data* particle_data_device = NULL static
struct for particle position and veloctiy
Definition at line 39 of file cuda_common_cuda.cu.
Referenced by copy_part_data_to_gpu(), copy_v_cs_from_GPU(), gpu_change_number_of_part_to_comm(), and gpu_get_particle_pointer().
CUDA_particle_data* particle_data_host = NULL
Definition at line 47 of file cuda_common_cuda.cu.
Referenced by copy_part_data_to_gpu(), and gpu_change_number_of_part_to_comm().
float* particle_forces_device = NULL static
struct for particle force
Definition at line 37 of file cuda_common_cuda.cu.
Referenced by copy_forces_from_GPU(), gpu_change_number_of_part_to_comm(), and gpu_get_particle_force_pointer().
float* particle_forces_host = NULL
Definition at line 48 of file cuda_common_cuda.cu.
Referenced by copy_forces_from_GPU(), and gpu_change_number_of_part_to_comm().
CUDA_particle_seed* particle_seeds_device = NULL static
struct for storing particle rn seed
Definition at line 41 of file cuda_common_cuda.cu.
Referenced by gpu_change_number_of_part_to_comm(), and gpu_get_particle_seed_pointer().
cudaStream_t stream[1]
cuda streams for parallel computing on cpu and gpu
Definition at line 56 of file cuda_common_cuda.cu.
Referenced by copy_part_data_to_gpu().