ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: cuda_init_tcl.cpp File Reference
cuda_init_tcl.cpp File Reference
#include "utils.hpp"
#include "parser.hpp"
#include "cuda_init.hpp"
#include "communication.hpp"
Functions
int tclcommand_cuda (ClientData data, Tcl_Interp *interp, int argc, char **argv)
returns 1 if and only if the GPU with the given id is usable for CUDA computations.
Function Documentation
int tclcommand_cuda (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
returns 1 if and only if the GPU with the given id is usable for CUDA computations.
Set the CUDA device to use or retrieve information available devices.
Only devices with compute capability of 1.1 or higher are ok, since atomic operations are required for CUDA-LB.
Definition at line 62 of file cuda_init_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, cuda_check_gpu(), cuda_error, cuda_get_device(), cuda_set_device(), cuda_test_device_access(), ES_ERROR, and ES_OK.
Referenced by tcl_register_commands().