ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: debye_hueckel.hpp File Reference
debye_hueckel.hpp File Reference
Routines to calculate the Debye_Hueckel Energy or/and Debye_Hueckel force for a particle pair.
#include "interaction_data.hpp"
Data Structures
struct Debye_hueckel_params
Structure to hold Debye-Hueckel Parameters.
Functions
Functions
int dh_set_params (double kappa, double r_cut)
int dh_set_params_cdh (double kappa, double r_cut, double eps_int, double eps_ext, double r0, double r1, double alpha)
void add_dh_coulomb_pair_force (Particle *p1, Particle *p2, double d[3], double dist, double force[3])
Computes the Debye_Hueckel pair force and adds this force to the particle forces (see tclcommand_inter).
double dh_coulomb_pair_energy (Particle *p1, Particle *p2, double dist)
Variables
Debye_hueckel_params dh_params
Structure containing the Debye-Hueckel parameters.
Detailed Description
Routines to calculate the Debye_Hueckel Energy or/and Debye_Hueckel force for a particle pair.
Definition in file debye_hueckel.hpp.
Function Documentation
void add_dh_coulomb_pair_force (Particle * p1, Particle * p2, double d[3], double dist, double force[3]) inline
Computes the Debye_Hueckel pair force and adds this force to the particle forces (see tclcommand_inter).
Parameters
p1 Pointer to first particle.
p2 Pointer to second/middle particle.
d Vector pointing from p1 to p2.
dist Distance between p1 and p2.
force returns the force on particle 1.
Definition at line 64 of file debye_hueckel.hpp.
References Debye_hueckel_params::alpha, coulomb, Debye_hueckel_params::eps_ext, Debye_hueckel_params::eps_int, Debye_hueckel_params::kappa, Particle::p, Coulomb_parameters::prefactor, ParticleProperties::q, Debye_hueckel_params::r0, Debye_hueckel_params::r1, and Debye_hueckel_params::r_cut.
Referenced by add_non_bonded_pair_force(), add_non_bonded_pair_virials(), and get_nonbonded_interaction().
double dh_coulomb_pair_energy (Particle * p1, Particle * p2, double dist) inline
Definition at line 115 of file debye_hueckel.hpp.
References Debye_hueckel_params::alpha, coulomb, Debye_hueckel_params::eps_ext, Debye_hueckel_params::eps_int, Debye_hueckel_params::kappa, Particle::p, Coulomb_parameters::prefactor, ParticleProperties::q, Debye_hueckel_params::r0, Debye_hueckel_params::r1, and Debye_hueckel_params::r_cut.
Referenced by add_non_bonded_pair_energy().
int dh_set_params (double kappa, double r_cut)
Definition at line 31 of file core/debye_hueckel.cpp.
References dh_params, Debye_hueckel_params::kappa, mpi_bcast_coulomb_params(), and Debye_hueckel_params::r_cut.
Referenced by dh_set_params_cdh(), and tclcommand_inter_coulomb_parse_dh().
int dh_set_params_cdh (double kappa, double r_cut, double eps_int, double eps_ext, double r0, double r1, double alpha)
Definition at line 48 of file core/debye_hueckel.cpp.
References Debye_hueckel_params::alpha, dh_params, dh_set_params(), Debye_hueckel_params::eps_ext, Debye_hueckel_params::eps_int, Debye_hueckel_params::r0, and Debye_hueckel_params::r1.
Referenced by tclcommand_inter_coulomb_parse_dh().
Variable Documentation
Debye_hueckel_params dh_params
Structure containing the Debye-Hueckel parameters.
Definition at line 86 of file interaction_data.cpp.
Referenced by dh_set_params(), dh_set_params_cdh(), mpi_bcast_coulomb_params_slave(), and tclprint_to_result_dh().