ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: domain_decomposition.hpp File Reference
domain_decomposition.hpp File Reference
This file contains everything related to the cell system: domain decomposition.
#include "utils.hpp"
#include "cells.hpp"
#include "integrate.hpp"
#include "verlet.hpp"
#include "thermostat.hpp"
Data Structures
struct IA_Neighbor
Structure containing information about non bonded interactions with particles in a neighbor cell.
struct IA_Neighbor_List
struct DomainDecomposition
Structure containing the information about the cell grid used for domain decomposition.
Functions
Exported Functions
void dd_on_geometry_change (int flags)
adjust the domain decomposition to a change in the geometry.
void dd_topology_init (CellPList *cl)
Initialize the topology.
void dd_topology_release ()
Called when the current cell structure is invalidated because for example the box length has changed.
void dd_exchange_and_sort_particles (int global_flag)
Just resort the particles.
Cell * dd_position_to_cell (double pos[3])
implements CellStructure::position_to_cell.
int calc_processor_min_num_cells ()
calculate physical (processor) minimal number of cells
void calc_link_cell ()
Calculate nonbonded and bonded forces with link-cell method (without Verlet lists)
void calculate_link_cell_energies ()
Nonbonded and bonded energy calculation using link-cell method.
void calculate_link_cell_virials (int v_comp)
Nonbonded and bonded virials calculation using link-cell method.
int dd_fill_comm_cell_lists (Cell **part_lists, int lc[3], int hc[3])
Fill a communication cell pointer list.
Cell * dd_save_position_to_cell (double pos[3])
Returns pointer to the cell which corresponds to the position if the position is in the nodes spatial domain otherwise a NULL pointer.
void dd_assign_prefetches (GhostCommunicator *comm)
Of every two communication rounds, set the first receivers to prefetch and poststore.
Variables
Exported Variables
DomainDecomposition dd
Information about the domain decomposition.
double max_skin
Maximal skin size.
int max_num_cells
Maximal number of cells per node.
int min_num_cells
Minimal number of cells per node.
Detailed Description
This file contains everything related to the cell system: domain decomposition.
The simulation box is split into spatial domains for each node according to a cartesian node grid (node_grid).
The domain of a node is split into a 3D cell grid with dimension DomainDecomposition::cell_grid. Together with one ghost cell layer on each side the overall dimension of the ghost cell grid is DomainDecomposition::ghost_cell_grid. The domain decomposition enables one the use of the linked cell algorithm which is in turn used for setting up the verlet list for the system. You can see a 2D graphical representation of the linked cell grid below.
Linked cells structure
2D representation of a linked cell grid: cell_grid = {4,4}, ghost_cell_grid = {6,6}
Each cell has 3^D neighbor cells (For cell 14 they are marked). Since we deal with pair forces, it is sufficient to calculate only half of the interactions (Newtons law: actio = reactio). We have chosen the upper half e.g. all neighbor cells with a higher linear index (For cell 14 they are marked in light blue). Caution: This implementation needs double sided ghost communication! For single sided ghost communication one would need some ghost-ghost cell interaction as well, which we do not need!
For more information on cells, see cells.hpp
Definition in file domain_decomposition.hpp.
Function Documentation
void calc_link_cell ()
Calculate nonbonded and bonded forces with link-cell method (without Verlet lists)
Definition at line 1135 of file domain_decomposition.cpp.
References add_bonded_force(), add_constraints_forces(), add_external_potential_forces(), add_non_bonded_pair_force(), CellPList::cell, DomainDecomposition::cell_inter, distance2vec(), do_nonbonded(), i, local_cells, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, neighbor, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, ParticleList::part, IA_Neighbor::pList, Particle::r, and rebuild_verletlist.
Referenced by force_calc().
int calc_processor_min_num_cells ()
calculate physical (processor) minimal number of cells
Definition at line 1123 of file domain_decomposition.cpp.
References i, and node_grid.
Referenced by on_program_start(), and tclcallback_min_num_cells().
void calculate_link_cell_energies ()
Nonbonded and bonded energy calculation using link-cell method.
Definition at line 1188 of file domain_decomposition.cpp.
References add_bonded_energy(), add_constraints_energy(), add_external_potential_energy(), add_kinetic_energy(), add_non_bonded_pair_energy(), CellPList::cell, DomainDecomposition::cell_inter, CELL_TRACE, distance2vec(), do_nonbonded(), i, local_cells, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, neighbor, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, ParticleList::part, IA_Neighbor::pList, Particle::r, rebuild_verletlist, and this_node.
Referenced by energy_calc().
void calculate_link_cell_virials (int v_comp)
Nonbonded and bonded virials calculation using link-cell method.
Definition at line 1244 of file domain_decomposition.cpp.
References add_bonded_virials(), add_kinetic_virials(), add_non_bonded_pair_virials(), add_three_body_bonded_stress(), CellPList::cell, DomainDecomposition::cell_inter, CELL_TRACE, distance2vec(), do_nonbonded(), i, local_cells, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, neighbor, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, ParticleList::part, IA_Neighbor::pList, Particle::r, rebuild_verletlist, and this_node.
Referenced by pressure_calc().
void dd_assign_prefetches (GhostCommunicator * comm)
Of every two communication rounds, set the first receivers to prefetch and poststore.
Definition at line 441 of file domain_decomposition.cpp.
References GhostCommunicator::comm, GHOST_PREFETCH, GHOST_PSTSTORE, GHOST_RECV, GHOST_SEND, GhostCommunicator::num, and GhostCommunication::type.
Referenced by dd_on_geometry_change(), and dd_topology_init().
void dd_exchange_and_sort_particles (int global_flag)
Just resort the particles.
Used during integration. The particles are stored in the cell structure.
Parameters
global_flag Use DD_GLOBAL_EXCHANGE for global exchange and DD_NEIGHBOR_EXCHANGE for neighbor exchange (recommended for use within Molecular dynamics, or any other integration scheme using only local particle moves)
Definition at line 918 of file domain_decomposition.cpp.
References boundary, CellPList::cell, CELL_GLOBAL_EXCHANGE, CELL_TRACE, check_particle_consistency(), comm_cart, dd_append_particles(), dd_save_position_to_cell(), fold_coordinate(), i, ParticleLocal::i, ParticleProperties::identity, init_particlelist(), Particle::l, local_cells, local_particles, Particle::m, move_indexed_particle(), MPI_Bcast(), MPI_INT, MPI_Reduce(), MPI_SUM, my_left, my_right, CellPList::n, ParticleList::n, n_nodes, node_grid, node_neighbor_lr, node_neighbors, node_pos, ParticlePosition::p, Particle::p, ParticleList::part, PERIODIC, Particle::r, realloc_particlelist(), recv_particles(), ROUND_ERROR_PREC, runtimeError, send_particles(), this_node, and ParticleMomentum::v.
Referenced by cells_resort_particles().
int dd_fill_comm_cell_lists (Cell ** part_lists, int lc[3], int hc[3])
Fill a communication cell pointer list.
Fill the cell pointers of all cells which are inside a rectangular subgrid of the 3D cell grid (DomainDecomposition::ghost_cell_grid) starting from the lower left corner lc up to the high top corner hc. The cell pointer list part_lists must already be large enough.
Parameters
part_lists List of cell pointers to store the result.
lc lower left corner of the subgrid.
hc high up corner of the subgrid.
Definition at line 273 of file domain_decomposition.cpp.
References CELL_TRACE, cells, get_linear_index(), DomainDecomposition::ghost_cell_grid, i, and this_node.
Referenced by dd_prepare_comm(), and le_dd_prepare_comm().
void dd_on_geometry_change (int flags)
adjust the domain decomposition to a change in the geometry.
Tries to speed up things if possible.
Parameters
flags a combination of CELL_FLAG_FAST and CELL_FLAG_GRIDCHANGED, see documentation of cells_on_geometry_change.
Definition at line 697 of file domain_decomposition.cpp.
References CELL_FLAG_FAST, CELL_FLAG_GRIDCHANGED, CELL_FLAG_LEES_EDWARDS, DomainDecomposition::cell_grid, DomainDecomposition::cell_size, cell_structure, CELL_STRUCTURE_CURRENT, CELL_STRUCTURE_DOMDEC, CELL_TRACE, cells_re_init(), CellStructure::collect_ghost_force_comm, dd_assign_prefetches(), dd_update_communicators_w_boxl(), dmin(), CellStructure::exchange_ghosts_comm, CellStructure::ghost_cells_comm, CellStructure::ghost_lbcoupling_comm, GHOSTTRANS_COUPLING, GHOSTTRANS_FORCE, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_POSSHFTD, GHOSTTRANS_PROPRTS, i, DomainDecomposition::inv_cell_size, LE_COMM_BACKWARDS, LE_COMM_FORWARDS, le_dd_dynamic_update_comm(), le_dd_update_communicators_w_boxl(), local_box_l, max_cut, max_range, max_skin, on_boxl_change(), runtimeError, this_node, CellStructure::update_ghost_pos_comm, and le_dd_comms_manager::update_on_le_offset_change().
Referenced by cells_on_geometry_change().
Cell* dd_position_to_cell (double pos[3])
implements CellStructure::position_to_cell.
Definition at line 614 of file domain_decomposition.cpp.
References DomainDecomposition::cell_grid, cells, get_linear_index(), DomainDecomposition::ghost_cell_grid, i, DomainDecomposition::inv_cell_size, local_box_l, my_left, PERIODIC, ROUND_ERROR_PREC, and runtimeError.
Referenced by dd_topology_init().
Cell* dd_save_position_to_cell (double pos[3])
Returns pointer to the cell which corresponds to the position if the position is in the nodes spatial domain otherwise a NULL pointer.
Definition at line 581 of file domain_decomposition.cpp.
References boundary, DomainDecomposition::cell_grid, cells, get_linear_index(), DomainDecomposition::ghost_cell_grid, i, DomainDecomposition::inv_cell_size, local_box_l, my_left, PERIODIC, and ROUND_ERROR_PREC.
Referenced by dd_exchange_and_sort_particles(), and dd_topology_init().
void dd_topology_init (CellPList * cl)
Initialize the topology.
The argument is a list of cell pointers, containing particles that have to be sorted into new cells. The particles might not belong to this node. This procedure is used when particle data or cell structure has changed and the cell structure has to be reinitialized. This also includes setting up the cell_structure array.
Parameters
cl List of cell pointers with particles to be stored in the new cell system.
broadcast the flag for using verlet list
Definition at line 794 of file domain_decomposition.cpp.
References append_unindexed_particle(), CellPList::cell, cell_structure, CELL_STRUCTURE_DOMDEC, CELL_TRACE, CellStructure::collect_ghost_force_comm, comm_cart, dd_assign_prefetches(), dd_create_cell_grid(), dd_init_cell_interactions(), dd_mark_cells(), dd_position_to_cell(), dd_prepare_comm(), dd_revert_comm_order(), dd_save_position_to_cell(), CellStructure::exchange_ghosts_comm, CellStructure::ghost_cells_comm, CellStructure::ghost_lbcoupling_comm, CellStructure::ghost_swimming_comm, GHOSTTRANS_COUPLING, GHOSTTRANS_FORCE, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_POSSHFTD, GHOSTTRANS_PROPRTS, GHOSTTRANS_SWIMMING, CellStructure::ibm_ghost_force_comm, le_dd_comms_manager::init(), le_dd_init_cell_interactions(), le_dd_prepare_comm(), local_cells, map_position_node_array(), MPI_Bcast(), MPI_INT, my_neighbor_count, CellPList::n, ParticleList::n, Particle::p, ParticleList::part, CellStructure::position_to_cell, CellStructure::position_to_node, this_node, CellStructure::type, CellStructure::update_ghost_pos_comm, update_local_particles(), and DomainDecomposition::use_vList.
Referenced by on_program_start(), and topology_init().
void dd_topology_release ()
Called when the current cell structure is invalidated because for example the box length has changed.
This procedure may NOT destroy the old inner and ghost cells, but it should free all other organizational data. Note that parameters like the box length or the node_grid may already have changed. Therefore organizational data has to be stored independently from variables that may be changed from outside.
Definition at line 888 of file domain_decomposition.cpp.
References DomainDecomposition::cell_inter, cell_structure, CELL_TRACE, CellStructure::collect_ghost_force_comm, CellStructure::exchange_ghosts_comm, free_comm(), free_pairList(), ghost_cells, CellStructure::ghost_cells_comm, CellStructure::ghost_lbcoupling_comm, CellStructure::ghost_swimming_comm, i, CellStructure::ibm_ghost_force_comm, local_cells, CellPList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, realloc, realloc_cellplist(), this_node, CellStructure::update_ghost_pos_comm, and IA_Neighbor::vList.
Referenced by topology_release().
Variable Documentation
DomainDecomposition dd
Information about the domain decomposition.
Definition at line 57 of file domain_decomposition.cpp.
Referenced by aggregation(), build_verlet_lists(), build_verlet_lists_and_calc_verlet_ia(), build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_link_cell_iccp3m(), calculate_verlet_energies(), calculate_verlet_ia(), calculate_verlet_ia_iccp3m(), calculate_verlet_virials(), cell_cell_transfer(), cells_update_ghosts(), energy_calc(), evaluateAsChebychevSeriesAt(), force_calc(), force_calc_iccp3m(), integrate_reaction(), lb_sanity_checks(), le_dd_dynamic_update_comm(), le_dd_init_cell_interactions(), le_dd_prepare_comm(), local_stress_tensor_calc(), maggs_sanity_checks(), pressure_calc(), printAllComms(), put_recv_buffer(), reactions_sanity_checks(), tclcommand_cellsystem(), le_dd_comms_manager::update_on_le_offset_change(), and le_dd_comms_manager::wrap_fill_comm_cell_lists().
int max_num_cells
Maximal number of cells per node.
In order to avoid memory problems due to the cell grid one has to specify the maximal number of cells::cells . The corresponding callback function is tclcallback_max_num_cells. If the number of cells n_cells, is larger than max_num_cells the cell grid is reduced. max_num_cells has to be larger than 27, e.g one inner cell. max_num_cells is initialized with the default value specified in config.hpp as CELLS_MAX_NUM_CELLS.
Definition at line 59 of file domain_decomposition.cpp.
double max_skin
Maximal skin size.
This is a global variable wwhich can be read out by the user via the TCL command setmd in order to optimize the cell grid
Definition at line 61 of file domain_decomposition.cpp.
int min_num_cells
Minimal number of cells per node.
This is mainly to avoid excessively large numbers of particles per cell, which will result in really large Verlet lists and eventually crash Espresso.
Definition at line 60 of file domain_decomposition.cpp.