ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: domain_decomposition_tcl.cpp File Reference
domain_decomposition_tcl.cpp File Reference
#include "utils.hpp"
#include "parser.hpp"
#include "domain_decomposition.hpp"
Macros
#define CELLS_MAX_NEIGHBORS 14
half the number of cell neighbors in 3 Dimensions.
Functions
int tclcallback_max_num_cells (Tcl_Interp *interp, void *_data)
Callback for setmd max_num_cells (maxnumcells >= 27).
int tclcallback_min_num_cells (Tcl_Interp *interp, void *_data)
Callback for setmd min_num_cells.
Variables
Variables
int max_num_cells
Maximal number of cells per node.
int min_num_cells
Minimal number of cells per node.
double max_skin
Maximal skin size.
Macro Definition Documentation
#define CELLS_MAX_NEIGHBORS 14
half the number of cell neighbors in 3 Dimensions.
Definition at line 32 of file domain_decomposition_tcl.cpp.
Function Documentation
int tclcallback_max_num_cells (Tcl_Interp * interp, void * _data)
Callback for setmd max_num_cells (maxnumcells >= 27).
see also max_num_cells
Definition at line 48 of file domain_decomposition_tcl.cpp.
References FIELD_MAXNUMCELLS, max_num_cells, min_num_cells, and mpi_bcast_parameter().
Referenced by tcl_register_global_variables().
int tclcallback_min_num_cells (Tcl_Interp * interp, void * _data)
Callback for setmd min_num_cells.
see also min_num_cells
Definition at line 60 of file domain_decomposition_tcl.cpp.
References calc_processor_min_num_cells(), FIELD_MINNUMCELLS, max_num_cells, min_num_cells, and mpi_bcast_parameter().
Referenced by tcl_register_global_variables().
Variable Documentation
int max_num_cells
Maximal number of cells per node.
In order to avoid memory problems due to the cell grid one has to specify the maximal number of cells::cells . The corresponding callback function is tclcallback_max_num_cells. If the number of cells n_cells, is larger than max_num_cells the cell grid is reduced. max_num_cells has to be larger than 27, e.g one inner cell. max_num_cells is initialized with the default value specified in config.hpp as CELLS_MAX_NUM_CELLS.
Definition at line 59 of file domain_decomposition.cpp.
Referenced by dd_create_cell_grid(), layered_topology_init(), tclcallback_max_num_cells(), and tclcallback_min_num_cells().
double max_skin
Maximal skin size.
This is a global variable wwhich can be read out by the user via the TCL command setmd in order to optimize the cell grid
Definition at line 61 of file domain_decomposition.cpp.
Referenced by dd_create_cell_grid(), and dd_on_geometry_change().
int min_num_cells
Minimal number of cells per node.
This is mainly to avoid excessively large numbers of particles per cell, which will result in really large Verlet lists and eventually crash Espresso.
Definition at line 60 of file domain_decomposition.cpp.
Referenced by dd_create_cell_grid(), on_program_start(), tclcallback_max_num_cells(), and tclcallback_min_num_cells().