ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: dpd.hpp File Reference
dpd.hpp File Reference
Routines to use dpd as thermostat or pair force T.
#include "utils.hpp"
#include "thermostat.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "virtual_sites.hpp"
Functions
void dpd_switch_off (void)
void thermo_init_dpd ()
void dpd_heat_up ()
void dpd_cool_down ()
void add_dpd_thermo_pair_force (Particle *p1, Particle *p2, double d[3], double dist, double dist2)
Calculate Random Force and Friction Force acting between particle p1 and p2 and add them to their forces.
void inter_dpd_heat_up ()
void inter_dpd_cool_down ()
void inter_dpd_switch_off ()
int inter_dpd_set_params (int part_type_a, int part_type_b, double gamma, double r_c, int wf, double tgamma, double tr_c, int twf)
void inter_dpd_init ()
void inter_dpd_update_params (double pref2_scale)
void add_inter_dpd_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double dist2)
Variables
int dpd_ignore_fixed_particles
Flag to decide wether to allow for fixed particles with DPD.
double dpd_gamma
DPD Friction coefficient gamma.
double dpd_r_cut
DPD thermostat cutoff.
int dpd_wf
DPD thermostat weight function.
double dpd_tgamma
DPD transversal Friction coefficient gamma.
double dpd_tr_cut
trans DPD thermostat cutoff
int dpd_twf
trans DPD thermostat weight function
double dpd_r_cut_inv
double dpd_pref1
double dpd_pref2
double dpd_tr_cut_inv
double dpd_pref3
double dpd_pref4
Detailed Description
Routines to use dpd as thermostat or pair force T.
Soddemann, B. Duenweg and K. Kremer, Phys. Rev. E 68, 046702 (2003) forces.cpp
Definition in file dpd.hpp.
Function Documentation
void add_dpd_thermo_pair_force (Particle * p1, Particle * p2, double d[3], double dist, double dist2)
Calculate Random Force and Friction Force acting between particle p1 and p2 and add them to their forces.
Definition at line 162 of file dpd.cpp.
References COORDS_FIX_MASK, d_random(), dpd_gamma, dpd_ignore_fixed_particles, dpd_pref1, dpd_pref2, dpd_pref3, dpd_pref4, dpd_r_cut, dpd_r_cut_inv, dpd_tgamma, dpd_tr_cut, dpd_tr_cut_inv, dpd_twf, dpd_wf, ParticleProperties::ext_flag, ParticleForce::f, Particle::f, i, ifParticleIsVirtual(), le_chatterjee_test_pair(), Particle::m, Particle::p, PMASS, SQR(), and ParticleMomentum::v.
Referenced by add_non_bonded_pair_force().
void add_inter_dpd_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double dist2)
Definition at line 375 of file dpd.cpp.
References COORDS_FIX_MASK, d_random(), IA_parameters::dpd_gamma, dpd_ignore_fixed_particles, IA_parameters::dpd_pref1, IA_parameters::dpd_pref2, IA_parameters::dpd_pref3, IA_parameters::dpd_pref4, dpd_r_cut, IA_parameters::dpd_r_cut, IA_parameters::dpd_tgamma, dpd_tr_cut, IA_parameters::dpd_tr_cut, IA_parameters::dpd_twf, dpd_wf, ParticleProperties::ext_flag, ParticleForce::f, Particle::f, i, le_chatterjee_test_pair(), Particle::m, Particle::p, PMASS, SQR(), and ParticleMomentum::v.
Referenced by add_non_bonded_pair_force().
void dpd_cool_down ()
Definition at line 148 of file dpd.cpp.
References dpd_pref2, dpd_pref2_buffer, dpd_pref4, and dpd_pref4_buffer.
Referenced by thermo_cool_down().
void dpd_heat_up ()
Definition at line 131 of file dpd.cpp.
References dpd_pref2, dpd_pref2_buffer, dpd_pref4, and dpd_pref4_buffer.
Referenced by thermo_heat_up().
void dpd_switch_off (void)
Definition at line 76 of file dpd.cpp.
References dpd_gamma, dpd_r_cut, dpd_tgamma, dpd_tr_cut, dpd_twf, dpd_wf, FIELD_DPD_GAMMA, FIELD_DPD_RCUT, FIELD_DPD_TGAMMA, FIELD_DPD_TRCUT, FIELD_DPD_TWF, FIELD_DPD_WF, and mpi_bcast_parameter().
Referenced by tclcommand_thermostat_parse_off().
void inter_dpd_cool_down ()
Definition at line 294 of file dpd.cpp.
References inter_dpd_update_params().
Referenced by thermo_cool_down().
void inter_dpd_heat_up ()
Definition at line 287 of file dpd.cpp.
References inter_dpd_update_params().
Referenced by thermo_heat_up().
void inter_dpd_init ()
Definition at line 327 of file dpd.cpp.
References IA_parameters::dpd_gamma, IA_parameters::dpd_pref1, IA_parameters::dpd_pref2, IA_parameters::dpd_pref3, IA_parameters::dpd_pref4, IA_parameters::dpd_r_cut, IA_parameters::dpd_tgamma, IA_parameters::dpd_tr_cut, get_ia_param(), n_particle_types, temperature, and time_step.
Referenced by tclcommand_inter_parse_inter_dpd(), and thermo_init().
int inter_dpd_set_params (int part_type_a, int part_type_b, double gamma, double r_c, int wf, double tgamma, double tr_c, int twf)
Definition at line 300 of file dpd.cpp.
References IA_parameters::dpd_gamma, IA_parameters::dpd_pref1, IA_parameters::dpd_pref2, IA_parameters::dpd_pref3, IA_parameters::dpd_pref4, IA_parameters::dpd_r_cut, IA_parameters::dpd_tgamma, IA_parameters::dpd_tr_cut, IA_parameters::dpd_twf, IA_parameters::dpd_wf, ES_ERROR, ES_OK, get_ia_param_safe(), mpi_bcast_ia_params(), temperature, and time_step.
Referenced by tclcommand_inter_parse_inter_dpd().
void inter_dpd_switch_off ()
Definition at line 345 of file dpd.cpp.
References IA_parameters::dpd_gamma, IA_parameters::dpd_pref1, IA_parameters::dpd_pref2, IA_parameters::dpd_pref3, IA_parameters::dpd_pref4, IA_parameters::dpd_r_cut, IA_parameters::dpd_tgamma, IA_parameters::dpd_tr_cut, IA_parameters::dpd_twf, IA_parameters::dpd_wf, get_ia_param(), and n_particle_types.
Referenced by tclcommand_thermostat_parse_off().
void inter_dpd_update_params (double pref2_scale)
Definition at line 359 of file dpd.cpp.
References IA_parameters::dpd_pref2, IA_parameters::dpd_pref4, IA_parameters::dpd_r_cut, IA_parameters::dpd_tr_cut, get_ia_param(), and n_particle_types.
Referenced by inter_dpd_cool_down(), and inter_dpd_heat_up().
void thermo_init_dpd ()
Definition at line 101 of file dpd.cpp.
References dpd_gamma, dpd_pref1, dpd_pref2, dpd_pref3, dpd_pref4, dpd_r_cut, dpd_r_cut_inv, dpd_tgamma, dpd_tr_cut, dpd_tr_cut_inv, temperature, THERMO_TRACE, this_node, and time_step.
Referenced by thermo_init().
Variable Documentation
double dpd_gamma
DPD Friction coefficient gamma.
Definition at line 31 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), dpd_switch_off(), tclcommand_thermostat_parse_and_print_dpd(), tclcommand_thermostat_parse_dpd(), and thermo_init_dpd().
int dpd_ignore_fixed_particles
Flag to decide wether to allow for fixed particles with DPD.
Definition at line 27 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), add_inter_dpd_pair_force(), and tclcommand_thermostat_parse_inter_dpd().
double dpd_pref1
Definition at line 64 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), and thermo_init_dpd().
double dpd_pref2
Definition at line 65 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), dpd_cool_down(), dpd_heat_up(), and thermo_init_dpd().
double dpd_pref3
Definition at line 71 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), and thermo_init_dpd().
double dpd_pref4
Definition at line 72 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), dpd_cool_down(), dpd_heat_up(), and thermo_init_dpd().
double dpd_r_cut
DPD thermostat cutoff.
Definition at line 33 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), add_inter_dpd_pair_force(), dpd_switch_off(), recalc_global_maximal_nonbonded_cutoff(), tclcommand_thermostat_parse_and_print_dpd(), tclcommand_thermostat_parse_dpd(), and thermo_init_dpd().
double dpd_r_cut_inv
Definition at line 63 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), and thermo_init_dpd().
double dpd_tgamma
DPD transversal Friction coefficient gamma.
Definition at line 38 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), dpd_switch_off(), tclcommand_thermostat_parse_and_print_dpd(), tclcommand_thermostat_parse_dpd(), and thermo_init_dpd().
double dpd_tr_cut
trans DPD thermostat cutoff
Definition at line 40 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), add_inter_dpd_pair_force(), dpd_switch_off(), recalc_global_maximal_nonbonded_cutoff(), tclcommand_thermostat_parse_and_print_dpd(), tclcommand_thermostat_parse_dpd(), and thermo_init_dpd().
double dpd_tr_cut_inv
Definition at line 70 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), and thermo_init_dpd().
int dpd_twf
trans DPD thermostat weight function
Definition at line 42 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), dpd_switch_off(), tclcommand_thermostat_parse_and_print_dpd(), and tclcommand_thermostat_parse_dpd().
int dpd_wf
DPD thermostat weight function.
Definition at line 35 of file dpd.cpp.
Referenced by add_dpd_thermo_pair_force(), add_inter_dpd_pair_force(), dpd_switch_off(), tclcommand_thermostat_parse_and_print_dpd(), and tclcommand_thermostat_parse_dpd().