ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: electrokinetics.hpp File Reference
electrokinetics.hpp File Reference
#include "config.hpp"
#include "lb-boundaries.hpp"
Macros
#define EK_LINK_U00 0
#define EK_LINK_0U0 1
#define EK_LINK_00U 2
#define EK_LINK_UU0 3
#define EK_LINK_UD0 4
#define EK_LINK_U0U 5
#define EK_LINK_U0D 6
#define EK_LINK_0UU 7
#define EK_LINK_0UD 8
#define EK_LINK_UUU 9
#define EK_LINK_UUD 10
#define EK_LINK_UDU 11
#define EK_LINK_UDD 12
#define EK_LINK_D00 13
#define EK_LINK_0D0 14
#define EK_LINK_00D 15
#define EK_LINK_DD0 16
#define EK_LINK_DU0 17
#define EK_LINK_D0D 18
#define EK_LINK_D0U 19
#define EK_LINK_0DD 20
#define EK_LINK_0DU 21
#define EK_LINK_DDD 22
#define EK_LINK_DDU 23
#define EK_LINK_DUD 24
#define EK_LINK_DUU 25
Functions
void ek_integrate ()
void ek_print_parameters ()
void ek_print_lbpar ()
void lb_set_ek_pointer (EK_parameters *pointeradress)
unsigned int ek_calculate_boundary_mass ()
int ek_print_vtk_density (int species, char *filename)
int ek_print_vtk_flux (int species, char *filename)
int ek_print_vtk_potential (char *filename)
int ek_print_vtk_particle_potential (char *filename)
int ek_print_vtk_lbforce (char *filename)
int ek_print_vtk_reaction_tags (char *filename)
int ek_lb_print_vtk_density (char *filename)
int ek_lb_print_vtk_velocity (char *filename)
int ek_init ()
int ek_set_agrid (double agrid)
int ek_set_lb_density (double lb_density)
int ek_set_viscosity (double viscosity)
int ek_set_friction (double friction)
int ek_set_T (double T)
int ek_set_bjerrumlength (double bjerrumlength)
int ek_set_electrostatics_coupling (bool electrostatics_coupling)
void ek_calculate_electrostatic_coupling ()
int ek_set_bulk_viscosity (double bulk_viscosity)
int ek_set_gamma_odd (double gamma_odd)
int ek_set_gamma_even (double gamma_even)
int ek_set_lb_force (double *ext_force)
int ek_set_density (int species, double density)
int ek_set_D (int species, double D)
int ek_set_valency (int species, double valency)
int ek_set_ext_force (int species, double ext_force_x, double ext_force_y, double ext_force_z)
int ek_set_stencil (int stencil)
int ek_node_print_velocity (int x, int y, int z, double *velocity)
int ek_node_print_density (int species, int x, int y, int z, double *density)
int ek_node_print_flux (int species, int x, int y, int z, double *flux)
int ek_node_set_density (int species, int x, int y, int z, double density)
float ek_calculate_net_charge ()
int ek_neutralize_system (int species)
int ek_save_checkpoint (char *filename)
int ek_load_checkpoint (char *filename)
void ek_init_species_density_wallcharge (ekfloat *wallcharge_species_density, int wallcharge_species)
int ek_set_reaction (int reactant, int product0, int product1, float rho_reactant_reservoir, float rho_product0_reservoir, float rho_product1_reservoir, float reaction_ct_rate, float reaction_fraction_0, float reaction_fraction_1, float mass_reactant, float mass_product0, float mass_product1)
int ek_print_vtk_pressure (char *filename)
int ek_tag_reaction_nodes (LB_Boundary *lbboundary, char reaction_type)
Variables
EK_parameters ek_parameters
int ek_initialized
Macro Definition Documentation
#define EK_LINK_00D 15
Definition at line 130 of file electrokinetics.hpp.
#define EK_LINK_00U 2
Definition at line 115 of file electrokinetics.hpp.
#define EK_LINK_0D0 14
Definition at line 129 of file electrokinetics.hpp.
#define EK_LINK_0DD 20
Definition at line 135 of file electrokinetics.hpp.
#define EK_LINK_0DU 21
Definition at line 136 of file electrokinetics.hpp.
#define EK_LINK_0U0 1
Definition at line 114 of file electrokinetics.hpp.
#define EK_LINK_0UD 8
Definition at line 121 of file electrokinetics.hpp.
#define EK_LINK_0UU 7
Definition at line 120 of file electrokinetics.hpp.
#define EK_LINK_D00 13
Definition at line 128 of file electrokinetics.hpp.
#define EK_LINK_D0D 18
Definition at line 133 of file electrokinetics.hpp.
#define EK_LINK_D0U 19
Definition at line 134 of file electrokinetics.hpp.
#define EK_LINK_DD0 16
Definition at line 131 of file electrokinetics.hpp.
#define EK_LINK_DDD 22
Definition at line 138 of file electrokinetics.hpp.
#define EK_LINK_DDU 23
Definition at line 139 of file electrokinetics.hpp.
#define EK_LINK_DU0 17
Definition at line 132 of file electrokinetics.hpp.
#define EK_LINK_DUD 24
Definition at line 140 of file electrokinetics.hpp.
#define EK_LINK_DUU 25
Definition at line 141 of file electrokinetics.hpp.
#define EK_LINK_U00 0
Definition at line 113 of file electrokinetics.hpp.
#define EK_LINK_U0D 6
Definition at line 119 of file electrokinetics.hpp.
#define EK_LINK_U0U 5
Definition at line 118 of file electrokinetics.hpp.
#define EK_LINK_UD0 4
Definition at line 117 of file electrokinetics.hpp.
#define EK_LINK_UDD 12
Definition at line 126 of file electrokinetics.hpp.
#define EK_LINK_UDU 11
Definition at line 125 of file electrokinetics.hpp.
#define EK_LINK_UU0 3
Definition at line 116 of file electrokinetics.hpp.
#define EK_LINK_UUD 10
Definition at line 124 of file electrokinetics.hpp.
#define EK_LINK_UUU 9
Definition at line 123 of file electrokinetics.hpp.
Function Documentation
unsigned int ek_calculate_boundary_mass ()
void ek_calculate_electrostatic_coupling ()
Referenced by calc_long_range_forces().
float ek_calculate_net_charge ()
Referenced by tclcommand_electrokinetics().
int ek_init ()
Referenced by tclcommand_electrokinetics().
void ek_init_species_density_wallcharge (ekfloat * wallcharge_species_density, int wallcharge_species)
Referenced by lb_init_boundaries().
void ek_integrate ()
Referenced by integrate_sd(), and integrate_vv().
int ek_lb_print_vtk_density (char * filename)
Referenced by tclcommand_electrokinetics().
int ek_lb_print_vtk_velocity (char * filename)
Referenced by tclcommand_electrokinetics().
int ek_load_checkpoint (char * filename)
Referenced by tclcommand_electrokinetics().
int ek_neutralize_system (int species)
Referenced by tclcommand_electrokinetics().
int ek_node_print_density (int species, int x, int y, int z, double * density)
Referenced by tclcommand_electrokinetics().
int ek_node_print_flux (int species, int x, int y, int z, double * flux)
Referenced by tclcommand_electrokinetics().
int ek_node_print_velocity (int x, int y, int z, double * velocity)
Referenced by tclcommand_electrokinetics().
int ek_node_set_density (int species, int x, int y, int z, double density)
Referenced by tclcommand_electrokinetics().
void ek_print_lbpar ()
void ek_print_parameters ()
int ek_print_vtk_density (int species, char * filename)
Referenced by tclcommand_electrokinetics().
int ek_print_vtk_flux (int species, char * filename)
Referenced by tclcommand_electrokinetics().
int ek_print_vtk_lbforce (char * filename)
Referenced by tclcommand_electrokinetics().
int ek_print_vtk_particle_potential (char * filename)
Referenced by tclcommand_electrokinetics().
int ek_print_vtk_potential (char * filename)
Referenced by tclcommand_electrokinetics().
int ek_print_vtk_pressure (char * filename)
Referenced by tclcommand_electrokinetics().
int ek_print_vtk_reaction_tags (char * filename)
Referenced by tclcommand_electrokinetics().
int ek_save_checkpoint (char * filename)
Referenced by tclcommand_electrokinetics().
int ek_set_agrid (double agrid)
Referenced by tclcommand_electrokinetics().
int ek_set_bjerrumlength (double bjerrumlength)
Referenced by tclcommand_electrokinetics().
int ek_set_bulk_viscosity (double bulk_viscosity)
Referenced by tclcommand_electrokinetics().
int ek_set_D (int species, double D)
Referenced by tclcommand_electrokinetics().
int ek_set_density (int species, double density)
Referenced by tclcommand_electrokinetics().
int ek_set_electrostatics_coupling (bool electrostatics_coupling)
Referenced by tclcommand_electrokinetics().
int ek_set_ext_force (int species, double ext_force_x, double ext_force_y, double ext_force_z)
Referenced by tclcommand_electrokinetics().
int ek_set_friction (double friction)
Referenced by tclcommand_electrokinetics().
int ek_set_gamma_even (double gamma_even)
Referenced by tclcommand_electrokinetics().
int ek_set_gamma_odd (double gamma_odd)
Referenced by tclcommand_electrokinetics().
int ek_set_lb_density (double lb_density)
Referenced by tclcommand_electrokinetics().
int ek_set_lb_force (double * ext_force)
Referenced by tclcommand_electrokinetics().
int ek_set_reaction (int reactant, int product0, int product1, float rho_reactant_reservoir, float rho_product0_reservoir, float rho_product1_reservoir, float reaction_ct_rate, float reaction_fraction_0, float reaction_fraction_1, float mass_reactant, float mass_product0, float mass_product1)
Referenced by tclcommand_electrokinetics().
int ek_set_stencil (int stencil)
Referenced by tclcommand_electrokinetics().
int ek_set_T (double T)
Referenced by tclcommand_electrokinetics().
int ek_set_valency (int species, double valency)
Referenced by tclcommand_electrokinetics().
int ek_set_viscosity (double viscosity)
Referenced by tclcommand_electrokinetics().
int ek_tag_reaction_nodes (LB_Boundary * lbboundary, char reaction_type)
Referenced by tclcommand_electrokinetics().
void lb_set_ek_pointer (EK_parameters * pointeradress)
Variable Documentation
int ek_initialized
Definition at line 166 of file lbgpu.cpp.
Referenced by generate_lbboundary(), integrate_sd(), integrate_vv(), lb_init_boundaries(), lb_init_GPU(), and tclcommand_lbfluid().
EK_parameters ek_parameters
Referenced by lb_init_boundaries(), pdb_parse(), pdb_rhoindex_cartesian2linear(), populate_lattice(), print_boundary_lattice(), print_charge_field(), and tclcommand_electrokinetics().