ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: electrokinetics_tcl.cpp File Reference
electrokinetics_tcl.cpp File Reference
#include "config.hpp"
#include "electrokinetics_tcl.hpp"
#include "electrokinetics.hpp"
#include "lb.hpp"
#include "lb-boundaries.hpp"
#include "lb-boundaries_tcl.hpp"
#include "initialize.hpp"
#include "electrokinetics_pdb_parse.hpp"
Functions
int tclcommand_electrokinetics (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Variables
int ek_initialized
Function Documentation
int tclcommand_electrokinetics (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 32 of file electrokinetics_tcl.cpp.
References ARG0_IS_D, ARG0_IS_I, ARG0_IS_S, ARG1_IS_D, ARG1_IS_S, ARG_IS_D, ARG_IS_I, ARG_IS_S, ARG_IS_S_EXACT, LB_Boundary::charge_density, ek_calculate_net_charge(), ek_init(), ek_initialized, ek_lb_print_vtk_density(), ek_lb_print_vtk_velocity(), ek_load_checkpoint(), ek_neutralize_system(), ek_node_print_density(), ek_node_print_flux(), ek_node_print_velocity(), ek_node_set_density(), ek_parameters, ek_print_vtk_density(), ek_print_vtk_flux(), ek_print_vtk_lbforce(), ek_print_vtk_particle_potential(), ek_print_vtk_potential(), ek_print_vtk_pressure(), ek_print_vtk_reaction_tags(), ek_save_checkpoint(), ek_set_agrid(), ek_set_bjerrumlength(), ek_set_bulk_viscosity(), ek_set_D(), ek_set_density(), ek_set_electrostatics_coupling(), ek_set_ext_force(), ek_set_friction(), ek_set_gamma_even(), ek_set_gamma_odd(), ek_set_lb_density(), ek_set_lb_force(), ek_set_reaction(), ek_set_stencil(), ek_set_T(), ek_set_valency(), ek_set_viscosity(), ek_tag_reaction_nodes(), err, gather_runtime_errors(), generate_lbboundary(), i, lb_init_boundaries(), lb_lbfluid_print_vtk_boundary(), n_lb_boundaries, LB_Boundary::net_charge, on_lbboundary_change(), pdb_parse(), tclcommand_lbboundary_box(), tclcommand_lbboundary_cylinder(), tclcommand_lbboundary_hollow_cone(), tclcommand_lbboundary_pore(), tclcommand_lbboundary_rhomboid(), tclcommand_lbboundary_sphere(), tclcommand_lbboundary_spherocylinder(), tclcommand_lbboundary_stomatocyte(), and tclcommand_lbboundary_wall().
Referenced by tcl_register_commands().
Variable Documentation
int ek_initialized
Definition at line 166 of file lbgpu.cpp.
Referenced by tclcommand_electrokinetics().