ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: electrokinetics_pdb_parse.cpp File Reference
electrokinetics_pdb_parse.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <iostream>
#include <string>
#include <sstream>
#include <limits>
#include "electrokinetics_pdb_parse.hpp"
#include "PdbParser.hpp"
Functions
void galloc (void **ptr, size_t size)
unsigned int pdb_rhoindex_cartesian2linear (unsigned int x, unsigned int y, unsigned int z)
int print_charge_field (char *filename)
int print_boundary_lattice (char *filename)
int populate_lattice (PdbParser::PdbParser &parser, double scale)
int pdb_parse (char *pdb_filename, char *itp_filename, double scale)
Variables
const int pdb_SUCCESS = 0
const int pdb_ERROR = 1
float * pdb_charge_lattice = NULL
int * pdb_boundary_lattice = NULL
Function Documentation
void galloc (void ** ptr, size_t size)
Definition at line 54 of file electrokinetics_pdb_parse.cpp.
References free, malloc, and realloc.
Referenced by pdb_parse().
int pdb_parse (char * pdb_filename, char * itp_filename, double scale)
Definition at line 271 of file electrokinetics_pdb_parse.cpp.
References ek_parameters, galloc(), i, PdbParser::PdbParser::parse_file(), pdb_boundary_lattice, pdb_charge_lattice, pdb_ERROR, and populate_lattice().
Referenced by tclcommand_electrokinetics().
unsigned int pdb_rhoindex_cartesian2linear (unsigned int x, unsigned int y, unsigned int z)
Definition at line 73 of file electrokinetics_pdb_parse.cpp.
References ek_parameters.
Referenced by populate_lattice().
int populate_lattice (PdbParser::PdbParser & parser, double scale)
Definition at line 145 of file electrokinetics_pdb_parse.cpp.
References PdbParser::PdbParser::calc_bounding_box(), PdbParser::itp_atom::charge, DEBUG, ek_parameters, PdbParser::itp_atomtype::epsilon, PdbParser::PdbParser::itp_atoms, PdbParser::PdbParser::itp_atomtypes, PdbParser::BoundingBox::llx, PdbParser::BoundingBox::lly, PdbParser::BoundingBox::llz, PdbParser::PdbParser::pdb_atoms, pdb_boundary_lattice, pdb_charge_lattice, pdb_rhoindex_cartesian2linear(), pdb_SUCCESS, PdbParser::itp_atomtype::sigma, PdbParser::itp_atom::type, PdbParser::BoundingBox::urx, PdbParser::BoundingBox::ury, and PdbParser::BoundingBox::urz.
Referenced by pdb_parse().
int print_boundary_lattice (char * filename)
Definition at line 111 of file electrokinetics_pdb_parse.cpp.
References ek_parameters, i, pdb_boundary_lattice, pdb_ERROR, and pdb_SUCCESS.
int print_charge_field (char * filename)
Definition at line 77 of file electrokinetics_pdb_parse.cpp.
References ek_parameters, i, pdb_charge_lattice, pdb_ERROR, and pdb_SUCCESS.
Variable Documentation
int* pdb_boundary_lattice = NULL
Definition at line 40 of file electrokinetics_pdb_parse.cpp.
Referenced by lb_init_boundaries(), lb_init_boundaries_GPU(), pdb_parse(), populate_lattice(), and print_boundary_lattice().
float* pdb_charge_lattice = NULL
Definition at line 39 of file electrokinetics_pdb_parse.cpp.
Referenced by lb_init_boundaries(), pdb_parse(), populate_lattice(), and print_charge_field().
const int pdb_ERROR = 1
Definition at line 37 of file electrokinetics_pdb_parse.cpp.
Referenced by pdb_parse(), print_boundary_lattice(), and print_charge_field().
const int pdb_SUCCESS = 0
Definition at line 36 of file electrokinetics_pdb_parse.cpp.
Referenced by populate_lattice(), print_boundary_lattice(), and print_charge_field().