ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: endangledist.cpp File Reference
endangledist.cpp File Reference
Implementation of endangledist.hpp.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "communication.hpp"
#include "constraint.hpp"
#include "grid.hpp"
Functions
int endangledist_set_params (int bond_type, double bend, double phi0, double distmin, double distmax)
set parameters for endangledist potential
static double calc_pwdist (Particle *p1, Bonded_ia_parameters *iaparams, int *clconstr)
Calculates the minimum distance between a particle to any wall constraint.
static double calc_pwangle (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, int *constr)
Calculate angle that p1–p2 makes with wall constraint.
int calc_endangledist_pair_force (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double force1[3], double force2[3])
int endangledist_pair_energy (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double *_energy)
Detailed Description
Implementation of endangledist.hpp.
Definition in file endangledist.cpp.
Function Documentation
int calc_endangledist_pair_force (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double force1[3], double force2[3])
Definition at line 150 of file endangledist.cpp.
References Endangledist_bond_parameters::bend, Constraint::c, calc_pwangle(), calc_pwdist(), check_id, constraints, Endangledist_bond_parameters::distmax, Endangledist_bond_parameters::distmin, Bond_parameters::endangledist, ParticleForce::f, Particle::f, get_mi_vector(), i, ParticleProperties::identity, Constraint_wall::n, ONEPART_TRACE, ParticlePosition::p, Particle::p, Bonded_ia_parameters::p, Endangledist_bond_parameters::phi0, PI, Particle::r, SQR(), sqrlen(), this_node, and Constraint::wal.
Referenced by add_bonded_force().
static double calc_pwangle (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, int * constr) static
Calculate angle that p1–p2 makes with wall constraint.
Definition at line 116 of file endangledist.cpp.
References constraints, get_mi_vector(), Constraint_wall::n, ParticlePosition::p, Particle::r, scalar(), sqrlen(), TINY_COS_VALUE, and Constraint::wal.
Referenced by calc_endangledist_pair_force(), and endangledist_pair_energy().
static double calc_pwdist (Particle * p1, Bonded_ia_parameters * iaparams, int * clconstr) static
Calculates the minimum distance between a particle to any wall constraint.
Definition at line 59 of file endangledist.cpp.
References Constraint::c, CONSTRAINT_WAL, constraints, Constraint_wall::d, fold_position(), ParticleLocal::i, Particle::l, Constraint_wall::n, n_constraints, ParticlePosition::p, Particle::r, and Constraint::wal.
Referenced by calc_endangledist_pair_force(), and endangledist_pair_energy().
int endangledist_pair_energy (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double * _energy)
Definition at line 244 of file endangledist.cpp.
References Endangledist_bond_parameters::bend, calc_pwangle(), calc_pwdist(), Endangledist_bond_parameters::distmax, Endangledist_bond_parameters::distmin, Bond_parameters::endangledist, Bonded_ia_parameters::p, Endangledist_bond_parameters::phi0, PI, and SQR().
Referenced by add_bonded_energy().
int endangledist_set_params (int bond_type, double bend, double phi0, double distmin, double distmax)
set parameters for endangledist potential
Definition at line 33 of file endangledist.cpp.
References Endangledist_bond_parameters::bend, BONDED_IA_ENDANGLEDIST, bonded_ia_params, Endangledist_bond_parameters::distmax, Endangledist_bond_parameters::distmin, Bond_parameters::endangledist, ES_ERROR, ES_OK, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Endangledist_bond_parameters::phi0, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_endangledist().