ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: energy_tcl.cpp File Reference
energy_tcl.cpp File Reference
Implements the analyze energy command.
#include "utils.hpp"
#include "parser.hpp"
#include "energy.hpp"
#include "external_potential.hpp"
Functions
static void tclcommand_analyze_print_all (Tcl_Interp *interp)
int tclcommand_analyze_parse_and_print_energy (Tcl_Interp *interp, int argc, char **argv)
write out energy.
Detailed Description
Implements the analyze energy command.
Definition in file energy_tcl.cpp.
Function Documentation
int tclcommand_analyze_parse_and_print_energy (Tcl_Interp * interp, int argc, char ** argv)
write out energy.
See energy_tcl.cpp
Definition at line 137 of file energy_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, ARG_IS_I, Observable_stat::coulomb, Observable_stat::data, Observable_stat::dipolar, DoubleList::e, ExternalPotential::energy, external_potentials, i, init_energies(), Observable_stat::init_status, master_energy_calc(), DoubleList::n, n_bonded_ia, Observable_stat::n_coulomb, Observable_stat::n_dipolar, n_external_potentials, n_part, n_particle_types, obsstat_bonded(), obsstat_nonbonded(), tclcommand_analyze_print_all(), and total_energy.
Referenced by tclcommand_analyze().
static void tclcommand_analyze_print_all (Tcl_Interp * interp) static
Definition at line 34 of file energy_tcl.cpp.
References BONDED_IA_NONE, bonded_ia_params, checkIfParticlesInteract(), Observable_stat::coulomb, coulomb, COULOMB_NONE, Observable_stat::data, Observable_stat::dipolar, DIPOLAR_NONE, Coulomb_parameters::Dmethod, DoubleList::e, ELECTROSTATICS, ExternalPotential::energy, energy, external_potentials, get_name_of_bonded_ia(), i, Coulomb_parameters::method, DoubleList::n, n_bonded_ia, Observable_stat::n_coulomb, Observable_stat::n_dipolar, n_external_potentials, n_particle_types, obsstat_bonded(), obsstat_nonbonded(), and total_energy.
Referenced by tclcommand_analyze_parse_and_print_energy().