ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: energy.cpp File Reference
energy.cpp File Reference
Implementation of energy.hpp.
#include "energy_inline.hpp"
#include "maggs.hpp"
#include "initialize.hpp"
#include "magnetic_non_p3m_methods.hpp"
#include "mdlc_correction.hpp"
#include "cuda_interface.hpp"
#include "forces.hpp"
#include "EspressoSystemInterface.hpp"
Functions
void init_energies (Observable_stat *stat)
allocate energy arrays and initialize with zero
void master_energy_calc ()
on the master node: calc energies only if necessary
void energy_calc (double *result)
parallel energy calculation.
void calc_long_range_energies ()
Calculate long range energies (P3M, MMM2d...).
Variables
ActorList energyActors
Observable_stat energy = {0, {NULL,0,0}, 0,0,0}
Observable_stat total_energy = {0, {NULL,0,0}, 0,0,0}
Detailed Description
Implementation of energy.hpp.
Definition in file energy.cpp.
Function Documentation
void calc_long_range_energies ()
Calculate long range energies (P3M, MMM2d...).
Definition at line 173 of file energy.cpp.
References add_mdlc_energy_corrections(), Observable_stat::coulomb, coulomb, COULOMB_ELC_P3M, COULOMB_MAGGS, COULOMB_MMM2D, COULOMB_P3M, COULOMB_P3M_GPU, dawaanr_calculations(), Observable_stat::dipolar, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, maggs_electric_energy(), magnetic_dipolar_direct_sum_calculations(), Coulomb_parameters::method, MMM2D_dielectric_layers_energy_contribution(), MMM2D_far_energy(), and runtimeError.
Referenced by energy_calc().
void energy_calc (double * result)
parallel energy calculation.
Parameters
result non-zero only on master node; will contain the cumulative over all nodes.
Definition at line 102 of file energy.cpp.
References build_verlet_lists(), calc_long_range_energies(), calculate_link_cell_energies(), calculate_verlet_energies(), cell_structure, CELL_STRUCTURE_DOMDEC, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, clear_energy_on_GPU(), comm_cart, copy_energy_from_GPU(), Observable_stat::data, dd, DoubleList::e, ExternalPotential::energy, espressoSystemInterface, external_potentials, free, i, init_energies(), EspressoSystemInterface::Instance(), interactions_sanity_checks(), layered_calculate_energies(), malloc, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, DoubleList::n, n_external_potentials, nsq_calculate_energies(), on_observable_calc(), rebuild_verletlist, smaller_time_step, time_step, CellStructure::type, EspressoSystemInterface::update(), and DomainDecomposition::use_vList.
Referenced by mpi_gather_stats(), and mpi_gather_stats_slave().
void init_energies (Observable_stat * stat)
allocate energy arrays and initialize with zero
Definition at line 50 of file energy.cpp.
References coulomb, COULOMB_ELC_P3M, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, external_potential_init_energies(), Observable_stat::init_status, Coulomb_parameters::method, n_bonded_ia, n_particle_types, and obsstat_realloc_and_clear().
Referenced by energy_calc(), hamiltonian_calc(), and tclcommand_analyze_parse_and_print_energy().
void master_energy_calc ()
on the master node: calc energies only if necessary
Definition at line 94 of file energy.cpp.
References Observable_stat::data, DoubleList::e, Observable_stat::init_status, and mpi_gather_stats().
Referenced by hamiltonian_calc(), and tclcommand_analyze_parse_and_print_energy().
Variable Documentation
Observable_stat energy = {0, {NULL,0,0}, 0,0,0}
Definition at line 45 of file energy.cpp.
Referenced by add_bonded_energy(), add_constraints_energy(), add_kinetic_energy(), add_non_bonded_pair_energy(), fene_pair_energy(), get_DLC_dipolar(), get_DLC_energy_dipolar(), subt_lj_pair_energy(), and tclcommand_analyze_print_all().
ActorList energyActors
Definition at line 43 of file energy.cpp.
Referenced by tclcommand_inter_coulomb_parse_ewaldgpu_notune(), tclcommand_inter_coulomb_parse_ewaldgpu_tune(), tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha(), and tclcommand_inter_coulomb_parse_mmm1dgpu().
Observable_stat total_energy = {0, {NULL,0,0}, 0,0,0}
Definition at line 46 of file energy.cpp.
Referenced by hamiltonian_calc(), invalidate_obs(), tclcommand_analyze_parse_and_print_energy(), and tclcommand_analyze_print_all().