ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: energy_inline.hpp File Reference
energy_inline.hpp File Reference
Implementation of the energy calculation.
#include "statistics.hpp"
#include "thermostat.hpp"
#include "p3m.hpp"
#include "p3m-dipolar.hpp"
#include "lj.hpp"
#include "ljgen.hpp"
#include "steppot.hpp"
#include "hertzian.hpp"
#include "gaussian.hpp"
#include "bmhtf-nacl.hpp"
#include "buckingham.hpp"
#include "soft_sphere.hpp"
#include "hat.hpp"
#include "ljcos.hpp"
#include "ljcos2.hpp"
#include "ljangle.hpp"
#include "tab.hpp"
#include "overlap.hpp"
#include "gb.hpp"
#include "fene.hpp"
#include "harmonic_dumbbell.hpp"
#include "harmonic.hpp"
#include "quartic.hpp"
#include "bonded_coulomb.hpp"
#include "subt_lj.hpp"
#include "angle.hpp"
#include "angle_harmonic.hpp"
#include "angle_cosine.hpp"
#include "angle_cossquare.hpp"
#include "angledist.hpp"
#include "debye_hueckel.hpp"
#include "endangledist.hpp"
#include "reaction_field.hpp"
#include "mmm1d.hpp"
#include "mmm2d.hpp"
#include "morse.hpp"
#include "elc.hpp"
#include "hydrogen_bond.hpp"
#include "twist_stack.hpp"
#include "actor/EwaldgpuForce_ShortRange.hpp"
#include "energy.hpp"
Functions
double calc_non_bonded_pair_energy (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double dist2)
Calculate non bonded energies between a pair of particles.
void add_non_bonded_pair_energy (Particle *p1, Particle *p2, double d[3], double dist, double dist2)
Add non bonded energies and short range coulomb between a pair of particles.
void add_bonded_energy (Particle *p1)
Calculate bonded energies for one particle.
void add_kinetic_energy (Particle *p1)
Calculate kinetic energies for one particle.
Detailed Description
Implementation of the energy calculation.
Definition in file energy_inline.hpp.
Function Documentation
void add_bonded_energy (Particle * p1) inline
Calculate bonded energies for one particle.
Parameters
p1 particle for which to calculate energies
Definition at line 264 of file energy_inline.hpp.
References angle_cosine_energy(), angle_cossquare_energy(), angle_energy(), angle_harmonic_energy(), angledist_energy(), Particle::bl, bonded_coulomb_pair_energy(), BONDED_IA_ANGLE_COSINE, BONDED_IA_ANGLE_COSSQUARE, BONDED_IA_ANGLE_HARMONIC, BONDED_IA_ANGLE_OLD, BONDED_IA_ANGLEDIST, BONDED_IA_BONDED_COULOMB, BONDED_IA_CG_DNA_BASEPAIR, BONDED_IA_CG_DNA_STACKING, BONDED_IA_DIHEDRAL, BONDED_IA_ENDANGLEDIST, BONDED_IA_FENE, BONDED_IA_HARMONIC, BONDED_IA_HARMONIC_DUMBBELL, BONDED_IA_OVERLAPPED, bonded_ia_params, BONDED_IA_QUARTIC, BONDED_IA_RIGID_BOND, BONDED_IA_SUBT_LJ, BONDED_IA_TABULATED, BONDED_IA_VIRTUAL_BOND, calc_hydrogen_bond_energy(), calc_twist_stack_energy(), dihedral_energy(), IntList::e, endangledist_pair_energy(), energy, fene_pair_energy(), get_mi_vector(), harmonic_dumbbell_pair_energy(), harmonic_pair_energy(), i, ParticleProperties::identity, local_particles, Bonded_ia_parameters::num, obsstat_bonded(), Bond_parameters::overlap, overlap_angle_energy(), OVERLAP_BOND_ANGLE, OVERLAP_BOND_DIHEDRAL, overlap_bond_energy(), OVERLAP_BOND_LENGTH, overlap_dihedral_energy(), ParticlePosition::p, Particle::p, Bonded_ia_parameters::p, quartic_pair_energy(), Particle::r, runtimeError, subt_lj_pair_energy(), Bond_parameters::tab, tab_angle_energy(), TAB_BOND_ANGLE, TAB_BOND_DIHEDRAL, tab_bond_energy(), TAB_BOND_LENGTH, tab_dihedral_energy(), Tabulated_bond_parameters::type, Overlap_bond_parameters::type, and Bonded_ia_parameters::type.
Referenced by calculate_link_cell_energies(), calculate_verlet_energies(), layered_calculate_energies(), and nsq_calculate_energies().
void add_kinetic_energy (Particle * p1) inline
Calculate kinetic energies for one particle.
Parameters
p1 particle for which to calculate energies
Definition at line 491 of file energy_inline.hpp.
References Observable_stat::data, DoubleList::e, energy, ifParticleIsVirtual(), Particle::m, ParticleMomentum::omega, Particle::p, PMASS, ParticleProperties::rinertia, ParticleProperties::rotation, SQR(), time_step, and ParticleMomentum::v.
Referenced by calculate_link_cell_energies(), calculate_verlet_energies(), layered_calculate_energies(), and nsq_calculate_energies().
void add_non_bonded_pair_energy (Particle * p1, Particle * p2, double d[3], double dist, double dist2) inline
Add non bonded energies and short range coulomb between a pair of particles.
Parameters
p1 pointer to particle 1.
p2 pointer to particle 2.
d vector between p1 and p2.
dist distance between p1 and p2.
dist2 distance squared between p1 and p2.
Definition at line 185 of file energy_inline.hpp.
References calc_non_bonded_pair_energy(), Observable_stat::coulomb, coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_EWALD_GPU, COULOMB_INTER_RF, COULOMB_MMM1D, COULOMB_MMM2D, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, dh_coulomb_pair_energy(), Observable_stat::dipolar, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, energy, ewaldgpu_coulomb_pair_energy(), get_ia_param(), ia_params, Coulomb_parameters::method, mmm1d_coulomb_pair_energy(), mmm2d_coulomb_pair_energy(), obsstat_nonbonded(), Particle::p, ParticleProperties::q, rf_coulomb_pair_energy(), and ParticleProperties::type.
Referenced by calculate_link_cell_energies(), calculate_verlet_energies(), layered_calculate_energies(), and nsq_calculate_energies().
double calc_non_bonded_pair_energy (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double dist2) inline
Calculate non bonded energies between a pair of particles.
Parameters
p1 pointer to particle 1.
p2 pointer to particle 2.
ia_params the interaction parameters between the two particles
d vector between p1 and p2.
dist distance between p1 and p2.
dist2 distance squared between p1 and p2.
Returns
the short ranged interaction energy between the two particles
Definition at line 81 of file energy_inline.hpp.
References BMHTF_pair_energy(), buck_pair_energy(), checkIfParticlesInteractViaMolCut(), gaussian_pair_energy(), gb_pair_energy(), hat_pair_energy(), hertzian_pair_energy(), interrf_pair_energy(), lj_pair_energy(), ljangle_pair_energy(), ljcos2_pair_energy(), ljcos_pair_energy(), ljgen_pair_energy(), ParticleProperties::mol_id, morse_pair_energy(), Particle::p, SmSt_pair_energy(), soft_pair_energy(), and tabulated_pair_energy().
Referenced by add_constraints_energy(), and add_non_bonded_pair_energy().