ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: errorhandling.cpp File Reference
errorhandling.cpp File Reference
Implementation of errorhandling.hpp.
#include <cstring>
#include <cstdlib>
#include <csignal>
#include <iostream>
#include "utils.hpp"
#include "errorhandling.hpp"
#include "communication.hpp"
#include "RuntimeErrorCollector.hpp"
Functions
static void sigint_handler (int sig)
void register_sigint_handler ()
register a handler for sigint that translates it into an runtime error.
void initRuntimeErrorCollector ()
void _runtimeWarning (const std::string &msg, const char *function, const char *file, const int line)
void _runtimeWarning (const char *msg, const char *function, const char *file, const int line)
void _runtimeWarning (const std::ostringstream &msg, const char *function, const char *file, const int line)
void _runtimeError (const std::string &msg, const char *function, const char *file, const int line)
void _runtimeError (const char *msg, const char *function, const char *file, const int line)
void _runtimeError (const std::ostringstream &msg, const char *function, const char *file, const int line)
int check_runtime_errors ()
check for runtime errors on all nodes.
list< string > mpiRuntimeErrorCollectorGather ()
void mpiRuntimeErrorCollectorGatherSlave (int node, int parm)
void errexit ()
exit ungracefully, core dump if switched on.
Variables
RuntimeErrorCollector * runtimeErrorCollector = NULL
list that contains the runtime error messages
Detailed Description
Implementation of errorhandling.hpp.
Definition in file errorhandling.cpp.
Function Documentation
void _runtimeError (const std::string & msg, const char * function, const char * file, const int line)
Definition at line 84 of file errorhandling.cpp.
References RuntimeErrorCollector::error().
void _runtimeError (const char * msg, const char * function, const char * file, const int line)
Definition at line 89 of file errorhandling.cpp.
References RuntimeErrorCollector::error().
void _runtimeError (const std::ostringstream & msg, const char * function, const char * file, const int line)
Definition at line 94 of file errorhandling.cpp.
References RuntimeErrorCollector::error().
void _runtimeWarning (const std::string & msg, const char * function, const char * file, const int line)
Definition at line 69 of file errorhandling.cpp.
References RuntimeErrorCollector::warning().
void _runtimeWarning (const char * msg, const char * function, const char * file, const int line)
Definition at line 74 of file errorhandling.cpp.
References RuntimeErrorCollector::warning().
void _runtimeWarning (const std::ostringstream & msg, const char * function, const char * file, const int line)
Definition at line 79 of file errorhandling.cpp.
References RuntimeErrorCollector::warning().
int check_runtime_errors ()
check for runtime errors on all nodes.
This has to be called on all nodes synchronously.
Returns
the number of characters in the error messages of all nodes together.
Definition at line 99 of file errorhandling.cpp.
References RuntimeErrorCollector::count().
Referenced by integrate_sd(), integrate_vv(), lattice_read_file(), lb_init(), mpi_bcast_parameter(), mpi_bcast_parameter_slave(), mpi_iccp3m_init(), mpi_iccp3m_init_slave(), mpi_iccp3m_iteration(), mpi_iccp3m_iteration_slave(), mpi_integrate(), and mpi_integrate_slave().
void errexit ()
exit ungracefully, core dump if switched on.
Definition at line 115 of file errorhandling.cpp.
References core(), and mpi_abort().
Referenced by _cuda_check_errors(), _cuda_safe_mem(), _cudaCheckError(), add_constraints_energy(), add_constraints_forces(), add_forces_from_recv_buffer(), analyze_fold_molecules(), build_verlet_lists(), build_verlet_lists_and_calc_verlet_ia(), build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_buck_cap_radii(), calc_radial_density_map(), calc_structurefactor(), check_cells_consistency(), check_particle_consistency(), check_particles(), check_tab_forcecap(), correct_vel_shake(), dawaanr_calculations(), get_name_of_bonded_ia(), ghost_communicator(), gpu_init_particle_comm(), icosaederC(), init_random_seed(), integrate_ensemble_init(), layered_exchange_and_sort_particles(), lb_calc_particle_lattice_ia_gpu(), lb_get_para_pointer(), lb_init_GPU(), lb_lbfluid_get_ext_force(), lb_lbfluid_get_interpolated_velocity_global(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_density(), lb_viscous_coupling(), local_place_particle(), local_remove_particle(), magnetic_dipolar_direct_sum_calculations(), maxwell_velocitiesC(), mdlc_tune(), MMM2D_setup_constants(), mpi_bcast_coulomb_params_slave(), mpi_gather_stats(), mpi_gather_stats_slave(), mpi_get_particles(), MPI_Irecv(), MPI_Isend(), mpi_loop(), MPI_Recv(), MPI_Send(), MPI_Sendrecv(), mpifake_sendrecv(), mpifake_unpack_hvector(), mpifake_unpack_struct(), on_coulomb_change(), prepare_send_buffer(), printAllComms(), propagate_pos_sd_cuda(), propagate_vel_pos(), put_recv_buffer(), recv_particles(), reduce_forces_sum(), remove_all_bonds_to(), sd_compute_brownian_force_farfield(), tclprint_to_result_overlapIA(), topology_init(), topology_release(), and velocitiesC().
void initRuntimeErrorCollector ()
Definition at line 65 of file errorhandling.cpp.
References MPI_COMM_WORLD.
Referenced by mpi_init().
list<string> mpiRuntimeErrorCollectorGather ()
Definition at line 104 of file errorhandling.cpp.
References RuntimeErrorCollector::gather(), mpi_call(), and mpiRuntimeErrorCollectorGatherSlave().
Referenced by gather_runtime_errors().
void mpiRuntimeErrorCollectorGatherSlave (int node, int parm)
Definition at line 111 of file errorhandling.cpp.
References RuntimeErrorCollector::gatherSlave().
Referenced by mpiRuntimeErrorCollectorGather().
void register_sigint_handler ()
register a handler for sigint that translates it into an runtime error.
Definition at line 55 of file errorhandling.cpp.
References sigint_handler().
Referenced by on_program_start().
static void sigint_handler (int sig) static
Definition at line 35 of file errorhandling.cpp.
References runtimeError.
Referenced by register_sigint_handler().
Variable Documentation
RuntimeErrorCollector* runtimeErrorCollector = NULL
list that contains the runtime error messages
Definition at line 62 of file errorhandling.cpp.