ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: Ewaldgpu_tcl.hpp File Reference
Ewaldgpu_tcl.hpp File Reference
#include "parser.hpp"
#include "config.hpp"
Functions
int tclprint_to_result_ewaldgpu (Tcl_Interp *interp)
int tclcommand_inter_coulomb_parse_ewaldgpu (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_inter_coulomb_parse_ewaldgpu_notune (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_inter_coulomb_parse_ewaldgpu_tune (Tcl_Interp *interp, int argc, char **argv, int adaptive)
int tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha (Tcl_Interp *interp, int argc, char **argv)
Function Documentation
int tclcommand_inter_coulomb_parse_ewaldgpu (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 29 of file Ewaldgpu_tcl.cpp.
References ARG0_IS_S, tclcommand_inter_coulomb_parse_ewaldgpu_notune(), tclcommand_inter_coulomb_parse_ewaldgpu_tune(), and tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha().
Referenced by tclcommand_inter_parse_coulomb().
int tclcommand_inter_coulomb_parse_ewaldgpu_notune (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 55 of file Ewaldgpu_tcl.cpp.
References ActorList::add(), ARG_IS_D, ARG_IS_I, ARG_IS_INTLIST, coulomb, COULOMB_EWALD_GPU, IntList::e, energyActors, espressoSystemInterface, ewaldgpu_params, forceActors, init_intlist(), Ewaldgpu_params::isTuned, Ewaldgpu_params::isTunedFlag, Coulomb_parameters::method, mpi_bcast_coulomb_params(), IntList::n, rebuild_verletlist, and EwaldgpuForce::set_params().
Referenced by tclcommand_inter_coulomb_parse_ewaldgpu().
int tclcommand_inter_coulomb_parse_ewaldgpu_tune (Tcl_Interp * interp, int argc, char ** argv, int adaptive)
Definition at line 123 of file Ewaldgpu_tcl.cpp.
References EwaldgpuForce::adaptive_tune(), ActorList::add(), ARG0_IS_S, ARG1_IS_D, ARG1_IS_I, coulomb, COULOMB_EWALD_GPU, energyActors, ES_ERROR, espressoSystemInterface, ewaldgpu_params, forceActors, free, Ewaldgpu_params::isTunedFlag, Coulomb_parameters::method, mpi_bcast_coulomb_params(), rebuild_verletlist, and EwaldgpuForce::set_params_tune().
Referenced by tclcommand_inter_coulomb_parse_ewaldgpu().
int tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 203 of file Ewaldgpu_tcl.cpp.
References ActorList::add(), ARG0_IS_D, ARG_IS_D, ARG_IS_I, ARG_IS_INTLIST, box_l, EwaldgpuForce::compute_optimal_alpha(), EwaldgpuForce::compute_q_sqare(), coulomb, COULOMB_EWALD_GPU, IntList::e, energyActors, espressoSystemInterface, ewaldgpu_params, forceActors, init_intlist(), Ewaldgpu_params::isTuned, Ewaldgpu_params::isTunedFlag, malloc, Coulomb_parameters::method, mpi_bcast_coulomb_params(), mpi_get_particles(), IntList::n, n_part, and rebuild_verletlist.
Referenced by tclcommand_inter_coulomb_parse_ewaldgpu().
int tclprint_to_result_ewaldgpu (Tcl_Interp * interp)
Definition at line 11 of file Ewaldgpu_tcl.cpp.
References Ewaldgpu_params::accuracy, Ewaldgpu_params::alpha, ewaldgpu_params, Ewaldgpu_params::num_kx, Ewaldgpu_params::num_ky, Ewaldgpu_params::num_kz, and Ewaldgpu_params::rcut.
Referenced by tclprint_to_result_CoulombIA().