ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: external_potential.hpp File Reference
external_potential.hpp File Reference
#include "lattice.hpp"
Data Structures
struct ExternalPotentialTabulated
struct ExternalPotential
Macros
#define MAX_FILENAME_SIZE 256
#define EXTERNAL_POTENTIAL_TYPE_TABULATED 0
#define EXTERNAL_POTENTIAL_TYPE_ROD 1
Functions
void external_potential_pre_init ()
int external_potential_tabulated_init (int number, char *filename, int n_particle_types, double *scale)
void external_potential_init_energies ()
int generate_external_potential (ExternalPotential **externalPotential)
int external_potential_init (int number, char *filename, int n_particle_types, double *scale)
int external_potential_tabulated_read_potential_file (int number)
void add_external_potential_forces (Particle *p)
void add_external_potential_energy (Particle *p)
int write_local_lattice_to_file (const char *filename_prefix, Lattice *lattice)
Variables
ExternalPotential * external_potentials
int n_external_potentials
Macro Definition Documentation
#define EXTERNAL_POTENTIAL_TYPE_ROD 1
Definition at line 27 of file external_potential.hpp.
#define EXTERNAL_POTENTIAL_TYPE_TABULATED 0
Definition at line 26 of file external_potential.hpp.
Referenced by add_external_potential_energy(), add_external_potential_forces(), and external_potential_tabulated_init().
#define MAX_FILENAME_SIZE 256
Definition at line 24 of file external_potential.hpp.
Referenced by external_potential_tabulated_init().
Function Documentation
void add_external_potential_energy (Particle * p)
Definition at line 294 of file external_potential.cpp.
References add_external_potential_tabulated_energy(), EXTERNAL_POTENTIAL_TYPE_TABULATED, i, n_external_potentials, and runtimeError.
Referenced by calculate_link_cell_energies(), calculate_verlet_energies(), layered_calculate_energies(), and nsq_calculate_energies().
void add_external_potential_forces (Particle * p)
Definition at line 265 of file external_potential.cpp.
References add_external_potential_tabulated_forces(), EXTERNAL_POTENTIAL_TYPE_TABULATED, i, n_external_potentials, and runtimeError.
Referenced by build_verlet_lists_and_calc_verlet_ia(), calc_link_cell(), calculate_verlet_ia(), layered_calculate_ia(), and nsq_calculate_ia().
int external_potential_init (int number, char * filename, int n_particle_types, double * scale)
void external_potential_init_energies ()
Definition at line 307 of file external_potential.cpp.
References ExternalPotential::energy, i, and n_external_potentials.
Referenced by init_energies().
void external_potential_pre_init ()
Definition at line 27 of file external_potential.cpp.
References n_external_potentials.
Referenced by on_program_start().
int external_potential_tabulated_init (int number, char * filename, int n_particle_types, double * scale)
Definition at line 45 of file external_potential.cpp.
References ES_ERROR, ES_OK, EXTERNAL_POTENTIAL_TYPE_TABULATED, ExternalPotentialTabulated::filename, i, malloc, MAX_FILENAME_SIZE, mpi_external_potential_broadcast(), mpi_external_potential_tabulated_read_potential_file(), ExternalPotential::n_particle_types, n_particle_types, ExternalPotential::scale, ExternalPotential::tabulated, and ExternalPotential::type.
Referenced by tclcommand_external_potential_tabulated().
int external_potential_tabulated_read_potential_file (int number)
Definition at line 64 of file external_potential.cpp.
References ExternalPotentialTabulated::filename, lattice_read_file(), and ExternalPotential::tabulated.
Referenced by mpi_external_potential_tabulated_read_potential_file(), and mpi_external_potential_tabulated_read_potential_file_slave().
int generate_external_potential (ExternalPotential ** externalPotential)
Definition at line 33 of file external_potential.cpp.
References ES_OK, n_external_potentials, and realloc.
Referenced by mpi_external_potential_broadcast_slave(), and tclcommand_external_potential().
int write_local_lattice_to_file (const char * filename_prefix, Lattice * lattice)
Definition at line 203 of file external_potential.cpp.
References Lattice::agrid, Lattice::dim, Lattice::element_size, ES_OK, Lattice::get_data_for_halo_index(), Lattice::grid, Lattice::grid_volume, Lattice::halo_grid, Lattice::halo_grid_surface, Lattice::halo_grid_volume, Lattice::halo_offset, Lattice::halo_size, i, index_t, Lattice::local_index_offset, Lattice::local_offset, Lattice::map_halo_index_to_pos(), Lattice::offset, and this_node.
Referenced by lattice_read_file().
Variable Documentation
ExternalPotential* external_potentials
Definition at line 24 of file external_potential.cpp.
Referenced by energy_calc(), mpi_external_potential_broadcast(), mpi_external_potential_broadcast_slave(), mpi_external_potential_sum_energies(), mpi_external_potential_sum_energies_slave(), tclcommand_analyze_parse_and_print_energy(), and tclcommand_analyze_print_all().
int n_external_potentials
Definition at line 25 of file external_potential.cpp.
Referenced by add_external_potential_energy(), add_external_potential_forces(), energy_calc(), external_potential_init_energies(), external_potential_pre_init(), generate_external_potential(), mpi_external_potential_sum_energies(), mpi_external_potential_sum_energies_slave(), tclcommand_analyze_parse_and_print_energy(), tclcommand_analyze_print_all(), and tclcommand_external_potential_tabulated().