ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: fd-electrostatics_cuda.cu File Reference
fd-electrostatics_cuda.cu File Reference
#include <cuda.h>
#include <cufft.h>
#include <fd-electrostatics.hpp>
#include <cuda_utils.hpp>
#include <string>
#include <cstdio>
Functions
__global__ void createGreensfcn ()
__global__ void multiplyGreensfcn (cufftComplex *charge_potential)
__device__ unsigned int fde_getThreadIndex ()
Variables
static __device__ __constant__ FdElectrostatics::Parameters fde_parameters_gpu
Function Documentation
__global__ void createGreensfcn ()
Definition at line 111 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::InputParameters::agrid, FdElectrostatics::InputParameters::bjerrum_length, FdElectrostatics::InputParameters::dim_x, FdElectrostatics::InputParameters::dim_y, FdElectrostatics::InputParameters::dim_z, fde_getThreadIndex(), fde_parameters_gpu, FdElectrostatics::Parameters::greensfcn, FdElectrostatics::InputParameters::kT, and PI_FLOAT.
Referenced by FdElectrostatics::FdElectrostatics().
__device__ unsigned int fde_getThreadIndex ()
Definition at line 18 of file fd-electrostatics_cuda.cu.
Referenced by createGreensfcn(), and multiplyGreensfcn().
__global__ void multiplyGreensfcn (cufftComplex * charge_potential)
Definition at line 153 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::InputParameters::dim_x, FdElectrostatics::InputParameters::dim_y, FdElectrostatics::InputParameters::dim_z, fde_getThreadIndex(), fde_parameters_gpu, and FdElectrostatics::Parameters::greensfcn.
Referenced by FdElectrostatics::calculatePotential().
Variable Documentation
__device__ __constant__ FdElectrostatics::Parameters fde_parameters_gpu static
Definition at line 15 of file fd-electrostatics_cuda.cu.
Referenced by createGreensfcn(), FdElectrostatics::FdElectrostatics(), and multiplyGreensfcn().