ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: forces.cpp File Reference
forces.cpp File Reference
Force calculation.
#include "p3m_gpu.hpp"
#include "maggs.hpp"
#include "forces_inline.hpp"
#include "electrokinetics.hpp"
Functions
void init_forces ()
initialize real particle forces with thermostat forces and ghost particle forces with zero.
void init_forces_ghosts ()
Set forces of all ghosts to zero.
void check_forces ()
Check if forces are NAN.
void calc_long_range_forces ()
Calculate long range forces (P3M, MMM2d...).
void calc_non_bonded_pair_force_from_partcfg (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double dist2, double force[3], double torque1[3], double torque2[3])
void calc_non_bonded_pair_force_from_partcfg_simple (Particle *p1, Particle *p2, double d[3], double dist, double dist2, double force[3])
Variables
ActorList forceActors
Detailed Description
Force calculation.
For more information see forces.h.
Definition in file forces.cpp.
Function Documentation
void calc_long_range_forces ()
Calculate long range forces (P3M, MMM2d...).
Definition at line 152 of file forces.cpp.
References add_mdlc_force_corrections(), coulomb, COULOMB_ELC_P3M, COULOMB_MAGGS, COULOMB_MMM2D, COULOMB_P3M, COULOMB_P3M_GPU, dawaanr_calculations(), DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, ek_calculate_electrostatic_coupling(), FORCE_TRACE, INTEG_METHOD_NPT_ISO, integ_switch, maggs_calc_forces(), magnetic_dipolar_direct_sum_calculations(), Coulomb_parameters::method, MMM2D_add_far_force(), MMM2D_dielectric_layers_force_contribution(), nptiso, p3m_gpu_add_farfield_force(), nptiso_struct::p_vir, runtimeError, and this_node.
Referenced by force_calc().
void calc_non_bonded_pair_force_from_partcfg (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double dist2, double force[3], double torque1[3], double torque2[3])
Definition at line 256 of file forces.cpp.
References calc_non_bonded_pair_force_parts(), and checkIfParticlesInteractViaMolCut_partcfg().
Referenced by calc_non_bonded_pair_force_from_partcfg_simple().
void calc_non_bonded_pair_force_from_partcfg_simple (Particle * p1, Particle * p2, double d[3], double dist, double dist2, double force[3])
Definition at line 271 of file forces.cpp.
References calc_non_bonded_pair_force_from_partcfg(), get_ia_param(), ia_params, Particle::p, and ParticleProperties::type.
Referenced by calc_force_between_mol().
void check_forces ()
Check if forces are NAN.
Definition at line 128 of file forces.cpp.
References CellPList::cell, check_particle_force(), ghost_cells, i, local_cells, CellPList::n, ParticleList::n, and ParticleList::part.
void init_forces ()
initialize real particle forces with thermostat forces and ghost particle forces with zero.
Definition at line 67 of file forces.cpp.
References CellPList::cell, ghost_cells, i, init_constraint_forces(), init_ghost_force(), init_local_particle_force(), INTEG_METHOD_NPT_ISO, integ_switch, local_cells, CellPList::n, ParticleList::n, nptiso, nptiso_struct::p_vir, and ParticleList::part.
Referenced by force_calc().
void init_forces_ghosts ()
Set forces of all ghosts to zero.
Definition at line 111 of file forces.cpp.
References CellPList::cell, ghost_cells, i, init_ghost_force(), CellPList::n, ParticleList::n, and ParticleList::part.
Referenced by force_calc().
Variable Documentation
ActorList forceActors
Definition at line 65 of file forces.cpp.
Referenced by force_calc(), tclcommand_HarmonicOrientationWell(), tclcommand_inter_coulomb_parse_ewaldgpu_notune(), tclcommand_inter_coulomb_parse_ewaldgpu_tune(), tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha(), and tclcommand_inter_coulomb_parse_mmm1dgpu().