ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: forces_inline.hpp File Reference
forces_inline.hpp File Reference
#include "topology.hpp"
#include "magnetic_non_p3m_methods.hpp"
#include "mdlc_correction.hpp"
#include "constraint.hpp"
#include "EspressoSystemInterface.hpp"
#include "forces.hpp"
#include "npt.hpp"
#include "p3m-dipolar.hpp"
#include "lj.hpp"
#include "ljgen.hpp"
#include "steppot.hpp"
#include "hertzian.hpp"
#include "gaussian.hpp"
#include "bmhtf-nacl.hpp"
#include "buckingham.hpp"
#include "soft_sphere.hpp"
#include "hat.hpp"
#include "tab.hpp"
#include "overlap.hpp"
#include "ljcos.hpp"
#include "ljcos2.hpp"
#include "ljangle.hpp"
#include "gb.hpp"
#include "fene.hpp"
#include "object-in-fluid/stretching_force.hpp"
#include "object-in-fluid/stretchlin_force.hpp"
#include "object-in-fluid/area_force_local.hpp"
#include "object-in-fluid/area_force_global.hpp"
#include "object-in-fluid/bending_force.hpp"
#include "object-in-fluid/volume_force.hpp"
#include "harmonic_dumbbell.hpp"
#include "harmonic.hpp"
#include "subt_lj.hpp"
#include "angle_harmonic.hpp"
#include "angle_cosine.hpp"
#include "angle_cossquare.hpp"
#include "angledist.hpp"
#include "debye_hueckel.hpp"
#include "endangledist.hpp"
#include "reaction_field.hpp"
#include "comforce.hpp"
#include "comfixed.hpp"
#include "molforces.hpp"
#include "morse.hpp"
#include "elc.hpp"
#include "collision.hpp"
#include "metadynamics.hpp"
#include "angle.hpp"
#include "hydrogen_bond.hpp"
#include "twist_stack.hpp"
#include "quartic.hpp"
#include "bonded_coulomb.hpp"
#include "actor/EwaldgpuForce_ShortRange.hpp"
#include "immersed_boundary/ibm_main.hpp"
#include "immersed_boundary/ibm_triel.hpp"
#include "immersed_boundary/ibm_volume_conservation.hpp"
#include "immersed_boundary/ibm_tribend.hpp"
Functions
void init_ghost_force (Particle *part)
initialize the forces for a ghost particle
void init_local_particle_force (Particle *part)
initialize the forces for a real particle
void force_calc ()
Calculate forces.
void calc_non_bonded_pair_force_parts (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double dist2, double force[3], double torque1[3]=NULL, double torque2[3]=NULL)
void calc_non_bonded_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double dist2, double force[3], double torque1[3]=NULL, double torque2[3]=NULL)
void calc_non_bonded_pair_force (Particle *p1, Particle *p2, double d[3], double dist, double dist2, double force[3])
void add_non_bonded_pair_force (Particle *p1, Particle *p2, double d[3], double dist, double dist2)
Calculate non bonded forces between a pair of particles.
void add_bonded_force (Particle *p1)
Calculate bonded forces for one particle.
void add_force (ParticleForce *F_to, ParticleForce *F_add)
add force to another.
void check_particle_force (Particle *part)
Function Documentation
void add_bonded_force (Particle * p1) inline
Calculate bonded forces for one particle.
Parameters
p1 particle for which to calculate forces
Definition at line 608 of file forces_inline.hpp.
References Particle::bl, BONDED_IA_ANGLE_COSINE, BONDED_IA_ANGLE_COSSQUARE, BONDED_IA_ANGLE_HARMONIC, BONDED_IA_ANGLE_OLD, BONDED_IA_ANGLEDIST, BONDED_IA_AREA_FORCE_GLOBAL, BONDED_IA_AREA_FORCE_LOCAL, BONDED_IA_BENDING_FORCE, BONDED_IA_BONDED_COULOMB, BONDED_IA_CG_DNA_BASEPAIR, BONDED_IA_CG_DNA_STACKING, BONDED_IA_DIHEDRAL, BONDED_IA_ENDANGLEDIST, BONDED_IA_FENE, BONDED_IA_HARMONIC, BONDED_IA_HARMONIC_DUMBBELL, BONDED_IA_IBM_TRIBEND, BONDED_IA_IBM_TRIEL, BONDED_IA_IBM_VOLUME_CONSERVATION, BONDED_IA_OVERLAPPED, bonded_ia_params, BONDED_IA_QUARTIC, BONDED_IA_RIGID_BOND, BONDED_IA_STRETCHING_FORCE, BONDED_IA_STRETCHLIN_FORCE, BONDED_IA_SUBT_LJ, BONDED_IA_TABULATED, BONDED_IA_VIRTUAL_BOND, BONDED_IA_VOLUME_FORCE, calc_angle_cosine_force(), calc_angle_cossquare_force(), calc_angle_force(), calc_angle_harmonic_force(), calc_angledist_force(), calc_area_force_local(), calc_bending_force(), calc_bonded_coulomb_pair_force(), calc_dihedral_force(), calc_endangledist_pair_force(), calc_fene_pair_force(), calc_harmonic_dumbbell_pair_force(), calc_harmonic_pair_force(), calc_hydrogen_bond_force(), calc_overlap_angle_force(), calc_overlap_bond_force(), calc_overlap_dihedral_force(), calc_quartic_pair_force(), calc_stretching_force_pair_force(), calc_stretchlin_force_pair_force(), calc_subt_lj_pair_force(), calc_tab_angle_force(), calc_tab_bond_force(), calc_tab_dihedral_force(), calc_twist_stack_force(), IntList::e, ParticleForce::f, Particle::f, get_mi_vector(), i, IBM_Tribend_CalcForce(), IBM_Triel_CalcForce(), ParticleProperties::identity, INTEG_METHOD_NPT_ISO, integ_switch, local_particles, nptiso, Bonded_ia_parameters::num, Bond_parameters::overlap, OVERLAP_BOND_ANGLE, OVERLAP_BOND_DIHEDRAL, OVERLAP_BOND_LENGTH, ParticlePosition::p, Particle::p, Bonded_ia_parameters::p, nptiso_struct::p_vir, Particle::r, runtimeError, Bond_parameters::tab, TAB_BOND_ANGLE, TAB_BOND_DIHEDRAL, TAB_BOND_LENGTH, ParticleForce::torque, Tabulated_bond_parameters::type, Overlap_bond_parameters::type, and Bonded_ia_parameters::type.
Referenced by build_verlet_lists_and_calc_verlet_ia(), calc_link_cell(), calculate_verlet_ia(), layered_calculate_ia(), and nsq_calculate_ia().
void add_force (ParticleForce * F_to, ParticleForce * F_add) inline
add force to another.
This is used when collecting ghost forces.
Definition at line 1017 of file forces_inline.hpp.
References ParticleForce::f, i, ROTATION, and ParticleForce::torque.
Referenced by add_forces_from_recv_buffer(), cell_cell_transfer(), and reduce_forces_sum().
void add_non_bonded_pair_force (Particle * p1, Particle * p2, double d[3], double dist, double dist2) inline
Calculate non bonded forces between a pair of particles.
Parameters
p1 pointer to particle 1.
p2 pointer to particle 2.
d vector between p1 and p2.
dist distance between p1 and p2.
dist2 distance squared between p1 and p2.
Definition at line 452 of file forces_inline.hpp.
References add_dh_coulomb_pair_force(), add_dpd_thermo_pair_force(), add_ewald_gpu_coulomb_pair_force(), add_inter_dpd_pair_force(), add_mmm1d_coulomb_pair_force(), add_mmm2d_coulomb_pair_force(), add_rf_coulomb_pair_force(), calc_non_bonded_pair_force(), collision_params, coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_EWALD_GPU, COULOMB_MMM1D, COULOMB_MMM2D, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, detect_collision(), DIPOLAR_MDLC_P3M, DIPOLAR_P3M, Coulomb_parameters::Dmethod, ParticleForce::f, Particle::f, FORCE_TRACE, get_ia_param(), ia_params, ParticleProperties::identity, INTEG_METHOD_NPT_ISO, integ_switch, Coulomb_parameters::method, Collision_parameters::mode, nptiso, Particle::p, nptiso_struct::p_vir, ParticleProperties::q, THERMO_DPD, THERMO_INTER_DPD, thermo_switch, this_node, ParticleForce::torque, and ParticleProperties::type.
Referenced by build_verlet_lists_and_calc_verlet_ia(), calc_link_cell(), calculate_verlet_ia(), layered_calculate_ia(), and nsq_calculate_ia().
void calc_non_bonded_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double dist2, double force[3], double torque1[3] = NULL, double torque2[3] = NULL) inline
Definition at line 423 of file forces_inline.hpp.
References calc_non_bonded_pair_force_parts(), and checkIfParticlesInteractViaMolCut().
Referenced by add_constraints_forces(), add_non_bonded_pair_force(), add_non_bonded_pair_virials(), calc_non_bonded_pair_force(), and get_nonbonded_interaction().
void calc_non_bonded_pair_force (Particle * p1, Particle * p2, double d[3], double dist, double dist2, double force[3]) inline
Definition at line 438 of file forces_inline.hpp.
References calc_non_bonded_pair_force(), get_ia_param(), ia_params, Particle::p, and ParticleProperties::type.
void calc_non_bonded_pair_force_parts (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double dist2, double force[3], double torque1[3] = NULL, double torque2[3] = NULL) inline
Definition at line 349 of file forces_inline.hpp.
References add_BMHTF_pair_force(), add_buck_pair_force(), add_gaussian_pair_force(), add_gb_pair_force(), add_hat_pair_force(), add_hertzian_pair_force(), add_interrf_pair_force(), add_lj_pair_force(), add_ljangle_pair_force(), add_ljcos2_pair_force(), add_ljcos_pair_force(), add_ljgen_pair_force(), add_morse_pair_force(), add_SmSt_pair_force(), add_soft_pair_force(), add_tabulated_pair_force(), ParticleProperties::mol_id, and Particle::p.
Referenced by calc_non_bonded_pair_force(), and calc_non_bonded_pair_force_from_partcfg().
void check_particle_force (Particle * part) inline
Definition at line 1027 of file forces_inline.hpp.
References ParticleForce::f, Particle::f, i, ParticleProperties::identity, isnan, Particle::p, runtimeError, and ParticleForce::torque.
Referenced by check_forces(), rescale_forces(), and rescale_forces_propagate_vel().
void force_calc () inline
Calculate forces.
A short list, what the function is doing:
Initialize forces with: friction_thermo_langevin (ghost forces with zero).
Calculate bonded interaction forces:
Loop all local particles (not the ghosts).
FENE
ANGLE (cos bend potential)
Calculate non-bonded short range interaction forces:
Loop all verlet lists of all cells.
Lennard-Jones.
Buckingham.
Real space part: Coulomb.
Ramp.
Calculate long range interaction forces:
Uses P3M_calc_kspace_forces
Definition at line 205 of file forces_inline.hpp.
References add_area_global_force(), add_volume_force(), build_verlet_lists_and_calc_verlet_ia(), calc_and_apply_mol_constraints(), calc_area_global(), calc_comfixed(), calc_comforce(), calc_link_cell(), calc_long_range_forces(), calc_particle_lattice_ia(), calc_volume(), calculate_verlet_ia(), cell_structure, CELL_STRUCTURE_DOMDEC, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, cells_update_ghosts(), CellStructure::collect_ghost_force_comm, copy_forces_from_GPU(), dd, distribute_mol_force(), espressoSystemInterface, forceActors, ghost_communicator(), handle_collisions(), i, IBM_VolumeConservation(), iccp3m_cfg, iccp3m_initialized, iccp3m_iteration(), init_forces(), init_forces_ghosts(), lattice_boltzmann_calc_shanchen_gpu(), LATTICE_LB, LATTICE_LB_GPU, lattice_switch, layered_calculate_ia(), lb_calc_particle_lattice_ia_gpu(), MAX_OBJECTS_IN_FLUID, meta_perform(), nsq_calculate_ia(), prepare_collision_queue(), rebuild_verletlist, recalc_forces, iccp3m_struct::set_flag, this_node, transfer_momentum_gpu, CellStructure::type, CellStructure::update_ghost_pos_comm, update_mol_vel_pos(), and DomainDecomposition::use_vList.
Referenced by integrate_sd(), and integrate_vv().
void init_ghost_force (Particle * part) inline
initialize the forces for a ghost particle
Definition at line 91 of file forces_inline.hpp.
References ParticleForce::f, Particle::f, ParticlePosition::quat, Particle::r, SQR(), and ParticleForce::torque.
Referenced by init_forces(), and init_forces_ghosts().
void init_local_particle_force (Particle * part) inline
initialize the forces for a real particle
Definition at line 117 of file forces_inline.hpp.
References ParticleProperties::ext_flag, ParticleProperties::ext_force, ParticleProperties::ext_torque, ParticleForce::f, Particle::f, ParticleParametersSwimming::f_swim, friction_thermo_langevin(), ParticleProperties::mass, Particle::p, PARTICLE_EXT_FORCE, PARTICLE_EXT_TORQUE, ParticlePosition::quat, ParticlePosition::quatu, Particle::r, SQR(), Particle::swim, ParticleParametersSwimming::swimming, THERMO_LANGEVIN, thermo_switch, and ParticleForce::torque.
Referenced by init_forces().