ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: galilei.cpp File Reference
galilei.cpp File Reference
#include "galilei.hpp"
#include "utils.hpp"
#include "cells.hpp"
#include "grid.hpp"
#include "initialize.hpp"
#include "forces.hpp"
Functions
void local_kill_particle_motion (int omega)
broadcasts reaction parameters and sets up an entry in the ia_params, so that the verlet radius is equal or bigger than the reaction range.
void local_kill_particle_forces (int torque)
void local_system_CMS (double *sdata)
void local_system_CMS_velocity (double *sdata)
void local_galilei_transform (double *sdata)
Variables
galilei_struct gal
Galilei parameters.
Function Documentation
void local_galilei_transform (double * sdata)
Definition at line 221 of file galilei.cpp.
References CellPList::cell, i, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleList::part, and ParticleMomentum::v.
Referenced by mpi_galilei_transform(), and mpi_galilei_transform_slave().
void local_kill_particle_forces (int torque)
Definition at line 64 of file galilei.cpp.
References CellPList::cell, ParticleForce::f, Particle::f, i, local_cells, CellPList::n, ParticleList::n, ParticleList::part, and ParticleForce::torque.
Referenced by mpi_kill_particle_forces(), and mpi_kill_particle_forces_slave().
void local_kill_particle_motion (int omega)
broadcasts reaction parameters and sets up an entry in the ia_params, so that the verlet radius is equal or bigger than the reaction range.
Definition at line 36 of file galilei.cpp.
References CellPList::cell, i, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleMomentum::omega, ParticleList::part, and ParticleMomentum::v.
Referenced by mpi_kill_particle_motion(), and mpi_kill_particle_motion_slave().
void local_system_CMS (double * sdata)
Definition at line 91 of file galilei.cpp.
References CellPList::cell, i, local_cells, ParticleProperties::mass, CellPList::n, ParticleList::n, Particle::p, ParticleList::part, and unfold_position().
Referenced by mpi_system_CMS(), and mpi_system_CMS_slave().
void local_system_CMS_velocity (double * sdata)
Definition at line 161 of file galilei.cpp.
References CellPList::cell, i, local_cells, Particle::m, ParticleProperties::mass, CellPList::n, ParticleList::n, Particle::p, ParticleList::part, and ParticleMomentum::v.
Referenced by mpi_system_CMS_velocity(), and mpi_system_CMS_velocity_slave().
Variable Documentation
galilei_struct gal
Galilei parameters.
Definition at line 32 of file galilei.cpp.
Referenced by mpi_galilei_transform(), mpi_system_CMS(), mpi_system_CMS_velocity(), tclcommand_system_CMS(), and tclcommand_system_CMS_velocity().