ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: galilei_tcl.cpp File Reference
galilei_tcl.cpp File Reference
#include "galilei.hpp"
#include "parser.hpp"
#include "utils.hpp"
#include "grid.hpp"
#include "communication.hpp"
#include "integrate.hpp"
Functions
int tcl_command_kill_particle_motion_print_usage (Tcl_Interp *interp)
int tcl_command_kill_particle_forces_print_usage (Tcl_Interp *interp)
int tcl_command_system_CMS_print_usage (Tcl_Interp *interp)
int tcl_command_system_CMS_velocity_print_usage (Tcl_Interp *interp)
int tcl_command_galilei_transform_print_usage (Tcl_Interp *interp)
int tclcommand_kill_particle_motion (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure to set up reactions
int tclcommand_kill_particle_forces (ClientData data, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_system_CMS (ClientData data, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_system_CMS_velocity (ClientData data, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_galilei_transform (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Function Documentation
int tcl_command_galilei_transform_print_usage (Tcl_Interp * interp)
Definition at line 68 of file galilei_tcl.cpp.
Referenced by tclcommand_galilei_transform().
int tcl_command_kill_particle_forces_print_usage (Tcl_Interp * interp)
Definition at line 44 of file galilei_tcl.cpp.
Referenced by tclcommand_kill_particle_forces().
int tcl_command_kill_particle_motion_print_usage (Tcl_Interp * interp)
Definition at line 36 of file galilei_tcl.cpp.
Referenced by tclcommand_kill_particle_motion().
int tcl_command_system_CMS_print_usage (Tcl_Interp * interp)
Definition at line 52 of file galilei_tcl.cpp.
Referenced by tclcommand_system_CMS().
int tcl_command_system_CMS_velocity_print_usage (Tcl_Interp * interp)
Definition at line 60 of file galilei_tcl.cpp.
Referenced by tclcommand_system_CMS_velocity().
int tclcommand_galilei_transform (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 196 of file galilei_tcl.cpp.
References ARG_IS_S_EXACT, mpi_galilei_transform(), and tcl_command_galilei_transform_print_usage().
Referenced by tcl_register_commands().
int tclcommand_kill_particle_forces (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 101 of file galilei_tcl.cpp.
References ARG_IS_S_EXACT, mpi_kill_particle_forces(), and tcl_command_kill_particle_forces_print_usage().
Referenced by tcl_register_commands().
int tclcommand_kill_particle_motion (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure to set up reactions
Definition at line 78 of file galilei_tcl.cpp.
References ARG_IS_S_EXACT, mpi_kill_particle_motion(), and tcl_command_kill_particle_motion_print_usage().
Referenced by tcl_register_commands().
int tclcommand_system_CMS (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 124 of file galilei_tcl.cpp.
References ARG_IS_S_EXACT, galilei_struct::cms, fold_position(), gal, mpi_system_CMS(), and tcl_command_system_CMS_print_usage().
Referenced by tcl_register_commands().
int tclcommand_system_CMS_velocity (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 172 of file galilei_tcl.cpp.
References ARG_IS_S_EXACT, galilei_struct::cms_vel, gal, mpi_system_CMS_velocity(), tcl_command_system_CMS_velocity_print_usage(), and time_step.
Referenced by tcl_register_commands().