ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ghmc_tcl.hpp File Reference
ghmc_tcl.hpp File Reference
This file contains the tcl interface for the GHMC (Generalized Hybrid MOnte Carlo) thermostat.
#include <tcl.h>
Functions
Exported Functions
int tclcommand_ghmc (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure to get ghmc statistics.
int tclcommand_save_state (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure to save the system state.
int tclcommand_load_state (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure to load last saved system state.
Detailed Description
This file contains the tcl interface for the GHMC (Generalized Hybrid MOnte Carlo) thermostat.
Definition in file ghmc_tcl.hpp.
Function Documentation
int tclcommand_ghmc (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure to get ghmc statistics.
USAGE: ghmc <statistics> see also tclcommand_ghmc
Definition at line 53 of file ghmc_tcl.cpp.
References ARG1_IS_S, INTEG_TRACE, tclcommand_ghmc_print_statistics(), tclcommand_ghmc_print_status(), tclcommand_ghmc_print_usage(), THERMO_TRACE, and this_node.
Referenced by tcl_register_commands().
int tclcommand_load_state (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure to load last saved system state.
USAGE: load_state see also tclcommand_load_state
Definition at line 102 of file ghmc_tcl.cpp.
References CELL_GLOBAL_EXCHANGE, cells_resort_particles(), INTEG_TRACE, invalidate_obs(), load_last_state(), tclcommand_ghmc_print_usage(), and this_node.
Referenced by tcl_register_commands().
int tclcommand_save_state (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure to save the system state.
USAGE: save_state see also tclcommand_save_state
Definition at line 83 of file ghmc_tcl.cpp.
References INTEG_TRACE, save_last_state(), tclcommand_ghmc_print_usage(), and this_node.
Referenced by tcl_register_commands().