ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ghmc.cpp File Reference
ghmc.cpp File Reference
For more information see ghmc.hpp.
#include <cmath>
#include "utils.hpp"
#include "integrate.hpp"
#include "thermostat.hpp"
#include "ghmc.hpp"
#include "random.hpp"
#include "particle_data.hpp"
#include "communication.hpp"
#include "energy.hpp"
#include "cells.hpp"
#include "virtual_sites.hpp"
#include "statistics.hpp"
Functions
Privat Functions
void hamiltonian_calc (int ekin_update_flag)
double calc_local_temp ()
void calc_kinetic (double *ek_trans, double *ek_rot)
void simple_momentum_update ()
void partial_momentum_update ()
void tscale_momentum_update ()
void momentum_flip ()
void save_last_state ()
save particles state
void load_last_state ()
load particles last saved state
void ghmc_momentum_update ()
momentum update step of ghmc
Exported Functions
void thermo_init_ghmc ()
initilize global thermostat parameters
void ghmc_init ()
initilize ghmc during integration
void ghmc_close ()
ghmc close proc
void ghmc_mc ()
ghmc MC step
Variables
int ghmc_mflip = GHMC_MFLIP_OFF
int ghmc_tscale = GHMC_TSCALE_OFF
int ghmc_mc_res
int ghmc_att
int ghmc_acc
double cosp
double sinp
double beta
Ghmc ghmcdata = { 0, 0, 0.0, 0.0}
Structure containing the ghmc relevant information.
Detailed Description
For more information see ghmc.hpp.
Definition in file ghmc.cpp.
Function Documentation
void calc_kinetic (double * ek_trans, double * ek_rot)
Definition at line 205 of file ghmc.cpp.
References CellPList::cell, comm_cart, i, ifParticleIsVirtual(), local_cells, MPI_Allreduce(), MPI_DOUBLE, MPI_IN_PLACE, MPI_SUM, CellPList::n, ParticleList::n, Particle::p, ParticleList::part, PMASS, ParticleProperties::rinertia, SQR(), and time_step.
Referenced by hamiltonian_calc(), and tscale_momentum_update().
double calc_local_temp ()
Definition at line 175 of file ghmc.cpp.
References CellPList::cell, i, local_cells, CellPList::n, ParticleList::n, ParticleList::part, PMASS, SQR(), and time_step.
void ghmc_close ()
ghmc close proc
Definition at line 459 of file ghmc.cpp.
References Ghmc::acc, Ghmc::att, ghmc_acc, ghmc_att, INTEG_TRACE, and this_node.
Referenced by integrate_sd(), and integrate_vv().
void ghmc_init ()
initilize ghmc during integration
Definition at line 449 of file ghmc.cpp.
References Ghmc::acc, Ghmc::att, INTEG_TRACE, save_last_state(), and this_node.
Referenced by integrate_sd(), and integrate_vv().
void ghmc_mc ()
ghmc MC step
Definition at line 469 of file ghmc.cpp.
References Ghmc::acc, Ghmc::att, beta, CELL_GLOBAL_EXCHANGE, cells_resort_particles(), d_random(), FIELD_GHMC_RES, ghmc_mc_res, ghmc_mflip, GHMC_MFLIP_ON, GHMC_MFLIP_RAND, GHMC_MOVE_ACCEPT, GHMC_MOVE_REJECT, hamiltonian_calc(), Ghmc::hmlt_new, Ghmc::hmlt_old, INTEG_TRACE, invalidate_obs(), load_last_state(), momentum_flip(), mpi_bcast_parameter(), save_last_state(), and this_node.
Referenced by integrate_sd(), and integrate_vv().
void ghmc_momentum_update ()
momentum update step of ghmc
Definition at line 252 of file ghmc.cpp.
References ghmc_tscale, GHMC_TSCALE_ON, hamiltonian_calc(), INTEG_TRACE, partial_momentum_update(), this_node, and tscale_momentum_update().
Referenced by integrate_sd(), and integrate_vv().
void hamiltonian_calc (int ekin_update_flag)
Definition at line 135 of file ghmc.cpp.
References calc_kinetic(), Observable_stat::data, DoubleList::e, Ghmc::hmlt_new, Ghmc::hmlt_old, i, init_energies(), Observable_stat::init_status, INTEG_TRACE, master_energy_calc(), DoubleList::n, this_node, and total_energy.
Referenced by ghmc_mc(), and ghmc_momentum_update().
void load_last_state ()
load particles last saved state
Definition at line 110 of file ghmc.cpp.
References CellPList::cell, i, local_cells, CellPList::n, ParticleList::n, and ParticleList::part.
Referenced by ghmc_mc(), and tclcommand_load_state().
void momentum_flip ()
Definition at line 400 of file ghmc.cpp.
References CellPList::cell, i, INTEG_TRACE, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleMomentum::omega, ParticleList::part, this_node, and ParticleMomentum::v.
Referenced by ghmc_mc().
void partial_momentum_update ()
Definition at line 369 of file ghmc.cpp.
References CellPList::cell, cosp, gaussian_random(), i, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleMomentum::omega, ParticleList::part, PMASS, sinp, temperature, time_step, and ParticleMomentum::v.
Referenced by ghmc_momentum_update().
void save_last_state ()
save particles state
Definition at line 85 of file ghmc.cpp.
References CellPList::cell, i, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleList::part, and Particle::r.
Referenced by ghmc_init(), ghmc_mc(), tclcommand_save_state(), and tscale_momentum_update().
void simple_momentum_update ()
Definition at line 332 of file ghmc.cpp.
References CellPList::cell, gaussian_random(), i, ifParticleIsVirtual(), local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleMomentum::omega, ParticleList::part, PMASS, temperature, time_step, and ParticleMomentum::v.
Referenced by tscale_momentum_update().
void thermo_init_ghmc ()
initilize global thermostat parameters
Definition at line 434 of file ghmc.cpp.
References beta, cosp, ghmc_acc, ghmc_att, ghmc_phi, Ghmc::hmlt_new, Ghmc::hmlt_old, sinp, temperature, THERMO_TRACE, and this_node.
Referenced by thermo_init().
void tscale_momentum_update ()
Definition at line 271 of file ghmc.cpp.
References calc_kinetic(), CellPList::cell, cosp, i, ifParticleIsVirtual(), Particle::l, local_cells, Particle::m, ParticleLocal::m_ls, CellPList::n, ParticleList::n, n_part, ParticleMomentum::omega, ParticleList::part, save_last_state(), simple_momentum_update(), sinp, temperature, and ParticleMomentum::v.
Referenced by ghmc_momentum_update().
Variable Documentation
double beta
Definition at line 54 of file ghmc.cpp.
Referenced by ghmc_mc(), sd_gmres_solver(), sd_iterative_solver(), sd_real_integrate(), and thermo_init_ghmc().
double cosp
Definition at line 52 of file ghmc.cpp.
Referenced by partial_momentum_update(), thermo_init_ghmc(), and tscale_momentum_update().
int ghmc_acc
Definition at line 50 of file ghmc.cpp.
Referenced by ghmc_close(), tclcommand_ghmc_print_statistics(), and thermo_init_ghmc().
int ghmc_att
Definition at line 50 of file ghmc.cpp.
Referenced by ghmc_close(), tclcommand_ghmc_print_statistics(), and thermo_init_ghmc().
int ghmc_mc_res
Definition at line 46 of file ghmc.cpp.
Referenced by ghmc_mc().
int ghmc_mflip = GHMC_MFLIP_OFF
Definition at line 42 of file ghmc.cpp.
Referenced by ghmc_mc(), tclcommand_thermostat_parse_ghmc(), tclcommand_thermostat_parse_off(), and tclcommand_thermostat_print_all().
int ghmc_tscale = GHMC_TSCALE_OFF
Definition at line 44 of file ghmc.cpp.
Referenced by ghmc_momentum_update(), tclcommand_thermostat_parse_ghmc(), tclcommand_thermostat_parse_off(), and tclcommand_thermostat_print_all().
Ghmc ghmcdata = { 0, 0, 0.0, 0.0}
Structure containing the ghmc relevant information.
Definition at line 56 of file ghmc.cpp.
Referenced by tclcommand_ghmc_print_status().
double sinp
Definition at line 52 of file ghmc.cpp.
Referenced by partial_momentum_update(), thermo_init_ghmc(), and tscale_momentum_update().