ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ghmc.hpp File Reference
ghmc.hpp File Reference
This file contains the implementation of the GHMC (Generalized Hybrid Monte Carlo) thermostat.
Data Structures
struct Ghmc
Data structure describing a slab and the velocities occuring their in.
Macros
#define GHMC_MFLIP_OFF 0
#define GHMC_MFLIP_ON 1
#define GHMC_MFLIP_RAND 2
#define GHMC_TSCALE_OFF 0
#define GHMC_TSCALE_ON 1
#define GHMC_MOVE_REJECT 0
#define GHMC_MOVE_ACCEPT 1
Functions
Exported Functions
void thermo_init_ghmc ()
initilize global thermostat parameters
void ghmc_init ()
initilize ghmc during integration
void ghmc_momentum_update ()
momentum update step of ghmc
void ghmc_mc ()
ghmc MC step
void ghmc_close ()
ghmc close proc
void save_last_state ()
save particles state
void load_last_state ()
load particles last saved state
Variables
int ghmc_mflip
int ghmc_tscale
int ghmc_att
int ghmc_acc
int ghmc_mc_res
Exported Variables
Ghmc ghmcdata
Structure containing the ghmc relevant information.
Detailed Description
This file contains the implementation of the GHMC (Generalized Hybrid Monte Carlo) thermostat.
Definition in file ghmc.hpp.
Macro Definition Documentation
#define GHMC_MFLIP_OFF 0
Definition at line 29 of file ghmc.hpp.
Referenced by tclcommand_thermostat_parse_ghmc(), tclcommand_thermostat_parse_off(), and tclcommand_thermostat_print_all().
#define GHMC_MFLIP_ON 1
Definition at line 30 of file ghmc.hpp.
Referenced by ghmc_mc(), tclcommand_thermostat_parse_ghmc(), and tclcommand_thermostat_print_all().
#define GHMC_MFLIP_RAND 2
Definition at line 31 of file ghmc.hpp.
Referenced by ghmc_mc(), tclcommand_thermostat_parse_ghmc(), and tclcommand_thermostat_print_all().
#define GHMC_MOVE_ACCEPT 1
Definition at line 37 of file ghmc.hpp.
Referenced by ghmc_mc().
#define GHMC_MOVE_REJECT 0
Definition at line 36 of file ghmc.hpp.
Referenced by ghmc_mc().
#define GHMC_TSCALE_OFF 0
Definition at line 33 of file ghmc.hpp.
Referenced by tclcommand_thermostat_parse_ghmc(), and tclcommand_thermostat_parse_off().
#define GHMC_TSCALE_ON 1
Definition at line 34 of file ghmc.hpp.
Referenced by ghmc_momentum_update(), tclcommand_thermostat_parse_ghmc(), and tclcommand_thermostat_print_all().
Function Documentation
void ghmc_close ()
ghmc close proc
Definition at line 459 of file ghmc.cpp.
References Ghmc::acc, Ghmc::att, ghmc_acc, ghmc_att, INTEG_TRACE, and this_node.
Referenced by integrate_sd(), and integrate_vv().
void ghmc_init ()
initilize ghmc during integration
Definition at line 449 of file ghmc.cpp.
References Ghmc::acc, Ghmc::att, INTEG_TRACE, save_last_state(), and this_node.
Referenced by integrate_sd(), and integrate_vv().
void ghmc_mc ()
ghmc MC step
Definition at line 469 of file ghmc.cpp.
References Ghmc::acc, Ghmc::att, beta, CELL_GLOBAL_EXCHANGE, cells_resort_particles(), d_random(), FIELD_GHMC_RES, ghmc_mc_res, ghmc_mflip, GHMC_MFLIP_ON, GHMC_MFLIP_RAND, GHMC_MOVE_ACCEPT, GHMC_MOVE_REJECT, hamiltonian_calc(), Ghmc::hmlt_new, Ghmc::hmlt_old, INTEG_TRACE, invalidate_obs(), load_last_state(), momentum_flip(), mpi_bcast_parameter(), save_last_state(), and this_node.
Referenced by integrate_sd(), and integrate_vv().
void ghmc_momentum_update ()
momentum update step of ghmc
Definition at line 252 of file ghmc.cpp.
References ghmc_tscale, GHMC_TSCALE_ON, hamiltonian_calc(), INTEG_TRACE, partial_momentum_update(), this_node, and tscale_momentum_update().
Referenced by integrate_sd(), and integrate_vv().
void load_last_state ()
load particles last saved state
Definition at line 110 of file ghmc.cpp.
References CellPList::cell, i, local_cells, CellPList::n, ParticleList::n, and ParticleList::part.
Referenced by ghmc_mc(), and tclcommand_load_state().
void save_last_state ()
save particles state
Definition at line 85 of file ghmc.cpp.
References CellPList::cell, i, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleList::part, and Particle::r.
Referenced by ghmc_init(), ghmc_mc(), tclcommand_save_state(), and tscale_momentum_update().
void thermo_init_ghmc ()
initilize global thermostat parameters
Definition at line 434 of file ghmc.cpp.
References beta, cosp, ghmc_acc, ghmc_att, ghmc_phi, Ghmc::hmlt_new, Ghmc::hmlt_old, sinp, temperature, THERMO_TRACE, and this_node.
Referenced by thermo_init().
Variable Documentation
int ghmc_acc
Definition at line 50 of file ghmc.cpp.
Referenced by ghmc_close(), tclcommand_ghmc_print_statistics(), and thermo_init_ghmc().
int ghmc_att
Definition at line 50 of file ghmc.cpp.
Referenced by ghmc_close(), tclcommand_ghmc_print_statistics(), and thermo_init_ghmc().
int ghmc_mc_res
Definition at line 46 of file ghmc.cpp.
Referenced by ghmc_mc().
int ghmc_mflip
Definition at line 42 of file ghmc.cpp.
Referenced by ghmc_mc(), tclcommand_thermostat_parse_ghmc(), tclcommand_thermostat_parse_off(), and tclcommand_thermostat_print_all().
int ghmc_tscale
Definition at line 44 of file ghmc.cpp.
Referenced by ghmc_momentum_update(), tclcommand_thermostat_parse_ghmc(), tclcommand_thermostat_parse_off(), and tclcommand_thermostat_print_all().
Ghmc ghmcdata
Structure containing the ghmc relevant information.
Definition at line 56 of file ghmc.cpp.
Referenced by tclcommand_ghmc_print_status().