ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ghosts.cpp File Reference
ghosts.cpp File Reference
Ghost particles and particle exchange.
#include <mpi.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <algorithm>
#include "utils.hpp"
#include "ghosts.hpp"
#include "global.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "particle_data.hpp"
#include "forces_inline.hpp"
Macros
#define REQ_GHOST_SEND 100
Tag for communication in ghost_comm.
Functions
void prepare_comm (GhostCommunicator *comm, int data_parts, int num)
Initialize a communicator.
void free_comm (GhostCommunicator *comm)
Free a communicator.
int calc_transmit_size (GhostCommunication *gc, int data_parts)
void prepare_send_buffer (GhostCommunication *gc, int data_parts)
static void prepare_ghost_cell (Cell *cell, int size)
void prepare_recv_buffer (GhostCommunication *gc, int data_parts)
void put_recv_buffer (GhostCommunication *gc, int data_parts)
void add_forces_from_recv_buffer (GhostCommunication *gc)
void cell_cell_transfer (GhostCommunication *gc, int data_parts)
void reduce_forces_sum (void *add, void *to, int *len, MPI_Datatype *type)
static int is_send_op (int comm_type, int node)
static int is_recv_op (int comm_type, int node)
void ghost_communicator (GhostCommunicator *gc)
do a ghost communication
void ghost_init ()
Initialize ghosts.
void invalidate_ghosts ()
Go through ghost_cells and remove the ghost entries from local_particles.
Variables
static int n_s_buffer = 0
static int max_s_buffer = 0
static char * s_buffer = NULL
send buffer.
std::vector< int > s_bondbuffer
static int n_r_buffer = 0
static int max_r_buffer = 0
static char * r_buffer = NULL
recv buffer.
std::vector< int > r_bondbuffer
static MPI_Op MPI_FORCES_SUM
int ghosts_have_v = 0
whether the ghosts should also have velocity information, e.
Detailed Description
Ghost particles and particle exchange.
For more information on ghosts, see ghosts.hpp
Definition in file ghosts.cpp.
Macro Definition Documentation
#define REQ_GHOST_SEND 100
Tag for communication in ghost_comm.
Definition at line 42 of file ghosts.cpp.
Referenced by ghost_communicator().
Function Documentation
void add_forces_from_recv_buffer (GhostCommunication * gc)
Definition at line 399 of file ghosts.cpp.
References add_force(), errexit(), Particle::f, ParticleList::n, GhostCommunication::n_part_lists, n_r_buffer, ParticleList::part, GhostCommunication::part_lists, r_buffer, and this_node.
Referenced by ghost_communicator().
int calc_transmit_size (GhostCommunication * gc, int data_parts)
Definition at line 93 of file ghosts.cpp.
References GHOSTTRANS_COUPLING, GHOSTTRANS_FORCE, GHOSTTRANS_MOMENTUM, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, GHOSTTRANS_SWIMMING, ParticleList::n, GhostCommunication::n_part_lists, and GhostCommunication::part_lists.
Referenced by ghost_communicator(), prepare_recv_buffer(), and prepare_send_buffer().
void cell_cell_transfer (GhostCommunication * gc, int data_parts)
Definition at line 424 of file ghosts.cpp.
References add_force(), Particle::bl, box_l, DomainDecomposition::cell_size, dd, IntList::e, Particle::el, Particle::f, GHOST_TRACE, GHOSTTRANS_COUPLING, GHOSTTRANS_FORCE, GHOSTTRANS_MOMENTUM, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_POSSHFTD, GHOSTTRANS_PROPRTS, GHOSTTRANS_SWIMMING, i, Particle::lc, lees_edwards_rate, Particle::m, my_left, ParticleList::myIndex, IntList::n, ParticleList::n, GhostCommunication::n_part_lists, ParticlePosition::p, Particle::p, ParticleList::part, GhostCommunication::part_lists, prepare_ghost_cell(), Particle::r, realloc_intlist(), GhostCommunication::shift, Particle::swim, this_node, GhostCommunication::type, and ParticleMomentum::v.
Referenced by ghost_communicator().
void free_comm (GhostCommunicator * comm)
Free a communicator.
Definition at line 85 of file ghosts.cpp.
References GhostCommunicator::comm, free, GHOST_TRACE, GhostCommunicator::num, GhostCommunication::part_lists, and this_node.
Referenced by dd_topology_release(), layered_topology_release(), and nsq_topology_release().
void ghost_communicator (GhostCommunicator * gc)
do a ghost communication
Definition at line 533 of file ghosts.cpp.
References add_forces_from_recv_buffer(), calc_transmit_size(), cell_cell_transfer(), GhostCommunicator::comm, comm_cart, GhostCommunicator::data_parts, errexit(), GHOST_BCST, GHOST_JOBMASK, GHOST_LOCL, GHOST_PREFETCH, GHOST_PSTSTORE, GHOST_RDCE, GHOST_RECV, GHOST_SEND, GHOST_TRACE, GHOSTTRANS_FORCE, GHOSTTRANS_PROPRTS, is_recv_op(), is_send_op(), MPI_Bcast(), MPI_BYTE, MPI_FORCES_SUM, MPI_INT, MPI_Recv(), MPI_Reduce(), MPI_Send(), n_r_buffer, n_s_buffer, GhostCommunication::node, GhostCommunicator::num, prepare_recv_buffer(), prepare_send_buffer(), put_recv_buffer(), r_bondbuffer, r_buffer, REQ_GHOST_SEND, s_bondbuffer, s_buffer, GhostCommunication::shift, this_node, and GhostCommunication::type.
Referenced by calc_particle_lattice_ia(), cells_resort_particles(), cells_update_ghosts(), correct_pos_shake(), correct_vel_shake(), force_calc(), IBM_ForcesIntoFluid_CPU(), integrate_sd(), integrate_vv(), and ParticleVelocitiesFromLB_CPU().
void ghost_init ()
Initialize ghosts.
Definition at line 700 of file ghosts.cpp.
References MPI_FORCES_SUM, MPI_Op_create(), and reduce_forces_sum().
Referenced by on_program_start().
void invalidate_ghosts ()
Go through ghost_cells and remove the ghost entries from local_particles.
Part of dd_exchange_and_sort_particles.
Definition at line 707 of file ghosts.cpp.
References CellPList::cell, ghost_cells, ParticleProperties::identity, local_particles, CellPList::n, ParticleList::n, Particle::p, and ParticleList::part.
Referenced by cells_re_init(), and cells_resort_particles().
static int is_recv_op (int comm_type, int node) static
Definition at line 526 of file ghosts.cpp.
References GHOST_BCST, GHOST_RDCE, GHOST_RECV, and this_node.
Referenced by ghost_communicator().
static int is_send_op (int comm_type, int node) static
Definition at line 520 of file ghosts.cpp.
References GHOST_BCST, GHOST_RDCE, GHOST_SEND, and this_node.
Referenced by ghost_communicator().
void prepare_comm (GhostCommunicator * comm, int data_parts, int num)
Initialize a communicator.
Definition at line 66 of file ghosts.cpp.
References GhostCommunicator::comm, GhostCommunicator::data_parts, GHOST_TRACE, ghosts_have_v, GHOSTTRANS_MOMENTUM, GHOSTTRANS_POSITION, i, malloc, GhostCommunicator::num, GhostCommunication::shift, and this_node.
Referenced by dd_prepare_comm(), layered_prepare_comm(), le_dd_prepare_comm(), and nsq_prepare_comm().
static void prepare_ghost_cell (Cell * cell, int size) static
Definition at line 237 of file ghosts.cpp.
References Particle::bl, IntList::e, Particle::el, free_particle(), ParticleLocal::ghost, Particle::l, IntList::max, IntList::n, ParticleList::n, ParticleList::part, and realloc_particlelist().
Referenced by cell_cell_transfer(), and put_recv_buffer().
void prepare_recv_buffer (GhostCommunication * gc, int data_parts)
Definition at line 273 of file ghosts.cpp.
References calc_transmit_size(), GHOST_TRACE, max_r_buffer, n_r_buffer, GhostCommunication::node, r_buffer, realloc, and this_node.
Referenced by ghost_communicator().
void prepare_send_buffer (GhostCommunication * gc, int data_parts)
Definition at line 137 of file ghosts.cpp.
References Particle::bl, calc_transmit_size(), IntList::e, Particle::el, errexit(), Particle::f, GHOST_TRACE, GHOSTTRANS_COUPLING, GHOSTTRANS_FORCE, GHOSTTRANS_MOMENTUM, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_POSSHFTD, GHOSTTRANS_PROPRTS, GHOSTTRANS_SWIMMING, i, Particle::lc, Particle::m, max_s_buffer, IntList::n, ParticleList::n, GhostCommunication::n_part_lists, n_s_buffer, GhostCommunication::node, ParticlePosition::p, Particle::p, ParticleList::part, GhostCommunication::part_lists, Particle::r, realloc, s_bondbuffer, s_buffer, GhostCommunication::shift, Particle::swim, and this_node.
Referenced by ghost_communicator().
void put_recv_buffer (GhostCommunication * gc, int data_parts)
Definition at line 285 of file ghosts.cpp.
References Particle::bl, box_l, DomainDecomposition::cell_size, dd, IntList::e, Particle::el, errexit(), Particle::f, GHOST_TRACE, GHOSTTRANS_COUPLING, GHOSTTRANS_FORCE, GHOSTTRANS_MOMENTUM, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, GHOSTTRANS_SWIMMING, ParticleProperties::identity, Particle::lc, lees_edwards_rate, local_particles, Particle::m, my_left, ParticleList::myIndex, IntList::n, ParticleList::n, GhostCommunication::n_part_lists, n_r_buffer, GhostCommunication::node, ParticlePosition::p, Particle::p, ParticleList::part, GhostCommunication::part_lists, prepare_ghost_cell(), Particle::r, r_bondbuffer, r_buffer, realloc_intlist(), GhostCommunication::shift, Particle::swim, this_node, and ParticleMomentum::v.
Referenced by ghost_communicator().
void reduce_forces_sum (void * add, void * to, int * len, MPI_Datatype * type)
Definition at line 504 of file ghosts.cpp.
References add_force(), errexit(), i, MPI_BYTE, and this_node.
Referenced by ghost_init().
Variable Documentation
int ghosts_have_v = 0
whether the ghosts should also have velocity information, e.
g. for DPD or RATTLE. You need this whenever you need the relative velocity of two particles. NO CHANGES OF THIS VALUE OUTSIDE OF on_ghost_flags_change !!!!
Definition at line 64 of file ghosts.cpp.
Referenced by on_ghost_flags_change(), and prepare_comm().
int max_r_buffer = 0 static
Definition at line 52 of file ghosts.cpp.
Referenced by prepare_recv_buffer().
int max_s_buffer = 0 static
Definition at line 45 of file ghosts.cpp.
Referenced by prepare_send_buffer().
MPI_Op MPI_FORCES_SUM static
Definition at line 58 of file ghosts.cpp.
Referenced by ghost_communicator(), and ghost_init().
int n_r_buffer = 0 static
Definition at line 51 of file ghosts.cpp.
Referenced by add_forces_from_recv_buffer(), ghost_communicator(), prepare_recv_buffer(), and put_recv_buffer().
int n_s_buffer = 0 static
Definition at line 44 of file ghosts.cpp.
Referenced by ghost_communicator(), and prepare_send_buffer().
std::vector<int> r_bondbuffer
Definition at line 56 of file ghosts.cpp.
Referenced by ghost_communicator(), and put_recv_buffer().
char* r_buffer = NULL static
recv buffer.
Just grows, which should be ok
Definition at line 54 of file ghosts.cpp.
Referenced by add_forces_from_recv_buffer(), ghost_communicator(), halo_communication(), lb_check_halo_regions(), prepare_recv_buffer(), and put_recv_buffer().
std::vector<int> s_bondbuffer
Definition at line 49 of file ghosts.cpp.
Referenced by ghost_communicator(), and prepare_send_buffer().
char* s_buffer = NULL static
send buffer.
Just grows, which should be ok
Definition at line 47 of file ghosts.cpp.
Referenced by ghost_communicator(), halo_communication(), lb_check_halo_regions(), and prepare_send_buffer().