ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: global_tcl.hpp File Reference
global_tcl.hpp File Reference
#include "parser.hpp"
Typedefs
typedef int(SetCallback) (Tcl_Interp *interp, void *data)
Function signature for the write callback procedures for global variables.
Functions
int tclcommand_setmd (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implements the Tcl command setmd. It allows to modify simulation parameters.
void register_global_callback (int field, SetCallback *callback)
Register a global variable, should be used only in register_global_variables.
int tclcallback_warnings (Tcl_Interp *interp, void *data)
Callback for warning settings.
Typedef Documentation
typedef int(SetCallback) (Tcl_Interp *interp, void *data)
Function signature for the write callback procedures for global variables.
Definition at line 30 of file global_tcl.hpp.
Function Documentation
void register_global_callback (int field, SetCallback * callback)
Register a global variable, should be used only in register_global_variables.
Definition at line 66 of file global_tcl.cpp.
References callbacks, n_callbacks, realloc, and tclcallback_ro().
Referenced by tcl_register_global_variables().
int tclcallback_warnings (Tcl_Interp * interp, void * data)
Callback for warning settings.
Definition at line 53 of file global_tcl.cpp.
References warnings.
Referenced by tcl_register_global_variables().
int tclcommand_setmd (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implements the Tcl command setmd. It allows to modify simulation parameters.
Definition at line 78 of file global_tcl.cpp.
References Datafield::data, Datafield::dimension, fields, find_callback(), gather_runtime_errors(), i, MAX_DIMENSION, Datafield::min_length, TYPE_BOOL, TYPE_DOUBLE, and TYPE_INT.
Referenced by tcl_register_commands().