ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: grid.hpp File Reference
grid.hpp File Reference
Domain decomposition for parallel computing.
#include "utils.hpp"
#include <climits>
#include "communication.hpp"
#include "errorhandling.hpp"
Macros
#define PERIODIC(coord) (periodic & (1L << coord))
Macro that tests for a coordinate being periodic or not.
Functions
Exported Functions
void init_node_grid ()
Make sure that the node grid is set, eventually determine one automatically.
int node_grid_is_set ()
return wether node grid was set.
void map_node_array (int node, int pos[3])
node mapping: array -> node.
int map_array_node (int pos[3])
node mapping: node -> array.
int map_position_node_array (double pos[3])
map a spatial position to the node grid
int calc_node_neighbors (int node)
fill neighbor lists of node.
void grid_changed_n_nodes ()
called from mpi_bcast_parameter .
void grid_changed_box_l ()
called from mpi_bcast_parameter .
void calc_minimal_box_dimensions ()
Calculates the smallest box and local box dimensions for periodic directions.
void calc_2d_grid (int n, int grid[3])
calculate most square 2d grid.
int map_3don2d_grid (int g3d[3], int g2d[3], int mult[3])
calculate 'best' mapping between a 2d and 3d grid.
void rescale_boxl (int dir, double d_new)
rescales the box in dimension 'dir' to the new value 'd_new', and rescales the particles accordingly
void get_mi_vector (double res[3], double a[3], double b[3])
get the minimal distance vector of two vectors in the current bc.
void fold_coordinate (double pos[3], double vel[3], int image_box[3], int dir)
fold a coordinate to primary simulation box, including velocity (in case of LEES_EDWARDS, the velocity depends on the image we are in).
void fold_coordinate (double pos[3], int image_box[3], int dir)
fold a coordinate to primary simulation box, not caring about velocities.
void fold_position (double pos[3], double vel[3], int image_box[3])
fold particle coordinates to primary simulation box.
void fold_position (double pos[3], int image_box[3])
fold particle coordinates to primary simulation box.
void unfold_position (double pos[3], double vel[3], int image_box[3])
unfold coordinates to physical position.
void unfold_position (double pos[3], int image_box[3])
unfold coordinates to physical position.
Variables
Exported Variables
int node_grid [3]
The number of nodes in each spatial dimension.
int node_pos [3]
position of node in node grid
int * node_neighbors
the nearest neighbors of a node in the node grid.
int * node_neighbor_lr
int * node_neighbor_wrap
int my_neighbor_count
the number of nearest neighbors of a node in the node grid.
int boundary [6]
where to fold particles that leave local box in direction i.
int periodic
Flags for all three dimensions wether pbc are applied (default).
double box_l [3]
Simulation box dimensions.
double box_l_i [3]
1 / box dimensions.
double min_box_l
Smallest simulation box dimension (box_l).
double local_box_l [3]
Dimensions of the box a single node is responsible for.
double min_local_box_l
Smallest local simulation box dimension (local_box_l).
double my_left [3]
Left (bottom, front) corner of this nodes local box.
double my_right [3]
Right (top, back) corner of this nodes local box.
Detailed Description
Domain decomposition for parallel computing.
The primary simulation box is divided into orthogonal rectangular subboxes which are assigned to the different nodes (or processes or threads if you want). This grid is described in node_grid. Each node has a number this_node and a position node_pos in that grid. Each node has also 6 nearest neighbors node_neighbors which are necessary for the communication between the nodes (see also ghosts.cpp and p3m.cpp for more details about the communication.
For the 6 directionswe have the following convention:
Convention for the order of the directions
The Figure illustrates the direction convetion used for arrays with 6 (e.g. node_neighbors, boundary) and 3 entries (e.g node_grid, box_l , my_left,...).
For more information on the domain decomposition, see grid.c.
Definition in file grid.hpp.
Macro Definition Documentation
#define PERIODIC (coord) (periodic & (1L << coord))
Macro that tests for a coordinate being periodic or not.
Definition at line 54 of file grid.hpp.
Referenced by add_ljangle_pair_force(), analyze_fold_molecules(), check_particle_consistency(), check_particles(), dd_append_particles(), dd_exchange_and_sort_particles(), dd_position_to_cell(), dd_prepare_comm(), dd_save_position_to_cell(), dd_update_communicators_w_boxl(), fold_coordinate(), get_mi_vector(), get_mi_vector_const(), layered_get_mi_vector(), layered_topology_init(), lb_check_halo_regions(), ljangle_pair_energy(), maggs_sanity_checks(), magnetic_dipolar_direct_sum_calculations(), mdlc_sanity_checks(), MMM1D_sanity_checks(), MMM2D_sanity_checks(), prepare_halo_communication(), and update_mol_pos_particle().
Function Documentation
void calc_2d_grid (int n, int grid[3])
calculate most square 2d grid.
Definition at line 307 of file grid.cpp.
References i.
void calc_minimal_box_dimensions ()
Calculates the smallest box and local box dimensions for periodic directions.
This is needed to check if the interaction ranges are compatible with the box dimensions and the node grid. see also box_l, local_box_l, min_box_l and min_local_box_l. Remark: In the apreiodic case min_box_l is set to 2 * MAX_INTERACTION_RANGE .
Definition at line 296 of file grid.cpp.
References box_l, dmin(), i, local_box_l, MAX_INTERACTION_RANGE, min_box_l, and min_local_box_l.
Referenced by grid_changed_box_l().
int calc_node_neighbors (int node)
fill neighbor lists of node.
Calculates the numbers of the nearest neighbors for a node and stores them in node_neighbors.
Returns
the number of neighbors
Parameters
node number of the node.
Definition at line 104 of file grid.cpp.
References boundary, comm_cart, GRID_TRACE, map_array_node(), map_node_array(), MPI_Cart_shift(), my_neighbor_count, node_grid, node_neighbor_lr, node_neighbor_wrap, node_neighbors, node_pos, realloc, and this_node.
Referenced by grid_changed_n_nodes().
void fold_coordinate (double pos[3], double vel[3], int image_box[3], int dir) inline
fold a coordinate to primary simulation box, including velocity (in case of LEES_EDWARDS, the velocity depends on the image we are in).
Parameters
pos the position...
vel the velocity...
image_box and the box
dir the coordinate to fold: dir = 0,1,2 for x, y and z coordinate.
Both pos and image_box are I/O, i. e. a previously folded position will be folded correctly.
Definition at line 211 of file grid.hpp.
References box_l, box_l_i, lees_edwards_offset, lees_edwards_rate, PERIODIC, ROUND_ERROR_PREC, and runtimeError.
Referenced by calc_cylindrical_average(), calc_diffusion_profile(), calc_radial_density_map(), dd_append_particles(), dd_exchange_and_sort_particles(), density_profile_av(), fold_all(), fold_coordinate(), and fold_position().
void fold_coordinate (double pos[3], int image_box[3], int dir) inline
fold a coordinate to primary simulation box, not caring about velocities.
Parameters
pos the position...
image_box and the box
dir the coordinate to fold: dir = 0,1,2 for x, y and z coordinate.
Both pos and image_box are I/O, i. e. a previously folded position will be folded correctly.
Definition at line 253 of file grid.hpp.
References fold_coordinate().
void fold_position (double pos[3], double vel[3], int image_box[3]) inline
fold particle coordinates to primary simulation box.
Parameters
pos the position...
vel the velocity...
image_box and the box
Pos, vel and image_box are I/O, i. e. a previously folded position will be folded correctly.
Definition at line 267 of file grid.hpp.
References fold_coordinate(), and i.
Referenced by add_constraints_energy(), add_constraints_forces(), add_external_potential_tabulated_energy(), add_external_potential_tabulated_forces(), calc_angledist_param(), calc_local_mol_info(), calc_pwdist(), calc_scaling(), calc_scaling2(), constraint_collision(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_get_particles_slave(), layered_append_particles(), layered_exchange_and_sort_particles(), lb_viscous_coupling(), local_place_particle(), magnetic_dipolar_direct_sum_calculations(), map_position_node_array(), Lattice::map_position_to_lattice_global(), observable_calc_density_profile(), observable_calc_flux_density_profile(), observable_calc_force_density_profile(), observable_calc_radial_density_profile(), observable_calc_radial_flux_density_profile(), reflect_particle(), tclcommand_analyze_parse_get_folded_positions(), tclcommand_imd_parse_pos(), tclcommand_part_print_folded_position(), and tclcommand_system_CMS().
void fold_position (double pos[3], int image_box[3]) inline
fold particle coordinates to primary simulation box.
Parameters
pos the position...
image_box and the box
Both pos and image_box are I/O, i. e. a previously folded position will be folded correctly.
Definition at line 282 of file grid.hpp.
References fold_coordinate(), and i.
void get_mi_vector (double res[3], double a[3], double b[3]) inline
get the minimal distance vector of two vectors in the current bc.
LEES_EDWARDS note: there is no need to add the le_offset here, any offset should already have been added when the image particle was prepared.
Parameters
a the vector to subtract from
b the vector to subtract
res where to store the result
Definition at line 190 of file grid.hpp.
References box_l, box_l_i, dround(), i, and PERIODIC.
Referenced by add_area_global_force(), add_bonded_energy(), add_bonded_force(), add_bonded_virials(), add_ljangle_pair_force(), add_three_body_bonded_stress(), add_volume_force(), angle_cosine_energy(), angle_cossquare_energy(), angle_energy(), angle_harmonic_energy(), angledist_energy(), bilayer_density_profile_sphere(), calc_angle_3body_forces(), calc_angle_3body_tabulated_forces(), calc_angle_cosine_3body_forces(), calc_angle_cosine_force(), calc_angle_cossquare_3body_forces(), calc_angle_cossquare_force(), calc_angle_force(), calc_angle_harmonic_3body_forces(), calc_angle_harmonic_force(), calc_angledist_force(), calc_angledist_param(), calc_area_force_local(), calc_area_global(), calc_bending_force(), calc_dihedral_angle(), calc_dihedral_force(), calc_dipole_dipole_ia(), calc_dipole_of_molecule(), calc_endangledist_pair_force(), calc_force_between_mol(), calc_hydrogen_bond_energy(), calc_hydrogen_bond_force(), calc_mol_pos(), calc_overlap_angle_force(), calc_pwangle(), calc_scaling(), calc_scaling2(), calc_tab_angle_force(), calc_twist_stack_energy(), calc_twist_stack_force(), calc_volume(), calc_wallbondyz(), calc_wallrdfyz(), CalcVolumeForce(), CalcVolumes(), compute_pos_corr_vec(), compute_vel_corr_vec(), distribute_mol_force(), distribute_tensors(), distto(), does_line_go_through_cube(), get_mol_dist(), get_mol_dist_vector_from_molid_cfg(), get_nonbonded_interaction(), IBM_Tribend_CalcForce(), IBM_Tribend_SetParams(), IBM_Triel_CalcForce(), IBM_Triel_SetParams(), incubewithskin(), integrate_reaction(), ljangle_pair_energy(), local_stress_tensor_calc(), min_distance2(), nbhood(), nsq_calculate_energies(), nsq_calculate_ia(), nsq_calculate_ia_iccp3m(), nsq_calculate_virials(), observable_calc_interacts_with(), observable_polymer_k_distribution(), observable_radial_density_distribution(), overlap_angle_energy(), print_bond_len(), reducepos(), tab_angle_energy(), test_mesh_elements(), vs_relate_to(), and vs_relative_pressure_and_stress_tensor().
void grid_changed_box_l ()
called from mpi_bcast_parameter .
Definition at line 245 of file grid.cpp.
References box_l, box_l_i, calc_minimal_box_dimensions(), GRID_TRACE, i, local_box_l, my_left, my_right, node_grid, node_pos, and this_node.
Referenced by grid_changed_n_nodes(), on_parameter_change(), and propagate_press_box_pos_and_rescale_npt().
void grid_changed_n_nodes ()
called from mpi_bcast_parameter .
Definition at line 269 of file grid.cpp.
References boundary, calc_node_neighbors(), comm_cart, grid_changed_box_l(), GRID_TRACE, MPI_Cart_coords(), MPI_Cart_create(), MPI_Comm_free(), MPI_Comm_rank(), MPI_COMM_WORLD, node_grid, node_neighbors, node_pos, and this_node.
Referenced by init_node_grid(), and on_parameter_change().
void init_node_grid ()
Make sure that the node grid is set, eventually determine one automatically.
Definition at line 72 of file grid.cpp.
References CELL_FLAG_GRIDCHANGED, cells_on_geometry_change(), and grid_changed_n_nodes().
Referenced by on_program_start().
int map_3don2d_grid (int g3d[3], int g2d[3], int mult[3])
calculate 'best' mapping between a 2d and 3d grid.
This we need for the communication from 3d domain decomposition to 2d row decomposition. The dimensions of the 2d grid are resorted, if necessary, in a way that they are multiples of the 3d grid dimensions.
Parameters
g3d 3d grid.
g2d 2d grid.
mult factors between 3d and 2d grid dimensions
Returns
index of the row direction [0,1,2].
Definition at line 317 of file grid.cpp.
References i.
int map_array_node (int pos[3]) inline
node mapping: node -> array.
Returns
rank of the node at position pos.
Parameters
pos position of the node in node grid.
Definition at line 131 of file grid.hpp.
References comm_cart, and MPI_Cart_rank().
Referenced by calc_node_neighbors(), Lattice::map_lattice_to_node(), and map_position_node_array().
void map_node_array (int node, int pos[3]) inline
node mapping: array -> node.
Parameters
node rank of the node you want to know the position for.
pos position of the node in node grid.
Definition at line 121 of file grid.hpp.
References comm_cart, and MPI_Cart_coords().
Referenced by calc_node_neighbors(), lb_calc_densprof(), lb_calc_velprof(), lb_init_boundaries(), le_dd_dynamic_update_comm(), le_dd_prepare_comm(), and printAllComms().
int map_position_node_array (double pos[3])
map a spatial position to the node grid
Definition at line 83 of file grid.cpp.
References box_l_i, fold_position(), i, map_array_node(), and node_grid.
Referenced by dd_topology_init(), layered_topology_init(), and nsq_topology_init().
int node_grid_is_set ()
return wether node grid was set.
Definition at line 78 of file grid.cpp.
References node_grid.
void rescale_boxl (int dir, double d_new)
rescales the box in dimension 'dir' to the new value 'd_new', and rescales the particles accordingly
Definition at line 341 of file grid.cpp.
References box_l, FIELD_BOXL, mpi_bcast_parameter(), and mpi_rescale_particles().
Referenced by add_particles(), and tclcommand_change_volume().
void unfold_position (double pos[3], double vel[3], int image_box[3]) inline
unfold coordinates to physical position.
Parameters
pos the position
pos the velocity
image_box and the box
Both pos and image_box are I/O, i.e. image_box will be (0,0,0) afterwards.
Definition at line 297 of file grid.hpp.
References box_l, box_l_i, i, lees_edwards_offset, and lees_edwards_rate.
Referenced by add_area_global_force(), add_volume_force(), calc_area_force_local(), calc_area_global(), calc_bending_force(), calc_local_mol_info(), calc_volume(), CalcVolumeForce(), CalcVolumes(), local_system_CMS(), meta_perform(), observable_calc_radial_flux_density_profile(), observable_radial_density_distribution(), tclcommand_analyze_parse_and_print_check_mol(), tclcommand_part_print_position(), tclcommand_writemd(), unfold_position(), and updatePartCfg().
void unfold_position (double pos[3], int image_box[3]) inline
unfold coordinates to physical position.
Parameters
pos the position...
image_box and the box
Both pos and image_box are I/O, i.e. image_box will be (0,0,0) afterwards.
Definition at line 330 of file grid.hpp.
References unfold_position().
Variable Documentation
int boundary[6]
where to fold particles that leave local box in direction i.
Definition at line 59 of file grid.cpp.
Referenced by calc_node_neighbors(), dd_append_particles(), dd_exchange_and_sort_particles(), dd_prepare_comm(), dd_save_position_to_cell(), dd_update_communicators_w_boxl(), GetIBMInterpolatedVelocity(), grid_changed_n_nodes(), lb_bounce_back(), lb_calc_fluid_temp(), lb_calc_local_fields(), lb_collide_stream(), lb_lbfluid_get_interpolated_velocity(), lb_lbfluid_print_boundary(), lb_lbfluid_print_vtk_boundary(), lb_stream_collide(), and prepare_halo_communication().
double box_l[3]
Simulation box dimensions.
Definition at line 62 of file grid.cpp.
Referenced by EwaldgpuForce::adaptive_tune(), add_ljangle_pair_force(), add_mdlc_energy_corrections(), add_mdlc_force_corrections(), add_mmm1d_coulomb_pair_force(), add_mmm2d_coulomb_pair_force(), add_particles(), add_z_force(), analyze_fold_molecules(), analyze_rdfchain(), bilayer_density_profile(), EspressoSystemInterface::box(), buf_mindist4(), build_verlet_lists(), build_verlet_lists_and_calc_verlet_ia(), build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_angledist_param(), calc_diffusion_profile(), calc_fluctuations(), calc_minimal_box_dimensions(), calc_mmm2d_copy_pair_energy(), calc_part_distribution(), calc_rdf(), calc_rdf_av(), calc_rdf_intermol_av(), calc_scaling(), calc_scaling2(), calc_structurefactor(), calc_trap_force(), calc_wallrdfyz(), calculate_maze_dist(), calculate_slitpore_dist(), cell_cell_transfer(), check_particle_consistency(), check_particles(), counterionsC(), create_free_volume_grid(), dd_create_cell_grid(), density_profile_av(), determine_minrad(), distribute_tensors(), distto(), does_line_go_through_cube(), fold_coordinate(), get_DLC_dipolar(), get_DLC_energy_dipolar(), get_lipid_orients(), get_mi_vector(), get_mi_vector_const(), getlength(), grid_changed_box_l(), Lattice::init(), integrate_ensemble_init(), lattice_read_file(), layered_get_mi_vector(), layered_prepare_comm(), lb_calc_average_rho(), lb_calc_densprof(), lb_calc_velprof(), lb_lbfluid_get_interpolated_velocity_global(), lb_lbfluid_load_checkpoint(), lb_lbfluid_print_boundary(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_boundary(), lb_lbfluid_print_vtk_velocity(), lb_lbfluid_save_checkpoint(), lb_lbfluid_set_agrid(), lb_reinit_parameters_gpu(), le_chatterjee_test_pair(), le_dd_dynamic_update_comm(), le_dd_prepare_comm(), le_dd_update_communicators_w_boxl(), lees_edwards_step_boundaries(), ljangle_pair_energy(), local_stress_tensor_calc(), maggs_compute_dipole_correction(), maggs_init(), maggs_sanity_checks(), magnetic_dipolar_direct_sum_calculations(), mdlc_set_params(), mdlc_tune(), mindist(), mindist3(), mindist4(), mmm1d_coulomb_pair_energy(), MMM1D_init(), mmm1d_tune(), MMM2D_add_far(), MMM2D_dielectric_layers_energy_contribution(), MMM2D_dielectric_layers_force_contribution(), MMM2D_setup_constants(), MMM2D_tune_near(), modify_stucturefactor(), mpi_observable_lb_radial_velocity_profile_parallel(), nemd_init(), observable_calc_lb_velocity_profile(), observable_calc_structure_factor(), observable_calc_structure_factor_fast(), on_coulomb_change(), polymerC(), pressure_calc(), wavepart::print(), propagate_pos_sd(), propagate_press_box_pos_and_rescale_npt(), propagate_vel_pos(), put_recv_buffer(), recalc_global_maximal_nonbonded_cutoff(), rescale_boxl(), saltC(), sd_set_particles_apart(), setup_P(), setup_PQ(), setup_Q(), tclcallback_box_l(), tclcommand_analyze_fluid_parse_velprof(), tclcommand_analyze_parse_density_profile_av(), tclcommand_analyze_parse_diffusion_profile(), tclcommand_analyze_parse_structurefactor(), tclcommand_analyze_parse_Vkappa(), tclcommand_change_volume(), tclcommand_crosslink(), tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha(), tclcommand_inter_coulomb_parse_mmm1d(), tclcommand_inter_coulomb_parse_mmm1dgpu(), tclcommand_inter_parse_ljangle(), tclcommand_lbnode(), tclcommand_nemd_parse_and_print_viscosity(), tclcommand_observable_print_structure_factor_fast_formatted(), tclcommand_observable_print_structure_factor_formatted(), tclcommand_parse_profile(), tclcommand_parse_radial_profile(), EwaldgpuForce::tune_rcut(), unfold_position(), update_mol_pos_particle(), le_dd_comms_manager::update_on_le_offset_change(), and z_energy().
double box_l_i[3]
1 / box dimensions.
Definition at line 63 of file grid.cpp.
Referenced by add_ljangle_pair_force(), analyze_fold_molecules(), fold_coordinate(), get_mi_vector(), get_mi_vector_const(), grid_changed_box_l(), layered_get_mi_vector(), le_frameV(), ljangle_pair_energy(), Lattice::map_lattice_to_node(), map_position_node_array(), propagate_vel_pos(), rod_energy(), and unfold_position().
double local_box_l[3]
Dimensions of the box a single node is responsible for.
Definition at line 65 of file grid.cpp.
Referenced by calc_minimal_box_dimensions(), dd_create_cell_grid(), dd_on_geometry_change(), dd_position_to_cell(), dd_save_position_to_cell(), force_and_velocity_check(), grid_changed_box_l(), Lattice::init(), layered_topology_init(), and Lattice::map_position_to_lattice().
double min_box_l
Smallest simulation box dimension (box_l).
Remark: with PARTIAL_PERIODIC, only the periodic directions are taken into account!
Definition at line 64 of file grid.cpp.
Referenced by calc_minimal_box_dimensions(), tclcommand_analyze_parse_distribution(), tclcommand_analyze_parse_rdf(), and tclcommand_observable_rdf().
double min_local_box_l
Smallest local simulation box dimension (local_box_l).
Remark: with PARTIAL_PERIODIC, only the periodic directions are taken into account!
Definition at line 66 of file grid.cpp.
Referenced by calc_minimal_box_dimensions().
double my_left[3]
Left (bottom, front) corner of this nodes local box.
Definition at line 67 of file grid.cpp.
Referenced by calc_particle_lattice_ia(), cell_cell_transfer(), dd_append_particles(), dd_create_cell_grid(), dd_exchange_and_sort_particles(), dd_init_cell_interactions(), dd_position_to_cell(), dd_save_position_to_cell(), ForcesIntoFluid_Kernel(), get_interpolated_velocity(), global_pos_in_local_box(), grid_changed_box_l(), IBM_ForcesIntoFluid_CPU(), Lattice::init(), layered_append_particles(), layered_exchange_and_sort_particles(), layered_position_to_cell(), le_dd_init_cell_interactions(), maggs_setup_local_lattice(), Lattice::map_position_to_lattice(), mpi_observable_lb_radial_velocity_profile_parallel(), ParticleVelocitiesFromLB_CPU(), ParticleVelocitiesFromLB_Kernel(), put_recv_buffer(), setup_P(), setup_PQ(), and setup_Q().
int my_neighbor_count
the number of nearest neighbors of a node in the node grid.
Definition at line 55 of file grid.cpp.
Referenced by calc_node_neighbors(), dd_topology_init(), le_dd_dynamic_update_comm(), le_dd_prepare_comm(), le_dd_update_communicators_w_boxl(), and printAllComms().
double my_right[3]
Right (top, back) corner of this nodes local box.
Definition at line 68 of file grid.cpp.
Referenced by calc_particle_lattice_ia(), dd_create_cell_grid(), dd_exchange_and_sort_particles(), global_pos_in_local_box(), grid_changed_box_l(), IBM_ForcesIntoFluid_CPU(), Lattice::init(), layered_append_particles(), layered_exchange_and_sort_particles(), maggs_setup_local_lattice(), mpi_observable_lb_radial_velocity_profile_parallel(), and ParticleVelocitiesFromLB_CPU().
int node_grid[3]
The number of nodes in each spatial dimension.
Definition at line 49 of file grid.cpp.
Referenced by calc_node_neighbors(), calc_processor_min_num_cells(), dd_exchange_and_sort_particles(), dd_prepare_comm(), dd_update_communicators_w_boxl(), grid_changed_box_l(), grid_changed_n_nodes(), halo_push_communication(), Lattice::init(), layered_topology_init(), lb_calc_densprof(), lb_calc_velprof(), le_dd_init_cell_interactions(), maggs_calc_init_e_field(), maggs_sanity_checks(), Lattice::map_lattice_to_node(), map_position_node_array(), mpi_init(), node_grid_is_set(), prepare_halo_communication(), tclcallback_node_grid(), tclcommand_analyze_fluid_parse_densprof(), tclcommand_cellsystem(), and le_dd_comms_manager::update_on_le_offset_change().
int* node_neighbor_lr
Definition at line 54 of file grid.cpp.
Referenced by calc_node_neighbors(), dd_exchange_and_sort_particles(), le_dd_dynamic_update_comm(), and le_dd_prepare_comm().
int* node_neighbor_wrap
Definition at line 53 of file grid.cpp.
Referenced by calc_node_neighbors(), le_dd_dynamic_update_comm(), le_dd_prepare_comm(), and le_dd_update_communicators_w_boxl().
int* node_neighbors
the nearest neighbors of a node in the node grid.
Definition at line 52 of file grid.cpp.
Referenced by calc_node_neighbors(), dd_exchange_and_sort_particles(), dd_prepare_comm(), grid_changed_n_nodes(), halo_push_communication(), Lattice::init(), lb_check_halo_regions(), le_dd_dynamic_update_comm(), le_dd_prepare_comm(), le_dd_update_communicators_w_boxl(), maggs_calc_init_e_field(), maggs_exchange_surface_patch(), prepare_halo_communication(), and printAllComms().
int node_pos[3]
position of node in node grid
Definition at line 50 of file grid.cpp.
Referenced by calc_node_neighbors(), dd_exchange_and_sort_particles(), dd_prepare_comm(), dd_update_communicators_w_boxl(), grid_changed_box_l(), grid_changed_n_nodes(), lb_calc_densprof(), lb_calc_velprof(), le_dd_dynamic_update_comm(), le_dd_init_cell_interactions(), le_dd_prepare_comm(), maggs_calc_init_e_field(), and mpi_init().
int periodic
Flags for all three dimensions wether pbc are applied (default).
The first three bits give the periodicity
Definition at line 60 of file grid.cpp.
Referenced by mpi_init(), mpi_local_stress_tensor_slave(), tclcallback_periodicity(), and tclcommand_analyze_parse_local_stress_tensor().