ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: grid_tcl.hpp File Reference
grid_tcl.hpp File Reference
#include "parser.hpp"
Functions
Exported Functions
int tclcallback_periodicity (Tcl_Interp *interp, void *_data)
datafield callback for periodic.
int tclcallback_node_grid (Tcl_Interp *interp, void *data)
datafield callback for node_grid.
int tclcallback_box_l (Tcl_Interp *interp, void *_data)
datafield callback for box_l.
int tclcommand_change_volume (ClientData data, Tcl_Interp *interp, int argc, char **argv)
changes the volume by resizing the box and isotropically adjusting the particles coordinates as well
Function Documentation
int tclcallback_box_l (Tcl_Interp * interp, void * _data)
datafield callback for box_l.
Sets the box dimensions.
Definition at line 82 of file grid_tcl.cpp.
References box_l, FIELD_BOXL, and mpi_bcast_parameter().
Referenced by tcl_register_global_variables().
int tclcallback_node_grid (Tcl_Interp * interp, void * data)
datafield callback for node_grid.
Definition at line 32 of file grid_tcl.cpp.
References FIELD_NODEGRID, mpi_bcast_parameter(), n_nodes, and node_grid.
Referenced by tcl_register_global_variables().
int tclcallback_periodicity (Tcl_Interp * interp, void * _data)
datafield callback for periodic.
Determines wether a coordinate is pbc (default).
Definition at line 59 of file grid_tcl.cpp.
References FIELD_PERIODIC, mpi_bcast_parameter(), and periodic.
Referenced by tcl_register_global_variables().
int tclcommand_change_volume (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
changes the volume by resizing the box and isotropically adjusting the particles coordinates as well
Definition at line 100 of file grid_tcl.cpp.
References box_l, gather_runtime_errors(), and rescale_boxl().
Referenced by tcl_register_commands().