ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: halo.hpp File Reference
halo.hpp File Reference
Halo scheme for parallelization of lattice algorithms.
#include <mpi.h>
#include "utils.hpp"
#include "lattice.hpp"
Data Structures
struct _Fieldtype
struct HaloInfo
Structure describing a Halo region.
struct HaloCommunicator
Structure holding a set of HaloInfo which comprise a certain parallelization scheme.
Macros
#define FIELDTYPE_DOUBLE (&fieldtype_double)
Types of halo communications
HALO_LOCL local exchange of halo regions on the same processor
HALO_SENDRECV halo exchange between different processors
#define HALO_LOCL 0
Tag for local exchange of halo regions on the same processor.
#define HALO_SENDRECV 1
Tag for halo exchange between different processors.
#define HALO_SEND 2
Tag for halo send only.
#define HALO_RECV 3
Tag for halo receive only.
#define HALO_OPEN 4
Tag for halo open boundary.
Tags for halo communications
REQ_HALO_SPREAD exchange of all halo regions
REQ_HALO_CHECK additional check for consistency of halo regions
#define REQ_HALO_SPREAD 501
Tag for halo update.
#define REQ_HALO_CHECK 599
Tag for consistency check of halo regions.
Typedefs
typedef struct _Fieldtype * Fieldtype
This struct describes the layout of the lattice data.
Functions
void halo_create_fieldtype (int count, int *lengths, int *disps, int extent, Fieldtype *newtype)
Creates a fieldtype describing the data layout.
void halo_create_field_vector (int vblocks, int vstride, int vskip, Fieldtype oldtype, Fieldtype *newtype)
Creates a field vector layout.
void halo_create_field_hvector (int vblocks, int vstride, int vskip, Fieldtype oldtype, Fieldtype *newtype)
void halo_free_fieldtype (Fieldtype *ftype)
Frees a fieldtype.
void prepare_halo_communication (HaloCommunicator *hc, Lattice *lattice, Fieldtype fieldtype, MPI_Datatype datatype)
Preparation of a certain halo parallelizations scheme.
void release_halo_communication (HaloCommunicator *hc)
Frees datastrutures associated with a halo communicator.
void halo_communication (HaloCommunicator *hc, char *base)
Perform communication according to the parallelization scheme described by the halo communicator.
Variables
struct _Fieldtype fieldtype_double
Predefined fieldtypes.
Detailed Description
Halo scheme for parallelization of lattice algorithms.
Header file for halo.cpp.
Definition in file halo.hpp.
Macro Definition Documentation
#define FIELDTYPE_DOUBLE (&fieldtype_double)
Definition at line 83 of file halo.hpp.
Referenced by lb_prepare_communication().
#define HALO_LOCL 0
Tag for local exchange of halo regions on the same processor.
Definition at line 45 of file halo.hpp.
Referenced by halo_communication(), and prepare_halo_communication().
#define HALO_OPEN 4
Tag for halo open boundary.
Definition at line 49 of file halo.hpp.
Referenced by halo_communication(), and prepare_halo_communication().
#define HALO_RECV 3
Tag for halo receive only.
Definition at line 48 of file halo.hpp.
Referenced by halo_communication(), and prepare_halo_communication().
#define HALO_SEND 2
Tag for halo send only.
Definition at line 47 of file halo.hpp.
Referenced by halo_communication(), and prepare_halo_communication().
#define HALO_SENDRECV 1
Tag for halo exchange between different processors.
Definition at line 46 of file halo.hpp.
Referenced by halo_communication(), and prepare_halo_communication().
#define REQ_HALO_CHECK 599
Tag for consistency check of halo regions.
Definition at line 61 of file halo.hpp.
Referenced by lb_check_halo_regions().
#define REQ_HALO_SPREAD 501
Tag for halo update.
Definition at line 60 of file halo.hpp.
Referenced by halo_communication(), and halo_push_communication().
Typedef Documentation
typedef struct _Fieldtype* Fieldtype
This struct describes the layout of the lattice data.
The description is similar to MPI datatypes but a bit more compact. See halo_create_fieldtype, halo_create_field_vector and halo_dtcopy to understand how it works.
Definition at line 68 of file halo.hpp.
Function Documentation
void halo_communication (HaloCommunicator * hc, char * base)
Perform communication according to the parallelization scheme described by the halo communicator.
Parameters
hc halo communicator describing the parallelization scheme
base base plane of local node
Definition at line 347 of file halo.cpp.
References comm_cart, HaloInfo::datatype, HaloInfo::dest_node, HaloInfo::fieldtype, halo_dtcopy(), halo_dtset(), HaloCommunicator::halo_info, HALO_LOCL, HALO_OPEN, HALO_RECV, HALO_SEND, HALO_SENDRECV, HALO_TRACE, MPI_Irecv(), MPI_Isend(), MPI_Sendrecv(), MPI_Wait(), HaloCommunicator::num, r_buffer, HaloInfo::r_offset, REQ_HALO_SPREAD, request, s_buffer, HaloInfo::s_offset, HaloInfo::source_node, this_node, and HaloInfo::type.
Referenced by calc_particle_lattice_ia(), lb_stream_collide(), and ParticleVelocitiesFromLB_CPU().
void halo_create_field_hvector (int vblocks, int vstride, int vskip, Fieldtype oldtype, Fieldtype * newtype)
Definition at line 107 of file halo.cpp.
References _Fieldtype::count, _Fieldtype::disps, _Fieldtype::extent, i, _Fieldtype::lengths, malloc, _Fieldtype::subtype, _Fieldtype::vblocks, _Fieldtype::vflag, _Fieldtype::vskip, and _Fieldtype::vstride.
Referenced by lb_prepare_communication().
void halo_create_field_vector (int vblocks, int vstride, int vskip, Fieldtype oldtype, Fieldtype * newtype)
Creates a field vector layout.
Parameters
vblocks number of vector blocks(Input)
vstride size of strides in field vector (Input)
vskip displacements of strides in field vector (Input)
oldtype fieldtype the vector is composed of (Input)
newtype newly created fieldtype (Input/Output)
Definition at line 82 of file halo.cpp.
References _Fieldtype::count, _Fieldtype::disps, _Fieldtype::extent, i, _Fieldtype::lengths, malloc, _Fieldtype::subtype, _Fieldtype::vblocks, _Fieldtype::vflag, _Fieldtype::vskip, and _Fieldtype::vstride.
Referenced by prepare_halo_communication().
void halo_create_fieldtype (int count, int * lengths, int * disps, int extent, Fieldtype * newtype)
Creates a fieldtype describing the data layout.
Parameters
count number of subtypes (Input)
lengths array of lenghts of the subtytpes (Input)
disps array of displacements the subtypes (Input)
extent extent of the whole new fieldtype (Input)
newtype newly created fieldtype (Input/Output)
Definition at line 45 of file halo.cpp.
References _Fieldtype::count, _Fieldtype::disps, _Fieldtype::extent, i, _Fieldtype::lengths, malloc, _Fieldtype::subtype, _Fieldtype::vblocks, _Fieldtype::vflag, _Fieldtype::vskip, and _Fieldtype::vstride.
void halo_free_fieldtype (Fieldtype * ftype)
Frees a fieldtype.
Parameters
ftype pointer to the type to be freed (Input)
Definition at line 135 of file halo.cpp.
References free.
void prepare_halo_communication (HaloCommunicator * hc, Lattice * lattice, Fieldtype fieldtype, MPI_Datatype datatype)
Preparation of a certain halo parallelizations scheme.
Sets up the necessary datastructures for halo_communication
Parameters
hc halo communicator beeing created (Input/Output)
lattice lattice the communcation is created for (Input)
fieldtype field layout of the lattice data (Input)
datatype MPI datatype for the lattice data (Input)
Preparation of a certain halo parallelizations scheme.
Sets up the necessary datastructures for halo_communication
Parameters
hc halo communicator beeing created (Input/Output)
lattice lattice the communcation is created for (Input)
fieldtype field layout of the lattice data (Input)
datatype MPI datatype for the lattice data (Input)
Definition at line 235 of file halo.cpp.
References boundary, HaloInfo::datatype, HaloInfo::dest_node, _Fieldtype::extent, HaloInfo::fieldtype, Lattice::grid, halo_create_field_vector(), Lattice::halo_grid, HaloCommunicator::halo_info, HALO_LOCL, HALO_OPEN, HALO_RECV, HALO_SEND, HALO_SENDRECV, HALO_TRACE, MPI_Type_commit(), MPI_Type_free(), MPI_Type_vector(), node_grid, node_neighbors, HaloCommunicator::num, PERIODIC, HaloInfo::r_offset, realloc, HaloInfo::s_offset, HaloInfo::source_node, this_node, and HaloInfo::type.
Referenced by lb_prepare_communication().
void release_halo_communication (HaloCommunicator * hc)
Frees datastrutures associated with a halo communicator.
Parameters
hc halo communicator to be released
Definition at line 331 of file halo.cpp.
References HaloInfo::datatype, free, HaloCommunicator::halo_info, MPI_Type_free(), and HaloCommunicator::num.
Referenced by lb_prepare_communication(), and lb_release().
Variable Documentation
struct _Fieldtype fieldtype_double
Predefined fieldtypes.
Predefined fieldtypes.
Definition at line 36 of file halo.cpp.