ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: halo.cpp File Reference
halo.cpp File Reference
Halo scheme for parallelization of lattice algorithms.
#include "utils.hpp"
#include "grid.hpp"
#include "lattice.hpp"
#include "halo.hpp"
Functions
void halo_create_fieldtype (int count, int *lengths, int *disps, int extent, Fieldtype *newtype)
Creates a fieldtype describing the data layout.
void halo_create_field_vector (int vblocks, int vstride, int vskip, Fieldtype oldtype, Fieldtype *newtype)
Creates a field vector layout.
void halo_create_field_hvector (int vblocks, int vstride, int vskip, Fieldtype oldtype, Fieldtype *newtype)
void halo_free_fieldtype (Fieldtype *ftype)
Frees a fieldtype.
void halo_dtset (char *dest, int value, Fieldtype type)
Set halo region to a given value.
void halo_dtcopy (char *r_buffer, char *s_buffer, int count, Fieldtype type)
Copy lattice data with layout described by fieldtype.
void halo_copy_vector (char *r_buffer, char *s_buffer, int count, Fieldtype type, int vflag)
void prepare_halo_communication (HaloCommunicator *hc, Lattice *lattice, Fieldtype fieldtype, MPI_Datatype datatype)
Preparation of the halo parallelization scheme.
void release_halo_communication (HaloCommunicator *hc)
Frees datastrutures associated with a halo communicator.
void halo_communication (HaloCommunicator *hc, char *base)
Perform communication according to the parallelization scheme described by the halo communicator.
Variables
struct _Fieldtype fieldtype_double = { 0, NULL, NULL, sizeof(double), 0, 0, 0, 0, NULL }
Primitive fieldtypes and their initializers.
Detailed Description
Halo scheme for parallelization of lattice algorithms.
Implementation of file halo.hpp.
Definition in file halo.cpp.
Function Documentation
void halo_communication (HaloCommunicator * hc, char * base)
Perform communication according to the parallelization scheme described by the halo communicator.
Parameters
hc halo communicator describing the parallelization scheme
base base plane of local node
Definition at line 347 of file halo.cpp.
References comm_cart, HaloInfo::datatype, HaloInfo::dest_node, HaloInfo::fieldtype, halo_dtcopy(), halo_dtset(), HaloCommunicator::halo_info, HALO_LOCL, HALO_OPEN, HALO_RECV, HALO_SEND, HALO_SENDRECV, HALO_TRACE, MPI_Irecv(), MPI_Isend(), MPI_Sendrecv(), MPI_Wait(), HaloCommunicator::num, r_buffer, HaloInfo::r_offset, REQ_HALO_SPREAD, request, s_buffer, HaloInfo::s_offset, HaloInfo::source_node, this_node, and HaloInfo::type.
Referenced by calc_particle_lattice_ia(), lb_stream_collide(), and ParticleVelocitiesFromLB_CPU().
void halo_copy_vector (char * r_buffer, char * s_buffer, int count, Fieldtype type, int vflag)
Definition at line 172 of file halo.cpp.
References _Fieldtype::count, _Fieldtype::extent, halo_dtcopy(), HALO_TRACE, i, _Fieldtype::subtype, this_node, _Fieldtype::vblocks, _Fieldtype::vskip, and _Fieldtype::vstride.
Referenced by halo_dtcopy().
void halo_create_field_hvector (int vblocks, int vstride, int vskip, Fieldtype oldtype, Fieldtype * newtype)
Definition at line 107 of file halo.cpp.
References _Fieldtype::count, _Fieldtype::disps, _Fieldtype::extent, i, _Fieldtype::lengths, malloc, _Fieldtype::subtype, _Fieldtype::vblocks, _Fieldtype::vflag, _Fieldtype::vskip, and _Fieldtype::vstride.
Referenced by lb_prepare_communication().
void halo_create_field_vector (int vblocks, int vstride, int vskip, Fieldtype oldtype, Fieldtype * newtype)
Creates a field vector layout.
Parameters
vblocks number of vector blocks(Input)
vstride size of strides in field vector (Input)
vskip displacements of strides in field vector (Input)
oldtype fieldtype the vector is composed of (Input)
newtype newly created fieldtype (Input/Output)
Definition at line 82 of file halo.cpp.
References _Fieldtype::count, _Fieldtype::disps, _Fieldtype::extent, i, _Fieldtype::lengths, malloc, _Fieldtype::subtype, _Fieldtype::vblocks, _Fieldtype::vflag, _Fieldtype::vskip, and _Fieldtype::vstride.
Referenced by prepare_halo_communication().
void halo_create_fieldtype (int count, int * lengths, int * disps, int extent, Fieldtype * newtype)
Creates a fieldtype describing the data layout.
Parameters
count number of subtypes (Input)
lengths array of lenghts of the subtytpes (Input)
disps array of displacements the subtypes (Input)
extent extent of the whole new fieldtype (Input)
newtype newly created fieldtype (Input/Output)
Definition at line 45 of file halo.cpp.
References _Fieldtype::count, _Fieldtype::disps, _Fieldtype::extent, i, _Fieldtype::lengths, malloc, _Fieldtype::subtype, _Fieldtype::vblocks, _Fieldtype::vflag, _Fieldtype::vskip, and _Fieldtype::vstride.
void halo_dtcopy (char * r_buffer, char * s_buffer, int count, Fieldtype type)
Copy lattice data with layout described by fieldtype.
Parameters
r_buffer data destination
s_buffer data source
count amount of data to copy
type field layout type
Definition at line 202 of file halo.cpp.
References _Fieldtype::count, _Fieldtype::disps, _Fieldtype::extent, halo_copy_vector(), HALO_TRACE, i, _Fieldtype::lengths, _Fieldtype::subtype, this_node, _Fieldtype::vblocks, _Fieldtype::vflag, _Fieldtype::vskip, and _Fieldtype::vstride.
Referenced by halo_communication(), and halo_copy_vector().
void halo_dtset (char * dest, int value, Fieldtype type)
Set halo region to a given value.
Parameters
dest pointer to the halo buffer (Input)
value integer value to write into the halo buffer
type halo field layout description
Definition at line 148 of file halo.cpp.
References _Fieldtype::count, _Fieldtype::disps, _Fieldtype::extent, i, _Fieldtype::lengths, _Fieldtype::vblocks, _Fieldtype::vskip, and _Fieldtype::vstride.
Referenced by halo_communication().
void halo_free_fieldtype (Fieldtype * ftype)
Frees a fieldtype.
Parameters
ftype pointer to the type to be freed (Input)
Definition at line 135 of file halo.cpp.
References free.
void prepare_halo_communication (HaloCommunicator * hc, Lattice * lattice, Fieldtype fieldtype, MPI_Datatype datatype)
Preparation of the halo parallelization scheme.
Preparation of a certain halo parallelizations scheme.
Sets up the necessary datastructures for halo_communication
Parameters
hc halo communicator beeing created (Input/Output)
lattice lattice the communcation is created for (Input)
fieldtype field layout of the lattice data (Input)
datatype MPI datatype for the lattice data (Input)
Definition at line 235 of file halo.cpp.
References boundary, HaloInfo::datatype, HaloInfo::dest_node, _Fieldtype::extent, HaloInfo::fieldtype, Lattice::grid, halo_create_field_vector(), Lattice::halo_grid, HaloCommunicator::halo_info, HALO_LOCL, HALO_OPEN, HALO_RECV, HALO_SEND, HALO_SENDRECV, HALO_TRACE, MPI_Type_commit(), MPI_Type_free(), MPI_Type_vector(), node_grid, node_neighbors, HaloCommunicator::num, PERIODIC, HaloInfo::r_offset, realloc, HaloInfo::s_offset, HaloInfo::source_node, this_node, and HaloInfo::type.
Referenced by lb_prepare_communication().
void release_halo_communication (HaloCommunicator * hc)
Frees datastrutures associated with a halo communicator.
Parameters
hc halo communicator to be released
Definition at line 331 of file halo.cpp.
References HaloInfo::datatype, free, HaloCommunicator::halo_info, MPI_Type_free(), and HaloCommunicator::num.
Referenced by lb_prepare_communication(), and lb_release().
Variable Documentation
struct _Fieldtype fieldtype_double = { 0, NULL, NULL, sizeof(double), 0, 0, 0, 0, NULL }
Primitive fieldtypes and their initializers.
Predefined fieldtypes.
Definition at line 36 of file halo.cpp.