ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: HarmonicOrientationWell_cuda.cu File Reference
HarmonicOrientationWell_cuda.cu File Reference
#include "HarmonicOrientationWell.hpp"
#include "cuda_utils.hpp"
#include <stdio.h>
Functions
__global__ void HarmonicOrientationWell_kernel (float x, float y, float z, float k, int n, float *quatu, float *torque)
void HarmonicOrientationWell_kernel_wrapper (float x, float y, float z, float k, int n, float *quatu, float *torque)
Function Documentation
__global__ void HarmonicOrientationWell_kernel (float x, float y, float z, float k, int n, float * quatu, float * torque)
Definition at line 24 of file HarmonicOrientationWell_cuda.cu.
Referenced by HarmonicOrientationWell_kernel_wrapper().
void HarmonicOrientationWell_kernel_wrapper (float x, float y, float z, float k, int n, float * quatu, float * torque)
Definition at line 57 of file HarmonicOrientationWell_cuda.cu.
References block(), HarmonicOrientationWell_kernel(), and KERNELCALL.
Referenced by HarmonicOrientationWell::computeTorques().