ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: harmonic.hpp File Reference
harmonic.hpp File Reference
Routines to calculate the HARMONIC Energy or/and HARMONIC force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "random.hpp"
Functions
int harmonic_set_params (int bond_type, double k, double r, double r_cut)
set the parameters for the harmonic potential
int calc_harmonic_pair_force (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double force[3])
Computes the HARMONIC pair force and adds this force to the particle forces (see interaction_data.cpp).
int harmonic_pair_energy (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double *_energy)
Detailed Description
Routines to calculate the HARMONIC Energy or/and HARMONIC force for a particle pair.
forces.cpp
Definition in file harmonic.hpp.
Function Documentation
int calc_harmonic_pair_force (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double force[3]) inline
Computes the HARMONIC pair force and adds this force to the particle forces (see interaction_data.cpp).
Parameters
p1 Pointer to first particle.
p2 Pointer to second/middle particle.
iaparams bond type number of the angle interaction (see interaction_data.cpp).
dx particle distance vector
force returns force of particle 1
Returns
0.
Definition at line 48 of file harmonic.hpp.
References check_id, configtemp, d_random(), ParticleForce::f, Particle::f, Bond_parameters::harmonic, i, ParticleProperties::identity, Harmonic_bond_parameters::k, ONEPART_TRACE, Particle::p, Bonded_ia_parameters::p, Harmonic_bond_parameters::r, Harmonic_bond_parameters::r_cut, ROUND_ERROR_PREC, SQR(), sqrlen(), and this_node.
Referenced by add_bonded_force(), and calc_bonded_force().
int harmonic_pair_energy (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double * _energy) inline
Definition at line 90 of file harmonic.hpp.
References Bond_parameters::harmonic, Harmonic_bond_parameters::k, Bonded_ia_parameters::p, Harmonic_bond_parameters::r, Harmonic_bond_parameters::r_cut, SQR(), and sqrlen().
Referenced by add_bonded_energy().
int harmonic_set_params (int bond_type, double k, double r, double r_cut)
set the parameters for the harmonic potential
Definition at line 28 of file harmonic.cpp.
References BONDED_IA_HARMONIC, bonded_ia_params, ES_ERROR, ES_OK, Bond_parameters::harmonic, Harmonic_bond_parameters::k, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Harmonic_bond_parameters::r, Harmonic_bond_parameters::r_cut, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_harmonic().