ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: hydrogen_bond.hpp File Reference
hydrogen_bond.hpp File Reference
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "grid.hpp"
Functions
int hydrogen_bond_set_params (int bond_type, DoubleList *params)
int calc_hydrogen_bond_force (Particle *s1, Particle *b1, Particle *b2, Particle *s2, Bonded_ia_parameters *iaparams, double f_s1[3], double f_b1[3], double f_b2[3], double f_s2[3])
int calc_hydrogen_bond_energy (Particle *s1, Particle *b1, Particle *b2, Particle *s2, Bonded_ia_parameters *iaparams, double *_energy)
Function Documentation
int calc_hydrogen_bond_energy (Particle * s1, Particle * b1, Particle * b2, Particle * s2, Bonded_ia_parameters * iaparams, double * _energy)
Definition at line 343 of file hydrogen_bond.cpp.
References Cg_dna_basepair_parameters::alpha, Cg_dna_basepair_parameters::alphasb, COS_MAX, COS_MIN, cross(), dot(), Cg_dna_basepair_parameters::E0, Cg_dna_basepair_parameters::E0sb, Cg_dna_basepair_parameters::f2, Cg_dna_basepair_parameters::f3, get_mi_vector(), Bond_parameters::hydrogen_bond, Cg_dna_basepair_parameters::kd, M_PI, norm(), normalize(), ParticlePosition::p, Bonded_ia_parameters::p, params, PI, Cg_dna_basepair_parameters::psi10, Cg_dna_basepair_parameters::psi20, Particle::r, Cg_dna_basepair_parameters::r0, Cg_dna_basepair_parameters::r0sb, Cg_dna_basepair_parameters::sigma1, Cg_dna_basepair_parameters::sigma2, and SQR().
Referenced by add_bonded_energy().
int calc_hydrogen_bond_force (Particle * s1, Particle * b1, Particle * b2, Particle * s2, Bonded_ia_parameters * iaparams, double f_s1[3], double f_b1[3], double f_b2[3], double f_s2[3])
Definition at line 84 of file hydrogen_bond.cpp.
References Cg_dna_basepair_parameters::alpha, Cg_dna_basepair_parameters::alphasb, COS_MAX, COS_MIN, cross(), dot(), Cg_dna_basepair_parameters::E0, Cg_dna_basepair_parameters::E0sb, Cg_dna_basepair_parameters::f2, Cg_dna_basepair_parameters::f3, get_mi_vector(), Bond_parameters::hydrogen_bond, i, ParticleProperties::identity, Cg_dna_basepair_parameters::kd, M_PI, norm(), ParticlePosition::p, Particle::p, Bonded_ia_parameters::p, params, PI, PS, Cg_dna_basepair_parameters::psi10, Cg_dna_basepair_parameters::psi20, PV, Particle::r, Cg_dna_basepair_parameters::r0, Cg_dna_basepair_parameters::r0sb, Cg_dna_basepair_parameters::sigma1, Cg_dna_basepair_parameters::sigma2, and SQR().
Referenced by add_bonded_force().
int hydrogen_bond_set_params (int bond_type, DoubleList * params)
Definition at line 472 of file hydrogen_bond.cpp.
References Cg_dna_basepair_parameters::alpha, Cg_dna_basepair_parameters::alphasb, BONDED_IA_CG_DNA_BASEPAIR, bonded_ia_params, DoubleList::e, Cg_dna_basepair_parameters::E0, Cg_dna_basepair_parameters::E0sb, ES_ERROR, ES_OK, Cg_dna_basepair_parameters::f2, Cg_dna_basepair_parameters::f3, Bond_parameters::hydrogen_bond, Cg_dna_basepair_parameters::kd, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Cg_dna_basepair_parameters::psi10, Cg_dna_basepair_parameters::psi20, Cg_dna_basepair_parameters::r0, Cg_dna_basepair_parameters::r0sb, Cg_dna_basepair_parameters::sigma1, Cg_dna_basepair_parameters::sigma2, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_hydrogen_bond().