ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: hydrogen_bond.cpp File Reference
hydrogen_bond.cpp File Reference
#include "hydrogen_bond.hpp"
#include "communication.hpp"
Macros
#define COS_MAX (0.99999999)
#define COS_MIN (-0.99999999)
#define EX(A) A[0], A[1], A[2]
#define PV(A)
#define PS(A)
Functions
double dot (double *x1, double *x2)
void cross (double *x1, double *x2, double *x3)
double norm2 (double *x)
double norm (double *x)
void normalize (double *x)
double cos_angle (double *x1, double *x2)
double angle (double *x1, double *x2)
int calc_hydrogen_bond_force (Particle *s1, Particle *b1, Particle *b2, Particle *s2, Bonded_ia_parameters *iaparams, double f_s1[3], double f_b1[3], double f_b2[3], double f_s2[3])
int calc_hydrogen_bond_energy (Particle *s1, Particle *b1, Particle *b2, Particle *s2, Bonded_ia_parameters *iaparams, double *_energy)
int hydrogen_bond_set_params (int bond_type, DoubleList *params)
Macro Definition Documentation
#define COS_MAX (0.99999999)
Definition at line 32 of file hydrogen_bond.cpp.
Referenced by calc_hydrogen_bond_energy(), and calc_hydrogen_bond_force().
#define COS_MIN (-0.99999999)
Definition at line 33 of file hydrogen_bond.cpp.
Referenced by calc_hydrogen_bond_energy(), and calc_hydrogen_bond_force().
#define EX (A) A[0], A[1], A[2]
Definition at line 74 of file hydrogen_bond.cpp.
#define PS (A)
Definition at line 81 of file hydrogen_bond.cpp.
Referenced by calc_hydrogen_bond_force().
#define PV (A)
Definition at line 80 of file hydrogen_bond.cpp.
Referenced by calc_hydrogen_bond_force().
Function Documentation
double angle (double * x1, double * x2) inline
Definition at line 70 of file hydrogen_bond.cpp.
References cos_angle().
Referenced by observable_radial_density_distribution(), and tclcommand_polymer().
int calc_hydrogen_bond_energy (Particle * s1, Particle * b1, Particle * b2, Particle * s2, Bonded_ia_parameters * iaparams, double * _energy)
Definition at line 343 of file hydrogen_bond.cpp.
References Cg_dna_basepair_parameters::alpha, Cg_dna_basepair_parameters::alphasb, COS_MAX, COS_MIN, cross(), dot(), Cg_dna_basepair_parameters::E0, Cg_dna_basepair_parameters::E0sb, Cg_dna_basepair_parameters::f2, Cg_dna_basepair_parameters::f3, get_mi_vector(), Bond_parameters::hydrogen_bond, Cg_dna_basepair_parameters::kd, M_PI, norm(), normalize(), ParticlePosition::p, Bonded_ia_parameters::p, params, PI, Cg_dna_basepair_parameters::psi10, Cg_dna_basepair_parameters::psi20, Particle::r, Cg_dna_basepair_parameters::r0, Cg_dna_basepair_parameters::r0sb, Cg_dna_basepair_parameters::sigma1, Cg_dna_basepair_parameters::sigma2, and SQR().
Referenced by add_bonded_energy().
int calc_hydrogen_bond_force (Particle * s1, Particle * b1, Particle * b2, Particle * s2, Bonded_ia_parameters * iaparams, double f_s1[3], double f_b1[3], double f_b2[3], double f_s2[3])
Definition at line 84 of file hydrogen_bond.cpp.
References Cg_dna_basepair_parameters::alpha, Cg_dna_basepair_parameters::alphasb, COS_MAX, COS_MIN, cross(), dot(), Cg_dna_basepair_parameters::E0, Cg_dna_basepair_parameters::E0sb, Cg_dna_basepair_parameters::f2, Cg_dna_basepair_parameters::f3, get_mi_vector(), Bond_parameters::hydrogen_bond, i, ParticleProperties::identity, Cg_dna_basepair_parameters::kd, M_PI, norm(), ParticlePosition::p, Particle::p, Bonded_ia_parameters::p, params, PI, PS, Cg_dna_basepair_parameters::psi10, Cg_dna_basepair_parameters::psi20, PV, Particle::r, Cg_dna_basepair_parameters::r0, Cg_dna_basepair_parameters::r0sb, Cg_dna_basepair_parameters::sigma1, Cg_dna_basepair_parameters::sigma2, and SQR().
Referenced by add_bonded_force().
double cos_angle (double * x1, double * x2) inline
Definition at line 66 of file hydrogen_bond.cpp.
References dot(), and norm().
Referenced by angle().
void cross (double * x1, double * x2, double * x3) inline
Definition at line 42 of file hydrogen_bond.cpp.
Referenced by calc_hydrogen_bond_energy(), calc_hydrogen_bond_force(), convert_torques_propagate_omega(), and crosslinkC().
double dot (double * x1, double * x2) inline
Definition at line 36 of file hydrogen_bond.cpp.
Referenced by calc_hydrogen_bond_energy(), calc_hydrogen_bond_force(), and cos_angle().
int hydrogen_bond_set_params (int bond_type, DoubleList * params)
Definition at line 472 of file hydrogen_bond.cpp.
References Cg_dna_basepair_parameters::alpha, Cg_dna_basepair_parameters::alphasb, BONDED_IA_CG_DNA_BASEPAIR, bonded_ia_params, DoubleList::e, Cg_dna_basepair_parameters::E0, Cg_dna_basepair_parameters::E0sb, ES_ERROR, ES_OK, Cg_dna_basepair_parameters::f2, Cg_dna_basepair_parameters::f3, Bond_parameters::hydrogen_bond, Cg_dna_basepair_parameters::kd, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Cg_dna_basepair_parameters::psi10, Cg_dna_basepair_parameters::psi20, Cg_dna_basepair_parameters::r0, Cg_dna_basepair_parameters::r0sb, Cg_dna_basepair_parameters::sigma1, Cg_dna_basepair_parameters::sigma2, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_hydrogen_bond().
double norm (double * x) inline
Definition at line 53 of file hydrogen_bond.cpp.
References norm2().
Referenced by add_volume_force(), calc_eigenvector_3x3(), calc_fluctuations(), calc_hydrogen_bond_energy(), calc_hydrogen_bond_force(), calc_volume(), calculate_pore_dist(), cos_angle(), normalize(), reflect_particle(), tclcommand_constraint_parse_wall(), and tclcommand_lbboundary_wall().
double norm2 (double * x) inline
Definition at line 49 of file hydrogen_bond.cpp.
References SQR().
Referenced by norm().
void normalize (double * x) inline
Definition at line 57 of file hydrogen_bond.cpp.
References norm().
Referenced by calc_hydrogen_bond_energy(), and calculate_hollow_cone_dist().