ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ibm_main.hpp File Reference
ibm_main.hpp File Reference
Main of the Bayreuth Immersed-Boundary implementation.
Functions
void update_mol_pos_particle (Particle *)
void update_mol_vel_particle (Particle *)
void distribute_mol_force ()
void IBM_UpdateParticlePositions ()
void IBM_ForcesIntoFluid_CPU ()
void IBM_ResetLBForces_CPU ()
void IBM_ForcesIntoFluid_GPU ()
void IBM_ResetLBForces_GPU ()
Detailed Description
Main of the Bayreuth Immersed-Boundary implementation.
Definition in file ibm_main.hpp.
Function Documentation
void distribute_mol_force ()
Definition at line 21 of file ibm_main.cpp.
void IBM_ForcesIntoFluid_CPU ()
Definition at line 45 of file ibm_main.cpp.
References Lattice::agrid, CellPList::cell, cell_structure, CoupleIBMParticleToFluid(), ghost_cells, ghost_communicator(), i, CellStructure::ibm_ghost_force_comm, lblattice, lbpar, local_cells, my_left, my_right, CellPList::n, ParticleList::n, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, and LB_Parameters::resend_halo.
Referenced by integrate_vv().
void IBM_ForcesIntoFluid_GPU ()
Definition at line 67 of file ibm_cuda.cu.
References cuda_safe_mem, ForcesIntoFluid_Kernel(), gpu_get_global_particle_vars_pointer_host(), IBM_cuda_mpi_get_particles(), IBM_ParticleDataInput_host, InitCUDA_IBM(), KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_particles, and this_node.
Referenced by integrate_vv().
void IBM_ResetLBForces_CPU ()
Definition at line 104 of file ibm_main.cpp.
References LB_Parameters::agrid, LB_Parameters::ext_force, LB_FluidNode::force, Lattice::halo_grid_volume, LB_FluidNode::has_force, i, lbfields, lblattice, lbpar, and LB_Parameters::tau.
Referenced by lb_stream_collide().
void IBM_ResetLBForces_GPU ()
Definition at line 47 of file ibm_cuda.cu.
References KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_nodes, ResetLBForces_Kernel(), and this_node.
void IBM_UpdateParticlePositions ()
Definition at line 128 of file ibm_main.cpp.
References announce_resort_particles(), CellPList::cell, distance2(), Particle::l, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticlePosition::p, Particle::p, ParticleLocal::p_old, ParticleList::part, ParticleVelocitiesFromLB_CPU(), ParticleVelocitiesFromLB_GPU(), Particle::r, resort_particles, skin, skin2, SQR(), time_step, and ParticleMomentum::v.
Referenced by integrate_vv().
void update_mol_pos_particle (Particle *)
Definition at line 19 of file ibm_main.cpp.
void update_mol_vel_particle (Particle *)
Definition at line 20 of file ibm_main.cpp.