ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ibm_cuda.cu File Reference
ibm_cuda.cu File Reference
#include "config.hpp"
#include "lbgpu.hpp"
#include "lb-boundaries.hpp"
#include "particle_data.hpp"
#include "cuda_utils.hpp"
#include "cuda_interface.hpp"
#include "immersed_boundary/ibm_main.hpp"
#include "immersed_boundary/ibm_cuda_interface.hpp"
Functions
__global__ void ResetLBForces_Kernel (LB_node_force_gpu node_f, const LB_parameters_gpu *const paraP)
__global__ void ParticleVelocitiesFromLB_Kernel (LB_nodes_gpu n_curr, const IBM_CUDA_ParticleDataInput *const particles_input, IBM_CUDA_ParticleDataOutput *const particles_output, LB_node_force_gpu node_f, const float *const lb_boundary_velocity, const LB_parameters_gpu *const para)
__global__ void ForcesIntoFluid_Kernel (const IBM_CUDA_ParticleDataInput *const particle_input, LB_node_force_gpu node_f, const LB_parameters_gpu *const paraP)
__device__ void atomicadd (float *address, float value)
void InitCUDA_IBM (const int numParticles)
void IBM_ResetLBForces_GPU ()
void IBM_ForcesIntoFluid_GPU ()
__device__ void Calc_m_from_n_IBM (const LB_nodes_gpu n_a, const unsigned int index, float *mode, const LB_parameters_gpu *const paraP)
void ParticleVelocitiesFromLB_GPU ()
Variables
IBM_CUDA_ParticleDataInput * IBM_ParticleDataInput_device = NULL
IBM_CUDA_ParticleDataOutput * IBM_ParticleDataOutput_device = NULL
LB_node_force_gpu node_f
struct for node force
LB_nodes_gpu * current_nodes
LB_parameters_gpu * paraIBM = NULL
float * lb_boundary_velocity_IBM = NULL
Function Documentation
__device__ void atomicadd (float * address, float value) inline
Definition at line 438 of file ibm_cuda.cu.
References atomicAdd().
Referenced by ForcesIntoFluid_Kernel().
__device__ void Calc_m_from_n_IBM (const LB_nodes_gpu n_a, const unsigned int index, float * mode, const LB_parameters_gpu *const paraP)
Definition at line 153 of file ibm_cuda.cu.
References LBQ, LB_parameters_gpu::number_of_nodes, para, and LB_nodes_gpu::vd.
Referenced by ParticleVelocitiesFromLB_Kernel().
__global__ void ForcesIntoFluid_Kernel (const IBM_CUDA_ParticleDataInput *const particle_input, LB_node_force_gpu node_f, const LB_parameters_gpu *const paraP)
Definition at line 233 of file ibm_cuda.cu.
References LB_parameters_gpu::agrid, atomicadd(), LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, IBM_CUDA_ParticleDataInput::f, LB_node_force_gpu::force, i, IBM_CUDA_ParticleDataInput::isVirtual, my_left, LB_parameters_gpu::number_of_nodes, LB_parameters_gpu::number_of_particles, para, IBM_CUDA_ParticleDataInput::pos, and LB_parameters_gpu::tau.
Referenced by IBM_ForcesIntoFluid_GPU().
void IBM_ForcesIntoFluid_GPU ()
Definition at line 67 of file ibm_cuda.cu.
References cuda_safe_mem, ForcesIntoFluid_Kernel(), gpu_get_global_particle_vars_pointer_host(), IBM_cuda_mpi_get_particles(), IBM_ParticleDataInput_host, InitCUDA_IBM(), KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_particles, and this_node.
Referenced by integrate_vv().
void IBM_ResetLBForces_GPU ()
Definition at line 47 of file ibm_cuda.cu.
References KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_nodes, ResetLBForces_Kernel(), and this_node.
void InitCUDA_IBM (const int numParticles)
Definition at line 106 of file ibm_cuda.cu.
References cuda_safe_mem, IBM_ParticleDataInput_host, IBM_ParticleDataOutput_host, lb_boundaries, lb_boundary_velocity_IBM, lb_get_para_pointer(), n_lb_boundaries, this_node, and LB_Boundary::velocity.
Referenced by IBM_ForcesIntoFluid_GPU().
void ParticleVelocitiesFromLB_GPU ()
Definition at line 197 of file ibm_cuda.cu.
References cuda_safe_mem, gpu_get_global_particle_vars_pointer_host(), IBM_cuda_mpi_send_velocities(), IBM_ParticleDataOutput_host, KERNELCALL, lb_boundary_velocity_IBM, lbpar_gpu, LB_parameters_gpu::number_of_particles, ParticleVelocitiesFromLB_Kernel(), and this_node.
Referenced by IBM_UpdateParticlePositions().
__global__ void ParticleVelocitiesFromLB_Kernel (LB_nodes_gpu n_curr, const IBM_CUDA_ParticleDataInput *const particles_input, IBM_CUDA_ParticleDataOutput *const particles_output, LB_node_force_gpu node_f, const float *const lb_boundary_velocity, const LB_parameters_gpu *const para)
Definition at line 297 of file ibm_cuda.cu.
References LB_parameters_gpu::agrid, LB_nodes_gpu::boundary, Calc_m_from_n_IBM(), LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, LB_node_force_gpu::force_buf, i, IBM_CUDA_ParticleDataInput::isVirtual, my_left, LB_parameters_gpu::number_of_nodes, LB_parameters_gpu::number_of_particles, para, IBM_CUDA_ParticleDataInput::pos, LB_parameters_gpu::rho, LB_parameters_gpu::tau, and IBM_CUDA_ParticleDataOutput::v.
Referenced by ParticleVelocitiesFromLB_GPU().
__global__ void ResetLBForces_Kernel (LB_node_force_gpu node_f, const LB_parameters_gpu *const paraP)
Definition at line 402 of file ibm_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::ext_force, LB_parameters_gpu::external_force, LB_node_force_gpu::force, LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, para, and LB_parameters_gpu::tau.
Referenced by IBM_ResetLBForces_GPU().
Variable Documentation
LB_nodes_gpu* current_nodes
Definition at line 102 of file lbgpu_cuda.cu.
IBM_CUDA_ParticleDataInput* IBM_ParticleDataInput_device = NULL
Definition at line 29 of file ibm_cuda.cu.
IBM_CUDA_ParticleDataOutput* IBM_ParticleDataOutput_device = NULL
Definition at line 30 of file ibm_cuda.cu.
float* lb_boundary_velocity_IBM = NULL
Definition at line 40 of file ibm_cuda.cu.
Referenced by InitCUDA_IBM(), and ParticleVelocitiesFromLB_GPU().
LB_node_force_gpu node_f
struct for node force
Definition at line 75 of file lbgpu_cuda.cu.
LB_parameters_gpu* paraIBM = NULL
Definition at line 39 of file ibm_cuda.cu.