ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ibm_triel.cpp File Reference
ibm_triel.cpp File Reference
#include "config.hpp"
#include "particle_data.hpp"
#include "interaction_data.hpp"
#include "grid.hpp"
#include "communication.hpp"
#include "immersed_boundary/ibm_triel.hpp"
Functions
void RotateForces (const double f1_rot[2], const double f2_rot[2], double f1[3], double f2[3], double v12[3], double v13[3])
Rotate calculated trielastic forces in the 2d plane back to the 3d plane Use knowledge that the x-axis in rotated system is parallel to r(p1->p2) in original system; To find the corresponding unit vector to y in the rotated system, construct vector perpendicular to r(p1->p2); note that f3 is not calculated here but is implicitly calculated by f3 = -(f1+f2) which is consistent with the literature.
int IBM_Triel_CalcForce (Particle *p1, Particle *p2, Particle *p3, Bonded_ia_parameters *iaparams)
int IBM_Triel_ResetParams (const int bond_type, const double k1, const double l0)
int IBM_Triel_SetParams (const int bond_type, const int ind1, const int ind2, const int ind3, const double max, const tElasticLaw elasticLaw, const double k1, const double k2)
Function Documentation
int IBM_Triel_CalcForce (Particle * p1, Particle * p2, Particle * p3, Bonded_ia_parameters * iaparams)
Definition at line 20 of file ibm_triel.cpp.
References IBM_Triel_Parameters::a1, IBM_Triel_Parameters::a2, IBM_Triel_Parameters::area0, IBM_Triel_Parameters::b1, IBM_Triel_Parameters::b2, IBM_Triel_Parameters::cosPhi0, IBM_Triel_Parameters::elasticLaw, ParticleForce::f, Particle::f, get_mi_vector(), i, Bond_parameters::ibm_triel, IBM_Triel_Parameters::k1, IBM_Triel_Parameters::k2, IBM_Triel_Parameters::l0, IBM_Triel_Parameters::lp0, IBM_Triel_Parameters::maxdist, NeoHookean, ParticlePosition::p, Bonded_ia_parameters::p, Particle::r, RotateForces(), scalar(), IBM_Triel_Parameters::sinPhi0, SQR(), sqrlen(), and vector_product().
Referenced by add_bonded_force().
int IBM_Triel_ResetParams (const int bond_type, const double k1, const double l0)
Definition at line 194 of file ibm_triel.cpp.
References IBM_Triel_Parameters::a1, IBM_Triel_Parameters::a2, IBM_Triel_Parameters::area0, IBM_Triel_Parameters::b1, IBM_Triel_Parameters::b2, BONDED_IA_IBM_TRIEL, bonded_ia_params, IBM_Triel_Parameters::cosPhi0, ES_ERROR, ES_OK, Bond_parameters::ibm_triel, IBM_Triel_Parameters::lp0, mpi_bcast_ia_params(), n_bonded_ia, Bonded_ia_parameters::p, and IBM_Triel_Parameters::sinPhi0.
Referenced by tclcommand_inter_parse_ibm_triel().
int IBM_Triel_SetParams (const int bond_type, const int ind1, const int ind2, const int ind3, const double max, const tElasticLaw elasticLaw, const double k1, const double k2)
Definition at line 235 of file ibm_triel.cpp.
References IBM_Triel_Parameters::a1, IBM_Triel_Parameters::a2, IBM_Triel_Parameters::area0, IBM_Triel_Parameters::b1, IBM_Triel_Parameters::b2, BONDED_IA_IBM_TRIEL, bonded_ia_params, IBM_Triel_Parameters::cosPhi0, IBM_Triel_Parameters::elasticLaw, ES_OK, get_mi_vector(), get_particle_data(), Bond_parameters::ibm_triel, IBM_Triel_Parameters::k1, IBM_Triel_Parameters::k2, IBM_Triel_Parameters::l0, IBM_Triel_Parameters::lp0, make_bond_type_exist(), IBM_Triel_Parameters::maxdist, mpi_bcast_ia_params(), Bonded_ia_parameters::num, ParticlePosition::p, Bonded_ia_parameters::p, Particle::r, scalar(), IBM_Triel_Parameters::sinPhi0, sqrlen(), Bonded_ia_parameters::type, and vector_product().
Referenced by tclcommand_inter_parse_ibm_triel().
void RotateForces (const double f1_rot[2], const double f2_rot[2], double f1[3], double f2[3], double v12[3], double v13[3])
Rotate calculated trielastic forces in the 2d plane back to the 3d plane Use knowledge that the x-axis in rotated system is parallel to r(p1->p2) in original system; To find the corresponding unit vector to y in the rotated system, construct vector perpendicular to r(p1->p2); note that f3 is not calculated here but is implicitly calculated by f3 = -(f1+f2) which is consistent with the literature.
Definition at line 306 of file ibm_triel.cpp.
References i, scalar(), and unit_vector().
Referenced by IBM_Triel_CalcForce().