ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ibm_volume_conservation.hpp File Reference
ibm_volume_conservation.hpp File Reference
Functions
int IBM_VolumeConservation_SetParams (const int bond_type, const int softID, const double kappaV)
int IBM_VolumeConservation_ResetParams (const int bond_type, const double volRef)
void IBM_InitVolumeConservation ()
void IBM_VolumeConservation ()
Function Documentation
void IBM_InitVolumeConservation ()
Definition at line 43 of file ibm_volume_conservation.cpp.
References BONDED_IA_IBM_VOLUME_CONSERVATION, bonded_ia_params, CalcVolumes(), i, Bond_parameters::ibmVolConsParameters, mpi_bcast_ia_params(), n_bonded_ia, Bonded_ia_parameters::p, IBM_VolCons_Parameters::softID, IBM_VolCons_Parameters::volRef, VolumeInitDone, and VolumesCurrent.
Referenced by integrate_vv().
void IBM_VolumeConservation ()
Definition at line 27 of file ibm_volume_conservation.cpp.
References CalcVolumeForce(), and CalcVolumes().
Referenced by force_calc().
int IBM_VolumeConservation_ResetParams (const int bond_type, const double volRef)
Definition at line 84 of file ibm_volume_conservation.cpp.
References BONDED_IA_IBM_VOLUME_CONSERVATION, bonded_ia_params, ES_ERROR, ES_OK, Bond_parameters::ibmVolConsParameters, mpi_bcast_ia_params(), n_bonded_ia, Bonded_ia_parameters::p, and IBM_VolCons_Parameters::volRef.
Referenced by tclcommand_inter_parse_ibm_volume_conservation().
int IBM_VolumeConservation_SetParams (const int bond_type, const int softID, const double kappaV)
Definition at line 105 of file ibm_volume_conservation.cpp.
References BONDED_IA_IBM_VOLUME_CONSERVATION, bonded_ia_params, ES_ERROR, ES_OK, Bond_parameters::ibmVolConsParameters, IBM_VolCons_Parameters::kappaV, make_bond_type_exist(), MaxNumIBM, mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, IBM_VolCons_Parameters::softID, Bonded_ia_parameters::type, and IBM_VolCons_Parameters::volRef.
Referenced by tclcommand_inter_parse_ibm_volume_conservation().