ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ibm_cuda_interface.hpp File Reference
ibm_cuda_interface.hpp File Reference
Data Structures
struct IBM_CUDA_ParticleDataInput
struct IBM_CUDA_ParticleDataOutput
Functions
void IBM_cuda_mpi_send_velocities ()
void IBM_cuda_mpi_get_particles ()
void ParticleVelocitiesFromLB_GPU ()
Variables
IBM_CUDA_ParticleDataInput * IBM_ParticleDataInput_host
IBM_CUDA_ParticleDataOutput * IBM_ParticleDataOutput_host
Function Documentation
void IBM_cuda_mpi_get_particles ()
Definition at line 38 of file ibm_cuda_interface.cpp.
References CellPList::cell, cells_get_n_particles(), comm_cart, COMM_TRACE, IBM_CUDA_ParticleDataInput::f, ParticleForce::f, Particle::f, fold_position(), free, i, IBM_cuda_mpi_get_particles_slave(), IBM_CUDA_ParticleDataInput::isVirtual, ParticleProperties::isVirtual, local_cells, malloc, MPI_BYTE, MPI_Gather(), MPI_INT, MPI_Recv(), CellPList::n, ParticleList::n, n_nodes, n_part, Particle::p, ParticleList::part, IBM_CUDA_ParticleDataInput::pos, REQ_CUDAIBMGETPART, and this_node.
Referenced by IBM_ForcesIntoFluid_GPU().
void IBM_cuda_mpi_send_velocities ()
Definition at line 157 of file ibm_cuda_interface.cpp.
References CellPList::cell, cells_get_n_particles(), comm_cart, COMM_TRACE, free, i, IBM_cuda_mpi_send_velocities_slave(), ParticleProperties::isVirtual, local_cells, Particle::m, malloc, MPI_BYTE, MPI_Gather(), MPI_INT, MPI_Send(), CellPList::n, ParticleList::n, n_nodes, n_part, Particle::p, ParticleList::part, REQ_CUDAIBMSENDVEL, this_node, IBM_CUDA_ParticleDataOutput::v, and ParticleMomentum::v.
Referenced by ParticleVelocitiesFromLB_GPU().
void ParticleVelocitiesFromLB_GPU ()
Definition at line 197 of file ibm_cuda.cu.
References cuda_safe_mem, gpu_get_global_particle_vars_pointer_host(), IBM_cuda_mpi_send_velocities(), IBM_ParticleDataOutput_host, KERNELCALL, lb_boundary_velocity_IBM, lbpar_gpu, LB_parameters_gpu::number_of_particles, ParticleVelocitiesFromLB_Kernel(), and this_node.
Referenced by IBM_UpdateParticlePositions().
Variable Documentation
IBM_CUDA_ParticleDataInput* IBM_ParticleDataInput_host
Definition at line 25 of file ibm_cuda_interface.cpp.
Referenced by IBM_ForcesIntoFluid_GPU(), and InitCUDA_IBM().
IBM_CUDA_ParticleDataOutput* IBM_ParticleDataOutput_host
Definition at line 26 of file ibm_cuda_interface.cpp.
Referenced by InitCUDA_IBM(), and ParticleVelocitiesFromLB_GPU().