ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ibm_tribend_helpers.hpp File Reference
ibm_tribend_helpers.hpp File Reference
Data Structures
struct Vector3D
struct Matrix3D
Functions
void get_mi_vector_const (double res[3], const double a[3], const double b[3])
void Subtr (Vector3D &res, const Vector3D &a, const Vector3D &b)
void Subtr (Vector3D &res, const Particle *const a, const Particle *const b)
double LengthSqr (const Vector3D &a)
double Length (const Vector3D &a)
double ScalarProduct (const Vector3D &a, const Vector3D &b)
void DyadicProduct (Matrix3D &res, const Vector3D &a, const Vector3D &b)
void AddTo (Matrix3D &a, const Matrix3D &b)
void AddScalarTo (Matrix3D &a, const double s)
void AddTo (Vector3D &a, const Vector3D &b)
void Multiply (Vector3D &res, const Vector3D &a, const double f)
void LeftVectorMatrix (Vector3D &res, const Vector3D &v, const Matrix3D &m)
double CalcCosTheta (const Particle *const xi, const Particle *const xj, const Particle *const xm)
Calculates the cosine of the angle between the vectors xi-xm and xj-xm.
double CalcCot (double cosTheta)
Given the cosine of the angle, this function returns the cotangens. Note: This assumes that the angle is in [0;Pi].
void CalcCotDerivativeGompperAnalyt (Vector3D &cosThetaDeriv, const Particle *const xi, const Particle *const xj, const Particle *const xm, const int derivativeNodeID)
Calculates the gradient of the cotangens of the angle between xi-xm and xj-xm with respect to the node with ID derivativeNodeID.
Function Documentation
void AddScalarTo (Matrix3D & a, const double s) inline
Definition at line 86 of file ibm_tribend_helpers.hpp.
References Matrix3D::el.
Referenced by CalcForceGompper().
void AddTo (Matrix3D & a, const Matrix3D & b) inline
Definition at line 79 of file ibm_tribend_helpers.hpp.
References Matrix3D::el, and i.
Referenced by CalcForceGompper().
void AddTo (Vector3D & a, const Vector3D & b) inline
Definition at line 94 of file ibm_tribend_helpers.hpp.
References Vector3D::el.
double CalcCosTheta (const Particle *const xi, const Particle *const xj, const Particle *const xm) inline
Calculates the cosine of the angle between the vectors xi-xm and xj-xm.
Definition at line 124 of file ibm_tribend_helpers.hpp.
References Length(), ScalarProduct(), and Subtr().
Referenced by CalcCotDerivativeGompperAnalyt(), and CalcForceGompper().
double CalcCot (double cosTheta) inline
Given the cosine of the angle, this function returns the cotangens. Note: This assumes that the angle is in [0;Pi].
Definition at line 138 of file ibm_tribend_helpers.hpp.
Referenced by CalcForceGompper().
void CalcCotDerivativeGompperAnalyt (Vector3D & cosThetaDeriv, const Particle *const xi, const Particle *const xj, const Particle *const xm, const int derivativeNodeID)
Calculates the gradient of the cotangens of the angle between xi-xm and xj-xm with respect to the node with ID derivativeNodeID.
Definition at line 149 of file ibm_tribend_helpers.hpp.
References CalcCosTheta(), Vector3D::el, i, ParticleProperties::identity, Length(), Particle::p, and Subtr().
Referenced by CalcForceGompper().
void DyadicProduct (Matrix3D & res, const Vector3D & a, const Vector3D & b) inline
Definition at line 65 of file ibm_tribend_helpers.hpp.
References Vector3D::el, and Matrix3D::el.
Referenced by CalcForceGompper().
void get_mi_vector_const (double res[3], const double a[3], const double b[3]) inline
Definition at line 19 of file ibm_tribend_helpers.hpp.
References box_l, box_l_i, dround(), i, and PERIODIC.
Referenced by Subtr().
void LeftVectorMatrix (Vector3D & res, const Vector3D & v, const Matrix3D & m) inline
Definition at line 110 of file ibm_tribend_helpers.hpp.
References Vector3D::el, and Matrix3D::el.
Referenced by CalcForceGompper().
double Length (const Vector3D & a) inline
Definition at line 52 of file ibm_tribend_helpers.hpp.
References LengthSqr().
Referenced by CalcCosTheta(), and CalcCotDerivativeGompperAnalyt().
double LengthSqr (const Vector3D & a) inline
Definition at line 44 of file ibm_tribend_helpers.hpp.
References Vector3D::el.
Referenced by CalcForceGompper(), and Length().
void Multiply (Vector3D & res, const Vector3D & a, const double f) inline
Definition at line 102 of file ibm_tribend_helpers.hpp.
References Vector3D::el.
Referenced by CalcForceGompper().
double ScalarProduct (const Vector3D & a, const Vector3D & b) inline
Definition at line 58 of file ibm_tribend_helpers.hpp.
References Vector3D::el.
Referenced by CalcCosTheta().
void Subtr (Vector3D & res, const Vector3D & a, const Vector3D & b) inline
Definition at line 33 of file ibm_tribend_helpers.hpp.
References Vector3D::el, and get_mi_vector_const().
Referenced by CalcCosTheta(), CalcCotDerivativeGompperAnalyt(), and CalcForceGompper().
void Subtr (Vector3D & res, const Particle *const a, const Particle *const b) inline
Definition at line 38 of file ibm_tribend_helpers.hpp.
References Vector3D::el, get_mi_vector_const(), ParticlePosition::p, and Particle::r.