ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ibm_tribend.hpp File Reference
ibm_tribend.hpp File Reference
Functions
int IBM_Tribend_SetParams (const int bond_type, const int ind1, const int ind2, const int ind3, const int ind4, const tBendingMethod method, const double kb, const bool flat)
int IBM_Tribend_ResetParams (const int bond_type, const double kb)
void IBM_Tribend_CalcForce (Particle *p1, const int numPartners, Particle **const partners, const Bonded_ia_parameters &iaparams)
Variables
double maxBendingForce
double maxBendingDist
double maxX
Function Documentation
void IBM_Tribend_CalcForce (Particle * p1, const int numPartners, Particle **const partners, const Bonded_ia_parameters & iaparams)
Definition at line 26 of file ibm_tribend.cpp.
References CalcForceGompper(), ParticleForce::f, Particle::f, get_mi_vector(), i, Bond_parameters::ibm_tribend, IBM_Tribend_Parameters::kb, IBM_Tribend_Parameters::method, NodeNeighbors, ParticlePosition::p, Bonded_ia_parameters::p, Particle::r, scalar(), sqrlen(), IBM_Tribend_Parameters::theta0, TriangleNormals, and vector_product().
Referenced by add_bonded_force().
int IBM_Tribend_ResetParams (const int bond_type, const double kb)
Definition at line 146 of file ibm_tribend.cpp.
References BONDED_IA_IBM_TRIBEND, bonded_ia_params, ES_ERROR, ES_OK, mpi_bcast_ia_params(), and n_bonded_ia.
Referenced by tclcommand_inter_parse_ibm_tribend().
int IBM_Tribend_SetParams (const int bond_type, const int ind1, const int ind2, const int ind3, const int ind4, const tBendingMethod method, const double kb, const bool flat)
Definition at line 166 of file ibm_tribend.cpp.
References BONDED_IA_IBM_TRIBEND, bonded_ia_params, ES_ERROR, ES_OK, get_mi_vector(), get_particle_data(), Bond_parameters::ibm_tribend, IBM_Tribend_Parameters::kb, make_bond_type_exist(), IBM_Tribend_Parameters::method, mpi_bcast_ia_params(), NodeNeighbors, Bonded_ia_parameters::num, ParticlePosition::p, Bonded_ia_parameters::p, PI, Particle::r, scalar(), IBM_Tribend_Parameters::theta0, TriangleNormals, Bonded_ia_parameters::type, unit_vector(), and vector_product().
Referenced by tclcommand_inter_parse_ibm_tribend().
Variable Documentation
double maxBendingDist
double maxBendingForce
double maxX