ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ibm_main.cpp File Reference
ibm_main.cpp File Reference
Main of the Bayreuth Immersed-Boundary implementation.
#include "config.hpp"
#include "particle_data.hpp"
#include "lb.hpp"
#include "cells.hpp"
#include "integrate.hpp"
#include "halo.hpp"
#include "lb-boundaries.hpp"
#include "immersed_boundary/ibm_main.hpp"
#include "immersed_boundary/ibm_cuda_interface.hpp"
Functions
void update_mol_pos_particle (Particle *)
void update_mol_vel_particle (Particle *)
void distribute_mol_force ()
void CoupleIBMParticleToFluid (Particle *p)
void ParticleVelocitiesFromLB_CPU ()
bool IsHalo (const int indexCheck)
void GetIBMInterpolatedVelocity (double *p, double *const v, double *const forceAdded)
void IBM_ForcesIntoFluid_CPU ()
void IBM_ResetLBForces_CPU ()
void IBM_UpdateParticlePositions ()
Variables
bool * isHaloCache = NULL
HaloCommunicator update_halo_comm
Communicator for halo exchange between processors.
Detailed Description
Main of the Bayreuth Immersed-Boundary implementation.
Definition in file ibm_main.cpp.
Function Documentation
void CoupleIBMParticleToFluid (Particle * p)
Definition at line 171 of file ibm_main.cpp.
References LB_Parameters::agrid, ParticleForce::f, Particle::f, index_t, IsHalo(), lbfields, lblattice, lbpar, Lattice::map_position_to_lattice(), ParticlePosition::p, Particle::r, LB_Parameters::tau, and time_step.
Referenced by IBM_ForcesIntoFluid_CPU().
void distribute_mol_force ()
Definition at line 21 of file ibm_main.cpp.
Referenced by force_calc().
void GetIBMInterpolatedVelocity (double * p, double *const v, double *const forceAdded)
Definition at line 214 of file ibm_main.cpp.
References LB_Parameters::agrid, boundary, LB_FluidNode::boundary, LB_Parameters::ext_force, LB_FluidNode::force_buf, index_t, lb_boundaries, lb_calc_modes(), lbboundary_mindist_position(), lbfields, lblattice, lbpar, Lattice::map_position_to_lattice(), LB_Parameters::rho, LB_Parameters::tau, and LB_Boundary::velocity.
Referenced by ParticleVelocitiesFromLB_CPU().
void IBM_ForcesIntoFluid_CPU ()
Definition at line 45 of file ibm_main.cpp.
References Lattice::agrid, CellPList::cell, cell_structure, CoupleIBMParticleToFluid(), ghost_cells, ghost_communicator(), i, CellStructure::ibm_ghost_force_comm, lblattice, lbpar, local_cells, my_left, my_right, CellPList::n, ParticleList::n, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, and LB_Parameters::resend_halo.
Referenced by integrate_vv().
void IBM_ResetLBForces_CPU ()
Definition at line 104 of file ibm_main.cpp.
References LB_Parameters::agrid, LB_Parameters::ext_force, LB_FluidNode::force, Lattice::halo_grid_volume, LB_FluidNode::has_force, i, lbfields, lblattice, lbpar, and LB_Parameters::tau.
Referenced by lb_stream_collide().
void IBM_UpdateParticlePositions ()
Definition at line 128 of file ibm_main.cpp.
References announce_resort_particles(), CellPList::cell, distance2(), Particle::l, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticlePosition::p, Particle::p, ParticleLocal::p_old, ParticleList::part, ParticleVelocitiesFromLB_CPU(), ParticleVelocitiesFromLB_GPU(), Particle::r, resort_particles, skin, skin2, SQR(), time_step, and ParticleMomentum::v.
Referenced by integrate_vv().
bool IsHalo (const int indexCheck)
Definition at line 339 of file ibm_main.cpp.
References Lattice::grid, Lattice::halo_grid, Lattice::halo_grid_volume, Lattice::halo_offset, i, isHaloCache, and lblattice.
Referenced by CoupleIBMParticleToFluid().
void ParticleVelocitiesFromLB_CPU ()
Definition at line 374 of file ibm_main.cpp.
References Lattice::agrid, LB_Parameters::agrid, CellPList::cell, cell_structure, CellStructure::collect_ghost_force_comm, ParticleForce::f, Particle::f, GetIBMInterpolatedVelocity(), ghost_cells, ghost_communicator(), halo_communication(), lbfluid, lblattice, lbpar, local_cells, Particle::m, my_left, my_right, CellPList::n, ParticleList::n, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, LB_Parameters::resend_halo, LB_Parameters::tau, and ParticleMomentum::v.
Referenced by IBM_UpdateParticlePositions().
void update_mol_pos_particle (Particle *)
Definition at line 19 of file ibm_main.cpp.
Referenced by update_mol_pos(), and update_mol_pos_cfg().
void update_mol_vel_particle (Particle *)
Definition at line 20 of file ibm_main.cpp.
Referenced by update_mol_vel().
Variable Documentation
bool* isHaloCache = NULL
Definition at line 32 of file ibm_main.cpp.
Referenced by IsHalo().
HaloCommunicator update_halo_comm
Communicator for halo exchange between processors.
Definition at line 109 of file lb.cpp.