ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: iccp3m.cpp File Reference
iccp3m.cpp File Reference
Detailed Information about the method is included in the corresponding header file iccp3m.hpp.
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <cstddef>
#include <cmath>
#include <ctime>
#include "iccp3m.hpp"
#include "p3m.hpp"
#include "elc.hpp"
#include "mmm2d.hpp"
#include "mmm1d.hpp"
#include "communication.hpp"
#include "utils.hpp"
#include "verlet.hpp"
#include "cells.hpp"
#include "particle_data.hpp"
#include "interaction_data.hpp"
#include "domain_decomposition.hpp"
#include "forces.hpp"
#include "config.hpp"
#include "global.hpp"
Macros
#define LIST_INCREMENT 20
Granularity of the verlet list.
Functions
void init_forces_iccp3m ()
void calc_long_range_forces_iccp3m ()
void on_particle_change ()
void iccp3m_init (void)
The initialisation of ICCP3M with zero values for all variables.
int bcast_iccp3m_cfg (void)
int iccp3m_iteration ()
The main iterative scheme, where the surface element charges are calculated self-consistently.
void force_calc_iccp3m ()
Calculation of the electrostatic forces between source charges (= real charges) and wall charges.
void layered_calculate_ia_iccp3m ()
nonbonded and bonded force calculation using the verlet list
void build_verlet_lists_and_calc_verlet_ia_iccp3m ()
Calculate the short range part of electrostatic interaction using verlet lists.
void calculate_verlet_ia_iccp3m ()
Calculate he short range part of electrostatic interaction using verlet lists, if verlet lists have already been properly built.
void calc_link_cell_iccp3m ()
Calculate he short range part of electrostatic interaction using for linked cell systems.
void nsq_calculate_ia_iccp3m ()
Calculate he short range part of electrostatic interaction using for n-squared cell systems.
Private Functions
void add_pair_iccp3m (PairList *pl, Particle *p1, Particle *p2)
Add a particle pair to a verlet pair list.
void resize_verlet_list_iccp3m (PairList *pl)
void init_local_particle_force_iccp3m (Particle *part)
initialize the forces for a real particle
void init_ghost_force_iccp3m (Particle *part)
initialize the forces for a ghost particle
int imod (int x, int y)
void iccp3m_revive_forces ()
void iccp3m_store_forces ()
void reset_forces ()
int iccp3m_sanity_check ()
check sanity of parameters for use with ICCP3M
Variables
iccp3m_struct iccp3m_cfg
int iccp3m_initialized = 0
Cell * local_icc
CellPList me_do_ghosts_icc
Detailed Description
Detailed Information about the method is included in the corresponding header file iccp3m.hpp.
Definition in file iccp3m.cpp.
Macro Definition Documentation
#define LIST_INCREMENT 20
Granularity of the verlet list.
Definition at line 76 of file iccp3m.cpp.
Referenced by add_pair_iccp3m(), and resize_verlet_list_iccp3m().
Function Documentation
void add_pair_iccp3m (PairList * pl, Particle * p1, Particle * p2) inline
Add a particle pair to a verlet pair list.
Checks verlet pair list size and reallocates memory if necessary.
Parameters
p1 Pointer to paricle one.
p2 Pointer to paricle two.
pl Pointer to the verlet pair list.
Definition at line 619 of file iccp3m.cpp.
References LIST_INCREMENT, PairList::max, PairList::n, PairList::pair, and realloc.
Referenced by build_verlet_lists_and_calc_verlet_ia_iccp3m().
int bcast_iccp3m_cfg (void)
Definition at line 100 of file iccp3m.cpp.
References iccp3m_struct::areas, iccp3m_struct::citeration, comm_cart, iccp3m_struct::convergence, iccp3m_struct::ein, iccp3m_struct::eout, iccp3m_struct::extx, iccp3m_struct::exty, iccp3m_struct::extz, iccp3m_struct::first_id, i, MPI_Bcast(), MPI_DOUBLE, MPI_INT, iccp3m_struct::n_ic, iccp3m_struct::num_iteration, iccp3m_struct::nvectorx, iccp3m_struct::nvectory, iccp3m_struct::nvectorz, realloc, iccp3m_struct::relax, iccp3m_struct::set_flag, iccp3m_struct::sigma, and this_node.
Referenced by mpi_iccp3m_init(), and mpi_iccp3m_init_slave().
void build_verlet_lists_and_calc_verlet_ia_iccp3m ()
Calculate the short range part of electrostatic interaction using verlet lists.
A modified version of build_verlet_lists_and_calc_verlet_ia() in verlet.hpp
Definition at line 336 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), add_pair_iccp3m(), box_l, CellPList::cell, DomainDecomposition::cell_inter, check_id, dd, distance2vec(), do_nonbonded(), errexit(), get_ia_param(), i, ParticleProperties::identity, local_cells, IA_parameters::max_cut, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, n_nodes, n_part, neighbor, IA_Neighbor_List::nList, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticleList::part, PI, IA_Neighbor::pList, Particle::r, rebuild_verletlist, resize_verlet_list_iccp3m(), skin, SQR(), this_node, ParticleProperties::type, DomainDecomposition::use_vList, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by force_calc_iccp3m().
void calc_link_cell_iccp3m ()
Calculate he short range part of electrostatic interaction using for linked cell systems.
A modified version of calc_link_cell() in domain_decomposition.hpp
Definition at line 436 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), CellPList::cell, DomainDecomposition::cell_inter, dd, distance2vec(), get_ia_param(), i, local_cells, IA_parameters::max_cut, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, neighbor, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, ParticleList::part, IA_Neighbor::pList, Particle::r, rebuild_verletlist, skin, SQR(), and ParticleProperties::type.
Referenced by force_calc_iccp3m().
void calc_long_range_forces_iccp3m ()
Definition at line 569 of file iccp3m.cpp.
References coulomb, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_MMM2D, COULOMB_P3M, Coulomb_parameters::method, MMM2D_add_far_force(), MMM2D_dielectric_layers_force_contribution(), and runtimeError.
Referenced by force_calc_iccp3m().
void calculate_verlet_ia_iccp3m ()
Calculate he short range part of electrostatic interaction using verlet lists, if verlet lists have already been properly built.
A modified version of calculate_verlet_ia() in verlet.hpp
Definition at line 409 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), CellPList::cell, DomainDecomposition::cell_inter, dd, distance2vec(), i, local_cells, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, PairList::pair, ParticleList::part, Particle::r, and IA_Neighbor::vList.
Referenced by force_calc_iccp3m().
void force_calc_iccp3m ()
Calculation of the electrostatic forces between source charges (= real charges) and wall charges.
For each electrostatic method the proper functions for short and long range parts are called. Long Range Parts are calculated directly, short range parts need helper functions according to the particle data organisation. A modified version of force_calc in forces.hpp.
Definition at line 245 of file iccp3m.cpp.
References build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_link_cell_iccp3m(), calc_long_range_forces_iccp3m(), calculate_verlet_ia_iccp3m(), cell_structure, CELL_STRUCTURE_DOMDEC, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, dd, init_forces_iccp3m(), layered_calculate_ia_iccp3m(), nsq_calculate_ia_iccp3m(), rebuild_verletlist, CellStructure::type, and DomainDecomposition::use_vList.
Referenced by iccp3m_iteration().
void iccp3m_init (void)
The initialisation of ICCP3M with zero values for all variables.
Definition at line 78 of file iccp3m.cpp.
References iccp3m_struct::areas, iccp3m_struct::citeration, iccp3m_struct::convergence, iccp3m_struct::ein, iccp3m_struct::eout, iccp3m_struct::extx, iccp3m_struct::exty, iccp3m_struct::extz, iccp3m_struct::first_id, iccp3m_struct::num_iteration, iccp3m_struct::nvectorx, iccp3m_struct::nvectory, iccp3m_struct::nvectorz, iccp3m_struct::relax, and iccp3m_struct::set_flag.
Referenced by mpi_iccp3m_init_slave(), and tclcommand_iccp3m().
int iccp3m_iteration ()
The main iterative scheme, where the surface element charges are calculated self-consistently.
Definition at line 145 of file iccp3m.cpp.
References iccp3m_struct::areas, Coulomb_parameters::bjerrum, CellPList::cell, iccp3m_struct::citeration, comm_cart, iccp3m_struct::convergence, coulomb, iccp3m_struct::ein, iccp3m_struct::eout, iccp3m_struct::extx, iccp3m_struct::exty, iccp3m_struct::extz, ParticleForce::f, Particle::f, iccp3m_struct::first_id, force_calc_iccp3m(), i, iccp3m_sanity_check(), ParticleProperties::identity, local_cells, MPI_Allreduce(), MPI_DOUBLE, MPI_MAX, CellPList::n, ParticleList::n, iccp3m_struct::n_ic, iccp3m_struct::num_iteration, iccp3m_struct::nvectorx, iccp3m_struct::nvectory, iccp3m_struct::nvectorz, on_particle_change(), Particle::p, ParticleList::part, ParticleProperties::q, iccp3m_struct::relax, runtimeError, and iccp3m_struct::sigma.
Referenced by force_calc(), mpi_iccp3m_iteration(), and mpi_iccp3m_iteration_slave().
void iccp3m_revive_forces ()
Definition at line 698 of file iccp3m.cpp.
References CellPList::cell, ParticleForce::f, Particle::f, iccp3m_struct::fx, iccp3m_struct::fy, iccp3m_struct::fz, i, ParticleProperties::identity, local_cells, CellPList::n, ParticleList::n, Particle::p, and ParticleList::part.
int iccp3m_sanity_check ()
check sanity of parameters for use with ICCP3M
Definition at line 732 of file iccp3m.cpp.
References coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_RF, INTEG_METHOD_NPT_ISO, integ_switch, Coulomb_parameters::method, and runtimeError.
Referenced by iccp3m_iteration().
void iccp3m_store_forces ()
Definition at line 714 of file iccp3m.cpp.
References CellPList::cell, ParticleForce::f, Particle::f, iccp3m_struct::fx, iccp3m_struct::fy, iccp3m_struct::fz, i, ParticleProperties::identity, local_cells, CellPList::n, ParticleList::n, Particle::p, and ParticleList::part.
int imod (int x, int y)
Definition at line 675 of file iccp3m.cpp.
void init_forces_iccp3m ()
Definition at line 525 of file iccp3m.cpp.
References CellPList::cell, ghost_cells, i, init_ghost_force_iccp3m(), init_local_particle_force_iccp3m(), INTEG_METHOD_NPT_ISO, integ_switch, local_cells, CellPList::n, ParticleList::n, ParticleList::part, and runtimeError.
Referenced by force_calc_iccp3m().
void init_ghost_force_iccp3m (Particle * part) inline
initialize the forces for a ghost particle
Definition at line 660 of file iccp3m.cpp.
References ParticleForce::f, Particle::f, and ParticleForce::torque.
Referenced by init_forces_iccp3m().
void init_local_particle_force_iccp3m (Particle * part) inline
initialize the forces for a real particle
Definition at line 645 of file iccp3m.cpp.
References ParticleForce::f, Particle::f, and ParticleForce::torque.
Referenced by init_forces_iccp3m().
void layered_calculate_ia_iccp3m ()
nonbonded and bonded force calculation using the verlet list
Calculation of short range part of electrostatic interaction in layered systems A modified version of layered_calculate_ia in layered.hpp.
Definition at line 279 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), CELL_TRACE, cells, do_nonbonded(), i, Particle::l, layered_get_mi_vector(), ParticleList::n, n_layers, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, sqrlen(), and this_node.
Referenced by force_calc_iccp3m().
void nsq_calculate_ia_iccp3m ()
Calculate he short range part of electrostatic interaction using for n-squared cell systems.
A modified version of nsq_calculate_ia nsquare.hpp.
Definition at line 481 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), CellPList::cell, get_mi_vector(), Particle::l, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, and sqrlen().
Referenced by force_calc_iccp3m().
void on_particle_change ()
Definition at line 272 of file initialize.cpp.
Referenced by iccp3m_iteration(), integrate_reaction(), mpi_galilei_transform(), mpi_galilei_transform_slave(), mpi_kill_particle_forces(), mpi_kill_particle_forces_slave(), mpi_kill_particle_motion(), mpi_kill_particle_motion_slave(), mpi_place_new_particle(), mpi_place_new_particle_slave(), mpi_place_particle(), mpi_place_particle_slave(), mpi_remove_particle_slave(), mpi_rescale_particles(), mpi_rescale_particles_slave(), mpi_send_bond(), mpi_send_bond_slave(), mpi_send_configtemp_flag(), mpi_send_configtemp_flag_slave(), mpi_send_dip(), mpi_send_dip_slave(), mpi_send_dipm(), mpi_send_dipm_slave(), mpi_send_exclusion(), mpi_send_exclusion_slave(), mpi_send_ext_force(), mpi_send_ext_force_slave(), mpi_send_ext_torque(), mpi_send_ext_torque_slave(), mpi_send_f(), mpi_send_f_slave(), mpi_send_mass(), mpi_send_mass_slave(), mpi_send_mol_id(), mpi_send_mol_id_slave(), mpi_send_mu_E(), mpi_send_mu_E_slave(), mpi_send_omega(), mpi_send_omega_slave(), mpi_send_q(), mpi_send_q_slave(), mpi_send_quat(), mpi_send_quat_slave(), mpi_send_rotation(), mpi_send_rotation_slave(), mpi_send_rotational_inertia(), mpi_send_rotational_inertia_slave(), mpi_send_smaller_timestep_flag(), mpi_send_smaller_timestep_flag_slave(), mpi_send_solvation(), mpi_send_solvation_slave(), mpi_send_swimming(), mpi_send_swimming_slave(), mpi_send_torque(), mpi_send_torque_slave(), mpi_send_type(), mpi_send_type_slave(), mpi_send_v(), mpi_send_v_slave(), mpi_send_virtual(), mpi_send_virtual_slave(), mpi_send_vs_relative(), mpi_send_vs_relative_slave(), mpi_set_particle_gamma(), mpi_set_particle_gamma_slave(), mpi_set_particle_temperature(), and mpi_set_particle_temperature_slave().
void reset_forces ()
Definition at line 685 of file iccp3m.cpp.
References CellPList::cell, ParticleForce::f, Particle::f, i, local_cells, CellPList::n, ParticleList::n, and ParticleList::part.
void resize_verlet_list_iccp3m (PairList * pl)
Definition at line 633 of file iccp3m.cpp.
References LIST_INCREMENT, PairList::max, PairList::n, PairList::pair, and realloc.
Referenced by build_verlet_lists_and_calc_verlet_ia_iccp3m().
Variable Documentation
iccp3m_struct iccp3m_cfg
Definition at line 54 of file iccp3m.cpp.
Referenced by force_calc(), tclcommand_iccp3m(), tclcommand_iccp3m_parse_double_list(), and tclcommand_iccp3m_parse_normals().
int iccp3m_initialized = 0
Definition at line 56 of file iccp3m.cpp.
Referenced by force_calc(), mpi_iccp3m_init_slave(), and tclcommand_iccp3m().
Cell* local_icc
Definition at line 67 of file iccp3m.cpp.
CellPList me_do_ghosts_icc
Definition at line 68 of file iccp3m.cpp.