ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: iccp3m_tcl.cpp File Reference
iccp3m_tcl.cpp File Reference
#include "iccp3m.hpp"
#include "parser.hpp"
#include <string>
#include <sstream>
#include <iostream>
Enumerations
enum {
ICCP3M_AREA, ICCP3M_EPSILON, ICCP3M_NORMAL, ICCP3M_SIGMA,
ICCP3M_EXTFIELD
}
Functions
int tclcommand_iccp3m_parse_normals (Tcl_Interp *interp, int n_ic, char *string)
int tclcommand_iccp3m_parse_double_list (Tcl_Interp *interp, int n_ic, char *string, int flag)
int tclcommand_iccp3m (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Parses the ICCP3M command.
Enumeration Type Documentation
anonymous enum
Enumerator
ICCP3M_AREA
ICCP3M_EPSILON
ICCP3M_NORMAL
ICCP3M_SIGMA
ICCP3M_EXTFIELD
Definition at line 34 of file iccp3m_tcl.cpp.
Function Documentation
int tclcommand_iccp3m (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Parses the ICCP3M command.
Implementation of the tcl-command
iccp3m { <last_ind_id> <e1> <num_iteration> <convergence> <relaxation> <area> <normal_components> <e_in/e_out> [<ext_field>] | iterate } ICC sets up and calculates induced charges on dielectric surfaces.
Definition at line 40 of file iccp3m_tcl.cpp.
References iccp3m_struct::areas, ARG0_IS_S, ARG1_IS_D, ARG1_IS_I, ARG_IS_D, ARG_IS_I, ARG_IS_S, iccp3m_struct::citeration, iccp3m_struct::convergence, iccp3m_struct::ein, iccp3m_struct::eout, iccp3m_struct::extx, iccp3m_struct::exty, iccp3m_struct::extz, iccp3m_struct::first_id, ICCP3M_AREA, iccp3m_cfg, ICCP3M_EPSILON, iccp3m_init(), iccp3m_initialized, ICCP3M_SIGMA, malloc, mpi_iccp3m_init(), mpi_iccp3m_iteration(), iccp3m_struct::n_ic, iccp3m_struct::num_iteration, iccp3m_struct::nvectorx, iccp3m_struct::relax, iccp3m_struct::set_flag, iccp3m_struct::sigma, tclcommand_iccp3m_parse_double_list(), and tclcommand_iccp3m_parse_normals().
Referenced by tcl_register_commands().
int tclcommand_iccp3m_parse_double_list (Tcl_Interp * interp, int n_ic, char * string, int flag)
Definition at line 227 of file iccp3m_tcl.cpp.
References iccp3m_struct::areas, iccp3m_struct::ein, free, i, ICCP3M_AREA, iccp3m_cfg, ICCP3M_EPSILON, ICCP3M_SIGMA, malloc, realloc, and iccp3m_struct::sigma.
Referenced by tclcommand_iccp3m().
int tclcommand_iccp3m_parse_normals (Tcl_Interp * interp, int n_ic, char * string)
Definition at line 190 of file iccp3m_tcl.cpp.
References i, iccp3m_cfg, iccp3m_struct::n_ic, iccp3m_struct::nvectorx, iccp3m_struct::nvectory, iccp3m_struct::nvectorz, and realloc.
Referenced by tclcommand_iccp3m().