ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: iccp3m.hpp File Reference
iccp3m.hpp File Reference
ICCP3M is a method that allows to take into account the influence of arbitrarliy shaped dielectric interfaces.
#include <ctime>
#include "p3m.hpp"
#include "utils.hpp"
#include "mmm1d.hpp"
#include "mmm2d.hpp"
#include "domain_decomposition.hpp"
#include "cells.hpp"
#include "integrate.hpp"
#include "verlet.hpp"
#include "layered.hpp"
#include "global.hpp"
#include "ghosts.hpp"
#include "nsquare.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "topology.hpp"
#include "forces.hpp"
Data Structures
struct iccp3m_struct
Functions
int bcast_iccp3m_cfg (void)
void force_calc_iccp3m ()
Calculation of the electrostatic forces between source charges (= real charges) and wall charges.
void layered_calculate_ia_iccp3m ()
Calculation of short range part of electrostatic interaction in layered systems A modified version of layered_calculate_ia in layered.hpp.
void build_verlet_lists_and_calc_verlet_ia_iccp3m ()
Calculate the short range part of electrostatic interaction using verlet lists.
void calculate_verlet_ia_iccp3m ()
Calculate he short range part of electrostatic interaction using verlet lists, if verlet lists have already been properly built.
void calc_link_cell_iccp3m ()
Calculate he short range part of electrostatic interaction using for linked cell systems.
void nsq_calculate_ia_iccp3m ()
Calculate he short range part of electrostatic interaction using for n-squared cell systems.
int iccp3m_iteration ()
The main iterative scheme, where the surface element charges are calculated self-consistently.
void iccp3m_init (void)
The initialisation of ICCP3M with zero values for all variables.
int iccp3m_sanity_check ()
check sanity of parameters for use with ICCP3M
void add_non_bonded_pair_force_iccp3m (Particle *p1, Particle *p2, double d[3], double dist, double dist2)
Variant of add_non_bonded_pair_force where only coulomb contributions are calculated.
Variables
iccp3m_struct iccp3m_cfg
int iccp3m_initialized
Detailed Description
ICCP3M is a method that allows to take into account the influence of arbitrarliy shaped dielectric interfaces.
The dielectric properties of a dielectric medium in the bulk of the simulation box are taken into account by reproducing the jump in the electric field at the inface with charge surface segments. The charge density of the surface segments have to be determined self-consistently using an iterative scheme. It can at presently
despite its name - be used with P3M, ELCP3M, MMM2D and MMM1D. For details see:
S. Tyagi, M. Suzen, M. Sega, C. Holm, M. Barbosa: A linear-scaling method for computing induced charges on arbitrary dielectric boundaries in large system simulations (Preprint)
To set up ICCP3M first the dielectric boundary has to be modelled by espresso particles 0..n where n has to be passed as a parameter to ICCP3M. This is still a bit inconvenient, as it forces the user to reserve the first n particle ids to wall charges, but as the other parts of espresso do not suffer from a limitation like this, it can be tolerated.
For the determination of the induced charges only the forces acting on the induced charges has to be determined. As P3M an the other coulomb solvers calculate all mutual forces, the force calculation was modified to avoid the calculation of the short range part of the source-source force calculation. For different particle data organisation schemes this is performed differently.
Definition in file iccp3m.hpp.
Function Documentation
void add_non_bonded_pair_force_iccp3m (Particle * p1, Particle * p2, double d[3], double dist, double dist2) inline
Variant of add_non_bonded_pair_force where only coulomb contributions are calculated.
Definition at line 147 of file iccp3m.hpp.
References add_mmm1d_coulomb_pair_force(), add_mmm2d_coulomb_pair_force(), coulomb, COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_MMM2D, COULOMB_P3M, COULOMB_P3M_GPU, ParticleForce::f, Particle::f, FORCE_TRACE, ParticleProperties::identity, Coulomb_parameters::method, Particle::p, ParticleProperties::q, and this_node.
Referenced by build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_link_cell_iccp3m(), calculate_verlet_ia_iccp3m(), layered_calculate_ia_iccp3m(), and nsq_calculate_ia_iccp3m().
int bcast_iccp3m_cfg (void)
Definition at line 100 of file iccp3m.cpp.
References iccp3m_struct::areas, iccp3m_struct::citeration, comm_cart, iccp3m_struct::convergence, iccp3m_struct::ein, iccp3m_struct::eout, iccp3m_struct::extx, iccp3m_struct::exty, iccp3m_struct::extz, iccp3m_struct::first_id, i, MPI_Bcast(), MPI_DOUBLE, MPI_INT, iccp3m_struct::n_ic, iccp3m_struct::num_iteration, iccp3m_struct::nvectorx, iccp3m_struct::nvectory, iccp3m_struct::nvectorz, realloc, iccp3m_struct::relax, iccp3m_struct::set_flag, iccp3m_struct::sigma, and this_node.
Referenced by mpi_iccp3m_init(), and mpi_iccp3m_init_slave().
void build_verlet_lists_and_calc_verlet_ia_iccp3m ()
Calculate the short range part of electrostatic interaction using verlet lists.
A modified version of build_verlet_lists_and_calc_verlet_ia() in verlet.hpp
Definition at line 336 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), add_pair_iccp3m(), box_l, CellPList::cell, DomainDecomposition::cell_inter, check_id, dd, distance2vec(), do_nonbonded(), errexit(), get_ia_param(), i, ParticleProperties::identity, local_cells, IA_parameters::max_cut, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, n_nodes, n_part, neighbor, IA_Neighbor_List::nList, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticleList::part, PI, IA_Neighbor::pList, Particle::r, rebuild_verletlist, resize_verlet_list_iccp3m(), skin, SQR(), this_node, ParticleProperties::type, DomainDecomposition::use_vList, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by force_calc_iccp3m().
void calc_link_cell_iccp3m ()
Calculate he short range part of electrostatic interaction using for linked cell systems.
A modified version of calc_link_cell() in domain_decomposition.hpp
Definition at line 436 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), CellPList::cell, DomainDecomposition::cell_inter, dd, distance2vec(), get_ia_param(), i, local_cells, IA_parameters::max_cut, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, neighbor, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, ParticleList::part, IA_Neighbor::pList, Particle::r, rebuild_verletlist, skin, SQR(), and ParticleProperties::type.
Referenced by force_calc_iccp3m().
void calculate_verlet_ia_iccp3m ()
Calculate he short range part of electrostatic interaction using verlet lists, if verlet lists have already been properly built.
A modified version of calculate_verlet_ia() in verlet.hpp
Definition at line 409 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), CellPList::cell, DomainDecomposition::cell_inter, dd, distance2vec(), i, local_cells, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, PairList::pair, ParticleList::part, Particle::r, and IA_Neighbor::vList.
Referenced by force_calc_iccp3m().
void force_calc_iccp3m ()
Calculation of the electrostatic forces between source charges (= real charges) and wall charges.
For each electrostatic method the proper functions for short and long range parts are called. Long Range Parts are calculated directly, short range parts need helper functions according to the particle data organisation. A modified version of force_calc in forces.hpp.
Definition at line 245 of file iccp3m.cpp.
References build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_link_cell_iccp3m(), calc_long_range_forces_iccp3m(), calculate_verlet_ia_iccp3m(), cell_structure, CELL_STRUCTURE_DOMDEC, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, dd, init_forces_iccp3m(), layered_calculate_ia_iccp3m(), nsq_calculate_ia_iccp3m(), rebuild_verletlist, CellStructure::type, and DomainDecomposition::use_vList.
Referenced by iccp3m_iteration().
void iccp3m_init (void)
The initialisation of ICCP3M with zero values for all variables.
Definition at line 78 of file iccp3m.cpp.
References iccp3m_struct::areas, iccp3m_struct::citeration, iccp3m_struct::convergence, iccp3m_struct::ein, iccp3m_struct::eout, iccp3m_struct::extx, iccp3m_struct::exty, iccp3m_struct::extz, iccp3m_struct::first_id, iccp3m_struct::num_iteration, iccp3m_struct::nvectorx, iccp3m_struct::nvectory, iccp3m_struct::nvectorz, iccp3m_struct::relax, and iccp3m_struct::set_flag.
Referenced by mpi_iccp3m_init_slave(), and tclcommand_iccp3m().
int iccp3m_iteration ()
The main iterative scheme, where the surface element charges are calculated self-consistently.
Definition at line 145 of file iccp3m.cpp.
References iccp3m_struct::areas, Coulomb_parameters::bjerrum, CellPList::cell, iccp3m_struct::citeration, comm_cart, iccp3m_struct::convergence, coulomb, iccp3m_struct::ein, iccp3m_struct::eout, iccp3m_struct::extx, iccp3m_struct::exty, iccp3m_struct::extz, ParticleForce::f, Particle::f, iccp3m_struct::first_id, force_calc_iccp3m(), i, iccp3m_sanity_check(), ParticleProperties::identity, local_cells, MPI_Allreduce(), MPI_DOUBLE, MPI_MAX, CellPList::n, ParticleList::n, iccp3m_struct::n_ic, iccp3m_struct::num_iteration, iccp3m_struct::nvectorx, iccp3m_struct::nvectory, iccp3m_struct::nvectorz, on_particle_change(), Particle::p, ParticleList::part, ParticleProperties::q, iccp3m_struct::relax, runtimeError, and iccp3m_struct::sigma.
Referenced by force_calc(), mpi_iccp3m_iteration(), and mpi_iccp3m_iteration_slave().
int iccp3m_sanity_check ()
check sanity of parameters for use with ICCP3M
Definition at line 732 of file iccp3m.cpp.
References coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_RF, INTEG_METHOD_NPT_ISO, integ_switch, Coulomb_parameters::method, and runtimeError.
Referenced by iccp3m_iteration().
void layered_calculate_ia_iccp3m ()
Calculation of short range part of electrostatic interaction in layered systems A modified version of layered_calculate_ia in layered.hpp.
Calculation of short range part of electrostatic interaction in layered systems A modified version of layered_calculate_ia in layered.hpp.
Definition at line 279 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), CELL_TRACE, cells, do_nonbonded(), i, Particle::l, layered_get_mi_vector(), ParticleList::n, n_layers, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, sqrlen(), and this_node.
Referenced by force_calc_iccp3m().
void nsq_calculate_ia_iccp3m ()
Calculate he short range part of electrostatic interaction using for n-squared cell systems.
A modified version of nsq_calculate_ia nsquare.hpp.
Definition at line 481 of file iccp3m.cpp.
References add_non_bonded_pair_force_iccp3m(), CellPList::cell, get_mi_vector(), Particle::l, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, and sqrlen().
Referenced by force_calc_iccp3m().
Variable Documentation
iccp3m_struct iccp3m_cfg
Definition at line 54 of file iccp3m.cpp.
Referenced by force_calc(), tclcommand_iccp3m(), tclcommand_iccp3m_parse_double_list(), and tclcommand_iccp3m_parse_normals().
int iccp3m_initialized
Definition at line 56 of file iccp3m.cpp.
Referenced by force_calc(), mpi_iccp3m_init_slave(), and tclcommand_iccp3m().