ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: iccp3m_tcl.hpp File Reference
iccp3m_tcl.hpp File Reference
#include "parser.hpp"
Functions
int tclcommand_iccp3m (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl-command
iccp3m { <last_ind_id> <e1> <num_iteration> <convergence> <relaxation> <area> <normal_components> <e_in/e_out> [<ext_field>] | iterate } ICC sets up and calculates induced charges on dielectric surfaces.
Function Documentation
int tclcommand_iccp3m (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl-command
iccp3m { <last_ind_id> <e1> <num_iteration> <convergence> <relaxation> <area> <normal_components> <e_in/e_out> [<ext_field>] | iterate } ICC sets up and calculates induced charges on dielectric surfaces.
At the beginning of every simulation run particles on the surface boundary have to be set up (before any real particle) together with the list of areas, normal vectors and dielectric constant associated with them. After that the iterate flag can be used during the simulation to update the value of the induced charges.
Parameters:
<last_ind_id> ID of the last surface charge. Note that the IDs of the surface charges must range from 0 to <last_ind_id> <e1> = Dielectric Constant of the Bulk accessible to free particles <num_iteration> = Maximum number of ICCP3M iterations calculating the induced charges. <relaxation> = Relaxaxion parameter for the successive over-relaxation scheme. <area> = List of the areas of each surface element. <normal_components> = List of normal vectors of each surface element. 3n list entries. Do not have to be normalized. <e_in/e_out> = Ratio of dielectric co
         iterate         = Indicates that a previous surface discretization shall be used. T
Implementation of the tcl-command
iccp3m { <last_ind_id> <e1> <num_iteration> <convergence> <relaxation> <area> <normal_components> <e_in/e_out> [<ext_field>] | iterate } ICC sets up and calculates induced charges on dielectric surfaces.
Definition at line 40 of file iccp3m_tcl.cpp.
References iccp3m_struct::areas, ARG0_IS_S, ARG1_IS_D, ARG1_IS_I, ARG_IS_D, ARG_IS_I, ARG_IS_S, iccp3m_struct::citeration, iccp3m_struct::convergence, iccp3m_struct::ein, iccp3m_struct::eout, iccp3m_struct::extx, iccp3m_struct::exty, iccp3m_struct::extz, iccp3m_struct::first_id, ICCP3M_AREA, iccp3m_cfg, ICCP3M_EPSILON, iccp3m_init(), iccp3m_initialized, ICCP3M_SIGMA, malloc, mpi_iccp3m_init(), mpi_iccp3m_iteration(), iccp3m_struct::n_ic, iccp3m_struct::num_iteration, iccp3m_struct::nvectorx, iccp3m_struct::relax, iccp3m_struct::set_flag, iccp3m_struct::sigma, tclcommand_iccp3m_parse_double_list(), and tclcommand_iccp3m_parse_normals().
Referenced by tcl_register_commands().