ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: imd.hpp File Reference
imd.hpp File Reference
The interface with VMD.
#include <stdint.h>
Enumerations
enum IMDType {
IMD_DISCONNECT, IMD_ENERGIES, IMD_FCOORDS, IMD_GO,
IMD_HANDSHAKE, IMD_KILL, IMD_MDCOMM, IMD_PAUSE,
IMD_TRATE, IMD_IOERROR
}
Functions
IMDType imd_recv_header (void *, int32_t *)
int imd_send_fcoords (void *, int32_t, const float *)
int imd_handshake (void *)
Variables
int transfer_rate
a value that you can set from VMD and read in your script as global variable
Detailed Description
The interface with VMD.
This code just provides a wrapper for the IMD interface functions, which allow to send particle positions to VMD. Additionally, VMD can send back a single integer value, called transfer_rate, which is accessible both from c and from Tcl. The IMD force feedback is not implemented.
Definition in file imd.hpp.
Enumeration Type Documentation
enum IMDType
Enumerator
IMD_DISCONNECT
IMD_ENERGIES
IMD_FCOORDS
IMD_GO
IMD_HANDSHAKE
IMD_KILL
IMD_MDCOMM
IMD_PAUSE
IMD_TRATE
IMD_IOERROR
Definition at line 31 of file imd.hpp.
Function Documentation
int imd_handshake (void *)
Definition at line 190 of file imd.cpp.
References fill_header(), HEADERSIZE, IMD_HANDSHAKE, imd_writen(), and IMDVERSION.
Referenced by tclcommand_imd_print_check_connect().
IMDType imd_recv_header (void * , int32_t *)
Definition at line 278 of file imd.cpp.
References HEADERSIZE, IMD_IOERROR, imd_readn(), and swap_header().
Referenced by tclcommand_imd_print_check_connect(), and tclcommand_imd_print_drain_socket().
int imd_send_fcoords (void * , int32_t , const float *)
Definition at line 230 of file imd.cpp.
References fill_header(), free, HEADERSIZE, IMD_FCOORDS, imd_writen(), and malloc.
Referenced by tclcommand_imd_parse_pos().
Variable Documentation
int transfer_rate
a value that you can set from VMD and read in your script as global variable
Definition at line 78 of file imd.cpp.
Referenced by tclcommand_imd_print_drain_socket().