ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: imd_tcl.cpp File Reference
imd_tcl.cpp File Reference
#include <unistd.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <cerrno>
#include <tcl.h>
#include "vmdsock.hpp"
#include "imd.hpp"
#include "particle_data.hpp"
#include "parser.hpp"
#include "grid.hpp"
#include "statistics_molecule.hpp"
#include <inttypes.h>
Functions
int tclcommand_imd_print_drain_socket (Tcl_Interp *interp)
int tclcommand_imd_print_check_connect (Tcl_Interp *interp)
int tclcommand_imd_parse_pos (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_imd (ClientData data, Tcl_Interp *interp, int argc, char **argv)
VMD connection.
Variables
static void * initsock = 0
static void * sock = 0
Function Documentation
int tclcommand_imd (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
VMD connection.
See imd_tcl.cpp
Definition at line 288 of file imd_tcl.cpp.
References ARG1_IS_S, ARG_IS_I, initsock, sock, tclcommand_imd_parse_pos(), tclcommand_imd_print_check_connect(), tclcommand_imd_print_drain_socket(), vmdsock_bind(), vmdsock_create(), vmdsock_destroy(), vmdsock_init(), and vmdsock_listen().
Referenced by tcl_register_commands().
int tclcommand_imd_parse_pos (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 171 of file imd_tcl.cpp.
References analyze_fold_molecules(), ARG_IS_S, fold_position(), free, i, ParticleProperties::identity, imd_send_fcoords(), initsock, malloc, max_seen_particle, n_part, ParticlePosition::p, Particle::p, partCfg, Particle::r, sock, tclcommand_imd_print_check_connect(), tclcommand_imd_print_drain_socket(), updatePartCfg(), vmdsock_selwrite(), and WITH_BONDS.
Referenced by tclcommand_imd().
int tclcommand_imd_print_check_connect (Tcl_Interp * interp)
Definition at line 140 of file imd_tcl.cpp.
References IMD_GO, imd_handshake(), imd_recv_header(), initsock, sock, vmdsock_accept(), vmdsock_destroy(), and vmdsock_selread().
Referenced by tclcommand_imd(), and tclcommand_imd_parse_pos().
int tclcommand_imd_print_drain_socket (Tcl_Interp * interp)
Definition at line 44 of file imd_tcl.cpp.
References IMD_DISCONNECT, IMD_ENERGIES, IMD_FCOORDS, IMD_IOERROR, IMD_KILL, IMD_MDCOMM, imd_recv_header(), IMD_TRATE, sock, transfer_rate, vmdsock_destroy(), and vmdsock_selread().
Referenced by tclcommand_imd(), and tclcommand_imd_parse_pos().
Variable Documentation
void* initsock = 0 static
Definition at line 38 of file imd_tcl.cpp.
Referenced by tclcommand_imd(), tclcommand_imd_parse_pos(), and tclcommand_imd_print_check_connect().
void* sock = 0 static
Definition at line 39 of file imd_tcl.cpp.
Referenced by tclcommand_imd(), tclcommand_imd_parse_pos(), tclcommand_imd_print_check_connect(), and tclcommand_imd_print_drain_socket().