ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: imd.cpp File Reference
imd.cpp File Reference
Implementation of imd.h.
#include <climits>
#include <unistd.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <cerrno>
#include <inttypes.h>
#include "utils.hpp"
#include "imd.hpp"
#include "communication.hpp"
#include "particle_data.hpp"
#include "statistics_chain.hpp"
#include "statistics_molecule.hpp"
#include "vmdsock.hpp"
Macros
#define HEADERSIZE 8
#define IMDVERSION 2
Functions
int imd_disconnect (void *)
int imd_pause (void *)
int imd_kill (void *)
int imd_trate (void *, int32_t)
int imd_send_mdcomm (void *, int32_t, const int32_t *, const float *)
int imd_send_energies (void *, const IMDEnergies *)
int imd_recv_handshake (void *)
int imd_recv_mdcomm (void *, int32_t, int32_t *, float *)
int imd_recv_energies (void *, IMDEnergies *)
int imd_recv_fcoords (void *, int32_t, float *)
static void swap4 (char *data, int ndata)
static int32_t imd_htonl (int32_t h)
static int32_t imd_ntohl (int32_t n)
static void fill_header (IMDheader *header, IMDType type, int32_t length)
static void swap_header (IMDheader *header)
static int32_t imd_readn (void *s, char *ptr, int32_t n)
static int32_t imd_writen (void *s, const char *ptr, int32_t n)
static int imd_go (void *s)
int imd_handshake (void *s)
int imd_send_fcoords (void *s, int32_t n, const float *coords)
IMDType imd_recv_header_nolengthswap (void *s, int32_t *length)
IMDType imd_recv_header (void *s, int32_t *length)
Variables
int transfer_rate = 0
a value that you can set from VMD and read in your script as global variable
Detailed Description
Implementation of imd.h.
Definition in file imd.cpp.
Macro Definition Documentation
#define HEADERSIZE 8
Definition at line 75 of file imd.cpp.
Referenced by imd_disconnect(), imd_go(), imd_handshake(), imd_kill(), imd_pause(), imd_recv_header(), imd_recv_header_nolengthswap(), imd_send_energies(), imd_send_fcoords(), imd_send_mdcomm(), and imd_trate().
#define IMDVERSION 2
Definition at line 76 of file imd.cpp.
Referenced by imd_handshake(), and imd_recv_handshake().
Function Documentation
static void fill_header (IMDheader * header, IMDType type, int32_t length) static
Definition at line 117 of file imd.cpp.
References imd_htonl().
Referenced by imd_disconnect(), imd_go(), imd_handshake(), imd_kill(), imd_pause(), imd_send_energies(), imd_send_fcoords(), imd_send_mdcomm(), and imd_trate().
int imd_disconnect (void * s)
Definition at line 165 of file imd.cpp.
References fill_header(), HEADERSIZE, IMD_DISCONNECT, and imd_writen().
static int imd_go (void * s) static
Definition at line 183 of file imd.cpp.
References fill_header(), HEADERSIZE, IMD_GO, and imd_writen().
Referenced by imd_recv_handshake().
int imd_handshake (void * s)
Definition at line 190 of file imd.cpp.
References fill_header(), HEADERSIZE, IMD_HANDSHAKE, imd_writen(), and IMDVERSION.
Referenced by tclcommand_imd_print_check_connect().
static int32_t imd_htonl (int32_t h) static
Definition at line 97 of file imd.cpp.
Referenced by fill_header().
int imd_kill (void * s)
Definition at line 177 of file imd.cpp.
References fill_header(), HEADERSIZE, IMD_KILL, and imd_writen().
static int32_t imd_ntohl (int32_t n) static
Definition at line 106 of file imd.cpp.
Referenced by swap_header().
int imd_pause (void * s)
Definition at line 171 of file imd.cpp.
References fill_header(), HEADERSIZE, IMD_PAUSE, and imd_writen().
static int32_t imd_readn (void * s, char * ptr, int32_t n) static
Definition at line 127 of file imd.cpp.
References vmdsock_read().
Referenced by imd_recv_energies(), imd_recv_fcoords(), imd_recv_header(), imd_recv_header_nolengthswap(), and imd_recv_mdcomm().
int imd_recv_energies (void * s, IMDEnergies * energies)
Definition at line 293 of file imd.cpp.
References imd_readn().
int imd_recv_fcoords (void * s, int32_t n, float * coords)
Definition at line 298 of file imd.cpp.
References imd_readn().
int imd_recv_handshake (void * s)
Definition at line 253 of file imd.cpp.
References imd_go(), IMD_HANDSHAKE, imd_recv_header_nolengthswap(), IMDVERSION, swap4(), and vmdsock_selread().
IMDType imd_recv_header (void * s, int32_t * length)
Definition at line 278 of file imd.cpp.
References HEADERSIZE, IMD_IOERROR, imd_readn(), and swap_header().
Referenced by tclcommand_imd_print_check_connect(), and tclcommand_imd_print_drain_socket().
IMDType imd_recv_header_nolengthswap (void * s, int32_t * length)
Definition at line 244 of file imd.cpp.
References HEADERSIZE, IMD_IOERROR, imd_readn(), and swap_header().
Referenced by imd_recv_handshake().
int imd_recv_mdcomm (void * s, int32_t n, int32_t * indices, float * forces)
Definition at line 287 of file imd.cpp.
References imd_readn().
int imd_send_energies (void * s, const IMDEnergies * energies)
Definition at line 218 of file imd.cpp.
References fill_header(), free, HEADERSIZE, IMD_ENERGIES, imd_writen(), and malloc.
int imd_send_fcoords (void * s, int32_t n, const float * coords)
Definition at line 230 of file imd.cpp.
References fill_header(), free, HEADERSIZE, IMD_FCOORDS, imd_writen(), and malloc.
Referenced by tclcommand_imd_parse_pos().
int imd_send_mdcomm (void * s, int32_t n, const int32_t * indices, const float * forces)
Definition at line 205 of file imd.cpp.
References fill_header(), free, HEADERSIZE, IMD_MDCOMM, imd_writen(), and malloc.
int imd_trate (void * s, int32_t rate)
Definition at line 197 of file imd.cpp.
References fill_header(), HEADERSIZE, IMD_TRATE, and imd_writen().
static int32_t imd_writen (void * s, const char * ptr, int32_t n) static
Definition at line 146 of file imd.cpp.
References vmdsock_write().
Referenced by imd_disconnect(), imd_go(), imd_handshake(), imd_kill(), imd_pause(), imd_send_energies(), imd_send_fcoords(), imd_send_mdcomm(), and imd_trate().
static void swap4 (char * data, int ndata) static
Definition at line 80 of file imd.cpp.
References i.
Referenced by imd_recv_handshake().
static void swap_header (IMDheader * header) static
Definition at line 122 of file imd.cpp.
References imd_ntohl().
Referenced by imd_recv_header(), and imd_recv_header_nolengthswap().
Variable Documentation
int transfer_rate = 0
a value that you can set from VMD and read in your script as global variable
Definition at line 78 of file imd.cpp.
Referenced by tclcommand_imd_print_drain_socket().