ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: initialize_interpreter.cpp File Reference
initialize_interpreter.cpp File Reference
#include <tcl.h>
#include <unistd.h>
#include <cstdlib>
#include <cstring>
#include <cstdio>
#include "initialize_interpreter.hpp"
#include "global.hpp"
#include "binary_file_tcl.hpp"
#include "cells_tcl.hpp"
#include "constraint_tcl.hpp"
#include "domain_decomposition_tcl.hpp"
#include "dpd_tcl.hpp"
#include "galilei_tcl.hpp"
#include "global_tcl.hpp"
#include "grid_tcl.hpp"
#include "iccp3m_tcl.hpp"
#include "integrate_tcl.hpp"
#include "integrate_sd_tcl.hpp"
#include "interaction_data_tcl.hpp"
#include "lb_tcl.hpp"
#include "lees_edwards_tcl.hpp"
#include "lj_tcl.hpp"
#include "maggs_tcl.hpp"
#include "metadynamics_tcl.hpp"
#include "p3m-dipolar_tcl.hpp"
#include "p3m_tcl.hpp"
#include "polymer_tcl.hpp"
#include "pressure_tcl.hpp"
#include "random_tcl.hpp"
#include "reaction_tcl.hpp"
#include "statistics_chain_tcl.hpp"
#include "statistics_cluster_tcl.hpp"
#include "statistics_correlation_tcl.hpp"
#include "statistics_fluid_tcl.hpp"
#include "statistics_observable_tcl.hpp"
#include "statistics_tcl.hpp"
#include "thermostat_tcl.hpp"
#include "virtual_sites_com_tcl.hpp"
#include "ghmc_tcl.hpp"
#include "external_potential_tcl.hpp"
#include "tuning.hpp"
#include "electrokinetics_tcl.hpp"
#include "actor/HarmonicWell_tcl.hpp"
#include "actor/HarmonicOrientationWell_tcl.hpp"
#include "minimize_energy_tcl.hpp"
#include "h5mdfile_tcl.hpp"
Macros
#define REGISTER_COMMAND(name, routine) Tcl_CreateCommand(interp, name, (Tcl_CmdProc *)routine, 0, NULL);
Functions
int tclcommand_bin (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl command bin, which can be used to bin data into arbitrary bins.
int tclcommand_blockfile (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the Tcl command blockfile.
int tclcommand_h5mdfile (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the Tcl command h5mdfile.
int tclcommand_replacestdchannel (ClientData clientData, Tcl_Interp *interp, int argc, char **argv)
replaces one of TCLs standart channels with a named pipe.
int tclcommand_code_info (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implements the Tcl command code_info.
int tclcommand_cuda (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Set the CUDA device to use or retrieve information available devices.
int tclcommand_imd (ClientData data, Tcl_Interp *interp, int argc, char **argv)
VMD connection.
int tclcommand_nemd (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure for nemd steering.
int tclcommand_on_collision (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Collision detection.
int tclcommand_part (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl command "part".
int tclcommand_uwerr (ClientData data, Tcl_Interp *interp, int argc, char *argv[])
The C implementation of the tcl function uwerr.
int tclcallback_timings (Tcl_Interp *interp, void *data)
callback for timing_samples.
char * get_default_scriptsdir ()
from scriptsdir.cpp
int tclcommand_time_integration (ClientData data, Tcl_Interp *interp, int argc, char *argv[])
Returns runtime of the integration loop in seconds.
int tclcommand_readpdb (ClientData data, Tcl_Interp *interp, int argc, char *argv[])
Reads particles from pdb file, see readpdb.cpp.
static void tcl_register_commands (Tcl_Interp *interp)
static void tcl_register_global_variables (Tcl_Interp *interp)
int tcl_appinit (Tcl_Interp *interp)
Macro Definition Documentation
#define REGISTER_COMMAND (name, routine) Tcl_CreateCommand(interp, name, (Tcl_CmdProc *)routine, 0, NULL);
Definition at line 131 of file initialize_interpreter.cpp.
Referenced by tcl_register_commands().
Function Documentation
char* get_default_scriptsdir ()
from scriptsdir.cpp
Definition at line 21 of file scriptsdir.cpp.
Referenced by tcl_appinit().
int tcl_appinit (Tcl_Interp * interp)
Definition at line 279 of file initialize_interpreter.cpp.
References get_default_scriptsdir(), tcl_register_commands(), and tcl_register_global_variables().
Referenced by main().
static void tcl_register_commands (Tcl_Interp * interp) static
Definition at line 134 of file initialize_interpreter.cpp.
References REGISTER_COMMAND, tclcommand_analyze(), tclcommand_bin(), tclcommand_bit_random(), tclcommand_blockfile(), tclcommand_cellsystem(), tclcommand_change_volume(), tclcommand_code_info(), tclcommand_constraint(), tclcommand_correlation(), tclcommand_counterions(), tclcommand_crosslink(), tclcommand_cuda(), tclcommand_diamond(), tclcommand_electrokinetics(), tclcommand_external_potential(), tclcommand_galilei_transform(), tclcommand_ghmc(), tclcommand_h5mdfile(), tclcommand_HarmonicOrientationWell(), tclcommand_iccp3m(), tclcommand_icosaeder(), tclcommand_imd(), tclcommand_integrate(), tclcommand_integrate_sd(), tclcommand_inter(), tclcommand_invalidate_system(), tclcommand_kill_particle_forces(), tclcommand_kill_particle_motion(), tclcommand_lbboundary(), tclcommand_lbfluid(), tclcommand_lbnode(), tclcommand_lbnode_extforce_gpu(), tclcommand_lees_edwards_offset(), tclcommand_load_state(), tclcommand_maxwell_velocities(), tclcommand_metadynamics(), tclcommand_minimize_energy(), tclcommand_nemd(), tclcommand_observable(), tclcommand_on_collision(), tclcommand_part(), tclcommand_polymer(), tclcommand_print_efield_capacitors(), tclcommand_reaction(), tclcommand_readmd(), tclcommand_readpdb(), tclcommand_replacestdchannel(), tclcommand_salt(), tclcommand_save_state(), tclcommand_sd_set_particles_apart(), tclcommand_sd_test(), tclcommand_setmd(), tclcommand_sort_particles(), tclcommand_system_CMS(), tclcommand_system_CMS_velocity(), tclcommand_t_random(), tclcommand_thermostat(), tclcommand_time_integration(), tclcommand_uwerr(), tclcommand_velocities(), and tclcommand_writemd().
Referenced by tcl_appinit().
static void tcl_register_global_variables (Tcl_Interp * interp) static
Definition at line 253 of file initialize_interpreter.cpp.
References FIELD_BOXL, FIELD_MAXNUMCELLS, FIELD_MIN_GLOBAL_CUT, FIELD_MINNUMCELLS, FIELD_NODEGRID, FIELD_NPTISO_PDIFF, FIELD_NPTISO_PISTON, FIELD_PERIODIC, FIELD_SD_RADIUS, FIELD_SD_RANDOM_PRECISION, FIELD_SD_RANDOM_STATE, FIELD_SD_SEED, FIELD_SD_VISCOSITY, FIELD_SIMTIME, FIELD_SKIN, FIELD_SMALLERTIMESTEP, FIELD_TIMESTEP, FIELD_TIMINGSAMP, FIELD_WARNINGS, register_global_callback(), tclcallback_box_l(), tclcallback_max_num_cells(), tclcallback_min_global_cut(), tclcallback_min_num_cells(), tclcallback_node_grid(), tclcallback_npt_p_diff(), tclcallback_npt_piston(), tclcallback_periodicity(), tclcallback_sd_radius(), tclcallback_sd_random_precision(), tclcallback_sd_random_state(), tclcallback_sd_seed(), tclcallback_sd_viscosity(), tclcallback_skin(), tclcallback_smaller_time_step(), tclcallback_time(), tclcallback_time_step(), tclcallback_timings(), and tclcallback_warnings().
Referenced by tcl_appinit().
int tclcallback_timings (Tcl_Interp * interp, void * data)
callback for timing_samples.
See tuning_tcl.cpp
Definition at line 29 of file tuning_tcl.cpp.
References timing_samples.
Referenced by tcl_register_global_variables().
int tclcommand_bin (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl command bin, which can be used to bin data into arbitrary bins.
See bin_tcl.cpp
Definition at line 41 of file bin_tcl.cpp.
References alloc_doublelist(), ARG1_IS_DOUBLELIST, ARG1_IS_S, ARG_IS_D, ARG_IS_DOUBLELIST, ARG_IS_I, DoubleList::e, i, init_doublelist(), DoubleList::n, realloc_doublelist(), setup_linear_bins(), and setup_log_bins().
Referenced by tcl_register_commands().
int tclcommand_blockfile (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the Tcl command blockfile.
Allows to read and write blockfile comfortably from Tcl. See blockfile_tcl.cpp
Referenced by tcl_register_commands().
int tclcommand_code_info (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implements the Tcl command code_info.
It provides information on the Version, Compilation status and the debug status of the used code. See config_tcl.cpp
Definition at line 47 of file config_tcl.cpp.
References tclcommand_code_info_compilation(), and tclcommand_code_info_version().
Referenced by tcl_register_commands().
int tclcommand_cuda (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Set the CUDA device to use or retrieve information available devices.
See cuda_init_tcl.cpp
Set the CUDA device to use or retrieve information available devices.
Only devices with compute capability of 1.1 or higher are ok, since atomic operations are required for CUDA-LB.
Definition at line 62 of file cuda_init_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, cuda_check_gpu(), cuda_error, cuda_get_device(), cuda_set_device(), cuda_test_device_access(), ES_ERROR, and ES_OK.
Referenced by tcl_register_commands().
int tclcommand_h5mdfile (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the Tcl command h5mdfile.
Allows to read and write h5mdfile comfortably from Tcl. See h5mdfile_tcl.cpp
Definition at line 120 of file h5mdfile_tcl.cpp.
Referenced by tcl_register_commands().
int tclcommand_imd (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
VMD connection.
See imd_tcl.cpp
Definition at line 288 of file imd_tcl.cpp.
References ARG1_IS_S, ARG_IS_I, initsock, sock, tclcommand_imd_parse_pos(), tclcommand_imd_print_check_connect(), tclcommand_imd_print_drain_socket(), vmdsock_bind(), vmdsock_create(), vmdsock_destroy(), vmdsock_init(), and vmdsock_listen().
Referenced by tcl_register_commands().
int tclcommand_nemd (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure for nemd steering.
USAGE: nemd <n_slabs> <n_exchange> see also tclcommand_nemd. See nemd_tcl.cpp
Definition at line 203 of file nemd_tcl.cpp.
References ARG1_IS_S, gather_runtime_errors(), INTEG_TRACE, nemd_free(), nemd_method, NEMD_METHOD_OFF, tclcommand_nemd_parse_and_print_profile(), tclcommand_nemd_parse_and_print_viscosity(), tclcommand_nemd_parse_exchange(), tclcommand_nemd_parse_shearrate(), tclcommand_nemd_print_status(), tclcommand_nemd_print_usage(), and this_node.
Referenced by tcl_register_commands().
int tclcommand_on_collision (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Collision detection.
See collision_tcl.cpp
Definition at line 31 of file collision_tcl.cpp.
References ARG0_IS_S, ARG_IS_D, ARG_IS_I, Collision_parameters::bond_centers, Collision_parameters::bond_vs, collision_detection_set_params(), COLLISION_MODE_BOND, COLLISION_MODE_EXCEPTION, COLLISION_MODE_VS, collision_params, Collision_parameters::distance, Collision_parameters::mode, and Collision_parameters::vs_particle_type.
Referenced by tcl_register_commands().
int tclcommand_part (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl command "part".
This command allows to modify particle data. See particle_data_tcl.cpp
Definition at line 2503 of file particle_data_tcl.cpp.
References ARG1_IS_I, ARG1_IS_S, ARG_IS_I, auto_exclusion(), part_parse_gc(), remove_all_exclusions(), remove_all_particles(), tclcommand_part_parse_cmd(), tclcommand_part_print_all(), and tclprint_to_result_Particle().
Referenced by tcl_register_commands().
int tclcommand_readpdb (ClientData data, Tcl_Interp * interp, int argc, char * argv[])
Reads particles from pdb file, see readpdb.cpp.
Definition at line 35 of file readpdb_tcl.cpp.
References ARG0_IS_D, ARG0_IS_I, ARG0_IS_S, PdbLJInteraction::epsilon, n_part, PdbLJInteraction::other_type, pdb_add_particles_from_file(), PdbLJInteraction::sigma, and usage().
Referenced by tcl_register_commands().
int tclcommand_replacestdchannel (ClientData clientData, Tcl_Interp * interp, int argc, char ** argv)
replaces one of TCLs standart channels with a named pipe.
See channels_tcl.cpp
Definition at line 27 of file channels_tcl.cpp.
Referenced by tcl_register_commands().
int tclcommand_time_integration (ClientData data, Tcl_Interp * interp, int argc, char * argv[])
Returns runtime of the integration loop in seconds.
From tuning_tcl.cpp
Definition at line 38 of file tuning_tcl.cpp.
References ARG1_IS_I, and time_force_calc().
Referenced by tcl_register_commands().
int tclcommand_uwerr (ClientData data, Tcl_Interp * interp, int argc, char * argv[])
The C implementation of the tcl function uwerr.
See uwerr_tcl.cpp
Definition at line 786 of file uwerr_tcl.cpp.
References free, i, malloc, UWerr(), UWerr_f(), uwerr_read_int_vector(), and uwerr_read_matrix().
Referenced by tcl_register_commands().