ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: initialize.hpp File Reference
initialize.hpp File Reference
This file contains the hook procedures.
Functions
Hook procedures
These procedures are called if several significant changes to the system happen which may make a reinitialization of subsystems necessary.
Note that all these functions are called on ALL nodes. if you need to do something only on the master node, check this_node == 0. The use of the asynchronous mpi_* functions (e. g. mpi_bcast_parameter) on the master node is possible.
void on_program_start ()
called once at the very beginning of the program start.
void on_integration_start ()
called every time the simulation is continued/started, i.
void on_observable_calc ()
called before calculating observables, i.e.
void on_particle_change ()
called every time a particle property is changed via Tcl.
void on_resort_particles ()
called every time the particles are resorted from node to node.
void on_coulomb_change ()
called every time the coulomb parameters are changed.
void on_short_range_ia_change ()
called every time short ranged interaction parameters are changed.
void on_constraint_change ()
called every time a constraint is changed.
void on_max_cut_change ()
called whenever the cutoff has potentially changed.
void on_boxl_change ()
called every time the box length has changed.
void on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
void on_temperature_change ()
called every time the temperature changes.
void on_parameter_change (int parameter)
called every time other parameters (timestep,...) are changed.
void on_n_particle_types_change ()
called every time the number of particle types has changed (increased)
void on_ghost_flags_change ()
call this if you want to change ghost flags, e.g.
void on_lb_params_change (int field)
void on_lbboundary_change ()
called every time the walls for the lb fluid are changed
Detailed Description
This file contains the hook procedures.
These are the ones with names on_* and are called whenever something is changed in Espresso which might influence other parts. For example, the P3M code has to be reinitialized whenever the box size changes. The hooking mechanism allows to keep track of such changes.
For this mechanism to work, two things have to be fulfilled. If some part of the code changes some property, it has to call the corresponding hook, i. e. on_particle_change if a particle property has been changed or on_short_range_ia_change, if a short ranged interaction has been changed. In turn procedures that depend on particle properties or the box size, should react to such changes in the corresponding hook procedure.
Definition in file initialize.hpp.
Function Documentation
void on_boxl_change ()
called every time the box length has changed.
This routine is relatively fast, and changing the box length every time step as for example necessary for NpT is more or less ok.
Definition at line 423 of file initialize.cpp.
References coulomb, COULOMB_ELC_P3M, COULOMB_MAGGS, COULOMB_MMM1D, COULOMB_MMM2D, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, Coulomb_parameters::Dmethod, EVENT_TRACE, LATTICE_LB, lattice_switch, lb_init(), lb_init_boundaries(), maggs_init(), Coulomb_parameters::method, MMM1D_init(), MMM2D_init(), and this_node.
Referenced by cells_on_geometry_change(), and dd_on_geometry_change().
void on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
This one is potentially slow.
Definition at line 476 of file initialize.cpp.
References coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_MAGGS, COULOMB_MMM1D, COULOMB_MMM2D, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, Coulomb_parameters::Dmethod, EVENT_TRACE, LATTICE_LB, lattice_switch, lb_init(), maggs_init(), Coulomb_parameters::method, MMM1D_init(), MMM2D_init(), on_ghost_flags_change(), and this_node.
Referenced by cells_re_init().
void on_constraint_change ()
called every time a constraint is changed.
Definition at line 371 of file initialize.cpp.
References EVENT_TRACE, invalidate_obs(), recalc_forces, and this_node.
Referenced by mpi_bcast_constraint(), and mpi_bcast_constraint_slave().
void on_coulomb_change ()
called every time the coulomb parameters are changed.
Definition at line 291 of file initialize.cpp.
References box_l, comm_cart, coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_MAGGS, COULOMB_MMM1D, COULOMB_MMM2D, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, Coulomb_parameters::Dmethod, errexit(), EVENT_TRACE, gpu_get_global_particle_vars_pointer_host(), invalidate_obs(), maggs_init(), Coulomb_parameters::method, MMM1D_init(), MMM2D_init(), MPI_Bcast(), MPI_BYTE, on_ghost_flags_change(), on_short_range_ia_change(), p3m_gpu_init(), recalc_coulomb_prefactor(), recalc_forces, and this_node.
Referenced by mpi_bcast_coulomb_params_slave().
void on_ghost_flags_change ()
call this if you want to change ghost flags, e.g.
wether ghosts have velocities or not. This is a opt-in process, i. e. all features are turned off and have to be reactivated if necessary inside this procedure.
Definition at line 674 of file initialize.cpp.
References CELL_STRUCTURE_CURRENT, cells_re_init(), coulomb, COULOMB_MAGGS, EVENT_TRACE, ghosts_have_v, LATTICE_LB, lattice_switch, Coulomb_parameters::method, n_rigidbonds, THERMO_DPD, thermo_switch, and this_node.
Referenced by on_cell_structure_change(), on_coulomb_change(), and on_parameter_change().
void on_integration_start ()
called every time the simulation is continued/started, i.
e. when switching from Tcl to the simulation core.
Definition at line 154 of file initialize.cpp.
References comm_cart, EVENT_TRACE, freePartCfg(), gpu_change_number_of_part_to_comm(), gpu_get_global_particle_vars_pointer_host(), INTEG_TRACE, integrate_ensemble_init(), integrator_npt_sanity_checks(), integrator_sanity_checks(), interactions_sanity_checks(), invalidate_obs(), LATTICE_LB, LATTICE_LB_GPU, lattice_switch, lb_GPU_sanity_checks(), lb_realloc_particles_gpu(), lb_reinit_particles_gpu, lb_sanity_checks(), meta_init(), MPI_Bcast(), MPI_BYTE, on_observable_calc(), reactions_sanity_checks(), recalc_forces, reinit_thermo, resort_particles, thermo_init(), and this_node.
Referenced by integrate_sd(), and integrate_vv().
void on_lb_params_change (int field)
Definition at line 640 of file initialize.cpp.
References EVENT_TRACE, lb_init(), lb_reinit_fluid(), lb_reinit_parameters(), LBPAR_AGRID, LBPAR_DENSITY, and this_node.
Referenced by mpi_bcast_lb_params_slave().
void on_lbboundary_change ()
called every time the walls for the lb fluid are changed
Definition at line 378 of file initialize.cpp.
References EVENT_TRACE, invalidate_obs(), LATTICE_LB, LATTICE_LB_GPU, lattice_switch, lb_init_boundaries(), recalc_forces, and this_node.
Referenced by mpi_bcast_lbboundary(), mpi_bcast_lbboundary_slave(), and tclcommand_electrokinetics().
void on_max_cut_change ()
called whenever the cutoff has potentially changed.
void on_n_particle_types_change ()
called every time the number of particle types has changed (increased)
void on_observable_calc ()
called before calculating observables, i.e.
energy, pressure or the integrator (forces). Initialize any methods here which are not initialized immediately (P3M, Maggs, etc.).
Definition at line 226 of file initialize.cpp.
References CELL_GLOBAL_EXCHANGE, cells_resort_particles(), coulomb, COULOMB_ELC_P3M, COULOMB_MAGGS, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, Coulomb_parameters::Dmethod, EVENT_TRACE, maggs_init(), Coulomb_parameters::method, reinit_electrostatics, reinit_magnetostatics, resort_particles, and this_node.
Referenced by aggregation(), energy_calc(), integrate_reaction(), on_integration_start(), and pressure_calc().
void on_parameter_change (int parameter)
called every time other parameters (timestep,...) are changed.
Note that this does not happen automatically. The callback procedure of the changed variable is responsible for that by calling mpi_bcast_event (2).
Parameters
parameter is the FIELD_* identifier of the field changed.
Definition at line 552 of file initialize.cpp.
References CELL_FLAG_GRIDCHANGED, CELL_STRUCTURE_CURRENT, cells_on_geometry_change(), cells_re_init(), EVENT_TRACE, FIELD_BOXL, FIELD_DPD_GAMMA, FIELD_DPD_IGNORE_FIXED_PARTICLES, FIELD_DPD_RCUT, FIELD_DPD_TGAMMA, FIELD_DPD_TRCUT, FIELD_INTEG_SWITCH, FIELD_LANGEVIN_GAMMA, FIELD_LATTICE_SWITCH, FIELD_LEES_EDWARDS_OFFSET, FIELD_MAXNUMCELLS, FIELD_MIN_GLOBAL_CUT, FIELD_MINNUMCELLS, FIELD_NODEGRID, FIELD_NPTISO_G0, FIELD_NPTISO_GV, FIELD_NPTISO_PISTON, FIELD_PERIODIC, FIELD_SKIN, FIELD_TEMPERATURE, FIELD_THERMO_SWITCH, FIELD_TIMESTEP, fields, grid_changed_box_l(), grid_changed_n_nodes(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso_struct::invalidate_p_vel, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, lb_reinit_parameters(), lb_reinit_parameters_gpu(), lees_edwards_step_boundaries(), nptiso, on_ghost_flags_change(), on_temperature_change(), recalc_maximal_cutoff(), reinit_thermo, and this_node.
Referenced by common_bcast_parameter(), mpi_set_smaller_time_step(), mpi_set_smaller_time_step_slave(), mpi_set_time_step(), and mpi_set_time_step_slave().
void on_particle_change ()
called every time a particle property is changed via Tcl.
Definition at line 272 of file initialize.cpp.
References EVENT_TRACE, freePartCfg(), invalidate_obs(), lb_reinit_particles_gpu, reinit_electrostatics, reinit_magnetostatics, resort_particles, and this_node.
void on_program_start ()
called once at the very beginning of the program start.
Definition at line 82 of file initialize.cpp.
References calc_processor_min_num_cells(), core(), cuda_init(), dd_topology_init(), reaction_struct::eq_rate, EVENT_TRACE, external_potential_pre_init(), force_and_energy_tables_init(), ghost_init(), init_bit_random(), init_node_grid(), init_random(), lb_pre_init(), local_cells, make_particle_type_exist(), min_num_cells, mpi_stop(), reaction, register_sigint_handler(), reaction_struct::sing_mult, and this_node.
Referenced by main().
void on_resort_particles ()
called every time the particles are resorted from node to node.
Definition at line 400 of file initialize.cpp.
References coulomb, COULOMB_ELC_P3M, COULOMB_MMM2D, EVENT_TRACE, Coulomb_parameters::method, MMM2D_on_resort_particles(), recalc_forces, and this_node.
Referenced by cells_resort_particles().
void on_short_range_ia_change ()
called every time short ranged interaction parameters are changed.
Definition at line 360 of file initialize.cpp.
References cells_on_geometry_change(), EVENT_TRACE, invalidate_obs(), recalc_forces, recalc_maximal_cutoff(), and this_node.
Referenced by mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), mpi_cap_forces_slave(), and on_coulomb_change().
void on_temperature_change ()
called every time the temperature changes.
This one is potentially slow.
Definition at line 534 of file initialize.cpp.
References EVENT_TRACE, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, lb_reinit_parameters(), lb_reinit_parameters_gpu(), and this_node.
Referenced by on_parameter_change().