ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: interaction_data.hpp File Reference
interaction_data.hpp File Reference
Various procedures concerning interactions between particles.
#include "utils.hpp"
#include "particle_data.hpp"
Data Structures
struct IA_parameters
field containing the interaction parameters for nonbonded interactions.
struct Coulomb_parameters
field containing the interaction parameters for the coulomb interaction.
struct Fene_bond_parameters
Parameters for FENE bond Potential.
struct Cg_dna_basepair_parameters
Parameters for the cg_dna potential Insert documentation here.
struct Cg_dna_stacking_parameters
struct Stretching_force_bond_parameters
Parameters for hyperelastic stretching_force.
struct Stretchlin_force_bond_parameters
Parameters for linear stretching_force.
struct Area_force_local_bond_parameters
Parameters for area_force_local.
struct Area_force_global_bond_parameters
Parameters for area_force_global.
struct Bending_force_bond_parameters
Parameters for bending_force.
struct Volume_force_bond_parameters
Parameters for volume_force.
struct Harmonic_bond_parameters
Parameters for harmonic bond Potential.
struct Harmonic_dumbbell_bond_parameters
Parameters for harmonic dumbbell bond Potential.
struct Quartic_bond_parameters
Parameters for quartic bond Potential.
struct Bonded_coulomb_bond_parameters
Parameters for coulomb bond Potential.
struct Angle_bond_parameters
Parameters for three body angular potential (bond-angle potentials).
struct Angle_harmonic_bond_parameters
Parameters for three body angular potential (bond_angle_harmonic).
struct Angle_cosine_bond_parameters
Parameters for three body angular potential (bond_angle_cosine).
struct Angle_cossquare_bond_parameters
Parameters for three body angular potential (bond_angle_cossquare).
struct Dihedral_bond_parameters
Parameters for four body angular potential (dihedral-angle potentials).
struct Tabulated_bond_parameters
Parameters for n-body tabulated potential (n=2,3,4).
struct Overlap_bond_parameters
Parameters for n-body overlapped potential (n=2,3,4).
struct Umbrella_bond_parameters
Parameters for umbrella potential.
struct Subt_lj_bond_parameters
Dummy parameters for -LJ Potential.
struct Rigid_bond_parameters
Parameters for the rigid_bond/SHAKE/RATTLE ALGORITHM.
struct Angledist_bond_parameters
Parameters for three body angular potential (bond-angle potentials) that depends on distance to wall constraint.
struct Endangledist_bond_parameters
Parameters for chainend angular potential with wall.
struct IBM_Triel_Parameters
Parameters for IBM elastic triangle (triel)
struct IBM_VolCons_Parameters
Parameters for IBM volume conservation bond.
struct IBM_Tribend_Parameters
Parameters for IBM tribend.
union Bond_parameters
Union in which to store the parameters of an individual bonded interaction.
struct Bonded_ia_parameters
Defines parameters for a bonded interaction.
struct Constraint_wall
Parameters for a WALL constraint (or a plane if you like that more).
struct Constraint_sphere
Parameters for a SPHERE constraint.
struct Constraint_cylinder
Parameters for a CYLINDER constraint.
struct Constraint_spherocylinder
Parameters for a SPHEROCYLINDER constraint.
struct Constraint_rhomboid
Parameters for a RHOMBOID constraint.
struct Constraint_pore
Parameters for a PORE constraint.
struct Constraint_slitpore
Parameters for a SLITPORE constraint.
struct Constraint_rod
Parameters for a ROD constraint.
struct Constraint_plate
Parameters for a PLATE constraint.
struct Constraint_maze
Parameters for a MAZE constraint.
struct Constraint_stomatocyte
Parameters for a STOMATOCYTE constraint.
struct Constraint_hollow_cone
Parameters for a HOLLOW_CONE constraint.
struct Constraint_box
Parameters for a BOX constraint.
struct Constraint_ext_magn_field
Parameters for a EXTERNAL MAGNETIC FIELD constraint.
struct Constraint_plane
Parameters for a plane constraint which is needed for tunable-slip boundary conditions.
struct SinusoidalField
struct Constraint
Structure to specify a constraint.
Macros
Tabulated potential
#define MAXLENGTH_TABFILE_NAME 256
The maximum allowable filename length for a tabulated potential file.
Enumerations
enum tElasticLaw { NeoHookean, Skalak }
enum tBendingMethod { TriangleNormals, NodeNeighbors }
Type codes for the type of Coulomb interaction
Enumeration of implemented methods for the electrostatic interaction.
enum CoulombMethod {
COULOMB_NONE, COULOMB_DH, COULOMB_P3M, COULOMB_MMM1D,
COULOMB_MMM2D, COULOMB_MAGGS, COULOMB_ELC_P3M, COULOMB_RF,
COULOMB_INTER_RF, COULOMB_P3M_GPU, COULOMB_MMM1D_GPU, COULOMB_EWALD_GPU,
COULOMB_EK
}
Type codes for the type of dipolar interaction
Enumeration of implemented methods for the magnetostatic interaction.
enum DipolarInteration {
DIPOLAR_NONE = 0, DIPOLAR_P3M, DIPOLAR_MDLC_P3M, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA,
DIPOLAR_DS, DIPOLAR_MDLC_DS
}
Type codes for constraints
Enumeration of implemented constraint types.
enum ConstraintApplied {
CONSTRAINT_NONE = 0, CONSTRAINT_WAL, CONSTRAINT_SPH, CONSTRAINT_CYL,
CONSTRAINT_ROD, CONSTRAINT_PLATE, CONSTRAINT_MAZE, CONSTRAINT_PORE,
CONSTRAINT_EXT_MAGN_FIELD, CONSTRAINT_PLANE, CONSTRAINT_RHOMBOID, CONSTRAINT_STOMATOCYTE,
CONSTRAINT_SLITPORE, CONSTRAINT_HOLLOW_CONE, CONSTRAINT_SPHEROCYLINDER
}
Functions
void force_and_energy_tables_init ()
Function for initializing force and energy tables.
int coulomb_set_bjerrum (double bjerrum)
int dipolar_set_Dbjerrum (double bjerrum)
void copy_ia_params (IA_parameters *dst, IA_parameters *src)
copy a set of interaction parameters.
IA_parameters * get_ia_param (int i, int j)
get interaction parameters between particle sorts i and j
IA_parameters * get_ia_param_safe (int i, int j)
get interaction parameters between particle sorts i and j.
void make_particle_type_exist (int type)
Makes sure that ia_params is large enough to cover interactions for this particle type.
void make_bond_type_exist (int type)
Makes sure that bonded_ia_params is large enough to cover the parameters for the bonded interaction type.
void realloc_ia_params (int nsize)
This function increases the LOCAL ia_params field to the given size.
void recalc_maximal_cutoff ()
calculates the maximal cutoff of all real space interactions.
void recalc_coulomb_prefactor ()
call when the temperature changes, for Bjerrum length adjusting.
int interactions_sanity_checks ()
check whether all force calculation routines are properly initialized.
int checkIfInteraction (IA_parameters *data)
check if a non bonded interaction is defined
int checkIfParticlesInteract (int i, int j)
check if the types of particles i and j have any non bonded interaction defined.
const char * get_name_of_bonded_ia (BondedInteraction type)
int virtual_set_params (int bond_type)
Variables
int n_particle_types
Maximal particle type seen so far.
int n_interaction_types
Coulomb_parameters coulomb
Structure containing the coulomb parameters.
int n_bonded_ia
number of bonded interactions.
Bonded_ia_parameters * bonded_ia_params
Field containing the paramters of the bonded ia types.
DoubleList tabulated_forces
Array containing all tabulated forces.
DoubleList tabulated_energies
Array containing all tabulated energies.
double max_cut
Maximal interaction cutoff (real space/short range interactions).
double max_cut_nonbonded
Maximal interaction cutoff (real space/short range non-bonded interactions).
double max_cut_bonded
Maximal interaction cutoff (real space/short range bonded interactions).
double min_global_cut
Minimal global interaction cutoff.
int ia_excl
Switch for nonbonded interaction exclusion.
Compounds for Coulomb interactions
thermodynamic force parameters
double field_induced
Induced field (for const.
double field_applied
Applied field (for const.
Type codes of bonded interactions
Enumeration of implemented bonded interactions.
#define INACTIVE_CUTOFF -1.0
cutoff for deactivated interactions.
enum BondedInteraction {
BONDED_IA_NONE = -1, BONDED_IA_FENE, BONDED_IA_HARMONIC, BONDED_IA_HARMONIC_DUMBBELL,
BONDED_IA_QUARTIC, BONDED_IA_BONDED_COULOMB, BONDED_IA_ANGLE_OLD, BONDED_IA_DIHEDRAL,
BONDED_IA_TABULATED, BONDED_IA_SUBT_LJ, BONDED_IA_RIGID_BOND, BONDED_IA_VIRTUAL_BOND,
BONDED_IA_ANGLEDIST, BONDED_IA_ENDANGLEDIST, BONDED_IA_OVERLAPPED, BONDED_IA_ANGLE_HARMONIC,
BONDED_IA_ANGLE_COSINE, BONDED_IA_ANGLE_COSSQUARE, BONDED_IA_STRETCHING_FORCE, BONDED_IA_AREA_FORCE_LOCAL,
BONDED_IA_BENDING_FORCE, BONDED_IA_VOLUME_FORCE, BONDED_IA_AREA_FORCE_GLOBAL, BONDED_IA_STRETCHLIN_FORCE,
BONDED_IA_CG_DNA_BASEPAIR, BONDED_IA_CG_DNA_STACKING, BONDED_IA_CG_DNA_BACKBONE, BONDED_IA_IBM_TRIEL,
BONDED_IA_IBM_VOLUME_CONSERVATION, BONDED_IA_IBM_TRIBEND, BONDED_IA_UMBRELLA
}
enum TabulatedBondedInteraction { TAB_UNKNOWN = 0, TAB_BOND_LENGTH, TAB_BOND_ANGLE, TAB_BOND_DIHEDRAL }
Specify tabulated bonded interactions.
enum OverlappedBondedInteraction { OVERLAP_UNKNOWN = 0, OVERLAP_BOND_LENGTH, OVERLAP_BOND_ANGLE, OVERLAP_BOND_DIHEDRAL }
Specify overlapped bonded interactions.
Detailed Description
Various procedures concerning interactions between particles.
Definition in file interaction_data.hpp.
Macro Definition Documentation
#define INACTIVE_CUTOFF -1.0
cutoff for deactivated interactions.
Below 0, so that even particles on top of each other don't interact by chance.
Definition at line 125 of file interaction_data.hpp.
Referenced by initialize_ia_params().
#define MAXLENGTH_TABFILE_NAME 256
The maximum allowable filename length for a tabulated potential file.
Definition at line 443 of file interaction_data.hpp.
Referenced by tabulated_set_params().
Enumeration Type Documentation
enum BondedInteraction
Enumerator
BONDED_IA_NONE
This bonded interaction was not set.
BONDED_IA_FENE
Type of bonded interaction is a FENE potential (to be combined with Lennard Jones).
BONDED_IA_HARMONIC
Type of bonded interaction is a HARMONIC potential.
BONDED_IA_HARMONIC_DUMBBELL
Type of bonded interaction is a HARMONIC_DUMBBELL potential.
BONDED_IA_QUARTIC
Type of bonded interaction is a QUARTIC potential.
BONDED_IA_BONDED_COULOMB
Type of bonded interaction is a BONDED_COULOMB.
BONDED_IA_ANGLE_OLD
Type of bonded interaction is a bond angle potential.
BONDED_IA_DIHEDRAL
Type of bonded interaction is a dihedral potential.
BONDED_IA_TABULATED
Type of tabulated bonded interaction potential, may be of bond length, of bond angle or of dihedral type.
BONDED_IA_SUBT_LJ
Type of bonded interaction is a (-LJ) potential.
BONDED_IA_RIGID_BOND
Type of a Rigid/Constrained bond.
BONDED_IA_VIRTUAL_BOND
Type of a virtual bond.
BONDED_IA_ANGLEDIST
Type of bonded interaction is a bond angle – constraint distance potential.
BONDED_IA_ENDANGLEDIST
Type of bonded interaction is a bond angle – chain ends have angle with wall constraint.
BONDED_IA_OVERLAPPED
Type of overlapped bonded interaction potential, may be of bond length, of bond angle or of dihedral type.
BONDED_IA_ANGLE_HARMONIC
Type of bonded interaction is a bond angle cosine potential.
BONDED_IA_ANGLE_COSINE
Type of bonded interaction is a bond angle cosine potential.
BONDED_IA_ANGLE_COSSQUARE
Type of bonded interaction is a bond angle cosine potential.
BONDED_IA_STRETCHING_FORCE
Type of bonded interaction is a hyperelastic stretching force.
BONDED_IA_AREA_FORCE_LOCAL
Type of bonded interaction is a local area force.
BONDED_IA_BENDING_FORCE
Type of bonded interaction is a bending force.
BONDED_IA_VOLUME_FORCE
Type of bonded interaction is a bending force.
BONDED_IA_AREA_FORCE_GLOBAL
Type of bonded interaction is a global area force.
BONDED_IA_STRETCHLIN_FORCE
Type of bonded interaction is a linear stretching force.
BONDED_IA_CG_DNA_BASEPAIR
Type of bonded interaction for cg DNA.
BONDED_IA_CG_DNA_STACKING
Type of bonded interaction for cg DNA.
BONDED_IA_CG_DNA_BACKBONE
Type of bonded interaction for cg DNA.
BONDED_IA_IBM_TRIEL
Type of bonded interaction is a wall repulsion (immersed boundary).
BONDED_IA_IBM_VOLUME_CONSERVATION
Type of bonded interaction is volume conservation force (immersed boundary).
BONDED_IA_IBM_TRIBEND
Type of bonded interaction is bending force (immersed boundary).
BONDED_IA_UMBRELLA
Type of bonded interaction is umbrella.
Definition at line 37 of file interaction_data.hpp.
enum ConstraintApplied
Enumerator
CONSTRAINT_NONE
No constraint applied.
CONSTRAINT_WAL
wall constraint applied
CONSTRAINT_SPH
spherical constraint applied
CONSTRAINT_CYL
(finite) cylinder shaped constraint applied
CONSTRAINT_ROD
Rod-like charge.
CONSTRAINT_PLATE
Plate-like charge.
CONSTRAINT_MAZE
maze-like constraint applied
CONSTRAINT_PORE
pore constraint applied
CONSTRAINT_EXT_MAGN_FIELD
External magnetic field constraint applied.
CONSTRAINT_PLANE
Constraint for tunable-lsip boundary conditions.
CONSTRAINT_RHOMBOID
Constraint for tunable-lsip boundary conditions.
CONSTRAINT_STOMATOCYTE
Constraint for a stomatocyte boundary.
CONSTRAINT_SLITPORE
slitpore constraint applied
CONSTRAINT_HOLLOW_CONE
Constraint for a hollow cone boundary.
CONSTRAINT_SPHEROCYLINDER
Constraint for spherocylinder boundary.
Definition at line 188 of file interaction_data.hpp.
enum CoulombMethod
Enumerator
COULOMB_NONE
COULOMB_DH
COULOMB_P3M
COULOMB_MMM1D
COULOMB_MMM2D
COULOMB_MAGGS
COULOMB_ELC_P3M
COULOMB_RF
COULOMB_INTER_RF
COULOMB_P3M_GPU
COULOMB_MMM1D_GPU
COULOMB_EWALD_GPU
COULOMB_EK
Definition at line 137 of file interaction_data.hpp.
enum DipolarInteration
Enumerator
DIPOLAR_NONE
dipolar interation switched off (NONE).
DIPOLAR_P3M
dipolar method is P3M.
DIPOLAR_MDLC_P3M
Dipolar method is P3M plus DLC.
DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA
Dipolar method is all with all and no replicas.
DIPOLAR_DS
Dipolar method is magnetic dipolar direct sum.
DIPOLAR_MDLC_DS
Dipolar method is direct sum plus DLC.
Definition at line 164 of file interaction_data.hpp.
enum OverlappedBondedInteraction
Specify overlapped bonded interactions.
Enumerator
OVERLAP_UNKNOWN
OVERLAP_BOND_LENGTH
OVERLAP_BOND_ANGLE
OVERLAP_BOND_DIHEDRAL
Definition at line 116 of file interaction_data.hpp.
enum TabulatedBondedInteraction
Specify tabulated bonded interactions.
Enumerator
TAB_UNKNOWN
TAB_BOND_LENGTH
TAB_BOND_ANGLE
TAB_BOND_DIHEDRAL
Definition at line 108 of file interaction_data.hpp.
enum tBendingMethod
Enumerator
TriangleNormals
NodeNeighbors
Definition at line 828 of file interaction_data.hpp.
enum tElasticLaw
Enumerator
NeoHookean
Skalak
Definition at line 789 of file interaction_data.hpp.
Function Documentation
int checkIfInteraction (IA_parameters * data) inline
check if a non bonded interaction is defined
Definition at line 1255 of file interaction_data.hpp.
References IA_parameters::particlesInteract.
Referenced by add_constraints_energy(), add_constraints_forces(), and checkIfParticlesInteract().
int checkIfParticlesInteract (int i, int j) inline
check if the types of particles i and j have any non bonded interaction defined.
Definition at line 1261 of file interaction_data.hpp.
References checkIfInteraction(), and get_ia_param().
Referenced by get_nonbonded_interaction(), tclcommand_analyze_print_all(), tclcommand_analyze_print_pressure_all(), tclcommand_analyze_print_stress_tensor_all(), and tclcommand_inter_print_all().
void copy_ia_params (IA_parameters * dst, IA_parameters * src)
copy a set of interaction parameters.
copy a set of interaction parameters.
Definition at line 347 of file interaction_data.cpp.
Referenced by mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), and realloc_ia_params().
int coulomb_set_bjerrum (double bjerrum)
Definition at line 881 of file interaction_data.cpp.
References Reaction_field_params::B, Coulomb_parameters::bjerrum, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_INTER_RF, COULOMB_MMM1D, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, Reaction_field_params::epsilon1, Reaction_field_params::epsilon2, ES_ERROR, ES_OK, Debye_hueckel_params::kappa, Reaction_field_params::kappa, MMM1D_struct::maxPWerror, Coulomb_parameters::method, mmm1d_params, mpi_bcast_coulomb_params(), Debye_hueckel_params::r_cut, and Reaction_field_params::r_cut.
Referenced by tclcommand_inter_parse_coulomb().
int dipolar_set_Dbjerrum (double bjerrum)
Definition at line 929 of file interaction_data.cpp.
References Coulomb_parameters::Dbjerrum, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, ES_ERROR, ES_OK, and mpi_bcast_coulomb_params().
Referenced by tclcommand_inter_parse_magnetic().
void force_and_energy_tables_init ()
Function for initializing force and energy tables.
Function for initializing force and energy tables.
Definition at line 129 of file interaction_data.cpp.
References init_doublelist().
Referenced by on_program_start().
IA_parameters* get_ia_param (int i, int j) inline
get interaction parameters between particle sorts i and j
Definition at line 1211 of file interaction_data.hpp.
References ia_params, and n_particle_types.
Referenced by add_constraints_energy(), add_constraints_forces(), add_non_bonded_pair_energy(), add_non_bonded_pair_force(), build_verlet_lists(), build_verlet_lists_and_calc_verlet_ia(), build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_buck_cap_radii(), calc_comfixed(), calc_comforce(), calc_link_cell_iccp3m(), calc_lj_cap_radii(), calc_ljangle_cap_radii(), calc_ljcos2_cap_radii(), calc_ljgen_cap_radii(), calc_morse_cap_radii(), calc_non_bonded_pair_force(), calc_non_bonded_pair_force_from_partcfg_simple(), calc_subt_lj_pair_force(), check_tab_forcecap(), checkIfParticlesInteract(), get_ia_param_safe(), inter_dpd_init(), inter_dpd_switch_off(), inter_dpd_update_params(), mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), recalc_maximal_cutoff_nonbonded(), subt_lj_pair_energy(), tclcommand_inter_print_non_bonded(), tclprint_to_result_affinityIA(), tclprint_to_result_BMHTFIA(), tclprint_to_result_buckIA(), tclprint_to_result_comfixedIA(), tclprint_to_result_comforceIA(), tclprint_to_result_cos2IA(), tclprint_to_result_GaussianIA(), tclprint_to_result_gbIA(), tclprint_to_result_hatIA(), tclprint_to_result_HertzianIA(), tclprint_to_result_inter_dpdIA(), tclprint_to_result_interrfIA(), tclprint_to_result_ljangleIA(), tclprint_to_result_ljcos2IA(), tclprint_to_result_ljcosIA(), tclprint_to_result_ljgenIA(), tclprint_to_result_ljIA(), tclprint_to_result_molcutIA(), tclprint_to_result_morseIA(), tclprint_to_result_NonbondedIA(), tclprint_to_result_SmStIA(), tclprint_to_result_softIA(), tclprint_to_result_tunable_slipIA(), and test_mesh_elements().
IA_parameters* get_ia_param_safe (int i, int j)
get interaction parameters between particle sorts i and j.
Slower than get_ia_param, but can also be used on not yet present particle types
Definition at line 351 of file interaction_data.cpp.
References get_ia_param(), imax(), and make_particle_type_exist().
Referenced by affinity_set_params(), BMHTF_set_params(), buckingham_set_params(), comfixed_set_params(), comforce_set_params(), cos2_set_params(), gaussian_set_params(), gay_berne_set_params(), hat_set_params(), hertzian_set_params(), inter_dpd_set_params(), interrf_set_params(), lennard_jones_set_params(), lj_cos_set_params(), ljangle_set_params(), ljcos2_set_params(), ljgen_set_params(), local_setup_reaction(), molcut_set_params(), morse_set_params(), smooth_step_set_params(), soft_sphere_set_params(), tabulated_set_params(), and tunable_slip_set_params().
const char* get_name_of_bonded_ia (BondedInteraction type)
Definition at line 692 of file interaction_data.cpp.
References BONDED_IA_ANGLE_COSINE, BONDED_IA_ANGLE_COSSQUARE, BONDED_IA_ANGLE_HARMONIC, BONDED_IA_ANGLE_OLD, BONDED_IA_ANGLEDIST, BONDED_IA_AREA_FORCE_GLOBAL, BONDED_IA_AREA_FORCE_LOCAL, BONDED_IA_BENDING_FORCE, BONDED_IA_BONDED_COULOMB, BONDED_IA_CG_DNA_BASEPAIR, BONDED_IA_CG_DNA_STACKING, BONDED_IA_DIHEDRAL, BONDED_IA_ENDANGLEDIST, BONDED_IA_FENE, BONDED_IA_HARMONIC, BONDED_IA_HARMONIC_DUMBBELL, BONDED_IA_IBM_TRIBEND, BONDED_IA_IBM_TRIEL, BONDED_IA_IBM_VOLUME_CONSERVATION, BONDED_IA_OVERLAPPED, BONDED_IA_QUARTIC, BONDED_IA_RIGID_BOND, BONDED_IA_STRETCHING_FORCE, BONDED_IA_STRETCHLIN_FORCE, BONDED_IA_SUBT_LJ, BONDED_IA_TABULATED, BONDED_IA_UMBRELLA, BONDED_IA_VIRTUAL_BOND, BONDED_IA_VOLUME_FORCE, errexit(), and this_node.
Referenced by tclcommand_analyze_print_all(), tclcommand_analyze_print_pressure_all(), and tclcommand_analyze_print_stress_tensor_all().
int interactions_sanity_checks ()
check whether all force calculation routines are properly initialized.
Definition at line 840 of file interaction_data.cpp.
References COULOMB_ELC_P3M, COULOMB_MMM1D, COULOMB_MMM2D, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, Coulomb_parameters::Dmethod, magnetic_dipolar_direct_sum_sanity_checks(), mdlc_sanity_checks(), Coulomb_parameters::method, MMM1D_sanity_checks(), and MMM2D_sanity_checks().
Referenced by energy_calc(), on_integration_start(), and pressure_calc().
void make_bond_type_exist (int type)
Makes sure that bonded_ia_params is large enough to cover the parameters for the bonded interaction type.
Attention: 1: There is no initialization done here. 2: Use only in connection with creating new or overwriting old bond types
Definition at line 808 of file interaction_data.cpp.
References BONDED_IA_NONE, BONDED_IA_OVERLAPPED, BONDED_IA_TABULATED, free, i, n_bonded_ia, and realloc.
Referenced by angle_cosine_set_params(), angle_cossquare_set_params(), angle_harmonic_set_params(), angle_set_params(), angledist_set_params(), area_force_global_set_params(), area_force_local_set_params(), bending_force_set_params(), bonded_coulomb_set_params(), dihedral_set_params(), endangledist_set_params(), fene_set_params(), harmonic_dumbbell_set_params(), harmonic_set_params(), hydrogen_bond_set_params(), IBM_Tribend_SetParams(), IBM_Triel_SetParams(), IBM_VolumeConservation_SetParams(), mpi_bcast_ia_params_slave(), overlapped_bonded_set_params(), quartic_set_params(), rigid_bond_set_params(), stretching_force_set_params(), stretchlin_force_set_params(), subt_lj_set_params(), tabulated_bonded_set_params(), twist_stack_set_params(), umbrella_set_params(), virtual_set_params(), and volume_force_set_params().
void make_particle_type_exist (int type)
Makes sure that ia_params is large enough to cover interactions for this particle type.
The interactions are initialized with values such that no physical interaction occurs.
Definition at line 800 of file interaction_data.cpp.
References mpi_bcast_n_particle_types(), and n_particle_types.
Referenced by collision_detection_set_params(), get_ia_param_safe(), local_setup_reaction(), on_program_start(), set_particle_type(), tclcommand_constraint_parse_cylinder(), tclcommand_constraint_parse_hollow_cone(), tclcommand_constraint_parse_maze(), tclcommand_constraint_parse_plane_cell(), tclcommand_constraint_parse_pore(), tclcommand_constraint_parse_rhomboid(), tclcommand_constraint_parse_slitpore(), tclcommand_constraint_parse_sphere(), tclcommand_constraint_parse_stomatocyte(), tclcommand_constraint_parse_wall(), and tclcommand_inter_print_non_bonded().
void realloc_ia_params (int nsize)
This function increases the LOCAL ia_params field to the given size.
Better use make_particle_type_exist since it takes care of the other nodes.
This function increases the LOCAL ia_params field to the given size.
This function is not exported since it does not do this on all nodes. Use make_particle_type_exist for that.
Definition at line 769 of file interaction_data.cpp.
References copy_ia_params(), free, i, initialize_ia_params(), malloc, and n_particle_types.
Referenced by mpi_bcast_n_particle_types_slave().
void recalc_coulomb_prefactor ()
call when the temperature changes, for Bjerrum length adjusting.
Definition at line 961 of file interaction_data.cpp.
References Coulomb_parameters::bjerrum, Coulomb_parameters::Dbjerrum, Coulomb_parameters::Dprefactor, Coulomb_parameters::prefactor, and temperature.
Referenced by on_coulomb_change().
void recalc_maximal_cutoff ()
calculates the maximal cutoff of all real space interactions.
these are: bonded, non bonded + real space electrostatics. The result is stored in the global variable max_cut. The maximal cutoff of the non-bonded + real space electrostatic interactions is stored in max_cut_non_bonded. This value is used in the verlet pair list algorithm (see verlet.hpp).
Definition at line 679 of file interaction_data.cpp.
References max_cut, max_cut_bonded, max_cut_nonbonded, recalc_maximal_cutoff_bonded(), and recalc_maximal_cutoff_nonbonded().
Referenced by on_parameter_change(), on_short_range_ia_change(), and propagate_press_box_pos_and_rescale_npt().
int virtual_set_params (int bond_type)
Definition at line 979 of file interaction_data.cpp.
References BONDED_IA_VIRTUAL_BOND, ES_ERROR, ES_OK, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_virtual_bonds().
Variable Documentation
Bonded_ia_parameters* bonded_ia_params
Field containing the paramters of the bonded ia types.
Definition at line 96 of file interaction_data.cpp.
Referenced by add_area_global_force(), add_bonded_energy(), add_bonded_force(), add_bonded_virials(), add_three_body_bonded_stress(), add_volume_force(), angle_cosine_set_params(), angle_cossquare_set_params(), angle_harmonic_set_params(), angle_set_params(), angledist_set_params(), area_force_global_set_params(), area_force_local_set_params(), auto_exclusion(), bending_force_set_params(), bonded_coulomb_set_params(), calc_area_global(), calc_volume(), CalcVolumeForce(), CalcVolumes(), collectBonds(), collision_detection_set_params(), compute_pos_corr_vec(), compute_vel_corr_vec(), detect_collision(), dihedral_set_params(), endangledist_set_params(), fene_set_params(), handle_collisions(), harmonic_dumbbell_set_params(), harmonic_set_params(), hydrogen_bond_set_params(), IBM_InitVolumeConservation(), IBM_Tribend_ResetParams(), IBM_Tribend_SetParams(), IBM_Triel_ResetParams(), IBM_Triel_SetParams(), IBM_VolumeConservation_ResetParams(), IBM_VolumeConservation_SetParams(), local_change_bond(), local_stress_tensor_calc(), mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), mpi_send_bond(), overlapped_bonded_set_params(), polymerC(), print_bond_len(), quartic_set_params(), remove_all_bonds_to(), rigid_bond_set_params(), stretching_force_set_params(), stretchlin_force_set_params(), subt_lj_set_params(), tabulated_bonded_set_params(), tclcommand_analyze_print_all(), tclcommand_analyze_print_pressure_all(), tclcommand_analyze_print_stress_tensor_all(), tclcommand_diamond(), tclcommand_icosaeder(), tclcommand_inter_print_all(), tclcommand_inter_print_partner_num(), tclcommand_part_parse_bond(), tclcommand_part_print_bond_partners(), tclcommand_part_print_bonding_structure(), tclprint_to_result_BondedIA(), try_delete_bond(), twist_stack_set_params(), umbrella_set_params(), and volume_force_set_params().
Coulomb_parameters coulomb
Structure containing the coulomb parameters.
Definition at line 75 of file interaction_data.cpp.
Referenced by add_dh_coulomb_pair_force(), add_ewald_gpu_coulomb_pair_force(), add_mdlc_energy_corrections(), add_mdlc_force_corrections(), add_mmm1d_coulomb_pair_force(), add_mmm2d_coulomb_pair_force(), add_non_bonded_pair_energy(), add_non_bonded_pair_force(), add_non_bonded_pair_force_iccp3m(), add_non_bonded_pair_virials(), add_plate_force(), add_rf_coulomb_pair_force_no_cutoff(), add_rod_force(), add_z_force(), calc_dipole_dipole_ia(), calc_long_range_energies(), calc_long_range_forces(), calc_long_range_forces_iccp3m(), calc_long_range_virials(), Mmm1dgpuForce::computeEnergy(), EwaldgpuForce::computeEnergy(), Mmm1dgpuForce::computeForces(), EwaldgpuForce::computeForces(), dawaanr_set_params(), dh_coulomb_pair_energy(), EwaldgpuForce::EwaldCPU_EnergySelf(), ewaldgpu_coulomb_pair_energy(), get_nonbonded_interaction(), EwaldgpuForce::GPU_Energy(), iccp3m_iteration(), iccp3m_sanity_check(), init_energies(), init_p_tensor(), init_virials(), integrate_sd(), integrate_set_npt_isotropic(), integrate_vv(), integrator_npt_sanity_checks(), maggs_init(), magnetic_dipolar_direct_sum_calculations(), mdds_set_params(), mdlc_set_params(), mmm1d_coulomb_pair_energy(), MMM1D_init(), MMM1D_set_params(), mmm1d_tune(), mmm2d_coulomb_pair_energy(), MMM2D_dielectric_layers_energy_contribution(), MMM2D_dielectric_layers_force_contribution(), MMM2D_init(), MMM2D_self_energy(), MMM2D_set_params(), mpi_bcast_coulomb_params_slave(), on_boxl_change(), on_cell_structure_change(), on_coulomb_change(), on_ghost_flags_change(), on_observable_calc(), on_resort_particles(), p3m_gpu_add_farfield_force(), plate_energy(), rf_coulomb_pair_energy_no_cutoff(), rod_energy(), EwaldgpuForce::setup(), Mmm1dgpuForce::setup(), setup_P(), setup_PQ(), setup_Q(), setup_z_energy(), setup_z_force(), tclcommand_analyze_print_all(), tclcommand_analyze_print_pressure_all(), tclcommand_analyze_print_stress_tensor_all(), tclcommand_integrate_set_npt_isotropic(), tclcommand_inter_coulomb_parse_dh(), tclcommand_inter_coulomb_parse_ewaldgpu_notune(), tclcommand_inter_coulomb_parse_ewaldgpu_tune(), tclcommand_inter_coulomb_parse_ewaldgpu_tunealpha(), tclcommand_inter_coulomb_parse_maggs(), tclcommand_inter_coulomb_parse_mmm1dgpu(), tclcommand_inter_coulomb_parse_rf(), tclcommand_inter_parse_coulomb(), tclcommand_inter_parse_magnetic(), tclcommand_inter_print_all(), tclcommand_print_efield_capacitors(), tclprint_to_result_CoulombIA(), tclprint_to_result_DipolarIA(), and z_energy().
double field_applied
Applied field (for const.
potential feature)
Definition at line 92 of file interaction_data.cpp.
Referenced by add_z_force(), and tclcommand_print_efield_capacitors().
double field_induced
Induced field (for const.
potential feature).
potential feature)
Definition at line 90 of file interaction_data.cpp.
Referenced by add_z_force(), and tclcommand_print_efield_capacitors().
int ia_excl
Switch for nonbonded interaction exclusion.
double max_cut
Maximal interaction cutoff (real space/short range interactions).
Maximal interaction cutoff (real space/short range interactions).
Definition at line 100 of file interaction_data.cpp.
Referenced by recalc_maximal_cutoff().
double max_cut_bonded
Maximal interaction cutoff (real space/short range bonded interactions).
Definition at line 102 of file interaction_data.cpp.
Referenced by recalc_maximal_cutoff(), recalc_maximal_cutoff_bonded(), and recalc_maximal_cutoff_nonbonded().
double max_cut_nonbonded
Maximal interaction cutoff (real space/short range non-bonded interactions).
Definition at line 101 of file interaction_data.cpp.
Referenced by build_verlet_lists(), build_verlet_lists_and_calc_verlet_ia(), build_verlet_lists_and_calc_verlet_ia_iccp3m(), calculate_verlet_energies(), calculate_verlet_virials(), recalc_maximal_cutoff(), recalc_maximal_cutoff_nonbonded(), and tclcommand_analyze_parse_aggregation().
double min_global_cut
Minimal global interaction cutoff.
Particles with a distance smaller than this are guaranteed to be available on the same node (through ghosts).
Definition at line 98 of file interaction_data.cpp.
Referenced by recalc_global_maximal_nonbonded_cutoff(), tclcallback_min_global_cut(), and vs_relate_to().
int n_bonded_ia
number of bonded interactions.
Not used so far.
Definition at line 95 of file interaction_data.cpp.
Referenced by change_particle_bond(), collision_detection_set_params(), IBM_InitVolumeConservation(), IBM_Tribend_ResetParams(), IBM_Triel_ResetParams(), IBM_VolumeConservation_ResetParams(), init_energies(), init_p_tensor(), init_virials(), make_bond_type_exist(), obsstat_realloc_and_clear(), recalc_maximal_cutoff_bonded(), tclcommand_analyze_parse_and_print_energy(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_all(), tclcommand_analyze_print_pressure_all(), tclcommand_analyze_print_stress_tensor_all(), tclcommand_diamond(), tclcommand_icosaeder(), tclcommand_inter_print_all(), tclcommand_inter_print_bonded(), tclcommand_inter_print_partner_num(), and tclcommand_part_parse_bond().
int n_interaction_types
Definition at line 71 of file interaction_data.cpp.
int n_particle_types
Maximal particle type seen so far.
Definition at line 70 of file interaction_data.cpp.
Referenced by calc_buck_cap_radii(), calc_comfixed(), calc_comforce(), calc_lj_cap_radii(), calc_ljangle_cap_radii(), calc_ljcos2_cap_radii(), calc_ljgen_cap_radii(), calc_morse_cap_radii(), calc_structurefactor(), check_tab_forcecap(), external_potential_tabulated_init(), get_ia_param(), init_energies(), init_p_tensor(), init_p_tensor_non_bonded(), init_virials(), init_virials_non_bonded(), inter_dpd_init(), inter_dpd_switch_off(), inter_dpd_update_params(), make_particle_type_exist(), mpi_external_potential_broadcast(), mpi_external_potential_broadcast_slave(), obsstat_nonbonded(), obsstat_nonbonded_inter(), obsstat_nonbonded_intra(), realloc_ia_params(), recalc_maximal_cutoff_nonbonded(), tclcommand_analyze_parse_and_print_energy(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_parse_gyration_tensor(), tclcommand_analyze_parse_holes(), tclcommand_analyze_print_all(), tclcommand_analyze_print_pressure_all(), tclcommand_analyze_print_stress_tensor_all(), and tclcommand_inter_print_all().
DoubleList tabulated_energies
Array containing all tabulated energies.
Array containing all tabulated energies.
Definition at line 110 of file interaction_data.cpp.
Referenced by mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), tabulated_pair_energy(), and tabulated_set_params().
DoubleList tabulated_forces
Array containing all tabulated forces.
Definition at line 108 of file interaction_data.cpp.
Referenced by add_tabulated_pair_force(), check_tab_forcecap(), mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), tabulated_pair_energy(), and tabulated_set_params().