ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: integrate_tcl.hpp File Reference
integrate_tcl.hpp File Reference
#include "parser.hpp"
Functions
Exported Functions
int tclcommand_integrate (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure for integrator steering.
int tclcallback_skin (Tcl_Interp *interp, void *_data)
Callback for the skin.
int tclcallback_time_step (Tcl_Interp *interp, void *_data)
Callback for integration time_step (0.0 <= time_step).
int tclcallback_smaller_time_step (Tcl_Interp *interp, void *_data)
Callback for integration time_step (0.0 <= time_step).
int tclcallback_time (Tcl_Interp *interp, void *_data)
Callback for current time in the integration.
int tclcommand_invalidate_system (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implements the obsolete tcl-command 'invalidate_system'.
Function Documentation
int tclcallback_skin (Tcl_Interp * interp, void * _data)
Callback for the skin.
Definition at line 272 of file integrate_tcl.cpp.
References FIELD_SKIN, mpi_bcast_parameter(), skin, and skin_set.
Referenced by tcl_register_global_variables().
int tclcallback_smaller_time_step (Tcl_Interp * interp, void * _data)
Callback for integration time_step (0.0 <= time_step).
Returns
TCL status.
Definition at line 313 of file integrate_tcl.cpp.
References mpi_set_smaller_time_step(), and time_step.
Referenced by tcl_register_global_variables().
int tclcallback_time (Tcl_Interp * interp, void * _data)
Callback for current time in the integration.
Definition at line 333 of file integrate_tcl.cpp.
References FIELD_SIMTIME, mpi_bcast_parameter(), and sim_time.
Referenced by tcl_register_global_variables().
int tclcallback_time_step (Tcl_Interp * interp, void * _data)
Callback for integration time_step (0.0 <= time_step).
Definition at line 285 of file integrate_tcl.cpp.
References lbpar, lbpar_gpu, mpi_set_time_step(), LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by tcl_register_global_variables().
int tclcommand_integrate (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure for integrator steering.
For documentation, see tclcommand_integrate
Definition at line 200 of file integrate_tcl.cpp.
References ARG1_IS_S, ARG_IS_I, ARG_IS_S, autoupdate_correlations(), autoupdate_observables(), correlations_autoupdate, FIELD_SKIN, gather_runtime_errors(), i, INTEG_TRACE, max_cut, mpi_bcast_parameter(), mpi_integrate(), observables_autoupdate, skin, skin_set, tclcommand_integrate_print_status(), tclcommand_integrate_print_usage(), tclcommand_integrate_set_npt_isotropic(), tclcommand_integrate_set_nvt(), and this_node.
Referenced by tcl_register_commands().
int tclcommand_invalidate_system (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implements the obsolete tcl-command 'invalidate_system'.
Definition at line 39 of file integrate_tcl.cpp.
Referenced by tcl_register_commands().