ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: integrate_sd_cuda.cu File Reference
integrate_sd_cuda.cu File Reference
Stokes dynamics integrator.
#include "config.hpp"
#include <stdio.h>
#include <iostream>
#include "cuda_runtime.h"
#include "curand.h"
#include <device_functions.h>
#include <algorithm>
#include "assert.h"
#include "integrate_sd_cuda.hpp"
#include "integrate_sd_cuda_debug.hpp"
#include "integrate_sd_cuda_kernel.hpp"
#include "integrate_sd.hpp"
#include <cublas_v2.h>
#include "global.hpp"
Macros
#define sd_gmres_solver_exit()
Functions
void propagate_pos_sd_cuda (real *box_l_h, int N, real *pos_h, real *force_h, real *velo_h)
void sd_compute_displacement (const real *r_d, int N, real viscosity, real radius, const real *L_d, const real *L_h, const real *total_mobility_d, const real *force_d, real *disp_d, int *myInfo_d)
real sd_iterative_solver (const matrix &mobility, const matrix &resistance, const real *force, real *disp, real rel_tol, real abs_tol, bool recalc)
this calls an iterative solver to solve the problem: disp * (1+resistance*mobility) = mobility_d * force_d and returnes
int sd_gmres_solver (const matrix &A1, const matrix &A2, const real *b, real tol, real abs_tol, int maxit, real *x, real *res)
void calculate_maxmin_eigenvalues (const matrix &mobility, real *lambda_min, real *lambda_max, real tol)
real calculate_chebyshev_coefficents (real lambda_min, real lambda_max, real tol, real **coefficents)
caclulate the chebyshev coefficents for the squareroot of the matrix It needs the largest and smalles eigenvalue which have to be computed before. Using chebyshev-gausquadrature https://en.wikipedia.org/wiki/Chebyshev%E2%80%93Gauss_quadrature.
real sd_compute_brownian_force_farfield (const matrix &mobility, const real *gaussian_ff, real tol, real *brownian_force_ff)
Compute the brownian force resulting from the farfield To compute the farfield contribution of the brownian motion the squareroot of the inverse of the mobility is required. Instead of calculating it directly, its action on the vector containing the randomnumbers is computed via the chebyshev-polynomials. In the case of FF_ONLY this computes directly the displacement!
void sd_Rgemv (const real *factor, const matrix &A, const real *in, real *out)
void sd_compute_mobility_matrix_wave_cpu (int kmax, real kmax2, matrix &mobility, real a, const real *L_h, real xi, real selfmobility, real ew_prec)
void _cuda_check_error (char *file, unsigned int line)
int sd_find_max (int *data, int length)
Variables
cublasHandle_t cublas = NULL
curandGenerator_t generator = NULL
int reprint =-1
Detailed Description
Stokes dynamics integrator.
Here the calculation of the displacements is implemented.
Definition in file integrate_sd_cuda.cu.
Macro Definition Documentation
#define sd_gmres_solver_exit ()
Value:
cuda_safe_mem(cudaFree((void*)r0));     \
  cuda_safe_mem(cudaFree((void*)v));cuda_safe_mem(cudaFree((void*)w));  \
  cuda_safe_mem(cudaFree((void*)tmp)); res[0] = normr;                  \
  if (warnings > 1) printf("GMRes used %d iterations.\n", iteration);   \
  if (tolb*1.01 >= normr)     { return 0;}                              \
  printf("tolb: %e, normr: %e, eps: %e \n",tolb, normr, eps);           \
  if (tolb*100 > normr)       { return 1;}                              \
  if (initnorm*1e10 >= normr) { return 2;}                              \
  else                        { return 4;}
Definition at line 960 of file integrate_sd_cuda.cu.
Referenced by sd_gmres_solver().
Function Documentation
void _cuda_check_error (char * file, unsigned int line)
Definition at line 1695 of file integrate_sd_cuda.cu.
References err.
real calculate_chebyshev_coefficents (real lambda_min, real lambda_max, real tol, real ** coefficents)
caclulate the chebyshev coefficents for the squareroot of the matrix It needs the largest and smalles eigenvalue which have to be computed before. Using chebyshev-gausquadrature https://en.wikipedia.org/wiki/Chebyshev%E2%80%93Gauss_quadrature.
Parameters
lambda_min : the lower boundery
lambda_max : the upper boundery of the interval
tol : the given tollerance which should be achieved
coefficents : the pointer where the data will be stored
Definition at line 1283 of file integrate_sd_cuda.cu.
References free, i, M_PI, malloc, realloc, and warnings.
Referenced by sd_compute_brownian_force_farfield().
void calculate_maxmin_eigenvalues (const matrix & mobility, real * lambda_min, real * lambda_max, real tol)
Definition at line 1140 of file integrate_sd_cuda.cu.
References cuda_safe_mem, sd_Rgemv(), matrix::size, and warnings.
Referenced by sd_compute_brownian_force_farfield().
void propagate_pos_sd_cuda (real * box_l_h, int N, real * pos_h, real * force_h, real * velo_h)
Definition at line 82 of file integrate_sd_cuda.cu.
References cublas, cuda_safe_mem, DIM, errexit(), sd_compute_displacement(), sd_radius, sd_viscosity, and time_step.
Referenced by propagate_pos_sd().
real sd_compute_brownian_force_farfield (const matrix & mobility, const real * gaussian_ff, real tol, real * brownian_force_ff)
Compute the brownian force resulting from the farfield To compute the farfield contribution of the brownian motion the squareroot of the inverse of the mobility is required. Instead of calculating it directly, its action on the vector containing the randomnumbers is computed via the chebyshev-polynomials. In the case of FF_ONLY this computes directly the displacement!
Definition at line 1379 of file integrate_sd_cuda.cu.
References calculate_chebyshev_coefficents(), calculate_maxmin_eigenvalues(), cublas, cuda_safe_mem, matrix::data, errexit(), i, isSymmetricDev(), matrix::ldd, sd_Rgemv(), matrix::size, warnings, and matrix::wavespace.
Referenced by sd_compute_displacement().
void sd_compute_displacement (const real * r_d, int N, real viscosity, real radius, const real * L_d, const real * L_h, const real * total_mobility_d, const real * force_d, real * disp_d, int * myInfo_d)
Definition at line 167 of file integrate_sd_cuda.cu.
References matrix::_free_wavespace(), matrix::col_idx, wavepart::cosines, cublas, cuda_safe_mem, matrix::data, DIM, generator, hasAnyNanDev(), matrix::is_sparse, isSymmetricDev(), matrix::ldd, matrix::ldd_short, M_PI, wavepart::matrices, wavepart::num, printMatrixDev(), printPosDev(), printVectorDev(), reprint, matrix::row_l, sd_compute_brownian_force_farfield(), sd_compute_mobility_matrix_wave_cpu(), sd_find_max(), sd_iterative_solver(), sd_random_precision, sd_random_state, sd_Rgemv(), sd_seed, sd_wavepart_addto_matrix(), wavepart::sines, matrix::size, SQR(), temperature, time_step, wavepart::vecs, warnings, and matrix::wavespace.
Referenced by propagate_pos_sd_cuda().
void sd_compute_mobility_matrix_wave_cpu (int kmax, real kmax2, matrix & mobility, real a, const real * L_h, real xi, real selfmobility, real ew_prec)
Definition at line 1583 of file integrate_sd_cuda.cu.
References wavepart::cosines, cuda_safe_mem, i, matrix::ldd_short, M_PI, wavepart::matrices, wavepart::max, wavepart::num, reprint, wavepart::sines, wavepart::vecs, and matrix::wavespace.
Referenced by sd_compute_displacement().
int sd_find_max (int * data, int length)
Definition at line 1708 of file integrate_sd_cuda.cu.
References cuda_safe_mem, and i.
Referenced by sd_compute_displacement().
int sd_gmres_solver (const matrix & A1, const matrix & A2, const real * b, real tol, real abs_tol, int maxit, real * x, real * res)
Definition at line 972 of file integrate_sd_cuda.cu.
References beta, cublas, cuda_safe_mem, i, matrix::ldd, normr(), sd_gmres_solver_exit, sd_Rgemv(), matrix::size, SQR(), and warnings.
Referenced by sd_iterative_solver().
real sd_iterative_solver (const matrix & mobility, const matrix & resistance, const real * force, real * disp, real rel_tol, real abs_tol, bool recalc)
this calls an iterative solver to solve the problem: disp * (1+resistance*mobility) = mobility_d * force_d and returnes
Parameters
disp
mobility and
resistance are square matrizes with
size <size> and ldd <((size+31)/32)*32>
force and
disp are vectors of
size <size>
Definition at line 597 of file integrate_sd_cuda.cu.
References beta, cublas, cuda_safe_mem, matrix::data, hasAnyNanDev(), matrix::is_sparse, matrix::ldd, sd_gmres_solver(), sd_Rgemv(), matrix::size, and warnings.
Referenced by sd_compute_displacement().
void sd_Rgemv (const real * factor, const matrix & A, const real * in, real * out)
Definition at line 1483 of file integrate_sd_cuda.cu.
References matrix::assert_all(), matrix::col_idx, wavepart::cosines, cublas, cuda_safe_mem, matrix::data, matrix::is_sparse, matrix::ldd, matrix::ldd_short, wavepart::matrices, wavepart::max, wavepart::num, matrix::row_l, sd_wavepart_sum(), wavepart::sines, matrix::size, wavepart::vecs, and matrix::wavespace.
Referenced by calculate_maxmin_eigenvalues(), sd_compute_brownian_force_farfield(), sd_compute_displacement(), sd_gmres_solver(), sd_iterative_solver(), and sd_test().
Variable Documentation
cublasHandle_t cublas = NULL
Definition at line 52 of file integrate_sd_cuda.cu.
Referenced by propagate_pos_sd_cuda(), sd_compute_brownian_force_farfield(), sd_compute_displacement(), sd_gmres_solver(), sd_iterative_solver(), sd_Rgemv(), and sd_test().
curandGenerator_t generator = NULL
Definition at line 53 of file integrate_sd_cuda.cu.
Referenced by sd_compute_displacement(), and sd_test().
int reprint =-1
Definition at line 54 of file integrate_sd_cuda.cu.
Referenced by sd_compute_displacement(), and sd_compute_mobility_matrix_wave_cpu().