ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: integrate_sd_cuda_kernel.cu File Reference
integrate_sd_cuda_kernel.cu File Reference
#include "config.hpp"
#include <stdio.h>
#include <assert.h>
#include "cuda_runtime.h"
#include <device_functions.h>
#include "integrate_sd_cuda.hpp"
#include "integrate_sd_cuda_device.cu"
Macros
#define mydebug(str, ...)
This computes the farfield contribution of the mobility in the case of no periodic boundary conditions. r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius mobility is the mobility matrix which will be retruned.
#define mydebug(str, ...)
This computes the farfield contribution of the mobility in the case of no periodic boundary conditions. r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius mobility is the mobility matrix which will be retruned.
#define mydebug(str, ...)
This computes the farfield contribution of the mobility in the case of no periodic boundary conditions. r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius mobility is the mobility matrix which will be retruned.
#define mydebug(str, ...)
This computes the farfield contribution of the mobility in the case of no periodic boundary conditions. r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius mobility is the mobility matrix which will be retruned.
#define myCC(pos) choleskyCache[threadIdx.x+ (pos)*numThreadsPerBlock]
#define DIST (2+1e-1)
#define DISP_MAX (1000)
Functions
__global__ void sd_compute_mobility_matrix (const real *r, int N, real self_mobility, real a, real *mobility)
__global__ void sd_compute_mobility_matrix_real_short (const real *r, int N, real self_mobility, real a, const real *L_g, real *mobility, real cutoff, real xi, real xa, real xa3)
This computes the farfield contribution of the mobility with ewald summation this version assumes that the real-space cutoff is smaller than the boxlength.
__global__ void sd_compute_mobility_sines (const real *r, int N, const real *vecs, int num, real *sines, real *cosines, int ldd)
This computes the farfield contribution of the mobility with ewald summation this kernel computes the sines and cosinus.
__global__ void sd_wavepart_sum (const real *const forces, const real *const vecs, int num, const real *const matrices_d, const real *const sines, const real *const cosines, int ldd, int N, real *sin_sum, real *cos_sum, real max)
This computes the farfield contribution of the mobility with ewald summation this kernel computes the sum in eq. (3.34) and (3.35) in the master thesis "rotne-prager based hydrodynamics" by D. Schwoerer: M^{wave} F_i cos / sin. The number of threads have to be a power of two e.g. 32, 64 or 128. forces is the input vector of form [fx_1, fy_1, fz_1, fx_2, fy_2, fz_2, ...].
__global__ void sd_wavepart_assemble (const int num, const real *const __restrict__ sines, const real *const __restrict__ cosines, const real *const __restrict__ sin_sum, const real *const __restrict__ cos_sum, const int ldd, real *__restrict__ out, const real max, const int N, const real factor)
This computes the wave space contribution of the matrix vector product of the farfield. This uses the pre computed values from the kernel sd_wavepart_sum num : number of wave vectors sines : sinus of the scalar product of position and wave vector cosines : cosines of the scalar product of position and wave vector sin_sum : precomputed sum for sinus cos_sum : precomputed sum for cosinus ldd : leading dimension of the sin_sum and cos_sum arrays out : out vector upon which the result gets added max : maximal value of which the sin_sum and cos_sum can have N : number of particles factor : the scalar factor c of the matrix product c A x.
__global__ void sd_wavepart_addto_matrix (const int num, const real *const matrices_d, const real *const sines, const real *const cosines, const int ldd, const int N, real *const mobility_d, const int mat_ldd)
Add the wavepart contribution of the mobility to the matrix num : number of wave space vectors matrices_d : pointer to the matrices of the wave space contribution in the ewald sum sines : sines of the scalar product of wave space vector and particle positions cosines : cosines of the scalar product of wave space vector and particle positions ldd : leading dimension of sines/cosines N : number of particles mobility_d : mobility matrix to which the wave space contribution is added mat_ldd : leading dimension of the mobility matrix.
__global__ void sd_compute_resistance_matrix (const real *pos, int N, real self_mobility, real a, const real *L_g, real *resistance, int *myInfo)
this computes the near field as a ResistanceMatrix pos : is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N : is the number of particles self_mobility : is 1./(6.*PI*eta*a) a : is the particle radius L_g : is the boxlength resistance : is the resistance matrix which will be retruned myInfo : contains infos about the operation: myInfo[0] : number of overlapping particles myInfo[1] : number of interacting particles (via nf) myInfo[2] : max number of interacting particles per particle
__global__ void sd_find_interacting_particles (const real *pos, const real *L_g, const int N, int *interacting, int *num_interacting, const real interaction_range)
Find particle pairs which are within a certain cutoff range pos : is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] L_g : is the boxlength N : is the number of particles interacting : list of interaction particles. First entry is the first particle close enough to particle 1. Followed by the first one close enough to the second and so on. The second interaction particle of the first is at lda_short=((N+31)/32)*32 stored. num_interacting : for each particle the number of interacting particles. interaction_range : the cutoff range for interaction. Has to be smaller than half the boxlength.
__global__ void sd_find_interacting_particles (const real *pos, const real *_L, const int N, int *interacting, int *num_interacting, const int *particle_count, const int *particle_sorted_list, const real *bucket_size_, const int *bucket_num_, const int *particle_to_bucket_list, const real interaction_range, const int total_bucket_num)
Find particle pairs which are within a certain cutoff range using buckets pos : the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] L : the boxlength N : the number of particles interacting : list of interaction particles. First entry is the first particle close enough to particle 1. Followed by the first one close enough to the second and so on. The second interaction particle of the first is at lda_short=((N+31)/32)*32 stored. num_interacting : for each particle the number of interacting particles. particle_count : the number of particles within a certain bucket particle_sorted_list : the list of the particles in the buckets bucket_size : real[3] array of the dimensions of a bucket bucket_num_ : int[3] array of the number of buckets in each direction particle_to_bucket_list : lookup table what particle is in what bucket interaction_range : the cutoff range for interaction. Has to be smaller than half the boxlength. total_bucket_num : number of buckets.
__global__ void sd_compute_resistance_matrix_sparse (const real *pos, const int N, const real self_mobility, const real a, const real *_L, real *resistance, const int *col_idx, const int *row_l, int *myInfo)
Compute the lubrication correction in the resistance formulation. pos : is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N : is the number of particles self_mobility : is 1./(6.*PI*eta*a) a : is the particle radius _L : is the boxlength resistance : is the sparse resistance matrix which will be returned col_idx : list of interacting partilces row_l : number of col_idx entries per particle myInfo : contains infos about the operation: myInfo[0] : number of overlapping particles myInfo[1] : number of interacting particles (via nf) myInfo[2] : max number of interacting particles per particle.
__global__ void sd_compute_brownian_force_nearfield (const real *r, const real *gaussian, int N, const real *L_g, real a, real self_mobility, real *brownian_force_nf)
Computing the brownian forces which arise from the nearfield contribution of the mobility matrix r : position of the particles gaussian : pointer to a sufficent amount of gaussian distributed random numbers N : number of particles L_g : size of periodic box a : hydrodynamic particle radius self_mobility : is 1./(6.*PI*eta*a) brownian_force_nf : computed brownian force.
__global__ void sd_multiply_sparse_matrix_vector (const int size, const real factor, const real *matrix, const int ldd, const int ldd_short, const int *col_idx, const int *row_l, const real *vec_in, real *vec_out)
computing the matrix vector y = c * A * x product with a square sparse matrix A and a scalar factor c size : size of the matrix and of the input and output vectors factor : factor $c$ is the given prefactor matrix : data of the sparse matrix ldd : leading dimension of the matrix ldd_short : leading dimension of col_idx col_idx : indices of the entries in the matrix row_l : number of entris per row vec_in : the input vecor $x$ vec_out : the output vector $y$
__global__ void sd_add_identity_matrix (real *matrix, int size, int lda)
this adds the identity matrix to a given matrix of ld=size matrix : pointer to the given matrix size : the size of the matrix (in the example below 3N) block : (ignored) the number of elements to process per thread if this is e.g. 3 and the matrix is 3Nx3N, than N threads have to be started
__global__ void sd_set_zero_matrix (real *matrix, int size, int ldd)
this sets a block to zero matrix : pointer to the given matrix size : the size of the matrix (in the example below 3N) ldd : the leading dimension of the matrix
__global__ void sd_set_zero (real *data, int size)
this sets a block to zero data : pointer to the given data size : the size of the data
__global__ void sd_set_value (int *data, int size, int value)
this sets a block to an given integer data : pointer to the given data size : the size of the data value : the value written to the data block
__global__ void sd_set_value (real *data, int size, real value)
this sets a block to an given real data : pointer to the given data size : the size of the data value : the value written to the data block
__global__ void sd_real_integrate_prepare (const real *r_d, real *disp_d, const real *L, real a, int N)
Checking before the actual integration whether any particles moves more than DISP_MAX and if so, reducing the displacement to DISP_MAX r_d : position of the particles disp_d : displacements of the particles L : box dimension a : particle radius N : number of particles.
__global__ void sd_real_integrate (real *r_d, const real *disp_d, const real *L, real a, int N)
if SD_AVOID_COLLISION is set avoid that particles are overlapping after the displacement, else only perform the integration step r_d : position of the particles disp_d : displacement of the particles L : box dimensions a : particle radius N : number of particles
__global__ void sd_bucket_sort (const real *pos, const real *bucketSize, const int *bucketNum, int N, int *particleCount, int *particleList, int maxParticlePerCell, int totalBucketNum, int *particleToBucketList)
sorting the particles in buckets pos : position of the particles bucketSize : dimension of bucket bucketNum : number of buckets in each direction N : number of particles particleCount : number of particles within a bucket particleList : list of the particles within a given bucket totalBucketNum : number of buckets, product of the three values of bucketNum particleToBucketList : array containg the bucket number for each particle
__global__ void sd_get_diag (int size, const real *mat_a, int lda, real *diag, real *diag_i)
This function reads the diagonal element entries of a square matrix and stores them in the vector diag and the inverse of them in diag_i size : size of the matrix mat_a : the matrix lda : leading dimension of the matrix mat_a diag : the diagonal (OUT) diag_i : the inverse of the diagonal (OUT)
__global__ void sd_nrm1 (const int size, const real *const vec, real *res)
computing the 1 norm of a given vector size : size of the vector vec : data of the vector res : the 1 norm (OUT)
__global__ void sd_nrm_inf (const int size, const int *const vec, int *res)
computing the 1 norm of a given vector size : size of the vector vec : data of the vector res : the 1 norm (OUT)
Macro Definition Documentation
#define DISP_MAX (1000)
Definition at line 1650 of file integrate_sd_cuda_kernel.cu.
Referenced by sd_real_integrate_prepare().
#define DIST (2+1e-1)
Definition at line 1649 of file integrate_sd_cuda_kernel.cu.
Referenced by sd_real_integrate().
#define myCC (pos) choleskyCache[threadIdx.x+ (pos)*numThreadsPerBlock]
Referenced by sd_compute_brownian_force_nearfield().
#define mydebug (str, ...)
This computes the farfield contribution of the mobility in the case of no periodic boundary conditions. r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius mobility is the mobility matrix which will be retruned.
This computes the farfield contribution of the mobility with ewald summation this kernel computes the sines and cosinus. r : the vector of positions [x_1, y_1, z_1, x_2, y_2, z_2, ...] N : the number of particles vecs * : a pointer to the k-vectors num : number of k-vectors sines : the values for sin(pos_i k_j) cosines : the values for cos(pos_i k_j) ldd : the leading dimension of the sines and cosines array.
This computes the farfield contribution of the mobility with ewald summation this version assumes that the real-space cutoff is smaller than the boxlength r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius L_g is the boxlength mobility is the mobility matrix which will be retruned cutoff the realspace cutoff distance xi the splitting parameter as defined by Beenakker 1986 xa = xi * a xa3 = xa * xa * xa.
Definition at line 649 of file integrate_sd_cuda_kernel.cu.
Referenced by sd_compute_mobility_matrix(), sd_compute_mobility_matrix_real_short(), sd_compute_mobility_sines(), sd_compute_resistance_matrix(), and sd_compute_resistance_matrix_sparse().
#define mydebug (str, ...)
This computes the farfield contribution of the mobility in the case of no periodic boundary conditions. r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius mobility is the mobility matrix which will be retruned.
This computes the farfield contribution of the mobility with ewald summation this kernel computes the sines and cosinus. r : the vector of positions [x_1, y_1, z_1, x_2, y_2, z_2, ...] N : the number of particles vecs * : a pointer to the k-vectors num : number of k-vectors sines : the values for sin(pos_i k_j) cosines : the values for cos(pos_i k_j) ldd : the leading dimension of the sines and cosines array.
This computes the farfield contribution of the mobility with ewald summation this version assumes that the real-space cutoff is smaller than the boxlength r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius L_g is the boxlength mobility is the mobility matrix which will be retruned cutoff the realspace cutoff distance xi the splitting parameter as defined by Beenakker 1986 xa = xi * a xa3 = xa * xa * xa.
Definition at line 649 of file integrate_sd_cuda_kernel.cu.
#define mydebug (str, ...)
This computes the farfield contribution of the mobility in the case of no periodic boundary conditions. r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius mobility is the mobility matrix which will be retruned.
This computes the farfield contribution of the mobility with ewald summation this kernel computes the sines and cosinus. r : the vector of positions [x_1, y_1, z_1, x_2, y_2, z_2, ...] N : the number of particles vecs * : a pointer to the k-vectors num : number of k-vectors sines : the values for sin(pos_i k_j) cosines : the values for cos(pos_i k_j) ldd : the leading dimension of the sines and cosines array.
This computes the farfield contribution of the mobility with ewald summation this version assumes that the real-space cutoff is smaller than the boxlength r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius L_g is the boxlength mobility is the mobility matrix which will be retruned cutoff the realspace cutoff distance xi the splitting parameter as defined by Beenakker 1986 xa = xi * a xa3 = xa * xa * xa.
Definition at line 649 of file integrate_sd_cuda_kernel.cu.
#define mydebug (str, ...)
This computes the farfield contribution of the mobility in the case of no periodic boundary conditions. r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius mobility is the mobility matrix which will be retruned.
This computes the farfield contribution of the mobility with ewald summation this kernel computes the sines and cosinus. r : the vector of positions [x_1, y_1, z_1, x_2, y_2, z_2, ...] N : the number of particles vecs * : a pointer to the k-vectors num : number of k-vectors sines : the values for sin(pos_i k_j) cosines : the values for cos(pos_i k_j) ldd : the leading dimension of the sines and cosines array.
This computes the farfield contribution of the mobility with ewald summation this version assumes that the real-space cutoff is smaller than the boxlength r is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N is the number of particles self_mobility is 1./(6.*PI*eta*a) a is the particle radius L_g is the boxlength mobility is the mobility matrix which will be retruned cutoff the realspace cutoff distance xi the splitting parameter as defined by Beenakker 1986 xa = xi * a xa3 = xa * xa * xa.
Definition at line 649 of file integrate_sd_cuda_kernel.cu.
Function Documentation
__global__ void sd_add_identity_matrix (real * matrix, int size, int lda)
this adds the identity matrix to a given matrix of ld=size matrix : pointer to the given matrix size : the size of the matrix (in the example below 3N) block : (ignored) the number of elements to process per thread if this is e.g. 3 and the matrix is 3Nx3N, than N threads have to be started
adds to each of the diagonal elemnts of the size*size matrix
Definition at line 1591 of file integrate_sd_cuda_kernel.cu.
References i.
__global__ void sd_bucket_sort (const real * pos, const real * bucketSize, const int * bucketNum, int N, int * particleCount, int * particleList, int maxParticlePerCell, int totalBucketNum, int * particleToBucketList)
sorting the particles in buckets pos : position of the particles bucketSize : dimension of bucket bucketNum : number of buckets in each direction N : number of particles particleCount : number of particles within a bucket particleList : list of the particles within a given bucket totalBucketNum : number of buckets, product of the three values of bucketNum particleToBucketList : array containg the bucket number for each particle
Definition at line 1769 of file integrate_sd_cuda_kernel.cu.
References atomicAdd(), and i.
__global__ void sd_compute_brownian_force_nearfield (const real * r, const real * gaussian, int N, const real * L_g, real a, real self_mobility, real * brownian_force_nf)
Computing the brownian forces which arise from the nearfield contribution of the mobility matrix r : position of the particles gaussian : pointer to a sufficent amount of gaussian distributed random numbers N : number of particles L_g : size of periodic box a : hydrodynamic particle radius self_mobility : is 1./(6.*PI*eta*a) brownian_force_nf : computed brownian force.
Definition at line 1314 of file integrate_sd_cuda_kernel.cu.
References atomicAdd(), DIM, i, isnan, myCC, and SQR().
__global__ void sd_compute_mobility_matrix (const real * r, int N, real self_mobility, real a, real * mobility)
Definition at line 48 of file integrate_sd_cuda_kernel.cu.
References DIM, i, and mydebug.
__global__ void sd_compute_mobility_matrix_real_short (const real * r, int N, real self_mobility, real a, const real * L_g, real * mobility, real cutoff, real xi, real xa, real xa3)
This computes the farfield contribution of the mobility with ewald summation this version assumes that the real-space cutoff is smaller than the boxlength.
Definition at line 183 of file integrate_sd_cuda_kernel.cu.
References DIM, i, and mydebug.
__global__ void sd_compute_mobility_sines (const real * r, int N, const real * vecs, int num, real * sines, real * cosines, int ldd)
This computes the farfield contribution of the mobility with ewald summation this kernel computes the sines and cosinus.
Definition at line 317 of file integrate_sd_cuda_kernel.cu.
References DIM, i, and mydebug.
__global__ void sd_compute_resistance_matrix (const real * pos, int N, real self_mobility, real a, const real * L_g, real * resistance, int * myInfo)
this computes the near field as a ResistanceMatrix pos : is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N : is the number of particles self_mobility : is 1./(6.*PI*eta*a) a : is the particle radius L_g : is the boxlength resistance : is the resistance matrix which will be retruned myInfo : contains infos about the operation: myInfo[0] : number of overlapping particles myInfo[1] : number of interacting particles (via nf) myInfo[2] : max number of interacting particles per particle
Definition at line 662 of file integrate_sd_cuda_kernel.cu.
References atomicAdd(), DIM, i, and mydebug.
__global__ void sd_compute_resistance_matrix_sparse (const real * pos, const int N, const real self_mobility, const real a, const real * _L, real * resistance, const int * col_idx, const int * row_l, int * myInfo)
Compute the lubrication correction in the resistance formulation. pos : is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] N : is the number of particles self_mobility : is 1./(6.*PI*eta*a) a : is the particle radius _L : is the boxlength resistance : is the sparse resistance matrix which will be returned col_idx : list of interacting partilces row_l : number of col_idx entries per particle myInfo : contains infos about the operation: myInfo[0] : number of overlapping particles myInfo[1] : number of interacting particles (via nf) myInfo[2] : max number of interacting particles per particle.
Definition at line 1103 of file integrate_sd_cuda_kernel.cu.
References atomicAdd(), DIM, i, and mydebug.
__global__ void sd_find_interacting_particles (const real * pos, const real * L_g, const int N, int * interacting, int * num_interacting, const real interaction_range)
Find particle pairs which are within a certain cutoff range pos : is the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] L_g : is the boxlength N : is the number of particles interacting : list of interaction particles. First entry is the first particle close enough to particle 1. Followed by the first one close enough to the second and so on. The second interaction particle of the first is at lda_short=((N+31)/32)*32 stored. num_interacting : for each particle the number of interacting particles. interaction_range : the cutoff range for interaction. Has to be smaller than half the boxlength.
Definition at line 859 of file integrate_sd_cuda_kernel.cu.
References i, and SQR().
__global__ void sd_find_interacting_particles (const real * pos, const real * _L, const int N, int * interacting, int * num_interacting, const int * particle_count, const int * particle_sorted_list, const real * bucket_size_, const int * bucket_num_, const int * particle_to_bucket_list, const real interaction_range, const int total_bucket_num)
Find particle pairs which are within a certain cutoff range using buckets pos : the vector of [x_1, y_1, z_1, x_2, y_2, z_2, ...] L : the boxlength N : the number of particles interacting : list of interaction particles. First entry is the first particle close enough to particle 1. Followed by the first one close enough to the second and so on. The second interaction particle of the first is at lda_short=((N+31)/32)*32 stored. num_interacting : for each particle the number of interacting particles. particle_count : the number of particles within a certain bucket particle_sorted_list : the list of the particles in the buckets bucket_size : real[3] array of the dimensions of a bucket bucket_num_ : int[3] array of the number of buckets in each direction particle_to_bucket_list : lookup table what particle is in what bucket interaction_range : the cutoff range for interaction. Has to be smaller than half the boxlength. total_bucket_num : number of buckets.
Definition at line 926 of file integrate_sd_cuda_kernel.cu.
References i, and SQR().
__global__ void sd_get_diag (int size, const real * mat_a, int lda, real * diag, real * diag_i)
This function reads the diagonal element entries of a square matrix and stores them in the vector diag and the inverse of them in diag_i size : size of the matrix mat_a : the matrix lda : leading dimension of the matrix mat_a diag : the diagonal (OUT) diag_i : the inverse of the diagonal (OUT)
Definition at line 1831 of file integrate_sd_cuda_kernel.cu.
__global__ void sd_multiply_sparse_matrix_vector (const int size, const real factor, const real * matrix, const int ldd, const int ldd_short, const int * col_idx, const int * row_l, const real * vec_in, real * vec_out)
computing the matrix vector y = c * A * x product with a square sparse matrix A and a scalar factor c size : size of the matrix and of the input and output vectors factor : factor $c$ is the given prefactor matrix : data of the sparse matrix ldd : leading dimension of the matrix ldd_short : leading dimension of col_idx col_idx : indices of the entries in the matrix row_l : number of entris per row vec_in : the input vecor $x$ vec_out : the output vector $y$
Definition at line 1566 of file integrate_sd_cuda_kernel.cu.
References i, and read_without_caching().
__global__ void sd_nrm1 (const int size, const real *const vec, real * res)
computing the 1 norm of a given vector size : size of the vector vec : data of the vector res : the 1 norm (OUT)
Definition at line 1845 of file integrate_sd_cuda_kernel.cu.
References i, and reduce_sum().
__global__ void sd_nrm_inf (const int size, const int *const vec, int * res)
computing the 1 norm of a given vector size : size of the vector vec : data of the vector res : the 1 norm (OUT)
computing the inf norm of a given vector (or in other words the largest value) if more than one block is used, this kernel does not perform the final reduction size : size of the vector vec : data of the vector res : the 1 norm (OUT)
Definition at line 1864 of file integrate_sd_cuda_kernel.cu.
References i, and reduce_max().
__global__ void sd_real_integrate (real * r_d, const real * disp_d, const real * L, real a, int N)
if SD_AVOID_COLLISION is set avoid that particles are overlapping after the displacement, else only perform the integration step r_d : position of the particles disp_d : displacement of the particles L : box dimensions a : particle radius N : number of particles
Definition at line 1682 of file integrate_sd_cuda_kernel.cu.
References beta, DIM, DIST, and i.
__global__ void sd_real_integrate_prepare (const real * r_d, real * disp_d, const real * L, real a, int N)
Checking before the actual integration whether any particles moves more than DISP_MAX and if so, reducing the displacement to DISP_MAX r_d : position of the particles disp_d : displacements of the particles L : box dimension a : particle radius N : number of particles.
Definition at line 1658 of file integrate_sd_cuda_kernel.cu.
References DISP_MAX, and i.
__global__ void sd_set_value (int * data, int size, int value)
this sets a block to an given integer data : pointer to the given data size : the size of the data value : the value written to the data block
Definition at line 1628 of file integrate_sd_cuda_kernel.cu.
References i.
__global__ void sd_set_value (real * data, int size, real value)
this sets a block to an given real data : pointer to the given data size : the size of the data value : the value written to the data block
Definition at line 1639 of file integrate_sd_cuda_kernel.cu.
References i.
__global__ void sd_set_zero (real * data, int size)
this sets a block to zero data : pointer to the given data size : the size of the data
Definition at line 1617 of file integrate_sd_cuda_kernel.cu.
References i.
__global__ void sd_set_zero_matrix (real * matrix, int size, int ldd)
this sets a block to zero matrix : pointer to the given matrix size : the size of the matrix (in the example below 3N) ldd : the leading dimension of the matrix
Definition at line 1604 of file integrate_sd_cuda_kernel.cu.
References i.
__global__ void sd_wavepart_addto_matrix (const int num, const real *const matrices_d, const real *const sines, const real *const cosines, const int ldd, const int N, real *const mobility_d, const int mat_ldd)
Add the wavepart contribution of the mobility to the matrix num : number of wave space vectors matrices_d : pointer to the matrices of the wave space contribution in the ewald sum sines : sines of the scalar product of wave space vector and particle positions cosines : cosines of the scalar product of wave space vector and particle positions ldd : leading dimension of sines/cosines N : number of particles mobility_d : mobility matrix to which the wave space contribution is added mat_ldd : leading dimension of the mobility matrix.
Add the wavepart contribution of the mobility to the matrix.
Definition at line 596 of file integrate_sd_cuda_kernel.cu.
References i.
Referenced by sd_compute_displacement().
__global__ void sd_wavepart_assemble (const int num, const real *const __restrict__ sines, const real *const __restrict__ cosines, const real *const __restrict__ sin_sum, const real *const __restrict__ cos_sum, const int ldd, real *__restrict__ out, const real max, const int N, const real factor)
This computes the wave space contribution of the matrix vector product of the farfield. This uses the pre computed values from the kernel sd_wavepart_sum num : number of wave vectors sines : sinus of the scalar product of position and wave vector cosines : cosines of the scalar product of position and wave vector sin_sum : precomputed sum for sinus cos_sum : precomputed sum for cosinus ldd : leading dimension of the sin_sum and cos_sum arrays out : out vector upon which the result gets added max : maximal value of which the sin_sum and cos_sum can have N : number of particles factor : the scalar factor c of the matrix product c A x.
Definition at line 484 of file integrate_sd_cuda_kernel.cu.
References DIM, and i.
__global__ void sd_wavepart_sum (const real *const forces, const real *const vecs, int num, const real *const matrices_d, const real *const sines, const real *const cosines, int ldd, int N, real * sin_sum, real * cos_sum, real max)
This computes the farfield contribution of the mobility with ewald summation this kernel computes the sum in eq. (3.34) and (3.35) in the master thesis "rotne-prager based hydrodynamics" by D. Schwoerer: M^{wave} F_i cos / sin. The number of threads have to be a power of two e.g. 32, 64 or 128. forces is the input vector of form [fx_1, fy_1, fz_1, fx_2, fy_2, fz_2, ...].
This computes the farfield contribution of the mobility with ewald summation this kernel computes the sines and cosinus.
Definition at line 370 of file integrate_sd_cuda_kernel.cu.
References reduce_sum().
Referenced by sd_Rgemv().