ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: integrate_sd_tcl.cpp File Reference
integrate_sd_tcl.cpp File Reference
#include "integrate_sd.hpp"
#include "npt.hpp"
#include "interaction_data.hpp"
#include "lb.hpp"
#include "pressure_tcl.hpp"
#include "communication.hpp"
#include "parser.hpp"
#include "statistics_correlation.hpp"
#include "global.hpp"
Functions
int tclcommand_integrate_sd_print_usage (Tcl_Interp *interp)
Hand over integrate usage information to tcl interpreter.
int tclcommand_sd_set_particle_apart_print_usage (Tcl_Interp *interp)
int tclcommand_integrate_sd_print_status (Tcl_Interp *interp)
Hand over integrate status information to tcl interpreter.
int tclcommand_sd_set_particles_apart (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure to set particles to an non overlapping state
int tclcommand_sd_test (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure to test some internal stuff in sd integrater
int tclcommand_integrate_sd (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure for integrator steering.
int tclcallback_sd_radius (Tcl_Interp *interp, void *_data)
Callback for the sd particle radius (0.0 < sd_radius)
int tclcallback_sd_viscosity (Tcl_Interp *interp, void *_data)
Callback for the sd viscosity (0.0 < sd_viscosity)
int tclcallback_sd_seed (Tcl_Interp *interp, void *_data)
Callback for the sd random seed.
int tclcallback_sd_random_state (Tcl_Interp *interp, void *_data)
Callback for the sd random state.
int tclcallback_sd_random_precision (Tcl_Interp *interp, void *_data)
Callback for the sd random precision (0.0 < sd_random_precision)
Function Documentation
int tclcallback_sd_radius (Tcl_Interp * interp, void * _data)
Callback for the sd particle radius (0.0 < sd_radius)
Definition at line 176 of file integrate_sd_tcl.cpp.
References FIELD_SD_RADIUS, mpi_bcast_parameter(), and sd_radius.
Referenced by tcl_register_global_variables().
int tclcallback_sd_random_precision (Tcl_Interp * interp, void * _data)
Callback for the sd random precision (0.0 < sd_random_precision)
Definition at line 218 of file integrate_sd_tcl.cpp.
References FIELD_SD_RANDOM_PRECISION, mpi_bcast_parameter(), and sd_random_precision.
Referenced by tcl_register_global_variables().
int tclcallback_sd_random_state (Tcl_Interp * interp, void * _data)
Callback for the sd random state.
Definition at line 209 of file integrate_sd_tcl.cpp.
References FIELD_SD_RANDOM_STATE, mpi_bcast_parameter(), and sd_random_state.
Referenced by tcl_register_global_variables().
int tclcallback_sd_seed (Tcl_Interp * interp, void * _data)
Callback for the sd random seed.
Definition at line 200 of file integrate_sd_tcl.cpp.
References FIELD_SD_SEED, mpi_bcast_parameter(), and sd_seed.
Referenced by tcl_register_global_variables().
int tclcallback_sd_viscosity (Tcl_Interp * interp, void * _data)
Callback for the sd viscosity (0.0 < sd_viscosity)
Definition at line 188 of file integrate_sd_tcl.cpp.
References FIELD_SD_VISCOSITY, mpi_bcast_parameter(), and sd_viscosity.
Referenced by tcl_register_global_variables().
int tclcommand_integrate_sd (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure for integrator steering.
For documentation, see tclcommand_integrate
Definition at line 122 of file integrate_sd_tcl.cpp.
References ARG1_IS_S, ARG_IS_I, autoupdate_correlations(), autoupdate_observables(), correlations_autoupdate, gather_runtime_errors(), i, INTEG_TRACE, integrate_sd(), observables_autoupdate, tclcommand_integrate_sd_print_status(), tclcommand_integrate_sd_print_usage(), and this_node.
Referenced by tcl_register_commands().
int tclcommand_integrate_sd_print_status (Tcl_Interp * interp)
Hand over integrate status information to tcl interpreter.
Definition at line 62 of file integrate_sd_tcl.cpp.
Referenced by tclcommand_integrate_sd().
int tclcommand_integrate_sd_print_usage (Tcl_Interp * interp)
Hand over integrate usage information to tcl interpreter.
Definition at line 39 of file integrate_sd_tcl.cpp.
Referenced by tclcommand_integrate_sd().
int tclcommand_sd_set_particle_apart_print_usage (Tcl_Interp * interp)
Definition at line 51 of file integrate_sd_tcl.cpp.
Referenced by tclcommand_sd_set_particles_apart(), and tclcommand_sd_test().
int tclcommand_sd_set_particles_apart (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure to set particles to an non overlapping state
Definition at line 68 of file integrate_sd_tcl.cpp.
References sd_radius, sd_set_particles_apart(), and tclcommand_sd_set_particle_apart_print_usage().
Referenced by tcl_register_commands().
int tclcommand_sd_test (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure to test some internal stuff in sd integrater
Definition at line 102 of file integrate_sd_tcl.cpp.
References ARG_IS_I, sd_test(), and tclcommand_sd_set_particle_apart_print_usage().
Referenced by tcl_register_commands().