ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: integrate_sd_cuda_debug.hpp File Reference
integrate_sd_cuda_debug.hpp File Reference
#include "config.hpp"
#include <sys/time.h>
#include <assert.h>
#include <iostream>
#include <iomanip>
#include "integrate_sd_cuda.hpp"
Data Structures
class myTimer
Functions
template<typename T >
void printMatrixDev (T *data, int m, int n, const char *msg)
template<typename T >
void printMatrixDev (T *data, int m, int n)
void printMatrixDev (const matrix &mat)
template<typename T >
void printMatrixHost (T *data, int m, int n, const char *msg)
template<typename T >
void printDistances (T *r_h, T, int N, T min, T max)
template<typename T >
void printDistances (T *r_h, T, int N)
void printPosDev (real *data, int m, const char *msg)
void printVectorDev (const real *data, const int m)
void printVectorDev (const real *data, const int m, const char *msg)
void printVectorHost (const real *data, const int m)
void printVectorHost (const real *data, const int m, const char *msg)
bool hasAnyNanDev (const real *data, int length)
bool isSymmetricDev (const matrix &mat)
bool isSymmetricDev (const real *data, int lda, int size)
real getAbsMax (const real *data, int length)
real getAbsMaxDev (const real *data_d, int length)
int countMinusDev (const real *data_d, int length)
template<typename T >
T mymin (T a, T b)
Function Documentation
int countMinusDev (const real * data_d, int length)
Definition at line 237 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem, and i.
real getAbsMax (const real * data, int length)
Definition at line 219 of file integrate_sd_cuda_debug.cu.
References i.
Referenced by getAbsMaxDev().
real getAbsMaxDev (const real * data_d, int length)
Definition at line 230 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem, and getAbsMax().
bool hasAnyNanDev (const real * data, int length)
Definition at line 248 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem, and isnan.
Referenced by sd_compute_displacement(), and sd_iterative_solver().
bool isSymmetricDev (const matrix & mat)
Definition at line 259 of file integrate_sd_cuda_debug.cu.
References matrix::data, isSymmetricDev(), matrix::ldd, and matrix::size.
Referenced by isSymmetricDev(), sd_compute_brownian_force_farfield(), and sd_compute_displacement().
bool isSymmetricDev (const real * data, int lda, int size)
Definition at line 263 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem, and i.
template<typename T > T mymin (T a, T b)
Definition at line 61 of file integrate_sd_cuda_debug.hpp.
Referenced by printMatrixHost().
template<typename T > void printDistances (T * r_h, T L, int N, T min, T max)
Definition at line 117 of file integrate_sd_cuda_debug.hpp.
References DIM, and i.
Referenced by printDistances().
template<typename T > void printDistances (T * r_h, T L, int N)
Definition at line 136 of file integrate_sd_cuda_debug.hpp.
References printDistances().
template<typename T > void printMatrixDev (T * data, int m, int n, const char * msg)
Definition at line 111 of file integrate_sd_cuda_debug.hpp.
template<typename T > void printMatrixDev (T * data, int m, int n)
Definition at line 98 of file integrate_sd_cuda_debug.hpp.
References printMatrixHost().
void printMatrixDev (const matrix & mat)
Definition at line 281 of file integrate_sd_cuda_debug.cu.
References matrix::data, matrix::ldd, printMatrixDev(), matrix::printWavespace(), and matrix::size.
Referenced by matrix::print(), printMatrixDev(), and sd_compute_displacement().
template<typename T > void printMatrixHost (T * data, int m, int n, const char * msg)
Definition at line 66 of file integrate_sd_cuda_debug.hpp.
References i, and mymin().
Referenced by printMatrixDev().
void printPosDev (real * data, int m, const char * msg)
Definition at line 145 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem.
Referenced by sd_compute_displacement().
void printVectorDev (const real * data, const int m)
Definition at line 99 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem.
void printVectorDev (const real * data, const int m, const char * msg)
Definition at line 95 of file integrate_sd_cuda_debug.cu.
References printVectorDev().
Referenced by wavepart::print(), printVectorDev(), and sd_compute_displacement().
void printVectorHost (const real * data, const int m)
Definition at line 138 of file integrate_sd_cuda_debug.cu.
void printVectorHost (const real * data, const int m, const char * msg)
Definition at line 133 of file integrate_sd_cuda_debug.cu.
References printVectorHost().
Referenced by printVectorHost().