ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: integrate_sd_cuda_debug.cu File Reference
integrate_sd_cuda_debug.cu File Reference
#include "config.hpp"
#include <iostream>
#include <iomanip>
#include <stdio.h>
#include <cublas_v2.h>
#include <curand.h>
#include "integrate_sd_cuda.hpp"
#include "integrate_sd_cuda_debug.hpp"
#include "integrate_sd_cuda_kernel.hpp"
#include "cuda_utils.hpp"
Functions
int sd_test (int size, int type)
void printVectorDev (const real *data, const int m, const char *msg)
void printVectorDev (const real *data, const int m)
void printVectorHost (const real *host, const int m, const char *msg)
void printVectorHost (const real *host, const int m)
void printPosDev (real *data, int m, const char *msg)
void _cudaCheckError (const char *msg, const char *file, const int line)
real getAbsMax (const real *data, int length)
real getAbsMaxDev (const real *data_d, int length)
int countMinusDev (const real *data_d, int length)
bool hasAnyNanDev (const real *data, int length)
bool isSymmetricDev (const matrix &mat)
bool isSymmetricDev (const real *data, int lda, int size)
void printMatrixDev (const matrix &mat)
Function Documentation
void _cudaCheckError (const char * msg, const char * file, const int line)
Definition at line 172 of file integrate_sd_cuda_debug.cu.
References err, and errexit().
int countMinusDev (const real * data_d, int length)
Definition at line 237 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem, and i.
real getAbsMax (const real * data, int length)
Definition at line 219 of file integrate_sd_cuda_debug.cu.
References i.
Referenced by getAbsMaxDev().
real getAbsMaxDev (const real * data_d, int length)
Definition at line 230 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem, and getAbsMax().
bool hasAnyNanDev (const real * data, int length)
Definition at line 248 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem, and isnan.
Referenced by sd_compute_displacement(), and sd_iterative_solver().
bool isSymmetricDev (const matrix & mat)
Definition at line 259 of file integrate_sd_cuda_debug.cu.
References matrix::data, isSymmetricDev(), matrix::ldd, and matrix::size.
Referenced by isSymmetricDev(), sd_compute_brownian_force_farfield(), and sd_compute_displacement().
bool isSymmetricDev (const real * data, int lda, int size)
Definition at line 263 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem, and i.
void printMatrixDev (const matrix & mat)
Definition at line 281 of file integrate_sd_cuda_debug.cu.
References matrix::data, matrix::ldd, printMatrixDev(), matrix::printWavespace(), and matrix::size.
Referenced by matrix::print(), printMatrixDev(), and sd_compute_displacement().
void printPosDev (real * data, int m, const char * msg)
Definition at line 145 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem.
Referenced by sd_compute_displacement().
void printVectorDev (const real * data, const int m, const char * msg)
Definition at line 95 of file integrate_sd_cuda_debug.cu.
References printVectorDev().
Referenced by wavepart::print(), printVectorDev(), and sd_compute_displacement().
void printVectorDev (const real * data, const int m)
Definition at line 99 of file integrate_sd_cuda_debug.cu.
References cuda_safe_mem.
void printVectorHost (const real * host, const int m, const char * msg)
Definition at line 133 of file integrate_sd_cuda_debug.cu.
References printVectorHost().
Referenced by printVectorHost().
void printVectorHost (const real * host, const int m)
Definition at line 138 of file integrate_sd_cuda_debug.cu.
int sd_test (int size, int type)
Definition at line 42 of file integrate_sd_cuda_debug.cu.
References matrix::col_idx, cublas, cuda_safe_mem, matrix::data, generator, i, matrix::is_sparse, matrix::ldd, matrix::row_l, sd_Rgemv(), and matrix::size.
Referenced by tclcommand_sd_test().