ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: integrate.hpp File Reference
integrate.hpp File Reference
Molecular dynamics integrator.
Macros
#define INTEG_METHOD_NPT_ISO 0
#define INTEG_METHOD_NVT 1
#define INTEG_METHOD_STEEPEST_DESCENT 2
Functions
int python_integrate (int n_steps, bool recalc_forces, bool reuse_forces)
void integrate_set_nvt ()
int integrate_set_npt_isotropic (double ext_pressure, double piston, int xdir, int ydir, int zdir, bool cubic_box)
Parse integrate npt_isotropic command.
Exported Functions
void integrator_sanity_checks ()
check sanity of integrator params
void integrator_npt_sanity_checks ()
check sanity of npt params
void integrate_ensemble_init ()
Initialize the used thermodynamic Ensemble (NVT or NPT)
void integrate_vv (int n_steps, int reuse_forces)
integrate with velocity verlet integrator.
void rescale_velocities (double scale)
function that rescales all velocities on one node according to a new time step.
Variables
Exported Variables
int integ_switch
Switch determining which Integrator to use.
int n_verlet_updates
incremented if a Verlet update is done, aka particle resorting.
double time_step
Time step for the integration.
double time_step_half
double time_step_squared
double time_step_squared_half
double smaller_time_step
Other time step in the multiple time step scheme.
int current_time_step_is_small
Flag to determine what kind of time step we're calculating.
int mts_index
Smaller integration time step index.
int mts_max
Number of MTS time steps.
double scal_store [3]
Store box dimensions for small timesteps.
double virial_store [3]
Flag to compute virial of all particles.
double configtemp [2]
Store configurational temperature terms (numerator/denominator)
double old_time_step
Old time step needed for rescaling of forces.
double sim_time
Actual simulation time (only on MASTER NODE).
double max_cut
Maximal interaction cutoff.
double skin
Verlet list skin.
bool skin_set
True iff the user has changed the skin setting.
int resort_particles
If non-zero, the particle data will be resorted before the next integration.
int recalc_forces
If non-zero, the forces will be recalculated before the next integration.
double verlet_reuse
Average number of integration steps the verlet list has been re used.
Detailed Description
Molecular dynamics integrator.
For more information see integrate.c.
Definition in file integrate.hpp.
Macro Definition Documentation
#define INTEG_METHOD_NPT_ISO 0
Definition at line 29 of file integrate.hpp.
Referenced by add_bonded_force(), add_non_bonded_pair_force(), calc_long_range_forces(), finalize_p_inst_npt(), iccp3m_sanity_check(), init_forces(), init_forces_iccp3m(), integrate_ensemble_init(), integrate_sd(), integrate_set_npt_isotropic(), integrate_vv(), integrator_npt_sanity_checks(), observable_compute_stress_tensor(), on_parameter_change(), propagate_pos(), propagate_press_box_pos_and_rescale_npt(), propagate_vel(), rescale_forces_propagate_vel(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_integrate_print_status(), tclcommand_integrate_set_npt_isotropic(), update_pressure(), and update_stress_tensor().
#define INTEG_METHOD_NVT 1
Definition at line 30 of file integrate.hpp.
Referenced by integrate_set_npt_isotropic(), integrate_set_nvt(), tclcommand_integrate_print_status(), tclcommand_integrate_set_npt_isotropic(), and tclcommand_integrate_set_nvt().
#define INTEG_METHOD_STEEPEST_DESCENT 2
Definition at line 31 of file integrate.hpp.
Referenced by integrate_vv(), and minimize_energy().
Function Documentation
void integrate_ensemble_init ()
Initialize the used thermodynamic Ensemble (NVT or NPT)
Definition at line 203 of file core/integrate.cpp.
References box_l, configtemp, nptiso_struct::dimension, errexit(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso_struct::inv_piston, nptiso_struct::non_const_dim, nptiso, nptiso_struct::p_inst, nptiso_struct::p_inst_av, nptiso_struct::p_vel, nptiso_struct::p_vir, nptiso_struct::piston, recalc_forces, this_node, and nptiso_struct::volume.
Referenced by on_integration_start().
int integrate_set_npt_isotropic (double ext_pressure, double piston, int xdir, int ydir, int zdir, bool cubic_box)
Parse integrate npt_isotropic command.
Definition at line 1182 of file core/integrate.cpp.
References Coulomb_parameters::bjerrum, coulomb, nptiso_struct::cubic_box, Coulomb_parameters::Dbjerrum, nptiso_struct::dimension, ES_ERROR, ES_OK, FIELD_INTEG_SWITCH, nptiso_struct::geometry, INTEG_METHOD_NPT_ISO, INTEG_METHOD_NVT, integ_switch, mpi_bcast_nptiso_geom(), mpi_bcast_parameter(), nptiso_struct::non_const_dim, NPTGEOM_XDIR, NPTGEOM_YDIR, NPTGEOM_ZDIR, nptiso, nptiso_struct::p_ext, nptiso_struct::piston, and runtimeError.
void integrate_set_nvt ()
Definition at line 1175 of file core/integrate.cpp.
References FIELD_INTEG_SWITCH, INTEG_METHOD_NVT, integ_switch, and mpi_bcast_parameter().
void integrate_vv (int n_steps, int reuse_forces)
integrate with velocity verlet integrator.
Parameters
n_steps number of steps to integrate.
reuse_forces if nonzero, blindly trust the forces still stored with the particles for the first time step.
Correct those particle positions that participate in a rigid/constrained bond
Definition at line 231 of file core/integrate.cpp.
References cell_structure, cells_update_ghosts(), check_runtime_errors(), CellStructure::collect_ghost_force_comm, COLLISION_DETECTION, comm_cart, convert_initial_torques(), convert_torques_propagate_omega(), correct_pos_shake(), correct_vel_shake(), coulomb, COULOMB_MAGGS, current_time_step_is_small, ek_initialized, ek_integrate(), force_calc(), ghmc_close(), ghmc_init(), ghmc_mc(), ghmc_momentum_update(), ghmc_nmd, ghost_communicator(), handle_collisions(), IBM_ForcesIntoFluid_CPU(), IBM_ForcesIntoFluid_GPU(), IBM_InitVolumeConservation(), IBM_UpdateParticlePositions(), INTEG_METHOD_NPT_ISO, INTEG_METHOD_STEEPEST_DESCENT, integ_switch, INTEG_TRACE, integrate_reaction(), nptiso_struct::invalidate_p_vel, lattice_boltzmann_update(), lattice_boltzmann_update_gpu(), LATTICE_LB, LATTICE_LB_GPU, lattice_switch, maggs_propagate_B_field(), Coulomb_parameters::method, MPI_Bcast(), MPI_DOUBLE, mpi_thermalize_cpu(), mts_index, mts_max, n_verlet_updates, nemd_method, NEMD_METHOD_OFF, nptiso, on_integration_start(), nptiso_struct::p_diff, nptiso_struct::p_inst, nptiso_struct::p_inst_av, nptiso_struct::p_vir, propagate_pos(), propagate_vel(), propagate_vel_pos(), recalc_forces, rescale_forces(), rescale_forces_propagate_vel(), save_old_pos(), sim_time, skin, skin2, smaller_time_step, SQR(), steepest_descent_step(), temperature, THERMO_BD, thermo_cool_down(), THERMO_CPU, THERMO_GHMC, thermo_heat_up(), THERMO_SD, thermo_switch, this_node, time_step, transfer_momentum, transfer_momentum_gpu, CellStructure::update_ghost_pos_comm, update_mol_vel(), verlet_reuse, virial_store, nptiso_struct::volume, and warnings.
Referenced by minimize_energy(), mpi_integrate(), and mpi_integrate_slave().
void integrator_npt_sanity_checks ()
check sanity of npt params
Definition at line 158 of file core/integrate.cpp.
References coulomb, COULOMB_DH, COULOMB_NONE, COULOMB_P3M, COULOMB_RF, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, INTEG_METHOD_NPT_ISO, integ_switch, Coulomb_parameters::method, nptiso, nptiso_struct::piston, and runtimeError.
Referenced by on_integration_start().
void integrator_sanity_checks ()
check sanity of integrator params
Definition at line 145 of file core/integrate.cpp.
References runtimeError, and time_step.
Referenced by on_integration_start().
int python_integrate (int n_steps, bool recalc_forces, bool reuse_forces)
Definition at line 1120 of file core/integrate.cpp.
References autoupdate_correlations(), autoupdate_observables(), correlations_autoupdate, ES_ERROR, ES_OK, FIELD_SKIN, i, INTEG_TRACE, max_cut, mpi_bcast_parameter(), mpi_integrate(), observables_autoupdate, runtimeError, skin, skin_set, and this_node.
void rescale_velocities (double scale)
function that rescales all velocities on one node according to a new time step.
Definition at line 582 of file core/integrate.cpp.
References CellPList::cell, i, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleList::part, and ParticleMomentum::v.
Referenced by mpi_set_time_step(), and mpi_set_time_step_slave().
Variable Documentation
double configtemp[2]
Store configurational temperature terms (numerator/denominator)
Store configurational temperature terms (numerator/denominator)
Definition at line 107 of file core/integrate.cpp.
Referenced by add_lj_pair_force(), add_ljgen_pair_force(), calc_angle_harmonic_force(), calc_dihedral_force(), calc_harmonic_pair_force(), integrate_ensemble_init(), mpi_get_configtemp(), mpi_get_configtemp_slave(), and mpi_send_configtemp_flag().
int current_time_step_is_small
Flag to determine what kind of time step we're calculating.
Definition at line 97 of file core/integrate.cpp.
Referenced by build_verlet_lists_and_calc_verlet_ia(), calculate_verlet_ia(), friction_thermo_langevin(), integrate_vv(), propagate_press_box_pos_and_rescale_npt(), propagate_vel(), propagate_vel_pos(), rescale_forces(), and rescale_forces_propagate_vel().
int integ_switch
Switch determining which Integrator to use.
Definition at line 76 of file core/integrate.cpp.
double max_cut
Maximal interaction cutoff.
Definition at line 100 of file interaction_data.cpp.
Referenced by cells_on_geometry_change(), dd_create_cell_grid(), dd_on_geometry_change(), incubewithskin(), local_stress_tensor_calc(), python_integrate(), reactions_sanity_checks(), and tclcommand_integrate().
int mts_index
Smaller integration time step index.
Definition at line 98 of file core/integrate.cpp.
Referenced by integrate_vv(), and propagate_press_box_pos_and_rescale_npt().
int mts_max
Number of MTS time steps.
Definition at line 99 of file core/integrate.cpp.
Referenced by integrate_vv(), and propagate_press_box_pos_and_rescale_npt().
int n_verlet_updates
incremented if a Verlet update is done, aka particle resorting.
Definition at line 78 of file core/integrate.cpp.
double old_time_step
Old time step needed for rescaling of forces.
int recalc_forces
If non-zero, the forces will be recalculated before the next integration.
Definition at line 91 of file core/integrate.cpp.
int resort_particles
If non-zero, the particle data will be resorted before the next integration.
Definition at line 90 of file core/integrate.cpp.
double scal_store[3]
Store box dimensions for small timesteps.
Definition at line 101 of file core/integrate.cpp.
Referenced by propagate_press_box_pos_and_rescale_npt().
double sim_time
Actual simulation time (only on MASTER NODE).
Definition at line 85 of file core/integrate.cpp.
double skin
Verlet list skin.
Definition at line 86 of file core/integrate.cpp.
bool skin_set
True iff the user has changed the skin setting.
Definition at line 88 of file core/integrate.cpp.
Referenced by python_integrate(), tclcallback_skin(), and tclcommand_integrate().
double smaller_time_step
Other time step in the multiple time step scheme.
Definition at line 95 of file core/integrate.cpp.
Referenced by add_kinetic_virials(), build_verlet_lists_and_calc_verlet_ia(), calculate_verlet_ia(), energy_calc(), finalize_p_inst_npt(), friction_thermo_langevin(), integrate_vv(), mpi_set_smaller_time_step(), mpi_set_smaller_time_step_slave(), propagate_press_box_pos_and_rescale_npt(), propagate_vel(), propagate_vel_pos(), rescale_forces(), rescale_forces_propagate_vel(), tclcommand_analyze_parse_and_print_energy_kinetic(), tclcommand_part_print_v(), thermo_init_langevin(), and thermo_init_npt_isotropic().
double time_step
Time step for the integration.
Definition at line 80 of file core/integrate.cpp.
double time_step_half
Definition at line 81 of file core/integrate.cpp.
double time_step_squared
Definition at line 82 of file core/integrate.cpp.
double time_step_squared_half
Definition at line 83 of file core/integrate.cpp.
double verlet_reuse
Average number of integration steps the verlet list has been re used.
Definition at line 93 of file core/integrate.cpp.
double virial_store[3]
Flag to compute virial of all particles.
Definition at line 102 of file core/integrate.cpp.
Referenced by integrate_vv().