ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: interaction_data_tcl.cpp File Reference
interaction_data_tcl.cpp File Reference
#include <cstring>
#include <cstdlib>
#include "interaction_data_tcl.hpp"
#include "interaction_data.hpp"
#include "communication.hpp"
#include "global.hpp"
#include "comforce_tcl.hpp"
#include "comfixed_tcl.hpp"
#include "rattle_tcl.hpp"
#include "mol_cut_tcl.hpp"
#include "lj.hpp"
#include "ljangle.hpp"
#include "morse.hpp"
#include "tab.hpp"
#include "buckingham.hpp"
#include "mmm2d.hpp"
#include "mmm-common.hpp"
#include "elc.hpp"
#include "bmhtf-nacl_tcl.hpp"
#include "buckingham_tcl.hpp"
#include "gb_tcl.hpp"
#include "gaussian_tcl.hpp"
#include "hat_tcl.hpp"
#include "lb_tcl.hpp"
#include "lj_tcl.hpp"
#include "ljangle_tcl.hpp"
#include "ljcos_tcl.hpp"
#include "ljcos2_tcl.hpp"
#include "cos2_tcl.hpp"
#include "ljgen_tcl.hpp"
#include "hertzian_tcl.hpp"
#include "morse_tcl.hpp"
#include "dpd_tcl.hpp"
#include "soft_sphere_tcl.hpp"
#include "steppot_tcl.hpp"
#include "tab_tcl.hpp"
#include "tunable_slip_tcl.hpp"
#include "debye_hueckel_tcl.hpp"
#include "elc_tcl.hpp"
#include "maggs_tcl.hpp"
#include "mmm1d_tcl.hpp"
#include "mmm2d_tcl.hpp"
#include "p3m_tcl.hpp"
#include "reaction_field_tcl.hpp"
#include "actor/Mmm1dgpu_tcl.hpp"
#include "actor/Ewaldgpu_tcl.hpp"
#include "mdlc_correction_tcl.hpp"
#include "p3m-dipolar_tcl.hpp"
#include "magnetic_non_p3m_methods_tcl.hpp"
#include "angle_tcl.hpp"
#include "angle_harmonic_tcl.hpp"
#include "angle_cosine_tcl.hpp"
#include "angle_cossquare_tcl.hpp"
#include "angledist_tcl.hpp"
#include "dihedral_tcl.hpp"
#include "endangledist_tcl.hpp"
#include "fene_tcl.hpp"
#include "overlap_tcl.hpp"
#include "harmonic_dumbbell_tcl.hpp"
#include "harmonic_tcl.hpp"
#include "quartic_tcl.hpp"
#include "bonded_coulomb_tcl.hpp"
#include "subt_lj_tcl.hpp"
#include "umbrella_tcl.hpp"
#include "tcl/object-in-fluid/area_force_local_tcl.hpp"
#include "tcl/object-in-fluid/area_force_global_tcl.hpp"
#include "tcl/object-in-fluid/volume_force_tcl.hpp"
#include "tcl/object-in-fluid/stretching_force_tcl.hpp"
#include "tcl/object-in-fluid/stretchlin_force_tcl.hpp"
#include "tcl/object-in-fluid/bending_force_tcl.hpp"
#include "twist_stack_tcl.hpp"
#include "hydrogen_bond_tcl.hpp"
#include "immersed_boundary/ibm_triel_tcl.hpp"
#include "immersed_boundary/ibm_volume_conservation_tcl.hpp"
#include "immersed_boundary/ibm_tribend_tcl.hpp"
Macros
#define REGISTER_COULOMB(name, parser)
#define REGISTER_DIPOLAR(name, parser)
#define REGISTER_NONBONDED(name, parser)
#define REGISTER_BONDED(name, parser) if (ARG0_IS_S(name)) return parser(interp, bond_type, argc, argv);
Functions
int tclprint_to_result_DipolarIA (Tcl_Interp *interp)
int tclprint_to_result_CoulombIA (Tcl_Interp *interp)
int tclcommand_inter_parse_coulomb (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_inter_parse_magnetic (Tcl_Interp *interp, int argc, char **argv)
int tclprint_to_result_BondedIA (Tcl_Interp *interp, int i)
int tclprint_to_result_NonbondedIA (Tcl_Interp *interp, int i, int j)
int tclcommand_inter_print_all (Tcl_Interp *interp)
int tclcommand_inter_print_bonded (Tcl_Interp *interp, int i)
int tclcommand_inter_print_non_bonded (Tcl_Interp *interp, int part_type_a, int part_type_b)
int tclcommand_inter_parse_non_bonded (Tcl_Interp *interp, int part_type_a, int part_type_b, int argc, char **argv)
int tclcommand_inter_print_partner_num (Tcl_Interp *interp, int bond_type)
int tclcommand_print_efield_capacitors (ClientData data, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_inter_parse_virtual_bonds (Tcl_Interp *interp, int bond_type, int argc, char **argv)
int tclcommand_inter_parse_bonded (Tcl_Interp *interp, int bond_type, int argc, char **argv)
int tclcommand_inter_parse_rest (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_inter (ClientData _data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl command "inter".
int tclcallback_min_global_cut (Tcl_Interp *interp, void *_data)
datafield callback for min_global_cut.
Macro Definition Documentation
#define REGISTER_BONDED (name, parser) if (ARG0_IS_S(name)) return parser(interp, bond_type, argc, argv);
Referenced by tclcommand_inter_parse_bonded().
#define REGISTER_COULOMB (name, parser)
Value:
if(ARG0_IS_S(name))                                     \
    return parser(interp, argc-1, argv+1);
Referenced by tclcommand_inter_parse_coulomb().
#define REGISTER_DIPOLAR (name, parser)
Value:
if(ARG0_IS_S(name))                                     \
    return parser(interp, argc-1, argv+1);
Referenced by tclcommand_inter_parse_magnetic().
#define REGISTER_NONBONDED (name, parser)
Value:
else if (ARG0_IS_S(name))                                               \
      change = parser(interp, part_type_a, part_type_b, argc, argv)
Referenced by tclcommand_inter_parse_non_bonded().
Function Documentation
int tclcallback_min_global_cut (Tcl_Interp * interp, void * _data)
datafield callback for min_global_cut.
Sets the minimal cell size.
Definition at line 1157 of file interaction_data_tcl.cpp.
References FIELD_MIN_GLOBAL_CUT, min_global_cut, and mpi_bcast_parameter().
Referenced by tcl_register_global_variables().
int tclcommand_inter (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl command "inter".
This function allows the interaction parameters to be modified.
Definition at line 1086 of file interaction_data_tcl.cpp.
References ARG1_IS_I, ARG_IS_I, gather_runtime_errors(), i, tclcommand_inter_parse_bonded(), tclcommand_inter_parse_non_bonded(), tclcommand_inter_parse_rest(), tclcommand_inter_print_all(), tclcommand_inter_print_bonded(), and tclcommand_inter_print_non_bonded().
Referenced by tcl_register_commands().
int tclcommand_inter_parse_bonded (Tcl_Interp * interp, int bond_type, int argc, char ** argv)
Definition at line 945 of file interaction_data_tcl.cpp.
References ARG0_IS_S, REGISTER_BONDED, tclcommand_inter_parse_angle_cosine(), tclcommand_inter_parse_angle_cossquare(), tclcommand_inter_parse_angle_harmonic(), tclcommand_inter_parse_angledist(), tclcommand_inter_parse_area_force_global(), tclcommand_inter_parse_area_force_local(), tclcommand_inter_parse_bending_force(), tclcommand_inter_parse_bonded_coulomb(), tclcommand_inter_parse_dihedral(), tclcommand_inter_parse_endangledist(), tclcommand_inter_parse_fene(), tclcommand_inter_parse_harmonic(), tclcommand_inter_parse_harmonic_dumbbell(), tclcommand_inter_parse_hydrogen_bond(), tclcommand_inter_parse_ibm_tribend(), tclcommand_inter_parse_ibm_triel(), tclcommand_inter_parse_ibm_volume_conservation(), tclcommand_inter_parse_overlapped_bonded(), tclcommand_inter_parse_quartic(), tclcommand_inter_parse_rigid_bond(), tclcommand_inter_parse_stretching_force(), tclcommand_inter_parse_stretchlin_force(), tclcommand_inter_parse_subt_lj(), tclcommand_inter_parse_tabulated_bonded(), tclcommand_inter_parse_twist_stack(), tclcommand_inter_parse_umbrella(), tclcommand_inter_parse_virtual_bonds(), tclcommand_inter_parse_volume_force(), and tclcommand_inter_print_partner_num().
Referenced by tclcommand_inter().
int tclcommand_inter_parse_coulomb (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 128 of file interaction_data_tcl.cpp.
References ARG0_IS_D, ARG0_IS_S, Coulomb_parameters::bjerrum, coulomb, COULOMB_ELC_P3M, COULOMB_INTER_RF, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, coulomb_set_bjerrum(), Coulomb_parameters::method, mpi_bcast_coulomb_params(), REGISTER_COULOMB, tclcommand_inter_coulomb_parse_dh(), tclcommand_inter_coulomb_parse_ewaldgpu(), tclcommand_inter_coulomb_parse_maggs(), tclcommand_inter_coulomb_parse_mmm1d(), tclcommand_inter_coulomb_parse_mmm1dgpu(), tclcommand_inter_coulomb_parse_mmm2d(), tclcommand_inter_coulomb_parse_rf(), and tclprint_to_result_CoulombIA().
Referenced by tclcommand_inter_parse_rest().
int tclcommand_inter_parse_magnetic (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 232 of file interaction_data_tcl.cpp.
References ARG0_IS_D, ARG0_IS_S, coulomb, Coulomb_parameters::Dbjerrum, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, dipolar_set_Dbjerrum(), Coulomb_parameters::Dmethod, mpi_bcast_coulomb_params(), REGISTER_DIPOLAR, tclcommand_inter_magnetic_parse_dawaanr(), tclcommand_inter_magnetic_parse_mdds(), tclcommand_inter_magnetic_parse_mdlc_params(), and tclprint_to_result_DipolarIA().
Referenced by tclcommand_inter_parse_rest().
int tclcommand_inter_parse_non_bonded (Tcl_Interp * interp, int part_type_a, int part_type_b, int argc, char ** argv)
Definition at line 739 of file interaction_data_tcl.cpp.
References REGISTER_NONBONDED, tclcommand_inter_parse_affinity(), tclcommand_inter_parse_BMHTF(), tclcommand_inter_parse_buckingham(), tclcommand_inter_parse_comfixed(), tclcommand_inter_parse_comforce(), tclcommand_inter_parse_cos2(), tclcommand_inter_parse_gaussian(), tclcommand_inter_parse_gb(), tclcommand_inter_parse_hat(), tclcommand_inter_parse_hertzian(), tclcommand_inter_parse_inter_dpd(), tclcommand_inter_parse_interrf(), tclcommand_inter_parse_lj(), tclcommand_inter_parse_ljangle(), tclcommand_inter_parse_ljcos(), tclcommand_inter_parse_ljcos2(), tclcommand_inter_parse_ljgen(), tclcommand_inter_parse_molcut(), tclcommand_inter_parse_morse(), tclcommand_inter_parse_SmSt(), tclcommand_inter_parse_soft(), tclcommand_inter_parse_tab(), and tclcommand_inter_parse_tunable_slip().
Referenced by tclcommand_inter().
int tclcommand_inter_parse_rest (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1032 of file interaction_data_tcl.cpp.
References ARG0_IS_S, tclcommand_inter_parse_buckforcecap(), tclcommand_inter_parse_coulomb(), tclcommand_inter_parse_forcecap(), tclcommand_inter_parse_ljangleforcecap(), tclcommand_inter_parse_ljforcecap(), tclcommand_inter_parse_magnetic(), tclcommand_inter_parse_morseforcecap(), and tclcommand_inter_parse_tabforcecap().
Referenced by tclcommand_inter().
int tclcommand_inter_parse_virtual_bonds (Tcl_Interp * interp, int bond_type, int argc, char ** argv)
Definition at line 939 of file interaction_data_tcl.cpp.
References CHECK_VALUE, and virtual_set_params().
Referenced by tclcommand_inter_parse_bonded().
int tclcommand_inter_print_all (Tcl_Interp * interp)
Definition at line 615 of file interaction_data_tcl.cpp.
References BONDED_IA_NONE, bonded_ia_params, checkIfParticlesInteract(), coulomb, COULOMB_NONE, DIPOLAR_NONE, Coulomb_parameters::Dmethod, force_cap, i, Coulomb_parameters::method, n_bonded_ia, n_particle_types, start, tclprint_to_result_BondedIA(), tclprint_to_result_CoulombIA(), tclprint_to_result_DipolarIA(), and tclprint_to_result_NonbondedIA().
Referenced by tclcommand_inter().
int tclcommand_inter_print_bonded (Tcl_Interp * interp, int i)
Definition at line 694 of file interaction_data_tcl.cpp.
References n_bonded_ia, and tclprint_to_result_BondedIA().
Referenced by tclcommand_inter().
int tclcommand_inter_print_non_bonded (Tcl_Interp * interp, int part_type_a, int part_type_b)
Definition at line 718 of file interaction_data_tcl.cpp.
References get_ia_param(), make_particle_type_exist(), and tclprint_to_result_NonbondedIA().
Referenced by tclcommand_inter().
int tclcommand_inter_print_partner_num (Tcl_Interp * interp, int bond_type)
Definition at line 873 of file interaction_data_tcl.cpp.
References bonded_ia_params, n_bonded_ia, Bonded_ia_parameters::num, and params.
Referenced by tclcommand_inter_parse_bonded().
int tclcommand_print_efield_capacitors (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 899 of file interaction_data_tcl.cpp.
References ARG1_IS_S, MMM2D_struct::const_pot_on, coulomb, COULOMB_ELC_P3M, COULOMB_MMM2D, field_applied, field_induced, Coulomb_parameters::method, and mmm2d_params.
Referenced by tcl_register_commands().
int tclprint_to_result_BondedIA (Tcl_Interp * interp, int i)
Definition at line 320 of file interaction_data_tcl.cpp.
References BONDED_IA_ANGLE_COSINE, BONDED_IA_ANGLE_COSSQUARE, BONDED_IA_ANGLE_HARMONIC, BONDED_IA_ANGLE_OLD, BONDED_IA_ANGLEDIST, BONDED_IA_AREA_FORCE_GLOBAL, BONDED_IA_AREA_FORCE_LOCAL, BONDED_IA_BENDING_FORCE, BONDED_IA_BONDED_COULOMB, BONDED_IA_DIHEDRAL, BONDED_IA_ENDANGLEDIST, BONDED_IA_FENE, BONDED_IA_HARMONIC, BONDED_IA_HARMONIC_DUMBBELL, BONDED_IA_IBM_TRIBEND, BONDED_IA_IBM_TRIEL, BONDED_IA_IBM_VOLUME_CONSERVATION, BONDED_IA_NONE, BONDED_IA_OVERLAPPED, bonded_ia_params, BONDED_IA_QUARTIC, BONDED_IA_RIGID_BOND, BONDED_IA_STRETCHING_FORCE, BONDED_IA_STRETCHLIN_FORCE, BONDED_IA_SUBT_LJ, BONDED_IA_TABULATED, BONDED_IA_UMBRELLA, BONDED_IA_VIRTUAL_BOND, BONDED_IA_VOLUME_FORCE, i, params, tclprint_to_result_angle_cosineIA(), tclprint_to_result_angle_cossquareIA(), tclprint_to_result_angle_harmonicIA(), tclprint_to_result_angledistIA(), tclprint_to_result_areaforceglobalIA(), tclprint_to_result_areaforcelocalIA(), tclprint_to_result_bendingforceIA(), tclprint_to_result_bonded_coulombIA(), tclprint_to_result_dihedralIA(), tclprint_to_result_endangledistIA(), tclprint_to_result_feneIA(), tclprint_to_result_harmonic_dumbbellIA(), tclprint_to_result_harmonicIA(), tclprint_to_result_ibm_tribend(), tclprint_to_result_ibm_triel(), tclprint_to_result_ibm_volume_conservation(), tclprint_to_result_overlapIA(), tclprint_to_result_quarticIA(), tclprint_to_result_rigid_bond(), tclprint_to_result_stretchingforceIA(), tclprint_to_result_stretchlinforceIA(), tclprint_to_result_subt_ljIA(), tclprint_to_result_tabulated_bondedIA(), tclprint_to_result_umbrellaIA(), tclprint_to_result_volumeforceIA(), and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_print_all(), and tclcommand_inter_print_bonded().
int tclprint_to_result_CoulombIA (Tcl_Interp * interp)
Definition at line 541 of file interaction_data_tcl.cpp.
References Coulomb_parameters::bjerrum, coulomb, COULOMB_DH, COULOMB_ELC_P3M, COULOMB_EWALD_GPU, COULOMB_INTER_RF, COULOMB_MAGGS, COULOMB_MMM1D, COULOMB_MMM1D_GPU, COULOMB_MMM2D, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, Coulomb_parameters::method, tclprint_to_result_dh(), tclprint_to_result_ewaldgpu(), tclprint_to_result_Maggs(), tclprint_to_result_MMM1D(), tclprint_to_result_MMM1DGPU(), tclprint_to_result_MMM2D(), and tclprint_to_result_rf().
Referenced by tclcommand_inter_parse_coulomb(), and tclcommand_inter_print_all().
int tclprint_to_result_DipolarIA (Tcl_Interp * interp)
Definition at line 583 of file interaction_data_tcl.cpp.
References coulomb, Coulomb_parameters::Dbjerrum, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, tclprint_to_result_DAWAANR(), tclprint_to_result_Magnetic_dipolar_direct_sum_(), and tclprint_to_result_MDLC().
Referenced by tclcommand_inter_parse_magnetic(), and tclcommand_inter_print_all().
int tclprint_to_result_NonbondedIA (Tcl_Interp * interp, int i, int j)
Definition at line 431 of file interaction_data_tcl.cpp.
References IA_parameters::affinity_on, IA_parameters::BMHTF_cut, IA_parameters::BUCK_cut, IA_parameters::COMFIXED_flag, IA_parameters::COMFORCE_flag, IA_parameters::COS2_cut, IA_parameters::dpd_r_cut, IA_parameters::dpd_tr_cut, IA_parameters::Gaussian_cut, IA_parameters::GB_cut, get_ia_param(), IA_parameters::HAT_r, IA_parameters::Hertzian_sig, IA_parameters::LJ_cut, IA_parameters::LJANGLE_cut, IA_parameters::LJCOS2_cut, IA_parameters::LJCOS_cut, IA_parameters::LJGEN_cut, IA_parameters::mol_cut_type, IA_parameters::MORSE_cut, IA_parameters::rf_on, IA_parameters::SmSt_cut, IA_parameters::soft_cut, IA_parameters::TAB_filename, IA_parameters::TAB_maxval, tclprint_to_result_affinityIA(), tclprint_to_result_BMHTFIA(), tclprint_to_result_buckIA(), tclprint_to_result_comfixedIA(), tclprint_to_result_comforceIA(), tclprint_to_result_cos2IA(), tclprint_to_result_GaussianIA(), tclprint_to_result_gbIA(), tclprint_to_result_hatIA(), tclprint_to_result_HertzianIA(), tclprint_to_result_inter_dpdIA(), tclprint_to_result_interrfIA(), tclprint_to_result_ljangleIA(), tclprint_to_result_ljcos2IA(), tclprint_to_result_ljcosIA(), tclprint_to_result_ljgenIA(), tclprint_to_result_ljIA(), tclprint_to_result_molcutIA(), tclprint_to_result_morseIA(), tclprint_to_result_SmStIA(), tclprint_to_result_softIA(), tclprint_to_result_tunable_slipIA(), and IA_parameters::TUNABLE_SLIP_r_cut.
Referenced by tclcommand_inter_print_all(), and tclcommand_inter_print_non_bonded().