ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: interaction_data_tcl.hpp File Reference
interaction_data_tcl.hpp File Reference
#include "parser.hpp"
#include "forcecap_tcl.hpp"
Functions
int tclcommand_inter (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl command "inter".
int tclcommand_constraint (ClientData _data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the Tcl function constraint.
int tclcallback_min_global_cut (Tcl_Interp *interp, void *_data)
datafield callback for min_global_cut.
int tclcommand_print_efield_capacitors (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Function Documentation
int tclcallback_min_global_cut (Tcl_Interp * interp, void * _data)
datafield callback for min_global_cut.
Sets the minimal cell size.
Definition at line 1157 of file interaction_data_tcl.cpp.
References FIELD_MIN_GLOBAL_CUT, min_global_cut, and mpi_bcast_parameter().
Referenced by tcl_register_global_variables().
int tclcommand_constraint (ClientData _data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the Tcl function constraint.
This function allows to set and delete constraints.
Definition at line 1850 of file constraint_tcl.cpp.
References gather_runtime_errors(), generate_constraint(), mpi_bcast_constraint(), n_constraints, tclcommand_constraint_mindist_position(), tclcommand_constraint_mindist_position_vec(), tclcommand_constraint_parse_cylinder(), tclcommand_constraint_parse_ext_magn_field(), tclcommand_constraint_parse_hollow_cone(), tclcommand_constraint_parse_maze(), tclcommand_constraint_parse_plane_cell(), tclcommand_constraint_parse_plate(), tclcommand_constraint_parse_pore(), tclcommand_constraint_parse_rhomboid(), tclcommand_constraint_parse_rod(), tclcommand_constraint_parse_slitpore(), tclcommand_constraint_parse_sphere(), tclcommand_constraint_parse_stomatocyte(), tclcommand_constraint_parse_wall(), tclcommand_constraint_print(), tclprint_to_result_Constraint(), tclprint_to_result_ConstraintForce(), and tclprint_to_result_n_constraints().
Referenced by tcl_register_commands().
int tclcommand_inter (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl command "inter".
This function allows the interaction parameters to be modified.
Definition at line 1086 of file interaction_data_tcl.cpp.
References ARG1_IS_I, ARG_IS_I, gather_runtime_errors(), i, tclcommand_inter_parse_bonded(), tclcommand_inter_parse_non_bonded(), tclcommand_inter_parse_rest(), tclcommand_inter_print_all(), tclcommand_inter_print_bonded(), and tclcommand_inter_print_non_bonded().
Referenced by tcl_register_commands().
int tclcommand_print_efield_capacitors (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 899 of file interaction_data_tcl.cpp.
References ARG1_IS_S, MMM2D_struct::const_pot_on, coulomb, COULOMB_ELC_P3M, COULOMB_MMM2D, field_applied, field_induced, Coulomb_parameters::method, and mmm2d_params.
Referenced by tcl_register_commands().