ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: integrate_sd_matrix.cu File Reference
integrate_sd_matrix.cu File Reference
#include "config.hpp"
#include <stdio.h>
#include <assert.h>
#include "cuda_runtime.h"
#include "integrate_sd.hpp"
#include "integrate_sd_cuda.hpp"
#include "integrate_sd_matrix.hpp"
#include <openssl/md5.h>
Functions
void getAndHash (const real *data, const int size, unsigned char result[MD5_DIGEST_LENGTH])
Function Documentation
void getAndHash (const real * data, const int size, unsigned char result[MD5_DIGEST_LENGTH])
Definition at line 159 of file integrate_sd_matrix.cu.
References cuda_safe_mem.
Referenced by wavepart::assert_all(), matrix::assert_all(), wavepart::hash_cosines(), matrix::hash_data(), matrix::hash_dense(), wavepart::hash_matrices(), wavepart::hash_sines(), and wavepart::hash_vecs().