ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: integrate_sd.cpp File Reference
integrate_sd.cpp File Reference
Stokesian dynamics integrator.
#include <mpi.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <assert.h>
#include "utils.hpp"
#include "integrate_sd.hpp"
#include "integrate.hpp"
#include "reaction.hpp"
#include "electrokinetics.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "cells.hpp"
#include "verlet.hpp"
#include "rotation.hpp"
#include "ghosts.hpp"
#include "pressure.hpp"
#include "p3m.hpp"
#include "maggs.hpp"
#include "thermostat.hpp"
#include "initialize.hpp"
#include "forces.hpp"
#include "nsquare.hpp"
#include "domain_decomposition.hpp"
#include "layered.hpp"
#include "nemd.hpp"
#include "rattle.hpp"
#include "errorhandling.hpp"
#include "lattice.hpp"
#include "lb.hpp"
#include "virtual_sites.hpp"
#include "statistics_correlation.hpp"
#include "ghmc.hpp"
Macros
#define REQ_INT_VERLET 400
Tag for communication in verlet fix: propagate_positions()
Typedefs
typedef float real
switch between double and float
Functions
void integrator_sanity_checks_sd ()
check sanity of integrator params
void integrate_sd (int n_steps)
integrate with euler integrator.
int sd_set_particles_apart ()
set particle apart so they dont overlap.
Privat Functions
void propagate_pos_sd ()
Propagate the positions.
void propagate_pos_bd (int N, real *pos, real *force, real *velocity)
int sd_get_particle_num ()
Variables
double sd_viscosity =1
double sd_radius =-1
int sd_seed [] ={0,('E'+'S'+'P'+'R'+'e'+'s'+'S'+'o')}
int sd_random_state [] ={0,0}
double sd_random_precision =1e-3
Detailed Description
Stokesian dynamics integrator.
For more information about the integrator see integrate_sd.hpp.
Definition in file integrate_sd.cpp.
Macro Definition Documentation
#define REQ_INT_VERLET 400
Tag for communication in verlet fix: propagate_positions()
Definition at line 70 of file integrate_sd.cpp.
Typedef Documentation
typedef float real
switch between double and float
Definition at line 76 of file integrate_sd.cpp.
Function Documentation
void integrate_sd (int n_steps)
integrate with euler integrator.
Parameters
n_steps number of steps to integrate.
Integration Steps: Update the Positions [ p_i(t + dt) = p_i(t) + dt * {ij} * f_j(t) + dt * {ij} * f^B_j ]
Correct those particle positions that participate in a rigid/constrained bond
Definition at line 138 of file integrate_sd.cpp.
References calc_and_apply_mol_constraints(), calc_comfixed(), cell_structure, cells_update_ghosts(), check_runtime_errors(), CellStructure::collect_ghost_force_comm, comm_cart, convert_initial_torques(), correct_pos_shake(), coulomb, COULOMB_MAGGS, ek_initialized, ek_integrate(), force_calc(), ghmc_close(), ghmc_init(), ghmc_mc(), ghmc_momentum_update(), ghmc_nmd, ghost_communicator(), handle_collisions(), INTEG_METHOD_NPT_ISO, integ_switch, INTEG_TRACE, integrate_reaction(), nptiso_struct::invalidate_p_vel, lattice_boltzmann_update(), lattice_boltzmann_update_gpu(), LATTICE_LB, LATTICE_LB_GPU, lattice_switch, maggs_propagate_B_field(), Coulomb_parameters::method, MPI_Bcast(), MPI_DOUBLE, n_verlet_updates, nptiso, on_integration_start(), nptiso_struct::p_diff, nptiso_struct::p_inst, nptiso_struct::p_inst_av, propagate_pos_sd(), recalc_forces, save_old_pos(), sim_time, THERMO_BD, THERMO_GHMC, THERMO_SD, thermo_switch, this_node, time_step, transfer_momentum, transfer_momentum_gpu, verlet_reuse, and nptiso_struct::volume.
Referenced by tclcommand_integrate_sd().
void integrator_sanity_checks_sd ()
check sanity of integrator params
Definition at line 107 of file integrate_sd.cpp.
References runtimeError, sd_radius, sd_viscosity, temperature, and time_step.
void propagate_pos_bd (int N, real * pos, real * force, real * velocity)
Definition at line 636 of file integrate_sd.cpp.
References gaussian_random(), i, M_PI, sd_radius, sd_viscosity, temperature, and time_step.
Referenced by propagate_pos_sd().
void propagate_pos_sd ()
Propagate the positions.
Integration step:
Definition at line 348 of file integrate_sd.cpp.
References announce_resort_particles(), box_l, CellPList::cell, check_id, COORD_FIXED, DIM, distance2(), ParticleForce::f, Particle::f, free, i, ifParticleIsVirtual(), INTEG_TRACE, isnan, Particle::l, local_cells, Particle::m, malloc, CellPList::n, ParticleList::n, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticleLocal::p_old, ParticleList::part, PMASS, propagate_omega_quat_particle(), propagate_pos_bd(), propagate_pos_sd_cuda(), Particle::r, resort_particles, sd_get_particle_num(), skin, skin2, SQR(), temperature, THERMO_BD, THERMO_SD, thermo_switch, this_node, time_step, and ParticleMomentum::v.
Referenced by integrate_sd().
int sd_get_particle_num ()
Definition at line 619 of file integrate_sd.cpp.
References CellPList::cell, i, ifParticleIsVirtual(), local_cells, CellPList::n, ParticleList::n, and ParticleList::part.
Referenced by propagate_pos_sd(), and sd_set_particles_apart().
int sd_set_particles_apart ()
set particle apart so they dont overlap.
Definition at line 486 of file integrate_sd.cpp.
References box_l, CellPList::cell, i, isnan, local_cells, M_PI, CellPList::n, ParticleList::n, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, sd_get_particle_num(), sd_radius, and SQR().
Referenced by tclcommand_sd_set_particles_apart().
Variable Documentation
double sd_radius =-1
Definition at line 84 of file integrate_sd.cpp.
Referenced by integrator_sanity_checks_sd(), propagate_pos_bd(), propagate_pos_sd_cuda(), sd_set_particles_apart(), tclcallback_sd_radius(), and tclcommand_sd_set_particles_apart().
double sd_random_precision =1e-3
Definition at line 88 of file integrate_sd.cpp.
Referenced by sd_compute_displacement(), and tclcallback_sd_random_precision().
int sd_random_state[] ={0,0}
Definition at line 87 of file integrate_sd.cpp.
Referenced by sd_compute_displacement(), and tclcallback_sd_random_state().
int sd_seed[] ={0,('E'+'S'+'P'+'R'+'e'+'s'+'S'+'o')}
Definition at line 86 of file integrate_sd.cpp.
Referenced by sd_compute_displacement(), and tclcallback_sd_seed().
double sd_viscosity =1
Definition at line 83 of file integrate_sd.cpp.
Referenced by integrator_sanity_checks_sd(), propagate_pos_bd(), propagate_pos_sd_cuda(), and tclcallback_sd_viscosity().