ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: layered.cpp File Reference
layered.cpp File Reference
Implementation of layered.h.
#include <mpi.h>
#include <cstring>
#include "utils.hpp"
#include "cells.hpp"
#include "integrate.hpp"
#include "layered.hpp"
#include "global.hpp"
#include "communication.hpp"
#include "ghosts.hpp"
#include "forces.hpp"
#include "forces_inline.hpp"
#include "pressure.hpp"
#include "energy.hpp"
#include "energy_inline.hpp"
#include "constraint.hpp"
#include "domain_decomposition.hpp"
Macros
#define LAYERED_BOTTOM 1
wether we are the lowest node
#define LAYERED_TOP 2
wether we are the highest node
#define LAYERED_PERIODIC 4
same as PERIODIC(2)
#define LAYERED_BTM_MASK (LAYERED_BOTTOM|LAYERED_PERIODIC)
#define LAYERED_TOP_MASK (LAYERED_TOP|LAYERED_PERIODIC)
#define LAYERED_TOP_NEIGHBOR ((layered_flags & LAYERED_TOP_MASK) != LAYERED_TOP)
node has a neighbor above (modulo n_nodes)
#define LAYERED_BTM_NEIGHBOR ((layered_flags & LAYERED_BTM_MASK) != LAYERED_BOTTOM)
node has a neighbor below (modulo n_nodes)
Functions
void layered_get_mi_vector (double res[3], double a[3], double b[3])
calculate the minimum image vector
Cell * layered_position_to_cell (double pos[3])
map a position to a cell, if on this node, else returns NULL.
void layered_topology_release ()
free all data structure that belong to this cell system
static void layered_prepare_comm (GhostCommunicator *comm, int data_parts)
void layered_topology_init (CellPList *old)
initialize the layered cell system and sort in the particles
static void layered_append_particles (ParticleList *pl, ParticleList *up, ParticleList *dn)
void layered_exchange_and_sort_particles (int global_flag)
distribute all particles such that they are in their dedicated cell
void layered_calculate_ia ()
nonbonded and bonded force calculation using the verlet list
void layered_calculate_energies ()
calculate short ranged energy
void layered_calculate_virials (int v_comp)
calculate short ranged virials
Variables
int layered_flags = 0
int n_layers = -1
number of layers, i.
int determine_n_layers = 1
double layer_h = 0
height of the layers, i.
double layer_h_i = 0
static int btm
static int top
Detailed Description
Implementation of layered.h.
Definition in file layered.cpp.
Macro Definition Documentation
#define LAYERED_BOTTOM 1
wether we are the lowest node
Definition at line 70 of file layered.cpp.
Referenced by layered_topology_init().
#define LAYERED_BTM_MASK (LAYERED_BOTTOM|LAYERED_PERIODIC)
Definition at line 75 of file layered.cpp.
Referenced by layered_prepare_comm().
#define LAYERED_BTM_NEIGHBOR ((layered_flags & LAYERED_BTM_MASK) != LAYERED_BOTTOM)
node has a neighbor below (modulo n_nodes)
Definition at line 80 of file layered.cpp.
Referenced by layered_append_particles(), layered_exchange_and_sort_particles(), layered_position_to_cell(), layered_prepare_comm(), and layered_topology_init().
#define LAYERED_PERIODIC 4
same as PERIODIC(2)
Definition at line 74 of file layered.cpp.
Referenced by layered_prepare_comm(), and layered_topology_init().
#define LAYERED_TOP 2
wether we are the highest node
Definition at line 72 of file layered.cpp.
Referenced by layered_topology_init().
#define LAYERED_TOP_MASK (LAYERED_TOP|LAYERED_PERIODIC)
Definition at line 76 of file layered.cpp.
Referenced by layered_prepare_comm().
#define LAYERED_TOP_NEIGHBOR ((layered_flags & LAYERED_TOP_MASK) != LAYERED_TOP)
node has a neighbor above (modulo n_nodes)
Definition at line 78 of file layered.cpp.
Referenced by layered_append_particles(), layered_exchange_and_sort_particles(), layered_position_to_cell(), layered_prepare_comm(), and layered_topology_init().
Function Documentation
static void layered_append_particles (ParticleList * pl, ParticleList * up, ParticleList * dn) static
Definition at line 409 of file layered.cpp.
References CELL_TRACE, fold_position(), ParticleLocal::i, ParticleProperties::identity, Particle::l, LAYERED_BTM_NEIGHBOR, layered_position_to_cell(), LAYERED_TOP_NEIGHBOR, Particle::m, move_indexed_particle(), my_left, my_right, ParticleList::n, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, this_node, and ParticleMomentum::v.
Referenced by layered_exchange_and_sort_particles().
void layered_calculate_energies ()
calculate short ranged energy
Definition at line 616 of file layered.cpp.
References add_bonded_energy(), add_constraints_energy(), add_external_potential_energy(), add_kinetic_energy(), add_non_bonded_pair_energy(), CELL_TRACE, cells, do_nonbonded(), i, Particle::l, layered_get_mi_vector(), ParticleList::n, n_layers, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, sqrlen(), and this_node.
Referenced by energy_calc().
void layered_calculate_ia ()
nonbonded and bonded force calculation using the verlet list
calculate short ranged forces
Definition at line 561 of file layered.cpp.
References add_bonded_force(), add_constraints_forces(), add_external_potential_forces(), add_non_bonded_pair_force(), CELL_TRACE, cells, do_nonbonded(), i, Particle::l, layered_get_mi_vector(), ParticleList::n, n_layers, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, sqrlen(), and this_node.
Referenced by force_calc().
void layered_calculate_virials (int v_comp)
calculate short ranged virials
Definition at line 673 of file layered.cpp.
References add_bonded_virials(), add_kinetic_virials(), add_non_bonded_pair_virials(), add_three_body_bonded_stress(), cells, do_nonbonded(), i, Particle::l, layered_get_mi_vector(), ParticleList::n, n_layers, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, and sqrlen().
Referenced by pressure_calc().
void layered_exchange_and_sort_particles (int global_flag)
distribute all particles such that they are in their dedicated cell
Definition at line 433 of file layered.cpp.
References btm, CELL_GLOBAL_EXCHANGE, CELL_TRACE, cells, comm_cart, errexit(), fold_position(), ParticleLocal::i, ParticleProperties::identity, init_particlelist(), Particle::l, layered_append_particles(), LAYERED_BTM_NEIGHBOR, layered_position_to_cell(), LAYERED_TOP_NEIGHBOR, Particle::m, move_indexed_particle(), MPI_Allreduce(), MPI_INT, MPI_MAX, my_left, my_right, ParticleList::n, n_layers, n_nodes, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, realloc_particlelist(), recv_particles(), runtimeError, send_particles(), this_node, top, and ParticleMomentum::v.
Referenced by cells_resort_particles().
void layered_get_mi_vector (double res[3], double a[3], double b[3])
calculate the minimum image vector
Definition at line 88 of file layered.cpp.
References box_l, box_l_i, dround(), i, and PERIODIC.
Referenced by layered_calculate_energies(), layered_calculate_ia(), layered_calculate_ia_iccp3m(), layered_calculate_virials(), MMM2D_dielectric_layers_energy_contribution(), and MMM2D_dielectric_layers_force_contribution().
Cell* layered_position_to_cell (double pos[3])
map a position to a cell, if on this node, else returns NULL.
Definition at line 100 of file layered.cpp.
References cells, layer_h_i, LAYERED_BTM_NEIGHBOR, LAYERED_TOP_NEIGHBOR, my_left, and n_layers.
Referenced by layered_append_particles(), layered_exchange_and_sort_particles(), and layered_topology_init().
static void layered_prepare_comm (GhostCommunicator * comm, int data_parts) static
Definition at line 128 of file layered.cpp.
References box_l, btm, CELL_TRACE, cells, GhostCommunicator::comm, comm_cart, GhostCommunicator::data_parts, GHOST_LOCL, GHOST_PREFETCH, GHOST_PSTSTORE, GHOST_RECV, GHOST_SEND, GHOSTTRANS_FORCE, GHOSTTRANS_POSITION, GHOSTTRANS_POSSHFTD, LAYERED_BTM_MASK, LAYERED_BTM_NEIGHBOR, layered_flags, LAYERED_PERIODIC, LAYERED_TOP_MASK, LAYERED_TOP_NEIGHBOR, malloc, GhostCommunication::mpi_comm, n_layers, n_nodes, GhostCommunication::n_part_lists, GhostCommunication::node, GhostCommunication::part_lists, prepare_comm(), GhostCommunication::shift, this_node, top, and GhostCommunication::type.
Referenced by layered_topology_init().
void layered_topology_init (CellPList * old)
initialize the layered cell system and sort in the particles
Definition at line 310 of file layered.cpp.
References append_unindexed_particle(), btm, CellPList::cell, cell_structure, CELL_STRUCTURE_LAYERED, CELL_TRACE, cells, CellStructure::collect_ghost_force_comm, comm_cart, determine_n_layers, CellStructure::exchange_ghosts_comm, ghost_cells, CellStructure::ghost_cells_comm, GHOSTTRANS_FORCE, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, imax(), layer_h, layer_h_i, LAYERED_BOTTOM, LAYERED_BTM_NEIGHBOR, layered_flags, LAYERED_PERIODIC, layered_position_to_cell(), layered_prepare_comm(), LAYERED_TOP, LAYERED_TOP_NEIGHBOR, local_box_l, local_cells, map_position_node_array(), max_num_cells, max_range, MPI_Bcast(), MPI_INT, CellPList::n, ParticleList::n, n_layers, n_nodes, node_grid, Particle::p, ParticleList::part, PERIODIC, CellStructure::position_to_cell, CellStructure::position_to_node, realloc_cellplist(), realloc_cells(), runtimeError, this_node, top, CellStructure::type, CellStructure::update_ghost_pos_comm, and update_local_particles().
Referenced by topology_init().
void layered_topology_release ()
free all data structure that belong to this cell system
Definition at line 119 of file layered.cpp.
References cell_structure, CELL_TRACE, CellStructure::collect_ghost_force_comm, CellStructure::exchange_ghosts_comm, free_comm(), CellStructure::ghost_cells_comm, this_node, and CellStructure::update_ghost_pos_comm.
Referenced by topology_release().
Variable Documentation
int btm static
Definition at line 86 of file layered.cpp.
Referenced by layered_exchange_and_sort_particles(), layered_prepare_comm(), and layered_topology_init().
int determine_n_layers = 1
Definition at line 83 of file layered.cpp.
Referenced by layered_topology_init(), and tclcommand_cellsystem().
double layer_h = 0
height of the layers, i.
e. box_l[2]/n_nodes
Definition at line 84 of file layered.cpp.
Referenced by add_force_contribution(), energy_contribution(), layered_topology_init(), MMM2D_setup_constants(), MMM2D_tune_far(), setup_P(), setup_PQ(), and setup_Q().
double layer_h_i = 0
Definition at line 84 of file layered.cpp.
Referenced by layered_position_to_cell(), and layered_topology_init().
int layered_flags = 0
Definition at line 82 of file layered.cpp.
Referenced by layered_prepare_comm(), and layered_topology_init().
int n_layers = -1
number of layers, i.
e. cells, per node
Definition at line 83 of file layered.cpp.
Referenced by add_P_force(), add_PQ_force(), add_Q_force(), add_z_force(), clear_image_contributions(), distribute(), gather_image_contributions(), layered_calculate_energies(), layered_calculate_ia(), layered_calculate_ia_iccp3m(), layered_calculate_virials(), layered_exchange_and_sort_particles(), layered_position_to_cell(), layered_prepare_comm(), layered_topology_init(), MMM2D_dielectric_layers_energy_contribution(), MMM2D_dielectric_layers_force_contribution(), P_energy(), PQ_energy(), prepare_scx_cache(), prepare_scy_cache(), Q_energy(), setup_P(), setup_PQ(), setup_Q(), setup_z_energy(), setup_z_force(), tclcommand_cellsystem(), and z_energy().
int top static
Definition at line 86 of file layered.cpp.
Referenced by layered_exchange_and_sort_particles(), layered_prepare_comm(), layered_topology_init(), and tclcommand_inter_coulomb_parse_mmm2d().