ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lb-boundaries.cpp File Reference
lb-boundaries.cpp File Reference
Boundary conditions for Lattice Boltzmann fluid dynamics.
#include "utils.hpp"
#include "constraint.hpp"
#include "lb-boundaries.hpp"
#include "lbgpu.hpp"
#include "lb.hpp"
#include "electrokinetics.hpp"
#include "electrokinetics_pdb_parse.hpp"
#include "interaction_data.hpp"
#include "communication.hpp"
Functions
void lbboundary_mindist_position (double pos[3], double *mindist, double distvec[3], int *no)
void lb_init_boundaries ()
Initialize boundary conditions for all constraints in the system.
int lbboundary_get_force (int no, double *f)
void lb_bounce_back ()
Bounce back boundary conditions.
Variables
int n_lb_boundaries = 0
LB_Boundary * lb_boundaries = NULL
Detailed Description
Boundary conditions for Lattice Boltzmann fluid dynamics.
Header file for lb-boundaries.hpp.
Definition in file lb-boundaries.cpp.
Function Documentation
void lb_bounce_back ()
Bounce back boundary conditions.
The populations that have propagated into a boundary node are bounced back to the node they came from. This results in no slip boundary conditions.
[cf. Ladd and Verberg, J. Stat. Phys. 104(5/6):1191-1251, 2001]
Definition at line 412 of file lb-boundaries.cpp.
References LB_Parameters::agrid, boundary, LB_FluidNode::boundary, LB_Model::c, LB_Model::c_sound_sq, LB_Boundary::force, get_linear_index(), Lattice::grid, Lattice::halo_grid, i, lb_calc_modes(), lbfields, lbfluid, lblattice, lbmodel, lbpar, LB_Parameters::rho, LB_Boundary::velocity, and LB_Model::w.
Referenced by lb_collide_stream().
void lb_init_boundaries ()
Initialize boundary conditions for all constraints in the system.
Initializes the constrains in the system.
call of cuda fkt
Definition at line 98 of file lb-boundaries.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, LB_FluidNode::boundary, calculate_cylinder_dist(), calculate_hollow_cone_dist(), calculate_pore_dist(), calculate_rhomboid_dist(), calculate_sphere_dist(), calculate_spherocylinder_dist(), calculate_stomatocyte_dist(), calculate_wall_dist(), LB_Boundary::charge_density, LB_Boundary::cyl, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, ek_init_species_density_wallcharge(), ek_initialized, ek_parameters, free, get_linear_index(), Lattice::grid, Lattice::halo_grid, Lattice::halo_grid_volume, LB_Boundary::hollow_cone, LATTICE_LB_GPU, lattice_switch, LB_BOUNDARY_CYL, LB_BOUNDARY_HOLLOW_CONE, LB_BOUNDARY_POR, LB_BOUNDARY_RHOMBOID, LB_BOUNDARY_SPH, LB_BOUNDARY_SPHEROCYLINDER, LB_BOUNDARY_STOMATOCYTE, LB_BOUNDARY_WAL, lb_init_boundaries_GPU(), lbfields, lblattice, lbpar_gpu, malloc, map_node_array(), n_lb_boundaries, LB_Boundary::net_charge, pdb_boundary_lattice, pdb_charge_lattice, LB_Boundary::pore, realloc, LB_Boundary::rhomboid, runtimeError, LB_Boundary::sph, LB_Boundary::spherocyl, LB_Boundary::stomatocyte, this_node, LB_Boundary::type, LB_Boundary::velocity, and LB_Boundary::wal.
Referenced by lb_reinit_fluid(), on_boxl_change(), on_lb_params_change_gpu(), on_lbboundary_change(), and tclcommand_electrokinetics().
int lbboundary_get_force (int no, double * f)
Definition at line 375 of file lb-boundaries.cpp.
References LB_Parameters::agrid, ES_ERROR, free, LATTICE_LB_GPU, lattice_switch, lb_gpu_get_boundary_forces(), lbpar, malloc, mpi_gather_stats(), n_lb_boundaries, and LB_Parameters::tau.
Referenced by tclcommand_lbboundary().
void lbboundary_mindist_position (double pos[3], double * mindist, double distvec[3], int * no)
Definition at line 43 of file lb-boundaries.cpp.
References calculate_cylinder_dist(), calculate_hollow_cone_dist(), calculate_pore_dist(), calculate_rhomboid_dist(), calculate_sphere_dist(), calculate_spherocylinder_dist(), calculate_stomatocyte_dist(), calculate_wall_dist(), CONSTRAINT_SPHEROCYLINDER, LB_Boundary::cyl, LB_Boundary::hollow_cone, LB_BOUNDARY_CYL, LB_BOUNDARY_HOLLOW_CONE, LB_BOUNDARY_POR, LB_BOUNDARY_RHOMBOID, LB_BOUNDARY_SPH, LB_BOUNDARY_STOMATOCYTE, LB_BOUNDARY_WAL, n_lb_boundaries, LB_Boundary::pore, LB_Boundary::rhomboid, LB_Boundary::sph, LB_Boundary::spherocyl, LB_Boundary::stomatocyte, and LB_Boundary::wal.
Referenced by GetIBMInterpolatedVelocity(), and lb_lbfluid_get_interpolated_velocity().
Variable Documentation
LB_Boundary* lb_boundaries = NULL
Definition at line 41 of file lb-boundaries.cpp.
Referenced by generate_lbboundary(), GetIBMInterpolatedVelocity(), InitCUDA_IBM(), lb_collect_boundary_forces(), lb_collide_stream(), lb_lbfluid_get_interpolated_velocity(), lb_reinit_forces(), mpi_bcast_lbboundary(), mpi_bcast_lbboundary_slave(), and tclcommand_printLbBoundaryToResult().
int n_lb_boundaries = 0
Definition at line 40 of file lb-boundaries.cpp.
Referenced by generate_lbboundary(), InitCUDA_IBM(), lb_calc_shanchen_GPU(), lb_collect_boundary_forces(), lb_collide_stream(), lb_gpu_get_boundary_forces(), lb_init_boundaries(), lb_init_boundaries_GPU(), lb_integrate_GPU(), lb_reinit_forces(), lbboundary_get_force(), lbboundary_mindist_position(), mpi_bcast_lbboundary(), mpi_bcast_lbboundary_slave(), tclcommand_electrokinetics(), tclcommand_lbboundary(), and tclcommand_lbboundary_print_all().