ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lb-boundaries.hpp File Reference
lb-boundaries.hpp File Reference
Boundary conditions for Lattice Boltzmann fluid dynamics.
#include "utils.hpp"
#include "constraint.hpp"
Data Structures
struct LB_Boundary
Structure to specify a boundary.
Macros
#define LB_BOUNDARY_WAL 1
wall constraint applied
#define LB_BOUNDARY_SPH 2
spherical constraint applied
#define LB_BOUNDARY_CYL 3
(finite) cylinder shaped constraint applied
#define LB_BOUNDARY_POR 4
a pore geometry
#define LB_BOUNDARY_RHOMBOID 5
rhomboid shaped constraint applied
#define LB_BOUNDARY_STOMATOCYTE 6
stomatocyte shaped constraint applied
#define LB_BOUNDARY_BOX 7
box shaped constraint (for electrokinetics reaction code)
#define LB_BOUNDARY_HOLLOW_CONE 8
hollow cone shaped constraint (for electrokinetics reaction code)
#define LB_BOUNDARY_SPHEROCYLINDER 9
spherocylinder constraint
#define LB_BOUNDARY_BOUNCE_BACK 1
Functions
void lb_init_boundaries ()
Initializes the constrains in the system.
void lbboundary_mindist_position (double pos[3], double *mindist, double distvec[3], int *no)
int lbboundary_get_force (int no, double *f)
void lb_bounce_back ()
Bounce back boundary conditions.
Variables
int n_lb_boundaries
LB_Boundary * lb_boundaries
Detailed Description
Boundary conditions for Lattice Boltzmann fluid dynamics.
Header file for lb-boundaries.cpp.
In the current version only simple bounce back walls are implemented. Thus after the streaming step, in all wall nodes all populations are bounced back from where they came from. Ulf Schiller spent a lot of time working on more powerful alternatives, they are to be found in the lb_testing branch of espresso until the end of 2010. Now we stripped down the code to a minimum, as most of it was not sufficiently understandable.
Anyone who wants to revive these, please look into the git.
Definition in file lb-boundaries.hpp.
Macro Definition Documentation
#define LB_BOUNDARY_BOUNCE_BACK 1
Definition at line 65 of file lb-boundaries.hpp.
Referenced by generate_lbboundary().
#define LB_BOUNDARY_BOX 7
box shaped constraint (for electrokinetics reaction code)
Definition at line 58 of file lb-boundaries.hpp.
Referenced by tclcommand_lbboundary_box().
#define LB_BOUNDARY_CYL 3
(finite) cylinder shaped constraint applied
Definition at line 50 of file lb-boundaries.hpp.
Referenced by lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_lbboundary_cylinder(), and tclcommand_printLbBoundaryToResult().
#define LB_BOUNDARY_HOLLOW_CONE 8
hollow cone shaped constraint (for electrokinetics reaction code)
Definition at line 60 of file lb-boundaries.hpp.
Referenced by lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_lbboundary_hollow_cone(), and tclcommand_printLbBoundaryToResult().
#define LB_BOUNDARY_POR 4
a pore geometry
Definition at line 52 of file lb-boundaries.hpp.
Referenced by lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_lbboundary_pore(), and tclcommand_printLbBoundaryToResult().
#define LB_BOUNDARY_RHOMBOID 5
rhomboid shaped constraint applied
Definition at line 54 of file lb-boundaries.hpp.
Referenced by lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_lbboundary_rhomboid(), and tclcommand_printLbBoundaryToResult().
#define LB_BOUNDARY_SPH 2
spherical constraint applied
Definition at line 48 of file lb-boundaries.hpp.
Referenced by lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_lbboundary_sphere(), and tclcommand_printLbBoundaryToResult().
#define LB_BOUNDARY_SPHEROCYLINDER 9
spherocylinder constraint
Definition at line 62 of file lb-boundaries.hpp.
Referenced by lb_init_boundaries(), tclcommand_lbboundary_spherocylinder(), and tclcommand_printLbBoundaryToResult().
#define LB_BOUNDARY_STOMATOCYTE 6
stomatocyte shaped constraint applied
Definition at line 56 of file lb-boundaries.hpp.
Referenced by lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_lbboundary_stomatocyte(), and tclcommand_printLbBoundaryToResult().
#define LB_BOUNDARY_WAL 1
wall constraint applied
Definition at line 46 of file lb-boundaries.hpp.
Referenced by lb_init_boundaries(), lbboundary_mindist_position(), tclcommand_lbboundary_wall(), and tclcommand_printLbBoundaryToResult().
Function Documentation
void lb_bounce_back ()
Bounce back boundary conditions.
The populations that have propagated into a boundary node are bounced back to the node they came from. This results in no slip boundary conditions.
[cf. Ladd and Verberg, J. Stat. Phys. 104(5/6):1191-1251, 2001]
Definition at line 412 of file lb-boundaries.cpp.
References LB_Parameters::agrid, boundary, LB_FluidNode::boundary, LB_Model::c, LB_Model::c_sound_sq, LB_Boundary::force, get_linear_index(), Lattice::grid, Lattice::halo_grid, i, lb_calc_modes(), lbfields, lbfluid, lblattice, lbmodel, lbpar, LB_Parameters::rho, LB_Boundary::velocity, and LB_Model::w.
Referenced by lb_collide_stream().
void lb_init_boundaries ()
Initializes the constrains in the system.
This function determines the lattice sited which belong to boundaries and marks them with a corresponding flag.
Initializes the constrains in the system.
call of cuda fkt
Definition at line 98 of file lb-boundaries.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, LB_FluidNode::boundary, calculate_cylinder_dist(), calculate_hollow_cone_dist(), calculate_pore_dist(), calculate_rhomboid_dist(), calculate_sphere_dist(), calculate_spherocylinder_dist(), calculate_stomatocyte_dist(), calculate_wall_dist(), LB_Boundary::charge_density, LB_Boundary::cyl, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, ek_init_species_density_wallcharge(), ek_initialized, ek_parameters, free, get_linear_index(), Lattice::grid, Lattice::halo_grid, Lattice::halo_grid_volume, LB_Boundary::hollow_cone, LATTICE_LB_GPU, lattice_switch, LB_BOUNDARY_CYL, LB_BOUNDARY_HOLLOW_CONE, LB_BOUNDARY_POR, LB_BOUNDARY_RHOMBOID, LB_BOUNDARY_SPH, LB_BOUNDARY_SPHEROCYLINDER, LB_BOUNDARY_STOMATOCYTE, LB_BOUNDARY_WAL, lb_init_boundaries_GPU(), lbfields, lblattice, lbpar_gpu, malloc, map_node_array(), n_lb_boundaries, LB_Boundary::net_charge, pdb_boundary_lattice, pdb_charge_lattice, LB_Boundary::pore, realloc, LB_Boundary::rhomboid, runtimeError, LB_Boundary::sph, LB_Boundary::spherocyl, LB_Boundary::stomatocyte, this_node, LB_Boundary::type, LB_Boundary::velocity, and LB_Boundary::wal.
Referenced by lb_reinit_fluid(), on_boxl_change(), on_lb_params_change_gpu(), on_lbboundary_change(), and tclcommand_electrokinetics().
int lbboundary_get_force (int no, double * f)
Definition at line 375 of file lb-boundaries.cpp.
References LB_Parameters::agrid, ES_ERROR, free, LATTICE_LB_GPU, lattice_switch, lb_gpu_get_boundary_forces(), lbpar, malloc, mpi_gather_stats(), n_lb_boundaries, and LB_Parameters::tau.
Referenced by tclcommand_lbboundary().
void lbboundary_mindist_position (double pos[3], double * mindist, double distvec[3], int * no)
Definition at line 43 of file lb-boundaries.cpp.
References calculate_cylinder_dist(), calculate_hollow_cone_dist(), calculate_pore_dist(), calculate_rhomboid_dist(), calculate_sphere_dist(), calculate_spherocylinder_dist(), calculate_stomatocyte_dist(), calculate_wall_dist(), CONSTRAINT_SPHEROCYLINDER, LB_Boundary::cyl, LB_Boundary::hollow_cone, LB_BOUNDARY_CYL, LB_BOUNDARY_HOLLOW_CONE, LB_BOUNDARY_POR, LB_BOUNDARY_RHOMBOID, LB_BOUNDARY_SPH, LB_BOUNDARY_STOMATOCYTE, LB_BOUNDARY_WAL, n_lb_boundaries, LB_Boundary::pore, LB_Boundary::rhomboid, LB_Boundary::sph, LB_Boundary::spherocyl, LB_Boundary::stomatocyte, and LB_Boundary::wal.
Referenced by GetIBMInterpolatedVelocity(), and lb_lbfluid_get_interpolated_velocity().
Variable Documentation
LB_Boundary* lb_boundaries
Definition at line 41 of file lb-boundaries.cpp.
Referenced by generate_lbboundary(), GetIBMInterpolatedVelocity(), InitCUDA_IBM(), lb_collect_boundary_forces(), lb_collide_stream(), lb_lbfluid_get_interpolated_velocity(), lb_reinit_forces(), mpi_bcast_lbboundary(), mpi_bcast_lbboundary_slave(), and tclcommand_printLbBoundaryToResult().
int n_lb_boundaries
Definition at line 40 of file lb-boundaries.cpp.