ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lb-boundaries_tcl.cpp File Reference
lb-boundaries_tcl.cpp File Reference
Boundary conditions parser file for Lattice Boltzmann fluid dynamics.
#include "utils.hpp"
#include "parser.hpp"
#include "constraint.hpp"
#include "lb.hpp"
#include "interaction_data.hpp"
#include "lb-boundaries.hpp"
#include "communication.hpp"
#include <limits>
Functions
int tclcommand_lbboundary (ClientData _data, Tcl_Interp *interp, int argc, char **argv)
lb boundary command.
int tclcommand_lbboundary_wall (LB_Boundary *lbb, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_lbboundary_sphere (LB_Boundary *lbb, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_lbboundary_cylinder (LB_Boundary *lbb, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_lbboundary_pore (LB_Boundary *lbb, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_lbboundary_stomatocyte (LB_Boundary *lbb, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_lbboundary_hollow_cone (LB_Boundary *lbb, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_printLbBoundaryToResult (Tcl_Interp *interp, int i)
int tclcommand_lbboundary_print_all (Tcl_Interp *interp)
LB_Boundary * generate_lbboundary ()
int tclcommand_lbboundary_spherocylinder (LB_Boundary *lbb, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_lbboundary_rhomboid (LB_Boundary *lbb, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_lbboundary_box (LB_Boundary *lbb, Tcl_Interp *interp, int argc, char **argv)
Detailed Description
Boundary conditions parser file for Lattice Boltzmann fluid dynamics.
Definition in file lb-boundaries_tcl.cpp.
Function Documentation
LB_Boundary* generate_lbboundary ()
Definition at line 278 of file lb-boundaries_tcl.cpp.
References LB_Boundary::charge_density, ek_initialized, LB_Boundary::force, lb_boundaries, LB_BOUNDARY_BOUNCE_BACK, n_lb_boundaries, realloc, LB_Boundary::type, and LB_Boundary::velocity.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbboundary().
int tclcommand_lbboundary (ClientData _data, Tcl_Interp * interp, int argc, char ** argv)
lb boundary command.
From lb-boundaries_tcl.cpp
Definition at line 1374 of file lb-boundaries_tcl.cpp.
References ARG_IS_S, gather_runtime_errors(), generate_lbboundary(), i, LATTICE_LB_GPU, LATTICE_OFF, lattice_switch, lbboundary_get_force(), mpi_bcast_lbboundary(), n_lb_boundaries, tclcommand_lbboundary_cylinder(), tclcommand_lbboundary_hollow_cone(), tclcommand_lbboundary_pore(), tclcommand_lbboundary_print_all(), tclcommand_lbboundary_rhomboid(), tclcommand_lbboundary_sphere(), tclcommand_lbboundary_spherocylinder(), tclcommand_lbboundary_stomatocyte(), tclcommand_lbboundary_wall(), and tclcommand_printLbBoundaryToResult().
Referenced by tcl_register_commands().
int tclcommand_lbboundary_box (LB_Boundary * lbb, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1364 of file lb-boundaries_tcl.cpp.
References LB_Boundary::box, LB_Boundary::c, LB_BOUNDARY_BOX, LB_Boundary::type, and Constraint_box::value.
Referenced by tclcommand_electrokinetics().
int tclcommand_lbboundary_cylinder (LB_Boundary * lbb, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 464 of file lb-boundaries_tcl.cpp.
References LB_Parameters::agrid, ARG_IS_S, Constraint_cylinder::axis, LB_Boundary::c, LB_Boundary::cyl, Constraint_cylinder::direction, i, LATTICE_LB_GPU, lattice_switch, LB_BOUNDARY_CYL, lbpar, Constraint_cylinder::length, Constraint_cylinder::pos, Constraint_cylinder::rad, SQR(), LB_Parameters::tau, LB_Boundary::type, and LB_Boundary::velocity.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbboundary().
int tclcommand_lbboundary_hollow_cone (LB_Boundary * lbb, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1200 of file lb-boundaries_tcl.cpp.
References ARG_IS_D, ARG_IS_S, LB_Boundary::c, Constraint_hollow_cone::direction, LB_Boundary::hollow_cone, Constraint_hollow_cone::inner_radius, LB_BOUNDARY_HOLLOW_CONE, M_PI, Constraint_hollow_cone::opening_angle, Constraint_hollow_cone::orientation_x, Constraint_hollow_cone::orientation_y, Constraint_hollow_cone::orientation_z, Constraint_hollow_cone::outer_radius, Constraint_hollow_cone::position_x, Constraint_hollow_cone::position_y, Constraint_hollow_cone::position_z, LB_Boundary::type, and Constraint_hollow_cone::width.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbboundary().
int tclcommand_lbboundary_pore (LB_Boundary * lbb, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 907 of file lb-boundaries_tcl.cpp.
References ARG_IS_S, Constraint_pore::axis, LB_Boundary::c, i, LB_BOUNDARY_POR, Constraint_pore::length, Constraint_pore::outer_rad_left, Constraint_pore::outer_rad_right, LB_Boundary::pore, Constraint_pore::pos, Constraint_pore::rad_left, Constraint_pore::rad_right, Constraint_pore::reflecting, Constraint_pore::smoothing_radius, SQR(), and LB_Boundary::type.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbboundary().
int tclcommand_lbboundary_print_all (Tcl_Interp * interp)
Definition at line 261 of file lb-boundaries_tcl.cpp.
References i, n_lb_boundaries, and tclcommand_printLbBoundaryToResult().
Referenced by tclcommand_lbboundary().
int tclcommand_lbboundary_rhomboid (LB_Boundary * lbb, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 752 of file lb-boundaries_tcl.cpp.
References Constraint_rhomboid::a, LB_Parameters::agrid, ARG_IS_S, Constraint_rhomboid::b, LB_Boundary::c, Constraint_rhomboid::c, Constraint_rhomboid::direction, LATTICE_LB_GPU, lattice_switch, LB_BOUNDARY_RHOMBOID, lbpar, Constraint_rhomboid::pos, LB_Boundary::rhomboid, LB_Parameters::tau, LB_Boundary::type, and LB_Boundary::velocity.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbboundary().
int tclcommand_lbboundary_sphere (LB_Boundary * lbb, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 394 of file lb-boundaries_tcl.cpp.
References ARG_IS_S, LB_Boundary::c, Constraint_sphere::direction, LB_BOUNDARY_SPH, Constraint_sphere::pos, Constraint_sphere::rad, LB_Boundary::sph, and LB_Boundary::type.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbboundary().
int tclcommand_lbboundary_spherocylinder (LB_Boundary * lbb, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 608 of file lb-boundaries_tcl.cpp.
References LB_Parameters::agrid, ARG_IS_S, Constraint_spherocylinder::axis, LB_Boundary::c, Constraint_spherocylinder::direction, i, LATTICE_LB_GPU, lattice_switch, LB_BOUNDARY_SPHEROCYLINDER, lbpar, Constraint_spherocylinder::length, Constraint_spherocylinder::pos, Constraint_spherocylinder::rad, LB_Boundary::spherocyl, SQR(), LB_Parameters::tau, LB_Boundary::type, and LB_Boundary::velocity.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbboundary().
int tclcommand_lbboundary_stomatocyte (LB_Boundary * lbb, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1061 of file lb-boundaries_tcl.cpp.
References ARG_IS_D, ARG_IS_S, LB_Boundary::c, Constraint_stomatocyte::direction, Constraint_stomatocyte::inner_radius, Constraint_stomatocyte::layer_width, LB_BOUNDARY_STOMATOCYTE, M_PI, Constraint_stomatocyte::orientation_x, Constraint_stomatocyte::orientation_y, Constraint_stomatocyte::orientation_z, Constraint_stomatocyte::outer_radius, Constraint_stomatocyte::position_x, Constraint_stomatocyte::position_y, Constraint_stomatocyte::position_z, LB_Boundary::stomatocyte, and LB_Boundary::type.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbboundary().
int tclcommand_lbboundary_wall (LB_Boundary * lbb, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 304 of file lb-boundaries_tcl.cpp.
References LB_Parameters::agrid, ARG_IS_S, LB_Boundary::c, Constraint_wall::d, i, LATTICE_LB_GPU, lattice_switch, LB_BOUNDARY_WAL, lbpar, Constraint_wall::n, norm(), SQR(), LB_Parameters::tau, LB_Boundary::type, LB_Boundary::velocity, and LB_Boundary::wal.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbboundary().
int tclcommand_printLbBoundaryToResult (Tcl_Interp * interp, int i)
Definition at line 47 of file lb-boundaries_tcl.cpp.
References Constraint_rhomboid::a, Constraint_cylinder::axis, Constraint_pore::axis, Constraint_rhomboid::b, LB_Boundary::c, Constraint_rhomboid::c, LB_Boundary::cyl, Constraint_wall::d, Constraint_sphere::direction, Constraint_cylinder::direction, Constraint_rhomboid::direction, Constraint_stomatocyte::direction, Constraint_hollow_cone::direction, LB_Boundary::hollow_cone, i, Constraint_stomatocyte::inner_radius, Constraint_hollow_cone::inner_radius, Constraint_stomatocyte::layer_width, lb_boundaries, LB_BOUNDARY_CYL, LB_BOUNDARY_HOLLOW_CONE, LB_BOUNDARY_POR, LB_BOUNDARY_RHOMBOID, LB_BOUNDARY_SPH, LB_BOUNDARY_SPHEROCYLINDER, LB_BOUNDARY_STOMATOCYTE, LB_BOUNDARY_WAL, Constraint_cylinder::length, Constraint_pore::length, Constraint_wall::n, Constraint_hollow_cone::opening_angle, Constraint_stomatocyte::orientation_x, Constraint_hollow_cone::orientation_x, Constraint_stomatocyte::orientation_y, Constraint_hollow_cone::orientation_y, Constraint_stomatocyte::orientation_z, Constraint_hollow_cone::orientation_z, Constraint_stomatocyte::outer_radius, Constraint_hollow_cone::outer_radius, LB_Boundary::pore, Constraint_sphere::pos, Constraint_cylinder::pos, Constraint_rhomboid::pos, Constraint_pore::pos, Constraint_stomatocyte::position_x, Constraint_hollow_cone::position_x, Constraint_stomatocyte::position_y, Constraint_hollow_cone::position_y, Constraint_stomatocyte::position_z, Constraint_hollow_cone::position_z, Constraint_sphere::rad, Constraint_cylinder::rad, Constraint_pore::rad_left, Constraint_pore::rad_right, LB_Boundary::rhomboid, LB_Boundary::sph, LB_Boundary::stomatocyte, LB_Boundary::type, LB_Boundary::wal, and Constraint_hollow_cone::width.
Referenced by tclcommand_lbboundary(), and tclcommand_lbboundary_print_all().