ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lb.hpp File Reference
lb.hpp File Reference
Header file for lb.cpp.
#include "utils.hpp"
#include "lattice_inline.hpp"
#include "lbgpu.hpp"
Data Structures
struct LB_Model
Some general remarks: This file implements the LB D3Q19 method to Espresso.
struct LB_FluidNode
Data structure for fluid on a local lattice site.
struct LB_Parameters
Data structure holding the parameters for the Lattice Boltzmann system.
Macros
#define D3Q19
Parameter fields for Lattice Boltzmann
The numbers are referenced in mpi_bcast_lb_params to determine what actions have to take place upon change of the respective parameter.
#define LBPAR_DENSITY 0
fluid density
#define LBPAR_VISCOSITY 1
fluid kinematic viscosity
#define LBPAR_AGRID 2
grid constant for fluid lattice
#define LBPAR_TAU 3
time step for fluid propagation
#define LBPAR_FRICTION 4
friction coefficient for viscous coupling between particles and fluid
#define LBPAR_EXTFORCE 5
external force acting on the fluid
#define LBPAR_BULKVISC 6
fluid bulk viscosity
#define LB_COUPLE_NULL 1
Note these are used for binary logic so should be powers of 2.
#define LB_COUPLE_TWO_POINT 2
#define LB_COUPLE_THREE_POINT 4
Functions
Exported Functions
void lattice_boltzmann_update ()
Updates the Lattice Boltzmann system for one time step.
void lb_pre_init ()
(Pre-)initializes data structures.
void lb_init ()
Performs a full initialization of the Lattice Boltzmann system.
void lb_reinit_parameters ()
(Re-)initializes the derived parameters for the Lattice Boltzmann system.
void lb_reinit_fluid ()
(Re-)initializes the fluid.
void lb_reinit_forces ()
Resets the forces on the fluid nodes.
int lb_sanity_checks ()
Checks if all LB parameters are meaningful.
void lb_set_local_fields (LB_FluidNode *node, const double rho, const double *v, const double *pi)
Sets the density and momentum on a local lattice site.
void lb_get_local_fields (LB_FluidNode *node, double *rho, double *j, double *pi)
Returns the mass, momentum and stress of a local lattice site.
void lb_calc_n_from_rho_j_pi (const index_t index, const double rho, const double *j, double *pi)
Calculates the equilibrium distributions.
void lb_propagate ()
Propagates the Lattice Boltzmann system for one time step.
void calc_particle_lattice_ia ()
Calculates the coupling of MD particles to the LB fluid.
int lb_lbfluid_get_interpolated_velocity (double *p, double *v)
calculates the fluid velocity at a given position of the lattice.
void lb_calc_local_fields (index_t index, double *rho, double *j, double *pi)
Calculate the local fluid fields.
void lb_calc_modes (index_t index, double *mode)
Calculation of hydrodynamic modes.
void lb_calc_local_rho (index_t index, double *rho)
Calculate the local fluid density.
void lb_calc_local_j (index_t index, double *j)
Calculate the local fluid momentum.
void lb_calc_local_pi (index_t index, double *pi)
Calculate the local fluid stress.
void lb_local_fields_get_boundary_flag (index_t index, int *boundary)
void lb_get_populations (index_t index, double *pop)
Calculate the local fluid momentum.
void lb_set_populations (index_t index, double *pop)
int lb_lbfluid_set_density (double *p_dens)
int lb_lbfluid_set_visc (double *p_visc)
int lb_lbfluid_set_bulk_visc (double *p_bulk_visc)
int lb_lbfluid_set_gamma_odd (double *p_gamma_odd)
int lb_lbfluid_set_gamma_even (double *p_gamma_even)
int lb_lbfluid_set_friction (double *p_friction)
int lb_lbfluid_set_couple_flag (int couple_flag)
int lb_lbfluid_set_agrid (double p_agrid)
int lb_lbfluid_set_ext_force (int component, double p_fx, double p_fy, double p_fz)
int lb_lbfluid_set_tau (double p_tau)
int lb_lbfluid_set_remove_momentum (void)
int lb_lbfluid_set_shanchen_coupling (double *p_coupling)
int lb_lbfluid_set_mobility (double *p_mobility)
int lb_lbfluid_print_vtk_boundary (char *filename)
int lb_lbfluid_print_vtk_velocity (char *filename)
int lb_lbfluid_print_vtk_density (char **filename)
int lb_lbfluid_print_boundary (char *filename)
int lb_lbfluid_print_velocity (char *filename)
int lb_lbfluid_save_checkpoint (char *filename, int binary)
int lb_lbfluid_load_checkpoint (char *filename, int binary)
int lb_lbnode_get_rho (int *ind, double *p_rho)
int lb_lbnode_get_u (int *ind, double *u)
int lb_lbnode_get_pi (int *ind, double *pi)
int lb_lbnode_get_pi_neq (int *ind, double *pi_neq)
int lb_lbnode_get_boundary (int *ind, int *p_boundary)
int lb_lbnode_get_pop (int *ind, double *pop)
int lb_lbnode_set_rho (int *ind, double *rho)
int lb_lbnode_set_u (int *ind, double *u)
int lb_lbnode_set_pi (int *ind, double *pi)
int lb_lbnode_set_pi_neq (int *ind, double *pi_neq)
int lb_lbnode_set_pop (int *ind, double *pop)
int lb_lbfluid_get_interpolated_velocity_global (double *p, double *v)
calculates the fluid velocity at a given position of the lattice.
Variables
int lb_components
LB_Model lbmodel
The DnQm model to be used.
LB_Parameters lbpar
Struct holding the Lattice Boltzmann parameters.
Lattice lblattice
The underlying lattice.
double ** lbfluid [2]
Pointer to the velocity populations of the fluid.
LB_FluidNode * lbfields
Pointer to the hydrodynamic fields of the fluid.
int transfer_momentum
Switch indicating momentum exchange between particles and fluid.
double lblambda
Eigenvalue of collision operator corresponding to shear viscosity.
double lblambda_bulk
Eigenvalue of collision operator corresponding to bulk viscosity.
int resend_halo
double gamma_shear
relaxation rate of shear modes
double gamma_bulk
relaxation rate of bulk modes
Detailed Description
Header file for lb.cpp.
This is the header file for the Lattice Boltzmann implementation in lb.cpp
Definition in file lb.hpp.
Macro Definition Documentation
#define D3Q19
Definition at line 41 of file lb.hpp.
#define LB_COUPLE_NULL 1
Note these are used for binary logic so should be powers of 2.
Definition at line 57 of file lb.hpp.
#define LB_COUPLE_THREE_POINT 4
Definition at line 59 of file lb.hpp.
Referenced by lb_lbfluid_set_couple_flag(), and tclcommand_lbfluid().
#define LB_COUPLE_TWO_POINT 2
Definition at line 58 of file lb.hpp.
Referenced by lb_calc_particle_lattice_ia_gpu(), lb_lbfluid_set_couple_flag(), and tclcommand_lbfluid().
#define LBPAR_AGRID 2
grid constant for fluid lattice
Definition at line 50 of file lb.hpp.
Referenced by lb_lbfluid_set_agrid(), on_lb_params_change(), and on_lb_params_change_gpu().
#define LBPAR_BULKVISC 6
fluid bulk viscosity
Definition at line 54 of file lb.hpp.
Referenced by lb_lbfluid_set_bulk_visc().
#define LBPAR_DENSITY 0
fluid density
Definition at line 48 of file lb.hpp.
Referenced by lb_lbfluid_set_density(), on_lb_params_change(), and on_lb_params_change_gpu().
#define LBPAR_EXTFORCE 5
external force acting on the fluid
Definition at line 53 of file lb.hpp.
Referenced by lb_lbfluid_set_ext_force().
#define LBPAR_FRICTION 4
friction coefficient for viscous coupling between particles and fluid
Definition at line 52 of file lb.hpp.
Referenced by lb_lbfluid_set_friction().
#define LBPAR_TAU 3
time step for fluid propagation
Definition at line 51 of file lb.hpp.
#define LBPAR_VISCOSITY 1
fluid kinematic viscosity
Definition at line 49 of file lb.hpp.
Referenced by lb_lbfluid_set_visc().
Function Documentation
void calc_particle_lattice_ia ()
Calculates the coupling of MD particles to the LB fluid.
This function is called from force_calc. The force is added to the particle force and the corresponding momentum exchange is applied to the fluid. Note that this function changes the state of the fluid!
Calculates the coupling of MD particles to the LB fluid.
So far, only viscous coupling with Stokesian friction is implemented. Include all particle-lattice forces in this function. The function is called from force_calc.
Parallelizing the fluid particle coupling is not straightforward because drawing of random numbers makes the whole thing nonlocal. One way to do it is to treat every particle only on one node, i.e. the random numbers need not be communicated. The particles that are not fully inside the local lattice are taken into account via their ghost images on the neighbouring nodes. But this requires that the correct values of the surrounding lattice nodes are available on the respective node, which means that we have to communicate the halo regions before treating the ghost particles. Moreover, after determining the ghost couplings, we have to communicate back the halo region such that all local lattice nodes have the correct values. Thus two communication phases are involved which will most likely be the bottleneck of the computation.
Another way of dealing with the particle lattice coupling is to treat a particle and all of it's images explicitly. This requires the communication of the random numbers used in the calculation of the coupling force. The problem is now that, if random numbers have to be redrawn, we cannot efficiently determine which particles and which images have to be re-calculated. We therefore go back to the outset and go through the whole system again until no failure occurs during such a sweep. In the worst case, this is very inefficient because many things are recalculated although they actually don't need. But we can assume that this happens extremely rarely and then we have on average only one communication phase for the random numbers, which probably makes this method preferable compared to the above one.
Definition at line 3125 of file lb.cpp.
References Lattice::agrid, CellPList::cell, cell_structure, check_id, d_random(), ParticleForce::f, Particle::f, ParticleLatticeCoupling::f_random, gaussian_random(), gaussian_random_cut(), ghost_cells, ghost_communicator(), CellStructure::ghost_lbcoupling_comm, CellStructure::ghost_swimming_comm, halo_communication(), Lattice::halo_grid_volume, i, ParticleProperties::identity, ifParticleIsVirtual(), lb_check_halo_regions(), lb_coupl_pref, lb_coupl_pref2, lb_viscous_coupling(), lbfluid, Particle::lc, local_cells, my_left, my_right, CellPList::n, ParticleList::n, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, rancounter, LB_Parameters::resend_halo, and transfer_momentum.
Referenced by force_calc().
void lattice_boltzmann_update ()
Updates the Lattice Boltzmann system for one time step.
This function performs the collision step and the streaming step. If external forces are present, they are applied prior to the collisions. If boundaries are present, it also applies the boundary conditions.
Updates the Lattice Boltzmann system for one time step.
This function is called from the integrator. Since the time step for the lattice dynamics can be coarser than the MD time step, we monitor the time since the last lattice update.
Definition at line 2784 of file lb.cpp.
References fluidstep, lb_collide_stream(), lb_stream_collide(), LB_Parameters::tau, and time_step.
Referenced by integrate_sd(), and integrate_vv().
void lb_calc_local_fields (index_t index, double * rho, double * j, double * pi) inline
Calculate the local fluid fields.
The calculation is implemented explicitly for the special case of D3Q19.
Parameters
index Index of the local lattice site.
rho local fluid density
j local fluid speed
pi local fluid pressure
Definition at line 398 of file lb.hpp.
References LB_Parameters::agrid, boundary, LB_FluidNode::force, gamma_bulk, gamma_shear, LATTICE_LB, lattice_switch, lb_calc_modes(), LB_Parameters::rho, runtimeError, scalar(), and SQR().
Referenced by lb_calc_fluid_temp(), lb_calc_local_pi(), lb_calc_velprof(), mpi_recv_fluid(), and mpi_recv_fluid_slave().
void lb_calc_local_j (index_t index, double * j) inline
Calculate the local fluid momentum.
The calculation is implemented explicitly for the special case of D3Q19.
Parameters
index The local lattice site (Input).
j local fluid speed
Definition at line 338 of file lb.hpp.
References LATTICE_LB, lattice_switch, lbfluid, and runtimeError.
Referenced by lb_calc_fluid_momentum().
void lb_calc_local_pi (index_t index, double * pi) inline
Calculate the local fluid stress.
The calculation is implemented explicitly for the special case of D3Q19.
Parameters
index The local lattice site (Input).
pi local fluid pressure
Definition at line 374 of file lb.hpp.
References LATTICE_LB, lattice_switch, lb_calc_local_fields(), and runtimeError.
void lb_calc_local_rho (index_t index, double * rho) inline
Calculate the local fluid density.
The calculation is implemented explicitly for the special case of D3Q19.
Parameters
index the local lattice site (Input).
rho local fluid density
Definition at line 302 of file lb.hpp.
References LB_Parameters::agrid, LATTICE_LB, lattice_switch, lbfluid, LB_Parameters::rho, and runtimeError.
Referenced by lb_calc_average_rho(), lb_calc_densprof(), and lb_calc_fluid_mass().
void lb_calc_modes (index_t index, double * mode)
Calculation of hydrodynamic modes.
Parameters
index number of the node to calculate the modes for
mode output pointer to a double[19]
Definition at line 2105 of file lb.cpp.
References LB_Model::e, i, lbfluid, and LB_Model::n_veloc.
Referenced by GetIBMInterpolatedVelocity(), lb_bounce_back(), lb_calc_local_fields(), lb_collide_stream(), and lb_lbfluid_get_interpolated_velocity().
void lb_calc_n_from_rho_j_pi (const index_t index, const double rho, const double * j, double * pi)
Calculates the equilibrium distributions.
Parameters
index Index of the local site
rho local fluid density
j local fluid speed
pi local fluid pressure
Definition at line 2018 of file lb.cpp.
References LB_Parameters::agrid, LB_Model::c, LB_Model::coeff, i, lbfluid, LB_Model::n_veloc, LB_Parameters::rho, scalar(), and SQR().
Referenced by lb_reinit_fluid(), mpi_send_fluid(), and mpi_send_fluid_slave().
void lb_get_local_fields (LB_FluidNode * node, double * rho, double * j, double * pi)
Returns the mass, momentum and stress of a local lattice site.
Parameters
node The index of the lattice site within the local domain (Input)
rho Local density of the fluid (Output)
j Local momentum of the fluid (Output)
pi Local stress tensor of the fluid (Output)
void lb_get_populations (index_t index, double * pop) inline
Calculate the local fluid momentum.
The calculation is implemented explicitly for the special case of D3Q19.
Parameters
index The local lattice site (Input).
pop fluid population
Definition at line 501 of file lb.hpp.
References LB_Model::coeff, i, lbfluid, and LB_Parameters::rho.
Referenced by mpi_recv_fluid_populations(), and mpi_recv_fluid_populations_slave().
void lb_init ()
Performs a full initialization of the Lattice Boltzmann system.
All derived parameters and the fluid are reset to their default values.
Definition at line 1958 of file lb.cpp.
References LB_Parameters::agrid, check_runtime_errors(), i, Lattice::init(), lb_prepare_communication(), lb_realloc_fluid(), lb_reinit_fluid(), lb_reinit_forces(), lb_reinit_parameters(), LB_TRACE, and runtimeError.
Referenced by on_boxl_change(), on_cell_structure_change(), and on_lb_params_change().
int lb_lbfluid_get_interpolated_velocity (double * p, double * v)
calculates the fluid velocity at a given position of the lattice.
Note that it can lead to undefined behaviour if the position is not within the local lattice.
Definition at line 2990 of file lb.cpp.
References LB_Parameters::agrid, boundary, LB_FluidNode::boundary, index_t, lb_boundaries, lb_calc_modes(), lbboundary_mindist_position(), Lattice::map_position_to_lattice(), LB_Parameters::rho, LB_Parameters::tau, and LB_Boundary::velocity.
Referenced by lb_viscous_coupling(), mpi_observable_lb_radial_velocity_profile_parallel(), and observable_calc_lb_velocity_profile().
int lb_lbfluid_get_interpolated_velocity_global (double * p, double * v)
calculates the fluid velocity at a given position of the lattice.
Note that it can lead to undefined behaviour if the position is not within the local lattice. This version of the function can be called without the position needing to be on the local processor
Note that it can lead to undefined behavior if the position is not within the local lattice. This version of the function can be called without the position needing to be on the local processor. Note that this gives a slightly different version than the values used to couple to MD beads when near a wall, see lb_lbfluid_get_interpolated_velocity.
Definition at line 1127 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, errexit(), LATTICE_LB_GPU, lattice_switch, lb_lbnode_get_u(), lbpar_gpu, and Lattice::map_position_to_lattice_global().
Referenced by tclcommand_lbfluid_print_interpolated_velocity().
int lb_lbfluid_load_checkpoint (char * filename, int binary)
Definition at line 954 of file lb.cpp.
References LB_Parameters::agrid, box_l, ES_ERROR, ES_OK, free, i, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, lb_lbnode_set_pop(), lb_load_checkpoint_GPU(), lbpar_gpu, malloc, mpi_bcast_lb_params(), LB_parameters_gpu::number_of_nodes, LB_Parameters::resend_halo, and runtimeError.
Referenced by lb_lbfluid_load_checkpoint_wrapper(), and tclcommand_lbfluid().
int lb_lbfluid_print_boundary (char * filename)
print of the calculated phys values
Definition at line 744 of file lb.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, boundary, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, free, LATTICE_LB_GPU, lattice_switch, lb_get_boundary_flags_GPU(), lb_lbnode_get_boundary(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_print_velocity (char * filename)
print of the calculated phys values
Definition at line 804 of file lb.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, errexit(), free, host_values, LATTICE_LB_GPU, lattice_switch, lb_get_values_GPU(), lb_lbnode_get_u(), lbpar_gpu, malloc, LB_parameters_gpu::number_of_nodes, and LB_rho_v_pi_gpu::v.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_print_vtk_boundary (char * filename)
print of the calculated phys values
print of the calculated phys values
Definition at line 569 of file lb.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, LB_Parameters::agrid, boundary, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, free, LATTICE_LB_GPU, lattice_switch, lb_get_boundary_flags_GPU(), lb_lbnode_get_boundary(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbfluid().
int lb_lbfluid_print_vtk_density (char ** filename)
print the calculated phys values
Definition at line 635 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, errexit(), free, host_values, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lb_get_values_GPU(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_print_vtk_velocity (char * filename)
print of the calculated phys values
Definition at line 679 of file lb.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, LB_Parameters::agrid, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, free, host_values, LATTICE_LB_GPU, lattice_switch, lb_get_values_GPU(), lb_lbnode_get_u(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_save_checkpoint (char * filename, int binary)
Definition at line 870 of file lb.cpp.
References LB_Parameters::agrid, box_l, ES_ERROR, ES_OK, free, i, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, lb_lbnode_get_pop(), lb_save_checkpoint_GPU(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by lb_lbfluid_save_checkpoint_wrapper(), and tclcommand_lbfluid().
int lb_lbfluid_set_agrid (double p_agrid)
Definition at line 356 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, LATTICE_LB_GPU, lattice_switch, LBPAR_AGRID, lbpar_gpu, mpi_bcast_lb_params(), LB_parameters_gpu::number_of_nodes, on_lb_params_change_gpu(), ROUND_ERROR_PREC, and runtimeError.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_bulk_visc (double * p_bulk_visc)
Definition at line 257 of file lb.cpp.
References LB_parameters_gpu::bulk_viscosity, LB_Parameters::bulk_viscosity, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, LBPAR_BULKVISC, lbpar_gpu, mpi_bcast_lb_params(), and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_couple_flag (int couple_flag)
Definition at line 337 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, LB_parameters_gpu::lb_couple_switch, LB_COUPLE_THREE_POINT, LB_COUPLE_TWO_POINT, and lbpar_gpu.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_density (double * p_dens)
Definition at line 219 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, LBPAR_DENSITY, lbpar_gpu, mpi_bcast_lb_params(), on_lb_params_change_gpu(), LB_parameters_gpu::rho, and LB_Parameters::rho.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_ext_force (int component, double p_fx, double p_fy, double p_fz)
Definition at line 428 of file lb.cpp.
References LB_parameters_gpu::ext_force, LB_Parameters::ext_force, LB_parameters_gpu::external_force, LATTICE_LB_GPU, lattice_switch, lb_reinit_extern_nodeforce_GPU(), LBPAR_EXTFORCE, lbpar_gpu, mpi_bcast_lb_params(), LB_parameters_gpu::rho, LB_Parameters::rho, LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_friction (double * p_friction)
Definition at line 316 of file lb.cpp.
References LB_parameters_gpu::friction, LB_Parameters::friction, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, LBPAR_FRICTION, lbpar_gpu, mpi_bcast_lb_params(), and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_gamma_even (double * p_gamma_even)
Definition at line 295 of file lb.cpp.
References LB_parameters_gpu::gamma_even, gamma_even, LB_Parameters::gamma_even, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lbpar_gpu, mpi_bcast_lb_params(), and on_lb_params_change_gpu().
int lb_lbfluid_set_gamma_odd (double * p_gamma_odd)
Definition at line 276 of file lb.cpp.
References LB_parameters_gpu::gamma_odd, gamma_odd, LB_Parameters::gamma_odd, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lbpar_gpu, mpi_bcast_lb_params(), and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_mobility (double * p_mobility)
Definition at line 179 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lbpar_gpu, LBPAR_MOBILITY, LB_parameters_gpu::mobility, and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_remove_momentum (void)
Definition at line 412 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, lbpar_gpu, on_lb_params_change_gpu(), and LB_parameters_gpu::remove_momentum.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_shanchen_coupling (double * p_coupling)
Definition at line 151 of file lb.cpp.
References LB_parameters_gpu::coupling, LB_COMPONENTS, LBPAR_COUPLING, lbpar_gpu, and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_tau (double p_tau)
Definition at line 393 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, lbpar_gpu, mpi_bcast_lb_params(), on_lb_params_change_gpu(), LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_visc (double * p_visc)
Definition at line 238 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lbpar_gpu, LBPAR_VISCOSITY, mpi_bcast_lb_params(), on_lb_params_change_gpu(), LB_parameters_gpu::viscosity, and LB_Parameters::viscosity.
Referenced by tclcommand_lbfluid().
int lb_lbnode_get_boundary (int * ind, int * p_boundary)
Definition at line 1254 of file lb.cpp.
References LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, lb_get_boundary_flag_GPU(), lbpar_gpu, Lattice::map_lattice_to_node(), and mpi_recv_fluid_boundary_flag().
Referenced by lb_lbfluid_print_boundary(), lb_lbfluid_print_vtk_boundary(), and tclcommand_lbnode().
int lb_lbnode_get_pi (int * ind, double * pi)
Definition at line 1192 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lb_lbnode_get_pi_neq(), lbpar_gpu, LB_parameters_gpu::rho, LB_Parameters::rho, LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by tclcommand_lbnode().
int lb_lbnode_get_pi_neq (int * ind, double * pi_neq)
Definition at line 1217 of file lb.cpp.
References LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, i, index_t, LATTICE_LB_GPU, lattice_switch, lb_print_node_GPU(), lbpar_gpu, malloc, Lattice::map_lattice_to_node(), mpi_recv_fluid(), LB_rho_v_pi_gpu::pi, and LB_Parameters::tau.
Referenced by lb_lbnode_get_pi(), and tclcommand_lbnode().
int lb_lbnode_get_pop (int * ind, double * pop)
Definition at line 1279 of file lb.cpp.
References get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, Lattice::map_lattice_to_node(), and mpi_recv_fluid_populations().
Referenced by lb_lbfluid_save_checkpoint(), and tclcommand_lbnode().
int lb_lbnode_get_rho (int * ind, double * p_rho)
Definition at line 1054 of file lb.cpp.
References LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lb_print_node_GPU(), lbpar_gpu, malloc, Lattice::map_lattice_to_node(), mpi_recv_fluid(), and LB_rho_v_pi_gpu::rho.
Referenced by tclcommand_lbnode().
int lb_lbnode_get_u (int * ind, double * u)
Definition at line 1086 of file lb.cpp.
References LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, lb_print_node_GPU(), lbpar_gpu, malloc, Lattice::map_lattice_to_node(), mpi_recv_fluid(), and LB_Parameters::tau.
Referenced by lb_lbfluid_get_interpolated_velocity_global(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_velocity(), and tclcommand_lbnode().
int lb_lbnode_set_pi (int * ind, double * pi)
Definition at line 1363 of file lb.cpp.
int lb_lbnode_set_pi_neq (int * ind, double * pi_neq)
Definition at line 1368 of file lb.cpp.
int lb_lbnode_set_pop (int * ind, double * pop)
Definition at line 1373 of file lb.cpp.
References get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, Lattice::map_lattice_to_node(), and mpi_send_fluid_populations().
Referenced by lb_lbfluid_load_checkpoint(), and tclcommand_lbnode().
int lb_lbnode_set_rho (int * ind, double * rho)
Definition at line 1297 of file lb.cpp.
References LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, i, index_t, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lb_set_node_rho_GPU(), lbpar_gpu, Lattice::map_lattice_to_node(), mpi_recv_fluid(), and mpi_send_fluid().
Referenced by tclcommand_lbnode().
int lb_lbnode_set_u (int * ind, double * u)
Definition at line 1330 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, lb_set_node_velocity_GPU(), lbpar_gpu, Lattice::map_lattice_to_node(), mpi_recv_fluid(), mpi_send_fluid(), LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by tclcommand_lbnode().
void lb_local_fields_get_boundary_flag (index_t index, int * boundary) inline
Definition at line 482 of file lb.hpp.
References LB_FluidNode::boundary, LATTICE_LB, lattice_switch, and runtimeError.
Referenced by mpi_recv_fluid_boundary_flag(), and mpi_recv_fluid_boundary_flag_slave().
void lb_pre_init ()
(Pre-)initializes data structures.
(Pre-)initializes data structures.
Definition at line 1763 of file lb.cpp.
References Lattice::halo_grid_volume, lbfluid, malloc, and LB_Model::n_veloc.
Referenced by on_program_start().
void lb_propagate ()
Propagates the Lattice Boltzmann system for one time step.
This function performs the collision step and the streaming step. If external forces are present, they are applied prior to the collisions. If boundaries are present, it also applies the boundary conditions.
void lb_reinit_fluid ()
(Re-)initializes the fluid.
(Re-)initializes the fluid.
Definition at line 1928 of file lb.cpp.
References LB_Parameters::agrid, LB_FluidNode::boundary, Lattice::halo_grid_volume, index_t, lb_calc_n_from_rho_j_pi(), lb_init_boundaries(), LB_TRACE, LB_FluidNode::recalc_fields, LB_Parameters::resend_halo, and LB_Parameters::rho.
Referenced by lb_init(), and on_lb_params_change().
void lb_reinit_forces ()
Resets the forces on the fluid nodes.
Definition at line 1903 of file lb.cpp.
References LB_Parameters::agrid, LB_Parameters::ext_force, LB_Boundary::force, LB_FluidNode::force, Lattice::halo_grid_volume, LB_FluidNode::has_force, i, index_t, lb_boundaries, n_lb_boundaries, and LB_Parameters::tau.
Referenced by lb_init().
void lb_reinit_parameters ()
(Re-)initializes the derived parameters for the Lattice Boltzmann system.
The current state of the fluid is unchanged.
(Re-)initializes the derived parameters for the Lattice Boltzmann system.
Definition at line 1841 of file lb.cpp.
References LB_Parameters::agrid, LB_Parameters::bulk_viscosity, LB_Model::c_sound_sq, d3q19_modebase, LB_Model::e, fluct, LB_Parameters::friction, gamma_bulk, gamma_even, LB_Parameters::gamma_even, gamma_odd, LB_Parameters::gamma_odd, gamma_shear, i, lb_coupl_pref, lb_coupl_pref2, lb_phi, LB_TRACE, LB_Model::n_veloc, SQR(), LB_Parameters::tau, temperature, this_node, time_step, and LB_Parameters::viscosity.
Referenced by lb_init(), on_lb_params_change(), on_parameter_change(), and on_temperature_change().
int lb_sanity_checks ()
Checks if all LB parameters are meaningful.
Checks if all LB parameters are meaningful.
Definition at line 1705 of file lb.cpp.
References LB_Parameters::agrid, cell_structure, CELL_STRUCTURE_DOMDEC, dd, LB_Parameters::rho, runtimeError, skin, LB_Parameters::tau, THERMO_LB, thermo_switch, CellStructure::type, DomainDecomposition::use_vList, and LB_Parameters::viscosity.
Referenced by on_integration_start().
void lb_set_local_fields (LB_FluidNode * node, const double rho, const double * v, const double * pi)
Sets the density and momentum on a local lattice site.
Parameters
node Pointer to the Node of the lattice site within the local domain (Input)
rho Local density of the fluid (Input)
v Local momentum of the fluid (Input)
pi Local pressure of the fluid (Input)
void lb_set_populations (index_t index, double * pop) inline
Definition at line 508 of file lb.hpp.
References LB_Model::coeff, i, lbfluid, and LB_Parameters::rho.
Referenced by mpi_send_fluid_populations(), and mpi_send_fluid_populations_slave().
Variable Documentation
double gamma_bulk
relaxation rate of bulk modes
Definition at line 119 of file lb.cpp.
Referenced by lb_apply_forces(), lb_calc_local_fields(), lb_reinit_parameters(), and lb_relax_modes().
double gamma_shear
relaxation rate of shear modes
Definition at line 117 of file lb.cpp.
Referenced by lb_apply_forces(), lb_calc_local_fields(), lb_reinit_parameters(), and lb_relax_modes().
int lb_components
Definition at line 47 of file lb.cpp.
LB_FluidNode* lbfields
Pointer to the hydrodynamic fields of the fluid.
Pointer to the hydrodynamic fields of the fluid.
Definition at line 106 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), IBM_ResetLBForces_CPU(), lb_bounce_back(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), and lb_init_boundaries().
double** lbfluid[2]
Pointer to the velocity populations of the fluid.
lbfluid[0] contains pre-collision populations, lbfluid[1] contains post-collision populations
Pointer to the velocity populations of the fluid.
Definition at line 103 of file lb.cpp.
Referenced by calc_particle_lattice_ia(), halo_push_communication(), lb_bounce_back(), lb_calc_local_j(), lb_calc_local_rho(), lb_calc_modes(), lb_calc_n_from_modes(), lb_calc_n_from_modes_push(), lb_calc_n_from_rho_j_pi(), lb_check_halo_regions(), lb_collide_stream(), lb_get_populations(), lb_pre_init(), lb_pull_calc_modes(), lb_realloc_fluid(), lb_release_fluid(), lb_set_populations(), lb_stream_collide(), ParticleVelocitiesFromLB_CPU(), and tclcommand_lbnode().
double lblambda
Eigenvalue of collision operator corresponding to shear viscosity.
double lblambda_bulk
Eigenvalue of collision operator corresponding to bulk viscosity.
Lattice lblattice
The underlying lattice.
The underlying lattice.
Definition at line 100 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), IBM_ForcesIntoFluid_CPU(), IBM_ResetLBForces_CPU(), IsHalo(), lb_bounce_back(), lb_calc_densprof(), lb_calc_fluid_mass(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_calc_velprof(), lb_init_boundaries(), ParticleVelocitiesFromLB_CPU(), tclcommand_analyze_fluid_parse_densprof(), and tclcommand_analyze_fluid_parse_velprof().
LB_Model lbmodel
The DnQm model to be used.
Definition at line 86 of file lb.cpp.
Referenced by lb_bounce_back().
LB_Parameters lbpar
Struct holding the Lattice Boltzmann parameters.
Definition at line 60 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), IBM_ForcesIntoFluid_CPU(), IBM_ResetLBForces_CPU(), lb_bounce_back(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_calc_velprof(), lbboundary_get_force(), mpi_bcast_lb_params_slave(), mpi_observable_lb_radial_velocity_profile_parallel(), mpi_recv_fluid_populations(), mpi_recv_fluid_populations_slave(), observable_calc_lb_velocity_profile(), ParticleVelocitiesFromLB_CPU(), tclcallback_time_step(), tclcommand_analyze_fluid_parse_densprof(), tclcommand_analyze_fluid_parse_velprof(), tclcommand_lbboundary_cylinder(), tclcommand_lbboundary_rhomboid(), tclcommand_lbboundary_spherocylinder(), tclcommand_lbboundary_wall(), and tclcommand_lbnode().
int resend_halo
int transfer_momentum
Switch indicating momentum exchange between particles and fluid.
Switch indicating momentum exchange between particles and fluid.
Definition at line 56 of file lb.cpp.
Referenced by calc_particle_lattice_ia(), integrate_sd(), and integrate_vv().