ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lb.cpp File Reference
lb.cpp File Reference
Lattice Boltzmann algorithm for hydrodynamic degrees of freedom.
#include <mpi.h>
#include <cstdio>
#include "utils.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "domain_decomposition.hpp"
#include "interaction_data.hpp"
#include "thermostat.hpp"
#include "halo.hpp"
#include "lb-d3q19.hpp"
#include "lb-boundaries.hpp"
#include "lb.hpp"
#include "immersed_boundary/ibm_main.hpp"
#include "cuda_interface.hpp"
Functions
static void lb_check_halo_regions ()
Checks consistency of the halo regions (ADDITIONAL_CHECKS) This function can be used as an additional check.
int lb_lbfluid_set_shanchen_coupling (double *p_coupling)
int lb_lbfluid_set_mobility (double *p_mobility)
int affinity_set_params (int part_type_a, int part_type_b, double *affinity)
int lb_lbfluid_set_density (double *p_dens)
int lb_lbfluid_set_visc (double *p_visc)
int lb_lbfluid_set_bulk_visc (double *p_bulk_visc)
int lb_lbfluid_set_gamma_odd (double *p_gamma_odd)
int lb_lbfluid_set_gamma_even (double *p_gamma_even)
int lb_lbfluid_set_friction (double *p_friction)
int lb_lbfluid_set_couple_flag (int couple_flag)
int lb_lbfluid_set_agrid (double p_agrid)
int lb_lbfluid_set_tau (double p_tau)
int lb_lbfluid_set_remove_momentum (void)
int lb_lbfluid_set_ext_force (int component, double p_fx, double p_fy, double p_fz)
int lb_lbfluid_get_density (double *p_dens)
int lb_lbfluid_get_visc (double *p_visc)
int lb_lbfluid_get_bulk_visc (double *p_bulk_visc)
int lb_lbfluid_get_gamma_odd (double *p_gamma_odd)
int lb_lbfluid_get_gamma_even (double *p_gamma_even)
int lb_lbfluid_get_agrid (double *p_agrid)
int lb_lbfluid_get_ext_force (double *p_fx, double *p_fy, double *p_fz)
int lb_lbfluid_print_vtk_boundary (char *filename)
int lb_lbfluid_print_vtk_density (char **filename)
int lb_lbfluid_print_vtk_velocity (char *filename)
int lb_lbfluid_print_boundary (char *filename)
int lb_lbfluid_print_velocity (char *filename)
int lb_lbfluid_save_checkpoint (char *filename, int binary)
int lb_lbfluid_load_checkpoint (char *filename, int binary)
int lb_lbnode_get_rho (int *ind, double *p_rho)
int lb_lbnode_get_u (int *ind, double *p_u)
int lb_lbfluid_get_interpolated_velocity_global (double *p, double *v)
calculates the fluid velocity at a given position of the lattice.
int lb_lbnode_get_pi (int *ind, double *p_pi)
int lb_lbnode_get_pi_neq (int *ind, double *p_pi)
int lb_lbnode_get_boundary (int *ind, int *p_boundary)
int lb_lbnode_get_pop (int *ind, double *p_pop)
int lb_lbnode_set_rho (int *ind, double *p_rho)
int lb_lbnode_set_u (int *ind, double *u)
int lb_lbnode_set_pi (int *ind, double *pi)
int lb_lbnode_set_pi_neq (int *ind, double *pi_neq)
int lb_lbnode_set_pop (int *ind, double *p_pop)
int lb_lbnode_set_extforce (int *ind, double *f)
static void halo_push_communication ()
int lb_sanity_checks ()
Performs basic sanity checks.
void lb_pre_init ()
(Pre-)allocate memory for data structures
static void lb_realloc_fluid ()
(Re-)allocate memory for the fluid and initialize pointers.
static void lb_prepare_communication ()
Sets up the structures for exchange of the halo regions.
void lb_reinit_parameters ()
(Re-)initializes the fluid.
void lb_reinit_forces ()
Resets the forces on the fluid nodes.
void lb_reinit_fluid ()
(Re-)initializes the fluid according to the given value of rho.
void lb_init ()
Performs a full initialization of the Lattice Boltzmann system.
void lb_release_fluid ()
Release the fluid.
void lb_release ()
Release fluid and communication.
void lb_calc_modes (index_t index, double *mode)
Calculation of hydrodynamic modes.
void lb_pull_calc_modes (index_t index, double *mode)
Streaming and calculation of modes (pull scheme)
void lb_relax_modes (index_t index, double *mode)
void lb_thermalize_modes (index_t index, double *mode)
void lb_apply_forces (index_t index, double *mode)
void lb_calc_n_from_modes (index_t index, double *mode)
void lb_calc_n_from_modes_push (index_t index, double *m)
void lb_collide_stream ()
void lb_stream_collide ()
Streaming and collisions (pull scheme)
void lattice_boltzmann_update ()
Update the lattice Boltzmann fluid.
static int compare_buffers (double *buf1, double *buf2, int size)
Mapping between hydrodynamic fields and particle populations
void lb_calc_n_from_rho_j_pi (const index_t index, const double rho, const double *j, double *pi)
Calculates the equilibrium distributions.
Coupling part
void lb_viscous_coupling (Particle *p, double force[3])
Coupling of a single particle to viscous fluid with Stokesian friction.
int lb_lbfluid_get_interpolated_velocity (double *p, double *v)
calculates the fluid velocity at a given position of the lattice.
void calc_particle_lattice_ia ()
Calculate particle lattice interactions.
void lb_calc_average_rho ()
Calculate the average density of the fluid in the system.
Variables
int lb_components = LB_COMPONENTS
int transfer_momentum = 0
Flag indicating momentum exchange between particles and fluid.
LB_Parameters lbpar
Struct holding the Lattice Boltzmann parameters.
LB_Model lbmodel = { 19, d3q19_lattice, d3q19_coefficients, d3q19_w, NULL, 1./3. }
The DnQm model to be used.
Lattice lblattice
The underlying lattice structure.
double ** lbfluid [2] = { NULL, NULL }
Pointer to the velocity populations of the fluid nodes.
LB_FluidNode * lbfields = NULL
Pointer to the hydrodynamic fields of the fluid nodes.
HaloCommunicator update_halo_comm = { 0, NULL }
Communicator for halo exchange between processors.
static double fluidstep =0.0
measures the MD time since the last fluid update
static int rancounter =0
counts the random numbers drawn for fluctuating LB and the coupling
static int failcounter =0
counts the occurences of negative populations due to fluctuations
Derived parameters
static int fluct
Flag indicating whether fluctuations are present.
double gamma_shear = 0.0
relaxation rate of shear modes
double gamma_bulk = 0.0
relaxation rate of bulk modes
static double gamma_odd = 0.0
relaxation of the odd kinetic modes
static double gamma_even = 0.0
relaxation of the even kinetic modes
static double lb_phi [19]
amplitudes of the fluctuations of the modes
static double lb_coupl_pref = 0.0
amplitude of the fluctuations in the viscous coupling
static double lb_coupl_pref2 = 0.0
amplitude of the fluctuations in the viscous coupling with gaussian random numbers
Detailed Description
Lattice Boltzmann algorithm for hydrodynamic degrees of freedom.
Includes fluctuating LB and coupling to MD particles via frictional momentum transfer.
Definition in file lb.cpp.
Function Documentation
int affinity_set_params (int part_type_a, int part_type_b, double * affinity)
Definition at line 200 of file lb.cpp.
References IA_parameters::affinity, IA_parameters::affinity_on, ES_ERROR, ES_OK, get_ia_param_safe(), LB_COMPONENTS, and mpi_bcast_ia_params().
Referenced by tclcommand_inter_parse_affinity().
void calc_particle_lattice_ia ()
Calculate particle lattice interactions.
Calculates the coupling of MD particles to the LB fluid.
So far, only viscous coupling with Stokesian friction is implemented. Include all particle-lattice forces in this function. The function is called from force_calc.
Parallelizing the fluid particle coupling is not straightforward because drawing of random numbers makes the whole thing nonlocal. One way to do it is to treat every particle only on one node, i.e. the random numbers need not be communicated. The particles that are not fully inside the local lattice are taken into account via their ghost images on the neighbouring nodes. But this requires that the correct values of the surrounding lattice nodes are available on the respective node, which means that we have to communicate the halo regions before treating the ghost particles. Moreover, after determining the ghost couplings, we have to communicate back the halo region such that all local lattice nodes have the correct values. Thus two communication phases are involved which will most likely be the bottleneck of the computation.
Another way of dealing with the particle lattice coupling is to treat a particle and all of it's images explicitly. This requires the communication of the random numbers used in the calculation of the coupling force. The problem is now that, if random numbers have to be redrawn, we cannot efficiently determine which particles and which images have to be re-calculated. We therefore go back to the outset and go through the whole system again until no failure occurs during such a sweep. In the worst case, this is very inefficient because many things are recalculated although they actually don't need. But we can assume that this happens extremely rarely and then we have on average only one communication phase for the random numbers, which probably makes this method preferable compared to the above one.
Definition at line 3125 of file lb.cpp.
References Lattice::agrid, CellPList::cell, cell_structure, check_id, d_random(), ParticleForce::f, Particle::f, ParticleLatticeCoupling::f_random, gaussian_random(), gaussian_random_cut(), ghost_cells, ghost_communicator(), CellStructure::ghost_lbcoupling_comm, CellStructure::ghost_swimming_comm, halo_communication(), Lattice::halo_grid_volume, i, ParticleProperties::identity, ifParticleIsVirtual(), lb_check_halo_regions(), lb_coupl_pref, lb_coupl_pref2, lb_viscous_coupling(), lbfluid, Particle::lc, local_cells, my_left, my_right, CellPList::n, ParticleList::n, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, rancounter, LB_Parameters::resend_halo, and transfer_momentum.
Referenced by force_calc().
static int compare_buffers (double * buf1, double * buf2, int size) static
Definition at line 3295 of file lb.cpp.
References runtimeError.
Referenced by lb_check_halo_regions().
static void halo_push_communication () static
Definition at line 1399 of file lb.cpp.
References comm_cart, free, get_linear_index(), Lattice::grid, Lattice::halo_grid, index_t, lbfluid, malloc, MPI_DOUBLE, MPI_Sendrecv(), node_grid, node_neighbors, realloc, and REQ_HALO_SPREAD.
Referenced by lb_collide_stream().
void lattice_boltzmann_update ()
Update the lattice Boltzmann fluid.
Updates the Lattice Boltzmann system for one time step.
This function is called from the integrator. Since the time step for the lattice dynamics can be coarser than the MD time step, we monitor the time since the last lattice update.
Definition at line 2784 of file lb.cpp.
References fluidstep, lb_collide_stream(), lb_stream_collide(), LB_Parameters::tau, and time_step.
Referenced by integrate_sd(), and integrate_vv().
void lb_apply_forces (index_t index, double * mode) inline
Definition at line 2409 of file lb.cpp.
References LB_Parameters::agrid, LB_Parameters::ext_force, LB_FluidNode::force, gamma_bulk, gamma_shear, LB_FluidNode::has_force, LB_Parameters::rho, scalar(), and LB_Parameters::tau.
Referenced by lb_collide_stream(), and lb_stream_collide().
void lb_calc_average_rho ()
Calculate the average density of the fluid in the system.
This function has to be called after changing the density of a local lattice site in order to set lbpar.rho consistently.
Definition at line 3263 of file lb.cpp.
References box_l, comm_cart, Lattice::grid, Lattice::halo_grid, index_t, lb_calc_local_rho(), MPI_Allreduce(), MPI_DOUBLE, MPI_SUM, and LB_Parameters::rho.
void lb_calc_modes (index_t index, double * mode)
Calculation of hydrodynamic modes.
Parameters
index number of the node to calculate the modes for
mode output pointer to a double[19]
Definition at line 2105 of file lb.cpp.
References LB_Model::e, i, lbfluid, and LB_Model::n_veloc.
Referenced by GetIBMInterpolatedVelocity(), lb_bounce_back(), lb_calc_local_fields(), lb_collide_stream(), and lb_lbfluid_get_interpolated_velocity().
void lb_calc_n_from_modes (index_t index, double * mode) inline
Definition at line 2458 of file lb.cpp.
References d3q19_modebase, LB_Model::e, i, lbfluid, LB_Model::n_veloc, and LB_Model::w.
Referenced by lb_stream_collide().
void lb_calc_n_from_modes_push (index_t index, double * m) inline
Definition at line 2520 of file lb.cpp.
References d3q19_modebase, LB_Model::e, get_linear_index(), Lattice::halo_grid, i, index_t, lbfluid, LB_Model::n_veloc, and LB_Model::w.
Referenced by lb_collide_stream().
void lb_calc_n_from_rho_j_pi (const index_t index, const double rho, const double * j, double * pi)
Calculates the equilibrium distributions.
Parameters
index Index of the local site
rho local fluid density
j local fluid speed
pi local fluid pressure
Definition at line 2018 of file lb.cpp.
References LB_Parameters::agrid, LB_Model::c, LB_Model::coeff, i, lbfluid, LB_Model::n_veloc, LB_Parameters::rho, scalar(), and SQR().
Referenced by lb_reinit_fluid(), mpi_send_fluid(), and mpi_send_fluid_slave().
static void lb_check_halo_regions () static
Checks consistency of the halo regions (ADDITIONAL_CHECKS) This function can be used as an additional check.
It test whether the halo regions have been exchanged correctly.
Definition at line 3313 of file lb.cpp.
References comm_cart, compare_buffers(), free, get_linear_index(), Lattice::grid, Lattice::halo_grid, i, index_t, lbfluid, malloc, MPI_DOUBLE, MPI_Sendrecv(), n_nodes, LB_Model::n_veloc, node_neighbors, PERIODIC, r_buffer, REQ_HALO_CHECK, and s_buffer.
Referenced by calc_particle_lattice_ia(), and lb_stream_collide().
void lb_collide_stream () inline
Definition at line 2609 of file lb.cpp.
References boundary, fluct, LB_Boundary::force, LB_FluidNode::force, LB_FluidNode::force_buf, Lattice::grid, Lattice::halo_grid, Lattice::halo_grid_volume, Lattice::halo_offset, halo_push_communication(), i, index_t, lb_apply_forces(), lb_bounce_back(), lb_boundaries, lb_calc_modes(), lb_calc_n_from_modes_push(), lb_relax_modes(), lb_thermalize_modes(), lbfluid, n_lb_boundaries, and LB_Parameters::resend_halo.
Referenced by lattice_boltzmann_update().
void lb_init ()
Performs a full initialization of the Lattice Boltzmann system.
All derived parameters and the fluid are reset to their default values.
Definition at line 1958 of file lb.cpp.
References LB_Parameters::agrid, check_runtime_errors(), i, Lattice::init(), lb_prepare_communication(), lb_realloc_fluid(), lb_reinit_fluid(), lb_reinit_forces(), lb_reinit_parameters(), LB_TRACE, and runtimeError.
Referenced by on_boxl_change(), on_cell_structure_change(), and on_lb_params_change().
int lb_lbfluid_get_agrid (double * p_agrid)
Definition at line 533 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, LATTICE_LB_GPU, lattice_switch, and lbpar_gpu.
int lb_lbfluid_get_bulk_visc (double * p_bulk_visc)
Definition at line 491 of file lb.cpp.
References LB_parameters_gpu::bulk_viscosity, LB_Parameters::bulk_viscosity, LATTICE_LB_GPU, lattice_switch, and lbpar_gpu.
int lb_lbfluid_get_density (double * p_dens)
Definition at line 462 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, lbpar_gpu, LB_parameters_gpu::rho, and LB_Parameters::rho.
int lb_lbfluid_get_ext_force (double * p_fx, double * p_fy, double * p_fz)
Definition at line 547 of file lb.cpp.
References errexit(), LB_parameters_gpu::ext_force, LB_Parameters::ext_force, LATTICE_LB_GPU, lattice_switch, and lbpar_gpu.
int lb_lbfluid_get_gamma_even (double * p_gamma_even)
Definition at line 519 of file lb.cpp.
References LB_parameters_gpu::gamma_even, LB_Parameters::gamma_even, LATTICE_LB_GPU, lattice_switch, and lbpar_gpu.
int lb_lbfluid_get_gamma_odd (double * p_gamma_odd)
Definition at line 505 of file lb.cpp.
References LB_parameters_gpu::gamma_odd, LB_Parameters::gamma_odd, LATTICE_LB_GPU, lattice_switch, and lbpar_gpu.
int lb_lbfluid_get_interpolated_velocity (double * p, double * v)
calculates the fluid velocity at a given position of the lattice.
Note that it can lead to undefined behaviour if the position is not within the local lattice.
Definition at line 2990 of file lb.cpp.
References LB_Parameters::agrid, boundary, LB_FluidNode::boundary, index_t, lb_boundaries, lb_calc_modes(), lbboundary_mindist_position(), Lattice::map_position_to_lattice(), LB_Parameters::rho, LB_Parameters::tau, and LB_Boundary::velocity.
Referenced by lb_viscous_coupling(), mpi_observable_lb_radial_velocity_profile_parallel(), and observable_calc_lb_velocity_profile().
int lb_lbfluid_get_interpolated_velocity_global (double * p, double * v)
calculates the fluid velocity at a given position of the lattice.
Note that it can lead to undefined behavior if the position is not within the local lattice. This version of the function can be called without the position needing to be on the local processor. Note that this gives a slightly different version than the values used to couple to MD beads when near a wall, see lb_lbfluid_get_interpolated_velocity.
Definition at line 1127 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, errexit(), LATTICE_LB_GPU, lattice_switch, lb_lbnode_get_u(), lbpar_gpu, and Lattice::map_position_to_lattice_global().
Referenced by tclcommand_lbfluid_print_interpolated_velocity().
int lb_lbfluid_get_visc (double * p_visc)
Definition at line 477 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, lbpar_gpu, LB_parameters_gpu::viscosity, and LB_Parameters::viscosity.
int lb_lbfluid_load_checkpoint (char * filename, int binary)
Definition at line 954 of file lb.cpp.
References LB_Parameters::agrid, box_l, ES_ERROR, ES_OK, free, i, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, lb_lbnode_set_pop(), lb_load_checkpoint_GPU(), lbpar_gpu, malloc, mpi_bcast_lb_params(), LB_parameters_gpu::number_of_nodes, LB_Parameters::resend_halo, and runtimeError.
Referenced by lb_lbfluid_load_checkpoint_wrapper(), and tclcommand_lbfluid().
int lb_lbfluid_print_boundary (char * filename)
print of the calculated phys values
Definition at line 744 of file lb.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, boundary, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, free, LATTICE_LB_GPU, lattice_switch, lb_get_boundary_flags_GPU(), lb_lbnode_get_boundary(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_print_velocity (char * filename)
print of the calculated phys values
Definition at line 804 of file lb.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, errexit(), free, host_values, LATTICE_LB_GPU, lattice_switch, lb_get_values_GPU(), lb_lbnode_get_u(), lbpar_gpu, malloc, LB_parameters_gpu::number_of_nodes, and LB_rho_v_pi_gpu::v.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_print_vtk_boundary (char * filename)
print of the calculated phys values
print of the calculated phys values
Definition at line 569 of file lb.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, LB_Parameters::agrid, boundary, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, free, LATTICE_LB_GPU, lattice_switch, lb_get_boundary_flags_GPU(), lb_lbnode_get_boundary(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_electrokinetics(), and tclcommand_lbfluid().
int lb_lbfluid_print_vtk_density (char ** filename)
print the calculated phys values
Definition at line 635 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, errexit(), free, host_values, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lb_get_values_GPU(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_print_vtk_velocity (char * filename)
print of the calculated phys values
Definition at line 679 of file lb.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, LB_Parameters::agrid, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, free, host_values, LATTICE_LB_GPU, lattice_switch, lb_get_values_GPU(), lb_lbnode_get_u(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_save_checkpoint (char * filename, int binary)
Definition at line 870 of file lb.cpp.
References LB_Parameters::agrid, box_l, ES_ERROR, ES_OK, free, i, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, lb_lbnode_get_pop(), lb_save_checkpoint_GPU(), lbpar_gpu, malloc, and LB_parameters_gpu::number_of_nodes.
Referenced by lb_lbfluid_save_checkpoint_wrapper(), and tclcommand_lbfluid().
int lb_lbfluid_set_agrid (double p_agrid)
Definition at line 356 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, box_l, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, LATTICE_LB_GPU, lattice_switch, LBPAR_AGRID, lbpar_gpu, mpi_bcast_lb_params(), LB_parameters_gpu::number_of_nodes, on_lb_params_change_gpu(), ROUND_ERROR_PREC, and runtimeError.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_bulk_visc (double * p_bulk_visc)
Definition at line 257 of file lb.cpp.
References LB_parameters_gpu::bulk_viscosity, LB_Parameters::bulk_viscosity, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, LBPAR_BULKVISC, lbpar_gpu, mpi_bcast_lb_params(), and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_couple_flag (int couple_flag)
Definition at line 337 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, LB_parameters_gpu::lb_couple_switch, LB_COUPLE_THREE_POINT, LB_COUPLE_TWO_POINT, and lbpar_gpu.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_density (double * p_dens)
Definition at line 219 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, LBPAR_DENSITY, lbpar_gpu, mpi_bcast_lb_params(), on_lb_params_change_gpu(), LB_parameters_gpu::rho, and LB_Parameters::rho.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_ext_force (int component, double p_fx, double p_fy, double p_fz)
Definition at line 428 of file lb.cpp.
References LB_parameters_gpu::ext_force, LB_Parameters::ext_force, LB_parameters_gpu::external_force, LATTICE_LB_GPU, lattice_switch, lb_reinit_extern_nodeforce_GPU(), LBPAR_EXTFORCE, lbpar_gpu, mpi_bcast_lb_params(), LB_parameters_gpu::rho, LB_Parameters::rho, LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_friction (double * p_friction)
Definition at line 316 of file lb.cpp.
References LB_parameters_gpu::friction, LB_Parameters::friction, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, LBPAR_FRICTION, lbpar_gpu, mpi_bcast_lb_params(), and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_gamma_even (double * p_gamma_even)
Definition at line 295 of file lb.cpp.
References LB_parameters_gpu::gamma_even, gamma_even, LB_Parameters::gamma_even, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lbpar_gpu, mpi_bcast_lb_params(), and on_lb_params_change_gpu().
int lb_lbfluid_set_gamma_odd (double * p_gamma_odd)
Definition at line 276 of file lb.cpp.
References LB_parameters_gpu::gamma_odd, gamma_odd, LB_Parameters::gamma_odd, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lbpar_gpu, mpi_bcast_lb_params(), and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_mobility (double * p_mobility)
Definition at line 179 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lbpar_gpu, LBPAR_MOBILITY, LB_parameters_gpu::mobility, and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_remove_momentum (void)
Definition at line 412 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, lbpar_gpu, on_lb_params_change_gpu(), and LB_parameters_gpu::remove_momentum.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_shanchen_coupling (double * p_coupling)
Definition at line 151 of file lb.cpp.
References LB_parameters_gpu::coupling, LB_COMPONENTS, LBPAR_COUPLING, lbpar_gpu, and on_lb_params_change_gpu().
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_tau (double p_tau)
Definition at line 393 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, lbpar_gpu, mpi_bcast_lb_params(), on_lb_params_change_gpu(), LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by tclcommand_lbfluid().
int lb_lbfluid_set_visc (double * p_visc)
Definition at line 238 of file lb.cpp.
References LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lbpar_gpu, LBPAR_VISCOSITY, mpi_bcast_lb_params(), on_lb_params_change_gpu(), LB_parameters_gpu::viscosity, and LB_Parameters::viscosity.
Referenced by tclcommand_lbfluid().
int lb_lbnode_get_boundary (int * ind, int * p_boundary)
Definition at line 1254 of file lb.cpp.
References LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, lb_get_boundary_flag_GPU(), lbpar_gpu, Lattice::map_lattice_to_node(), and mpi_recv_fluid_boundary_flag().
Referenced by lb_lbfluid_print_boundary(), lb_lbfluid_print_vtk_boundary(), and tclcommand_lbnode().
int lb_lbnode_get_pi (int * ind, double * p_pi)
Definition at line 1192 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lb_lbnode_get_pi_neq(), lbpar_gpu, LB_parameters_gpu::rho, LB_Parameters::rho, LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by tclcommand_lbnode().
int lb_lbnode_get_pi_neq (int * ind, double * p_pi)
Definition at line 1217 of file lb.cpp.
References LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, i, index_t, LATTICE_LB_GPU, lattice_switch, lb_print_node_GPU(), lbpar_gpu, malloc, Lattice::map_lattice_to_node(), mpi_recv_fluid(), LB_rho_v_pi_gpu::pi, and LB_Parameters::tau.
Referenced by lb_lbnode_get_pi(), and tclcommand_lbnode().
int lb_lbnode_get_pop (int * ind, double * p_pop)
Definition at line 1279 of file lb.cpp.
References get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, Lattice::map_lattice_to_node(), and mpi_recv_fluid_populations().
Referenced by lb_lbfluid_save_checkpoint(), and tclcommand_lbnode().
int lb_lbnode_get_rho (int * ind, double * p_rho)
Definition at line 1054 of file lb.cpp.
References LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lb_print_node_GPU(), lbpar_gpu, malloc, Lattice::map_lattice_to_node(), mpi_recv_fluid(), and LB_rho_v_pi_gpu::rho.
Referenced by tclcommand_lbnode().
int lb_lbnode_get_u (int * ind, double * p_u)
Definition at line 1086 of file lb.cpp.
References LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, lb_print_node_GPU(), lbpar_gpu, malloc, Lattice::map_lattice_to_node(), mpi_recv_fluid(), and LB_Parameters::tau.
Referenced by lb_lbfluid_get_interpolated_velocity_global(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_velocity(), and tclcommand_lbnode().
int lb_lbnode_set_extforce (int * ind, double * f)
Definition at line 1391 of file lb.cpp.
int lb_lbnode_set_pi (int * ind, double * pi)
Definition at line 1363 of file lb.cpp.
int lb_lbnode_set_pi_neq (int * ind, double * pi_neq)
Definition at line 1368 of file lb.cpp.
int lb_lbnode_set_pop (int * ind, double * p_pop)
Definition at line 1373 of file lb.cpp.
References get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, Lattice::map_lattice_to_node(), and mpi_send_fluid_populations().
Referenced by lb_lbfluid_load_checkpoint(), and tclcommand_lbnode().
int lb_lbnode_set_rho (int * ind, double * p_rho)
Definition at line 1297 of file lb.cpp.
References LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, i, index_t, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lb_set_node_rho_GPU(), lbpar_gpu, Lattice::map_lattice_to_node(), mpi_recv_fluid(), and mpi_send_fluid().
Referenced by tclcommand_lbnode().
int lb_lbnode_set_u (int * ind, double * u)
Definition at line 1330 of file lb.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, get_linear_index(), Lattice::halo_grid, index_t, LATTICE_LB_GPU, lattice_switch, lb_set_node_velocity_GPU(), lbpar_gpu, Lattice::map_lattice_to_node(), mpi_recv_fluid(), mpi_send_fluid(), LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by tclcommand_lbnode().
void lb_pre_init ()
(Pre-)allocate memory for data structures
(Pre-)initializes data structures.
Definition at line 1763 of file lb.cpp.
References Lattice::halo_grid_volume, lbfluid, malloc, and LB_Model::n_veloc.
Referenced by on_program_start().
static void lb_prepare_communication () static
Sets up the structures for exchange of the halo regions.
See also halo.cpp
Definition at line 1791 of file lb.cpp.
References HaloInfo::datatype, HaloInfo::dest_node, HaloInfo::fieldtype, FIELDTYPE_DOUBLE, halo_create_field_hvector(), Lattice::halo_grid_volume, HaloCommunicator::halo_info, i, MPI_DOUBLE, MPI_Type_commit(), MPI_Type_create_hvector(), MPI_Type_get_extent(), LB_Model::n_veloc, HaloCommunicator::num, prepare_halo_communication(), HaloInfo::r_offset, realloc, release_halo_communication(), HaloInfo::s_offset, HaloInfo::source_node, and HaloInfo::type.
Referenced by lb_init().
void lb_pull_calc_modes (index_t index, double * mode) inline
Streaming and calculation of modes (pull scheme)
Definition at line 2178 of file lb.cpp.
References LB_Model::e, Lattice::halo_grid, i, lbfluid, and LB_Model::n_veloc.
Referenced by lb_stream_collide().
static void lb_realloc_fluid () static
(Re-)allocate memory for the fluid and initialize pointers.
Definition at line 1770 of file lb.cpp.
References Lattice::halo_grid_volume, i, LB_TRACE, lbfluid, LB_Model::n_veloc, and realloc.
Referenced by lb_init().
void lb_reinit_fluid ()
(Re-)initializes the fluid according to the given value of rho.
(Re-)initializes the fluid.
Definition at line 1928 of file lb.cpp.
References LB_Parameters::agrid, LB_FluidNode::boundary, Lattice::halo_grid_volume, index_t, lb_calc_n_from_rho_j_pi(), lb_init_boundaries(), LB_TRACE, LB_FluidNode::recalc_fields, LB_Parameters::resend_halo, and LB_Parameters::rho.
Referenced by lb_init(), and on_lb_params_change().
void lb_reinit_forces ()
Resets the forces on the fluid nodes.
Definition at line 1903 of file lb.cpp.
References LB_Parameters::agrid, LB_Parameters::ext_force, LB_Boundary::force, LB_FluidNode::force, Lattice::halo_grid_volume, LB_FluidNode::has_force, i, index_t, lb_boundaries, n_lb_boundaries, and LB_Parameters::tau.
Referenced by lb_init().
void lb_reinit_parameters ()
(Re-)initializes the fluid.
(Re-)initializes the derived parameters for the Lattice Boltzmann system.
Definition at line 1841 of file lb.cpp.
References LB_Parameters::agrid, LB_Parameters::bulk_viscosity, LB_Model::c_sound_sq, d3q19_modebase, LB_Model::e, fluct, LB_Parameters::friction, gamma_bulk, gamma_even, LB_Parameters::gamma_even, gamma_odd, LB_Parameters::gamma_odd, gamma_shear, i, lb_coupl_pref, lb_coupl_pref2, lb_phi, LB_TRACE, LB_Model::n_veloc, SQR(), LB_Parameters::tau, temperature, this_node, time_step, and LB_Parameters::viscosity.
Referenced by lb_init(), on_lb_params_change(), on_parameter_change(), and on_temperature_change().
void lb_relax_modes (index_t index, double * mode) inline
Definition at line 2269 of file lb.cpp.
References LB_Parameters::agrid, LB_FluidNode::force, gamma_bulk, gamma_even, gamma_odd, gamma_shear, LB_Parameters::rho, scalar(), and SQR().
Referenced by lb_collide_stream(), and lb_stream_collide().
void lb_release ()
Release fluid and communication.
Definition at line 2009 of file lb.cpp.
References lb_release_fluid(), and release_halo_communication().
void lb_release_fluid ()
Release the fluid.
Definition at line 2001 of file lb.cpp.
References free, and lbfluid.
Referenced by lb_release().
int lb_sanity_checks ()
Performs basic sanity checks.
Checks if all LB parameters are meaningful.
Definition at line 1705 of file lb.cpp.
References LB_Parameters::agrid, cell_structure, CELL_STRUCTURE_DOMDEC, dd, LB_Parameters::rho, runtimeError, skin, LB_Parameters::tau, THERMO_LB, thermo_switch, CellStructure::type, DomainDecomposition::use_vList, and LB_Parameters::viscosity.
Referenced by on_integration_start().
void lb_stream_collide () inline
Streaming and collisions (pull scheme)
Definition at line 2703 of file lb.cpp.
References boundary, fluct, Lattice::grid, halo_communication(), Lattice::halo_grid, Lattice::halo_offset, IBM_ResetLBForces_CPU(), index_t, lb_apply_forces(), lb_calc_n_from_modes(), lb_check_halo_regions(), lb_pull_calc_modes(), lb_relax_modes(), lb_thermalize_modes(), lbfluid, and LB_Parameters::resend_halo.
Referenced by lattice_boltzmann_update().
void lb_thermalize_modes (index_t index, double * mode) inline
Definition at line 2326 of file lb.cpp.
References LB_Parameters::agrid, d_random(), fluct, gaussian_random(), gaussian_random_cut(), lb_phi, rancounter, and LB_Parameters::rho.
Referenced by lb_collide_stream(), and lb_stream_collide().
void lb_viscous_coupling (Particle * p, double force[3]) inline
Coupling of a single particle to viscous fluid with Stokesian friction.
Section II.C. Ahlrichs and Duenweg, JCP 111(17):8225 (1999)
Parameters
p The coupled particle (Input).
force Coupling force between particle and fluid (Output).
Definition at line 2810 of file lb.cpp.
References LB_Parameters::agrid, check_id, COORD_FIXED, ParticleParametersSwimming::dipole_length, errexit(), ParticleProperties::ext_flag, ParticleLatticeCoupling::f_random, ParticleParametersSwimming::f_swim, fold_position(), LB_Parameters::friction, ParticleProperties::identity, index_t, lb_lbfluid_get_interpolated_velocity(), Particle::lc, Particle::m, Lattice::map_position_to_lattice(), ParticleProperties::mu_E, n_nodes, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticleParametersSwimming::push_pull, ParticlePosition::quatu, Particle::r, Particle::swim, ParticleParametersSwimming::swimming, LB_Parameters::tau, this_node, time_step, ParticleMomentum::v, ParticleParametersSwimming::v_center, ParticleParametersSwimming::v_source, and ParticleParametersSwimming::v_swim.
Referenced by calc_particle_lattice_ia().
Variable Documentation
int failcounter =0 static
counts the occurences of negative populations due to fluctuations
Definition at line 139 of file lb.cpp.
int fluct static
Flag indicating whether fluctuations are present.
Definition at line 114 of file lb.cpp.
Referenced by lb_collide_stream(), lb_reinit_parameters(), lb_stream_collide(), and lb_thermalize_modes().
double fluidstep =0.0 static
measures the MD time since the last fluid update
Definition at line 133 of file lb.cpp.
Referenced by lattice_boltzmann_update().
double gamma_bulk = 0.0
relaxation rate of bulk modes
Definition at line 119 of file lb.cpp.
Referenced by lb_apply_forces(), lb_calc_local_fields(), lb_reinit_parameters(), and lb_relax_modes().
double gamma_even = 0.0 static
relaxation of the even kinetic modes
Definition at line 123 of file lb.cpp.
Referenced by lb_lbfluid_set_gamma_even(), lb_reinit_parameters(), and lb_relax_modes().
double gamma_odd = 0.0 static
relaxation of the odd kinetic modes
Definition at line 121 of file lb.cpp.
Referenced by lb_lbfluid_set_gamma_odd(), lb_reinit_parameters(), and lb_relax_modes().
double gamma_shear = 0.0
relaxation rate of shear modes
Definition at line 117 of file lb.cpp.
Referenced by lb_apply_forces(), lb_calc_local_fields(), lb_reinit_parameters(), and lb_relax_modes().
int lb_components = LB_COMPONENTS
Definition at line 47 of file lb.cpp.
double lb_coupl_pref = 0.0 static
amplitude of the fluctuations in the viscous coupling
Definition at line 127 of file lb.cpp.
Referenced by calc_particle_lattice_ia(), and lb_reinit_parameters().
double lb_coupl_pref2 = 0.0 static
amplitude of the fluctuations in the viscous coupling with gaussian random numbers
Definition at line 129 of file lb.cpp.
Referenced by calc_particle_lattice_ia(), and lb_reinit_parameters().
double lb_phi[19] static
amplitudes of the fluctuations of the modes
Definition at line 125 of file lb.cpp.
Referenced by lb_reinit_parameters(), and lb_thermalize_modes().
LB_FluidNode* lbfields = NULL
Pointer to the hydrodynamic fields of the fluid nodes.
Pointer to the hydrodynamic fields of the fluid.
Definition at line 106 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), IBM_ResetLBForces_CPU(), lb_bounce_back(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), and lb_init_boundaries().
double** lbfluid[2] = { NULL, NULL }
Pointer to the velocity populations of the fluid nodes.
Pointer to the velocity populations of the fluid.
Definition at line 103 of file lb.cpp.
Referenced by calc_particle_lattice_ia(), halo_push_communication(), lb_bounce_back(), lb_calc_local_j(), lb_calc_local_rho(), lb_calc_modes(), lb_calc_n_from_modes(), lb_calc_n_from_modes_push(), lb_calc_n_from_rho_j_pi(), lb_check_halo_regions(), lb_collide_stream(), lb_get_populations(), lb_pre_init(), lb_pull_calc_modes(), lb_realloc_fluid(), lb_release_fluid(), lb_set_populations(), lb_stream_collide(), ParticleVelocitiesFromLB_CPU(), and tclcommand_lbnode().
Lattice lblattice
The underlying lattice structure.
The underlying lattice.
Definition at line 100 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), IBM_ForcesIntoFluid_CPU(), IBM_ResetLBForces_CPU(), IsHalo(), lb_bounce_back(), lb_calc_densprof(), lb_calc_fluid_mass(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_calc_velprof(), lb_init_boundaries(), ParticleVelocitiesFromLB_CPU(), tclcommand_analyze_fluid_parse_densprof(), and tclcommand_analyze_fluid_parse_velprof().
LB_Model lbmodel = { 19, d3q19_lattice, d3q19_coefficients, d3q19_w, NULL, 1./3. }
The DnQm model to be used.
Definition at line 86 of file lb.cpp.
Referenced by lb_bounce_back().
LB_Parameters lbpar
Initial value:
= {
    {0.0},
    {0.0},
    {-1.0},
    -1.0,
    -1.0,
    {0.0},
    { 0.0, 0.0, 0.0},
    {0.},
    {0.},
    {0.},
    0
}
Struct holding the Lattice Boltzmann parameters.
Definition at line 60 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), IBM_ForcesIntoFluid_CPU(), IBM_ResetLBForces_CPU(), lb_bounce_back(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_calc_velprof(), lbboundary_get_force(), mpi_bcast_lb_params_slave(), mpi_observable_lb_radial_velocity_profile_parallel(), mpi_recv_fluid_populations(), mpi_recv_fluid_populations_slave(), observable_calc_lb_velocity_profile(), ParticleVelocitiesFromLB_CPU(), tclcallback_time_step(), tclcommand_analyze_fluid_parse_densprof(), tclcommand_analyze_fluid_parse_velprof(), tclcommand_lbboundary_cylinder(), tclcommand_lbboundary_rhomboid(), tclcommand_lbboundary_spherocylinder(), tclcommand_lbboundary_wall(), and tclcommand_lbnode().
int rancounter =0 static
counts the random numbers drawn for fluctuating LB and the coupling
Definition at line 137 of file lb.cpp.
Referenced by calc_particle_lattice_ia(), and lb_thermalize_modes().
int transfer_momentum = 0
Flag indicating momentum exchange between particles and fluid.
Switch indicating momentum exchange between particles and fluid.
Definition at line 56 of file lb.cpp.
Referenced by calc_particle_lattice_ia(), integrate_sd(), and integrate_vv().
HaloCommunicator update_halo_comm = { 0, NULL }
Communicator for halo exchange between processors.
Definition at line 109 of file lb.cpp.