ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lb_tcl.hpp File Reference
lb_tcl.hpp File Reference
#include "parser.hpp"
Functions
int tclcommand_lbfluid (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Parser for the TCL command lbfluid.
int tclcommand_lbnode (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Parser for the lbnode command.
int tclcommand_lbfluid_print_interpolated_velocity (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_lbnode_extforce_gpu (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Parser for the tclcommand_lbnode_extforce_gpu command.
int tclcommand_inter_parse_affinity (Tcl_Interp *interp, int part_type_a, int part_type_b, int argc, char **argv)
int tclcommand_lbboundary (ClientData _data, Tcl_Interp *interp, int argc, char **argv)
lb boundary command.
int affinity_set_params (int part_type_a, int part_type_b, double *affinity)
int tclprint_to_result_affinityIA (Tcl_Interp *interp, int i, int j)
Variables
int ek_initialized
Function Documentation
int affinity_set_params (int part_type_a, int part_type_b, double * affinity)
Definition at line 200 of file lb.cpp.
References IA_parameters::affinity, IA_parameters::affinity_on, ES_ERROR, ES_OK, get_ia_param_safe(), LB_COMPONENTS, and mpi_bcast_ia_params().
Referenced by tclcommand_inter_parse_affinity().
int tclcommand_inter_parse_affinity (Tcl_Interp * interp, int part_type_a, int part_type_b, int argc, char ** argv)
Definition at line 55 of file lb_tcl.cpp.
References affinity_set_params(), ARG_IS_D, ES_ERROR, and LB_COMPONENTS.
Referenced by tclcommand_inter_parse_non_bonded().
int tclcommand_lbboundary (ClientData _data, Tcl_Interp * interp, int argc, char ** argv)
lb boundary command.
From lb-boundaries_tcl.cpp
Definition at line 1374 of file lb-boundaries_tcl.cpp.
References ARG_IS_S, gather_runtime_errors(), generate_lbboundary(), i, LATTICE_LB_GPU, LATTICE_OFF, lattice_switch, lbboundary_get_force(), mpi_bcast_lbboundary(), n_lb_boundaries, tclcommand_lbboundary_cylinder(), tclcommand_lbboundary_hollow_cone(), tclcommand_lbboundary_pore(), tclcommand_lbboundary_print_all(), tclcommand_lbboundary_rhomboid(), tclcommand_lbboundary_sphere(), tclcommand_lbboundary_spherocylinder(), tclcommand_lbboundary_stomatocyte(), tclcommand_lbboundary_wall(), and tclcommand_printLbBoundaryToResult().
Referenced by tcl_register_commands().
int tclcommand_lbfluid (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Parser for the TCL command lbfluid.
Parser for the TCL command lbfluid.
if we have LB the LB cpu is set by default
Definition at line 205 of file lb_tcl.cpp.
References ARG0_IS_S_EXACT, ARG1_IS_D, ARG1_IS_S_EXACT, ARG_IS_D, ek_initialized, err, FIELD_LATTICE_SWITCH, FIELD_THERMO_SWITCH, gather_runtime_errors(), i, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, LB_COUPLE_THREE_POINT, LB_COUPLE_TWO_POINT, lb_lbfluid_load_checkpoint(), lb_lbfluid_print_boundary(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_boundary(), lb_lbfluid_print_vtk_density(), lb_lbfluid_print_vtk_velocity(), lb_lbfluid_save_checkpoint(), lb_lbfluid_set_agrid(), lb_lbfluid_set_bulk_visc(), lb_lbfluid_set_couple_flag(), lb_lbfluid_set_density(), lb_lbfluid_set_ext_force(), lb_lbfluid_set_friction(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_mobility(), lb_lbfluid_set_remove_momentum(), lb_lbfluid_set_shanchen_coupling(), lb_lbfluid_set_tau(), lb_lbfluid_set_visc(), lbfluid_tcl_print_usage(), mpi_bcast_parameter(), tclcommand_lbfluid_print_interpolated_velocity(), THERMO_LB, thermo_switch, and time_step.
Referenced by tcl_register_commands().
int tclcommand_lbfluid_print_interpolated_velocity (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1143 of file lb_tcl.cpp.
References ARG_IS_D, i, and lb_lbfluid_get_interpolated_velocity_global().
Referenced by tclcommand_lbfluid().
int tclcommand_lbnode (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Parser for the lbnode command.
Parser for the lbnode command.
Definition at line 877 of file lb_tcl.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, ARG0_IS_D, ARG0_IS_S_EXACT, ARG_IS_I, box_l, LATTICE_LB_GPU, lattice_switch, LB_COMPONENTS, lb_lbnode_get_boundary(), lb_lbnode_get_pi(), lb_lbnode_get_pi_neq(), lb_lbnode_get_pop(), lb_lbnode_get_rho(), lb_lbnode_get_u(), lb_lbnode_set_pop(), lb_lbnode_set_rho(), lb_lbnode_set_u(), lbfluid, lbnode_tcl_print_usage(), lbpar, and lbpar_gpu.
Referenced by tcl_register_commands().
int tclcommand_lbnode_extforce_gpu (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Parser for the tclcommand_lbnode_extforce_gpu command.
Can be used in future to set more values like rho,u e.g.
Definition at line 131 of file lb_tcl.cpp.
References ARG0_IS_S_EXACT, ARG_IS_I, err, ES_ERROR, and lbnode_parse_set().
Referenced by tcl_register_commands().
int tclprint_to_result_affinityIA (Tcl_Interp * interp, int i, int j)
Definition at line 38 of file lb_tcl.cpp.
References IA_parameters::affinity, get_ia_param(), and LB_COMPONENTS.
Referenced by tclprint_to_result_NonbondedIA().
Variable Documentation
int ek_initialized
Definition at line 166 of file lbgpu.cpp.
Referenced by lb_reinit_parameters_gpu().