ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lbgpu_cuda.cu File Reference
lbgpu_cuda.cu File Reference
Cuda (.cu) file for the Lattice Boltzmann implementation on GPUs.
#include "config.hpp"
#include <stdio.h>
#include <cuda.h>
#include <stdlib.h>
#include "electrokinetics.hpp"
#include "electrokinetics_pdb_parse.hpp"
#include "lbgpu.hpp"
#include "cuda_interface.hpp"
#include "cuda_utils.hpp"
Macros
#define FLATNOISE
#define sqrt12 3.46410161514f
#define BOUNCEBACK()
#define free_and_realloc(var, size) { if((var) != NULL) cudaFree((var)); cuda_safe_mem(cudaMalloc((void**)&var, size)); }
Functions
device functions called by kernel functions
__device__ void atomicadd (float *address, float value)
atomic add function for sveral cuda architectures
__device__ void atomicadd (double *address, double value)
__device__ void random_01 (LB_randomnr_gpu *rn)
randomgenerator which generates numbers [0,1]
__device__ void gaussian_random_cut (LB_randomnr_gpu *rn)
randomgenerator which generates numbers between -2 sigma and 2 sigma in the form of a Gaussian with standard deviation sigma=1.118591404 resulting in an actual standard deviation of 1.
__device__ void gaussian_random (LB_randomnr_gpu *rn)
gaussian random nummber generator for thermalisation
__device__ void random_wrapper (LB_randomnr_gpu *rn)
__device__ void index_to_xyz (unsigned int index, unsigned int *xyz)
tranformation from 1d array-index to xyz
__device__ void calc_m_from_n (LB_nodes_gpu n_a, unsigned int index, float *mode)
calculation of the modes from the velocity densities (space-transform.)
__device__ void reset_LB_forces (unsigned int index, LB_node_force_gpu node_f, bool buffer=true)
__global__ void reset_LB_forces_kernel (LB_node_force_gpu node_f, bool buffer=true)
void reset_LB_forces_GPU (bool buffer)
Resets the forces on the fluid nodes.
__device__ void update_rho_v (float *mode, unsigned int index, LB_node_force_gpu node_f, LB_rho_v_gpu *d_v)
__device__ void relax_modes (float *mode, unsigned int index, LB_node_force_gpu node_f, LB_rho_v_gpu *d_v)
lb_relax_modes, means collision update of the modes
__device__ void thermalize_modes (float *mode, unsigned int index, LB_randomnr_gpu *rn)
thermalization of the modes with gaussian random numbers
__device__ void normalize_modes (float *mode)
normalization of the modes need befor backtransformation into velocity space
__device__ void calc_n_from_modes_push (LB_nodes_gpu n_b, float *mode, unsigned int index)
backtransformation from modespace to desityspace and streaming with the push method using pbc
__device__ void bounce_back_boundaries (LB_nodes_gpu n_curr, unsigned int index, float *lb_boundary_velocity, float *lb_boundary_force)
Bounce back boundary conditions.
__device__ void apply_forces (unsigned int index, float *mode, LB_node_force_gpu node_f, LB_rho_v_gpu *d_v)
add of (external) forces within the modespace, needed for particle-interaction
__device__ void calc_values_in_MD_units (LB_nodes_gpu n_a, float *mode, LB_rho_v_pi_gpu *d_p_v, LB_rho_v_gpu *d_v, LB_node_force_gpu node_f, unsigned int index, unsigned int print_index)
function used to calculate hydrodynamic fields in MD units.
__device__ void calc_values_from_m_in_LB_units (float *mode_single, LB_rho_v_gpu *d_v_single, float *rho_out, float *j_out, float *pi_out)
function used to calculate hydrodynamic fields in MD units.
__device__ void calc_values (LB_nodes_gpu n_a, float *mode, LB_rho_v_gpu *d_v, LB_node_force_gpu node_f, unsigned int index)
function used to calc physical values of every node
__device__ void calc_mode (float *mode, LB_nodes_gpu n_a, unsigned int node_index, int component_index)
interpolation_three_point_coupling
__device__ __inline__ void interpolation_three_point_coupling (LB_nodes_gpu n_a, float *particle_position, unsigned int *node_index, LB_rho_v_gpu *d_v, float *delta, float *interpolated_u)
(Eq.
calc_viscous_force_three_point_couple
__device__ void calc_viscous_force_three_point_couple (LB_nodes_gpu n_a, float *delta, CUDA_particle_data *particle_data, float *particle_force, unsigned int part_index, LB_randomnr_gpu *rn_part, float *delta_j, unsigned int *node_index, LB_rho_v_gpu *d_v, int flag_cs)
(Eq.
__device__ void calc_node_force_three_point_couple (float *delta, float *delta_j, unsigned int *node_index, LB_node_force_gpu node_f)
calcutlation of the node force caused by the particles, with atomicadd due to avoiding race conditions (Eq.
__global__ void temperature (LB_nodes_gpu n_a, float *cpu_jsquared, int *number_of_non_boundary_nodes)
calculate temperature of the fluid kernel
interpolation_two_point_coupling
__device__ __inline__ void interpolation_two_point_coupling (LB_nodes_gpu n_a, float *particle_position, unsigned int *node_index, float *mode, LB_rho_v_gpu *d_v, float *delta, float *interpolated_u)
(Eq.
calc_viscous_force
__device__ void calc_viscous_force (LB_nodes_gpu n_a, float *delta, float *partgrad1, float *partgrad2, float *partgrad3, CUDA_particle_data *particle_data, float *particle_force, CUDA_fluid_composition *fluid_composition, unsigned int part_index, LB_randomnr_gpu *rn_part, float *delta_j, unsigned int *node_index, LB_rho_v_gpu *d_v, int flag_cs)
(Eq.
__device__ void calc_node_force (float *delta, float *delta_j, float *partgrad1, float *partgrad2, float *partgrad3, unsigned int *node_index, LB_node_force_gpu node_f)
calculation of the node force caused by the particles, with atomicadd due to avoiding race conditions (Eq.
System setup and Kernel functions
__global__ void calc_n_from_rho_j_pi (LB_nodes_gpu n_a, LB_rho_v_gpu *d_v, LB_node_force_gpu node_f, int *gpu_check)
kernel to calculate local populations from hydrodynamic fields given by the tcl values.
__global__ void set_u_from_rho_v_pi (LB_nodes_gpu n_a, int single_nodeindex, float *velocity, LB_rho_v_gpu *d_v, LB_node_force_gpu node_f)
kernel to calculate local populations from hydrodynamic fields from given flow field velocities.
__global__ void calc_mass (LB_nodes_gpu n_a, float *sum)
calculate mass of the whole fluid kernel
__global__ void reinit_node_force (LB_node_force_gpu node_f)
(re-)initialization of the node force / set up of external force in lb units
__global__ void init_extern_nodeforces (int n_extern_nodeforces, LB_extern_nodeforce_gpu *extern_nodeforces, LB_node_force_gpu node_f)
set extern force on single nodes kernel
__device__ __inline__ float calc_massmode (LB_nodes_gpu n_a, int single_nodeindex, int component_index)
__device__ __inline__ void calc_shanchen_contribution (LB_nodes_gpu n_a, int component_index, int x, int y, int z, float *p)
__global__ void lb_shanchen_GPU (LB_nodes_gpu n_a, LB_node_force_gpu node_f)
function to calc shanchen forces
__global__ void set_rho (LB_nodes_gpu n_a, LB_rho_v_gpu *d_v, int single_nodeindex, float *rho)
kernel to set the local density
__global__ void init_boundaries (int *boundary_node_list, int *boundary_index_list, int number_of_boundnodes, LB_nodes_gpu n_a, LB_nodes_gpu n_b)
set the boundary flag for all boundary nodes
__global__ void reset_boundaries (LB_nodes_gpu n_a, LB_nodes_gpu n_b)
reset the boundary flag of every node
__global__ void integrate (LB_nodes_gpu n_a, LB_nodes_gpu n_b, LB_rho_v_gpu *d_v, LB_node_force_gpu node_f, EK_parameters *ek_parameters_gpu)
integrationstep of the lb-fluid-solver
__global__ void calc_fluid_particle_ia (LB_nodes_gpu n_a, CUDA_particle_data *particle_data, float *particle_force, CUDA_fluid_composition *fluid_composition, LB_node_force_gpu node_f, CUDA_particle_seed *part, LB_rho_v_gpu *d_v)
part interaction kernel
__global__ void calc_fluid_particle_ia_three_point_couple (LB_nodes_gpu n_a, CUDA_particle_data *particle_data, float *particle_force, LB_node_force_gpu node_f, CUDA_particle_seed *part, LB_rho_v_gpu *d_v)
part interaction kernel
__global__ void apply_boundaries (LB_nodes_gpu n_curr, float *lb_boundary_velocity, float *lb_boundary_force)
Bounce back boundary kernel.
__global__ void lb_shanchen_set_boundaries (LB_nodes_gpu n_curr)
__global__ void get_mesoscopic_values_in_MD_units (LB_nodes_gpu n_a, LB_rho_v_pi_gpu *p_v, LB_rho_v_gpu *d_v, LB_node_force_gpu node_f)
get physical values of the nodes (density, velocity, ...)
__global__ void lb_get_boundaries (LB_nodes_gpu n_a, unsigned int *device_bound_array)
get boundary flags
__global__ void lb_print_node (int single_nodeindex, LB_rho_v_pi_gpu *d_p_v, LB_nodes_gpu n_a, LB_rho_v_gpu *d_v, LB_node_force_gpu node_f)
print single node values kernel
__global__ void momentum (LB_nodes_gpu n_a, LB_rho_v_gpu *d_v, LB_node_force_gpu node_f, float *sum)
__global__ void remove_momentum (LB_nodes_gpu n_a, LB_rho_v_gpu *d_v, LB_node_force_gpu node_f, float *sum)
__global__ void lb_get_boundary_flag (int single_nodeindex, unsigned int *device_flag, LB_nodes_gpu n_a)
print single node boundary flag
void lb_get_para_pointer (LB_parameters_gpu **pointeradress)
void lb_get_lbpar_pointer (LB_parameters_gpu **pointeradress)
void lb_get_boundary_force_pointer (float **pointeradress)
void lb_get_device_values_pointer (LB_rho_v_gpu **pointeradress)
void lb_init_GPU (LB_parameters_gpu *lbpar_gpu)
initialization for the lb gpu fluid called from host
void lb_reinit_GPU (LB_parameters_gpu *lbpar_gpu)
reinitialization for the lb gpu fluid called from host
void lb_realloc_particles_GPU_leftovers (LB_parameters_gpu *lbpar_gpu)
void lb_init_boundaries_GPU (int host_n_lb_boundaries, int number_of_boundnodes, int *host_boundary_node_list, int *host_boundary_index_list, float *host_lb_boundary_velocity)
setup and call boundaries from the host
void lb_reinit_extern_nodeforce_GPU (LB_parameters_gpu *lbpar_gpu)
setup and call extern single node force initialization from the host
void lb_init_extern_nodeforces_GPU (int n_extern_nodeforces, LB_extern_nodeforce_gpu *host_extern_nodeforces, LB_parameters_gpu *lbpar_gpu)
setup and call extern single node force initialization from the host
void lb_calc_particle_lattice_ia_gpu ()
setup and call particle kernel from the host
void lb_get_values_GPU (LB_rho_v_pi_gpu *host_values)
setup and call kernel for getting macroscopic fluid values of all nodes
void lb_get_boundary_flags_GPU (unsigned int *host_bound_array)
get all the boundary flags for all nodes
void lb_print_node_GPU (int single_nodeindex, LB_rho_v_pi_gpu *host_print_values)
setup and call kernel for getting macroscopic fluid values of a single node
void lb_calc_fluid_mass_GPU (double *mass)
setup and call kernel to calculate the total momentum of the hole fluid
void lb_calc_fluid_momentum_GPU (double *host_mom)
setup and call kernel to calculate the total momentum of the whole fluid
void lb_remove_fluid_momentum_GPU (void)
setup and call kernel to remove the net momentum of the whole fluid
void lb_calc_fluid_temperature_GPU (double *host_temp)
setup and call kernel to calculate the temperature of the hole fluid
void lb_calc_shanchen_GPU ()
void lb_save_checkpoint_GPU (float *host_checkpoint_vd, unsigned int *host_checkpoint_seed, unsigned int *host_checkpoint_boundary, lbForceFloat *host_checkpoint_force)
setup and call kernel for getting macroscopic fluid values of all nodes
void lb_load_checkpoint_GPU (float *host_checkpoint_vd, unsigned int *host_checkpoint_seed, unsigned int *host_checkpoint_boundary, lbForceFloat *host_checkpoint_force)
setup and call kernel for setting macroscopic fluid values of all nodes
void lb_get_boundary_flag_GPU (int single_nodeindex, unsigned int *host_flag)
setup and call kernel to get the boundary flag of a single node
void lb_set_node_rho_GPU (int single_nodeindex, float *host_rho)
set the density at a single node
void lb_set_node_velocity_GPU (int single_nodeindex, float *host_velocity)
set the net velocity at a single node
void reinit_parameters_GPU (LB_parameters_gpu *lbpar_gpu)
reinit of params
void lb_integrate_GPU ()
integration kernel for the lb gpu fluid update called from host
void lb_gpu_get_boundary_forces (double *forces)
__device__ void get_interpolated_velocity (LB_nodes_gpu n_a, float *r, float *u, LB_node_force_gpu node_f, int asdf)
__global__ void fill_lb_radial_velocity_profile (LB_nodes_gpu n_a, radial_profile_data *pdata, float *data, LB_node_force_gpu node_f)
int statistics_observable_lbgpu_radial_velocity_profile (radial_profile_data *pdata, double *A, unsigned int n_A)
Variables
int extended_values_flag =0
static LB_rho_v_gpu * device_rho_v = NULL
defining structures residing in global memory
static LB_rho_v_pi_gpu * device_rho_v_pi = NULL
device_rho_v_pi: extended struct for hydrodynamic fields: this is the interface to tcl, and stores values in MD units.
static LB_rho_v_pi_gpu * print_rho_v_pi = NULL
print_rho_v_pi: struct for hydrodynamic fields: this is the interface to tcl, and stores values in MD units.
static LB_nodes_gpu nodes_a = {.vd=NULL,.seed=NULL,.boundary=NULL}
structs for velocity densities
static LB_nodes_gpu nodes_b = {.vd=NULL,.seed=NULL,.boundary=NULL}
LB_node_force_gpu node_f = {.force=NULL,.scforce=NULL}
struct for node force
static LB_extern_nodeforce_gpu * extern_nodeforces = NULL
static float * lb_boundary_force = NULL
static float * lb_boundary_velocity = NULL
static int * boundary_node_list
pointer for bound index array
static int * boundary_index_list
static __device__ __constant__ int n_lb_boundaries_gpu = 0
static size_t size_of_boundindex
static __device__ __constant__ int ek_initialized_gpu = 0
EK_parameters * lb_ek_parameters_gpu
static int * gpu_check = NULL
pointers for additional cuda check flag
static int * h_gpu_check = NULL
static unsigned int intflag = 1
LB_nodes_gpu * current_nodes = NULL
static size_t size_of_rho_v
defining size values for allocating global memory
static size_t size_of_rho_v_pi
static size_t size_of_extern_nodeforces
static __device__ __constant__ LB_parameters_gpu para
parameters residing in constant memory
static const float c_sound_sq = 1.0f/3.0f
Detailed Description
Cuda (.cu) file for the Lattice Boltzmann implementation on GPUs.
Header file for lbgpu.hpp.
Definition in file lbgpu_cuda.cu.
Macro Definition Documentation
#define BOUNCEBACK ()
Value:
for(int component=0; component<LB_COMPONENTS;component++){\
     shift = 2.0f*para.agrid*para.agrid*para.rho[component]*3.0f*weight*para.tau*(v[0]*c[0] + v[1]*c[1] + v[2]*c[2]); \
     pop_to_bounce_back =  n_curr.vd[(population+component*LBQ)*para.number_of_nodes + index ]; \
     to_index_x = (x+c[0]+para.dim_x)%para.dim_x; \
     to_index_y = (y+c[1]+para.dim_y)%para.dim_y; \
     to_index_z = (z+c[2]+para.dim_z)%para.dim_z; \
     to_index = to_index_x + para.dim_x*to_index_y + para.dim_x*para.dim_y*to_index_z; \
     if ( n_curr.boundary[to_index] == 0) \
     { \
       boundary_force[0] += (2.0f*pop_to_bounce_back+shift)*c[0]/para.tau/para.tau/para.agrid; \
       boundary_force[1] += (2.0f*pop_to_bounce_back+shift)*c[1]/para.tau/para.tau/para.agrid; \
       boundary_force[2] += (2.0f*pop_to_bounce_back+shift)*c[2]/para.tau/para.tau/para.agrid; \
       n_curr.vd[(inverse+component*LBQ)*para.number_of_nodes + to_index ] = pop_to_bounce_back + shift; \
       n_curr.vd[(inverse+component*LBQ)*para.number_of_nodes + to_index ] = pop_to_bounce_back + shift; \
     } \
  }
Referenced by bounce_back_boundaries().
#define FLATNOISE
Definition at line 40 of file lbgpu_cuda.cu.
#define free_and_realloc (var, size) { if((var) != NULL) cudaFree((var)); cuda_safe_mem(cudaMalloc((void**)&var, size)); }
Referenced by lb_init_GPU().
#define sqrt12 3.46410161514f
Referenced by random_wrapper().
Function Documentation
__global__ void apply_boundaries (LB_nodes_gpu n_curr, float * lb_boundary_velocity, float * lb_boundary_force)
Bounce back boundary kernel.
Parameters
n_a Pointer to local node residing in array a (Input)
n_b Pointer to local node residing in array b (Input)
lb_boundary_velocity The constant velocity at the boundary, set by the user (Input)
lb_boundary_force The force on the boundary nodes (Output)
Definition at line 2935 of file lbgpu_cuda.cu.
References bounce_back_boundaries(), LB_parameters_gpu::number_of_nodes, and para.
Referenced by lb_integrate_GPU().
__device__ void apply_forces (unsigned int index, float * mode, LB_node_force_gpu node_f, LB_rho_v_gpu * d_v)
add of (external) forces within the modespace, needed for particle-interaction
Parameters
index node index / thread index (Input)
mode Pointer to the local register values mode (Input/Output)
node_f Pointer to local node force (Input)
*d_v Pointer to local device values
update momentum modes
update momentum modes
update stress modes
Definition at line 1150 of file lbgpu_cuda.cu.
References LB_node_force_gpu::force, LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_mobility, LB_parameters_gpu::gamma_shear, LB_COMPONENTS, LBQ, LB_parameters_gpu::number_of_nodes, para, reset_LB_forces(), LB_node_force_gpu::scforce, and LB_rho_v_gpu::v.
Referenced by integrate().
__device__ void atomicadd (float * address, float value) inline
atomic add function for sveral cuda architectures
Definition at line 122 of file lbgpu_cuda.cu.
References atomicAdd().
Referenced by bounce_back_boundaries(), calc_mass(), calc_node_force(), calc_node_force_three_point_couple(), momentum(), and temperature().
__device__ void atomicadd (double * address, double value) inline
Definition at line 136 of file lbgpu_cuda.cu.
__device__ void bounce_back_boundaries (LB_nodes_gpu n_curr, unsigned int index, float * lb_boundary_velocity, float * lb_boundary_force)
Bounce back boundary conditions.
The populations that have propagated into a boundary node are bounced back to the node they came from. This results in no slip boundary conditions.
[cf. Ladd and Verberg, J. Stat. Phys. 104(5/6):1191-1251, 2001]
Parameters
index node index / thread index (Input)
n_curr Pointer to local node which receives the current node field (Input)
lb_boundary_velocity The constant velocity at the boundary, set by the user (Input)
lb_boundary_force The force on the boundary nodes (Output)
store vd temporary in second lattice to avoid race conditions
Definition at line 1011 of file lbgpu_cuda.cu.
References atomicadd(), BOUNCEBACK, LB_nodes_gpu::boundary, and index_to_xyz().
Referenced by apply_boundaries().
__global__ void calc_fluid_particle_ia (LB_nodes_gpu n_a, CUDA_particle_data * particle_data, float * particle_force, CUDA_fluid_composition * fluid_composition, LB_node_force_gpu node_f, CUDA_particle_seed * part, LB_rho_v_gpu * d_v)
part interaction kernel
Parameters
n_a Pointer to local node residing in array a (Input)
*particle_data Pointer to the particle position and velocity (Input)
*particle_force Pointer to the particle force (Input)
*part Pointer to the rn array of the particles (Input)
node_f Pointer to local node force (Input)
*fluid_composition Pointer to the local fluid composition for the Shanchen
*d_v Pointer to local device values
force acting on the particle. delta_j will be used later to compute the force that acts back onto the fluid.
force which acts back to the fluid node
Definition at line 2858 of file lbgpu_cuda.cu.
References calc_node_force(), calc_viscous_force(), LB_COMPONENTS, LB_parameters_gpu::number_of_particles, para, and LB_randomnr_gpu::seed.
Referenced by lb_calc_particle_lattice_ia_gpu().
__global__ void calc_fluid_particle_ia_three_point_couple (LB_nodes_gpu n_a, CUDA_particle_data * particle_data, float * particle_force, LB_node_force_gpu node_f, CUDA_particle_seed * part, LB_rho_v_gpu * d_v)
part interaction kernel
Parameters
n_a Pointer to local node residing in array a (Input)
*particle_data Pointer to the particle position and velocity (Input)
*particle_force Pointer to the particle force (Input)
*part Pointer to the rn array of the particles (Input)
node_f Pointer to local node force (Input)
*d_v Pointer to local device values
force acting on the particle. delta_j will be used later to compute the force that acts back onto the fluid.
force which acts back to the fluid node
Definition at line 2901 of file lbgpu_cuda.cu.
References calc_node_force_three_point_couple(), calc_viscous_force_three_point_couple(), LB_COMPONENTS, LB_parameters_gpu::number_of_particles, para, and LB_randomnr_gpu::seed.
Referenced by lb_calc_particle_lattice_ia_gpu().
__device__ void calc_m_from_n (LB_nodes_gpu n_a, unsigned int index, float * mode)
calculation of the modes from the velocity densities (space-transform.)
Parameters
n_a Pointer to local node residing in array a (Input)
index Node index / thread index (Input)
mode Pointer to the local register values mode (Output)
Definition at line 270 of file lbgpu_cuda.cu.
References LB_COMPONENTS, LBQ, LB_parameters_gpu::number_of_nodes, para, and LB_nodes_gpu::vd.
Referenced by calc_n_from_rho_j_pi(), get_interpolated_velocity(), get_mesoscopic_values_in_MD_units(), integrate(), interpolation_three_point_coupling(), interpolation_two_point_coupling(), lb_print_node(), and set_u_from_rho_v_pi().
__global__ void calc_mass (LB_nodes_gpu n_a, float * sum)
calculate mass of the whole fluid kernel
Parameters
*sum Pointer to result storage value (Output)
n_a Pointer to local node residing in array a (Input)
Definition at line 2472 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, atomicadd(), calc_mode(), LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, para, and LB_parameters_gpu::rho.
Referenced by lb_calc_fluid_mass_GPU().
__device__ __inline__ float calc_massmode (LB_nodes_gpu n_a, int single_nodeindex, int component_index)
Parameters
single_nodeindex Single node index (Input)
component_index Shanchen component index (Input)
n_a Pointer to local node residing in array a(Input)
mass mode
Definition at line 2551 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LBQ, LB_parameters_gpu::number_of_nodes, para, LB_parameters_gpu::rho, and LB_nodes_gpu::vd.
Referenced by calc_shanchen_contribution(), and lb_shanchen_GPU().
__device__ void calc_mode (float * mode, LB_nodes_gpu n_a, unsigned int node_index, int component_index)
Parameters
node_index node index around (8) particle (Input)
*mode Pointer to the local register values mode (Output)
n_a Pointer to local node residing in array a(Input)
component_index Shanchen component index (Input)
mass mode
momentum modes
Definition at line 1487 of file lbgpu_cuda.cu.
References LBQ, LB_parameters_gpu::number_of_nodes, para, and LB_nodes_gpu::vd.
Referenced by calc_mass(), calc_viscous_force(), momentum(), and temperature().
__device__ void calc_n_from_modes_push (LB_nodes_gpu n_b, float * mode, unsigned int index)
backtransformation from modespace to desityspace and streaming with the push method using pbc
Parameters
index node index / thread index (Input)
mode Pointer to the local register values mode (Input)
*n_b Pointer to local node residing in array b (Output)
Definition at line 769 of file lbgpu_cuda.cu.
References LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, index_to_xyz(), LB_COMPONENTS, LBQ, LB_parameters_gpu::number_of_nodes, para, and LB_nodes_gpu::vd.
Referenced by integrate().
__global__ void calc_n_from_rho_j_pi (LB_nodes_gpu n_a, LB_rho_v_gpu * d_v, LB_node_force_gpu node_f, int * gpu_check)
kernel to calculate local populations from hydrodynamic fields given by the tcl values.
The mapping is given in terms of the equilibrium distribution.
Eq. (2.15) Ladd, J. Fluid Mech. 271, 295-309 (1994) Eq. (4) in Berk Usta, Ladd and Butler, JCP 122, 094902 (2005)
Parameters
n_a Pointer to the lattice site (Input).
*gpu_check additional check if gpu kernel are executed(Input).
*d_v Pointer to local device values
*node_f Pointer to node forces
default values for fields in lattice units
reduce the pressure tensor to the part needed here. NOTE: this not true anymore for SHANCHEN if the densities are not uniform. FIXME
update the q=0 sublattice
update the q=1 sublattice
update the q=2 sublattice
set different seed for randomgen on every node
Definition at line 2234 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, c_sound_sq, calc_m_from_n(), LB_COMPONENTS, LBQ, LB_parameters_gpu::number_of_nodes, para, LB_parameters_gpu::rho, LB_nodes_gpu::seed, update_rho_v(), LB_nodes_gpu::vd, and LB_parameters_gpu::your_seed.
Referenced by lb_init_GPU(), and lb_reinit_GPU().
__device__ void calc_node_force (float * delta, float * delta_j, float * partgrad1, float * partgrad2, float * partgrad3, unsigned int * node_index, LB_node_force_gpu node_f)
calculation of the node force caused by the particles, with atomicadd due to avoiding race conditions (Eq.
(14) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
Parameters
*delta Pointer for the weighting of particle position (Input)
partgrad1 particle gradient for the Shan-Chen
partgrad2 particle gradient for the Shan-Chen
partgrad3 particle gradient for the Shan-Chen
*delta_j Pointer for the weighting of particle momentum (Input)
node_index node index around (8) particle (Input)
node_f Pointer to the node force (Output).
Definition at line 2179 of file lbgpu_cuda.cu.
References atomicadd(), LB_node_force_gpu::force, LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, and para.
Referenced by calc_fluid_particle_ia().
__device__ void calc_node_force_three_point_couple (float * delta, float * delta_j, unsigned int * node_index, LB_node_force_gpu node_f)
calcutlation of the node force caused by the particles, with atomicadd due to avoiding race conditions (Eq.
(14) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
Parameters
*delta Pointer for the weighting of particle position (Input)
*delta_j Pointer for the weighting of particle momentum (Input)
node_index node index around (8) particle (Input)
node_f Pointer to the node force (Output).
Definition at line 1744 of file lbgpu_cuda.cu.
References atomicadd(), LB_node_force_gpu::force, i, LB_parameters_gpu::number_of_nodes, and para.
Referenced by calc_fluid_particle_ia_three_point_couple().
__device__ __inline__ void calc_shanchen_contribution (LB_nodes_gpu n_a, int component_index, int x, int y, int z, float * p)
Definition at line 2571 of file lbgpu_cuda.cu.
References calc_massmode(), LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, and para.
Referenced by lb_shanchen_GPU().
__device__ void calc_values (LB_nodes_gpu n_a, float * mode, LB_rho_v_gpu * d_v, LB_node_force_gpu node_f, unsigned int index)
function used to calc physical values of every node
Parameters
n_a Pointer to local node residing in array a for boundary flag(Input)
mode Pointer to the local register values mode (Input)
d_v Pointer to local device values (Input/Output)
node_f Pointer to local node force (Input)
index node index / thread index (Input)
re-construct the real density remember that the populations are stored as differences to their equilibrium value
if forces are present, the momentum density is redefined to inlcude one half-step of the force action. See the Chapman-Enskog expansion in [Ladd & Verberg].
Definition at line 1437 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_nodes_gpu::boundary, LB_node_force_gpu::force, LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, para, LB_parameters_gpu::rho, LB_rho_v_gpu::rho, and LB_rho_v_gpu::v.
__device__ void calc_values_from_m_in_LB_units (float * mode_single, LB_rho_v_gpu * d_v_single, float * rho_out, float * j_out, float * pi_out)
function used to calculate hydrodynamic fields in MD units.
Parameters
mode_single Pointer to the local register values mode (Input)
d_v_single Pointer to local device values (Input)
rho_out Pointer to density (Output)
j_out Pointer to momentum (Output)
pi_out Pointer to pressure tensor (Output)
Definition at line 1368 of file lbgpu_cuda.cu.
References LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_shear, LB_COMPONENTS, LBQ, para, LB_rho_v_gpu::rho, and LB_rho_v_gpu::v.
Referenced by set_u_from_rho_v_pi().
__device__ void calc_values_in_MD_units (LB_nodes_gpu n_a, float * mode, LB_rho_v_pi_gpu * d_p_v, LB_rho_v_gpu * d_v, LB_node_force_gpu node_f, unsigned int index, unsigned int print_index)
function used to calculate hydrodynamic fields in MD units.
Parameters
n_a Pointer to local node residing in array a for boundary flag(Input)
mode Pointer to the local register values mode (Input)
d_p_v Pointer to local print values (Output)
d_v Pointer to local device values (Input)
node_f Pointer to local node force (Input)
index node index / thread index (Input)
print_index node index / thread index (Output)
Definition at line 1249 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_nodes_gpu::boundary, LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_shear, i, LB_COMPONENTS, LBQ, para, LB_rho_v_pi_gpu::pi, LB_rho_v_gpu::rho, LB_rho_v_pi_gpu::rho, LB_parameters_gpu::tau, update_rho_v(), LB_rho_v_gpu::v, and LB_rho_v_pi_gpu::v.
Referenced by get_mesoscopic_values_in_MD_units(), and lb_print_node().
__device__ void calc_viscous_force (LB_nodes_gpu n_a, float * delta, float * partgrad1, float * partgrad2, float * partgrad3, CUDA_particle_data * particle_data, float * particle_force, CUDA_fluid_composition * fluid_composition, unsigned int part_index, LB_randomnr_gpu * rn_part, float * delta_j, unsigned int * node_index, LB_rho_v_gpu * d_v, int flag_cs)
(Eq.
(12) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
Parameters
n_a Pointer to local node residing in array a (Input)
partgrad1 particle gradient for the Shan-Chen
partgrad2 particle gradient for the Shan-Chen
partgrad3 particle gradient for the Shan-Chen
*delta Pointer for the weighting of particle position (Output)
*delta_j Pointer for the weighting of particle momentum (Output)
*particle_data Pointer to the particle position and velocity (Input)
*particle_force Pointer to the particle force (Input)
*fluid_composition Pointer to the fluid composition (Input)
part_index particle id / thread id (Input)
*rn_part Pointer to randomnumber array of the particle
node_index node index around (8) particle (Output)
*d_v Pointer to local device values
flag_cs Determine if we are at the centre (0, typical) or at the source (1, swimmer only)
calculate viscous force take care to rescale velocities with time_step and transform to MD units (Eq. (9) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
add stochastic force of zero mean (Ahlrichs, Duenweg equ. 15)
delta_j for transform momentum transfer to lattice units which is done in calc_node_force (Eq. (12) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
Definition at line 1891 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, calc_mode(), LB_parameters_gpu::friction, gaussian_random(), gaussian_random_cut(), interpolation_two_point_coupling(), LB_COMPONENTS, LB_parameters_gpu::lb_coupl_pref, LB_parameters_gpu::lb_coupl_pref2, para, random_01(), LB_randomnr_gpu::randomnr, LB_parameters_gpu::rho, LB_parameters_gpu::tau, and LB_parameters_gpu::time_step.
Referenced by calc_fluid_particle_ia().
__device__ void calc_viscous_force_three_point_couple (LB_nodes_gpu n_a, float * delta, CUDA_particle_data * particle_data, float * particle_force, unsigned int part_index, LB_randomnr_gpu * rn_part, float * delta_j, unsigned int * node_index, LB_rho_v_gpu * d_v, int flag_cs)
(Eq.
(12) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
Parameters
n_a Pointer to local node residing in array a (Input)
*delta Pointer for the weighting of particle position (Output)
*delta_j Pointer for the weighting of particle momentum (Output)
*particle_position Pointer to the particle position (Input)
*rn_part Pointer to randomnumber array of the particle
node_index node index around (8) particle (Output)
*d_v Pointer to local device values
flag_cs Determine if we are at the centre (0, typical) or at the source (1, swimmer only)
calculate viscous force take care to rescale velocities with time_step and transform to MD units (Eq. (9) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
add stochastic force of zero mean (Ahlrichs, Duenweg equ. 15)
delta_j for transform momentum transfer to lattice units which is done in calc_node_force (Eq. (12) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
Definition at line 1612 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, ENGINE, LB_parameters_gpu::friction, gaussian_random(), gaussian_random_cut(), interpolation_three_point_coupling(), LB_COMPONENTS, LB_parameters_gpu::lb_coupl_pref, LB_parameters_gpu::lb_coupl_pref2, para, random_01(), LB_randomnr_gpu::randomnr, LB_parameters_gpu::tau, and LB_parameters_gpu::time_step.
Referenced by calc_fluid_particle_ia_three_point_couple().
__global__ void fill_lb_radial_velocity_profile (LB_nodes_gpu n_a, radial_profile_data * pdata, float * data, LB_node_force_gpu node_f)
Definition at line 3784 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, radial_profile_data::center, LB_parameters_gpu::dim_z, get_interpolated_velocity(), radial_profile_data::maxphi, radial_profile_data::maxr, radial_profile_data::maxz, radial_profile_data::minphi, radial_profile_data::minr, radial_profile_data::minz, para, radial_profile_data::phibins, radial_profile_data::rbins, and radial_profile_data::zbins.
Referenced by statistics_observable_lbgpu_radial_velocity_profile().
__device__ void gaussian_random (LB_randomnr_gpu * rn)
gaussian random nummber generator for thermalisation
Parameters
*rn Pointer to randomnumber array of the local node node or particle
On every second call two gaussian random numbers are calculated via the Box-Muller transformation.
draw two uniform random numbers in the unit circle
perform Box-Muller transformation
Definition at line 211 of file lbgpu_cuda.cu.
References random_01(), and LB_randomnr_gpu::randomnr.
Referenced by calc_particle_lattice_ia(), calc_viscous_force(), calc_viscous_force_three_point_couple(), friction_therm0_nptiso(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), friction_thermV_nptiso(), lb_thermalize_modes(), partial_momentum_update(), propagate_pos_bd(), random_wrapper(), and simple_momentum_update().
__device__ void gaussian_random_cut (LB_randomnr_gpu * rn)
randomgenerator which generates numbers between -2 sigma and 2 sigma in the form of a Gaussian with standard deviation sigma=1.118591404 resulting in an actual standard deviation of 1.
Parameters
*rn Pointer to randomnumber array of the local node or particle
On every second call two gaussian random numbers are calculated via the Box-Muller transformation.
draw two uniform random numbers in the unit circle
perform Box-Muller transformation and cutoff the ends and replace with flat noise
Definition at line 167 of file lbgpu_cuda.cu.
References random_01(), and LB_randomnr_gpu::randomnr.
Referenced by calc_particle_lattice_ia(), calc_viscous_force(), calc_viscous_force_three_point_couple(), friction_therm0_nptiso(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), friction_thermV_nptiso(), lb_thermalize_modes(), and random_wrapper().
__device__ void get_interpolated_velocity (LB_nodes_gpu n_a, float * r, float * u, LB_node_force_gpu node_f, int asdf)
see ahlrichs + duenweg page 8227 equ (10) and (11)
Definition at line 3703 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_nodes_gpu::boundary, calc_m_from_n(), LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, i, LB_COMPONENTS, my_left, para, LB_parameters_gpu::rho, and LB_parameters_gpu::tau.
Referenced by fill_lb_radial_velocity_profile().
__global__ void get_mesoscopic_values_in_MD_units (LB_nodes_gpu n_a, LB_rho_v_pi_gpu * p_v, LB_rho_v_gpu * d_v, LB_node_force_gpu node_f)
get physical values of the nodes (density, velocity, ...)
Parameters
n_a Pointer to local node residing in array a (Input)
*p_v Pointer to local print values (Output)
*d_v Pointer to local device values (Input)
node_f The forces on the LB nodes
Definition at line 2998 of file lbgpu_cuda.cu.
References calc_m_from_n(), calc_values_in_MD_units(), LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, and para.
Referenced by lb_get_values_GPU().
__device__ void index_to_xyz (unsigned int index, unsigned int * xyz)
tranformation from 1d array-index to xyz
Parameters
index node index / thread index (Input)
xyz Pointer to calculated xyz array (Output)
Definition at line 256 of file lbgpu_cuda.cu.
References LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, and para.
Referenced by bounce_back_boundaries(), calc_n_from_modes_push(), lb_shanchen_GPU(), and lb_shanchen_set_boundaries().
__global__ void init_boundaries (int * boundary_node_list, int * boundary_index_list, int number_of_boundnodes, LB_nodes_gpu n_a, LB_nodes_gpu n_b)
set the boundary flag for all boundary nodes
Parameters
boundary_node_list The indices of the boundary nodes
boundary_index_list The flag representing the corresponding boundary
number_of_boundnodes The number of boundary nodes
n_a Pointer to local node residing in array a (Input)
n_b Pointer to local node residing in array b (Input)
Definition at line 2781 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary.
Referenced by lb_init_boundaries_GPU().
__global__ void init_extern_nodeforces (int n_extern_nodeforces, LB_extern_nodeforce_gpu * extern_nodeforces, LB_node_force_gpu node_f)
set extern force on single nodes kernel
Parameters
n_extern_nodeforces number of nodes (Input)
*extern_nodeforces Pointer to extern node force array (Input)
node_f node force struct (Output)
Definition at line 2528 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_node_force_gpu::force, LB_extern_nodeforce_gpu::force, LB_extern_nodeforce_gpu::index, LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, para, and LB_parameters_gpu::tau.
Referenced by lb_init_extern_nodeforces_GPU().
__global__ void integrate (LB_nodes_gpu n_a, LB_nodes_gpu n_b, LB_rho_v_gpu * d_v, LB_node_force_gpu node_f, EK_parameters * ek_parameters_gpu)
integrationstep of the lb-fluid-solver
Parameters
n_a Pointer to local node residing in array a (Input)
n_b Pointer to local node residing in array b (Input)
*d_v Pointer to local device values (Input)
node_f Pointer to local node force (Input)
ek_parameters_gpu Pointer to the parameters for the electrokinetics (Input)
every node is connected to a thread via the index
the 19 moments (modes) are only temporary register values
storing the seed into a register value
calc_m_from_n
lb_relax_modes
lb_thermalize_modes
if external force is used apply node force
lb_calc_n_from_modes_push
calc of velocity densities and streaming with pbc
rewriting the seed back to the global memory
Definition at line 2813 of file lbgpu_cuda.cu.
References apply_forces(), calc_m_from_n(), calc_n_from_modes_push(), LB_parameters_gpu::fluct, LB_COMPONENTS, normalize_modes(), LB_parameters_gpu::number_of_nodes, LB_parameters_gpu::number_of_particles, para, relax_modes(), LB_nodes_gpu::seed, LB_randomnr_gpu::seed, and thermalize_modes().
Referenced by lb_integrate_GPU().
__device__ __inline__ void interpolation_three_point_coupling (LB_nodes_gpu n_a, float * particle_position, unsigned int * node_index, LB_rho_v_gpu * d_v, float * delta, float * interpolated_u)
(Eq.
(12) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
Parameters
n_a Pointer to local node residing in array a (Input)
*delta Pointer for the weighting of particle position (Output)
*particle_data Pointer to the particle position and velocity (Input)
*particle_force Pointer to the particle force (Input)
part_index particle id / thread id (Input)
node_index node index around (8) particle (Output)
*d_v Pointer to local device values
*interpolated_u Pointer to the interpolated velocity
see Duenweg and Ladd http://arxiv.org/abs/0803.2826 eqn. 301
the i index is left node, nearest node, right node
note the -0.5f is to account for the shift of the LB grid relative to the MD
the +0.5 is to turn the floorf into a round function
Here we collect the nodes for the three point coupling scheme (27 nodes in 3d) with the analogous numbering scheme of the two point coupling scheme
Definition at line 1534 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_nodes_gpu::boundary, calc_m_from_n(), LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, i, LB_COMPONENTS, para, and LB_parameters_gpu::rho.
Referenced by calc_viscous_force_three_point_couple().
__device__ __inline__ void interpolation_two_point_coupling (LB_nodes_gpu n_a, float * particle_position, unsigned int * node_index, float * mode, LB_rho_v_gpu * d_v, float * delta, float * interpolated_u)
(Eq.
(12) Ahlrichs and Duenweg, JCP 111(17):8225 (1999))
Parameters
n_a Pointer to local node residing in array a (Input)
node_index node index around (8) particle (Output)
*particle_position Pointer to the particle position (Input)
*mode Pointer to the 19 modes for current lattice point
*d_v Pointer to local device values
*interpolated_u Pointer to the interpolated velocity
*delta Pointer for the weighting of particle position (Output)
Definition at line 1795 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_nodes_gpu::boundary, calc_m_from_n(), LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, i, LB_COMPONENTS, para, LB_parameters_gpu::rho, and LB_rho_v_gpu::v.
Referenced by calc_viscous_force().
void lb_calc_fluid_mass_GPU (double * mass)
setup and call kernel to calculate the total momentum of the hole fluid
Parameters
*mass value of the mass calcutated on the GPU
values for the kernel call
Definition at line 3424 of file lbgpu_cuda.cu.
References calc_mass(), cuda_safe_mem, KERNELCALL, lbpar_gpu, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_analyze_fluid_mass_gpu().
void lb_calc_fluid_momentum_GPU (double * host_mom)
setup and call kernel to calculate the total momentum of the whole fluid
Parameters
host_mom value of the momentum calcutated on the GPU
values for the kernel call
Definition at line 3448 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, cuda_safe_mem, KERNELCALL, lbpar_gpu, momentum(), LB_parameters_gpu::number_of_nodes, and LB_parameters_gpu::tau.
Referenced by tclcommand_analyze_fluid_parse_momentum_gpu().
void lb_calc_fluid_temperature_GPU (double * host_temp)
setup and call kernel to calculate the temperature of the hole fluid
Parameters
host_temp value of the temperatur calcutated on the GPU
values for the kernel call
Definition at line 3498 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, cuda_safe_mem, KERNELCALL, LB_COMPONENTS, lbpar_gpu, LB_parameters_gpu::number_of_nodes, LB_parameters_gpu::rho, LB_parameters_gpu::tau, and temperature().
Referenced by tclcommand_analyze_fluid_parse_temperature_gpu().
void lb_calc_particle_lattice_ia_gpu ()
setup and call particle kernel from the host
call of the particle kernel
values for the particle kernel
only other option is the three point coupling scheme
Definition at line 3330 of file lbgpu_cuda.cu.
References calc_fluid_particle_ia(), calc_fluid_particle_ia_three_point_couple(), errexit(), gpu_get_fluid_composition_pointer(), gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), gpu_get_particle_seed_pointer(), KERNELCALL, LB_parameters_gpu::lb_couple_switch, LB_COUPLE_TWO_POINT, lbpar_gpu, and LB_parameters_gpu::number_of_particles.
Referenced by force_calc().
void lb_calc_shanchen_GPU ()
values for the kernel call
Definition at line 3533 of file lbgpu_cuda.cu.
References KERNELCALL, lb_shanchen_GPU(), lb_shanchen_set_boundaries(), lbpar_gpu, n_lb_boundaries, and LB_parameters_gpu::number_of_nodes.
Referenced by lattice_boltzmann_calc_shanchen_gpu().
__global__ void lb_get_boundaries (LB_nodes_gpu n_a, unsigned int * device_bound_array)
get boundary flags
Parameters
n_a Pointer to local node residing in array a (Input)
device_bound_array Pointer to local device values (Input)
Definition at line 3013 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, LB_parameters_gpu::number_of_nodes, and para.
Referenced by lb_get_boundary_flags_GPU().
__global__ void lb_get_boundary_flag (int single_nodeindex, unsigned int * device_flag, LB_nodes_gpu n_a)
print single node boundary flag
Parameters
single_nodeindex index of the node (Input)
*device_flag Pointer to result storage array (Input)
n_a Pointer to local node residing in array a (Input)
Definition at line 3088 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary.
Referenced by lb_get_boundary_flag_GPU().
void lb_get_boundary_flag_GPU (int single_nodeindex, unsigned int * host_flag)
setup and call kernel to get the boundary flag of a single node
Parameters
single_nodeindex number of the node to get the flag for
host_flag her goes the value of the boundary flag
Definition at line 3589 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, and lb_get_boundary_flag().
Referenced by lb_lbnode_get_boundary().
void lb_get_boundary_flags_GPU (unsigned int * host_bound_array)
get all the boundary flags for all nodes
Parameters
host_bound_array here go the values of the boundary flag
values for the kernel call
Definition at line 3386 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, lb_get_boundaries(), lbpar_gpu, and LB_parameters_gpu::number_of_nodes.
Referenced by lb_lbfluid_print_boundary(), and lb_lbfluid_print_vtk_boundary().
void lb_get_boundary_force_pointer (float ** pointeradress)
Definition at line 3113 of file lbgpu_cuda.cu.
References lb_boundary_force.
void lb_get_device_values_pointer (LB_rho_v_gpu ** pointeradress)
Definition at line 3119 of file lbgpu_cuda.cu.
References device_rho_v.
void lb_get_lbpar_pointer (LB_parameters_gpu ** pointeradress)
Definition at line 3108 of file lbgpu_cuda.cu.
References lbpar_gpu.
void lb_get_para_pointer (LB_parameters_gpu ** pointeradress)
Definition at line 3100 of file lbgpu_cuda.cu.
References errexit(), and para.
Referenced by InitCUDA_IBM().
void lb_get_values_GPU (LB_rho_v_pi_gpu * host_values)
setup and call kernel for getting macroscopic fluid values of all nodes
Parameters
*host_values struct to save the gpu values
values for the kernel call
Definition at line 3368 of file lbgpu_cuda.cu.
References cuda_safe_mem, get_mesoscopic_values_in_MD_units(), KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and size_of_rho_v_pi.
Referenced by lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_density(), and lb_lbfluid_print_vtk_velocity().
void lb_gpu_get_boundary_forces (double * forces)
Definition at line 3690 of file lbgpu_cuda.cu.
References cuda_safe_mem, free, i, lb_boundary_force, malloc, and n_lb_boundaries.
Referenced by lbboundary_get_force().
void lb_init_boundaries_GPU (int host_n_lb_boundaries, int number_of_boundnodes, int * host_boundary_node_list, int * host_boundary_index_list, float * host_lb_boundary_velocity)
setup and call boundaries from the host
Parameters
host_n_lb_boundaries number of LB boundaries
number_of_boundnodes number of boundnodes
host_boundary_node_list The indices of the boundary nodes
host_boundary_index_list The flag representing the corresponding boundary
host_lb_boundary_velocity The constant velocity at the boundary, set by the user (Input)
values for the kernel call
Definition at line 3244 of file lbgpu_cuda.cu.
References boundary_index_list, boundary_node_list, cuda_safe_mem, init_boundaries(), KERNELCALL, lb_boundary_force, lb_boundary_velocity, lbpar_gpu, n_lb_boundaries, n_lb_boundaries_gpu, LB_parameters_gpu::number_of_nodes, pdb_boundary_lattice, reset_boundaries(), and size_of_boundindex.
Referenced by lb_init_boundaries().
void lb_init_extern_nodeforces_GPU (int n_extern_nodeforces, LB_extern_nodeforce_gpu * host_extern_nodeforces, LB_parameters_gpu * lbpar_gpu)
setup and call extern single node force initialization from the host
Parameters
n_extern_nodeforces number of nodes on which the external force has to be applied
*host_extern_nodeforces Pointer to the host extern node forces
*lbpar_gpu Pointer to host parameter struct
Definition at line 3309 of file lbgpu_cuda.cu.
References cuda_safe_mem, LB_parameters_gpu::external_force, init_extern_nodeforces(), KERNELCALL, para, and size_of_extern_nodeforces.
Referenced by lb_lbnode_set_extforce_GPU().
void lb_init_GPU (LB_parameters_gpu * lbpar_gpu)
initialization for the lb gpu fluid called from host
Parameters
*lbpar_gpu Pointer to parameters to setup the lb field
Allocate structs in device memory
write parameters in const memory
check flag if lb gpu init works
values for the kernel call
calc of velocitydensities from given parameters and initialize the Node_Force array with zero
Definition at line 3126 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, calc_n_from_rho_j_pi(), cuda_safe_mem, ek_initialized, ek_initialized_gpu, errexit(), extended_values_flag, LB_node_force_gpu::force, LB_node_force_gpu::force_buf, free, free_and_realloc, gpu_check, h_gpu_check, intflag, KERNELCALL, LB_COMPONENTS, malloc, nodes_a, LB_parameters_gpu::number_of_nodes, para, reinit_node_force(), reset_boundaries(), LB_node_force_gpu::scforce, LB_nodes_gpu::seed, size_of_rho_v, size_of_rho_v_pi, and LB_nodes_gpu::vd.
Referenced by lb_init_gpu().
void lb_integrate_GPU ()
integration kernel for the lb gpu fluid update called from host
values for the kernel call
call of fluid step
Definition at line 3650 of file lbgpu_cuda.cu.
References apply_boundaries(), cuda_safe_mem, integrate(), intflag, KERNELCALL, lb_boundary_force, lb_boundary_velocity, lb_ek_parameters_gpu, lbpar_gpu, n_lb_boundaries, nodes_a, nodes_b, and LB_parameters_gpu::number_of_nodes.
Referenced by lattice_boltzmann_update_gpu().
void lb_load_checkpoint_GPU (float * host_checkpoint_vd, unsigned int * host_checkpoint_seed, unsigned int * host_checkpoint_boundary, lbForceFloat * host_checkpoint_force)
setup and call kernel for setting macroscopic fluid values of all nodes
Parameters
*host_checkpoint_vd struct to save the gpu populations
*host_checkpoint_seed struct to save the nodes' seeds for the lb on the gpu
*host_checkpoint_boundary struct to save the boundary nodes
*host_checkpoint_force struct to save the forces on the nodes
Definition at line 3573 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, cuda_safe_mem, LB_node_force_gpu::force, intflag, lbpar_gpu, nodes_a, LB_parameters_gpu::number_of_nodes, LB_nodes_gpu::seed, and LB_nodes_gpu::vd.
Referenced by lb_lbfluid_load_checkpoint().
__global__ void lb_print_node (int single_nodeindex, LB_rho_v_pi_gpu * d_p_v, LB_nodes_gpu n_a, LB_rho_v_gpu * d_v, LB_node_force_gpu node_f)
print single node values kernel
Parameters
single_nodeindex index of the node (Input)
*d_p_v Pointer to result storage array (Input)
n_a Pointer to local node residing in array a (Input)
*d_v Pointer to local device values
node_f Pointer to local node force
Definition at line 3030 of file lbgpu_cuda.cu.
References calc_m_from_n(), calc_values_in_MD_units(), and LB_COMPONENTS.
Referenced by lb_print_node_GPU().
void lb_print_node_GPU (int single_nodeindex, LB_rho_v_pi_gpu * host_print_values)
setup and call kernel for getting macroscopic fluid values of a single node
Definition at line 3405 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, and lb_print_node().
Referenced by lb_lbnode_get_pi_neq(), lb_lbnode_get_rho(), and lb_lbnode_get_u().
void lb_realloc_particles_GPU_leftovers (LB_parameters_gpu * lbpar_gpu)
Definition at line 3230 of file lbgpu_cuda.cu.
References cuda_safe_mem, and para.
Referenced by lb_realloc_particles_gpu().
void lb_reinit_extern_nodeforce_GPU (LB_parameters_gpu * lbpar_gpu)
setup and call extern single node force initialization from the host
Parameters
*lbpar_gpu Pointer to host parameter struct
values for the kernel call
Definition at line 3291 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, LB_parameters_gpu::number_of_nodes, para, and reinit_node_force().
Referenced by lb_lbfluid_set_ext_force().
void lb_reinit_GPU (LB_parameters_gpu * lbpar_gpu)
reinitialization for the lb gpu fluid called from host
Parameters
*lbpar_gpu Pointer to parameters to setup the lb field
write parameters in const memory
values for the kernel call
calc of velocity densities from given parameters and initialize the Node_Force array with zero
Definition at line 3215 of file lbgpu_cuda.cu.
References calc_n_from_rho_j_pi(), cuda_safe_mem, gpu_check, KERNELCALL, LB_parameters_gpu::number_of_nodes, and para.
Referenced by lb_reinit_fluid_gpu().
void lb_remove_fluid_momentum_GPU (void)
setup and call kernel to remove the net momentum of the whole fluid
values for the kernel call
Definition at line 3473 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, lbpar_gpu, momentum(), LB_parameters_gpu::number_of_nodes, and remove_momentum().
Referenced by lattice_boltzmann_update_gpu().
void lb_save_checkpoint_GPU (float * host_checkpoint_vd, unsigned int * host_checkpoint_seed, unsigned int * host_checkpoint_boundary, lbForceFloat * host_checkpoint_force)
setup and call kernel for getting macroscopic fluid values of all nodes
Parameters
*host_checkpoint_vd struct to save the gpu populations
*host_checkpoint_seed struct to save the nodes' seeds for the lb on the gpu
*host_checkpoint_boundary struct to save the boundary nodes
*host_checkpoint_force struct to save the forces on the nodes
Definition at line 3558 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, cuda_safe_mem, LB_node_force_gpu::force, lbpar_gpu, LB_parameters_gpu::number_of_nodes, LB_nodes_gpu::seed, and LB_nodes_gpu::vd.
Referenced by lb_lbfluid_save_checkpoint().
void lb_set_node_rho_GPU (int single_nodeindex, float * host_rho)
set the density at a single node
Parameters
single_nodeindex the node to set the velocity for
*host_rho the density to set
Definition at line 3609 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, LB_COMPONENTS, and set_rho().
Referenced by lb_lbnode_set_rho().
void lb_set_node_velocity_GPU (int single_nodeindex, float * host_velocity)
set the net velocity at a single node
Parameters
single_nodeindex the node to set the velocity for
host_velocity the velocity to set
Definition at line 3626 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, and set_u_from_rho_v_pi().
Referenced by lb_lbnode_set_u().
__global__ void lb_shanchen_GPU (LB_nodes_gpu n_a, LB_node_force_gpu node_f)
function to calc shanchen forces
Parameters
n_a Pointer to local node residing in array a(Input)
node_f Pointer to local node force (Input)
Definition at line 2670 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, calc_massmode(), calc_shanchen_contribution(), LB_parameters_gpu::coupling, LB_node_force_gpu::force, index_to_xyz(), LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, para, reset_LB_forces(), and LB_node_force_gpu::scforce.
Referenced by lb_calc_shanchen_GPU().
__global__ void lb_shanchen_set_boundaries (LB_nodes_gpu n_curr)
Definition at line 2943 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, index_to_xyz(), LB_COMPONENTS, LBQ, LB_parameters_gpu::number_of_nodes, para, and LB_nodes_gpu::vd.
Referenced by lb_calc_shanchen_GPU().
__global__ void momentum (LB_nodes_gpu n_a, LB_rho_v_gpu * d_v, LB_node_force_gpu node_f, float * sum)
Definition at line 3043 of file lbgpu_cuda.cu.
References atomicadd(), LB_nodes_gpu::boundary, calc_mode(), LB_node_force_gpu::force, LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, and para.
Referenced by lb_calc_fluid_momentum(), lb_calc_fluid_momentum_GPU(), lb_remove_fluid_momentum_GPU(), predict_momentum_particles(), and tclcommand_analyze_parse_and_print_momentum().
__device__ void normalize_modes (float * mode)
normalization of the modes need befor backtransformation into velocity space
Parameters
mode Pointer to the local register values mode (Input/Output)
normalization factors enter in the back transformation
Definition at line 734 of file lbgpu_cuda.cu.
References LB_COMPONENTS, and LBQ.
Referenced by integrate().
__device__ void random_01 (LB_randomnr_gpu * rn)
randomgenerator which generates numbers [0,1]
Parameters
*rn Pointer to randomnumber array of the local node or particle
Definition at line 150 of file lbgpu_cuda.cu.
References LB_randomnr_gpu::randomnr, and LB_randomnr_gpu::seed.
Referenced by calc_viscous_force(), calc_viscous_force_three_point_couple(), gaussian_random(), gaussian_random_cut(), and random_wrapper().
__device__ void random_wrapper (LB_randomnr_gpu * rn)
Definition at line 232 of file lbgpu_cuda.cu.
References gaussian_random(), gaussian_random_cut(), random_01(), LB_randomnr_gpu::randomnr, and sqrt12.
Referenced by thermalize_modes().
__global__ void reinit_node_force (LB_node_force_gpu node_f)
(re-)initialization of the node force / set up of external force in lb units
Parameters
node_f Pointer to local node force (Input)
Definition at line 2491 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::ext_force, LB_parameters_gpu::external_force, LB_node_force_gpu::force, LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, para, and LB_parameters_gpu::tau.
Referenced by lb_init_GPU(), and lb_reinit_extern_nodeforce_GPU().
void reinit_parameters_GPU (LB_parameters_gpu * lbpar_gpu)
reinit of params
Parameters
*lbpar_gpu struct containing the paramters of the fluid
write parameters in const memory
Definition at line 3644 of file lbgpu_cuda.cu.
References cuda_safe_mem, and para.
Referenced by lb_reinit_parameters_gpu().
__device__ void relax_modes (float * mode, unsigned int index, LB_node_force_gpu node_f, LB_rho_v_gpu * d_v)
lb_relax_modes, means collision update of the modes
Parameters
index node index / thread index (Input)
mode Pointer to the local register values mode (Input/Output)
node_f Pointer to local node force (Input)
*d_v Pointer to local device values
equilibrium part of the stress modes (eq13 schiller)
in Shan-Chen we have to relax the momentum modes as well using the mobility, but the total momentum is conserved
relax the stress modes (eq14 schiller)
relax the ghost modes (project them out)
ghost modes have no equilibrium part due to orthogonality
Definition at line 599 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_even, LB_parameters_gpu::gamma_mobility, LB_parameters_gpu::gamma_odd, LB_parameters_gpu::gamma_shear, LB_COMPONENTS, LBQ, para, LB_parameters_gpu::rho, update_rho_v(), and LB_rho_v_gpu::v.
Referenced by integrate().
__global__ void remove_momentum (LB_nodes_gpu n_a, LB_rho_v_gpu * d_v, LB_node_force_gpu node_f, float * sum)
Definition at line 3071 of file lbgpu_cuda.cu.
References LB_node_force_gpu::force, LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, and para.
Referenced by lb_remove_fluid_momentum_GPU().
__global__ void reset_boundaries (LB_nodes_gpu n_a, LB_nodes_gpu n_b)
reset the boundary flag of every node
Parameters
n_a Pointer to local node residing in array a (Input)
n_b Pointer to local node residing in array b (Input)
Definition at line 2796 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, LB_parameters_gpu::number_of_nodes, and para.
Referenced by lb_init_boundaries_GPU(), and lb_init_GPU().
__device__ void reset_LB_forces (unsigned int index, LB_node_force_gpu node_f, bool buffer = true)
Definition at line 502 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::ext_force, LB_parameters_gpu::external_force, LB_node_force_gpu::force, LB_node_force_gpu::force_buf, LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, para, and LB_parameters_gpu::tau.
Referenced by apply_forces(), lb_shanchen_GPU(), and reset_LB_forces_kernel().
void reset_LB_forces_GPU (bool buffer)
Resets the forces on the fluid nodes.
Definition at line 547 of file lbgpu_cuda.cu.
References KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and reset_LB_forces_kernel().
__global__ void reset_LB_forces_kernel (LB_node_force_gpu node_f, bool buffer = true)
Definition at line 540 of file lbgpu_cuda.cu.
References LB_parameters_gpu::number_of_nodes, para, and reset_LB_forces().
Referenced by reset_LB_forces_GPU().
__global__ void set_rho (LB_nodes_gpu n_a, LB_rho_v_gpu * d_v, int single_nodeindex, float * rho)
kernel to set the local density
Parameters
n_a the current nodes array (double buffering!)
single_nodeindex the node to set the velocity for
rho the density to set
d_v Pointer to the local modes
default values for fields in lattice units
Definition at line 2736 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_COMPONENTS, LBQ, LB_parameters_gpu::number_of_nodes, para, LB_parameters_gpu::rho, LB_rho_v_gpu::rho, and LB_nodes_gpu::vd.
Referenced by lb_set_node_rho_GPU().
__global__ void set_u_from_rho_v_pi (LB_nodes_gpu n_a, int single_nodeindex, float * velocity, LB_rho_v_gpu * d_v, LB_node_force_gpu node_f)
kernel to calculate local populations from hydrodynamic fields from given flow field velocities.
The mapping is given in terms of the equilibrium distribution.
Eq. (2.15) Ladd, J. Fluid Mech. 271, 295-309 (1994) Eq. (4) in Berk Usta, Ladd and Butler, JCP 122, 094902 (2005)
Parameters
n_a the current nodes array (double buffering!)
single_nodeindex the node to set the velocity for
velocity the velocity to set
*d_v Pointer to local device values (Input)
*node_f Pointer to node forces (Input)
Definition at line 2338 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, calc_m_from_n(), calc_values_from_m_in_LB_units(), LB_COMPONENTS, LBQ, LB_parameters_gpu::number_of_nodes, para, LB_parameters_gpu::rho, update_rho_v(), and LB_nodes_gpu::vd.
Referenced by lb_set_node_velocity_GPU().
int statistics_observable_lbgpu_radial_velocity_profile (radial_profile_data * pdata, double * A, unsigned int n_A)
Definition at line 3847 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, cuda_safe_mem, LB_parameters_gpu::dim_z, fill_lb_radial_velocity_profile(), free, i, KERNELCALL, lbpar_gpu, malloc, radial_profile_data::maxr, radial_profile_data::phibins, radial_profile_data::rbins, and radial_profile_data::zbins.
Referenced by observable_calc_lb_radial_velocity_profile().
__global__ void temperature (LB_nodes_gpu n_a, float * cpu_jsquared, int * number_of_non_boundary_nodes)
calculate temperature of the fluid kernel
Parameters
*cpu_jsquared Pointer to result storage value (Output)
n_a Pointer to local node residing in array a (Input)
Definition at line 1763 of file lbgpu_cuda.cu.
References atomicAdd(), atomicadd(), LB_nodes_gpu::boundary, calc_mode(), LB_COMPONENTS, LB_parameters_gpu::number_of_nodes, and para.
Referenced by lb_calc_fluid_temperature_GPU().
__device__ void thermalize_modes (float * mode, unsigned int index, LB_randomnr_gpu * rn)
thermalization of the modes with gaussian random numbers
Parameters
index node index / thread index (Input)
mode Pointer to the local register values mode (Input/Output)
*rn Pointer to randomnumber array of the local node
mass mode
momentum modes
stress modes
ghost modes
Definition at line 666 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_mobility, LB_parameters_gpu::gamma_shear, LB_COMPONENTS, LBQ, LB_parameters_gpu::mu, para, random_wrapper(), LB_randomnr_gpu::randomnr, and LB_parameters_gpu::rho.
Referenced by integrate().
__device__ void update_rho_v (float * mode, unsigned int index, LB_node_force_gpu node_f, LB_rho_v_gpu * d_v)
re-construct the real density remember that the populations are stored as differences to their equilibrium value
if forces are present, the momentum density is redefined to inlcude one half-step of the force action. See the Chapman-Enskog expansion in [Ladd & Verberg].
Definition at line 557 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_node_force_gpu::force, LB_COMPONENTS, LBQ, LB_parameters_gpu::number_of_nodes, para, LB_parameters_gpu::rho, LB_rho_v_gpu::rho, and LB_rho_v_gpu::v.
Referenced by calc_n_from_rho_j_pi(), calc_values_in_MD_units(), relax_modes(), and set_u_from_rho_v_pi().
Variable Documentation
int* boundary_index_list static
Definition at line 86 of file lbgpu_cuda.cu.
Referenced by lb_init_boundaries_GPU().
int* boundary_node_list static
pointer for bound index array
Definition at line 85 of file lbgpu_cuda.cu.
Referenced by lb_init_boundaries_GPU().
const float c_sound_sq = 1.0f/3.0f static
Definition at line 110 of file lbgpu_cuda.cu.
Referenced by calc_n_from_rho_j_pi().
LB_nodes_gpu* current_nodes = NULL
Definition at line 102 of file lbgpu_cuda.cu.
LB_rho_v_gpu* device_rho_v = NULL static
defining structures residing in global memory
device_rho_v: struct for hydrodynamic fields: this is for internal use (i.e. stores values in LB units) and should not used for printing values
Definition at line 53 of file lbgpu_cuda.cu.
Referenced by lb_get_device_values_pointer().
LB_rho_v_pi_gpu* device_rho_v_pi = NULL static
device_rho_v_pi: extended struct for hydrodynamic fields: this is the interface to tcl, and stores values in MD units.
It should not be used as an input for any LB calculations. TODO: This structure is not yet used, and it is here to allow access to the stress tensor at any timestep, e.g. for future implementations of moving boundary codes
Definition at line 60 of file lbgpu_cuda.cu.
__device__ __constant__ int ek_initialized_gpu = 0 static
Definition at line 92 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU().
int extended_values_flag =0
Definition at line 43 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU().
LB_extern_nodeforce_gpu* extern_nodeforces = NULL static
Definition at line 77 of file lbgpu_cuda.cu.
int* gpu_check = NULL static
pointers for additional cuda check flag
Definition at line 98 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU(), and lb_reinit_GPU().
int* h_gpu_check = NULL static
Definition at line 99 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU().
unsigned int intflag = 1 static
Definition at line 101 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU(), lb_integrate_GPU(), and lb_load_checkpoint_GPU().
float* lb_boundary_force = NULL static
Definition at line 80 of file lbgpu_cuda.cu.
Referenced by lb_get_boundary_force_pointer(), lb_gpu_get_boundary_forces(), lb_init_boundaries_GPU(), and lb_integrate_GPU().
float* lb_boundary_velocity = NULL static
Definition at line 82 of file lbgpu_cuda.cu.
Referenced by lb_init_boundaries_GPU(), and lb_integrate_GPU().
EK_parameters* lb_ek_parameters_gpu
Definition at line 95 of file lbgpu_cuda.cu.
Referenced by lb_integrate_GPU().
__device__ __constant__ int n_lb_boundaries_gpu = 0 static
Definition at line 87 of file lbgpu_cuda.cu.
Referenced by lb_init_boundaries_GPU().
LB_node_force_gpu node_f = {.force=NULL,.scforce=NULL}
struct for node force
Definition at line 75 of file lbgpu_cuda.cu.
LB_nodes_gpu nodes_a = {.vd=NULL,.seed=NULL,.boundary=NULL} static
structs for velocity densities
Definition at line 71 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU(), lb_integrate_GPU(), and lb_load_checkpoint_GPU().
LB_nodes_gpu nodes_b = {.vd=NULL,.seed=NULL,.boundary=NULL} static
Definition at line 72 of file lbgpu_cuda.cu.
Referenced by lb_integrate_GPU().
__device__ __constant__ LB_parameters_gpu para static
parameters residing in constant memory
Definition at line 109 of file lbgpu_cuda.cu.
Referenced by apply_boundaries(), apply_forces(), calc_fluid_particle_ia(), calc_fluid_particle_ia_three_point_couple(), calc_m_from_n(), Calc_m_from_n_IBM(), calc_mass(), calc_massmode(), calc_mode(), calc_n_from_modes_push(), calc_n_from_rho_j_pi(), calc_node_force(), calc_node_force_three_point_couple(), calc_shanchen_contribution(), calc_values(), calc_values_from_m_in_LB_units(), calc_values_in_MD_units(), calc_viscous_force(), calc_viscous_force_three_point_couple(), fill_lb_radial_velocity_profile(), ForcesIntoFluid_Kernel(), get_interpolated_velocity(), get_mesoscopic_values_in_MD_units(), index_to_xyz(), init_extern_nodeforces(), integrate(), interpolation_three_point_coupling(), interpolation_two_point_coupling(), lb_get_boundaries(), lb_get_para_pointer(), lb_init_extern_nodeforces_GPU(), lb_init_GPU(), lb_realloc_particles_GPU_leftovers(), lb_reinit_extern_nodeforce_GPU(), lb_reinit_GPU(), lb_shanchen_GPU(), lb_shanchen_set_boundaries(), momentum(), ParticleVelocitiesFromLB_Kernel(), reinit_node_force(), reinit_parameters_GPU(), relax_modes(), remove_momentum(), reset_boundaries(), reset_LB_forces(), reset_LB_forces_kernel(), ResetLBForces_Kernel(), set_rho(), set_u_from_rho_v_pi(), temperature(), thermalize_modes(), and update_rho_v().
LB_rho_v_pi_gpu* print_rho_v_pi = NULL static
print_rho_v_pi: struct for hydrodynamic fields: this is the interface to tcl, and stores values in MD units.
It should not used as an input for any LB calculations. TODO: in the future, one might want to have several structures for printing separately rho, v, pi without having to compute/store the complete set.
Definition at line 68 of file lbgpu_cuda.cu.
size_t size_of_boundindex static
Definition at line 88 of file lbgpu_cuda.cu.
Referenced by lb_init_boundaries_GPU().
size_t size_of_extern_nodeforces static
Definition at line 106 of file lbgpu_cuda.cu.
Referenced by lb_init_extern_nodeforces_GPU().
size_t size_of_rho_v static
defining size values for allocating global memory
Definition at line 104 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU().
size_t size_of_rho_v_pi static
Definition at line 105 of file lbgpu_cuda.cu.
Referenced by lb_get_values_GPU(), and lb_init_GPU().