ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lbgpu.hpp File Reference
lbgpu.hpp File Reference
Header file for lbgpu.cpp.
#include "utils.hpp"
#include "config.hpp"
#include "statistics_observable.hpp"
Data Structures
struct LB_parameters_gpu
struct LB_rho_v_gpu
Data structure holding the conserved quantities for the Lattice Boltzmann system.
struct LB_rho_v_pi_gpu
struct LB_nodes_gpu
Data structure holding the velocity densities for the Lattice Boltzmann system.
struct LB_randomnr_gpu
Data structure for the randomnr and the seed.
struct LB_node_force_gpu
struct LB_extern_nodeforce_gpu
Macros
#define D3Q19
#define LBQ 19
#define LB_COUPLE_NULL 1
Note these are usef for binary logic so should be powers of 2.
#define LB_COUPLE_TWO_POINT 2
#define LB_COUPLE_THREE_POINT 4
Parameter fields for Lattice Boltzmann
The numbers are referenced in mpi_bcast_lb_params to determine what actions have to take place upon change of the respective parameter.
#define LBPAR_DENSITY 0
fluid density
#define LBPAR_VISCOSITY 1
fluid kinematic viscosity
#define LBPAR_AGRID 2
grid constant for fluid lattice
#define LBPAR_TAU 3
time step for fluid propagation
#define LBPAR_FRICTION 4
friction coefficient for viscous coupling between particles and fluid
#define LBPAR_EXTFORCE 5
external force acting on the fluid
#define LBPAR_BULKVISC 6
fluid bulk viscosity
#define LBPAR_BOUNDARY 7
boundary parameters
#define LBPAR_COUPLING 8
#define LBPAR_MOBILITY 9
Typedefs
typedef double lbForceFloat
Functions
void on_lb_params_change_gpu (int field)
Exported Functions
void lb_GPU_sanity_checks ()
void lb_get_device_values_pointer (LB_rho_v_gpu **pointeradress)
void lb_get_boundary_force_pointer (float **pointeradress)
void lb_get_lbpar_pointer (LB_parameters_gpu **pointeradress)
void lb_get_para_pointer (LB_parameters_gpu **pointeradress)
void lattice_boltzmann_update_gpu ()
lattice boltzmann update gpu called from integrate.cpp
void lb_pre_init_gpu ()
(Pre-)initializes data structures.
void lb_init_gpu ()
Performs a full initialization of the Lattice Boltzmann system.
void lb_reinit_parameters_gpu ()
(Re-)initializes the derived parameters for the Lattice Boltzmann system.
void lb_reinit_fluid_gpu ()
(Re-)initializes the fluid.
void reset_LB_forces_GPU (bool buffer=true)
Resets the forces on the fluid nodes.
void lb_realloc_particles_gpu ()
(Re-)initializes the particle array
void lb_realloc_particles_GPU_leftovers (LB_parameters_gpu *lbpar_gpu)
void lb_init_GPU (LB_parameters_gpu *lbpar_gpu)
initialization for the lb gpu fluid called from host
void lb_integrate_GPU ()
integration kernel for the lb gpu fluid update called from host
void lb_calc_shanchen_GPU ()
void lattice_boltzmann_calc_shanchen_gpu ()
main of lb_gpu_programm
void lb_free_GPU ()
void lb_get_values_GPU (LB_rho_v_pi_gpu *host_values)
setup and call kernel for getting macroscopic fluid values of all nodes
void lb_print_node_GPU (int single_nodeindex, LB_rho_v_pi_gpu *host_print_values)
setup and call kernel for getting macroscopic fluid values of a single node
void lb_init_boundaries_GPU (int n_lb_boundaries, int number_of_boundnodes, int *host_boundary_node_list, int *host_boundary_index_list, float *lb_bounday_velocity)
setup and call boundaries from the host
void lb_init_extern_nodeforces_GPU (int n_extern_nodeforces, LB_extern_nodeforce_gpu *host_extern_nodeforces, LB_parameters_gpu *lbpar_gpu)
setup and call extern single node force initialization from the host
void lb_calc_particle_lattice_ia_gpu ()
setup and call particle kernel from the host
void lb_calc_fluid_mass_GPU (double *mass)
setup and call kernel to calculate the total momentum of the hole fluid
void lb_calc_fluid_momentum_GPU (double *host_mom)
setup and call kernel to calculate the total momentum of the whole fluid
void lb_remove_fluid_momentum_GPU (void)
setup and call kernel to remove the net momentum of the whole fluid
void lb_calc_fluid_temperature_GPU (double *host_temp)
setup and call kernel to calculate the temperature of the hole fluid
void lb_get_boundary_flag_GPU (int single_nodeindex, unsigned int *host_flag)
setup and call kernel to get the boundary flag of a single node
void lb_get_boundary_flags_GPU (unsigned int *host_bound_array)
get all the boundary flags for all nodes
void lb_set_node_velocity_GPU (int single_nodeindex, float *host_velocity)
set the net velocity at a single node
void lb_set_node_rho_GPU (int single_nodeindex, float *host_rho)
set the density at a single node
void reinit_parameters_GPU (LB_parameters_gpu *lbpar_gpu)
reinit of params
void lb_reinit_extern_nodeforce_GPU (LB_parameters_gpu *lbpar_gpu)
setup and call extern single node force initialization from the host
void lb_reinit_GPU (LB_parameters_gpu *lbpar_gpu)
reinitialization for the lb gpu fluid called from host
int lb_lbnode_set_extforce_GPU (int ind[3], double f[3])
void lb_gpu_get_boundary_forces (double *forces)
void lb_save_checkpoint_GPU (float *host_checkpoint_vd, unsigned int *host_checkpoint_seed, unsigned int *host_checkpoint_boundary, lbForceFloat *host_checkpoint_force)
setup and call kernel for getting macroscopic fluid values of all nodes
void lb_load_checkpoint_GPU (float *host_checkpoint_vd, unsigned int *host_checkpoint_seed, unsigned int *host_checkpoint_boundary, lbForceFloat *host_checkpoint_force)
setup and call kernel for setting macroscopic fluid values of all nodes
int lb_lbfluid_save_checkpoint_wrapper (char *filename, int binary)
int lb_lbfluid_load_checkpoint_wrapper (char *filename, int binary)
int statistics_observable_lbgpu_radial_velocity_profile (radial_profile_data *pdata, double *A, unsigned int n_A)
Variables
Exported Variables
LB_parameters_gpu lbpar_gpu
Switch indicating momentum exchange between particles and fluid.
LB_rho_v_pi_gpu * host_values
this is the array that stores the hydrodynamic fields for the output
int transfer_momentum_gpu
Flag indicating momentum exchange between particles and fluid.
LB_extern_nodeforce_gpu * extern_nodeforces_gpu
int n_lb_boundaries
LB_node_force_gpu node_f
struct for node force
int ek_initialized
Detailed Description
Header file for lbgpu.cpp.
This is the header file for the Lattice Boltzmann implementation in lbgpu_cfile.cpp
Definition in file lbgpu.hpp.
Macro Definition Documentation
#define D3Q19
Definition at line 38 of file lbgpu.hpp.
#define LB_COUPLE_NULL 1
Note these are usef for binary logic so should be powers of 2.
Definition at line 42 of file lbgpu.hpp.
#define LB_COUPLE_THREE_POINT 4
Definition at line 44 of file lbgpu.hpp.
#define LB_COUPLE_TWO_POINT 2
Definition at line 43 of file lbgpu.hpp.
#define LBPAR_AGRID 2
grid constant for fluid lattice
Definition at line 53 of file lbgpu.hpp.
#define LBPAR_BOUNDARY 7
boundary parameters
Definition at line 59 of file lbgpu.hpp.
#define LBPAR_BULKVISC 6
fluid bulk viscosity
Definition at line 57 of file lbgpu.hpp.
#define LBPAR_COUPLING 8
Definition at line 62 of file lbgpu.hpp.
Referenced by lb_lbfluid_set_shanchen_coupling().
#define LBPAR_DENSITY 0
fluid density
Definition at line 51 of file lbgpu.hpp.
#define LBPAR_EXTFORCE 5
external force acting on the fluid
Definition at line 56 of file lbgpu.hpp.
#define LBPAR_FRICTION 4
friction coefficient for viscous coupling between particles and fluid
Definition at line 55 of file lbgpu.hpp.
#define LBPAR_MOBILITY 9
Definition at line 63 of file lbgpu.hpp.
Referenced by lb_lbfluid_set_mobility().
#define LBPAR_TAU 3
time step for fluid propagation
Definition at line 54 of file lbgpu.hpp.
#define LBPAR_VISCOSITY 1
fluid kinematic viscosity
Definition at line 52 of file lbgpu.hpp.
#define LBQ 19
Definition at line 39 of file lbgpu.hpp.
Referenced by apply_forces(), calc_m_from_n(), Calc_m_from_n_IBM(), calc_massmode(), calc_mode(), calc_n_from_modes_push(), calc_n_from_rho_j_pi(), calc_values_from_m_in_LB_units(), calc_values_in_MD_units(), lb_shanchen_set_boundaries(), normalize_modes(), relax_modes(), set_rho(), set_u_from_rho_v_pi(), thermalize_modes(), and update_rho_v().
Typedef Documentation
typedef double lbForceFloat
Definition at line 68 of file lbgpu.hpp.
Function Documentation
void lattice_boltzmann_calc_shanchen_gpu ()
main of lb_gpu_programm
Definition at line 177 of file lbgpu.cpp.
References fluidstep, lb_calc_shanchen_GPU(), LB_parameters_gpu::tau, and time_step.
Referenced by force_calc().
void lattice_boltzmann_update_gpu ()
lattice boltzmann update gpu called from integrate.cpp
Definition at line 189 of file lbgpu.cpp.
References fluidstep, lb_integrate_GPU(), lb_remove_fluid_momentum_GPU(), LB_TRACE, LB_parameters_gpu::remove_momentum, LB_parameters_gpu::tau, and time_step.
Referenced by integrate_sd(), and integrate_vv().
void lb_calc_fluid_mass_GPU (double * mass)
setup and call kernel to calculate the total momentum of the hole fluid
Parameters
*mass value of the mass calcutated on the GPU
values for the kernel call
Definition at line 3424 of file lbgpu_cuda.cu.
References calc_mass(), cuda_safe_mem, KERNELCALL, lbpar_gpu, and LB_parameters_gpu::number_of_nodes.
Referenced by tclcommand_analyze_fluid_mass_gpu().
void lb_calc_fluid_momentum_GPU (double * host_mom)
setup and call kernel to calculate the total momentum of the whole fluid
Parameters
host_mom value of the momentum calcutated on the GPU
values for the kernel call
Definition at line 3448 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, cuda_safe_mem, KERNELCALL, lbpar_gpu, momentum(), LB_parameters_gpu::number_of_nodes, and LB_parameters_gpu::tau.
Referenced by tclcommand_analyze_fluid_parse_momentum_gpu().
void lb_calc_fluid_temperature_GPU (double * host_temp)
setup and call kernel to calculate the temperature of the hole fluid
Parameters
host_temp value of the temperatur calcutated on the GPU
values for the kernel call
Definition at line 3498 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, cuda_safe_mem, KERNELCALL, LB_COMPONENTS, lbpar_gpu, LB_parameters_gpu::number_of_nodes, LB_parameters_gpu::rho, LB_parameters_gpu::tau, and temperature().
Referenced by tclcommand_analyze_fluid_parse_temperature_gpu().
void lb_calc_particle_lattice_ia_gpu ()
setup and call particle kernel from the host
call of the particle kernel
values for the particle kernel
only other option is the three point coupling scheme
Definition at line 3330 of file lbgpu_cuda.cu.
References calc_fluid_particle_ia(), calc_fluid_particle_ia_three_point_couple(), errexit(), gpu_get_fluid_composition_pointer(), gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), gpu_get_particle_seed_pointer(), KERNELCALL, LB_parameters_gpu::lb_couple_switch, LB_COUPLE_TWO_POINT, lbpar_gpu, and LB_parameters_gpu::number_of_particles.
Referenced by force_calc().
void lb_calc_shanchen_GPU ()
values for the kernel call
Definition at line 3533 of file lbgpu_cuda.cu.
References KERNELCALL, lb_shanchen_GPU(), lb_shanchen_set_boundaries(), lbpar_gpu, n_lb_boundaries, and LB_parameters_gpu::number_of_nodes.
Referenced by lattice_boltzmann_calc_shanchen_gpu().
void lb_free_GPU ()
void lb_get_boundary_flag_GPU (int single_nodeindex, unsigned int * host_flag)
setup and call kernel to get the boundary flag of a single node
Parameters
single_nodeindex number of the node to get the flag for
host_flag her goes the value of the boundary flag
Definition at line 3589 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, and lb_get_boundary_flag().
Referenced by lb_lbnode_get_boundary().
void lb_get_boundary_flags_GPU (unsigned int * host_bound_array)
get all the boundary flags for all nodes
Parameters
host_bound_array here go the values of the boundary flag
values for the kernel call
Definition at line 3386 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, lb_get_boundaries(), lbpar_gpu, and LB_parameters_gpu::number_of_nodes.
Referenced by lb_lbfluid_print_boundary(), and lb_lbfluid_print_vtk_boundary().
void lb_get_boundary_force_pointer (float ** pointeradress)
Definition at line 3113 of file lbgpu_cuda.cu.
References lb_boundary_force.
void lb_get_device_values_pointer (LB_rho_v_gpu ** pointeradress)
Definition at line 3119 of file lbgpu_cuda.cu.
References device_rho_v.
void lb_get_lbpar_pointer (LB_parameters_gpu ** pointeradress)
Definition at line 3108 of file lbgpu_cuda.cu.
References lbpar_gpu.
void lb_get_para_pointer (LB_parameters_gpu ** pointeradress)
Definition at line 3100 of file lbgpu_cuda.cu.
References errexit(), and para.
Referenced by InitCUDA_IBM().
void lb_get_values_GPU (LB_rho_v_pi_gpu * host_values)
setup and call kernel for getting macroscopic fluid values of all nodes
Parameters
*host_values struct to save the gpu values
values for the kernel call
Definition at line 3368 of file lbgpu_cuda.cu.
References cuda_safe_mem, get_mesoscopic_values_in_MD_units(), KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and size_of_rho_v_pi.
Referenced by lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_density(), and lb_lbfluid_print_vtk_velocity().
void lb_gpu_get_boundary_forces (double * forces)
Definition at line 3690 of file lbgpu_cuda.cu.
References cuda_safe_mem, free, i, lb_boundary_force, malloc, and n_lb_boundaries.
Referenced by lbboundary_get_force().
void lb_GPU_sanity_checks ()
Definition at line 384 of file lbgpu.cpp.
References LB_parameters_gpu::agrid, i, LB_COMPONENTS, LB_parameters_gpu::rho, runtimeError, LB_parameters_gpu::tau, this_node, and LB_parameters_gpu::viscosity.
Referenced by on_integration_start().
void lb_init_boundaries_GPU (int host_n_lb_boundaries, int number_of_boundnodes, int * host_boundary_node_list, int * host_boundary_index_list, float * host_lb_boundary_velocity)
setup and call boundaries from the host
Parameters
host_n_lb_boundaries number of LB boundaries
number_of_boundnodes number of boundnodes
host_boundary_node_list The indices of the boundary nodes
host_boundary_index_list The flag representing the corresponding boundary
host_lb_boundary_velocity The constant velocity at the boundary, set by the user (Input)
values for the kernel call
Definition at line 3244 of file lbgpu_cuda.cu.
References boundary_index_list, boundary_node_list, cuda_safe_mem, init_boundaries(), KERNELCALL, lb_boundary_force, lb_boundary_velocity, lbpar_gpu, n_lb_boundaries, n_lb_boundaries_gpu, LB_parameters_gpu::number_of_nodes, pdb_boundary_lattice, reset_boundaries(), and size_of_boundindex.
Referenced by lb_init_boundaries().
void lb_init_extern_nodeforces_GPU (int n_extern_nodeforces, LB_extern_nodeforce_gpu * host_extern_nodeforces, LB_parameters_gpu * lbpar_gpu)
setup and call extern single node force initialization from the host
Parameters
n_extern_nodeforces number of nodes on which the external force has to be applied
*host_extern_nodeforces Pointer to the host extern node forces
*lbpar_gpu Pointer to host parameter struct
Definition at line 3309 of file lbgpu_cuda.cu.
References cuda_safe_mem, LB_parameters_gpu::external_force, init_extern_nodeforces(), KERNELCALL, para, and size_of_extern_nodeforces.
Referenced by lb_lbnode_set_extforce_GPU().
void lb_init_gpu ()
Performs a full initialization of the Lattice Boltzmann system.
All derived parameters and the fluid are reset to their default values.
set parameters for transfer to gpu
Definition at line 339 of file lbgpu.cpp.
References gpu_init_particle_comm(), lb_init_GPU(), lb_realloc_particles_gpu(), lb_reinit_parameters_gpu(), and LB_TRACE.
Referenced by on_lb_params_change_gpu().
void lb_init_GPU (LB_parameters_gpu * lbpar_gpu)
initialization for the lb gpu fluid called from host
Parameters
*lbpar_gpu Pointer to parameters to setup the lb field
Allocate structs in device memory
write parameters in const memory
check flag if lb gpu init works
values for the kernel call
calc of velocitydensities from given parameters and initialize the Node_Force array with zero
Definition at line 3126 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, calc_n_from_rho_j_pi(), cuda_safe_mem, ek_initialized, ek_initialized_gpu, errexit(), extended_values_flag, LB_node_force_gpu::force, LB_node_force_gpu::force_buf, free, free_and_realloc, gpu_check, h_gpu_check, intflag, KERNELCALL, LB_COMPONENTS, malloc, nodes_a, LB_parameters_gpu::number_of_nodes, para, reinit_node_force(), reset_boundaries(), LB_node_force_gpu::scforce, LB_nodes_gpu::seed, size_of_rho_v, size_of_rho_v_pi, and LB_nodes_gpu::vd.
Referenced by lb_init_gpu().
void lb_integrate_GPU ()
integration kernel for the lb gpu fluid update called from host
values for the kernel call
call of fluid step
Definition at line 3650 of file lbgpu_cuda.cu.
References apply_boundaries(), cuda_safe_mem, integrate(), intflag, KERNELCALL, lb_boundary_force, lb_boundary_velocity, lb_ek_parameters_gpu, lbpar_gpu, n_lb_boundaries, nodes_a, nodes_b, and LB_parameters_gpu::number_of_nodes.
Referenced by lattice_boltzmann_update_gpu().
int lb_lbfluid_load_checkpoint_wrapper (char * filename, int binary)
Definition at line 417 of file lbgpu.cpp.
References lb_lbfluid_load_checkpoint().
int lb_lbfluid_save_checkpoint_wrapper (char * filename, int binary)
Definition at line 412 of file lbgpu.cpp.
References lb_lbfluid_save_checkpoint().
int lb_lbnode_set_extforce_GPU (int ind[3], double f[3])
Definition at line 357 of file lbgpu.cpp.
References LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, ES_ERROR, ES_OK, LB_parameters_gpu::external_force, LB_extern_nodeforce_gpu::force, LB_extern_nodeforce_gpu::index, lb_init_extern_nodeforces_GPU(), n_extern_nodeforces, and realloc.
Referenced by lbnode_parse_set().
void lb_load_checkpoint_GPU (float * host_checkpoint_vd, unsigned int * host_checkpoint_seed, unsigned int * host_checkpoint_boundary, lbForceFloat * host_checkpoint_force)
setup and call kernel for setting macroscopic fluid values of all nodes
Parameters
*host_checkpoint_vd struct to save the gpu populations
*host_checkpoint_seed struct to save the nodes' seeds for the lb on the gpu
*host_checkpoint_boundary struct to save the boundary nodes
*host_checkpoint_force struct to save the forces on the nodes
Definition at line 3573 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, cuda_safe_mem, LB_node_force_gpu::force, intflag, lbpar_gpu, nodes_a, LB_parameters_gpu::number_of_nodes, LB_nodes_gpu::seed, and LB_nodes_gpu::vd.
Referenced by lb_lbfluid_load_checkpoint().
void lb_pre_init_gpu ()
(Pre-)initializes data structures.
void lb_print_node_GPU (int single_nodeindex, LB_rho_v_pi_gpu * host_print_values)
setup and call kernel for getting macroscopic fluid values of a single node
Definition at line 3405 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, and lb_print_node().
Referenced by lb_lbnode_get_pi_neq(), lb_lbnode_get_rho(), and lb_lbnode_get_u().
void lb_realloc_particles_gpu ()
(Re-)initializes the particle array
(Re-)initializes the particle array
allocating of the needed memory for several structs
Definition at line 209 of file lbgpu.cpp.
References i_random(), lb_realloc_particles_GPU_leftovers(), LB_TRACE, max_ran, n_part, LB_parameters_gpu::number_of_particles, and LB_parameters_gpu::your_seed.
Referenced by lb_init_gpu(), and on_integration_start().
void lb_realloc_particles_GPU_leftovers (LB_parameters_gpu * lbpar_gpu)
Definition at line 3230 of file lbgpu_cuda.cu.
References cuda_safe_mem, and para.
Referenced by lb_realloc_particles_gpu().
void lb_reinit_extern_nodeforce_GPU (LB_parameters_gpu * lbpar_gpu)
setup and call extern single node force initialization from the host
Parameters
*lbpar_gpu Pointer to host parameter struct
values for the kernel call
Definition at line 3291 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, LB_parameters_gpu::number_of_nodes, para, and reinit_node_force().
Referenced by lb_lbfluid_set_ext_force().
void lb_reinit_fluid_gpu ()
(Re-)initializes the fluid.
(Re-)initializes the fluid.
Definition at line 225 of file lbgpu.cpp.
References lb_reinit_GPU(), lb_reinit_parameters_gpu(), LB_TRACE, LB_parameters_gpu::number_of_nodes, and LB_parameters_gpu::reinit.
Referenced by on_lb_params_change_gpu().
void lb_reinit_GPU (LB_parameters_gpu * lbpar_gpu)
reinitialization for the lb gpu fluid called from host
Parameters
*lbpar_gpu Pointer to parameters to setup the lb field
write parameters in const memory
values for the kernel call
calc of velocity densities from given parameters and initialize the Node_Force array with zero
Definition at line 3215 of file lbgpu_cuda.cu.
References calc_n_from_rho_j_pi(), cuda_safe_mem, gpu_check, KERNELCALL, LB_parameters_gpu::number_of_nodes, and para.
Referenced by lb_reinit_fluid_gpu().
void lb_reinit_parameters_gpu ()
(Re-)initializes the derived parameters for the Lattice Boltzmann system.
The current state of the fluid is unchanged.
(Re-)initializes the derived parameters for the Lattice Boltzmann system.
Definition at line 253 of file lbgpu.cpp.
References LB_parameters_gpu::agrid, box_l, LB_parameters_gpu::bulk_viscosity, c_sound_sq, LB_parameters_gpu::dim_x, LB_parameters_gpu::dim_y, LB_parameters_gpu::dim_z, ek_initialized, LB_parameters_gpu::fluct, LB_parameters_gpu::friction, LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_mobility, LB_parameters_gpu::gamma_shear, LB_COMPONENTS, LB_parameters_gpu::lb_coupl_pref, LB_parameters_gpu::lb_coupl_pref2, LB_TRACE, LB_parameters_gpu::mobility, LB_parameters_gpu::mu, LB_parameters_gpu::number_of_nodes, reinit_parameters_GPU(), runtimeError, LB_parameters_gpu::tau, temperature, time_step, LB_parameters_gpu::time_step, and LB_parameters_gpu::viscosity.
Referenced by lb_init_gpu(), lb_reinit_fluid_gpu(), on_lb_params_change_gpu(), on_parameter_change(), and on_temperature_change().
void lb_remove_fluid_momentum_GPU (void)
setup and call kernel to remove the net momentum of the whole fluid
values for the kernel call
Definition at line 3473 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, lbpar_gpu, momentum(), LB_parameters_gpu::number_of_nodes, and remove_momentum().
Referenced by lattice_boltzmann_update_gpu().
void lb_save_checkpoint_GPU (float * host_checkpoint_vd, unsigned int * host_checkpoint_seed, unsigned int * host_checkpoint_boundary, lbForceFloat * host_checkpoint_force)
setup and call kernel for getting macroscopic fluid values of all nodes
Parameters
*host_checkpoint_vd struct to save the gpu populations
*host_checkpoint_seed struct to save the nodes' seeds for the lb on the gpu
*host_checkpoint_boundary struct to save the boundary nodes
*host_checkpoint_force struct to save the forces on the nodes
Definition at line 3558 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, cuda_safe_mem, LB_node_force_gpu::force, lbpar_gpu, LB_parameters_gpu::number_of_nodes, LB_nodes_gpu::seed, and LB_nodes_gpu::vd.
Referenced by lb_lbfluid_save_checkpoint().
void lb_set_node_rho_GPU (int single_nodeindex, float * host_rho)
set the density at a single node
Parameters
single_nodeindex the node to set the velocity for
*host_rho the density to set
Definition at line 3609 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, LB_COMPONENTS, and set_rho().
Referenced by lb_lbnode_set_rho().
void lb_set_node_velocity_GPU (int single_nodeindex, float * host_velocity)
set the net velocity at a single node
Parameters
single_nodeindex the node to set the velocity for
host_velocity the velocity to set
Definition at line 3626 of file lbgpu_cuda.cu.
References cuda_safe_mem, KERNELCALL, and set_u_from_rho_v_pi().
Referenced by lb_lbnode_set_u().
void on_lb_params_change_gpu (int field)
Definition at line 655 of file initialize.cpp.
References EVENT_TRACE, lb_init_boundaries(), lb_init_gpu(), lb_reinit_fluid_gpu(), lb_reinit_parameters_gpu(), LBPAR_AGRID, LBPAR_DENSITY, and this_node.
Referenced by lb_lbfluid_set_agrid(), lb_lbfluid_set_bulk_visc(), lb_lbfluid_set_density(), lb_lbfluid_set_friction(), lb_lbfluid_set_gamma_even(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_mobility(), lb_lbfluid_set_remove_momentum(), lb_lbfluid_set_shanchen_coupling(), lb_lbfluid_set_tau(), and lb_lbfluid_set_visc().
void reinit_parameters_GPU (LB_parameters_gpu * lbpar_gpu)
reinit of params
Parameters
*lbpar_gpu struct containing the paramters of the fluid
write parameters in const memory
Definition at line 3644 of file lbgpu_cuda.cu.
References cuda_safe_mem, and para.
Referenced by lb_reinit_parameters_gpu().
void reset_LB_forces_GPU (bool buffer = true)
Resets the forces on the fluid nodes.
Definition at line 547 of file lbgpu_cuda.cu.
References KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and reset_LB_forces_kernel().
int statistics_observable_lbgpu_radial_velocity_profile (radial_profile_data * pdata, double * A, unsigned int n_A)
Definition at line 3847 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, cuda_safe_mem, LB_parameters_gpu::dim_z, fill_lb_radial_velocity_profile(), free, i, KERNELCALL, lbpar_gpu, malloc, radial_profile_data::maxr, radial_profile_data::phibins, radial_profile_data::rbins, and radial_profile_data::zbins.
Referenced by observable_calc_lb_radial_velocity_profile().
Variable Documentation
int ek_initialized
Definition at line 166 of file lbgpu.cpp.
LB_extern_nodeforce_gpu* extern_nodeforces_gpu
LB_rho_v_pi_gpu* host_values
this is the array that stores the hydrodynamic fields for the output
Definition at line 141 of file lbgpu.cpp.
Referenced by lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_density(), and lb_lbfluid_print_vtk_velocity().
LB_parameters_gpu lbpar_gpu
Switch indicating momentum exchange between particles and fluid.
Switch indicating momentum exchange between particles and fluid.
Definition at line 74 of file lbgpu.cpp.
Referenced by IBM_ForcesIntoFluid_GPU(), IBM_ResetLBForces_GPU(), lb_calc_fluid_mass_GPU(), lb_calc_fluid_momentum_GPU(), lb_calc_fluid_temperature_GPU(), lb_calc_particle_lattice_ia_gpu(), lb_calc_shanchen_GPU(), lb_get_boundary_flags_GPU(), lb_get_lbpar_pointer(), lb_get_values_GPU(), lb_init_boundaries(), lb_init_boundaries_GPU(), lb_integrate_GPU(), lb_lbfluid_get_agrid(), lb_lbfluid_get_bulk_visc(), lb_lbfluid_get_density(), lb_lbfluid_get_ext_force(), lb_lbfluid_get_gamma_even(), lb_lbfluid_get_gamma_odd(), lb_lbfluid_get_interpolated_velocity_global(), lb_lbfluid_get_visc(), lb_lbfluid_load_checkpoint(), lb_lbfluid_print_boundary(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_boundary(), lb_lbfluid_print_vtk_density(), lb_lbfluid_print_vtk_velocity(), lb_lbfluid_save_checkpoint(), lb_lbfluid_set_agrid(), lb_lbfluid_set_bulk_visc(), lb_lbfluid_set_couple_flag(), lb_lbfluid_set_density(), lb_lbfluid_set_ext_force(), lb_lbfluid_set_friction(), lb_lbfluid_set_gamma_even(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_mobility(), lb_lbfluid_set_remove_momentum(), lb_lbfluid_set_shanchen_coupling(), lb_lbfluid_set_tau(), lb_lbfluid_set_visc(), lb_lbnode_get_boundary(), lb_lbnode_get_pi(), lb_lbnode_get_pi_neq(), lb_lbnode_get_rho(), lb_lbnode_get_u(), lb_lbnode_set_rho(), lb_lbnode_set_u(), lb_load_checkpoint_GPU(), lb_remove_fluid_momentum_GPU(), lb_save_checkpoint_GPU(), ParticleVelocitiesFromLB_GPU(), reset_LB_forces_GPU(), statistics_observable_lbgpu_radial_velocity_profile(), tclcallback_time_step(), and tclcommand_lbnode().
int n_lb_boundaries
Definition at line 40 of file lb-boundaries.cpp.
Referenced by generate_lbboundary(), InitCUDA_IBM(), lb_calc_shanchen_GPU(), lb_collect_boundary_forces(), lb_collide_stream(), lb_gpu_get_boundary_forces(), lb_init_boundaries(), lb_init_boundaries_GPU(), lb_integrate_GPU(), lb_reinit_forces(), lbboundary_get_force(), lbboundary_mindist_position(), mpi_bcast_lbboundary(), mpi_bcast_lbboundary_slave(), tclcommand_electrokinetics(), tclcommand_lbboundary(), and tclcommand_lbboundary_print_all().
LB_node_force_gpu node_f
struct for node force
Definition at line 75 of file lbgpu_cuda.cu.
int transfer_momentum_gpu
Flag indicating momentum exchange between particles and fluid.
Definition at line 148 of file lbgpu.cpp.
Referenced by force_calc(), integrate_sd(), and integrate_vv().