ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lees_edwards_domain_decomposition.hpp File Reference
lees_edwards_domain_decomposition.hpp File Reference
Data and methods for Lees-Edwards periodic boundary conditions.
#include "utils.hpp"
#include "cells.hpp"
#include "integrate.hpp"
#include "verlet.hpp"
#include "thermostat.hpp"
#include "lees_edwards_comms_manager.hpp"
Functions
Exported Functions
void le_dd_prepare_comm (le_dd_comms_manager *mgr, GhostCommunicator *comm, int data_parts)
Create communicators for cell structure domain decomposition.
void le_dd_dynamic_update_comm (le_dd_comms_manager *mgr, GhostCommunicator *comm, int data_parts, int backwards)
Update communicators based on a new LE offset.
void le_dd_update_communicators_w_boxl (le_dd_comms_manager *mgr)
update the 'shift' member of those GhostCommunicators, which use that value to speed up the folding process of its ghost members (see dd_prepare_comm for the original), i.e.
void le_dd_init_cell_interactions ()
Init cell interactions for the Lees-Edwards cell system.
Detailed Description
Data and methods for Lees-Edwards periodic boundary conditions.
Most of the domain decomposition is handled as normal, (see domain_decomposition.hpp) however imaging over the Y-axis is neccessarily a little different.
Definition in file lees_edwards_domain_decomposition.hpp.
Function Documentation
void le_dd_dynamic_update_comm (le_dd_comms_manager * mgr, GhostCommunicator * comm, int data_parts, int backwards)
Update communicators based on a new LE offset.
(see GhostCommunicator and also le_dd_prepare_comm)
Update communicators based on a new LE offset.
(see GhostCommunicator)
Definition at line 681 of file lees_edwards_domain_decomposition.cpp.
References box_l, DomainDecomposition::cell_grid, GhostCommunicator::comm, comms_count, comms_log, le_dd_comms_manager::comms_order, dd, GHOSTTRANS_POSSHFTD, i, LE_COMM_BACKWARDS, LE_TRACE, lees_edwards_offset, map_node_array(), my_neighbor_count, GhostCommunication::n_part_lists, GhostCommunication::node, node_neighbor_lr, node_neighbor_wrap, node_neighbors, node_pos, GhostCommunication::part_lists, printAllComms(), GhostCommunication::shift, this_node, and le_dd_comms_manager::wrap_fill_comm_cell_lists().
Referenced by dd_on_geometry_change().
void le_dd_init_cell_interactions ()
Init cell interactions for the Lees-Edwards cell system.
initializes the interacting neighbor cell list of a cell. The created list of interacting neighbor cells is used by the verlet algorithm (see verlet.c) to build the verlet lists.
initializes the interacting neighbor cell list of a cell. The created list of interacting neighbor cells is used by the verlet algorithm (see verlet.cpp) to build the verlet lists.
Definition at line 53 of file lees_edwards_domain_decomposition.cpp.
References DomainDecomposition::cell_grid, IA_Neighbor::cell_ind, DomainDecomposition::cell_inter, DomainDecomposition::cell_size, cells, dd, get_linear_index(), DomainDecomposition::ghost_cell_grid, init_pairList(), local_cells, my_left, IA_Neighbor::my_pos, CellPList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, node_grid, node_pos, IA_Neighbor::pList, realloc, this_node, and IA_Neighbor::vList.
Referenced by dd_topology_init().
void le_dd_prepare_comm (le_dd_comms_manager * mgr, GhostCommunicator * comm, int data_parts)
Create communicators for cell structure domain decomposition.
(see GhostCommunicator and also dd_prepare_comm)
(see GhostCommunicator)
Definition at line 340 of file lees_edwards_domain_decomposition.cpp.
References box_l, DomainDecomposition::cell_grid, CELL_TRACE, GhostCommunicator::comm, comms_count, comms_log, le_dd_comms_manager::comms_order, dd, dd_fill_comm_cell_lists(), GHOST_LOCL, GHOST_RECV, GHOST_SEND, GHOSTTRANS_POSSHFTD, i, LE_TRACE, lees_edwards_offset, malloc, map_node_array(), my_neighbor_count, GhostCommunication::n_part_lists, GhostCommunication::node, node_neighbor_lr, node_neighbor_wrap, node_neighbors, node_pos, GhostCommunication::part_lists, prepare_comm(), printAllComms(), GhostCommunication::shift, this_node, GhostCommunication::type, and le_dd_comms_manager::wrap_fill_comm_cell_lists().
Referenced by dd_topology_init().
void le_dd_update_communicators_w_boxl (le_dd_comms_manager * mgr)
update the 'shift' member of those GhostCommunicators, which use that value to speed up the folding process of its ghost members (see dd_prepare_comm for the original), i.e.
all which have GHOSTTRANS_POSSHFTD or'd into 'data_parts' upon execution of dd_prepare_comm.
Definition at line 148 of file lees_edwards_domain_decomposition.cpp.
References box_l, cell_structure, GhostCommunicator::comm, le_dd_comms_manager::comms_order, CellStructure::exchange_ghosts_comm, i, lees_edwards_offset, my_neighbor_count, node_neighbor_wrap, node_neighbors, GhostCommunication::shift, this_node, and CellStructure::update_ghost_pos_comm.
Referenced by dd_on_geometry_change().