ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lj.hpp File Reference
lj.hpp File Reference
Routines to calculate the lennard jones energy and/or force for a particle pair.
#include "utils.hpp"
#include "particle_data.hpp"
#include "interaction_data.hpp"
#include "mol_cut.hpp"
#include "forcecap.hpp"
Functions
int ljforcecap_set_params (double ljforcecap)
set the force cap for the LJ interaction.
int lennard_jones_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double shift, double offset, double cap_radius, double min)
void add_lj_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double force[3])
Calculate lennard Jones force between particle p1 and p2.
double lj_pair_energy (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist)
calculate Lennard jones energy between particle p1 and p2.
void calc_lj_cap_radii ()
calculate lj_capradius from force_cap
Detailed Description
Routines to calculate the lennard jones energy and/or force for a particle pair.
forces.cpp
Definition in file lj.hpp.
Function Documentation
void add_lj_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double force[3]) inline
Calculate lennard Jones force between particle p1 and p2.
Definition at line 45 of file lj.hpp.
References IA_parameters::affinity, IA_parameters::affinity_on, check_id, ParticlePosition::composition, configtemp, CUTOFF_CHECK, ParticleForce::f, Particle::f, ParticleProperties::identity, LB_COMPONENTS, IA_parameters::LJ_capradius, IA_parameters::LJ_eps, IA_parameters::LJ_min, IA_parameters::LJ_offset, IA_parameters::LJ_sig, LJ_TRACE, ONEPART_TRACE, Particle::p, Particle::r, SQR(), and this_node.
Referenced by calc_non_bonded_pair_force_parts().
void calc_lj_cap_radii ()
calculate lj_capradius from force_cap
Definition at line 68 of file lj.cpp.
References force_cap, FORCE_TRACE, get_ia_param(), i, IA_parameters::LJ_capradius, IA_parameters::LJ_eps, IA_parameters::LJ_sig, n_particle_types, params, SQR(), and this_node.
Referenced by mpi_cap_forces_slave().
int lennard_jones_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double shift, double offset, double cap_radius, double min)
Definition at line 39 of file lj.cpp.
References ES_ERROR, ES_OK, force_cap, get_ia_param_safe(), IA_parameters::LJ_capradius, IA_parameters::LJ_cut, IA_parameters::LJ_eps, IA_parameters::LJ_min, IA_parameters::LJ_offset, IA_parameters::LJ_shift, IA_parameters::LJ_sig, mpi_bcast_ia_params(), and mpi_cap_forces().
Referenced by add_lj_interaction(), add_lj_internal(), and tclcommand_inter_parse_lj().
double lj_pair_energy (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist) inline
calculate Lennard jones energy between particle p1 and p2.
Definition at line 123 of file lj.hpp.
References CUTOFF_CHECK, IA_parameters::LJ_capradius, IA_parameters::LJ_eps, IA_parameters::LJ_min, IA_parameters::LJ_offset, IA_parameters::LJ_shift, IA_parameters::LJ_sig, and SQR().
Referenced by calc_non_bonded_pair_energy().
int ljforcecap_set_params (double ljforcecap)
set the force cap for the LJ interaction.
Parameters
ljforcecap the maximal force, 0 to disable, -1 for individual cutoff for each of the interactions.
Definition at line 32 of file lj.cpp.
References ES_OK, and mpi_cap_forces().