ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: lj_tcl.cpp File Reference
lj_tcl.cpp File Reference
#include "utils.hpp"
#include "lj.hpp"
#include "lj_tcl.hpp"
#include "parser.hpp"
#include "mol_cut.hpp"
#include "communication.hpp"
#include "forcecap_tcl.hpp"
Functions
int tclprint_to_result_ljIA (Tcl_Interp *interp, int i, int j)
int tclcommand_inter_parse_ljforcecap (Tcl_Interp *interp, int argc, char **argv)
set the force cap for the LJ interaction.
int tclcommand_inter_parse_lj (Tcl_Interp *interp, int part_type_a, int part_type_b, int argc, char **argv)
Function Documentation
int tclcommand_inter_parse_lj (Tcl_Interp * interp, int part_type_a, int part_type_b, int argc, char ** argv)
Definition at line 73 of file lj_tcl.cpp.
References ARG_IS_D, ARG_IS_S, ES_ERROR, and lennard_jones_set_params().
Referenced by tclcommand_inter_parse_non_bonded().
int tclcommand_inter_parse_ljforcecap (Tcl_Interp * interp, int argc, char ** argv)
set the force cap for the LJ interaction.
parser for the forcecap
Parameters
interp tcl interpreter handle
argc number of arguments
argv arguments
Definition at line 61 of file lj_tcl.cpp.
References tclcommand_inter_parse_forcecap().
Referenced by tclcommand_inter_parse_rest().
int tclprint_to_result_ljIA (Tcl_Interp * interp, int i, int j)
Definition at line 31 of file lj_tcl.cpp.
References get_ia_param(), IA_parameters::LJ_capradius, IA_parameters::LJ_cut, IA_parameters::LJ_eps, IA_parameters::LJ_min, IA_parameters::LJ_offset, IA_parameters::LJ_shift, and IA_parameters::LJ_sig.
Referenced by tclprint_to_result_NonbondedIA().