ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ljangle.cpp File Reference
ljangle.cpp File Reference
#include "utils.hpp"
#include "ljangle.hpp"
#include <cmath>
#include "interaction_data.hpp"
#include "communication.hpp"
Functions
int ljangle_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, int b1p, int b1n, int b2p, int b2n, double cap_radius, double z0, double dz, double kappa, double epsprime)
For the warmup you can cap the singularity of the directionnal LJ potential at r=0.
void calc_ljangle_cap_radii ()
calculate ljangle_capradius from force_cap
Function Documentation
void calc_ljangle_cap_radii ()
calculate ljangle_capradius from force_cap
Definition at line 89 of file ljangle.cpp.
References force_cap, FORCE_TRACE, get_ia_param(), i, IA_parameters::LJANGLE_capradius, IA_parameters::LJANGLE_eps, IA_parameters::LJANGLE_sig, n_particle_types, params, SQR(), and this_node.
Referenced by mpi_cap_forces_slave().
int ljangle_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, int b1p, int b1n, int b2p, int b2n, double cap_radius, double z0, double dz, double kappa, double epsprime)
For the warmup you can cap the singularity of the directionnal LJ potential at r=0.
look into the warmup documentation for more details (who wants to write that?).
Definition at line 48 of file ljangle.cpp.
References ES_ERROR, ES_OK, force_cap, get_ia_param_safe(), IA_parameters::LJANGLE_bonded1neg, IA_parameters::LJANGLE_bonded1pos, IA_parameters::LJANGLE_bonded1type, IA_parameters::LJANGLE_bonded2neg, IA_parameters::LJANGLE_bonded2pos, IA_parameters::LJANGLE_capradius, IA_parameters::LJANGLE_cut, IA_parameters::LJANGLE_dz, IA_parameters::LJANGLE_eps, IA_parameters::LJANGLE_epsprime, IA_parameters::LJANGLE_kappa, IA_parameters::LJANGLE_sig, IA_parameters::LJANGLE_z0, mpi_bcast_ia_params(), and mpi_cap_forces().
Referenced by tclcommand_inter_parse_ljangle().