ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ljangle.hpp File Reference
ljangle.hpp File Reference
Routines to calculate the lennard-jones 12-10 with angular dependance.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "mol_cut.hpp"
#include "grid.hpp"
#include "forcecap.hpp"
#include <cmath>
Functions
int ljangle_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, int b1p, int b1n, int b2p, int b2n, double cap_radius, double z0, double dz, double kappa, double epsprime)
For the warmup you can cap the singularity of the directionnal LJ potential at r=0.
void add_ljangle_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist)
Calculate lj-angle force between particle p1 and p2 Involves 6 particles total.
double ljangle_pair_energy (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist)
calculate Lennard jones energy between particle p1 and p2.
void calc_ljangle_cap_radii ()
calculate ljangle_capradius from force_cap
Detailed Description
Routines to calculate the lennard-jones 12-10 with angular dependance.
The potential is a product of a 12-10 LJ potential with two cos^2. The potential actually relies on 6 particles: the 2 primary beads and each bead needs two other particles to define an orientation. We calculate the interaction explicitly without the use of the ROTATION feature.
Optional: simulate two different environments in which the interaction strengths differ. For example: simulate hydrogen-bonds both in water and inside a bilayer. The two environments are distinguished by their z-position. Input: the midplane of the 2nd environment, its total thickness, the thickness of the interface, and the value of the interaction strength in this medium. The interaction strengh of the second environment must be stronger than of the first one.
forces.cpp
Definition in file ljangle.hpp.
Function Documentation
void add_ljangle_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist) inline
Calculate lj-angle force between particle p1 and p2 Involves 6 particles total.
Definition at line 67 of file ljangle.hpp.
References box_l, box_l_i, check_id, CUTOFF_CHECK, dround(), ParticleForce::f, Particle::f, get_mi_vector(), ParticleProperties::identity, LJ_TRACE, IA_parameters::LJANGLE_bonded1neg, IA_parameters::LJANGLE_bonded1pos, IA_parameters::LJANGLE_bonded1type, IA_parameters::LJANGLE_bonded2neg, IA_parameters::LJANGLE_bonded2pos, IA_parameters::LJANGLE_capradius, IA_parameters::LJANGLE_dz, IA_parameters::LJANGLE_eps, IA_parameters::LJANGLE_epsprime, IA_parameters::LJANGLE_kappa, IA_parameters::LJANGLE_sig, IA_parameters::LJANGLE_z0, local_particles, n_part, ONEPART_TRACE, ParticlePosition::p, Particle::p, PERIODIC, Particle::r, scalar(), SQR(), sqrlen(), this_node, and ParticleProperties::type.
Referenced by calc_non_bonded_pair_force_parts().
void calc_ljangle_cap_radii ()
calculate ljangle_capradius from force_cap
Definition at line 89 of file ljangle.cpp.
References force_cap, FORCE_TRACE, get_ia_param(), i, IA_parameters::LJANGLE_capradius, IA_parameters::LJANGLE_eps, IA_parameters::LJANGLE_sig, n_particle_types, params, SQR(), and this_node.
Referenced by mpi_cap_forces_slave().
double ljangle_pair_energy (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist) inline
calculate Lennard jones energy between particle p1 and p2.
Definition at line 262 of file ljangle.hpp.
References box_l, box_l_i, CUTOFF_CHECK, dround(), get_mi_vector(), ParticleProperties::identity, IA_parameters::LJANGLE_bonded1neg, IA_parameters::LJANGLE_bonded1pos, IA_parameters::LJANGLE_bonded1type, IA_parameters::LJANGLE_bonded2neg, IA_parameters::LJANGLE_bonded2pos, IA_parameters::LJANGLE_capradius, IA_parameters::LJANGLE_dz, IA_parameters::LJANGLE_eps, IA_parameters::LJANGLE_epsprime, IA_parameters::LJANGLE_kappa, IA_parameters::LJANGLE_sig, IA_parameters::LJANGLE_z0, local_particles, n_part, ParticlePosition::p, Particle::p, PERIODIC, Particle::r, scalar(), SQR(), sqrlen(), and ParticleProperties::type.
Referenced by calc_non_bonded_pair_energy().
int ljangle_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, int b1p, int b1n, int b2p, int b2n, double cap_radius, double z0, double dz, double kappa, double epsprime)
For the warmup you can cap the singularity of the directionnal LJ potential at r=0.
look into the warmup documentation for more details (who wants to write that?).
Definition at line 48 of file ljangle.cpp.
References ES_ERROR, ES_OK, force_cap, get_ia_param_safe(), IA_parameters::LJANGLE_bonded1neg, IA_parameters::LJANGLE_bonded1pos, IA_parameters::LJANGLE_bonded1type, IA_parameters::LJANGLE_bonded2neg, IA_parameters::LJANGLE_bonded2pos, IA_parameters::LJANGLE_capradius, IA_parameters::LJANGLE_cut, IA_parameters::LJANGLE_dz, IA_parameters::LJANGLE_eps, IA_parameters::LJANGLE_epsprime, IA_parameters::LJANGLE_kappa, IA_parameters::LJANGLE_sig, IA_parameters::LJANGLE_z0, mpi_bcast_ia_params(), and mpi_cap_forces().
Referenced by tclcommand_inter_parse_ljangle().