ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ljangle_tcl.cpp File Reference
ljangle_tcl.cpp File Reference
#include "utils.hpp"
#include "ljangle.hpp"
#include "ljangle_tcl.hpp"
#include <cmath>
#include "interaction_data.hpp"
#include "parser.hpp"
#include "communication.hpp"
#include "forcecap_tcl.hpp"
Functions
int tclprint_to_result_ljangleIA (Tcl_Interp *interp, int i, int j)
int tclcommand_inter_parse_ljangleforcecap (Tcl_Interp *interp, int argc, char **argv)
set the force cap for the directional LJ interaction.
int tclcommand_inter_parse_ljangle (Tcl_Interp *interp, int part_type_a, int part_type_b, int argc, char **argv)
Function Documentation
int tclcommand_inter_parse_ljangle (Tcl_Interp * interp, int part_type_a, int part_type_b, int argc, char ** argv)
Definition at line 109 of file ljangle_tcl.cpp.
References ARG_IS_D, ARG_IS_I, box_l, and ljangle_set_params().
Referenced by tclcommand_inter_parse_non_bonded().
int tclcommand_inter_parse_ljangleforcecap (Tcl_Interp * interp, int argc, char ** argv)
set the force cap for the directional LJ interaction.
Parameters
interp tcl interpreter handle
argc number of arguments.
argv arguments.
Definition at line 97 of file ljangle_tcl.cpp.
References tclcommand_inter_parse_forcecap().
Referenced by tclcommand_inter_parse_rest().
int tclprint_to_result_ljangleIA (Tcl_Interp * interp, int i, int j)
Definition at line 51 of file ljangle_tcl.cpp.
References get_ia_param(), IA_parameters::LJANGLE_bonded1neg, IA_parameters::LJANGLE_bonded1pos, IA_parameters::LJANGLE_bonded2neg, IA_parameters::LJANGLE_bonded2pos, IA_parameters::LJANGLE_capradius, IA_parameters::LJANGLE_cut, IA_parameters::LJANGLE_dz, IA_parameters::LJANGLE_eps, IA_parameters::LJANGLE_epsprime, IA_parameters::LJANGLE_kappa, IA_parameters::LJANGLE_sig, and IA_parameters::LJANGLE_z0.
Referenced by tclprint_to_result_NonbondedIA().