ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ljcos.hpp File Reference
ljcos.hpp File Reference
Routines to calculate the lennard jones+cosine energy and/or force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "mol_cut.hpp"
Functions
int lj_cos_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double offset)
void add_ljcos_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double force[3])
double ljcos_pair_energy (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist)
Detailed Description
Routines to calculate the lennard jones+cosine energy and/or force for a particle pair.
forces.cpp
Definition in file ljcos.hpp.
Function Documentation
void add_ljcos_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double force[3]) inline
Definition at line 40 of file ljcos.hpp.
References check_id, CUTOFF_CHECK, ParticleForce::f, Particle::f, ParticleProperties::identity, IA_parameters::LJ_capradius, IA_parameters::LJ_eps, IA_parameters::LJ_sig, LJ_TRACE, IA_parameters::LJCOS_alfa, IA_parameters::LJCOS_beta, IA_parameters::LJCOS_eps, IA_parameters::LJCOS_offset, IA_parameters::LJCOS_rmin, IA_parameters::LJCOS_sig, ONEPART_TRACE, Particle::p, SQR(), and this_node.
Referenced by calc_non_bonded_pair_force_parts().
int lj_cos_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double offset)
Definition at line 28 of file ljcos.cpp.
References driwu2, ES_ERROR, ES_OK, get_ia_param_safe(), IA_parameters::LJCOS_alfa, IA_parameters::LJCOS_beta, IA_parameters::LJCOS_cut, IA_parameters::LJCOS_eps, IA_parameters::LJCOS_offset, IA_parameters::LJCOS_rmin, IA_parameters::LJCOS_sig, mpi_bcast_ia_params(), PI, and SQR().
Referenced by tclcommand_inter_parse_ljcos().
double ljcos_pair_energy (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist) inline
Definition at line 88 of file ljcos.hpp.
References CUTOFF_CHECK, IA_parameters::LJCOS_alfa, IA_parameters::LJCOS_beta, IA_parameters::LJCOS_cut, IA_parameters::LJCOS_eps, IA_parameters::LJCOS_offset, IA_parameters::LJCOS_rmin, IA_parameters::LJCOS_sig, and SQR().
Referenced by calc_non_bonded_pair_energy().