ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ljcos_tcl.hpp File Reference
ljcos_tcl.hpp File Reference
#include "parser.hpp"
Functions
int tclprint_to_result_ljcosIA (Tcl_Interp *interp, int i, int j)
int tclcommand_inter_parse_ljcos (Tcl_Interp *interp, int part_type_a, int part_type_b, int argc, char **argv)
Function Documentation
int tclcommand_inter_parse_ljcos (Tcl_Interp * interp, int part_type_a, int part_type_b, int argc, char ** argv)
Definition at line 53 of file ljcos_tcl.cpp.
References ARG_IS_D, ES_ERROR, and lj_cos_set_params().
Referenced by tclcommand_inter_parse_non_bonded().
int tclprint_to_result_ljcosIA (Tcl_Interp * interp, int i, int j)
Definition at line 30 of file ljcos_tcl.cpp.
References get_ia_param(), IA_parameters::LJCOS_alfa, IA_parameters::LJCOS_beta, IA_parameters::LJCOS_cut, IA_parameters::LJCOS_eps, IA_parameters::LJCOS_offset, IA_parameters::LJCOS_rmin, and IA_parameters::LJCOS_sig.
Referenced by tclprint_to_result_NonbondedIA().