ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ljcos2.cpp File Reference
ljcos2.cpp File Reference
#include "ljcos2.hpp"
#include <cmath>
#include "lj.hpp"
#include "communication.hpp"
Functions
int ljcos2_set_params (int part_type_a, int part_type_b, double eps, double sig, double offset, double w)
void calc_ljcos2_cap_radii ()
calculate ljcos2_capradius from force_cap
Function Documentation
void calc_ljcos2_cap_radii ()
calculate ljcos2_capradius from force_cap
Definition at line 64 of file ljcos2.cpp.
References force_cap, FORCE_TRACE, get_ia_param(), i, IA_parameters::LJCOS2_capradius, IA_parameters::LJCOS2_eps, IA_parameters::LJCOS2_sig, n_particle_types, params, SQR(), and this_node.
Referenced by mpi_cap_forces_slave().
int ljcos2_set_params (int part_type_a, int part_type_b, double eps, double sig, double offset, double w)
Definition at line 38 of file ljcos2.cpp.
References ES_ERROR, ES_OK, force_cap, get_ia_param_safe(), IA_parameters::LJCOS2_cut, IA_parameters::LJCOS2_eps, IA_parameters::LJCOS2_offset, IA_parameters::LJCOS2_rchange, IA_parameters::LJCOS2_sig, IA_parameters::LJCOS2_w, mpi_bcast_ia_params(), and mpi_cap_forces().
Referenced by tclcommand_inter_parse_ljcos2().