ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: ljgen.cpp File Reference
ljgen.cpp File Reference
Routines to calculate the generalized lennard jones energy and/or force for a particle pair.
#include "config.hpp"
#include "lj.hpp"
#include "ljgen.hpp"
#include "communication.hpp"
Functions
int ljgen_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double shift, double offset, int a1, int a2, double b1, double b2, double cap_radius, double lambda, double softrad)
void calc_ljgen_cap_radii ()
calculate lj_capradius from force_cap
Detailed Description
Routines to calculate the generalized lennard jones energy and/or force for a particle pair.
"Generalized" here means that the LJ energy is of the form
eps * [ b1 * (sigma/(r-r_offset))^a1 - b2 * (sigma/(r-r_offset))^a2 + shift]
forces.cpp
Definition in file ljgen.cpp.
Function Documentation
void calc_ljgen_cap_radii ()
calculate lj_capradius from force_cap
Definition at line 81 of file ljgen.cpp.
References force_cap, FORCE_TRACE, get_ia_param(), i, IA_parameters::LJGEN_a1, IA_parameters::LJGEN_a2, IA_parameters::LJGEN_b1, IA_parameters::LJGEN_b2, IA_parameters::LJGEN_capradius, IA_parameters::LJGEN_eps, IA_parameters::LJGEN_lambda, IA_parameters::LJGEN_sig, n_particle_types, params, and this_node.
Referenced by mpi_cap_forces_slave().
int ljgen_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double shift, double offset, int a1, int a2, double b1, double b2, double cap_radius, double lambda, double softrad)
Definition at line 40 of file ljgen.cpp.
References ES_ERROR, ES_OK, force_cap, get_ia_param_safe(), IA_parameters::LJGEN_a1, IA_parameters::LJGEN_a2, IA_parameters::LJGEN_b1, IA_parameters::LJGEN_b2, IA_parameters::LJGEN_capradius, IA_parameters::LJGEN_cut, IA_parameters::LJGEN_eps, IA_parameters::LJGEN_lambda, IA_parameters::LJGEN_offset, IA_parameters::LJGEN_shift, IA_parameters::LJGEN_sig, IA_parameters::LJGEN_softrad, mpi_bcast_ia_params(), and mpi_cap_forces().
Referenced by tclcommand_inter_parse_ljgen().