ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: maggs.hpp File Reference
maggs.hpp File Reference
Maxwell Equations Molecular Dynamics (MEMD) method for electrostatic interactions.
#include "config.hpp"
Data Structures
struct MAGGS_struct
Maggs structure.
Functions
External functions
void maggs_init ()
initialization function, parse command and set parameters.
int maggs_set_parameters (double bjerrum, double f_mass, int mesh, int finite_epsilon_flag, double epsilon_infty)
called from: initialize.cpp
int maggs_get_mesh_1D ()
get lattice size in one dimension
double maggs_set_permittivity (int node_x, int node_y, int node_z, int direction, double relative_epsilon)
set permittivity for single lattice links
void maggs_propagate_B_field (double dt)
Propagate the B-field in the system.
void maggs_calc_forces ()
Calculate the forces on all particles.
double maggs_electric_energy ()
Get the electric energy of the system as return value.
double maggs_magnetic_energy ()
Get the magnetic energy of the artificial transversal field component as return value.
int maggs_count_charged_particles ()
Count the number of charges in the whole system.
void maggs_exit ()
Clean up, free memory.
Variables
External structure
protect header file:
MAGGS_struct maggs
Detailed Description
Maxwell Equations Molecular Dynamics (MEMD) method for electrostatic interactions.
We use a local update scheme to propagate artificial B-fields on a lattice in the system. In principal, the algorithm simulates full electrodynamics, but with a tunable speed of light.
The method is very usable for large particle numbers or highly parallel architectures, since it is local and scales linearly. It is not suited for high-precision calculation of forces, since the simple interpolation scheme produces errors in the order of 10^-5 in the force.
The chosen mesh should roughly be of the size of the particles.
Further reading on the algorithm:
I. Pasichnyk and B. Dunweg, Coulomb interaction via local dynamics: a molecular-dynamics algorithm. J. Phys: Condens. Matter, 16 ,p. 1399-4020, (2004).
Definition in file maggs.hpp.
Function Documentation
void maggs_calc_forces ()
Calculate the forces on all particles.
Writes the result directly into the force pointer.
Calculate the forces on all particles.
Calculates the actual force on each particle by calling all other needed functions (except for maggs_propagate_B_field)
Definition at line 2239 of file maggs.cpp.
References CellPList::cell, cells_get_n_particles(), MAGGS_struct::finite_epsilon_flag, FOR3D, i, MAGGS_struct::inva, local_cells, lparams, maggs_add_transverse_field(), maggs_calc_part_link_forces(), maggs_calc_self_influence(), maggs_compute_dipole_correction(), maggs_couple_current_to_Dfield(), maggs_get_linear_index(), MAGGS_TRACE, maggs_update_charge_gradients(), CellPList::n, ParticleList::n, ParticlePosition::p, Particle::p, ParticleList::part, ParticleProperties::q, Particle::r, realloc, SPACE_DIM, and time_step.
Referenced by calc_long_range_forces().
int maggs_count_charged_particles ()
Count the number of charges in the whole system.
Count the number of charges in the whole system.
Returns
total number of charged particles in the system
Definition at line 272 of file maggs.cpp.
References CellPList::cell, comm_cart, i, local_cells, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, CellPList::n, ParticleList::n, and ParticleList::part.
Referenced by mpi_bcast_event_slave().
double maggs_electric_energy ()
Get the electric energy of the system as return value.
Get the electric energy of the system as return value.
Returns
returns electric energy
Definition at line 2315 of file maggs.cpp.
References MAGGS_struct::a, comm_cart, Dfield, FOR3D, FORALL_INNER_SITES, i, lattice, lparams, maggs_get_linear_index(), MPI_Allreduce(), MPI_DOUBLE, MPI_SUM, and SQR().
Referenced by calc_long_range_energies().
void maggs_exit ()
Clean up, free memory.
Not used at the moment.
Clean up, free memory.
Definition at line 2388 of file maggs.cpp.
References Bfield, Dfield, free, lattice, and neighbor.
int maggs_get_mesh_1D ()
get lattice size in one dimension
Returns
mesh in 1D
Definition at line 787 of file maggs.cpp.
References MAGGS_struct::mesh.
Referenced by tclcommand_localeps().
void maggs_init ()
initialization function, parse command and set parameters.
Called from initialize.cpp
initialization function, parse command and set parameters.
Sets maggs structure variables. Calls calculation of initial D-field.
Definition at line 2360 of file maggs.cpp.
References MAGGS_struct::a, MAGGS_struct::bjerrum, Coulomb_parameters::bjerrum, box_l, coulomb, MAGGS_struct::inva, M_PI, maggs_calc_init_e_field(), maggs_calc_self_energy_coeffs(), maggs_sanity_checks(), maggs_setup_local_lattice(), MAGGS_struct::mesh, MAGGS_struct::pref2, MAGGS_struct::prefactor, and temperature.
Referenced by on_boxl_change(), on_cell_structure_change(), on_coulomb_change(), and on_observable_calc().
double maggs_magnetic_energy ()
Get the magnetic energy of the artificial transversal field component as return value.
Get the magnetic energy of the artificial transversal field component as return value.
Integrates the B-field over the whole system to get the energy of the magnetic field.
Returns
returns magnetic energy
Definition at line 2338 of file maggs.cpp.
References MAGGS_struct::a, Bfield, FORALL_INNER_SITES, i, lparams, maggs_get_linear_index(), and SQR().
void maggs_propagate_B_field (double dt)
Propagate the B-field in the system.
Called TWICE from integrate.cpp with timestep dt/2 to ensure time-reversibility of the integrator.
Parameters
dt Timestep for which to propagate the field.
Propagate the B-field in the system.
Parameters
dt time step for update. Should be half the MD time step
Definition at line 1953 of file maggs.cpp.
References Bfield, Dfield, i, MAGGS_struct::invsqrt_f_mass, lparams, maggs_calc_dual_curl(), maggs_exchange_surface_patch(), maggs_get_linear_index(), and neighbor.
Referenced by integrate_sd(), and integrate_vv().
int maggs_set_parameters (double bjerrum, double f_mass, int mesh, int finite_epsilon_flag, double epsilon_infty)
called from: initialize.cpp
set the main parameters for the algorithm.
Parameters
bjerrum Bjerrum length for the system
f_mass parameter to tune the speed of light (1/c^2)
mesh Mesh size in one dimension
finite_epsilon_flag whether to do epsilon-at-infinity-correction
epsilon_infty epsilon-at-infinity
Definition at line 540 of file maggs.cpp.
References MAGGS_struct::bjerrum, MAGGS_struct::epsilon_infty, ES_OK, MAGGS_struct::f_mass, MAGGS_struct::finite_epsilon_flag, MAGGS_struct::invsqrt_f_mass, MAGGS_struct::mesh, and mpi_bcast_coulomb_params().
Referenced by tclcommand_inter_coulomb_parse_maggs().
double maggs_set_permittivity (int node_x, int node_y, int node_z, int direction, double relative_epsilon)
set permittivity for single lattice links
Parameters
node_x index of the node in x direction
node_y index of the node in y direction
node_z index of the node in z direction
direction direction in which the link points from the node. 0 is for x, 1 is for y, 2 is for z
relative_epsilon permittivity to set, relative to the background permittivity set by the bjerrum length
Definition at line 799 of file maggs.cpp.
References lattice, lparams, and maggs_get_linear_index().
Referenced by tclcommand_localeps().
Variable Documentation
MAGGS_struct maggs
Definition at line 157 of file maggs.cpp.
Referenced by mpi_bcast_coulomb_params_slave(), and tclprint_to_result_Maggs().