ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: magnetic_non_p3m_methods.cpp File Reference
magnetic_non_p3m_methods.cpp File Reference
All 3d non P3M methods to deal with the magnetic dipoles.
#include "domain_decomposition.hpp"
#include "magnetic_non_p3m_methods.hpp"
Functions
double calc_dipole_dipole_ia (Particle *p1, Particle *p2, int force_flag)
double dawaanr_calculations (int force_flag, int energy_flag)
Core of the DAWAANR method: here you compute all the magnetic forces, torques and the magnetic energy for the whole system.
int magnetic_dipolar_direct_sum_sanity_checks ()
double magnetic_dipolar_direct_sum_calculations (int force_flag, int energy_flag)
int dawaanr_set_params ()
switch on DAWAANR magnetostatics.
int mdds_set_params (int n_cut)
switch on direct sum magnetostatics.
Variables
int Ncut_off_magnetic_dipolar_direct_sum =0
Detailed Description
All 3d non P3M methods to deal with the magnetic dipoles.
DAWAANR => DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA Handling of a system of dipoles where no replicas Assumes minimum image convention for those axis in which the system is periodic as defined by setmd.
MDDS => Calculates dipole-dipole interaction of a perioidic system by explicitly summing the dipole-dipole interaction over several copies of the system Uses spherical summation order
Definition in file magnetic_non_p3m_methods.cpp.
Function Documentation
double calc_dipole_dipole_ia (Particle * p1, Particle * p2, int force_flag)
Definition at line 40 of file magnetic_non_p3m_methods.cpp.
References coulomb, ParticlePosition::dip, Coulomb_parameters::Dprefactor, ParticleForce::f, Particle::f, get_mi_vector(), ParticlePosition::p, Particle::r, and ParticleForce::torque.
Referenced by dawaanr_calculations().
double dawaanr_calculations (int force_flag, int energy_flag)
Core of the DAWAANR method: here you compute all the magnetic forces, torques and the magnetic energy for the whole system.
Definition at line 123 of file magnetic_non_p3m_methods.cpp.
References calc_dipole_dipole_ia(), CellPList::cell, ParticleProperties::dipm, errexit(), i, local_cells, CellPList::n, ParticleList::n, n_nodes, Particle::p, and ParticleList::part.
Referenced by calc_long_range_energies(), and calc_long_range_forces().
int dawaanr_set_params ()
switch on DAWAANR magnetostatics.
Returns
ES_ERROR, if not on a single CPU
Definition at line 446 of file magnetic_non_p3m_methods.cpp.
References coulomb, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, Coulomb_parameters::Dmethod, ES_ERROR, ES_OK, mpi_bcast_coulomb_params(), and n_nodes.
Referenced by tclcommand_inter_magnetic_parse_dawaanr().
double magnetic_dipolar_direct_sum_calculations (int force_flag, int energy_flag)
Definition at line 202 of file magnetic_non_p3m_methods.cpp.
References box_l, CellPList::cell, coulomb, ParticlePosition::dip, Coulomb_parameters::Dprefactor, errexit(), ParticleForce::f, Particle::f, fold_position(), free, i, ParticleLocal::i, Particle::l, local_cells, malloc, CellPList::n, ParticleList::n, n_nodes, n_part, Ncut_off_magnetic_dipolar_direct_sum, ParticlePosition::p, ParticleList::part, PERIODIC, Particle::r, and ParticleForce::torque.
Referenced by calc_long_range_energies(), and calc_long_range_forces().
int magnetic_dipolar_direct_sum_sanity_checks ()
Definition at line 192 of file magnetic_non_p3m_methods.cpp.
Referenced by interactions_sanity_checks().
int mdds_set_params (int n_cut)
switch on direct sum magnetostatics.
Parameters
n_cut cut off for the explicit summation
Returns
ES_ERROR, if not on a single CPU
Definition at line 460 of file magnetic_non_p3m_methods.cpp.
References coulomb, DIPOLAR_DS, DIPOLAR_MDLC_DS, Coulomb_parameters::Dmethod, ES_ERROR, ES_OK, mpi_bcast_coulomb_params(), n_nodes, and Ncut_off_magnetic_dipolar_direct_sum.
Referenced by tclcommand_inter_magnetic_parse_mdds().
Variable Documentation
int Ncut_off_magnetic_dipolar_direct_sum =0
Definition at line 187 of file magnetic_non_p3m_methods.cpp.
Referenced by magnetic_dipolar_direct_sum_calculations(), mdds_set_params(), and tclprint_to_result_Magnetic_dipolar_direct_sum_().