ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: magnetic_non_p3m_methods_tcl.cpp File Reference
magnetic_non_p3m_methods_tcl.cpp File Reference
#include "parser.hpp"
#include "magnetic_non_p3m_methods_tcl.hpp"
#include "magnetic_non_p3m_methods.hpp"
Functions
int tclprint_to_result_DAWAANR (Tcl_Interp *interp)
int tclcommand_inter_magnetic_parse_dawaanr (Tcl_Interp *interp, int argc, char **argv)
int tclprint_to_result_Magnetic_dipolar_direct_sum_ (Tcl_Interp *interp)
int tclcommand_inter_magnetic_parse_mdds (Tcl_Interp *interp, int argc, char **argv)
Variables
int Ncut_off_magnetic_dipolar_direct_sum
Function Documentation
int tclcommand_inter_magnetic_parse_dawaanr (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 53 of file magnetic_non_p3m_methods_tcl.cpp.
References dawaanr_set_params(), and ES_OK.
Referenced by tclcommand_inter_parse_magnetic().
int tclcommand_inter_magnetic_parse_mdds (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 94 of file magnetic_non_p3m_methods_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, ES_OK, and mdds_set_params().
Referenced by tclcommand_inter_parse_magnetic().
int tclprint_to_result_DAWAANR (Tcl_Interp * interp)
Definition at line 45 of file magnetic_non_p3m_methods_tcl.cpp.
Referenced by tclprint_to_result_DipolarIA().
int tclprint_to_result_Magnetic_dipolar_direct_sum_ (Tcl_Interp * interp)
Definition at line 82 of file magnetic_non_p3m_methods_tcl.cpp.
References Ncut_off_magnetic_dipolar_direct_sum.
Referenced by tclprint_to_result_DipolarIA().
Variable Documentation
int Ncut_off_magnetic_dipolar_direct_sum
Definition at line 187 of file magnetic_non_p3m_methods.cpp.
Referenced by magnetic_dipolar_direct_sum_calculations(), mdds_set_params(), and tclprint_to_result_Magnetic_dipolar_direct_sum_().