ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: metadynamics_tcl.cpp File Reference
metadynamics_tcl.cpp File Reference
#include "parser.hpp"
#include "metadynamics.hpp"
Functions
int tclcommand_metadynamics_print_status (Tcl_Interp *interp)
Print metadynamics options and parameters.
int tclcommand_metadynamics_print_usage (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_metadynamics_parse_off (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_metadynamics_parse_distance (Tcl_Interp *interp, int argc, char **argv)
Reaction coordinates available.
int tclcommand_metadynamics_parse_relative_z (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_metadynamics_print_stat (Tcl_Interp *interp, int argc, char **argv)
Input/Output stuff.
int tclcommand_metadynamics_parse_load_stat (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_metadynamics (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the Tcl command tclcommand_metadynamics.
Function Documentation
int tclcommand_metadynamics (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the Tcl command tclcommand_metadynamics.
This function allows to change the parameters of metadynamics
Definition at line 336 of file metadynamics_tcl.cpp.
References ARG1_IS_S, err, gather_runtime_errors(), tclcommand_metadynamics_parse_distance(), tclcommand_metadynamics_parse_load_stat(), tclcommand_metadynamics_parse_off(), tclcommand_metadynamics_parse_relative_z(), tclcommand_metadynamics_print_stat(), tclcommand_metadynamics_print_status(), and tclcommand_metadynamics_print_usage().
Referenced by tcl_register_commands().
int tclcommand_metadynamics_parse_distance (Tcl_Interp * interp, int argc, char ** argv)
Reaction coordinates available.
Definition at line 110 of file metadynamics_tcl.cpp.
References ARG_IS_D, ARG_IS_I, dmax(), dmin(), free, max_seen_particle, meta_acc_force, meta_acc_fprofile, meta_bias_height, meta_bias_width, META_DIST, meta_f_bound, meta_num_relaxation_steps, meta_pid1, meta_pid2, meta_switch, meta_xi_max, meta_xi_min, and meta_xi_num_bins.
Referenced by tclcommand_metadynamics().
int tclcommand_metadynamics_parse_load_stat (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 246 of file metadynamics_tcl.cpp.
References DoubleList::e, i, init_doublelist(), meta_acc_force, meta_acc_fprofile, meta_init(), META_OFF, meta_switch, meta_xi_num_bins, DoubleList::n, and realloc_doublelist().
Referenced by tclcommand_metadynamics().
int tclcommand_metadynamics_parse_off (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 99 of file metadynamics_tcl.cpp.
References META_OFF, meta_pid1, meta_pid2, and meta_switch.
Referenced by tclcommand_metadynamics().
int tclcommand_metadynamics_parse_relative_z (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 158 of file metadynamics_tcl.cpp.
References ARG_IS_D, ARG_IS_I, dmax(), dmin(), free, max_seen_particle, meta_acc_force, meta_acc_fprofile, meta_bias_height, meta_bias_width, meta_f_bound, meta_num_relaxation_steps, meta_pid1, meta_pid2, META_REL_Z, meta_switch, meta_xi_max, meta_xi_min, and meta_xi_num_bins.
Referenced by tclcommand_metadynamics().
int tclcommand_metadynamics_print_stat (Tcl_Interp * interp, int argc, char ** argv)
Input/Output stuff.
Definition at line 207 of file metadynamics_tcl.cpp.
References ARG1_IS_S, meta_acc_force, meta_acc_fprofile, meta_val_xi, meta_xi_min, meta_xi_num_bins, and meta_xi_step.
Referenced by tclcommand_metadynamics().
int tclcommand_metadynamics_print_status (Tcl_Interp * interp)
Print metadynamics options and parameters.
Definition at line 26 of file metadynamics_tcl.cpp.
References meta_bias_height, meta_bias_width, META_DIST, meta_f_bound, META_OFF, meta_pid1, meta_pid2, META_REL_Z, meta_switch, meta_xi_max, meta_xi_min, and meta_xi_num_bins.
Referenced by tclcommand_metadynamics().
int tclcommand_metadynamics_print_usage (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 84 of file metadynamics_tcl.cpp.
Referenced by tclcommand_metadynamics().