ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: minimize_energy.hpp File Reference
minimize_energy.hpp File Reference
#include "forces_inline.hpp"
#include "communication.hpp"
Functions
bool minimize_energy (void)
void minimize_energy_init (const double f_max, const double gamma, const int max_steps, const double max_displacement)
bool steepest_descent_step (void)
Function Documentation
bool minimize_energy (void)
Definition at line 117 of file minimize_energy.cpp.
References comm_cart, INTEG_METHOD_STEEPEST_DESCENT, integ_switch, integrate_vv(), MPI_Bcast(), and MPI_BYTE.
Referenced by mpi_minimize_energy(), and mpi_minimize_energy_slave().
void minimize_energy_init (const double f_max, const double gamma, const int max_steps, const double max_displacement)
Definition at line 107 of file minimize_energy.cpp.
Referenced by tclcommand_minimize_energy().
bool steepest_descent_step (void)
Definition at line 48 of file minimize_energy.cpp.
References announce_resort_particles(), CellPList::cell, comm_cart, COORD_FIXED, distance2(), ParticleForce::f, Particle::f, i, ifParticleIsVirtual(), Particle::l, local_cells, MINIMIZE_ENERGY_TRACE, MPI_Allreduce(), MPI_DOUBLE, MPI_MAX, CellPList::n, ParticleList::n, ParticlePosition::p, Particle::p, ParticleLocal::p_old, ParticleList::part, Particle::r, resort_particles, skin, skin2, and SQR().
Referenced by integrate_vv().