ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: mmm-common.cpp File Reference
mmm-common.cpp File Reference
Common parts of the MMM family of methods for the electrostatic interaction, MMM1D, MMM2D and ELC.
#include "mmm-common.hpp"
#include "utils.hpp"
Functions
static void preparePolygammaEven (int n, double binom, Polynom *series)
static void preparePolygammaOdd (int n, double binom, Polynom *series)
void create_mod_psi_up_to (int new_n)
create the both the even and odd polygamma functions up to order 2*n
Variables
Polynom * modPsi = NULL
table of the Taylor expansions of the modified polygamma functions
int n_modPsi = 0
Detailed Description
Common parts of the MMM family of methods for the electrostatic interaction, MMM1D, MMM2D and ELC.
This file contains the code for the polygamma expansions used for the near formulas of MMM1D and MMM2D.
The expansion of the polygamma functions is fairly easy and follows directly from Abramowitz and Stegun. For details, see Axel Arnold and Christian Holm, "MMM2D: A fast and accurate summation method for electrostatic interactions in 2D slab geometries", Comp. Phys. Comm., 148/3(2002),327-348.
Definition in file mmm-common.cpp.
Function Documentation
void create_mod_psi_up_to (int new_n)
create the both the even and odd polygamma functions up to order 2*n
Definition at line 109 of file mmm-common.cpp.
References n_modPsi, preparePolygammaEven(), preparePolygammaOdd(), and realloc.
Referenced by MMM2D_tune_near(), modpsi_init(), and prepare_polygamma_series().
static void preparePolygammaEven (int n, double binom, Polynom * series) static
Definition at line 37 of file mmm-common.cpp.
References alloc_doublelist(), C_GAMMA, DoubleList::e, hzeta(), init_doublelist(), DoubleList::n, realloc_doublelist(), and ROUND_ERROR_PREC.
Referenced by create_mod_psi_up_to().
static void preparePolygammaOdd (int n, double binom, Polynom * series) static
Definition at line 83 of file mmm-common.cpp.
References DoubleList::e, hzeta(), init_doublelist(), DoubleList::n, realloc_doublelist(), and ROUND_ERROR_PREC.
Referenced by create_mod_psi_up_to().
Variable Documentation
Polynom* modPsi = NULL
table of the Taylor expansions of the modified polygamma functions
Definition at line 34 of file mmm-common.cpp.
Referenced by modpsi_init().
int n_modPsi = 0
Definition at line 35 of file mmm-common.cpp.
Referenced by add_mmm1d_coulomb_pair_force(), add_mmm2d_coulomb_pair_force(), calc_mmm2d_copy_pair_energy(), create_mod_psi_up_to(), mmm1d_coulomb_pair_energy(), and modpsi_init().