ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: Mmm1dgpuForce_cuda.cu File Reference
Mmm1dgpuForce_cuda.cu File Reference
#include "actor/Mmm1dgpuForce.hpp"
#include "cuda_utils.hpp"
#include "mmm-common_cuda.hpp"
#include "mmm1d.hpp"
#include "interaction_data.hpp"
#include "EspressoSystemInterface.hpp"
Macros
#define cudaSetDevice(d)
Functions
__device__ void atomicadd (float *address, float value)
__forceinline__ __device__ mmm1dgpu_real sqpow (mmm1dgpu_real x)
__forceinline__ __device__ mmm1dgpu_real cbpow (mmm1dgpu_real x)
__device__ void sumReduction (mmm1dgpu_real *input, mmm1dgpu_real *sum)
__global__ void sumKernel (mmm1dgpu_real *data, int N)
__global__ void besselTuneKernel (int *result, mmm1dgpu_real far_switch_radius, int maxCut)
__global__ void forcesKernel (const __restrict__ mmm1dgpu_real *r, const __restrict__ mmm1dgpu_real *q, __restrict__ mmm1dgpu_real *force, int N, int pairs, int tStart=0, int tStop=-1)
__global__ void energiesKernel (const __restrict__ mmm1dgpu_real *r, const __restrict__ mmm1dgpu_real *q, __restrict__ mmm1dgpu_real *energy, int N, int pairs, int tStart=0, int tStop=-1)
__global__ void vectorReductionKernel (mmm1dgpu_real *src, mmm1dgpu_real *dst, int N, int tStart=0, int tStop=-1)
__global__ void scaleAndAddKernel (mmm1dgpu_real *dst, mmm1dgpu_real *src, int N, mmm1dgpu_real factor)
Variables
const int deviceCount = 1
float multigpu_factors [] = {1.0}
const mmm1dgpu_real C_GAMMAf = C_GAMMA
const mmm1dgpu_real C_2PIf = C_2PI
__constant__ mmm1dgpu_real far_switch_radius_2 = 0.05*0.05
__constant__ mmm1dgpu_real boxz
__constant__ mmm1dgpu_real uz
__constant__ mmm1dgpu_real coulomb_prefactor = 1.0
__constant__ int bessel_cutoff = 5
__constant__ mmm1dgpu_real maxPWerror = 1e-5
Macro Definition Documentation
#define cudaSetDevice (d)
Definition at line 27 of file Mmm1dgpuForce_cuda.cu.
Referenced by modpsi_init(), Mmm1dgpuForce::set_params(), and Mmm1dgpuForce::setup().
Function Documentation
__device__ void atomicadd (float * address, float value) inline
Definition at line 38 of file Mmm1dgpuForce_cuda.cu.
References atomicAdd().
Referenced by forcesKernel().
__global__ void besselTuneKernel (int * result, mmm1dgpu_real far_switch_radius, int maxCut)
Definition at line 196 of file Mmm1dgpuForce_cuda.cu.
References C_2PIf, dev_K1(), err, maxPWerror, and uz.
__forceinline__ __device__ mmm1dgpu_real cbpow (mmm1dgpu_real x)
Definition at line 154 of file Mmm1dgpuForce_cuda.cu.
Referenced by forcesKernel().
__global__ void energiesKernel (const __restrict__ mmm1dgpu_real * r, const __restrict__ mmm1dgpu_real * q, __restrict__ mmm1dgpu_real * energy, int N, int pairs, int tStart = 0, int tStop = -1)
Definition at line 407 of file Mmm1dgpuForce_cuda.cu.
References bessel_cutoff, boxz, C_2PIf, C_GAMMAf, coulomb_prefactor, dev_K0(), dev_mod_psi_even(), device_n_modPsi, far_switch_radius_2, maxPWerror, sqpow(), sumReduction(), and uz.
Referenced by Mmm1dgpuForce::computeEnergy().
__global__ void forcesKernel (const __restrict__ mmm1dgpu_real * r, const __restrict__ mmm1dgpu_real * q, __restrict__ mmm1dgpu_real * force, int N, int pairs, int tStart = 0, int tStop = -1)
Definition at line 313 of file Mmm1dgpuForce_cuda.cu.
References atomicadd(), bessel_cutoff, boxz, C_2PIf, cbpow(), coulomb_prefactor, dev_K0(), dev_K1(), dev_mod_psi_even(), dev_mod_psi_odd(), device_n_modPsi, far_switch_radius_2, maxPWerror, sqpow(), and uz.
Referenced by Mmm1dgpuForce::computeForces().
__global__ void scaleAndAddKernel (mmm1dgpu_real * dst, mmm1dgpu_real * src, int N, mmm1dgpu_real factor)
Definition at line 530 of file Mmm1dgpuForce_cuda.cu.
Referenced by Mmm1dgpuForce::computeEnergy().
__forceinline__ __device__ mmm1dgpu_real sqpow (mmm1dgpu_real x)
Definition at line 150 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), and forcesKernel().
__global__ void sumKernel (mmm1dgpu_real * data, int N)
Definition at line 173 of file Mmm1dgpuForce_cuda.cu.
References i, and sumReduction().
Referenced by Mmm1dgpuForce::computeEnergy().
__device__ void sumReduction (mmm1dgpu_real * input, mmm1dgpu_real * sum)
Definition at line 159 of file Mmm1dgpuForce_cuda.cu.
References i.
Referenced by energiesKernel(), and sumKernel().
__global__ void vectorReductionKernel (mmm1dgpu_real * src, mmm1dgpu_real * dst, int N, int tStart = 0, int tStop = -1)
Definition at line 483 of file Mmm1dgpuForce_cuda.cu.
References i.
Referenced by Mmm1dgpuForce::computeForces().
Variable Documentation
__constant__ int bessel_cutoff = 5
Definition at line 63 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), forcesKernel(), and tclcommand_inter_coulomb_parse_mmm1dgpu().
__constant__ mmm1dgpu_real boxz
Definition at line 60 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), forcesKernel(), and Mmm1dgpuForce::set_params().
const mmm1dgpu_real C_2PIf = C_2PI
Definition at line 57 of file Mmm1dgpuForce_cuda.cu.
Referenced by besselTuneKernel(), energiesKernel(), and forcesKernel().
const mmm1dgpu_real C_GAMMAf = C_GAMMA
Definition at line 56 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel().
__constant__ mmm1dgpu_real coulomb_prefactor = 1.0
Definition at line 62 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), EwaldGPU_EnergyReci_LowThreads(), EwaldGPU_EnergyReci_MaxThreads(), EwaldGPU_ForcesReci_LowThreads(), EwaldGPU_ForcesReci_MaxThreads(), and forcesKernel().
const int deviceCount = 1
Definition at line 25 of file Mmm1dgpuForce_cuda.cu.
Referenced by modpsi_init(), Mmm1dgpuForce::set_params(), and Mmm1dgpuForce::setup().
__constant__ mmm1dgpu_real far_switch_radius_2 = 0.05*0.05
Definition at line 59 of file Mmm1dgpuForce_cuda.cu.
Referenced by energiesKernel(), forcesKernel(), and Mmm1dgpuForce::set_params().
__constant__ mmm1dgpu_real maxPWerror = 1e-5
Definition at line 64 of file Mmm1dgpuForce_cuda.cu.
Referenced by besselTuneKernel(), energiesKernel(), forcesKernel(), mdlc_set_params(), MMM1D_set_params(), MMM2D_set_params(), tclcommand_inter_coulomb_parse_mmm1d(), tclcommand_inter_coulomb_parse_mmm1dgpu(), and tclcommand_inter_coulomb_parse_mmm2d().
float multigpu_factors[] = {1.0}
Definition at line 26 of file Mmm1dgpuForce_cuda.cu.
__constant__ mmm1dgpu_real uz
Definition at line 61 of file Mmm1dgpuForce_cuda.cu.
Referenced by besselTuneKernel(), energiesKernel(), forcesKernel(), and Mmm1dgpuForce::set_params().