ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: mmm1d.hpp File Reference
mmm1d.hpp File Reference
MMM1D algorithm for long range coulomb interactions.
#include "utils.hpp"
#include "particle_data.hpp"
Data Structures
struct MMM1D_struct
parameters for the MMM1D electrostatic interaction
Functions
int MMM1D_set_params (double switch_rad, double maxPWerror)
parameters for MMM1D.
int MMM1D_sanity_checks ()
check that MMM1D can run with the current parameters
void MMM1D_init ()
initialize the MMM1D constants
void add_mmm1d_coulomb_pair_force (double chprf, double d[3], double dist2, double dist, double force[3])
double mmm1d_coulomb_pair_energy (Particle *p1, Particle *p2, double d[3], double r2, double r)
int mmm1d_tune (char **log)
tuning of the parameters which are not set by the user, e.g.
Variables
MMM1D_struct mmm1d_params
Detailed Description
MMM1D algorithm for long range coulomb interactions.
Implementation of the MMM1D method for the calculation of the electrostatic interaction in one dimensionally periodic systems. For details on the method see MMM in general. The MMM1D method works only with the nsquared cell system, since neither the near nor far formula can be decomposed. However, this implementation is reasonably fast, so that one can use up to 200 charges easily in a simulation.
Definition in file mmm1d.hpp.
Function Documentation
void add_mmm1d_coulomb_pair_force (double chprf, double d[3], double dist2, double dist, double force[3])
Definition at line 187 of file mmm1d.cpp.
References bessel_radii, box_l, C_2PI, coulomb, MMM1D_struct::far_switch_radius_2, K0, K1, LPK01(), MAXIMAL_B_CUT, MMM1D_struct::maxPWerror, mod_psi_even(), mod_psi_odd(), n_modPsi, Coulomb_parameters::prefactor, prefL3_i, prefuz2, uz, and uz2.
Referenced by add_non_bonded_pair_force(), and add_non_bonded_pair_force_iccp3m().
double mmm1d_coulomb_pair_energy (Particle * p1, Particle * p2, double d[3], double r2, double r)
Definition at line 292 of file mmm1d.cpp.
References bessel_radii, box_l, C_2PI, C_GAMMA, coulomb, MMM1D_struct::far_switch_radius_2, K0, M_LN2, MAXIMAL_B_CUT, MMM1D_struct::maxPWerror, mod_psi_even(), n_modPsi, Particle::p, Coulomb_parameters::prefactor, ParticleProperties::q, uz, and uz2.
Referenced by add_non_bonded_pair_energy().
void MMM1D_init ()
initialize the MMM1D constants
Definition at line 170 of file mmm1d.cpp.
References box_l, coulomb, determine_bessel_radii(), MMM1D_struct::far_switch_radius_2, L2, MAXIMAL_B_CUT, MMM1D_struct::maxPWerror, MMM1D_sanity_checks(), Coulomb_parameters::prefactor, prefL3_i, prefuz2, prepare_polygamma_series(), SQR(), uz, and uz2.
Referenced by on_boxl_change(), on_cell_structure_change(), and on_coulomb_change().
int MMM1D_sanity_checks ()
check that MMM1D can run with the current parameters
Definition at line 151 of file mmm1d.cpp.
References cell_structure, CELL_STRUCTURE_NSQUARE, PERIODIC, runtimeError, and CellStructure::type.
Referenced by interactions_sanity_checks(), and MMM1D_init().
int MMM1D_set_params (double switch_rad, double maxPWerror)
parameters for MMM1D.
Most of the parameters can also be tuned automatically. Unlike P3M, this tuning is redone automatically whenever parameters change, but not immediately if you set this parameters.
Parameters
switch_rad at which xy-distance the calculation switches from the far to the near formula. If -1, this parameter will be tuned automatically.
maxPWerror the maximal allowed error for the potential and the forces without the prefactors, i. e. for the pure lattice 1/r-sum.
Definition at line 140 of file mmm1d.cpp.
References coulomb, COULOMB_MMM1D, MMM1D_struct::far_switch_radius_2, MMM1D_struct::maxPWerror, maxPWerror, Coulomb_parameters::method, mpi_bcast_coulomb_params(), and SQR().
Referenced by tclcommand_inter_coulomb_parse_mmm1d().
int mmm1d_tune (char ** log)
tuning of the parameters which are not set by the user, e.g.
the switching radius or the bessel_cutoff. Call this only on the master node.
Parameters
log contains information about the tuning (tried values and errors)
Returns
ES_OK or ES_ERROR
Definition at line 358 of file mmm1d.cpp.
References bessel_radii, box_l, coulomb, COULOMB_MMM1D, ES_DOUBLE_SPACE, ES_ERROR, ES_INTEGER_SPACE, ES_OK, MMM1D_struct::far_switch_radius_2, MAXIMAL_B_CUT, Coulomb_parameters::method, mpi_bcast_coulomb_params(), SQR(), strcat_alloc(), TEST_INTEGRATIONS, and time_force_calc().
Referenced by tclcommand_inter_coulomb_parse_mmm1d().
Variable Documentation
MMM1D_struct mmm1d_params
Definition at line 65 of file mmm1d.cpp.
Referenced by coulomb_set_bjerrum(), mpi_bcast_coulomb_params_slave(), Mmm1dgpuForce::set_params(), tclprint_to_result_MMM1D(), and tclprint_to_result_MMM1DGPU().