ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: Mmm1dgpu_tcl.cpp File Reference
Mmm1dgpu_tcl.cpp File Reference
#include "Mmm1dgpu_tcl.hpp"
#include "forces.hpp"
#include "energy.hpp"
#include "actor/Mmm1dgpuForce.hpp"
#include "mmm1d.hpp"
#include "EspressoSystemInterface.hpp"
Functions
int tclprint_to_result_MMM1DGPU (Tcl_Interp *interp)
print the mmm1d parameters to the interpreters result
int tclcommand_inter_coulomb_parse_mmm1dgpu (Tcl_Interp *interp, int argc, char **argv)
parse the mmm1d parameters
Variables
Mmm1dgpuForce * mmm1dgpuForce
Function Documentation
int tclcommand_inter_coulomb_parse_mmm1dgpu (Tcl_Interp * interp, int argc, char ** argv)
parse the mmm1d parameters
Definition at line 55 of file Mmm1dgpu_tcl.cpp.
References ActorList::add(), ARG0_IS_S, ARG_IS_D, ARG_IS_I, bessel_cutoff, box_l, coulomb, COULOMB_MMM1D_GPU, energyActors, espressoSystemInterface, forceActors, maxPWerror, Coulomb_parameters::method, mpi_bcast_coulomb_params(), and Mmm1dgpuForce::set_params().
Referenced by tclcommand_inter_parse_coulomb().
int tclprint_to_result_MMM1DGPU (Tcl_Interp * interp)
print the mmm1d parameters to the interpreters result
Definition at line 30 of file Mmm1dgpu_tcl.cpp.
References MMM1D_struct::bessel_cutoff, MMM1D_struct::far_switch_radius_2, MMM1D_struct::maxPWerror, and mmm1d_params.
Referenced by tclprint_to_result_CoulombIA().
Variable Documentation
Mmm1dgpuForce* mmm1dgpuForce
Definition at line 28 of file Mmm1dgpu_tcl.cpp.