ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: mmm1d.cpp File Reference
mmm1d.cpp File Reference
MMM1D algorithm for long range coulomb interaction.
#include "utils.hpp"
#include "mmm1d.hpp"
#include "polynom.hpp"
#include "specfunc.hpp"
#include "communication.hpp"
#include "cells.hpp"
#include "grid.hpp"
#include "tuning.hpp"
#include "interaction_data.hpp"
#include "mmm-common.hpp"
#include "errorhandling.hpp"
Macros
#define TEST_INTEGRATIONS 1000
How many trial calculations.
#define MAXIMAL_B_CUT 30
Largest numerically stable cutoff for Bessel function.
#define MIN_RAD 0.01
minimal radius for the far formula in multiples of box_l[2]
#define K0 LPK0
if you define this, the Besselfunctions are calculated up to machine precision, otherwise 10^-14, which should be definitely enough for daily life.
#define K1 LPK1
Functions
static double far_error (int P, double minrad)
static double determine_minrad (double maxPWerror, int P)
static void determine_bessel_radii (double maxPWerror, int maxP)
static void prepare_polygamma_series (double maxPWerror, double maxrad2)
int MMM1D_set_params (double switch_rad, double maxPWerror)
parameters for MMM1D.
int MMM1D_sanity_checks ()
check that MMM1D can run with the current parameters
void MMM1D_init ()
initialize the MMM1D constants
void add_mmm1d_coulomb_pair_force (double chpref, double d[3], double r2, double r, double force[3])
double mmm1d_coulomb_pair_energy (Particle *p1, Particle *p2, double d[3], double r2, double r)
int mmm1d_tune (char **log)
tuning of the parameters which are not set by the user, e.g.
Variables
MMM1D_struct mmm1d_params = { 0.05, 1e-5 }
static double * bessel_radii
From which distance a certain bessel cutoff is valid.
static double uz
inverse box dimensions and other constants
static double L2
static double uz2
static double prefuz2
static double prefL3_i
Detailed Description
MMM1D algorithm for long range coulomb interaction.
For more information about MMM1D, see mmm1d.h.
Definition in file mmm1d.cpp.
Macro Definition Documentation
#define K0 LPK0
if you define this, the Besselfunctions are calculated up to machine precision, otherwise 10^-14, which should be definitely enough for daily life.
Definition at line 56 of file mmm1d.cpp.
Referenced by add_mmm1d_coulomb_pair_force(), and mmm1d_coulomb_pair_energy().
#define K1 LPK1
Definition at line 57 of file mmm1d.cpp.
Referenced by add_mmm1d_coulomb_pair_force(), and far_error().
#define MAXIMAL_B_CUT 30
Largest numerically stable cutoff for Bessel function.
Don't change without improving the formulas.
Definition at line 45 of file mmm1d.cpp.
Referenced by add_mmm1d_coulomb_pair_force(), mmm1d_coulomb_pair_energy(), MMM1D_init(), and mmm1d_tune().
#define MIN_RAD 0.01
minimal radius for the far formula in multiples of box_l[2]
Definition at line 48 of file mmm1d.cpp.
Referenced by determine_minrad().
#define TEST_INTEGRATIONS 1000
How many trial calculations.
Definition at line 41 of file mmm1d.cpp.
Referenced by mmm1d_tune().
Function Documentation
void add_mmm1d_coulomb_pair_force (double chpref, double d[3], double r2, double r, double force[3])
Definition at line 187 of file mmm1d.cpp.
References bessel_radii, box_l, C_2PI, coulomb, MMM1D_struct::far_switch_radius_2, K0, K1, LPK01(), MAXIMAL_B_CUT, MMM1D_struct::maxPWerror, mod_psi_even(), mod_psi_odd(), n_modPsi, Coulomb_parameters::prefactor, prefL3_i, prefuz2, uz, and uz2.
Referenced by add_non_bonded_pair_force(), and add_non_bonded_pair_force_iccp3m().
static void determine_bessel_radii (double maxPWerror, int maxP) static
Definition at line 109 of file mmm1d.cpp.
References bessel_radii, determine_minrad(), and realloc.
Referenced by MMM1D_init().
static double determine_minrad (double maxPWerror, int P) static
Definition at line 80 of file mmm1d.cpp.
References box_l, dmax(), dmin(), far_error(), and MIN_RAD.
Referenced by determine_bessel_radii().
static double far_error (int P, double minrad) static
Definition at line 71 of file mmm1d.cpp.
References dmax(), K1, M_PI, and uz.
Referenced by determine_minrad().
double mmm1d_coulomb_pair_energy (Particle * p1, Particle * p2, double d[3], double r2, double r)
Definition at line 292 of file mmm1d.cpp.
References bessel_radii, box_l, C_2PI, C_GAMMA, coulomb, MMM1D_struct::far_switch_radius_2, K0, M_LN2, MAXIMAL_B_CUT, MMM1D_struct::maxPWerror, mod_psi_even(), n_modPsi, Particle::p, Coulomb_parameters::prefactor, ParticleProperties::q, uz, and uz2.
Referenced by add_non_bonded_pair_energy().
void MMM1D_init ()
initialize the MMM1D constants
Definition at line 170 of file mmm1d.cpp.
References box_l, coulomb, determine_bessel_radii(), MMM1D_struct::far_switch_radius_2, L2, MAXIMAL_B_CUT, MMM1D_struct::maxPWerror, MMM1D_sanity_checks(), Coulomb_parameters::prefactor, prefL3_i, prefuz2, prepare_polygamma_series(), SQR(), uz, and uz2.
Referenced by on_boxl_change(), on_cell_structure_change(), and on_coulomb_change().
int MMM1D_sanity_checks ()
check that MMM1D can run with the current parameters
Definition at line 151 of file mmm1d.cpp.
References cell_structure, CELL_STRUCTURE_NSQUARE, PERIODIC, runtimeError, and CellStructure::type.
Referenced by interactions_sanity_checks(), and MMM1D_init().
int MMM1D_set_params (double switch_rad, double maxPWerror)
parameters for MMM1D.
Most of the parameters can also be tuned automatically. Unlike P3M, this tuning is redone automatically whenever parameters change, but not immediately if you set this parameters.
Parameters
switch_rad at which xy-distance the calculation switches from the far to the near formula. If -1, this parameter will be tuned automatically.
maxPWerror the maximal allowed error for the potential and the forces without the prefactors, i. e. for the pure lattice 1/r-sum.
Definition at line 140 of file mmm1d.cpp.
References coulomb, COULOMB_MMM1D, MMM1D_struct::far_switch_radius_2, MMM1D_struct::maxPWerror, maxPWerror, Coulomb_parameters::method, mpi_bcast_coulomb_params(), and SQR().
Referenced by tclcommand_inter_coulomb_parse_mmm1d().
int mmm1d_tune (char ** log)
tuning of the parameters which are not set by the user, e.g.
the switching radius or the bessel_cutoff. Call this only on the master node.
Parameters
log contains information about the tuning (tried values and errors)
Returns
ES_OK or ES_ERROR
Definition at line 358 of file mmm1d.cpp.
References bessel_radii, box_l, coulomb, COULOMB_MMM1D, ES_DOUBLE_SPACE, ES_ERROR, ES_INTEGER_SPACE, ES_OK, MMM1D_struct::far_switch_radius_2, MAXIMAL_B_CUT, Coulomb_parameters::method, mpi_bcast_coulomb_params(), SQR(), strcat_alloc(), TEST_INTEGRATIONS, and time_force_calc().
Referenced by tclcommand_inter_coulomb_parse_mmm1d().
static void prepare_polygamma_series (double maxPWerror, double maxrad2) static
Definition at line 118 of file mmm1d.cpp.
References create_mod_psi_up_to(), err, mod_psi_even(), and uz2.
Referenced by MMM1D_init().
Variable Documentation
double* bessel_radii static
From which distance a certain bessel cutoff is valid.
Can't be part of the params since these get broadcasted.
Definition at line 68 of file mmm1d.cpp.
Referenced by add_mmm1d_coulomb_pair_force(), determine_bessel_radii(), mmm1d_coulomb_pair_energy(), and mmm1d_tune().
double L2 static
Definition at line 62 of file mmm1d.cpp.
Referenced by MMM1D_init().
MMM1D_struct mmm1d_params = { 0.05, 1e-5 }
Definition at line 65 of file mmm1d.cpp.
Referenced by coulomb_set_bjerrum(), mpi_bcast_coulomb_params_slave(), Mmm1dgpuForce::set_params(), tclprint_to_result_MMM1D(), and tclprint_to_result_MMM1DGPU().
double prefL3_i static
Definition at line 62 of file mmm1d.cpp.
Referenced by add_mmm1d_coulomb_pair_force(), and MMM1D_init().
double prefuz2 static
Definition at line 62 of file mmm1d.cpp.
Referenced by add_mmm1d_coulomb_pair_force(), and MMM1D_init().
double uz static
inverse box dimensions and other constants
Definition at line 62 of file mmm1d.cpp.
Referenced by add_mmm1d_coulomb_pair_force(), far_error(), mmm1d_coulomb_pair_energy(), and MMM1D_init().
double uz2 static
Definition at line 62 of file mmm1d.cpp.
Referenced by add_mmm1d_coulomb_pair_force(), mmm1d_coulomb_pair_energy(), MMM1D_init(), and prepare_polygamma_series().