ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: mmm2d.hpp File Reference
mmm2d.hpp File Reference
MMM2D algorithm for long range coulomb interaction in 2d+h geometries.
#include "utils.hpp"
Data Structures
struct MMM2D_struct
parameters for the MMM2D method for electrostatics.
Functions
int MMM2D_set_params (double maxPWerror, double far_cut, double delta_top, double delta_bot, int const_pot_on, double pot_diff)
set parameters for MMM2D.
double MMM2D_add_far (int f, int e)
the general long range force/energy calculation
void MMM2D_add_far_force ()
the actual long range force calculation
double MMM2D_far_energy ()
the actual long range energy calculation
void add_mmm2d_coulomb_pair_force (double charge_factor, double dv[3], double d2, double d, double f[3])
pairwise calculated parts of MMM2D force (near neighbors)
double mmm2d_coulomb_pair_energy (double charge_factor, double dv[3], double d2, double d)
pairwise calculated parts of MMM2D force (near neighbors)
int MMM2D_sanity_checks ()
check that MMM2D can run with the current parameters
void MMM2D_init ()
initialize the MMM2D constants
void MMM2D_on_resort_particles ()
if the number of particles has changed (even per node), the particle buffers for the coefficients have to be resized.
double MMM2D_dielectric_layers_energy_contribution ()
energy contribution from dielectric layers
void MMM2D_dielectric_layers_force_contribution ()
force contribution from dielectric layers
Variables
char const * mmm2d_errors []
error messages, see above
MMM2D_struct mmm2d_params
Detailed Description
MMM2D algorithm for long range coulomb interaction in 2d+h geometries.
Implementation of the MMM2D method for the calculation of the electrostatic interaction for two dimensionally periodic systems. For details on the method see MMM general. The MMM2D method works only with the layered or nsquared cell system. The tuning is not automated, since the only tunable parameter is the cell size, which can be changed easily in Tcl. Moreover, only a few values make sense to be tested, since in general the number of cells will be between 5 and 20.
Definition in file mmm2d.hpp.
Function Documentation
void add_mmm2d_coulomb_pair_force (double charge_factor, double dv[3], double d2, double d, double f[3])
pairwise calculated parts of MMM2D force (near neighbors)
Definition at line 1504 of file mmm2d.cpp.
References box_l, C_2PI, COMPLEX_FAC, COMPLEX_STEP, complexCutoff, coulomb, IntList::e, DoubleList::e, i, K0, K1, LPK01(), mod_psi_even(), mod_psi_odd(), IntList::n, n_modPsi, part_error, Coulomb_parameters::prefactor, runtimeError, ux, ux2, uy, and uy2.
Referenced by add_non_bonded_pair_force(), add_non_bonded_pair_force_iccp3m(), and MMM2D_dielectric_layers_force_contribution().
double MMM2D_add_far (int f, int e)
the general long range force/energy calculation
Definition at line 1295 of file mmm2d.cpp.
References add_force_contribution(), box_l, C_2PI, energy_contribution(), MMM2D_struct::far_cut, MMM2D_struct::far_cut2, FARRELPREC, free, malloc, n_scxcache, n_scycache, prepare_scx_cache(), prepare_scy_cache(), self_energy, SQR(), ux, ux2, uy2, and uz.
Referenced by MMM2D_add_far_force(), and MMM2D_far_energy().
void MMM2D_add_far_force () inline
the actual long range force calculation
Definition at line 79 of file mmm2d.hpp.
References MMM2D_add_far().
Referenced by calc_long_range_forces(), and calc_long_range_forces_iccp3m().
double mmm2d_coulomb_pair_energy (double charge_factor, double dv[3], double d2, double d)
pairwise calculated parts of MMM2D force (near neighbors)
Definition at line 1791 of file mmm2d.cpp.
References calc_mmm2d_copy_pair_energy(), coulomb, and Coulomb_parameters::prefactor.
Referenced by add_non_bonded_pair_energy(), and MMM2D_dielectric_layers_energy_contribution().
double MMM2D_dielectric_layers_energy_contribution ()
energy contribution from dielectric layers
Definition at line 2036 of file mmm2d.cpp.
References box_l, C_2PI, cells, coulomb, MMM2D_struct::delta_mid_bot, MMM2D_struct::delta_mid_top, MMM2D_struct::dielectric_contrast_on, i, layered_get_mi_vector(), mmm2d_coulomb_pair_energy(), ParticleList::n, n_layers, n_nodes, ParticlePosition::p, Particle::p, ParticleList::part, Coulomb_parameters::prefactor, ParticleProperties::q, Particle::r, sqrlen(), this_node, ux, and uy.
Referenced by calc_long_range_energies().
void MMM2D_dielectric_layers_force_contribution ()
force contribution from dielectric layers
Definition at line 1970 of file mmm2d.cpp.
References add_mmm2d_coulomb_pair_force(), box_l, C_2PI, cells, coulomb, MMM2D_struct::delta_mid_bot, MMM2D_struct::delta_mid_top, MMM2D_struct::dielectric_contrast_on, ParticleForce::f, Particle::f, i, layered_get_mi_vector(), ParticleList::n, n_layers, n_nodes, ParticlePosition::p, Particle::p, ParticleList::part, Coulomb_parameters::prefactor, ParticleProperties::q, Particle::r, sqrlen(), this_node, ux, and uy.
Referenced by calc_long_range_forces(), and calc_long_range_forces_iccp3m().
double MMM2D_far_energy () inline
the actual long range energy calculation
Definition at line 84 of file mmm2d.hpp.
References MMM2D_add_far().
Referenced by calc_long_range_energies().
void MMM2D_init ()
initialize the MMM2D constants
Definition at line 1916 of file mmm2d.cpp.
References cell_structure, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, coulomb, COULOMB_NONE, MMM2D_struct::dielectric_contrast_on, err, MMM2D_struct::far_calculated, MMM2D_struct::far_cut, MMM2D_struct::maxPWerror, Coulomb_parameters::method, mmm2d_errors, MMM2D_sanity_checks(), MMM2D_setup_constants(), MMM2D_tune_far(), MMM2D_tune_near(), n_nodes, runtimeError, and CellStructure::type.
Referenced by on_boxl_change(), on_cell_structure_change(), and on_coulomb_change().
void MMM2D_on_resort_particles ()
if the number of particles has changed (even per node), the particle buffers for the coefficients have to be resized.
Definition at line 1952 of file mmm2d.cpp.
References cell_structure, CELL_STRUCTURE_LAYERED, cells_get_n_particles(), MMM2D_struct::far_cut, gblcblk, lclcblk, MMM2D_self_energy(), n_cells, n_scxcache, n_scycache, partblk, realloc, scxcache, scycache, CellStructure::type, ux, and uy.
Referenced by on_resort_particles().
int MMM2D_sanity_checks ()
check that MMM2D can run with the current parameters
Definition at line 1896 of file mmm2d.cpp.
References cell_structure, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, PERIODIC, runtimeError, and CellStructure::type.
Referenced by interactions_sanity_checks(), and MMM2D_init().
int MMM2D_set_params (double maxPWerror, double far_cut, double delta_top, double delta_bot, int const_pot_on, double pot_diff)
set parameters for MMM2D.
This assumes that the particles do NOT leave the box. For the near formula (nsquared cell structure), precision might be lost, while the far formula might have problems with overflows.
Parameters
maxPWerror the maximal error for the pairwise interactions. Both for potential and force components. The potential is therefore always slightly more precise
far_cut sets the cutoff for the far formula in inverse lengths. If -1, the far cutoff is determined by maxPWerror. Manual setting is probably only good for testing
delta_top dielectric contrast at top of the simulation box
delta_mid dielectric contrast in the middle of the simulation box
Definition at line 1830 of file mmm2d.cpp.
References cell_structure, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, MMM2D_struct::const_pot_on, coulomb, COULOMB_MMM2D, MMM2D_struct::delta_mid_bot, MMM2D_struct::delta_mid_top, MMM2D_struct::delta_mult, MMM2D_struct::dielectric_contrast_on, err, ERROR_ICL, ES_ERROR, ES_OK, MMM2D_struct::far_calculated, MMM2D_struct::far_cut, MMM2D_struct::far_cut2, MMM2D_struct::maxPWerror, maxPWerror, Coulomb_parameters::method, MMM2D_setup_constants(), MMM2D_tune_far(), MMM2D_tune_near(), mpi_bcast_coulomb_params(), n_nodes, MMM2D_struct::pot_diff, SQR(), and CellStructure::type.
Referenced by tclcommand_inter_coulomb_parse_mmm2d().
Variable Documentation
char const* mmm2d_errors[]
error messages, see above
Definition at line 41 of file mmm2d.cpp.
Referenced by MMM2D_init(), and tclcommand_inter_coulomb_parse_mmm2d().
MMM2D_struct mmm2d_params
Definition at line 129 of file mmm2d.cpp.
Referenced by mpi_bcast_coulomb_params_slave(), tclcommand_print_efield_capacitors(), and tclprint_to_result_MMM2D().