ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: mmm2d_tcl.hpp File Reference
mmm2d_tcl.hpp File Reference
#include "parser.hpp"
Functions
int tclprint_to_result_MMM2D (Tcl_Interp *interp)
print the mmm2d parameters to the interpreters result
int tclcommand_inter_coulomb_parse_mmm2d (Tcl_Interp *interp, int argc, char **argv)
parse the mmm2d parameters
Function Documentation
int tclcommand_inter_coulomb_parse_mmm2d (Tcl_Interp * interp, int argc, char ** argv)
parse the mmm2d parameters
Definition at line 65 of file mmm2d_tcl.cpp.
References ARG0_IS_D, ARG0_IS_S, ARG_IS_D, cell_structure, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, err, maxPWerror, mmm2d_errors, MMM2D_set_params(), top, and CellStructure::type.
Referenced by tclcommand_inter_parse_coulomb().
int tclprint_to_result_MMM2D (Tcl_Interp * interp)
print the mmm2d parameters to the interpreters result
Definition at line 42 of file mmm2d_tcl.cpp.
References MMM2D_struct::const_pot_on, MMM2D_struct::delta_mid_bot, MMM2D_struct::delta_mid_top, MMM2D_struct::dielectric_contrast_on, MMM2D_struct::far_cut, MMM2D_struct::maxPWerror, mmm2d_params, and MMM2D_struct::pot_diff.
Referenced by tclprint_to_result_CoulombIA().