ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: modes.cpp File Reference
modes.cpp File Reference
Implementation of modes.h.
#include "modes.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
Macros
#define MODES2D_NUM_TOL 0.00001
Numerical tolerance to be used only in modes2d.
Typedefs
typedef double fftw_real
fftw plan for calculating the 2d mode analysis
Functions
void fold_all (void)
double calc_zref (int tmpzdir)
void map_to_2dgrid ()
This function takes a given grid supplied by the user and determines the correct orientation in which to do the fourier transform.
int orient_order (double *result, double *stored_dirs)
This routine calculates the orientational order parameter for a lipid bilayer.
int lipid_orientation (int id, Particle *partCfg, double zref, double director[3], double refdir[3])
This routine performs a simple check to see whether a lipid is oriented up or down or if it has escaped the bilayer.
int get_lipid_orients (IntList *l_orient)
int modes2d (fftw_complex *modes, int switch_fluc)
This routine performs must of the work involved in the analyze modes2d command.
int bilayer_density_profile_sphere (IntList *beadids, double rrange, DoubleList *density_profile, double radius, double center[3])
This routine calculates density profiles for given bead types as a function of height relative to the bilayer midplane where the bilayer is assumed to wrap around a sphere of radius r and center cx,cy,cz.
int bilayer_density_profile (IntList *beadids, double hrange, DoubleList *density_profile, int usegrid)
This routine calculates density profiles for given bead types as a function of height relative to the bilayer midplane.
int calc_fluctuations (double *height_grid, int switch_fluc)
This routine calculates an average height for the bilayer in each grid square as follows;.
Variables
int mode_grid_changed = 1
Flag to indicate when the grid size has changed.
int mode_grid_3d [3] = {0,0,0}
An array containing the size of the mode grid along each coordinate axis.
int xdir = -1
Integer label x for grid axes compared to real axes.
int ydir = -1
Integer label y for grid axes compared to real axes.
int zdir = -1
Integer label z for grid axes compared to real axes.
double stray_cut_off = 10000000.0
Default value for the distance beyond which a particle is said to have escaped the bilayer.
Detailed Description
Implementation of modes.h.
Definition in file modes.cpp.
Macro Definition Documentation
#define MODES2D_NUM_TOL 0.00001
Numerical tolerance to be used only in modes2d.
Definition at line 56 of file modes.cpp.
Referenced by map_to_2dgrid().
Typedef Documentation
typedef double fftw_real
fftw plan for calculating the 2d mode analysis
Definition at line 38 of file modes.cpp.
Function Documentation
int bilayer_density_profile (IntList * beadids, double hrange, DoubleList * density_profile, int usegrid)
This routine calculates density profiles for given bead types as a function of height relative to the bilayer midplane.
First the height function is calculated
The height value of each bead is then calculated relative to the overall height function and the population of the relevant bin is increased.
Definition at line 597 of file modes.cpp.
References box_l, calc_fluctuations(), calc_zref(), IntList::e, DoubleList::e, free, i, lipid_orientation(), malloc, IntList::max, DoubleList::max, mode_grid_3d, n_part, ParticlePosition::p, Particle::p, partCfg, Particle::r, runtimeError, ParticleProperties::type, xdir, ydir, and zdir.
Referenced by tclcommand_analyze_parse_bilayer_density_profile().
int bilayer_density_profile_sphere (IntList * beadids, double rrange, DoubleList * density_profile, double radius, double center[3])
This routine calculates density profiles for given bead types as a function of height relative to the bilayer midplane where the bilayer is assumed to wrap around a sphere of radius r and center cx,cy,cz.
The radius value of each bead is then calculated relative to the colloid radius and the population of the relevant bin is increased.
Definition at line 498 of file modes.cpp.
References IntList::e, DoubleList::e, fold_all(), get_mi_vector(), i, lipid_orientation(), IntList::max, DoubleList::max, n_part, Particle::p, partCfg, runtimeError, sortPartCfg(), sqrlen(), ParticleProperties::type, updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze_parse_bilayer_density_profile().
int calc_fluctuations (double * height_grid, int switch_fluc)
This routine calculates an average height for the bilayer in each grid square as follows;.
Calculates the average bead position in the height dimension modes::zdir
Calculates the average height of each bilayer leaflet above or below modes::zdir separately. These averages are then averaged together to create a height function over the 2d grid. In calculating this height function, checks are made for grid cells that contain no lipids. In such cases a value equal to the mean of surrounding cells is substituted.
Also can calculate the thickness of a flat bilayer.
Definition at line 713 of file modes.cpp.
References box_l, calc_zref(), free, i, lipid_orientation(), malloc, mode_grid_3d, n_part, norm(), ParticlePosition::p, Particle::p, partCfg, Particle::r, runtimeError, sortPartCfg(), STAT_TRACE, this_node, updatePartCfg(), WITHOUT_BONDS, xdir, ydir, and zdir.
Referenced by bilayer_density_profile(), get_lipid_orients(), and modes2d().
double calc_zref (int tmpzdir)
Definition at line 76 of file modes.cpp.
References fold_all(), i, n_part, ParticlePosition::p, partCfg, Particle::r, and zdir.
Referenced by bilayer_density_profile(), calc_fluctuations(), get_lipid_orients(), and orient_order().
void fold_all (void)
Definition at line 64 of file modes.cpp.
References fold_coordinate(), i, ParticleLocal::i, Particle::l, n_part, Particle::p, partCfg, xdir, ydir, and zdir.
Referenced by bilayer_density_profile_sphere(), and calc_zref().
int get_lipid_orients (IntList * l_orient)
Definition at line 346 of file modes.cpp.
References box_l, calc_fluctuations(), calc_zref(), IntList::e, ES_ERROR, free, i, lipid_orientation(), malloc, mode_grid_3d, n_molecules, Particle::p, Molecule::part, partCfg, runtimeError, sortPartCfg(), topology, updatePartCfg(), WITHOUT_BONDS, xdir, ydir, and zdir.
Referenced by tclcommand_analyze_parse_get_lipid_orients().
int lipid_orientation (int id, Particle * partCfg, double zref, double director[3], double refdir[3])
This routine performs a simple check to see whether a lipid is oriented up or down or if it has escaped the bilayer.
Parameters
id The particle identifier
partCfg An array of sorted particles
zref The average z position of all particles. This is used to check for stray lipids
director director
refdir is a vector indicating the direction indicating up. This is usually the zaxis. If it is not the z axis then lipids will not be returned as stray.
Definition at line 280 of file modes.cpp.
References distance(), IntList::e, ES_ERROR, i, ParticleProperties::mol_id, IntList::n, n_molecules, ParticlePosition::p, Particle::p, Molecule::part, Particle::r, stray_cut_off, topology, xdir, ydir, and zdir.
Referenced by bilayer_density_profile(), bilayer_density_profile_sphere(), calc_fluctuations(), get_lipid_orients(), and orient_order().
void map_to_2dgrid ()
This function takes a given grid supplied by the user and determines the correct orientation in which to do the fourier transform.
In this regard one of the grid dimensions must be 0 and the other two must be integer multiples of two and equal to each other. The dimension that is 0 will be assigned an internal reference called zdir and will be used to calculate the height function used in the fft
Definition at line 101 of file modes.cpp.
References i, mode_grid_3d, MODES2D_NUM_TOL, runtimeError, STAT_TRACE, this_node, xdir, ydir, and zdir.
Referenced by tclcommand_analyze_parse_bilayer_set().
int modes2d (fftw_complex * modes, int switch_fluc)
This routine performs must of the work involved in the analyze modes2d command.
A breakdown of what the routine does is as follows
fftw plans and in / out arrays are initialized as required
calculate height function is called
The height function is fourier transformed using the fftw library.
Note: argument switch_fluc switch_fluc == 1 for height grid switch_fluc == 0 for thickness
Input values for the fft
Output values for the fft
Every time a change is made to the grid calculate the fftw plan for the subsequent fft and destroy any existing plans
Definition at line 418 of file modes.cpp.
References calc_fluctuations(), malloc, mode_grid_3d, mode_grid_changed, runtimeError, sortPartCfg(), STAT_TRACE, this_node, updatePartCfg(), WITHOUT_BONDS, xdir, ydir, and zdir.
Referenced by tclcommand_analyze_parse_modes2d().
int orient_order (double * result, double * stored_dirs)
This routine calculates the orientational order parameter for a lipid bilayer.
Definition at line 167 of file modes.cpp.
References calc_zref(), IntList::e, ES_ERROR, ES_OK, i, init_intlist(), lipid_orientation(), n_molecules, Molecule::part, partCfg, realloc_intlist(), runtimeError, scalar(), sortPartCfg(), topology, updatePartCfg(), WITHOUT_BONDS, xdir, ydir, and zdir.
Referenced by tclcommand_analyze_parse_lipid_orient_order().
Variable Documentation
int mode_grid_3d[3] = {0,0,0}
An array containing the size of the mode grid along each coordinate axis.
Note that at present this should be a symmetric square
Definition at line 47 of file modes.cpp.
Referenced by bilayer_density_profile(), calc_fluctuations(), get_lipid_orients(), map_to_2dgrid(), modes2d(), tclcommand_analyze_parse_bilayer_set(), and tclcommand_analyze_parse_modes2d().
int mode_grid_changed = 1
Flag to indicate when the grid size has changed.
Definition at line 42 of file modes.cpp.
Referenced by modes2d(), and tclcommand_analyze_parse_bilayer_set().
double stray_cut_off = 10000000.0
Default value for the distance beyond which a particle is said to have escaped the bilayer.
The default is set very large so that all lipids are counted
Definition at line 61 of file modes.cpp.
Referenced by lipid_orientation(), and tclcommand_analyze_parse_bilayer_set().
int xdir = -1
Integer label x for grid axes compared to real axes.
Definition at line 49 of file modes.cpp.
Referenced by bilayer_density_profile(), calc_fluctuations(), fold_all(), get_lipid_orients(), lipid_orientation(), map_to_2dgrid(), modes2d(), orient_order(), tclcommand_analyze_parse_bilayer_density_profile(), tclcommand_analyze_parse_get_lipid_orients(), tclcommand_analyze_parse_modes2d(), and tclcommand_integrate_set_npt_isotropic().
int ydir = -1
Integer label y for grid axes compared to real axes.
Definition at line 51 of file modes.cpp.
Referenced by bilayer_density_profile(), calc_fluctuations(), fold_all(), get_lipid_orients(), lipid_orientation(), map_to_2dgrid(), modes2d(), orient_order(), tclcommand_analyze_parse_bilayer_density_profile(), tclcommand_analyze_parse_get_lipid_orients(), tclcommand_analyze_parse_modes2d(), and tclcommand_integrate_set_npt_isotropic().
int zdir = -1
Integer label z for grid axes compared to real axes.
Definition at line 53 of file modes.cpp.
Referenced by bilayer_density_profile(), calc_fluctuations(), calc_zref(), fold_all(), get_lipid_orients(), lipid_orientation(), map_to_2dgrid(), modes2d(), orient_order(), tclcommand_analyze_parse_bilayer_density_profile(), tclcommand_analyze_parse_get_lipid_orients(), tclcommand_analyze_parse_modes2d(), and tclcommand_integrate_set_npt_isotropic().