ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: molforces.cpp File Reference
molforces.cpp File Reference
Routines for calculating and applying trap forces upon molecules.
#include <mpi.h>
#include "utils.hpp"
#include "grid.hpp"
#include "molforces.hpp"
#include "topology.hpp"
#include "particle_data.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "forces.hpp"
Functions
void apply_mol_constraints ()
void calc_trap_force ()
void get_local_trapped_mols (IntList *local_trapped_mols)
void calc_local_mol_info (IntList *local_trapped_mols)
void mpi_comm_mol_info (IntList *local_trapped_mols)
void mpi_comm_mol_info_slave (IntList *local_trapped_mols)
void calc_mol_info ()
Calculate the center of mass, total mass, velocity, total force, and trap force on all trapped molecules.
void calc_and_apply_mol_constraints ()
Checks if there are any molecules trapped (IsTrapped=1) and if so calls calc_mol_info and apply_mol_constaints.
Variables
int IsTrapped = 0
Detailed Description
Routines for calculating and applying trap forces upon molecules.
This trap force can be set to
a harmonic potential with a restlength of zero on the molecular centre of mass
a drag on the molecular velocity
a cancelation of the total force on the molecule (including thermostat forces) The centre of mass can be fixed to an absolute position or to a relative position in the simulation box. The molecular trap forces is distributed evenly upon all particles in a molecule. (see topology.cpp and molforces.cpp)
Definition in file molforces.cpp.
Function Documentation
void apply_mol_constraints ()
Definition at line 51 of file molforces.cpp.
References CellPList::cell, ParticleForce::f, Particle::f, i, local_cells, ParticleProperties::mol_id, CellPList::n, ParticleList::n, Particle::p, ParticleList::part, topology, and Molecule::trap_force.
Referenced by calc_and_apply_mol_constraints().
void calc_and_apply_mol_constraints ()
Checks if there are any molecules trapped (IsTrapped=1) and if so calls calc_mol_info and apply_mol_constaints.
Definition at line 410 of file molforces.cpp.
References apply_mol_constraints(), calc_mol_info(), and IsTrapped.
Referenced by force_calc(), and integrate_sd().
void calc_local_mol_info (IntList * local_trapped_mols)
Definition at line 164 of file molforces.cpp.
References CellPList::cell, Molecule::com, COORD_FIXED, IntList::e, Molecule::f, ParticleForce::f, Particle::f, fold_position(), i, ParticleLocal::i, Particle::l, local_cells, Particle::m, Molecule::mass, ParticleProperties::mol_id, IntList::n, CellPList::n, ParticleList::n, n_molecules, ParticlePosition::p, Particle::p, ParticleList::part, PMASS, Particle::r, runtimeError, topology, unfold_position(), Molecule::v, and ParticleMomentum::v.
Referenced by calc_mol_info().
void calc_mol_info ()
Calculate the center of mass, total mass, velocity, total force, and trap force on all trapped molecules.
Definition at line 377 of file molforces.cpp.
References calc_local_mol_info(), get_local_trapped_mols(), init_intlist(), mpi_comm_mol_info(), mpi_comm_mol_info_slave(), realloc_intlist(), runtimeError, this_node, and topo_part_info_synced.
Referenced by calc_and_apply_mol_constraints().
void calc_trap_force ()
Definition at line 73 of file molforces.cpp.
References box_l, Molecule::com, COORD_FIXED, Molecule::drag_constant, Molecule::f, Molecule::fav, Molecule::favcounter, Molecule::isrelative, IntList::n, n_molecules, Molecule::noforce_flag, Molecule::part, runtimeError, topo_part_info_synced, topology, Molecule::trap_center, Molecule::trap_flag, Molecule::trap_force, Molecule::trap_spring_constant, and Molecule::v.
Referenced by mpi_comm_mol_info().
void get_local_trapped_mols (IntList * local_trapped_mols)
Definition at line 128 of file molforces.cpp.
References CellPList::cell, COORD_FIXED, IntList::e, i, intlist_contains(), local_cells, IntList::max, ParticleProperties::mol_id, IntList::n, CellPList::n, ParticleList::n, n_molecules, Particle::p, ParticleList::part, realloc_intlist(), runtimeError, and topology.
Referenced by calc_mol_info().
void mpi_comm_mol_info (IntList * local_trapped_mols)
Definition at line 235 of file molforces.cpp.
References calc_trap_force(), Molecule::com, comm_cart, Molecule::f, free, i, intlist_contains(), malloc, Molecule::mass, MPI_DOUBLE, MPI_INT, MPI_Recv(), MPI_Send(), n_molecules, n_nodes, topology, and Molecule::v.
Referenced by calc_mol_info().
void mpi_comm_mol_info_slave (IntList * local_trapped_mols)
Definition at line 343 of file molforces.cpp.
References comm_cart, IntList::e, i, MPI_DOUBLE, MPI_INT, MPI_Recv(), MPI_Send(), IntList::n, and topology.
Referenced by calc_mol_info().
Variable Documentation
int IsTrapped = 0
Definition at line 49 of file molforces.cpp.
Referenced by calc_and_apply_mol_constraints(), mpi_sync_topo_part_info(), mpi_sync_topo_part_info_slave(), and set_molecule_trap().