ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: mpi.cpp File Reference
mpi.cpp File Reference
For more information about MPIFake, see mpi.h.
#include "mpi.h"
Functions
static void mpifake_dtblock (MPI_Datatype newtype, MPI_Datatype oldtype, int count, int disp)
static void mpifake_pack (void *dest, void *src, int num, MPI_Datatype dtype)
static int mpifake_unpack (void *dest, void *src, int num, MPI_Datatype dtype)
int MPI_Type_struct (int count, int *lengths, MPI_Aint *disps, MPI_Datatype *oldtypes, MPI_Datatype *newtype)
int MPI_Type_contiguous (int count, MPI_Datatype oldtype, MPI_Datatype *newtype)
int MPI_Type_vector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype *newtype)
int MPI_Type_hvector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype *newtype)
int MPI_Type_create_hvector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype *newtype)
static void mpifake_pack_hvector (void *_dest, void *_src, int num, MPI_Datatype dtype, int vflag)
static void mpifake_pack_struct (void *_dest, void *_src, int num, MPI_Datatype dtype)
static int mpifake_unpack_hvector (void *_dest, void *_src, int num, MPI_Datatype dtype, int vflag)
static int mpifake_unpack_struct (void *_dest, void *_src, int num, MPI_Datatype dtype)
static void mpifake_cpy_hvector (void *_dest, void *_src, int num, MPI_Datatype dtype, int vflag)
static void mpifake_cpy_struct (void *_dest, void *_src, int count, MPI_Datatype dtype)
void mpifake_copy (void *src, void *dest, int *count, MPI_Datatype *dtype)
int mpifake_sendrecv (void *_s, int scount, MPI_Datatype sdtype, void *_r, int rcount, MPI_Datatype rdtype)
Variables
struct mpifake_dtype mpifake_dtype_lb = { 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL }
struct mpifake_dtype mpifake_dtype_ub = { 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL }
struct mpifake_dtype mpifake_dtype_byte = { 0, 0, sizeof(char), sizeof(char), 1, 1, sizeof(char), NULL, NULL, NULL, NULL }
struct mpifake_dtype mpifake_dtype_char = { 0, 0, sizeof(char), sizeof(char), 1, 1, sizeof(char), NULL, NULL, NULL, NULL }
struct mpifake_dtype mpifake_dtype_int = { 0, 0, sizeof(int), sizeof(int), 1, 1, sizeof(int), NULL, NULL, NULL, NULL }
struct mpifake_dtype mpifake_dtype_long = { 0, 0, sizeof(long), sizeof(long), 1, 1, sizeof(long), NULL, NULL, NULL, NULL }
struct mpifake_dtype mpifake_dtype_double = { 0, 0, sizeof(double), sizeof(double), 1, 1, sizeof(double), NULL, NULL, NULL, NULL }
Detailed Description
For more information about MPIFake, see mpi.h.
Definition in file mpi.cpp.
Function Documentation
int MPI_Type_contiguous (int count, MPI_Datatype oldtype, MPI_Datatype * newtype)
Definition at line 80 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, mpifake_dtype::format, LAM_DTCONTIG, mpifake_dtype::lower, malloc, MPI_SUCCESS, mpifake_dtblock(), mpifake_dtype::size, and mpifake_dtype::upper.
Referenced by maggs_exchange_surface_patch(), and maggs_prepare_surface_planes().
int MPI_Type_create_hvector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype * newtype)
Definition at line 141 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, mpifake_dtype::format, LAM_DTHVECTOR, mpifake_dtype::length, mpifake_dtype::lower, malloc, MPI_SUCCESS, mpifake_dtblock(), mpifake_dtype::size, mpifake_dtype::stride, and mpifake_dtype::upper.
Referenced by lb_prepare_communication(), maggs_exchange_surface_patch(), and MPI_Type_hvector().
int MPI_Type_hvector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype * newtype)
Definition at line 136 of file mpi.cpp.
References MPI_Type_create_hvector().
int MPI_Type_struct (int count, int * lengths, MPI_Aint * disps, MPI_Datatype * oldtypes, MPI_Datatype * newtype)
Definition at line 40 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::disps, mpifake_dtype::dtypes, mpifake_dtype::format, i, LAM_DTSTRUCT, mpifake_dtype::lengths, mpifake_dtype::lower, malloc, MPI_SUCCESS, mpifake_dtblock(), mpifake_dtype::size, and mpifake_dtype::upper.
int MPI_Type_vector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype * newtype)
Definition at line 101 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, mpifake_dtype::format, LAM_DTVECTOR, mpifake_dtype::length, mpifake_dtype::lower, malloc, MPI_SUCCESS, mpifake_dtblock(), mpifake_dtype::size, mpifake_dtype::stride, and mpifake_dtype::upper.
Referenced by maggs_exchange_surface_patch(), maggs_prepare_surface_planes(), and prepare_halo_communication().
void mpifake_copy (void * src, void * dest, int * count, MPI_Datatype * dtype)
Definition at line 435 of file mpi.cpp.
References LAM_DTCONTIG, LAM_DTHVECTOR, LAM_DTSTRUCT, LAM_DTVECTOR, mpifake_copy(), mpifake_cpy_hvector(), and mpifake_cpy_struct().
Referenced by mpifake_copy(), mpifake_cpy_hvector(), mpifake_cpy_struct(), and mpifake_sendrecv().
static void mpifake_cpy_hvector (void * _dest, void * _src, int num, MPI_Datatype dtype, int vflag) static
Definition at line 391 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, i, mpifake_dtype::length, mpifake_dtype::lower, mpifake_copy(), mpifake_dtype::stride, and mpifake_dtype::upper.
Referenced by mpifake_copy().
static void mpifake_cpy_struct (void * _dest, void * _src, int count, MPI_Datatype dtype) static
Definition at line 414 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::disps, mpifake_dtype::dtypes, i, mpifake_dtype::lengths, mpifake_dtype::lower, mpifake_copy(), and mpifake_dtype::upper.
Referenced by mpifake_copy().
static void mpifake_dtblock (MPI_Datatype newtype, MPI_Datatype oldtype, int count, int disp) static
Definition at line 176 of file mpi.cpp.
References mpifake_dtype::lower, mpifake_dtype::size, and mpifake_dtype::upper.
Referenced by MPI_Type_contiguous(), MPI_Type_create_hvector(), MPI_Type_struct(), and MPI_Type_vector().
static void mpifake_pack (void * dest, void * src, int num, MPI_Datatype dtype) static
Definition at line 262 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, mpifake_dtype::format, LAM_DTCONTIG, LAM_DTHVECTOR, LAM_DTSTRUCT, LAM_DTVECTOR, mpifake_pack_hvector(), mpifake_pack_struct(), and mpifake_dtype::size.
Referenced by mpifake_pack_hvector(), mpifake_pack_struct(), and mpifake_sendrecv().
static void mpifake_pack_hvector (void * _dest, void * _src, int num, MPI_Datatype dtype, int vflag) static
Definition at line 205 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, i, mpifake_dtype::length, mpifake_dtype::lower, mpifake_pack(), mpifake_dtype::size, mpifake_dtype::stride, and mpifake_dtype::upper.
Referenced by mpifake_pack().
static void mpifake_pack_struct (void * _dest, void * _src, int num, MPI_Datatype dtype) static
Definition at line 233 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::disps, mpifake_dtype::dtypes, i, mpifake_dtype::lengths, mpifake_dtype::lower, mpifake_pack(), mpifake_dtype::size, and mpifake_dtype::upper.
Referenced by mpifake_pack().
int mpifake_sendrecv (void * _s, int scount, MPI_Datatype sdtype, void * _r, int rcount, MPI_Datatype rdtype)
Definition at line 465 of file mpi.cpp.
References errexit(), free, malloc, MPI_SUCCESS, mpifake_copy(), mpifake_pack(), mpifake_unpack(), and mpifake_dtype::size.
Referenced by MPI_Allgather(), MPI_Gather(), and MPI_Scatter().
static int mpifake_unpack (void * dest, void * src, int num, MPI_Datatype dtype) static
Definition at line 363 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, mpifake_dtype::format, LAM_DTCONTIG, LAM_DTHVECTOR, LAM_DTSTRUCT, LAM_DTVECTOR, mpifake_unpack_hvector(), mpifake_unpack_struct(), and mpifake_dtype::size.
Referenced by mpifake_sendrecv(), mpifake_unpack_hvector(), and mpifake_unpack_struct().
static int mpifake_unpack_hvector (void * _dest, void * _src, int num, MPI_Datatype dtype, int vflag) static
Definition at line 289 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, errexit(), i, mpifake_dtype::length, mpifake_dtype::lower, mpifake_unpack(), mpifake_dtype::size, start, mpifake_dtype::stride, and mpifake_dtype::upper.
Referenced by mpifake_unpack().
static int mpifake_unpack_struct (void * _dest, void * _src, int num, MPI_Datatype dtype) static
Definition at line 326 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::disps, mpifake_dtype::dtypes, errexit(), i, mpifake_dtype::lengths, mpifake_dtype::lower, mpifake_unpack(), mpifake_dtype::size, start, and mpifake_dtype::upper.
Referenced by mpifake_unpack().
Variable Documentation
struct mpifake_dtype mpifake_dtype_byte = { 0, 0, sizeof(char), sizeof(char), 1, 1, sizeof(char), NULL, NULL, NULL, NULL }
Definition at line 30 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_char = { 0, 0, sizeof(char), sizeof(char), 1, 1, sizeof(char), NULL, NULL, NULL, NULL }
Definition at line 31 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_double = { 0, 0, sizeof(double), sizeof(double), 1, 1, sizeof(double), NULL, NULL, NULL, NULL }
Definition at line 34 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_int = { 0, 0, sizeof(int), sizeof(int), 1, 1, sizeof(int), NULL, NULL, NULL, NULL }
Definition at line 32 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_lb = { 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL }
Definition at line 28 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_long = { 0, 0, sizeof(long), sizeof(long), 1, 1, sizeof(long), NULL, NULL, NULL, NULL }
Definition at line 33 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_ub = { 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL }
Definition at line 29 of file mpi.cpp.