ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: mpi.h File Reference
mpi.h File Reference
This is the MPIfake implementation.
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
Data Structures
struct mpifake_dtype
Macros
#define LAM_DTBASIC 0 /* basic datatype */
#define LAM_DTCONTIG 1 /* contiguous */
#define LAM_DTVECTOR 2 /* vector */
#define LAM_DTHVECTOR 3 /* hvector */
#define LAM_DTINDEXED 4 /* indexed */
#define LAM_DTHINDEXED 5 /* hindexed */
#define LAM_DTSTRUCT 6 /* struct */
#define LAM_DTHVECTORCREAT 7 /* extended vector */
#define LAM_DTHINDEXEDCREAT 8 /* extended indexed */
#define LAM_DTSTRUCTCREAT 9 /* extended struct */
#define LAM_DTINDEXEDBLK 10 /* indexed block */
#define LAM_DTSUBARRAY 11 /* local array */
#define LAM_DTDARRAY 12 /* distributed array */
#define MPI_LOR mpifake_copy
#define MPI_SUM mpifake_copy
#define MPI_MAX mpifake_copy
#define MPI_COPY mpifake_copy
#define MPI_STATUS_IGNORE NULL
#define MPI_SUCCESS 1
#define MPI_COMM_WORLD NULL
#define MPI_REQUEST_NULL NULL
#define MPI_ANY_SOURCE 0
#define MPI_ANY_TAG 0
#define MPI_IN_PLACE (void*)0x1
#define MPI_INT (&mpifake_dtype_int)
#define MPI_DOUBLE (&mpifake_dtype_double)
#define MPI_BYTE (&mpifake_dtype_byte)
#define MPI_LONG (&mpifake_dtype_long)
#define MPI_CHAR (&mpifake_dtype_char)
#define MPI_LB (&mpifake_dtype_lb)
#define MPI_UB (&mpifake_dtype_ub)
#define MPI_DATATYPE_NULL NULL
#define MPI_MAX_PROCESSOR_NAME 6
Typedefs
typedef struct mpifake_dtype * MPI_Datatype
typedef void * MPI_Status
typedef void * MPI_Comm
typedef void * MPI_Errhandler
typedef void * MPI_Request
typedef long MPI_Aint
typedef void(MPI_User_function) (void *, void *, int *, MPI_Datatype *)
typedef void(MPI_Handler_function) (MPI_Comm *, int *,...)
typedef MPI_User_function * MPI_Op
Functions
void errexit ()
exit ungracefully, core dump if switched on.
void mpifake_copy (void *from, void *to, int *count, MPI_Datatype *dtype)
int mpifake_sendrecv (void *s, int scount, MPI_Datatype sdtype, void *r, int rcount, MPI_Datatype rdtype)
int MPI_Type_struct (int count, int *lengths, MPI_Aint *disps, MPI_Datatype *oldtypes, MPI_Datatype *newtype)
int MPI_Type_contiguous (int count, MPI_Datatype oldtype, MPI_Datatype *newtype)
int MPI_Type_vector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype *newtype)
int MPI_Type_hvector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype *newtype)
int MPI_Type_create_hvector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype *newtype)
int MPI_Init (int *a, char ***b)
int MPI_Finalize (void)
int MPI_Abort (MPI_Comm comm, int status)
int MPI_Comm_size (MPI_Comm comm, int *psize)
int MPI_Comm_rank (MPI_Comm comm, int *rank)
int MPI_Cart_rank (MPI_Comm comm, int *coords, int *rank)
int MPI_Cart_coords (MPI_Comm comm, int rank, int maxdims, int *coords)
int MPI_Cart_shift (MPI_Comm comm, int direction, int disp, int *rank_source, int *rank_dest)
int MPI_Cart_create (MPI_Comm comm_old, int ndims, int *dims, int *periods, int reorder, MPI_Comm *comm_cart)
int MPI_Dims_create (int nnodes, int ndims, int *dims)
int MPI_Comm_split (MPI_Comm comm, int colour, int key, MPI_Comm *newcomm)
int MPI_Comm_free (MPI_Comm *comm)
int MPI_Type_commit (MPI_Datatype *dtype)
int MPI_Type_free (MPI_Datatype *dtype)
int MPI_Type_extent (MPI_Datatype dtype, MPI_Aint *pextent)
int MPI_Type_get_extent (MPI_Datatype dtype, MPI_Aint *lower, MPI_Aint *pextent)
int MPI_Barrier (MPI_Comm comm)
int MPI_Waitall (int count, MPI_Request *reqs, MPI_Status *stats)
int MPI_Wait (MPI_Request *reqs, MPI_Status *stats)
int MPI_Comm_create_errhandler (MPI_Handler_function *errfunc, MPI_Errhandler *errhdl)
int MPI_Comm_set_errhandler (MPI_Comm comm, MPI_Errhandler errhdl)
int MPI_Bcast (void *buff, int count, MPI_Datatype datatype, int root, MPI_Comm comm)
int MPI_Probe (int source, int tag, MPI_Comm comm, MPI_Status *status)
int MPI_Get_count (const MPI_Status *status, MPI_Datatype datatype, int *count)
int MPI_Recv (void *buf, int count, MPI_Datatype dtype, int src, int tag, MPI_Comm comm, MPI_Status *stat)
int MPI_Irecv (void *buf, int count, MPI_Datatype dtype, int src, int tag, MPI_Comm comm, MPI_Request *req)
int MPI_Send (void *buf, int count, MPI_Datatype dtype, int dst, int tag, MPI_Comm comm)
int MPI_Sendrecv (void *sbuf, int scount, MPI_Datatype stype, int dst, int stag, void *rbuf, int rcount, MPI_Datatype rtype, int src, int rtag, MPI_Comm comm, MPI_Status *stat)
int MPI_Isend (void *buf, int count, MPI_Datatype dtype, int dst, int tag, MPI_Comm comm, MPI_Request *req)
int MPI_Gather (void *sbuf, int scount, MPI_Datatype sdtype, void *rbuf, int rcount, MPI_Datatype rdtype, int root, MPI_Comm comm)
int MPI_Allgather (void *sbuf, int scount, MPI_Datatype sdtype, void *rbuf, int rcount, MPI_Datatype rdtype, MPI_Comm comm)
int MPI_Scatter (void *sbuf, int scount, MPI_Datatype sdtype, void *rbuf, int rcount, MPI_Datatype rdtype, int root, MPI_Comm comm)
int MPI_Op_create (MPI_User_function func, int commute, MPI_Op *pop)
int MPI_Reduce (void *sbuf, void *rbuf, int count, MPI_Datatype dtype, MPI_Op op, int root, MPI_Comm comm)
int MPI_Allreduce (void *sbuf, void *rbuf, int count, MPI_Datatype dtype, MPI_Op op, MPI_Comm comm)
int MPI_Error_string (int errcode, char *string, int *len)
int MPI_Get_processor_name (char *proc_name, int *proc_name_len)
Variables
struct mpifake_dtype mpifake_dtype_int
struct mpifake_dtype mpifake_dtype_double
struct mpifake_dtype mpifake_dtype_byte
struct mpifake_dtype mpifake_dtype_long
struct mpifake_dtype mpifake_dtype_char
struct mpifake_dtype mpifake_dtype_ub
struct mpifake_dtype mpifake_dtype_lb
Detailed Description
This is the MPIfake implementation.
This is NOT a real MPI implementation, but rather implements a subset of the MPI commands such that Espresso is able to run with a single processor. For this to work, you do not have to have any MPI implementation like LAM or MPICH installed.
Definition in file mpi.h.
Macro Definition Documentation
#define LAM_DTBASIC 0 /* basic datatype */
Definition at line 48 of file mpi.h.
#define LAM_DTCONTIG 1 /* contiguous */
Definition at line 49 of file mpi.h.
Referenced by MPI_Type_contiguous(), mpifake_copy(), mpifake_pack(), and mpifake_unpack().
#define LAM_DTDARRAY 12 /* distributed array */
Definition at line 60 of file mpi.h.
#define LAM_DTHINDEXED 5 /* hindexed */
Definition at line 53 of file mpi.h.
#define LAM_DTHINDEXEDCREAT 8 /* extended indexed */
Definition at line 56 of file mpi.h.
#define LAM_DTHVECTOR 3 /* hvector */
Definition at line 51 of file mpi.h.
Referenced by MPI_Type_create_hvector(), mpifake_copy(), mpifake_pack(), and mpifake_unpack().
#define LAM_DTHVECTORCREAT 7 /* extended vector */
Definition at line 55 of file mpi.h.
#define LAM_DTINDEXED 4 /* indexed */
Definition at line 52 of file mpi.h.
#define LAM_DTINDEXEDBLK 10 /* indexed block */
Definition at line 58 of file mpi.h.
#define LAM_DTSTRUCT 6 /* struct */
Definition at line 54 of file mpi.h.
Referenced by MPI_Type_struct(), mpifake_copy(), mpifake_pack(), and mpifake_unpack().
#define LAM_DTSTRUCTCREAT 9 /* extended struct */
Definition at line 57 of file mpi.h.
#define LAM_DTSUBARRAY 11 /* local array */
Definition at line 59 of file mpi.h.
#define LAM_DTVECTOR 2 /* vector */
Definition at line 50 of file mpi.h.
Referenced by MPI_Type_vector(), mpifake_copy(), mpifake_pack(), and mpifake_unpack().
#define MPI_ANY_SOURCE 0
Definition at line 100 of file mpi.h.
Referenced by RuntimeErrorCollector::gather(), mpi_system_CMS(), and mpi_system_CMS_velocity().
#define MPI_ANY_TAG 0
Definition at line 101 of file mpi.h.
Referenced by RuntimeErrorCollector::gather().
#define MPI_BYTE (&mpifake_dtype_byte)
Definition at line 115 of file mpi.h.
Referenced by ghost_communicator(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_get_particles_slave(), IBM_cuda_mpi_send_velocities(), IBM_cuda_mpi_send_velocities_slave(), maggs_exchange_surface_patch(), maggs_prepare_surface_planes(), minimize_energy(), mpi_bcast_collision_params_slave(), mpi_bcast_constraint(), mpi_bcast_constraint_slave(), mpi_bcast_coulomb_params_slave(), mpi_bcast_cuda_global_part_vars_slave(), mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), mpi_bcast_lb_params_slave(), mpi_bcast_lbboundary(), mpi_bcast_lbboundary_slave(), mpi_bit_random_stat(), mpi_bit_random_stat_slave(), mpi_external_potential_broadcast(), mpi_external_potential_broadcast_slave(), mpi_get_particles(), mpi_get_particles_slave(), mpi_observable_lb_radial_velocity_profile_slave_implementation(), mpi_random_stat(), mpi_random_stat_slave(), mpi_recv_part(), mpi_recv_part_slave(), mpi_send_swimming(), mpi_send_swimming_slave(), observable_calc_lb_radial_velocity_profile(), on_coulomb_change(), on_integration_start(), recv_particles(), reduce_forces_sum(), and send_particles().
#define MPI_CHAR (&mpifake_dtype_char)
Definition at line 117 of file mpi.h.
Referenced by RuntimeErrorCollector::gather(), and RuntimeErrorCollector::gatherSlave().
#define MPI_COMM_WORLD NULL
Definition at line 96 of file mpi.h.
Referenced by calc_area_global(), calc_volume(), grid_changed_n_nodes(), initRuntimeErrorCollector(), mpi_init(), mpi_send_rotation(), mpi_send_rotation_slave(), observable_compute_stress_tensor(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
#define MPI_COPY mpifake_copy
Definition at line 91 of file mpi.h.
#define MPI_DATATYPE_NULL NULL
Definition at line 120 of file mpi.h.
#define MPI_DOUBLE (&mpifake_dtype_double)
Definition at line 114 of file mpi.h.
Referenced by add_z_force(), bcast_iccp3m_cfg(), calc_area_global(), calc_kinetic(), calc_mu_max(), calc_volume(), CalcVolumes(), common_bcast_parameter(), distribute(), energy_calc(), finalize_p_inst_npt(), gather_image_contributions(), get_DLC_dipolar(), get_DLC_energy_dipolar(), halo_push_communication(), iccp3m_iteration(), integrate_sd(), integrate_vv(), lb_calc_average_rho(), lb_calc_densprof(), lb_calc_fluid_mass(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_calc_velprof(), lb_check_halo_regions(), lb_collect_boundary_forces(), lb_prepare_communication(), local_setup_reaction(), maggs_calc_init_e_field(), maggs_check_curl_E(), maggs_compute_dipole_correction(), maggs_count_charged_particles(), maggs_electric_energy(), maggs_exchange_surface_patch(), maggs_prepare_surface_planes(), mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), mpi_cap_forces_slave(), mpi_comm_mol_info(), mpi_comm_mol_info_slave(), mpi_external_potential_broadcast(), mpi_external_potential_broadcast_slave(), mpi_external_potential_sum_energies(), mpi_external_potential_sum_energies_slave(), mpi_galilei_transform(), mpi_galilei_transform_slave(), mpi_get_configtemp(), mpi_get_configtemp_slave(), mpi_get_constraint_force(), mpi_get_constraint_force_slave(), mpi_local_stress_tensor(), mpi_local_stress_tensor_slave(), mpi_observable_lb_radial_velocity_profile_slave_implementation(), mpi_place_new_particle(), mpi_place_new_particle_slave(), mpi_place_particle(), mpi_place_particle_slave(), mpi_recv_fluid(), mpi_recv_fluid_populations(), mpi_recv_fluid_populations_slave(), mpi_recv_fluid_slave(), mpi_rescale_particles(), mpi_rescale_particles_slave(), mpi_send_dip(), mpi_send_dip_slave(), mpi_send_dipm(), mpi_send_dipm_slave(), mpi_send_ext_force(), mpi_send_ext_force_slave(), mpi_send_ext_torque(), mpi_send_ext_torque_slave(), mpi_send_f(), mpi_send_f_slave(), mpi_send_fluid(), mpi_send_fluid_populations(), mpi_send_fluid_populations_slave(), mpi_send_fluid_slave(), mpi_send_mass(), mpi_send_mass_slave(), mpi_send_mu_E(), mpi_send_mu_E_slave(), mpi_send_omega(), mpi_send_omega_slave(), mpi_send_q(), mpi_send_q_slave(), mpi_send_quat(), mpi_send_quat_slave(), mpi_send_rotational_inertia(), mpi_send_rotational_inertia_slave(), mpi_send_solvation(), mpi_send_solvation_slave(), mpi_send_torque(), mpi_send_torque_slave(), mpi_send_v(), mpi_send_v_slave(), mpi_send_vs_relative(), mpi_send_vs_relative_slave(), mpi_set_particle_gamma(), mpi_set_particle_gamma_slave(), mpi_set_particle_temperature(), mpi_set_particle_temperature_slave(), mpi_set_smaller_time_step(), mpi_set_smaller_time_step_slave(), mpi_set_time_step(), mpi_set_time_step_slave(), mpi_sync_topo_part_info(), mpi_sync_topo_part_info_slave(), mpi_system_CMS(), mpi_system_CMS_slave(), mpi_system_CMS_velocity(), mpi_system_CMS_velocity_slave(), observable_calc_lb_radial_velocity_profile(), observable_compute_stress_tensor(), predict_momentum_particles(), pressure_calc(), propagate_press_box_pos_and_rescale_npt(), slab_dip_count_mu(), steepest_descent_step(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), update_stress_tensor(), and z_energy().
#define MPI_IN_PLACE (void*)0x1
Definition at line 103 of file mpi.h.
Referenced by calc_kinetic(), calc_mu_max(), RuntimeErrorCollector::count(), get_DLC_dipolar(), and MPI_Allreduce().
#define MPI_INT (&mpifake_dtype_int)
Definition at line 113 of file mpi.h.
Referenced by announce_resort_particles(), bcast_iccp3m_cfg(), check_particles(), common_bcast_parameter(), correct_pos_shake(), correct_vel_shake(), RuntimeErrorCollector::count(), dd_exchange_and_sort_particles(), dd_topology_init(), ghost_communicator(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_send_velocities(), layered_exchange_and_sort_particles(), layered_topology_init(), lb_calc_densprof(), lb_calc_velprof(), local_setup_reaction(), mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), mpi_bcast_nptiso_geom_slave(), mpi_bit_random_seed(), mpi_bit_random_seed_slave(), mpi_comm_mol_info(), mpi_comm_mol_info_slave(), mpi_get_particles(), mpi_get_particles_slave(), mpi_local_stress_tensor(), mpi_local_stress_tensor_slave(), mpi_loop(), mpi_recv_fluid_boundary_flag(), mpi_recv_fluid_boundary_flag_slave(), mpi_recv_part(), mpi_recv_part_slave(), mpi_send_bond(), mpi_send_bond_slave(), mpi_send_configtemp_flag(), mpi_send_configtemp_flag_slave(), mpi_send_exclusion(), mpi_send_exclusion_slave(), mpi_send_ext_force(), mpi_send_ext_force_slave(), mpi_send_ext_torque(), mpi_send_ext_torque_slave(), mpi_send_mol_id(), mpi_send_mol_id_slave(), mpi_send_rotation(), mpi_send_rotation_slave(), mpi_send_smaller_timestep_flag(), mpi_send_smaller_timestep_flag_slave(), mpi_send_type(), mpi_send_type_slave(), mpi_send_virtual(), mpi_send_virtual_slave(), mpi_send_vs_relative(), mpi_send_vs_relative_slave(), mpi_sync_topo_part_info(), mpi_sync_topo_part_info_slave(), mpi_who_has(), mpi_who_has_slave(), nsq_balance_particles(), recv_particles(), and send_particles().
#define MPI_LB (&mpifake_dtype_lb)
Definition at line 118 of file mpi.h.
#define MPI_LONG (&mpifake_dtype_long)
Definition at line 116 of file mpi.h.
Referenced by mpi_random_seed(), and mpi_random_seed_slave().
#define MPI_LOR mpifake_copy
Definition at line 88 of file mpi.h.
#define MPI_MAX mpifake_copy
Definition at line 90 of file mpi.h.
Referenced by calc_mu_max(), iccp3m_iteration(), layered_exchange_and_sort_particles(), maggs_check_curl_E(), and steepest_descent_step().
#define MPI_MAX_PROCESSOR_NAME 6
Definition at line 211 of file mpi.h.
#define MPI_REQUEST_NULL NULL
Definition at line 98 of file mpi.h.
Referenced by maggs_exchange_surface_patch().
#define MPI_STATUS_IGNORE NULL
Definition at line 93 of file mpi.h.
Referenced by RuntimeErrorCollector::gather(), mpi_get_particles(), mpi_place_new_particle_slave(), mpi_place_particle_slave(), mpi_recv_fluid(), mpi_recv_fluid_boundary_flag(), mpi_recv_fluid_populations(), mpi_recv_part(), mpi_rescale_particles_slave(), mpi_send_bond(), mpi_send_bond_slave(), mpi_send_dip_slave(), mpi_send_dipm_slave(), mpi_send_ext_force_slave(), mpi_send_ext_torque_slave(), mpi_send_f_slave(), mpi_send_fluid_populations_slave(), mpi_send_fluid_slave(), mpi_send_mass_slave(), mpi_send_mol_id_slave(), mpi_send_mu_E_slave(), mpi_send_omega_slave(), mpi_send_q_slave(), mpi_send_quat_slave(), mpi_send_rotational_inertia_slave(), mpi_send_solvation_slave(), mpi_send_swimming_slave(), mpi_send_torque_slave(), mpi_send_type_slave(), mpi_send_v_slave(), mpi_send_virtual_slave(), mpi_send_vs_relative_slave(), mpi_system_CMS(), mpi_system_CMS_velocity(), mpi_who_has(), and recv_particles().
#define MPI_SUCCESS 1
Definition at line 94 of file mpi.h.
Referenced by MPI_Abort(), MPI_Allreduce(), MPI_Barrier(), MPI_Bcast(), MPI_Cart_coords(), MPI_Cart_create(), MPI_Cart_rank(), MPI_Cart_shift(), MPI_Comm_create_errhandler(), MPI_Comm_free(), MPI_Comm_rank(), MPI_Comm_set_errhandler(), MPI_Comm_size(), MPI_Comm_split(), MPI_Dims_create(), MPI_Error_string(), MPI_Finalize(), MPI_Get_count(), MPI_Get_processor_name(), MPI_Init(), MPI_Irecv(), MPI_Isend(), MPI_Op_create(), MPI_Probe(), MPI_Recv(), MPI_Reduce(), MPI_Send(), MPI_Sendrecv(), MPI_Type_commit(), MPI_Type_contiguous(), MPI_Type_create_hvector(), MPI_Type_extent(), MPI_Type_free(), MPI_Type_get_extent(), MPI_Type_struct(), MPI_Type_vector(), MPI_Wait(), MPI_Waitall(), and mpifake_sendrecv().
#define MPI_SUM mpifake_copy
Definition at line 89 of file mpi.h.
Referenced by add_z_force(), announce_resort_particles(), calc_area_global(), calc_kinetic(), calc_volume(), CalcVolumes(), correct_pos_shake(), correct_vel_shake(), RuntimeErrorCollector::count(), dd_exchange_and_sort_particles(), energy_calc(), finalize_p_inst_npt(), gather_image_contributions(), get_DLC_dipolar(), get_DLC_energy_dipolar(), lb_calc_average_rho(), lb_calc_fluid_mass(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_collect_boundary_forces(), maggs_calc_init_e_field(), maggs_compute_dipole_correction(), maggs_count_charged_particles(), maggs_electric_energy(), mpi_external_potential_sum_energies(), mpi_external_potential_sum_energies_slave(), mpi_get_configtemp(), mpi_get_configtemp_slave(), mpi_get_constraint_force(), mpi_get_constraint_force_slave(), mpi_local_stress_tensor(), mpi_local_stress_tensor_slave(), mpi_observable_lb_radial_velocity_profile_slave_implementation(), observable_calc_lb_radial_velocity_profile(), observable_compute_stress_tensor(), predict_momentum_particles(), pressure_calc(), slab_dip_count_mu(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), update_stress_tensor(), and z_energy().
#define MPI_UB (&mpifake_dtype_ub)
Definition at line 119 of file mpi.h.
Typedef Documentation
typedef long MPI_Aint
Definition at line 77 of file mpi.h.
typedef void* MPI_Comm
Definition at line 74 of file mpi.h.
typedef struct mpifake_dtype* MPI_Datatype
Definition at line 44 of file mpi.h.
typedef void* MPI_Errhandler
Definition at line 75 of file mpi.h.
typedef void(MPI_Handler_function) (MPI_Comm *, int *,...)
Definition at line 80 of file mpi.h.
typedef MPI_User_function* MPI_Op
Definition at line 82 of file mpi.h.
typedef void* MPI_Request
Definition at line 76 of file mpi.h.
typedef void* MPI_Status
Definition at line 73 of file mpi.h.
typedef void(MPI_User_function) (void *, void *, int *, MPI_Datatype *)
Definition at line 79 of file mpi.h.
Function Documentation
void errexit ()
exit ungracefully, core dump if switched on.
Definition at line 115 of file errorhandling.cpp.
References core(), and mpi_abort().
Referenced by _cuda_check_errors(), _cuda_safe_mem(), _cudaCheckError(), add_constraints_energy(), add_constraints_forces(), add_forces_from_recv_buffer(), analyze_fold_molecules(), build_verlet_lists(), build_verlet_lists_and_calc_verlet_ia(), build_verlet_lists_and_calc_verlet_ia_iccp3m(), calc_buck_cap_radii(), calc_radial_density_map(), calc_structurefactor(), check_cells_consistency(), check_particle_consistency(), check_particles(), check_tab_forcecap(), correct_vel_shake(), dawaanr_calculations(), get_name_of_bonded_ia(), ghost_communicator(), gpu_init_particle_comm(), icosaederC(), init_random_seed(), integrate_ensemble_init(), layered_exchange_and_sort_particles(), lb_calc_particle_lattice_ia_gpu(), lb_get_para_pointer(), lb_init_GPU(), lb_lbfluid_get_ext_force(), lb_lbfluid_get_interpolated_velocity_global(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_density(), lb_viscous_coupling(), local_place_particle(), local_remove_particle(), magnetic_dipolar_direct_sum_calculations(), maxwell_velocitiesC(), mdlc_tune(), MMM2D_setup_constants(), mpi_bcast_coulomb_params_slave(), mpi_gather_stats(), mpi_gather_stats_slave(), mpi_get_particles(), MPI_Irecv(), MPI_Isend(), mpi_loop(), MPI_Recv(), MPI_Send(), MPI_Sendrecv(), mpifake_sendrecv(), mpifake_unpack_hvector(), mpifake_unpack_struct(), on_coulomb_change(), prepare_send_buffer(), printAllComms(), propagate_pos_sd_cuda(), propagate_vel_pos(), put_recv_buffer(), recv_particles(), reduce_forces_sum(), remove_all_bonds_to(), sd_compute_brownian_force_farfield(), tclprint_to_result_overlapIA(), topology_init(), topology_release(), and velocitiesC().
int MPI_Abort (MPI_Comm comm, int status) inline
Definition at line 130 of file mpi.h.
References MPI_SUCCESS.
Referenced by mpi_abort().
int MPI_Allgather (void * sbuf, int scount, MPI_Datatype sdtype, void * rbuf, int rcount, MPI_Datatype rdtype, MPI_Comm comm) inline
Definition at line 194 of file mpi.h.
References mpifake_sendrecv().
Referenced by nsq_balance_particles().
int MPI_Allreduce (void * sbuf, void * rbuf, int count, MPI_Datatype dtype, MPI_Op op, MPI_Comm comm) inline
Definition at line 205 of file mpi.h.
References MPI_IN_PLACE, and MPI_SUCCESS.
Referenced by add_z_force(), announce_resort_particles(), calc_area_global(), calc_kinetic(), calc_mu_max(), calc_volume(), CalcVolumes(), RuntimeErrorCollector::count(), gather_image_contributions(), get_DLC_dipolar(), iccp3m_iteration(), layered_exchange_and_sort_particles(), lb_calc_average_rho(), maggs_calc_init_e_field(), maggs_check_curl_E(), maggs_compute_dipole_correction(), maggs_electric_energy(), slab_dip_count_mu(), steepest_descent_step(), and z_energy().
int MPI_Barrier (MPI_Comm comm) inline
Definition at line 150 of file mpi.h.
References MPI_SUCCESS.
Referenced by mpi_loop(), mpi_stop(), and mpi_stop_slave().
int MPI_Bcast (void * buff, int count, MPI_Datatype datatype, int root, MPI_Comm comm) inline
Definition at line 155 of file mpi.h.
References MPI_SUCCESS.
Referenced by bcast_iccp3m_cfg(), check_particles(), common_bcast_parameter(), correct_pos_shake(), correct_vel_shake(), dd_exchange_and_sort_particles(), dd_topology_init(), ghost_communicator(), integrate_sd(), integrate_vv(), layered_topology_init(), lb_calc_densprof(), lb_calc_velprof(), local_setup_reaction(), minimize_energy(), mpi_bcast_collision_params_slave(), mpi_bcast_constraint(), mpi_bcast_constraint_slave(), mpi_bcast_coulomb_params_slave(), mpi_bcast_cuda_global_part_vars_slave(), mpi_bcast_ia_params(), mpi_bcast_ia_params_slave(), mpi_bcast_lb_params_slave(), mpi_bcast_lbboundary(), mpi_bcast_lbboundary_slave(), mpi_bcast_nptiso_geom_slave(), mpi_cap_forces_slave(), mpi_external_potential_broadcast(), mpi_external_potential_broadcast_slave(), mpi_galilei_transform(), mpi_galilei_transform_slave(), mpi_local_stress_tensor(), mpi_local_stress_tensor_slave(), mpi_loop(), mpi_observable_lb_radial_velocity_profile_slave_implementation(), mpi_send_exclusion(), mpi_send_exclusion_slave(), mpi_set_smaller_time_step(), mpi_set_smaller_time_step_slave(), mpi_set_time_step(), mpi_set_time_step_slave(), mpi_sync_topo_part_info(), mpi_sync_topo_part_info_slave(), observable_calc_lb_radial_velocity_profile(), on_coulomb_change(), on_integration_start(), and propagate_press_box_pos_and_rescale_npt().
int MPI_Cart_coords (MPI_Comm comm, int rank, int maxdims, int * coords) inline
Definition at line 134 of file mpi.h.
References MPI_SUCCESS.
Referenced by grid_changed_n_nodes(), map_node_array(), and mpi_init().
int MPI_Cart_create (MPI_Comm comm_old, int ndims, int * dims, int * periods, int reorder, MPI_Comm * comm_cart) inline
Definition at line 137 of file mpi.h.
References MPI_SUCCESS.
Referenced by grid_changed_n_nodes(), and mpi_init().
int MPI_Cart_rank (MPI_Comm comm, int * coords, int * rank) inline
Definition at line 133 of file mpi.h.
References MPI_SUCCESS.
Referenced by map_array_node().
int MPI_Cart_shift (MPI_Comm comm, int direction, int disp, int * rank_source, int * rank_dest) inline
Definition at line 135 of file mpi.h.
References MPI_SUCCESS.
Referenced by calc_node_neighbors().
int MPI_Comm_create_errhandler (MPI_Handler_function * errfunc, MPI_Errhandler * errhdl) inline
Definition at line 153 of file mpi.h.
References MPI_SUCCESS.
Referenced by mpi_init().
int MPI_Comm_free (MPI_Comm * comm) inline
Definition at line 141 of file mpi.h.
References MPI_SUCCESS.
Referenced by grid_changed_n_nodes(), lb_calc_densprof(), lb_calc_velprof(), and maggs_calc_init_e_field().
int MPI_Comm_rank (MPI_Comm comm, int * rank) inline
Definition at line 132 of file mpi.h.
References MPI_SUCCESS.
Referenced by grid_changed_n_nodes(), lb_calc_densprof(), lb_calc_velprof(), and mpi_init().
int MPI_Comm_set_errhandler (MPI_Comm comm, MPI_Errhandler errhdl) inline
Definition at line 154 of file mpi.h.
References MPI_SUCCESS.
Referenced by mpi_init().
int MPI_Comm_size (MPI_Comm comm, int * psize) inline
Definition at line 131 of file mpi.h.
References MPI_SUCCESS.
Referenced by mpi_init().
int MPI_Comm_split (MPI_Comm comm, int colour, int key, MPI_Comm * newcomm) inline
Definition at line 140 of file mpi.h.
References MPI_SUCCESS.
Referenced by lb_calc_densprof(), lb_calc_velprof(), and maggs_calc_init_e_field().
int MPI_Dims_create (int nnodes, int ndims, int * dims) inline
Definition at line 139 of file mpi.h.
References MPI_SUCCESS.
Referenced by mpi_init().
int MPI_Error_string (int errcode, char * string, int * len) inline
Definition at line 209 of file mpi.h.
References MPI_SUCCESS.
Referenced by mpi_core().
int MPI_Finalize (void) inline
Definition at line 129 of file mpi.h.
References MPI_SUCCESS.
Referenced by mpi_stop(), and mpi_stop_slave().
int MPI_Gather (void * sbuf, int scount, MPI_Datatype sdtype, void * rbuf, int rcount, MPI_Datatype rdtype, int root, MPI_Comm comm) inline
Definition at line 190 of file mpi.h.
References mpifake_sendrecv().
Referenced by IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_send_velocities(), lb_calc_densprof(), lb_calc_velprof(), mpi_bit_random_seed(), mpi_bit_random_seed_slave(), mpi_bit_random_stat(), mpi_bit_random_stat_slave(), mpi_get_particles(), mpi_get_particles_slave(), mpi_random_seed(), mpi_random_seed_slave(), mpi_random_stat(), mpi_random_stat_slave(), mpi_who_has(), and mpi_who_has_slave().
int MPI_Get_count (const MPI_Status * status, MPI_Datatype datatype, int * count) inline
Definition at line 157 of file mpi.h.
References MPI_SUCCESS.
Referenced by RuntimeErrorCollector::gather().
int MPI_Get_processor_name (char * proc_name, int * proc_name_len) inline
Definition at line 213 of file mpi.h.
References MPI_SUCCESS.
int MPI_Init (int * a, char *** b) inline
Definition at line 128 of file mpi.h.
References MPI_SUCCESS.
Referenced by mpi_init().
int MPI_Irecv (void * buf, int count, MPI_Datatype dtype, int src, int tag, MPI_Comm comm, MPI_Request * req) inline
Definition at line 164 of file mpi.h.
References errexit(), and MPI_SUCCESS.
Referenced by halo_communication(), and maggs_exchange_surface_patch().
int MPI_Isend (void * buf, int count, MPI_Datatype dtype, int dst, int tag, MPI_Comm comm, MPI_Request * req) inline
Definition at line 171 of file mpi.h.
References errexit(), and MPI_SUCCESS.
Referenced by halo_communication(), and maggs_exchange_surface_patch().
int MPI_Op_create (MPI_User_function func, int commute, MPI_Op * pop) inline
Definition at line 202 of file mpi.h.
References MPI_SUCCESS.
Referenced by ghost_init().
int MPI_Probe (int source, int tag, MPI_Comm comm, MPI_Status * status) inline
Definition at line 156 of file mpi.h.
References MPI_SUCCESS.
Referenced by RuntimeErrorCollector::gather().
int MPI_Recv (void * buf, int count, MPI_Datatype dtype, int src, int tag, MPI_Comm comm, MPI_Status * stat) inline
Definition at line 162 of file mpi.h.
References errexit(), and MPI_SUCCESS.
Referenced by distribute(), RuntimeErrorCollector::gather(), ghost_communicator(), IBM_cuda_mpi_get_particles(), IBM_cuda_mpi_send_velocities_slave(), lb_calc_densprof(), lb_calc_velprof(), maggs_calc_init_e_field(), mpi_comm_mol_info(), mpi_comm_mol_info_slave(), mpi_get_particles(), mpi_place_new_particle_slave(), mpi_place_particle_slave(), mpi_recv_fluid(), mpi_recv_fluid_boundary_flag(), mpi_recv_fluid_populations(), mpi_recv_part(), mpi_rescale_particles_slave(), mpi_send_bond(), mpi_send_bond_slave(), mpi_send_configtemp_flag_slave(), mpi_send_dip_slave(), mpi_send_dipm_slave(), mpi_send_ext_force_slave(), mpi_send_ext_torque_slave(), mpi_send_f_slave(), mpi_send_fluid_populations_slave(), mpi_send_fluid_slave(), mpi_send_mass_slave(), mpi_send_mol_id_slave(), mpi_send_mu_E_slave(), mpi_send_omega_slave(), mpi_send_q_slave(), mpi_send_quat_slave(), mpi_send_rotation_slave(), mpi_send_rotational_inertia_slave(), mpi_send_smaller_timestep_flag_slave(), mpi_send_solvation_slave(), mpi_send_swimming_slave(), mpi_send_torque_slave(), mpi_send_type_slave(), mpi_send_v_slave(), mpi_send_virtual_slave(), mpi_send_vs_relative_slave(), mpi_set_particle_gamma_slave(), mpi_set_particle_temperature_slave(), mpi_system_CMS(), mpi_system_CMS_velocity(), mpi_who_has(), and recv_particles().
int MPI_Reduce (void * sbuf, void * rbuf, int count, MPI_Datatype dtype, MPI_Op op, int root, MPI_Comm comm) inline
Definition at line 203 of file mpi.h.
References MPI_SUCCESS.
Referenced by correct_pos_shake(), correct_vel_shake(), dd_exchange_and_sort_particles(), energy_calc(), finalize_p_inst_npt(), get_DLC_energy_dipolar(), ghost_communicator(), lb_calc_fluid_mass(), lb_calc_fluid_momentum(), lb_calc_fluid_temp(), lb_collect_boundary_forces(), maggs_count_charged_particles(), mpi_external_potential_sum_energies(), mpi_external_potential_sum_energies_slave(), mpi_get_configtemp(), mpi_get_configtemp_slave(), mpi_get_constraint_force(), mpi_get_constraint_force_slave(), mpi_local_stress_tensor(), mpi_local_stress_tensor_slave(), mpi_observable_lb_radial_velocity_profile_slave_implementation(), observable_calc_lb_radial_velocity_profile(), observable_compute_stress_tensor(), predict_momentum_particles(), pressure_calc(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
int MPI_Scatter (void * sbuf, int scount, MPI_Datatype sdtype, void * rbuf, int rcount, MPI_Datatype rdtype, int root, MPI_Comm comm) inline
Definition at line 198 of file mpi.h.
References mpifake_sendrecv().
Referenced by mpi_bit_random_seed(), mpi_bit_random_seed_slave(), mpi_bit_random_stat(), mpi_bit_random_stat_slave(), mpi_random_seed(), mpi_random_seed_slave(), mpi_random_stat(), and mpi_random_stat_slave().
int MPI_Send (void * buf, int count, MPI_Datatype dtype, int dst, int tag, MPI_Comm comm) inline
Definition at line 166 of file mpi.h.
References errexit(), and MPI_SUCCESS.
Referenced by distribute(), RuntimeErrorCollector::gatherSlave(), ghost_communicator(), IBM_cuda_mpi_get_particles_slave(), IBM_cuda_mpi_send_velocities(), lb_calc_densprof(), lb_calc_velprof(), maggs_calc_init_e_field(), mpi_comm_mol_info(), mpi_comm_mol_info_slave(), mpi_get_particles_slave(), mpi_place_new_particle(), mpi_place_particle(), mpi_recv_fluid_boundary_flag_slave(), mpi_recv_fluid_populations_slave(), mpi_recv_fluid_slave(), mpi_recv_part_slave(), mpi_rescale_particles(), mpi_send_bond(), mpi_send_bond_slave(), mpi_send_configtemp_flag(), mpi_send_dip(), mpi_send_dipm(), mpi_send_ext_force(), mpi_send_ext_torque(), mpi_send_f(), mpi_send_fluid(), mpi_send_fluid_populations(), mpi_send_mass(), mpi_send_mol_id(), mpi_send_mu_E(), mpi_send_omega(), mpi_send_q(), mpi_send_quat(), mpi_send_rotation(), mpi_send_rotational_inertia(), mpi_send_smaller_timestep_flag(), mpi_send_solvation(), mpi_send_swimming(), mpi_send_torque(), mpi_send_type(), mpi_send_v(), mpi_send_virtual(), mpi_send_vs_relative(), mpi_set_particle_gamma(), mpi_set_particle_temperature(), mpi_system_CMS_slave(), mpi_system_CMS_velocity_slave(), mpi_who_has_slave(), and send_particles().
int MPI_Sendrecv (void * sbuf, int scount, MPI_Datatype stype, int dst, int stag, void * rbuf, int rcount, MPI_Datatype rtype, int src, int rtag, MPI_Comm comm, MPI_Status * stat) inline
Definition at line 168 of file mpi.h.
References errexit(), and MPI_SUCCESS.
Referenced by halo_communication(), halo_push_communication(), and lb_check_halo_regions().
int MPI_Type_commit (MPI_Datatype * dtype) inline
Definition at line 142 of file mpi.h.
References MPI_SUCCESS.
Referenced by lb_prepare_communication(), maggs_exchange_surface_patch(), maggs_prepare_surface_planes(), and prepare_halo_communication().
int MPI_Type_contiguous (int count, MPI_Datatype oldtype, MPI_Datatype * newtype)
Definition at line 80 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, mpifake_dtype::format, LAM_DTCONTIG, mpifake_dtype::lower, malloc, MPI_SUCCESS, mpifake_dtblock(), mpifake_dtype::size, and mpifake_dtype::upper.
Referenced by maggs_exchange_surface_patch(), and maggs_prepare_surface_planes().
int MPI_Type_create_hvector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype * newtype)
Definition at line 141 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, mpifake_dtype::format, LAM_DTHVECTOR, mpifake_dtype::length, mpifake_dtype::lower, malloc, MPI_SUCCESS, mpifake_dtblock(), mpifake_dtype::size, mpifake_dtype::stride, and mpifake_dtype::upper.
Referenced by lb_prepare_communication(), maggs_exchange_surface_patch(), and MPI_Type_hvector().
int MPI_Type_extent (MPI_Datatype dtype, MPI_Aint * pextent) inline
Definition at line 144 of file mpi.h.
References mpifake_dtype::lower, MPI_SUCCESS, and mpifake_dtype::upper.
int MPI_Type_free (MPI_Datatype * dtype) inline
Definition at line 143 of file mpi.h.
References free, and MPI_SUCCESS.
Referenced by prepare_halo_communication(), and release_halo_communication().
int MPI_Type_get_extent (MPI_Datatype dtype, MPI_Aint * lower, MPI_Aint * pextent) inline
Definition at line 145 of file mpi.h.
References mpifake_dtype::lower, MPI_SUCCESS, and mpifake_dtype::upper.
Referenced by lb_prepare_communication().
int MPI_Type_hvector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype * newtype)
Definition at line 136 of file mpi.cpp.
References MPI_Type_create_hvector().
int MPI_Type_struct (int count, int * lengths, MPI_Aint * disps, MPI_Datatype * oldtypes, MPI_Datatype * newtype)
Definition at line 40 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::disps, mpifake_dtype::dtypes, mpifake_dtype::format, i, LAM_DTSTRUCT, mpifake_dtype::lengths, mpifake_dtype::lower, malloc, MPI_SUCCESS, mpifake_dtblock(), mpifake_dtype::size, and mpifake_dtype::upper.
int MPI_Type_vector (int count, int length, int stride, MPI_Datatype oldtype, MPI_Datatype * newtype)
Definition at line 101 of file mpi.cpp.
References mpifake_dtype::count, mpifake_dtype::dtype, mpifake_dtype::format, LAM_DTVECTOR, mpifake_dtype::length, mpifake_dtype::lower, malloc, MPI_SUCCESS, mpifake_dtblock(), mpifake_dtype::size, mpifake_dtype::stride, and mpifake_dtype::upper.
Referenced by maggs_exchange_surface_patch(), maggs_prepare_surface_planes(), and prepare_halo_communication().
int MPI_Wait (MPI_Request * reqs, MPI_Status * stats) inline
Definition at line 152 of file mpi.h.
References MPI_SUCCESS.
Referenced by halo_communication().
int MPI_Waitall (int count, MPI_Request * reqs, MPI_Status * stats) inline
Definition at line 151 of file mpi.h.
References MPI_SUCCESS.
Referenced by maggs_exchange_surface_patch().
void mpifake_copy (void * from, void * to, int * count, MPI_Datatype * dtype)
Definition at line 435 of file mpi.cpp.
References LAM_DTCONTIG, LAM_DTHVECTOR, LAM_DTSTRUCT, LAM_DTVECTOR, mpifake_copy(), mpifake_cpy_hvector(), and mpifake_cpy_struct().
Referenced by mpifake_copy(), mpifake_cpy_hvector(), mpifake_cpy_struct(), and mpifake_sendrecv().
int mpifake_sendrecv (void * s, int scount, MPI_Datatype sdtype, void * r, int rcount, MPI_Datatype rdtype)
Definition at line 465 of file mpi.cpp.
References errexit(), free, malloc, MPI_SUCCESS, mpifake_copy(), mpifake_pack(), mpifake_unpack(), and mpifake_dtype::size.
Referenced by MPI_Allgather(), MPI_Gather(), and MPI_Scatter().
Variable Documentation
struct mpifake_dtype mpifake_dtype_byte
Definition at line 30 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_char
Definition at line 31 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_double
Definition at line 34 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_int
Definition at line 32 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_lb
Definition at line 28 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_long
Definition at line 33 of file mpi.cpp.
struct mpifake_dtype mpifake_dtype_ub
Definition at line 29 of file mpi.cpp.