ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: utils Namespace Reference
utils Namespace Reference
Data Structures
struct vector_size_unequal
Functions
template<typename T >
std::vector< T > cross_product (const std::vector< T > &a, const std::vector< T > &b) throw ()
template<typename T >
void cross_product (T const *const a, T const *const b, T *const c)
template<typename T >
double dot_product (const std::vector< T > &a, const std::vector< T > &b) throw ()
template<typename T >
double dot_product (T const *const a, T const *const b)
template<typename T >
double sqrlen (const std::vector< T > &a)
template<typename T >
double sqrlen (T const *const a)
template<typename T >
double veclen (const std::vector< T > &a)
template<typename T >
double veclen (T const *const a)
template<typename T >
std::vector< T > vecsub (const std::vector< T > &a, const std::vector< T > &b) throw ()
template<typename T >
void vecsub (T const *const a, T const *const b, T *const c)
Function Documentation
template<typename T > std::vector<T> utils::cross_product (const std::vector< T > & a, const std::vector< T > & b) throw ()
Definition at line 1084 of file utils.hpp.
Referenced by calc_cylindrical_average().
template<typename T > void utils::cross_product (T const *const a, T const *const b, T *const c)
Definition at line 1096 of file utils.hpp.
template<typename T > double utils::dot_product (const std::vector< T > & a, const std::vector< T > & b) throw ()
Definition at line 1107 of file utils.hpp.
References i.
Referenced by calc_cylindrical_average().
template<typename T > double utils::dot_product (T const *const a, T const *const b)
Definition at line 1118 of file utils.hpp.
References i.
template<typename T > double utils::sqrlen (const std::vector< T > & a)
Definition at line 1130 of file utils.hpp.
References i.
Referenced by veclen().
template<typename T > double utils::sqrlen (T const *const a)
Definition at line 1139 of file utils.hpp.
References i.
template<typename T > double utils::veclen (const std::vector< T > & a)
Definition at line 1148 of file utils.hpp.
References sqrlen().
Referenced by calc_cylindrical_average().
template<typename T > double utils::veclen (T const *const a)
Definition at line 1153 of file utils.hpp.
References sqrlen().
template<typename T > std::vector<T> utils::vecsub (const std::vector< T > & a, const std::vector< T > & b) throw ()
Definition at line 1162 of file utils.hpp.
References i.
Referenced by calc_cylindrical_average().
template<typename T > void utils::vecsub (T const *const a, T const *const b, T *const c)
Definition at line 1173 of file utils.hpp.
References i.