ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: nemd_tcl.cpp File Reference
nemd_tcl.cpp File Reference
#include "nemd.hpp"
#include <cstdio>
#include "integrate.hpp"
#include "communication.hpp"
#include "parser.hpp"
#include "grid.hpp"
Functions
int tclcommand_nemd (ClientData data, Tcl_Interp *interp, int argc, char **argv)
tcl procedure for nemd steering.
Privat Functions
int tclcommand_nemd_print_usage (Tcl_Interp *interp)
Hand over nemd usage information to tcl interpreter.
int tclcommand_nemd_print_status (Tcl_Interp *interp)
Hand over nemd status information to tcl interpreter.
int tclcommand_nemd_parse_exchange (Tcl_Interp *interp, int argc, char **argv)
Set nemd method to exchange and set nemd parameters.
int tclcommand_nemd_parse_shearrate (Tcl_Interp *interp, int argc, char **argv)
Set nemd method to shearrate and set nemd parameters.
int tclcommand_nemd_parse_and_print_profile (Tcl_Interp *interp)
Hand over velocity profile to tcl interpreter.
int tclcommand_nemd_parse_and_print_viscosity (Tcl_Interp *interp)
Gives back the calculated viscosity.
Function Documentation
int tclcommand_nemd (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
tcl procedure for nemd steering.
USAGE: nemd <n_slabs> <n_exchange> see also tclcommand_nemd. See nemd_tcl.cpp
Definition at line 203 of file nemd_tcl.cpp.
References ARG1_IS_S, gather_runtime_errors(), INTEG_TRACE, nemd_free(), nemd_method, NEMD_METHOD_OFF, tclcommand_nemd_parse_and_print_profile(), tclcommand_nemd_parse_and_print_viscosity(), tclcommand_nemd_parse_exchange(), tclcommand_nemd_parse_shearrate(), tclcommand_nemd_print_status(), tclcommand_nemd_print_usage(), and this_node.
Referenced by tcl_register_commands().
int tclcommand_nemd_parse_and_print_profile (Tcl_Interp * interp)
Hand over velocity profile to tcl interpreter.
Definition at line 140 of file nemd_tcl.cpp.
References i, INTEG_TRACE, Nemd::n_slabs, nemd_method, NEMD_METHOD_OFF, nemddata, Nemd::profile_norm, this_node, time_step, and Nemd::velocity_profile.
Referenced by tclcommand_nemd().
int tclcommand_nemd_parse_and_print_viscosity (Tcl_Interp * interp)
Gives back the calculated viscosity.
Definition at line 166 of file nemd_tcl.cpp.
References box_l, INTEG_TRACE, Nemd::momentum, Nemd::momentum_norm, nemd_method, NEMD_METHOD_EXCHANGE, NEMD_METHOD_OFF, NEMD_METHOD_SHEARRATE, nemddata, Nemd::shear_rate, this_node, and time_step.
Referenced by tclcommand_nemd().
int tclcommand_nemd_parse_exchange (Tcl_Interp * interp, int argc, char ** argv)
Set nemd method to exchange and set nemd parameters.
Definition at line 90 of file nemd_tcl.cpp.
References ARG_IS_I, nemd_init(), nemd_method, NEMD_METHOD_EXCHANGE, and tclcommand_nemd_print_usage().
Referenced by tclcommand_nemd().
int tclcommand_nemd_parse_shearrate (Tcl_Interp * interp, int argc, char ** argv)
Set nemd method to shearrate and set nemd parameters.
Definition at line 117 of file nemd_tcl.cpp.
References ARG_IS_D, ARG_IS_I, nemd_init(), nemd_method, NEMD_METHOD_SHEARRATE, and tclcommand_nemd_print_usage().
Referenced by tclcommand_nemd().
int tclcommand_nemd_print_status (Tcl_Interp * interp)
Hand over nemd status information to tcl interpreter.
Definition at line 61 of file nemd_tcl.cpp.
References Nemd::n_exchange, Nemd::n_slabs, nemd_method, NEMD_METHOD_EXCHANGE, NEMD_METHOD_OFF, NEMD_METHOD_SHEARRATE, nemddata, and Nemd::shear_rate.
Referenced by tclcommand_nemd().
int tclcommand_nemd_print_usage (Tcl_Interp * interp)
Hand over nemd usage information to tcl interpreter.
Definition at line 41 of file nemd_tcl.cpp.
Referenced by tclcommand_nemd(), tclcommand_nemd_parse_exchange(), and tclcommand_nemd_parse_shearrate().