ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: nemd.cpp File Reference
nemd.cpp File Reference
For more information see nemd.hpp.
#include "nemd.hpp"
#include <cstdio>
#include "integrate.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
Functions
void nemd_change_momentum ()
Change momentum in top an middle slab.
void nemd_store_velocity_profile ()
Store the mean value of the velocity x-component of all slabs in Nemd::velocity_profile.
Privat Functions
int nemd_free (void)
Free all associated memory.
void nemd_init (int n_slabs, int n_exchange, double shear_rate)
Initialize all data structures for nemd.
Variables
int nemd_method = NEMD_METHOD_OFF
Nemd nemddata = { -1, 0, 0, 0.0, 1.0, NULL, 0, 0, NULL, 0.0, 0.0, 0.0, 0}
Structure containing the nemd relevant information.
Detailed Description
For more information see nemd.hpp.
Definition in file nemd.cpp.
Function Documentation
void nemd_change_momentum ()
Change momentum in top an middle slab.
How this is done depends on nemd method.
Definition at line 137 of file nemd.cpp.
References Slab::fastest, i, INTEG_TRACE, local_particles, Particle::m, Nemd::mid_slab, Nemd::momentum, Nemd::momentum_norm, Nemd::n_exchange, Slab::n_fastest, Slab::n_parts_in_slab, nemd_method, NEMD_METHOD_EXCHANGE, NEMD_METHOD_OFF, NEMD_METHOD_SHEARRATE, runtimeError, Nemd::slab, Nemd::slab_vel, this_node, Nemd::top_slab, ParticleMomentum::v, Slab::v_mean, Slab::v_min, and Slab::vel_diff.
Referenced by propagate_vel().
int nemd_free (void)
Free all associated memory.
Definition at line 45 of file nemd.cpp.
References ES_OK, Slab::fastest, free, INTEG_TRACE, Nemd::invthickness, Nemd::mid_slab, Nemd::n_exchange, Nemd::n_slabs, Nemd::profile_norm, Nemd::shear_rate, Nemd::slab, Nemd::slab_vel, Nemd::thickness, this_node, Nemd::top_slab, and Nemd::velocity_profile.
Referenced by nemd_init(), and tclcommand_nemd().
void nemd_init (int n_slabs, int n_exchange, double shear_rate)
Initialize all data structures for nemd.
Definition at line 69 of file nemd.cpp.
References box_l, Slab::fastest, i, Slab::ind_min, INTEG_TRACE, Nemd::invthickness, malloc, Nemd::mid_slab, Nemd::momentum, Nemd::momentum_norm, Nemd::n_exchange, Slab::n_fastest, n_nodes, Slab::n_parts_in_slab, Nemd::n_slabs, nemd_free(), runtimeError, Nemd::shear_rate, Nemd::slab, Nemd::slab_vel, Nemd::thickness, this_node, time_step, Nemd::top_slab, Slab::v_mean, Slab::v_min, Slab::vel_diff, and Nemd::velocity_profile.
Referenced by tclcommand_nemd_parse_exchange(), and tclcommand_nemd_parse_shearrate().
void nemd_store_velocity_profile ()
Store the mean value of the velocity x-component of all slabs in Nemd::velocity_profile.
Definition at line 194 of file nemd.cpp.
References i, INTEG_TRACE, Slab::n_parts_in_slab, Nemd::n_slabs, Nemd::profile_norm, Nemd::slab, this_node, Slab::v_mean, and Nemd::velocity_profile.
Referenced by propagate_vel().
Variable Documentation
int nemd_method = NEMD_METHOD_OFF
Definition at line 35 of file nemd.cpp.
Referenced by integrate_vv(), nemd_add_velocity(), nemd_change_momentum(), nemd_get_velocity(), tclcommand_nemd(), tclcommand_nemd_parse_and_print_profile(), tclcommand_nemd_parse_and_print_viscosity(), tclcommand_nemd_parse_exchange(), tclcommand_nemd_parse_shearrate(), and tclcommand_nemd_print_status().
Nemd nemddata = { -1, 0, 0, 0.0, 1.0, NULL, 0, 0, NULL, 0.0, 0.0, 0.0, 0}
Structure containing the nemd relevant information.
Definition at line 38 of file nemd.cpp.
Referenced by tclcommand_nemd_parse_and_print_profile(), tclcommand_nemd_parse_and_print_viscosity(), and tclcommand_nemd_print_status().