ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: nsquare.cpp File Reference
nsquare.cpp File Reference
Implementation of nsquare.h.
#include <mpi.h>
#include <cstring>
#include "utils.hpp"
#include "nsquare.hpp"
#include "communication.hpp"
#include "ghosts.hpp"
#include "forces.hpp"
#include "pressure.hpp"
#include "energy_inline.hpp"
#include "constraint.hpp"
Functions
Cell * nsq_position_to_cell (double pos[3])
always returns the one local cell
void nsq_topology_release ()
always returns the one local cell
static void nsq_prepare_comm (GhostCommunicator *comm, int data_parts)
void nsq_topology_init (CellPList *old)
setup the nsquare topology
void nsq_balance_particles (int global_flag)
implements the load balancing as described above.
void nsq_calculate_ia ()
nonbonded and bonded force calculation using the verlet list
void nsq_calculate_energies ()
n^2 energy calculation
void nsq_calculate_virials (int v_comp)
n^2 pressure calculation
Variables
Cell * local
CellPList me_do_ghosts
Detailed Description
Implementation of nsquare.h.
Definition in file nsquare.cpp.
Function Documentation
void nsq_balance_particles (int global_flag)
implements the load balancing as described above.
Definition at line 155 of file nsquare.cpp.
References CELL_GLOBAL_EXCHANGE, CELL_TRACE, cells_get_n_particles(), check_particle_consistency(), comm_cart, free, i, init_particlelist(), malloc, MPI_Allgather(), MPI_INT, ParticleList::n, n_nodes, n_part, ParticleList::part, realloc_particlelist(), recv_particles(), send_particles(), this_node, and update_local_particles().
Referenced by cells_resort_particles().
void nsq_calculate_energies ()
n^2 energy calculation
Definition at line 296 of file nsquare.cpp.
References add_bonded_energy(), add_constraints_energy(), add_external_potential_energy(), add_kinetic_energy(), add_non_bonded_pair_energy(), CellPList::cell, do_nonbonded(), get_mi_vector(), Particle::l, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, and sqrlen().
Referenced by energy_calc().
void nsq_calculate_ia ()
nonbonded and bonded force calculation using the verlet list
n^2 force calculation
Definition at line 242 of file nsquare.cpp.
References add_bonded_force(), add_constraints_forces(), add_external_potential_forces(), add_non_bonded_pair_force(), CellPList::cell, do_nonbonded(), get_mi_vector(), Particle::l, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, and sqrlen().
Referenced by force_calc().
void nsq_calculate_virials (int v_comp)
n^2 pressure calculation
Definition at line 351 of file nsquare.cpp.
References add_bonded_virials(), add_kinetic_virials(), add_non_bonded_pair_virials(), add_three_body_bonded_stress(), CellPList::cell, do_nonbonded(), get_mi_vector(), Particle::l, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, and sqrlen().
Referenced by pressure_calc().
Cell* nsq_position_to_cell (double pos[3])
always returns the one local cell
Definition at line 40 of file nsquare.cpp.
References local.
Referenced by nsq_topology_init().
static void nsq_prepare_comm (GhostCommunicator * comm, int data_parts) static
Definition at line 56 of file nsquare.cpp.
References cells, GhostCommunicator::comm, comm_cart, malloc, GhostCommunication::mpi_comm, n_nodes, GhostCommunication::n_part_lists, GhostCommunication::node, GhostCommunication::part_lists, and prepare_comm().
Referenced by nsq_topology_init().
void nsq_topology_init (CellPList * old)
setup the nsquare topology
Definition at line 76 of file nsquare.cpp.
References append_unindexed_particle(), CellPList::cell, cell_structure, CELL_STRUCTURE_NSQUARE, CELL_TRACE, cells, CellStructure::collect_ghost_force_comm, GhostCommunicator::comm, CellStructure::exchange_ghosts_comm, GHOST_BCST, ghost_cells, CellStructure::ghost_cells_comm, GHOST_PREFETCH, GHOST_RDCE, GHOSTTRANS_FORCE, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, init_cellplist(), local, local_cells, map_position_node_array(), CellPList::n, ParticleList::n, n_nodes, nsq_position_to_cell(), nsq_prepare_comm(), ParticleList::part, CellStructure::position_to_cell, CellStructure::position_to_node, realloc_cellplist(), realloc_cells(), this_node, CellStructure::type, GhostCommunication::type, CellStructure::update_ghost_pos_comm, and update_local_particles().
Referenced by topology_init().
void nsq_topology_release ()
always returns the one local cell
Definition at line 45 of file nsquare.cpp.
References cell_structure, CELL_TRACE, CellStructure::collect_ghost_force_comm, CellStructure::exchange_ghosts_comm, free_comm(), CellStructure::ghost_cells_comm, realloc_cellplist(), this_node, and CellStructure::update_ghost_pos_comm.
Referenced by topology_release().
Variable Documentation
Cell* local
Definition at line 37 of file nsquare.cpp.
Referenced by nsq_position_to_cell(), and nsq_topology_init().
CellPList me_do_ghosts
Definition at line 38 of file nsquare.cpp.