ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: nsquare.hpp File Reference
nsquare.hpp File Reference
This file contains the code for a simple n^2 particle loop.
#include "cells.hpp"
Functions
Cell * nsq_position_to_cell (double pos[3])
always returns the one local cell
void nsq_topology_release ()
always returns the one local cell
void nsq_topology_init (CellPList *local)
setup the nsquare topology
void nsq_balance_particles (int global_flag)
implements the load balancing as described above.
void nsq_calculate_ia ()
n^2 force calculation
void nsq_calculate_energies ()
n^2 energy calculation
void nsq_calculate_virials (int v_comp)
n^2 pressure calculation
Detailed Description
This file contains the code for a simple n^2 particle loop.
The nsquare cell system performs a full n^2 particle interaction calculation over the simulation box. Therefore every node just has a single cell containing all local particles plus one ghost cell per other node. The communication is done via broadcasts (exchange_ghosts and update_ghosts) and reduce operations (collect_ghost_force).
The algorithm used for interaction calculation is parallelized, but a full communication is needed every time step. Let us assume that the number of nodes P is odd. Then a node p will do the interaction calculation with another node q iff is even. Of course then every node has to do the same amount of work (provided the particles are distributed equally), and each interaction pair is done exactly once, since for odd P odd iff is even. For an even number of nodes, a virtual additional processor is assumed, with which no interactions occur. This means, that each communication cycle, 1 processor is idle, which is pretty ineffective.
The second main part of this cell system is a load balancer which at the beginning of the integration is called and balances the numbers of particles between the nodes. This means that the number of particles per node should be around , so the goal is to let every processor have a number of particles which is one of the two integers closest to . The algorithm is greedy, i. e. it searches for the node with most and least particles and transfers as much as possible particles between them so that at least one of them satisfies the constraints. Of course the algorithm terminates if both satisfy the condition without transfer.
The calculations themselves are just simple loops over all appropriate particle pairs.
Definition in file nsquare.hpp.
Function Documentation
void nsq_balance_particles (int global_flag)
implements the load balancing as described above.
Definition at line 155 of file nsquare.cpp.
References CELL_GLOBAL_EXCHANGE, CELL_TRACE, cells_get_n_particles(), check_particle_consistency(), comm_cart, free, i, init_particlelist(), malloc, MPI_Allgather(), MPI_INT, ParticleList::n, n_nodes, n_part, ParticleList::part, realloc_particlelist(), recv_particles(), send_particles(), this_node, and update_local_particles().
Referenced by cells_resort_particles().
void nsq_calculate_energies ()
n^2 energy calculation
Definition at line 296 of file nsquare.cpp.
References add_bonded_energy(), add_constraints_energy(), add_external_potential_energy(), add_kinetic_energy(), add_non_bonded_pair_energy(), CellPList::cell, do_nonbonded(), get_mi_vector(), Particle::l, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, and sqrlen().
Referenced by energy_calc().
void nsq_calculate_ia ()
n^2 force calculation
n^2 force calculation
Definition at line 242 of file nsquare.cpp.
References add_bonded_force(), add_constraints_forces(), add_external_potential_forces(), add_non_bonded_pair_force(), CellPList::cell, do_nonbonded(), get_mi_vector(), Particle::l, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, and sqrlen().
Referenced by force_calc().
void nsq_calculate_virials (int v_comp)
n^2 pressure calculation
Definition at line 351 of file nsquare.cpp.
References add_bonded_virials(), add_kinetic_virials(), add_non_bonded_pair_virials(), add_three_body_bonded_stress(), CellPList::cell, do_nonbonded(), get_mi_vector(), Particle::l, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleLocal::p_old, ParticleList::part, Particle::r, rebuild_verletlist, and sqrlen().
Referenced by pressure_calc().
Cell* nsq_position_to_cell (double pos[3])
always returns the one local cell
Definition at line 40 of file nsquare.cpp.
References local.
Referenced by nsq_topology_init().
void nsq_topology_init (CellPList * local)
setup the nsquare topology
Definition at line 76 of file nsquare.cpp.
References append_unindexed_particle(), CellPList::cell, cell_structure, CELL_STRUCTURE_NSQUARE, CELL_TRACE, cells, CellStructure::collect_ghost_force_comm, GhostCommunicator::comm, CellStructure::exchange_ghosts_comm, GHOST_BCST, ghost_cells, CellStructure::ghost_cells_comm, GHOST_PREFETCH, GHOST_RDCE, GHOSTTRANS_FORCE, GHOSTTRANS_PARTNUM, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, init_cellplist(), local, local_cells, map_position_node_array(), CellPList::n, ParticleList::n, n_nodes, nsq_position_to_cell(), nsq_prepare_comm(), ParticleList::part, CellStructure::position_to_cell, CellStructure::position_to_node, realloc_cellplist(), realloc_cells(), this_node, CellStructure::type, GhostCommunication::type, CellStructure::update_ghost_pos_comm, and update_local_particles().
Referenced by topology_init().
void nsq_topology_release ()
always returns the one local cell
Definition at line 45 of file nsquare.cpp.
References cell_structure, CELL_TRACE, CellStructure::collect_ghost_force_comm, CellStructure::exchange_ghosts_comm, free_comm(), CellStructure::ghost_cells_comm, realloc_cellplist(), this_node, and CellStructure::update_ghost_pos_comm.
Referenced by topology_release().