ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: overlap_tcl.hpp File Reference
overlap_tcl.hpp File Reference
Tcl interface for overlap.hpp.
#include "parser.hpp"
Functions
int tclcommand_inter_parse_overlapped_bonded (Tcl_Interp *interp, int bond_type, int argc, char **argv)
parse parameters for the overlapped bonded potential
int tclprint_to_result_overlapIA (Tcl_Interp *interp, Bonded_ia_parameters *params)
Detailed Description
Tcl interface for overlap.hpp.
Definition in file overlap_tcl.hpp.
Function Documentation
int tclcommand_inter_parse_overlapped_bonded (Tcl_Interp * interp, int bond_type, int argc, char ** argv)
parse parameters for the overlapped bonded potential
Definition at line 32 of file overlap_tcl.cpp.
References ARG_IS_S, OVERLAP_BOND_ANGLE, OVERLAP_BOND_DIHEDRAL, OVERLAP_BOND_LENGTH, OVERLAP_UNKNOWN, and overlapped_bonded_set_params().
Referenced by tclcommand_inter_parse_bonded().
int tclprint_to_result_overlapIA (Tcl_Interp * interp, Bonded_ia_parameters * params)
Definition at line 67 of file overlap_tcl.cpp.
References errexit(), Overlap_bond_parameters::filename, Bond_parameters::overlap, OVERLAP_BOND_ANGLE, OVERLAP_BOND_DIHEDRAL, OVERLAP_BOND_LENGTH, Bonded_ia_parameters::p, and Overlap_bond_parameters::type.
Referenced by tclprint_to_result_BondedIA().