ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: overlap.hpp File Reference
overlap.hpp File Reference
Routines to calculate the energy and/or force for bonds, angles and dihedrals as a sum of N functions in the forms: bonds — parameter: [N, a_i, b_i, c_i], function: U(bond) = sum_(i=1,N) {a_i*exp[-(bond-b_i)^2 /(c_i^2)]}.
#include "dihedral.hpp"
Functions
int overlapped_bonded_set_params (int bond_type, OverlappedBondedInteraction overlap_type, char *filename)
Bonded overlapped potentials: Reads overlapped parameters from a file.
int calc_overlap_bond_force (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double force[3])
Computes the two body overlapped bonded force.
int overlap_bond_energy (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double *_energy)
Computes the two body overlapped angle interaction energy (see tclcommand_inter, tclcommand_analyze).
int calc_overlap_angle_force (Particle *p_mid, Particle *p_left, Particle *p_right, Bonded_ia_parameters *iaparams, double force1[3], double force2[3])
Computes the three body overlapped angle interaction force.
int overlap_angle_energy (Particle *p_mid, Particle *p_left, Particle *p_right, Bonded_ia_parameters *iaparams, double *_energy)
Computes the three body overlapped angle interaction energy (see tclcommand_inter, tclcommand_analyze).
int calc_overlap_dihedral_force (Particle *p2, Particle *p1, Particle *p3, Particle *p4, Bonded_ia_parameters *iaparams, double force2[3], double force1[3], double force3[3])
Computes the four body overlapped dihedral interaction force.
int overlap_dihedral_energy (Particle *p2, Particle *p1, Particle *p3, Particle *p4, Bonded_ia_parameters *iaparams, double *_energy)
Computes the four body overlapped dihedral interaction energy (see tclcommand_inter, tclcommand_analyze).
Detailed Description
Routines to calculate the energy and/or force for bonds, angles and dihedrals as a sum of N functions in the forms: bonds — parameter: [N, a_i, b_i, c_i], function: U(bond) = sum_(i=1,N) {a_i*exp[-(bond-b_i)^2 /(c_i^2)]}.
angles— parameter: [N, a_i, b_i, c_i], function: U(cos(angl)) = sum_(i=1,N) {a_i*exp[-(cos(angl)-b_i)^2 / (2 * c_i^2)]}. dihedrals—parameter: [N, a_i, b_i, c_i], function: U(dihe)= sum_(i=1,N) {a_i*(1+Math.cos(c_i*dihe+b_i))}. Require feature OVERLAPPED compiled in myconfig.hpp (for more info of FEATURES, see config.hpp).
Definition in file overlap.hpp.
Function Documentation
int calc_overlap_angle_force (Particle * p_mid, Particle * p_left, Particle * p_right, Bonded_ia_parameters * iaparams, double force1[3], double force2[3]) inline
Computes the three body overlapped angle interaction force.
Adds this force to the particle forces in forces.hpp (see tclcommand_inter).
Parameters
p_mid Pointer to second/middle particle.
p_left Pointer to first/left particle.
p_right Pointer to third/right particle.
iaparams bond type number of the angle interaction (see tclcommand_inter).
force1 returns force of particle 1
force2 returns force of particle 2
Returns
0 Needs feature OVERLAPPED compiled in (see config.hpp).
Definition at line 130 of file overlap.hpp.
References get_mi_vector(), Overlap_bond_parameters::noverlaps, Bond_parameters::overlap, ParticlePosition::p, Bonded_ia_parameters::p, Overlap_bond_parameters::para_a, Overlap_bond_parameters::para_b, Overlap_bond_parameters::para_c, Particle::r, scalar(), sqrlen(), and TINY_COS_VALUE.
Referenced by add_bonded_force().
int calc_overlap_bond_force (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double force[3]) inline
Computes the two body overlapped bonded force.
Adds this force to the particle forces in forces.hpp (see tclcommand_inter).
Parameters
p1 Pointer to first particle.
p2 Pointer to second/middle particle.
iaparams bond type number of the angle interaction (see tclcommand_inter).
dx particle distance vector
force returns force of particle 1
Returns
0. Needs feature OVERLAPPED compiled in (see config.hpp).
Definition at line 53 of file overlap.hpp.
References check_id, ParticleForce::f, Particle::f, i, ParticleProperties::identity, Overlap_bond_parameters::noverlaps, ONEPART_TRACE, Bond_parameters::overlap, Particle::p, Bonded_ia_parameters::p, Overlap_bond_parameters::para_a, Overlap_bond_parameters::para_b, Overlap_bond_parameters::para_c, sqrlen(), and this_node.
Referenced by add_bonded_force(), and calc_bonded_force().
int calc_overlap_dihedral_force (Particle * p2, Particle * p1, Particle * p3, Particle * p4, Bonded_ia_parameters * iaparams, double force2[3], double force1[3], double force3[3]) inline
Computes the four body overlapped dihedral interaction force.
Adds this force to the particle forces in forces.hpp (see tclcommand_inter).
Parameters
p1,p2,p3,p4 define the angle between the planes p1,p2,p3 and p2,p3,p4
iaparams bond type number of the angle interaction (see tclcommand_inter).
force1 returns force of particle 1
force2 returns force of particle 2
force3 returns force of particle 3
Returns
0 Needs feature OVERLAPPED compiled in (see config.hpp).
Definition at line 244 of file overlap.hpp.
References calc_dihedral_angle(), i, Overlap_bond_parameters::noverlaps, Bond_parameters::overlap, Bonded_ia_parameters::p, Overlap_bond_parameters::para_a, Overlap_bond_parameters::para_b, Overlap_bond_parameters::para_c, TINY_SIN_VALUE, and vector_product().
Referenced by add_bonded_force().
int overlap_angle_energy (Particle * p_mid, Particle * p_left, Particle * p_right, Bonded_ia_parameters * iaparams, double * _energy) inline
Computes the three body overlapped angle interaction energy (see tclcommand_inter, tclcommand_analyze).
Parameters
p_mid Pointer to first particle.
p_left Pointer to second/middle particle.
p_right Pointer to third particle.
iaparams bond type number of the angle interaction (see tclcommand_inter).
_energy return energy pointer.
Returns
0. Needs feature OVERLAPPED compiled in (see config.hpp).
Definition at line 192 of file overlap.hpp.
References get_mi_vector(), Overlap_bond_parameters::noverlaps, Bond_parameters::overlap, ParticlePosition::p, Bonded_ia_parameters::p, Overlap_bond_parameters::para_a, Overlap_bond_parameters::para_b, Overlap_bond_parameters::para_c, Particle::r, scalar(), sqrlen(), and TINY_COS_VALUE.
Referenced by add_bonded_energy().
int overlap_bond_energy (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double * _energy) inline
Computes the two body overlapped angle interaction energy (see tclcommand_inter, tclcommand_analyze).
Parameters
p1 Pointer to first particle.
p2 Pointer to second/middle particle.
iaparams bond type number of the angle interaction (see tclcommand_inter).
dx particle distance vector
_energy returns energy of this interaction
Returns
0. Needs feature OVERLAPPED compiled in (see config.hpp).
Definition at line 97 of file overlap.hpp.
References Overlap_bond_parameters::noverlaps, Bond_parameters::overlap, Bonded_ia_parameters::p, Overlap_bond_parameters::para_a, Overlap_bond_parameters::para_b, Overlap_bond_parameters::para_c, and sqrlen().
Referenced by add_bonded_energy().
int overlap_dihedral_energy (Particle * p2, Particle * p1, Particle * p3, Particle * p4, Bonded_ia_parameters * iaparams, double * _energy) inline
Computes the four body overlapped dihedral interaction energy (see tclcommand_inter, tclcommand_analyze).
Parameters
p1,p2,p3,p4 define the angle between the planes p1,p2,p3 and p2,p3,p4
iaparams bond type number of the angle interaction (see tclcommand_inter).
_energy return energy pointer.
Returns
0. Needs feature OVERLAPPED compiled in (see config.hpp).
Definition at line 315 of file overlap.hpp.
References calc_dihedral_angle(), Overlap_bond_parameters::noverlaps, Bond_parameters::overlap, Bonded_ia_parameters::p, Overlap_bond_parameters::para_a, Overlap_bond_parameters::para_b, and Overlap_bond_parameters::para_c.
Referenced by add_bonded_energy().
int overlapped_bonded_set_params (int bond_type, OverlappedBondedInteraction overlap_type, char * filename)
Bonded overlapped potentials: Reads overlapped parameters from a file.
ia_params are then communicated to each node
Warning
No checking is performed for the file read!!
Definition at line 32 of file overlap.cpp.
References BONDED_IA_OVERLAPPED, bonded_ia_params, Overlap_bond_parameters::filename, i, make_bond_type_exist(), malloc, Overlap_bond_parameters::maxval, mpi_bcast_ia_params(), Overlap_bond_parameters::noverlaps, Bonded_ia_parameters::num, Bond_parameters::overlap, OVERLAP_BOND_ANGLE, OVERLAP_BOND_DIHEDRAL, OVERLAP_BOND_LENGTH, Bonded_ia_parameters::p, Overlap_bond_parameters::para_a, Overlap_bond_parameters::para_b, Overlap_bond_parameters::para_c, Overlap_bond_parameters::type, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_overlapped_bonded().