ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: p3m_gpu_cuda.cu File Reference
p3m_gpu_cuda.cu File Reference
Cuda (.cu) file for the P3M electrostatics method.
#include <stdio.h>
#include <stdlib.h>
#include <cuda.h>
#include <cufft.h>
#include "cuda_interface.hpp"
#include "cuda_utils.hpp"
#include "config.hpp"
#include "p3m_gpu.hpp"
#include "utils.hpp"
#include "EspressoSystemInterface.hpp"
#include "interaction_data.hpp"
Data Structures
struct dummytypename
Macros
#define P3M_GPU_TRACE(A)
#define SQR(A) ((A)*(A))
#define epsi 0.1
#define c2 -0.1666666666667e-0
#define c4 0.8333333333333e-2
#define c6 -0.1984126984127e-3
#define c8 0.2755731922399e-5
#define THREADS_PER_BLOCK 1024
atomic add function for several cuda architectures
Functions
__host__ __device__ double csinc (double d)
template<int cao_value>
__device__ REAL_TYPE caf (int i, REAL_TYPE x)
__host__ __device__ static void Aliasing_sums_ik (int cao, REAL_TYPE box, REAL_TYPE alpha, int mesh, int NX, int NY, int NZ, REAL_TYPE *Zaehler, REAL_TYPE *Nenner)
__global__ void calculate_influence_function_device (int cao, int mesh, REAL_TYPE box, REAL_TYPE alpha, REAL_TYPE *G_hat)
__global__ void apply_diff_op (CUFFT_TYPE_COMPLEX *mesh, const int mesh_size, CUFFT_TYPE_COMPLEX *force_mesh_x, CUFFT_TYPE_COMPLEX *force_mesh_y, CUFFT_TYPE_COMPLEX *force_mesh_z, const REAL_TYPE box)
__device__ int wrap_index (const int ind, const int mesh)
__global__ void apply_influence_function (CUFFT_TYPE_COMPLEX *mesh, int mesh_size, REAL_TYPE *G_hat)
template<int cao>
__global__ void assign_charge_kernel_shared (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX *mesh, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, int n_part, int parts_per_block)
template<int cao>
__global__ void assign_charge_kernel (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX *mesh, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, int n_part, int parts_per_block)
template<>
__global__ void assign_charge_kernel< 1 > (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX *mesh, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, int n_part, int parts_per_block)
void assign_charges (int n_part, const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX *mesh, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, int cao)
template<int cao>
__global__ void assign_forces_kernel (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX *mesh_x, CUFFT_TYPE_COMPLEX *mesh_y, CUFFT_TYPE_COMPLEX *mesh_z, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, float *lb_particle_force_gpu, REAL_TYPE prefactor, int n_part, int parts_per_block)
template<int cao>
__global__ void assign_forces_kernel_shared (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX *mesh_x, CUFFT_TYPE_COMPLEX *mesh_y, CUFFT_TYPE_COMPLEX *mesh_z, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, float *lb_particle_force_gpu, REAL_TYPE prefactor, int n_part, int parts_per_block)
void assign_forces (int n_part, const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX *mesh_x, CUFFT_TYPE_COMPLEX *mesh_y, CUFFT_TYPE_COMPLEX *mesh_z, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, float *lb_particle_force_gpu, REAL_TYPE prefactor, int cao)
void p3m_gpu_init (int cao, int mesh, REAL_TYPE alpha, REAL_TYPE box)
void p3m_gpu_add_farfield_force ()
Variables
struct dummytypename p3m_gpu_data
static char p3m_gpu_data_initialized = 0
__shared__ float weights []
Detailed Description
Cuda (.cu) file for the P3M electrostatics method.
Header file p3m_gpu.hpp .
Definition in file p3m_gpu_cuda.cu.
Macro Definition Documentation
#define c2 -0.1666666666667e-0
Referenced by csinc().
#define c4 0.8333333333333e-2
Referenced by csinc().
#define c6 -0.1984126984127e-3
Referenced by csinc().
#define c8 0.2755731922399e-5
Referenced by csinc().
#define epsi 0.1
Referenced by csinc().
#define P3M_GPU_TRACE (A)
Definition at line 44 of file p3m_gpu_cuda.cu.
Referenced by p3m_gpu_init().
#define SQR (A) ((A)*(A))
Definition at line 63 of file p3m_gpu_cuda.cu.
Referenced by Aliasing_sums_ik(), caf(), calculate_influence_function_device(), and csinc().
#define THREADS_PER_BLOCK 1024
atomic add function for several cuda architectures
Definition at line 483 of file p3m_gpu_cuda.cu.
Referenced by assign_charges().
Function Documentation
__host__ __device__ static void Aliasing_sums_ik (int cao, REAL_TYPE box, REAL_TYPE alpha, int mesh, int NX, int NY, int NZ, REAL_TYPE * Zaehler, REAL_TYPE * Nenner) static
Definition at line 351 of file p3m_gpu_cuda.cu.
References csinc(), MX, MY, MZ, P3M_BRILLOUIN, PI, REAL_TYPE, and SQR.
Referenced by calculate_influence_function_device().
__global__ void apply_diff_op (CUFFT_TYPE_COMPLEX * mesh, const int mesh_size, CUFFT_TYPE_COMPLEX * force_mesh_x, CUFFT_TYPE_COMPLEX * force_mesh_y, CUFFT_TYPE_COMPLEX * force_mesh_z, const REAL_TYPE box)
Definition at line 502 of file p3m_gpu_cuda.cu.
References CUFFT_TYPE_COMPLEX, PI, and weights.
Referenced by p3m_gpu_add_farfield_force().
__global__ void apply_influence_function (CUFFT_TYPE_COMPLEX * mesh, int mesh_size, REAL_TYPE * G_hat)
Definition at line 541 of file p3m_gpu_cuda.cu.
Referenced by p3m_gpu_add_farfield_force().
template<int cao> __global__ void assign_charge_kernel (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX * mesh, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, int n_part, int parts_per_block)
id of the particle
position relative to the closest gird point
index of the nearest mesh point
Definition at line 591 of file p3m_gpu_cuda.cu.
References atomicAdd(), REAL_TYPE, and wrap_index().
template<> __global__ void assign_charge_kernel< 1 > (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX * mesh, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, int n_part, int parts_per_block)
id of the particle
position relative to the closest gird point
index of the nearest mesh point
Definition at line 630 of file p3m_gpu_cuda.cu.
References atomicAdd(), REAL_TYPE, and wrap_index().
Referenced by assign_charges().
template<int cao> __global__ void assign_charge_kernel_shared (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX * mesh, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, int n_part, int parts_per_block)
id of the particle
position relative to the closest gird point
index of the nearest mesh point
Definition at line 549 of file p3m_gpu_cuda.cu.
References atomicAdd(), REAL_TYPE, weights, and wrap_index().
void assign_charges (int n_part, const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX * mesh, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, int cao)
Definition at line 664 of file p3m_gpu_cuda.cu.
References _cuda_check_errors(), assign_charge_kernel< 1 >(), block(), n_part, and THREADS_PER_BLOCK.
Referenced by p3m_gpu_add_farfield_force().
void assign_forces (int n_part, const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX * mesh_x, CUFFT_TYPE_COMPLEX * mesh_y, CUFFT_TYPE_COMPLEX * mesh_z, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, float * lb_particle_force_gpu, REAL_TYPE prefactor, int cao)
Definition at line 811 of file p3m_gpu_cuda.cu.
References _cuda_check_errors(), block(), and n_part.
Referenced by p3m_gpu_add_farfield_force().
template<int cao> __global__ void assign_forces_kernel (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX * mesh_x, CUFFT_TYPE_COMPLEX * mesh_y, CUFFT_TYPE_COMPLEX * mesh_z, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, float * lb_particle_force_gpu, REAL_TYPE prefactor, int n_part, int parts_per_block)
id of the particle
position relative to the closest gird point
index of the nearest mesh point
Definition at line 725 of file p3m_gpu_cuda.cu.
References atomicAdd(), REAL_TYPE, and wrap_index().
template<int cao> __global__ void assign_forces_kernel_shared (const CUDA_particle_data *const pdata, CUFFT_TYPE_COMPLEX * mesh_x, CUFFT_TYPE_COMPLEX * mesh_y, CUFFT_TYPE_COMPLEX * mesh_z, const int m_size, const REAL_TYPE pos_shift, const REAL_TYPE hi, float * lb_particle_force_gpu, REAL_TYPE prefactor, int n_part, int parts_per_block)
id of the particle
position relative to the closest gird point
index of the nearest mesh point
Definition at line 765 of file p3m_gpu_cuda.cu.
References atomicAdd(), REAL_TYPE, weights, and wrap_index().
template<int cao_value> __device__ REAL_TYPE caf (int i, REAL_TYPE x)
Definition at line 281 of file p3m_gpu_cuda.cu.
References SQR.
__global__ void calculate_influence_function_device (int cao, int mesh, REAL_TYPE box, REAL_TYPE alpha, REAL_TYPE * G_hat)
Definition at line 428 of file p3m_gpu_cuda.cu.
References Aliasing_sums_ik(), PI, REAL_TYPE, and SQR.
Referenced by p3m_gpu_init().
__host__ __device__ double csinc (double d) inline
Definition at line 67 of file p3m_gpu_cuda.cu.
References c2, c4, c6, c8, epsi, PI, and SQR.
Referenced by Aliasing_sums_ik().
void p3m_gpu_add_farfield_force ()
Definition at line 961 of file p3m_gpu_cuda.cu.
References apply_diff_op(), apply_influence_function(), assign_charges(), assign_forces(), dummytypename::box, dummytypename::cao, dummytypename::charge_mesh, coulomb, cuda_safe_mem, CUFFT_FFT, CUFFT_TYPE_COMPLEX, dummytypename::fft_plan, dummytypename::force_mesh_x, dummytypename::force_mesh_y, dummytypename::force_mesh_z, dummytypename::G_hat, gpu_get_global_particle_vars_pointer_host(), gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), KERNELCALL, KERNELCALL_shared, dummytypename::mesh, dummytypename::npart, p3m_gpu_data, Coulomb_parameters::prefactor, and REAL_TYPE.
Referenced by calc_long_range_forces().
void p3m_gpu_init (int cao, int mesh, REAL_TYPE alpha, REAL_TYPE box)
Definition at line 882 of file p3m_gpu_cuda.cu.
References dummytypename::alpha, block(), dummytypename::box, calculate_influence_function_device(), dummytypename::cao, dummytypename::charge_mesh, CUFFT_PLAN_FLAG, CUFFT_TYPE_COMPLEX, espressoSystemInterface, dummytypename::fft_plan, dummytypename::force_mesh_x, dummytypename::force_mesh_y, dummytypename::force_mesh_z, free, dummytypename::G_hat, dummytypename::G_hat_host, gpu_get_global_particle_vars_pointer_host(), KERNELCALL, malloc, dummytypename::mesh, dummytypename::npart, p3m_gpu_data, p3m_gpu_data_initialized, P3M_GPU_TRACE, REAL_TYPE, and this_node.
Referenced by on_coulomb_change().
__device__ int wrap_index (const int ind, const int mesh) inline
Definition at line 532 of file p3m_gpu_cuda.cu.
Referenced by assign_charge_kernel(), assign_charge_kernel< 1 >(), assign_charge_kernel_shared(), assign_forces_kernel(), and assign_forces_kernel_shared().
Variable Documentation
struct dummytypename p3m_gpu_data
Referenced by p3m_gpu_add_farfield_force(), and p3m_gpu_init().
char p3m_gpu_data_initialized = 0 static
Definition at line 61 of file p3m_gpu_cuda.cu.
Referenced by p3m_gpu_init().
__shared__ float weights[]
Referenced by apply_diff_op(), assign_charge_kernel_shared(), assign_forces_kernel_shared(), and tclcommand_analyze_parse_g_av().