ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: p3m_gpu.hpp File Reference
p3m_gpu.hpp File Reference
Macros
#define _P3M_GPU_FLOAT
#define REAL_TYPE float
#define CUFFT_TYPE_COMPLEX cufftComplex
#define CUFFT_FFT cufftExecC2C
#define CUFFT_PLAN_FLAG CUFFT_C2C
Functions
void p3m_gpu_init (int cao, int mesh, REAL_TYPE alpha, REAL_TYPE box)
void p3m_gpu_add_farfield_force ()
Macro Definition Documentation
#define _P3M_GPU_FLOAT
Definition at line 23 of file p3m_gpu.hpp.
#define CUFFT_FFT cufftExecC2C
Definition at line 29 of file p3m_gpu.hpp.
Referenced by p3m_gpu_add_farfield_force().
#define CUFFT_PLAN_FLAG CUFFT_C2C
Definition at line 30 of file p3m_gpu.hpp.
Referenced by p3m_gpu_init().
#define CUFFT_TYPE_COMPLEX cufftComplex
Definition at line 28 of file p3m_gpu.hpp.
Referenced by apply_diff_op(), p3m_gpu_add_farfield_force(), and p3m_gpu_init().
#define REAL_TYPE float
Definition at line 27 of file p3m_gpu.hpp.
Referenced by Aliasing_sums_ik(), assign_charge_kernel(), assign_charge_kernel< 1 >(), assign_charge_kernel_shared(), assign_forces_kernel(), assign_forces_kernel_shared(), calculate_influence_function_device(), p3m_gpu_add_farfield_force(), and p3m_gpu_init().
Function Documentation
void p3m_gpu_add_farfield_force ()
Definition at line 961 of file p3m_gpu_cuda.cu.
References apply_diff_op(), apply_influence_function(), assign_charges(), assign_forces(), dummytypename::box, dummytypename::cao, dummytypename::charge_mesh, coulomb, cuda_safe_mem, CUFFT_FFT, CUFFT_TYPE_COMPLEX, dummytypename::fft_plan, dummytypename::force_mesh_x, dummytypename::force_mesh_y, dummytypename::force_mesh_z, dummytypename::G_hat, gpu_get_global_particle_vars_pointer_host(), gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), KERNELCALL, KERNELCALL_shared, dummytypename::mesh, dummytypename::npart, p3m_gpu_data, Coulomb_parameters::prefactor, and REAL_TYPE.
Referenced by calc_long_range_forces().
void p3m_gpu_init (int cao, int mesh, REAL_TYPE alpha, REAL_TYPE box)
Definition at line 882 of file p3m_gpu_cuda.cu.
References dummytypename::alpha, block(), dummytypename::box, calculate_influence_function_device(), dummytypename::cao, dummytypename::charge_mesh, CUFFT_PLAN_FLAG, CUFFT_TYPE_COMPLEX, espressoSystemInterface, dummytypename::fft_plan, dummytypename::force_mesh_x, dummytypename::force_mesh_y, dummytypename::force_mesh_z, free, dummytypename::G_hat, dummytypename::G_hat_host, gpu_get_global_particle_vars_pointer_host(), KERNELCALL, malloc, dummytypename::mesh, dummytypename::npart, p3m_gpu_data, p3m_gpu_data_initialized, P3M_GPU_TRACE, REAL_TYPE, and this_node.
Referenced by on_coulomb_change().