ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: parser.cpp File Reference
parser.cpp File Reference
Implementation of parser.h.
#include "utils.hpp"
#include "parser.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include <list>
#include <string>
Functions
int parse_int_list (Tcl_Interp *interp, char *list, IntList *il)
parse an integer list
int parse_double_list (Tcl_Interp *interp, char *list, DoubleList *dl)
parse an double list
int gather_runtime_errors (Tcl_Interp *interp, int error_code)
gather all error messages from all nodes and set the interpreter result to these error messages.
Detailed Description
Implementation of parser.h.
parse_int_list is too long for inlining.
Definition in file parser.cpp.
Function Documentation
int gather_runtime_errors (Tcl_Interp * interp, int ret_state)
gather all error messages from all nodes and set the interpreter result to these error messages.
This should be called only on the master node.
The errors are append to the result, if ret_state == TCL_ERROR, otherwise the result is overwritten, in case an error occurs. Therefore you should end any Tcl command handler by return gather_runtime_errors(<return_value>). This code uses asynchronous communication.
Parameters
ret_state return value of the procedure
interp where to put the errors
Returns
new return value after the background errors, if any, have been handled
Definition at line 62 of file parser.cpp.
References mpiRuntimeErrorCollectorGather().
Referenced by tclcommand_analyze(), tclcommand_blockfile(), tclcommand_cellsystem(), tclcommand_change_volume(), tclcommand_constraint(), tclcommand_counterions(), tclcommand_crosslink(), tclcommand_diamond(), tclcommand_electrokinetics(), tclcommand_external_potential_tabulated(), tclcommand_icosaeder(), tclcommand_integrate(), tclcommand_integrate_sd(), tclcommand_inter(), tclcommand_inter_coulomb_parse_mmm1d(), tclcommand_lbboundary(), tclcommand_lbfluid(), tclcommand_lees_edwards_offset(), tclcommand_maxwell_velocities(), tclcommand_metadynamics(), tclcommand_nemd(), tclcommand_part_parse_cmd(), tclcommand_salt(), tclcommand_setmd(), tclcommand_thermostat(), and tclcommand_velocities().
int parse_double_list (Tcl_Interp * interp, char * list, DoubleList * dl)
parse an double list
Parameters
interp for conversion of backslash stuff
list the string containing the list
dl where to store the results
Definition at line 48 of file parser.cpp.
References DoubleList::e, i, DoubleList::n, and realloc_doublelist().
int parse_int_list (Tcl_Interp * interp, char * list, IntList * il)
parse an integer list
Parameters
interp for conversion of backslash stuff
list the string containing the list
il where to store the results
Definition at line 34 of file parser.cpp.
References IntList::e, i, IntList::n, and realloc_intlist().
Referenced by parse_id_list().