ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: particle_data_tcl.cpp File Reference
particle_data_tcl.cpp File Reference
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <mpi.h>
#include "utils.hpp"
#include "particle_data.hpp"
#include "global.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "interaction_data.hpp"
#include "integrate.hpp"
#include "cells.hpp"
#include "parser.hpp"
#include "rotation.hpp"
#include "virtual_sites.hpp"
Functions
void add_link (IntList *il, IntList *link, int l, int p, int size)
void tclcommand_part_print_gamma (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_T (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_rotational_inertia (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_omega_body_frame (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_torque_body_frame (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_omega_lab_frame (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_torque_lab_frame (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_v_body (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_quat (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_quatu (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_swimming (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_dip (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_rotation (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_smaller_timestep (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_v (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_mu_E (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_solvation (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_composition (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_f (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_position (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_folded_position (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_bonding_structure (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_bond_partners (Particle *part, char *buffer, Tcl_Interp *interp, int distance)
Return all bond partners of a particle including bonds that are not stored at the particle itself up to a certain distance in numbers of bonds.
void tclcommand_part_print_exclusions (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_fix (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_ext_force (Particle *part, char *buffer, Tcl_Interp *interp)
void tclcommand_part_print_ext_torque (Particle *part, char *buffer, Tcl_Interp *interp)
int tclprint_to_result_Particle (Tcl_Interp *interp, int part_num)
append particle data in ASCII form to the Tcl result.
int tclcommand_part_print_all (Tcl_Interp *interp)
int tclcommand_part_parse_print (Tcl_Interp *interp, int argc, char **argv, int part_num)
int tclcommand_part_parse_delete (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_pos (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_solvation (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_mass (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_rotation (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_rotational_inertia (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_dipm (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_dip (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int part_parse_vs_relative (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int part_parse_vs_relate_to (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_smaller_timestep (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_q (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_mu_E (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_v (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_f (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_type (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_mol_id (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_swimming (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_quat (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_omega_body (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_omega_lab (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_torque_body (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_torque_lab (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_ext_torque (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_ext_force (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_fix (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_unfix (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int part_parse_temp (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int part_parse_gamma (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int part_parse_gc (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_part_parse_bond (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_exclusion (Tcl_Interp *interp, int argc, char **argv, int part_num, int *change)
int tclcommand_part_parse_cmd (Tcl_Interp *interp, int argc, char **argv, int part_num)
int tclcommand_part (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl command "part".
Function Documentation
void add_link (IntList * il, IntList * link, int l, int p, int size)
Definition at line 39 of file particle_data_tcl.cpp.
References IntList::e, i, IntList::n, and realloc_intlist().
Referenced by tclcommand_part_print_bond_partners().
int part_parse_gamma (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1869 of file particle_data_tcl.cpp.
References ARG_IS_D, and set_particle_gamma().
Referenced by tclcommand_part_parse_cmd().
int part_parse_gc (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1894 of file particle_data_tcl.cpp.
References ARG0_IS_S, ARG_IS_I, delete_particle_of_type(), ES_ERROR, find_particle_type(), i, TypeList::id_list, Index, TypeOfIndex::index, init_type_array(), TypeOfIndex::max_entry, TypeList::max_entry, NOT_INDEXED, number_of_particles_with_type(), Type, IndexOfType::type, type_array, and Type_array_init.
Referenced by tclcommand_part(), and tclcommand_part_parse_cmd().
int part_parse_temp (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1846 of file particle_data_tcl.cpp.
References ARG_IS_D, and set_particle_temperature().
Referenced by tclcommand_part_parse_cmd().
int part_parse_vs_relate_to (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1196 of file particle_data_tcl.cpp.
References ARG0_IS_I, and vs_relate_to().
Referenced by tclcommand_part_parse_cmd().
int part_parse_vs_relative (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1158 of file particle_data_tcl.cpp.
References ARG0_IS_I, ARG1_IS_D, and set_particle_vs_relative().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl command "part".
This command allows to modify particle data. See particle_data_tcl.cpp
Definition at line 2503 of file particle_data_tcl.cpp.
References ARG1_IS_I, ARG1_IS_S, ARG_IS_I, auto_exclusion(), part_parse_gc(), remove_all_exclusions(), remove_all_particles(), tclcommand_part_parse_cmd(), tclcommand_part_print_all(), and tclprint_to_result_Particle().
Referenced by tcl_register_commands().
int tclcommand_part_parse_bond (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 2052 of file particle_data_tcl.cpp.
References ARG0_IS_I, ARG0_IS_S, ARG_IS_I, bonded_ia_params, build_particle_node(), change_particle_bond(), ES_OK, free, malloc, max_seen_particle, n_bonded_ia, Bonded_ia_parameters::num, and particle_node.
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_cmd (Tcl_Interp * interp, int argc, char ** argv, int part_num)
Definition at line 2274 of file particle_data_tcl.cpp.
References ARG0_IS_S, ARG0_IS_S_EXACT, build_particle_node(), CHECK_PARTICLES, err, gather_runtime_errors(), mpi_bcast_event(), part_parse_gamma(), part_parse_gc(), part_parse_temp(), part_parse_vs_relate_to(), part_parse_vs_relative(), particle_node, tclcommand_part_parse_bond(), tclcommand_part_parse_delete(), tclcommand_part_parse_dip(), tclcommand_part_parse_dipm(), tclcommand_part_parse_exclusion(), tclcommand_part_parse_ext_force(), tclcommand_part_parse_ext_torque(), tclcommand_part_parse_f(), tclcommand_part_parse_fix(), tclcommand_part_parse_mass(), tclcommand_part_parse_mol_id(), tclcommand_part_parse_mu_E(), tclcommand_part_parse_omega_body(), tclcommand_part_parse_omega_lab(), tclcommand_part_parse_pos(), tclcommand_part_parse_print(), tclcommand_part_parse_q(), tclcommand_part_parse_quat(), tclcommand_part_parse_rotation(), tclcommand_part_parse_rotational_inertia(), tclcommand_part_parse_smaller_timestep(), tclcommand_part_parse_solvation(), tclcommand_part_parse_swimming(), tclcommand_part_parse_torque_body(), tclcommand_part_parse_torque_lab(), tclcommand_part_parse_type(), tclcommand_part_parse_unfix(), and tclcommand_part_parse_v().
Referenced by tclcommand_part().
int tclcommand_part_parse_delete (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 900 of file particle_data_tcl.cpp.
References remove_particle().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_dip (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1091 of file particle_data_tcl.cpp.
References ARG_IS_D, ROUND_ERROR_PREC, and set_particle_dip().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_dipm (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1066 of file particle_data_tcl.cpp.
References ARG0_IS_D, and set_particle_dipm().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_exclusion (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 2218 of file particle_data_tcl.cpp.
References ARG0_IS_I, ARG0_IS_S, build_particle_node(), change_exclusion(), and particle_node.
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_ext_force (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1754 of file particle_data_tcl.cpp.
References ARG_IS_D, PARTICLE_EXT_FORCE, and set_particle_ext_force().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_ext_torque (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1718 of file particle_data_tcl.cpp.
References ARG_IS_D, PARTICLE_EXT_TORQUE, and set_particle_ext_torque().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_f (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Todo:
{scale with particle mass}
Definition at line 1369 of file particle_data_tcl.cpp.
References ARG_IS_D, set_particle_f(), and time_step.
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_fix (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1789 of file particle_data_tcl.cpp.
References ARG_IS_I, COORD_FIXED, i, and set_particle_fix().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_mass (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 984 of file particle_data_tcl.cpp.
References ARG0_IS_D, and set_particle_mass().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_mol_id (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1436 of file particle_data_tcl.cpp.
References ARG0_IS_I, ARG0_IS_S, and set_particle_mol_id().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_mu_E (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1302 of file particle_data_tcl.cpp.
References ARG_IS_D, and set_particle_mu_E().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_omega_body (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1592 of file particle_data_tcl.cpp.
References ARG_IS_D, and set_particle_omega_body().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_omega_lab (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1623 of file particle_data_tcl.cpp.
References ARG_IS_D, and set_particle_omega_lab().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_pos (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 923 of file particle_data_tcl.cpp.
References ARG_IS_D, ES_PART_ERROR, and place_particle().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_print (Tcl_Interp * interp, int argc, char ** argv, int part_num)
Definition at line 711 of file particle_data_tcl.cpp.
References ARG0_IS_S, ARG0_IS_S_EXACT, ARG1_IS_I, ARG_IS_S_EXACT, distance(), free_particle(), get_particle_data(), max_seen_particle, tclcommand_part_print_bond_partners(), tclcommand_part_print_bonding_structure(), tclcommand_part_print_composition(), tclcommand_part_print_dip(), tclcommand_part_print_exclusions(), tclcommand_part_print_ext_force(), tclcommand_part_print_ext_torque(), tclcommand_part_print_f(), tclcommand_part_print_fix(), tclcommand_part_print_folded_position(), tclcommand_part_print_gamma(), tclcommand_part_print_mu_E(), tclcommand_part_print_omega_body_frame(), tclcommand_part_print_omega_lab_frame(), tclcommand_part_print_position(), tclcommand_part_print_quat(), tclcommand_part_print_quatu(), tclcommand_part_print_rotation(), tclcommand_part_print_rotational_inertia(), tclcommand_part_print_smaller_timestep(), tclcommand_part_print_solvation(), tclcommand_part_print_swimming(), tclcommand_part_print_T(), tclcommand_part_print_torque_body_frame(), tclcommand_part_print_torque_lab_frame(), tclcommand_part_print_v(), and tclcommand_part_print_v_body().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_q (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1276 of file particle_data_tcl.cpp.
References ARG0_IS_D, and set_particle_q().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_quat (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1553 of file particle_data_tcl.cpp.
References ARG_IS_D, and set_particle_quat().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_rotation (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1011 of file particle_data_tcl.cpp.
References ARG0_IS_I, and set_particle_rotation().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_rotational_inertia (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1039 of file particle_data_tcl.cpp.
References ARG_IS_D, and set_particle_rotational_inertia().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_smaller_timestep (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1221 of file particle_data_tcl.cpp.
References ARG0_IS_I, and set_particle_smaller_timestep().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_solvation (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 952 of file particle_data_tcl.cpp.
References ARG_IS_D, LB_COMPONENTS, and set_particle_solvation().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_swimming (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1470 of file particle_data_tcl.cpp.
References ARG_IS_D, ARG_IS_S, ParticleParametersSwimming::dipole_length, err, ParticleParametersSwimming::f_swim, get_particle_data(), ParticleParametersSwimming::push_pull, ParticleParametersSwimming::rotational_friction, set_particle_swimming(), Particle::swim, ParticleParametersSwimming::swimming, and ParticleParametersSwimming::v_swim.
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_torque_body (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1654 of file particle_data_tcl.cpp.
References ARG_IS_D, and set_particle_torque_body().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_torque_lab (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1685 of file particle_data_tcl.cpp.
References ARG_IS_D, and set_particle_torque_lab().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_type (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1407 of file particle_data_tcl.cpp.
References ARG0_IS_I, and set_particle_type().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_unfix (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1829 of file particle_data_tcl.cpp.
References set_particle_fix().
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_parse_v (Tcl_Interp * interp, int argc, char ** argv, int part_num, int * change)
Definition at line 1332 of file particle_data_tcl.cpp.
References ARG_IS_D, set_particle_v(), and time_step.
Referenced by tclcommand_part_parse_cmd().
int tclcommand_part_print_all (Tcl_Interp * interp)
Definition at line 682 of file particle_data_tcl.cpp.
References build_particle_node(), i, max_seen_particle, PART_TRACE, particle_node, start, and tclprint_to_result_Particle().
Referenced by tclcommand_part().
void tclcommand_part_print_bond_partners (Particle * part, char * buffer, Tcl_Interp * interp, int distance)
Return all bond partners of a particle including bonds that are not stored at the particle itself up to a certain distance in numbers of bonds.
Return a tcl list to the interpreter c
Definition at line 370 of file particle_data_tcl.cpp.
References add_link(), add_partner(), Particle::bl, bonded_ia_params, distance(), IntList::e, free, i, ia_params, ParticleProperties::identity, init_intlist(), malloc, max_seen_particle, IntList::n, n_part, Bonded_ia_parameters::num, Particle::p, partCfg, realloc_intlist(), updatePartCfg(), and WITH_BONDS.
Referenced by tclcommand_part_parse_print().
void tclcommand_part_print_bonding_structure (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 348 of file particle_data_tcl.cpp.
References Particle::bl, bonded_ia_params, IntList::e, i, and Bonded_ia_parameters::num.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_composition (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 282 of file particle_data_tcl.cpp.
References ParticlePosition::composition, LB_COMPONENTS, and Particle::r.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_dip (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 192 of file particle_data_tcl.cpp.
References ParticlePosition::dip, and Particle::r.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_exclusions (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 449 of file particle_data_tcl.cpp.
References IntList::e, Particle::el, i, and IntList::n.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_ext_force (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 471 of file particle_data_tcl.cpp.
References ParticleProperties::ext_flag, ParticleProperties::ext_force, Particle::p, and PARTICLE_EXT_FORCE.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_ext_torque (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 487 of file particle_data_tcl.cpp.
References ParticleProperties::ext_flag, ParticleProperties::ext_torque, Particle::p, and PARTICLE_EXT_TORQUE.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_f (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 293 of file particle_data_tcl.cpp.
References ParticleForce::f, Particle::f, PMASS, and time_step.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_fix (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 460 of file particle_data_tcl.cpp.
References COORD_FIXED, ParticleProperties::ext_flag, i, and Particle::p.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_folded_position (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 321 of file particle_data_tcl.cpp.
References fold_position(), ParticleLocal::i, Particle::l, Particle::m, ParticlePosition::p, Particle::r, and ParticleMomentum::v.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_gamma (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 50 of file particle_data_tcl.cpp.
References ParticleProperties::gamma, and Particle::p.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_mu_E (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 259 of file particle_data_tcl.cpp.
References ParticleProperties::mu_E, and Particle::p.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_omega_body_frame (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 83 of file particle_data_tcl.cpp.
References Particle::m, and ParticleMomentum::omega.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_omega_lab_frame (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 106 of file particle_data_tcl.cpp.
References convert_omega_body_to_space().
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_position (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 304 of file particle_data_tcl.cpp.
References ParticleLocal::i, Particle::l, ParticlePosition::p, Particle::r, and unfold_position().
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_quat (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 150 of file particle_data_tcl.cpp.
References ParticlePosition::quat, and Particle::r.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_quatu (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 162 of file particle_data_tcl.cpp.
References ParticlePosition::quatu, and Particle::r.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_rotation (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 212 of file particle_data_tcl.cpp.
References Particle::p, and ParticleProperties::rotation.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_rotational_inertia (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 62 of file particle_data_tcl.cpp.
References Particle::p, and ParticleProperties::rinertia.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_smaller_timestep (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 220 of file particle_data_tcl.cpp.
References Particle::p, and ParticleProperties::smaller_timestep.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_solvation (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 272 of file particle_data_tcl.cpp.
References LB_COMPONENTS, Particle::p, and ParticleProperties::solvation.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_swimming (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 174 of file particle_data_tcl.cpp.
References ParticleParametersSwimming::dipole_length, ParticleParametersSwimming::f_swim, ParticleParametersSwimming::push_pull, ParticleParametersSwimming::rotational_friction, Particle::swim, ParticleParametersSwimming::swimming, and ParticleParametersSwimming::v_swim.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_T (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 55 of file particle_data_tcl.cpp.
References Particle::p, and ParticleProperties::T.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_torque_body_frame (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 93 of file particle_data_tcl.cpp.
References Particle::f, and ParticleForce::torque.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_torque_lab_frame (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 120 of file particle_data_tcl.cpp.
References convert_torques_body_to_space().
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_v (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 235 of file particle_data_tcl.cpp.
References Particle::m, Particle::p, smaller_time_step, ParticleProperties::smaller_timestep, time_step, and ParticleMomentum::v.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
void tclcommand_part_print_v_body (Particle * part, char * buffer, Tcl_Interp * interp)
Definition at line 135 of file particle_data_tcl.cpp.
References convert_vel_space_to_body(), and time_step.
Referenced by tclcommand_part_parse_print(), and tclprint_to_result_Particle().
int tclprint_to_result_Particle (Tcl_Interp * interp, int part_num)
append particle data in ASCII form to the Tcl result.
Parameters
part_num the particle which data is appended
interp the Tcl interpreter to which result to add to
Definition at line 507 of file particle_data_tcl.cpp.
References Particle::bl, COORDS_FIX_MASK, ParticleProperties::dipm, Particle::el, ParticleProperties::ext_flag, free_particle(), get_particle_data(), ParticleProperties::identity, ParticleProperties::mass, ParticleProperties::mol_id, IntList::n, Particle::p, PARTICLE_EXT_FORCE, PARTICLE_EXT_TORQUE, ParticleProperties::q, tclcommand_part_print_bonding_structure(), tclcommand_part_print_composition(), tclcommand_part_print_dip(), tclcommand_part_print_exclusions(), tclcommand_part_print_ext_force(), tclcommand_part_print_ext_torque(), tclcommand_part_print_f(), tclcommand_part_print_fix(), tclcommand_part_print_folded_position(), tclcommand_part_print_gamma(), tclcommand_part_print_mu_E(), tclcommand_part_print_omega_body_frame(), tclcommand_part_print_omega_lab_frame(), tclcommand_part_print_position(), tclcommand_part_print_quat(), tclcommand_part_print_quatu(), tclcommand_part_print_rotation(), tclcommand_part_print_rotational_inertia(), tclcommand_part_print_smaller_timestep(), tclcommand_part_print_solvation(), tclcommand_part_print_swimming(), tclcommand_part_print_T(), tclcommand_part_print_torque_body_frame(), tclcommand_part_print_torque_lab_frame(), tclcommand_part_print_v(), tclcommand_part_print_v_body(), ParticleProperties::type, ParticleProperties::vs_relative_distance, and ParticleProperties::vs_relative_to_particle_id.
Referenced by tclcommand_part(), and tclcommand_part_print_all().