ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: polymer.hpp File Reference
polymer.hpp File Reference
This file contains everything needed to create a start-up configuration of (partially charged) polymer chains with counterions and salt molecules, assigning velocities to the particles and crosslinking the polymers if necessary.
#include "particle_data.hpp"
Functions
double mindist4 (double pos[3])
C implementation of 'mindist <posx> <posy> <posz>',
which returns the minimum distance of all current particles to position (<posx>, <posy>, <posz>) as a double.
int mindist3 (int part_id, double r_catch, int *ids)
C implementation of 'mindist <part_id> <r_catch>',
which returns the size of an array <ids> of indices of particles which are less than <r_catch> away from the position of the particle <part_id>.
int collision (double pos[3], double shield, int n_add, double *add)
Checks whether a particle at coordinates (<posx>, <posy>, <posz>) collides with any other particle due to a minimum image distance smaller than <shield>.
int constraint_collision (double *p1, double *p2)
Function used by polymerC to determine wether a constraint has been violated while setting up a polymer.
int polymerC (int N_P, int MPC, double bond_length, int part_id, double *posed, int mode, double shield, int max_try, double val_cM, int cM_dist, int type_nM, int type_cM, int type_FENE, double angle, double angle2, double *posed2, int constr)
C implementation of 'polymer <N_P> <MPC> <bond_length> [options]', which returns how often the attempt to place a monomer failed in the worst case.
int counterionsC (int N_CI, int part_id, int mode, double shield, int max_try, double val_CI, int type_CI)
C implementation of 'counterions <N_CI> [options]'.
int saltC (int N_pS, int N_nS, int part_id, int mode, double shield, int max_try, double val_pS, double val_nS, int type_pS, int type_nS, double rad)
C implementation of 'salt <N_pS> <N_nS> [options]',.
double velocitiesC (double v_max, int part_id, int N_T)
C implementation of 'velocities <v_max> [options]',.
double maxwell_velocitiesC (int part_id, int N_T)
C implementation of 'maxwell_velocities [options]',.
int collectBonds (int mode, int part_id, int N_P, int MPC, int type_bond, int **bond_out, int ***bonds_out)
Collects the bonds leading to and from the ending monomers of the chains (mode == 1) or all the bonds leading to and from each monomer (mode == 2).
int crosslinkC (int N_P, int MPC, int part_id, double r_catch, int link_dist, int chain_dist, int type_FENE, int max_try)
C implementation of 'crosslink <N_P> <MPC> [options]',.
int diamondC (double a, double bond_length, int MPC, int N_CI, double val_nodes, double val_cM, double val_CI, int cM_dist, int nonet)
C implementation of 'diamond <a> <bond_length> <MPC> [options]'.
int icosaederC (double ico_a, int MPC, int N_CI, double val_cM, double val_CI, int cM_dist)
C implementation of 'icosaeder <a> <bond_length> <MPC> [options]'.
Detailed Description
This file contains everything needed to create a start-up configuration of (partially charged) polymer chains with counterions and salt molecules, assigning velocities to the particles and crosslinking the polymers if necessary.
For more information on polymer, see polymer.c
Definition in file polymer.hpp.
Function Documentation
int collectBonds (int mode, int part_id, int N_P, int MPC, int type_bond, int ** bond_out, int *** bonds_out)
Collects the bonds leading to and from the ending monomers of the chains (mode == 1) or all the bonds leading to and from each monomer (mode == 2).
Returns
Returns '0' upon success, '-2' otherwise.
Definition at line 545 of file polymer.cpp.
References Particle::bl, bonded_ia_params, IntList::e, free, i, ParticleProperties::identity, malloc, mpi_get_particles(), IntList::n, n_part, Bonded_ia_parameters::num, Particle::p, POLY_TRACE, realloc, and realloc_intlist().
Referenced by crosslinkC().
int collision (double pos[3], double shield, int n_add, double * add)
Checks whether a particle at coordinates (<posx>, <posy>, <posz>) collides with any other particle due to a minimum image distance smaller than <shield>.
Parameters
pos coordinates of particle to check
shield minimum distance before it is defined as collision
n_add number of additional coordinates to check
add additional coordinates to check
Returns
Returns '1' if there is a collision, '0' otherwise.
Definition at line 123 of file polymer.cpp.
References buf_mindist4(), and mindist4().
Referenced by counterionsC(), polymerC(), and saltC().
int constraint_collision (double * p1, double * p2)
Function used by polymerC to determine wether a constraint has been violated while setting up a polymer.
Currently only "wall", "sphere" and "cylinder" constraints are respected.
Parameters
p1 = position of first particle given as double-array of lenght 3
p2 = position of second particle given as double-array of length 3
Returns
Returns 1 if p1 and p2 sit on opposite sites of any constraint currently defined in the system and 0 otherwise
Definition at line 130 of file polymer.cpp.
References Constraint::c, calculate_cylinder_dist(), calculate_sphere_dist(), calculate_wall_dist(), CONSTRAINT_CYL, CONSTRAINT_SPH, CONSTRAINT_WAL, constraints, Constraint::cyl, fold_position(), i, n_constraints, Constraint::sph, Constraint::type, Constraint::wal, and warnings.
Referenced by polymerC().
int counterionsC (int N_CI, int part_id, int mode, double shield, int max_try, double val_CI, int type_CI)
C implementation of 'counterions <N_CI> [options]'.
Parameters
N_CI = number of counterions to create
part_id = particle number of the first counterion (defaults to 'n_total_particles')
mode = selects setup mode: Self avoiding walk (SAW) or plain random walk (RW) (defaults to 'SAW')
shield = shield around each particle another particle's position may not enter if using SAW (defaults to '0.0')
max_try = how often a monomer should be reset if current position collides with a previous particle (defaults to '30000')
val_CI = valency of the counterions (defaults to '-1.0')
type_CI = type number of the counterions to be used with "part" (default to '2')
Returns
Returns how often the attempt to place a particle failed in the worst case.
Definition at line 395 of file polymer.cpp.
References box_l, collision(), d_random(), ES_ERROR, ES_PART_ERROR, imax(), place_particle(), POLY_TRACE, set_particle_q(), and set_particle_type().
Referenced by diamondC(), icosaederC(), and tclcommand_counterions().
int crosslinkC (int N_P, int MPC, int part_id, double r_catch, int link_dist, int chain_dist, int type_FENE, int max_try)
C implementation of 'crosslink <N_P> <MPC> [options]',.
Parameters
N_P = number of polymer chains
MPC = monomers per chain
part_id = particle number of the start monomer (defaults to '0')
r_catch = maximum length of a crosslink (defaults to '1.9')
link_dist = minimum distance between the indices of two crosslinked monomers with different binding partners (defaults to '2')
chain_dist = same as <link_dist>, but for monomers of the same bond (defaults to <MPC> => no bonds to the same chain allowed)
type_FENE = type number of the FENE-typed bonded interaction bonds to be set between the monomers (defaults to '0')
max_try = how often crosslinks should be removed if they are too close to other links (defaults to '30000')
Returns
Returns how many ends are now successfully linked.
Definition at line 634 of file polymer.cpp.
References change_particle_bond(), collectBonds(), cross(), d_random(), dround(), ES_ERROR, free, i, malloc, mindist3(), n_part, POLY_TRACE, and realloc.
Referenced by tclcommand_crosslink().
int diamondC (double a, double bond_length, int MPC, int N_CI, double val_nodes, double val_cM, double val_CI, int cM_dist, int nonet)
C implementation of 'diamond <a> <bond_length> <MPC> [options]'.
Definition at line 747 of file polymer.cpp.
References change_particle_bond(), counterionsC(), ES_ERROR, ES_PART_ERROR, i, place_particle(), set_particle_q(), and set_particle_type().
Referenced by tclcommand_diamond().
int icosaederC (double ico_a, int MPC, int N_CI, double val_cM, double val_CI, int cM_dist)
C implementation of 'icosaeder <a> <bond_length> <MPC> [options]'.
Definition at line 794 of file polymer.cpp.
References change_particle_bond(), counterionsC(), errexit(), ES_ERROR, ES_PART_ERROR, i, place_particle(), set_particle_q(), set_particle_type(), and SQR().
Referenced by tclcommand_icosaeder().
double maxwell_velocitiesC (int part_id, int N_T)
C implementation of 'maxwell_velocities [options]',.
Parameters
part_id = particle number of the first of the <N_T> particles (defaults to '0')
N_T = number of particles of which the velocities should be set (defaults to 'n_total_particles - part_id')
Returns
Returns the averaged velocity when done.
Definition at line 511 of file polymer.cpp.
References d_random(), errexit(), ES_ERROR, i, PI, set_particle_v(), SQR(), and time_step.
Referenced by tclcommand_maxwell_velocities().
int mindist3 (int part_id, double r_catch, int * ids)
C implementation of 'mindist <part_id> <r_catch>',
which returns the size of an array <ids> of indices of particles which are less than <r_catch> away from the position of the particle <part_id>.
Definition at line 56 of file polymer.cpp.
References box_l, dround(), free, i, ParticleProperties::identity, malloc, mpi_get_particles(), n_part, ParticlePosition::p, Particle::p, Particle::r, runtimeError, and SQR().
Referenced by crosslinkC().
double mindist4 (double pos[3])
C implementation of 'mindist <posx> <posy> <posz>',
which returns the minimum distance of all current particles to position (<posx>, <posy>, <posz>) as a double.
If it fails, return value equals -1.
Definition at line 86 of file polymer.cpp.
References box_l, dmin(), dround(), free, i, malloc, mindist(), mpi_get_particles(), n_part, ParticlePosition::p, Particle::r, and SQR().
Referenced by collision().
int polymerC (int N_P, int MPC, double bond_length, int part_id, double * posed, int mode, double shield, int max_try, double val_cM, int cM_dist, int type_nM, int type_cM, int type_FENE, double angle, double angle2, double * posed2, int constr)
C implementation of 'polymer <N_P> <MPC> <bond_length> [options]', which returns how often the attempt to place a monomer failed in the worst case.
Parameters
N_P = how many polymers to create
MPC = monomers per chain
bond_length = length of the bonds between two monomers
part_id = particle number of the start monomer (defaults to '0')
posed = sets the position of the start monomer of the first chain (defaults to a randomly chosen value)
mode = selects setup mode: (Pseudo) self avoiding walk ([P]SAW) or plain random walk (RW) (defaults to 'SAW')
shield = shield around each particle another particle's position may not enter if using SAW (defaults to '0.0')
max_try = how often a monomer should be reset if current position collides with a previous particle (defaults to '30000')
val_cM = valency of charged monomers (defaults to '0.0')
cM_dist = distance between two charged monomers' indices (defaults to '1')
type_nM = type number of neutral monomers (defaults to '0')
type_cM = type number of charged monomers (default to '1')
type_FENE = type number of the FENE-typed bonded interaction bonds to be set between the monomers (defaults to '0')
angle = desired bond-angle to be fixed
angle2 = secon spherical bond-angle
posed2 = sets the position of the 2nd monomer of the first chain
constr = shall constraints be respected when setting up polymer? (0=no, 1=yes, default: 0)
Returns
Returns how often the attempt to place a monomer failed in the worst case.
If val_cM < 1e-10, the charge is assumed to be zero, and type_cM = type_nM.
Definition at line 176 of file polymer.cpp.
References bonded_ia_params, box_l, change_particle_bond(), collision(), constraint_collision(), d_random(), ES_ERROR, ES_PART_ERROR, free, i, imax(), malloc, Bonded_ia_parameters::num, PI, place_particle(), POLY_TRACE, ROUND_ERROR_PREC, set_particle_q(), set_particle_type(), SQR(), sqrlen(), vec_rotate(), and vector_product().
int saltC (int N_pS, int N_nS, int part_id, int mode, double shield, int max_try, double val_pS, double val_nS, int type_pS, int type_nS, double rad)
C implementation of 'salt <N_pS> <N_nS> [options]',.
Parameters
N_pS = number of positive salt ions to create
N_nS = number of negative salt ions to create
part_id = particle number of the first salt ion (defaults to 'n_total_particles')
mode = selects setup mode: Self avoiding walk (SAW) or plain random walk (RW) (defaults to 'SAW')
shield = shield around each particle another particle's position may not enter if using SAW (defaults to '0')
max_try = how often a monomer should be reset if current position collides with a previous particle (defaults to '30000')
val_pS = valency of the positive salt ions (defaults to '1')
val_nS = valencies of the negative salt ions (default to '-1')
type_pS = type numbers to be used for positive salt ions (defaults to '3')
type_nS = type numbers to be used for negative salt ions (defaults to '4')
rad = radius of the sphere for the cell model. If value is >0 the ions are distributed in a sphere centered in the simulation box.
Returns
Returns how often the attempt to place a particle failed in the worst case.
Definition at line 420 of file polymer.cpp.
References box_l, collision(), d_random(), ES_ERROR, ES_PART_ERROR, imax(), place_particle(), POLY_TRACE, set_particle_q(), and set_particle_type().
Referenced by tclcommand_salt().
double velocitiesC (double v_max, int part_id, int N_T)
C implementation of 'velocities <v_max> [options]',.
Parameters
v_max = maximum velocity to be used
part_id = particle number of the first of the <N_T> particles (defaults to '0')
N_T = number of particles of which the velocities should be set (defaults to 'n_total_particles - part_id')
Returns
Returns the averaged velocity when done.
Definition at line 488 of file polymer.cpp.
References d_random(), errexit(), ES_ERROR, i, set_particle_v(), SQR(), and time_step.
Referenced by tclcommand_velocities().