ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: pressure_tcl.cpp File Reference
pressure_tcl.cpp File Reference
#include "pressure.hpp"
#include "parser.hpp"
Functions
int tclcallback_npt_piston (Tcl_Interp *interp, void *_data)
Callback for setting nptiso_struct::piston.
int tclcallback_p_ext (Tcl_Interp *interp, void *_data)
Callback for setting nptiso_struct::p_ext.
int tclcallback_npt_p_diff (Tcl_Interp *interp, void *_data)
Callback for setting nptiso_struct::p_diff.
static void tclcommand_analyze_print_pressure_all (Tcl_Interp *interp)
int tclcommand_analyze_parse_and_print_pressure (Tcl_Interp *interp, int v_comp, int argc, char **argv)
implementation of 'analyze pressure'
int tclcommand_analyze_parse_and_print_p_IK1 (Tcl_Interp *interp, int argc, char **argv)
implementation of 'analyze p_IK1'
int tclcommand_analyze_parse_bins (Tcl_Interp *interp, int argc, char **argv)
Implementation of 'analyze bins'.
static void tclcommand_analyze_print_stress_tensor_all (Tcl_Interp *interp)
int tclcommand_analyze_parse_and_print_stress_tensor (Tcl_Interp *interp, int v_comp, int argc, char **argv)
implementation of 'analyze stress_tensor'
int tclcommand_analyze_parse_local_stress_tensor (Tcl_Interp *interp, int argc, char **argv)
implementation of 'analyse local_stress_tensor
Function Documentation
int tclcallback_npt_p_diff (Tcl_Interp * interp, void * _data)
Callback for setting nptiso_struct::p_diff.
Definition at line 46 of file pressure_tcl.cpp.
References FIELD_NPTISO_PDIFF, mpi_bcast_parameter(), nptiso, and nptiso_struct::p_diff.
Referenced by tcl_register_global_variables().
int tclcallback_npt_piston (Tcl_Interp * interp, void * _data)
Callback for setting nptiso_struct::piston.
Definition at line 31 of file pressure_tcl.cpp.
References FIELD_NPTISO_PISTON, mpi_bcast_parameter(), nptiso, and nptiso_struct::piston.
Referenced by tcl_register_global_variables(), and tclcommand_integrate_set_npt_isotropic().
int tclcallback_p_ext (Tcl_Interp * interp, void * _data)
Callback for setting nptiso_struct::p_ext.
Definition at line 39 of file pressure_tcl.cpp.
References FIELD_NPTISO_PEXT, mpi_bcast_parameter(), nptiso, and nptiso_struct::p_ext.
Referenced by tclcommand_integrate_set_npt_isotropic().
int tclcommand_analyze_parse_and_print_p_IK1 (Tcl_Interp * interp, int argc, char ** argv)
implementation of 'analyze p_IK1'
Definition at line 365 of file pressure_tcl.cpp.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_and_print_pressure (Tcl_Interp * interp, int v_comp, int argc, char ** argv)
implementation of 'analyze pressure'
Parameters
interp Tcl interpreter
argc arguments
argv arguments
v_comp flag which enables (1) compensation of the velocities required for deriving a pressure reflecting nptiso_struct::p_inst (hence it only works with domain decomposition); naturally it therefore doesn't make sense to use it without NpT.
Definition at line 198 of file pressure_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, ARG_IS_I, Observable_stat::coulomb, Observable_stat::data, nptiso_struct::dimension, DoubleList::e, nptiso_struct::geometry, i, init_p_tensor(), init_p_tensor_non_bonded(), Observable_stat::init_status, init_virials(), init_virials_non_bonded(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso_struct::invalidate_p_vel, master_pressure_calc(), MPI_COMM_WORLD, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, DoubleList::n, n_bonded_ia, Observable_stat::n_coulomb, n_part, n_particle_types, nptiso_struct::nptgeom_dir, nptiso, obsstat_bonded(), obsstat_nonbonded(), obsstat_nonbonded_inter(), obsstat_nonbonded_intra(), nptiso_struct::p_vel, tclcommand_analyze_print_pressure_all(), total_p_tensor, total_p_tensor_non_bonded, total_pressure, total_pressure_non_bonded, nptiso_struct::volume, and Observable_stat::vs_relative.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_and_print_stress_tensor (Tcl_Interp * interp, int v_comp, int argc, char ** argv)
implementation of 'analyze stress_tensor'
Definition at line 517 of file pressure_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, ARG_IS_I, Observable_stat::coulomb, Observable_stat::data, nptiso_struct::dimension, DoubleList::e, nptiso_struct::geometry, i, init_p_tensor(), init_p_tensor_non_bonded(), Observable_stat::init_status, init_virials(), init_virials_non_bonded(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso_struct::invalidate_p_vel, master_pressure_calc(), MPI_COMM_WORLD, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, DoubleList::n, n_bonded_ia, n_part, n_particle_types, nptiso_struct::nptgeom_dir, nptiso, obsstat_bonded(), obsstat_nonbonded(), obsstat_nonbonded_inter(), obsstat_nonbonded_intra(), p_tensor, nptiso_struct::p_vel, tclcommand_analyze_print_stress_tensor_all(), total_p_tensor, total_p_tensor_non_bonded, total_pressure, total_pressure_non_bonded, nptiso_struct::volume, and Observable_stat::vs_relative.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_bins (Tcl_Interp * interp, int argc, char ** argv)
Implementation of 'analyze bins'.
Definition at line 371 of file pressure_tcl.cpp.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_local_stress_tensor (Tcl_Interp * interp, int argc, char ** argv)
implementation of 'analyse local_stress_tensor
Definition at line 685 of file pressure_tcl.cpp.
References alloc_doublelist(), ARG0_IS_D, ARG0_IS_I, DoubleList::e, free, i, init_doublelist(), malloc, mpi_local_stress_tensor(), periodic, PTENSOR_TRACE, realloc_doublelist(), this_node, and usage().
Referenced by tclcommand_analyze().
static void tclcommand_analyze_print_pressure_all (Tcl_Interp * interp) static
Definition at line 58 of file pressure_tcl.cpp.
References BONDED_IA_NONE, bonded_ia_params, checkIfParticlesInteract(), Observable_stat::coulomb, coulomb, COULOMB_NONE, Observable_stat::data, Observable_stat::dipolar, DIPOLAR_NONE, Coulomb_parameters::Dmethod, DoubleList::e, ELECTROSTATICS, get_name_of_bonded_ia(), i, Coulomb_parameters::method, DoubleList::n, n_bonded_ia, Observable_stat::n_coulomb, Observable_stat::n_dipolar, n_particle_types, obsstat_bonded(), obsstat_nonbonded(), obsstat_nonbonded_inter(), obsstat_nonbonded_intra(), total_pressure, total_pressure_non_bonded, and Observable_stat::vs_relative.
Referenced by tclcommand_analyze_parse_and_print_pressure().
static void tclcommand_analyze_print_stress_tensor_all (Tcl_Interp * interp) static
Definition at line 381 of file pressure_tcl.cpp.
References BONDED_IA_NONE, bonded_ia_params, checkIfParticlesInteract(), Observable_stat::coulomb, coulomb, COULOMB_NONE, Observable_stat::data, DIPOLAR_NONE, Coulomb_parameters::Dmethod, DoubleList::e, get_name_of_bonded_ia(), i, Coulomb_parameters::method, DoubleList::n, n_bonded_ia, n_particle_types, obsstat_bonded(), obsstat_nonbonded(), obsstat_nonbonded_inter(), obsstat_nonbonded_intra(), total_p_tensor, total_p_tensor_non_bonded, and Observable_stat::vs_relative.
Referenced by tclcommand_analyze_parse_and_print_stress_tensor().