ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: pressure.hpp File Reference
pressure.hpp File Reference
Pressure calculation.
#include "utils.hpp"
#include "integrate.hpp"
#include "statistics.hpp"
#include "thermostat.hpp"
#include "forces_inline.hpp"
#include "npt.hpp"
Functions
Exported Functions
void init_virials (Observable_stat *stat)
Initializes a virials Observable stat.
void init_virials_non_bonded (Observable_stat_non_bonded *stat_nb)
Initializes a virials Observable stat.
void init_p_tensor_non_bonded (Observable_stat_non_bonded *stat_nb)
Initializes stat_nb to be used by pressure_calc.
void init_p_tensor (Observable_stat *stat)
Initializes stat to be used by pressure_calc.
void master_pressure_calc (int v_comp)
on the master node: calc energies only if necessary
void pressure_calc (double *result, double *result_t, double *result_nb, double *result_t_nb, int v_comp)
Calculates the pressure in the system from a virial expansion using the terms from calculate_verlet_virials or nsq_calculate_virials dependeing on the used cell system.
void add_non_bonded_pair_virials (Particle *p1, Particle *p2, double d[3], double dist, double dist2)
Calculate non bonded energies between a pair of particles.
void calc_bonded_force (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, int *i, double dx[3], double force[3])
void calc_three_body_bonded_forces (Particle *p1, Particle *p2, Particle *p3, Bonded_ia_parameters *iaparams, double force1[3], double force2[3], double force3[3])
void add_bonded_virials (Particle *p1)
Calculate bonded virials for one particle.
void add_three_body_bonded_stress (Particle *p1)
Calculate the contribution to the stress tensor from angular potentials.
void add_kinetic_virials (Particle *p1, int v_comp)
Calculate kinetic pressure (aka energy) for one particle.
int local_stress_tensor_calc (DoubleList *TensorInBin, int bins[3], int periodic[3], double range_start[3], double range[3])
implementation of 'analyse local_stress_tensor
int observable_compute_stress_tensor (int v_comp, double *A, unsigned int n_A)
function to calculate stress tensor for the observables
void update_pressure (int v_comp)
void analyze_pressure_all (std::vector< std::string > &pressure_labels, std::vector< double > &pressures, int v_comp)
double analyze_pressure (std::string pressure_to_calc, int v_comp)
double analyze_pressure_pair (std::string pressure_to_calc, int type1, int type2, int v_comp)
double analyze_pressure_single (std::string pressure_to_calc, int bond_or_type, int v_comp)
void update_stress_tensor (int v_comp)
void analyze_stress_tensor_all (std::vector< std::string > &stressTensorLabel, std::vector< double > &stressTensorValues, int v_comp)
int analyze_stress_tensor (std::string pressure_to_calc, int v_comp, std::vector< double > &stress)
int analyze_stress_pair (std::string pressure_to_calc, int type1, int type2, int v_comp, std::vector< double > &stress)
int analyze_stress_single (std::string pressure_to_calc, int bond_or_type, int v_comp, std::vector< double > &stress)
int analyze_local_stress_tensor (int *periodic, double *range_start, double *range, int *bins, DoubleList *local_stress_tensor)
Variables
Exported Variables
Observable_stat virials
Observable_stat total_pressure
Observable_stat p_tensor
Observable_stat total_p_tensor
Observable_stat_non_bonded virials_non_bonded
Observable_stat_non_bonded total_pressure_non_bonded
Observable_stat_non_bonded p_tensor_non_bonded
Observable_stat_non_bonded total_p_tensor_non_bonded
Detailed Description
Pressure calculation.
Really similar to energy.h.
Definition in file pressure.hpp.
Function Documentation
void add_bonded_virials (Particle * p1) inline
Calculate bonded virials for one particle.
For performance reasons the force routines add their values directly to the particles. So here we do some tricks to get the value out without changing the forces.
Parameters
p1 particle for which to calculate virials
Definition at line 303 of file pressure.hpp.
References Particle::bl, BONDED_IA_HARMONIC, bonded_ia_params, calc_bonded_force(), IntList::e, get_mi_vector(), Bond_parameters::harmonic, i, ParticleProperties::identity, local_particles, obsstat_bonded(), ParticlePosition::p, Particle::p, Bonded_ia_parameters::p, Particle::r, Harmonic_bond_parameters::r_cut, and runtimeError.
Referenced by calculate_link_cell_virials(), calculate_verlet_virials(), layered_calculate_virials(), and nsq_calculate_virials().
void add_kinetic_virials (Particle * p1, int v_comp) inline
Calculate kinetic pressure (aka energy) for one particle.
Parameters
p1 particle for which to calculate pressure
v_comp flag which enables (1) compensation of the velocities required for deriving a pressure reflecting nptiso_struct::p_inst (hence it only works with domain decomposition); naturally it therefore doesn't make sense to use it without NpT.
Definition at line 505 of file pressure.hpp.
References Observable_stat::data, DoubleList::e, ParticleForce::f, Particle::f, Particle::m, PMASS, smaller_time_step, SQR(), time_step, and ParticleMomentum::v.
Referenced by calculate_link_cell_virials(), calculate_verlet_virials(), layered_calculate_virials(), and nsq_calculate_virials().
void add_non_bonded_pair_virials (Particle * p1, Particle * p2, double d[3], double dist, double dist2) inline
Calculate non bonded energies between a pair of particles.
Parameters
p1 pointer to particle 1.
p2 pointer to particle 2.
d vector between p1 and p2.
dist distance between p1 and p2.
dist2 distance squared between p1 and p2.
Definition at line 72 of file pressure.hpp.
References add_dh_coulomb_pair_force(), add_rf_coulomb_pair_force(), calc_non_bonded_pair_force(), Observable_stat::coulomb, coulomb, COULOMB_DH, COULOMB_INTER_RF, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, DIPOLAR_NONE, Coulomb_parameters::Dmethod, Coulomb_parameters::method, ParticleProperties::mol_id, obsstat_nonbonded(), obsstat_nonbonded_inter(), obsstat_nonbonded_intra(), Particle::p, ParticleProperties::q, and ParticleProperties::type.
Referenced by calculate_link_cell_virials(), calculate_verlet_virials(), layered_calculate_virials(), and nsq_calculate_virials().
void add_three_body_bonded_stress (Particle * p1) inline
Calculate the contribution to the stress tensor from angular potentials.
The central particle of the three-particle interaction is responsible for the contribution of the entire interaction - this is the coding not the physics.
Definition at line 347 of file pressure.hpp.
References Particle::bl, BONDED_IA_ANGLE_COSINE, BONDED_IA_ANGLE_COSSQUARE, BONDED_IA_ANGLE_HARMONIC, BONDED_IA_ANGLEDIST, BONDED_IA_AREA_FORCE_GLOBAL, BONDED_IA_AREA_FORCE_LOCAL, BONDED_IA_BENDING_FORCE, BONDED_IA_DIHEDRAL, BONDED_IA_FENE, BONDED_IA_HARMONIC, bonded_ia_params, BONDED_IA_RIGID_BOND, BONDED_IA_STRETCHING_FORCE, BONDED_IA_STRETCHLIN_FORCE, BONDED_IA_SUBT_LJ, BONDED_IA_TABULATED, BONDED_IA_VIRTUAL_BOND, BONDED_IA_VOLUME_FORCE, calc_three_body_bonded_forces(), IntList::e, get_mi_vector(), i, ParticleProperties::identity, local_particles, obsstat_bonded(), ParticlePosition::p, Particle::p, Bonded_ia_parameters::p, Particle::r, runtimeError, Bond_parameters::tab, TAB_BOND_ANGLE, TAB_BOND_DIHEDRAL, TAB_BOND_LENGTH, Tabulated_bond_parameters::type, and Bonded_ia_parameters::type.
Referenced by calculate_link_cell_virials(), calculate_verlet_virials(), layered_calculate_virials(), and nsq_calculate_virials().
int analyze_local_stress_tensor (int * periodic, double * range_start, double * range, int * bins, DoubleList * local_stress_tensor)
Definition at line 1098 of file pressure.cpp.
References alloc_doublelist(), DoubleList::e, ES_ERROR, ES_OK, i, init_doublelist(), malloc, mpi_local_stress_tensor(), PTENSOR_TRACE, and this_node.
double analyze_pressure (std::string pressure_to_calc, int v_comp)
void analyze_pressure_all (std::vector< std::string > & pressure_labels, std::vector< double > & pressures, int v_comp)
double analyze_pressure_pair (std::string pressure_to_calc, int type1, int type2, int v_comp)
double analyze_pressure_single (std::string pressure_to_calc, int bond_or_type, int v_comp)
int analyze_stress_pair (std::string pressure_to_calc, int type1, int type2, int v_comp, std::vector< double > & stress)
int analyze_stress_single (std::string pressure_to_calc, int bond_or_type, int v_comp, std::vector< double > & stress)
int analyze_stress_tensor (std::string pressure_to_calc, int v_comp, std::vector< double > & stress)
void analyze_stress_tensor_all (std::vector< std::string > & stressTensorLabel, std::vector< double > & stressTensorValues, int v_comp)
void calc_bonded_force (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, int * i, double dx[3], double force[3]) inline
Definition at line 155 of file pressure.hpp.
References BONDED_IA_ANGLE_COSINE, BONDED_IA_ANGLE_COSSQUARE, BONDED_IA_ANGLE_HARMONIC, BONDED_IA_ANGLEDIST, BONDED_IA_DIHEDRAL, BONDED_IA_FENE, BONDED_IA_HARMONIC, BONDED_IA_HARMONIC_DUMBBELL, BONDED_IA_OVERLAPPED, BONDED_IA_RIGID_BOND, BONDED_IA_SUBT_LJ, BONDED_IA_TABULATED, BONDED_IA_VIRTUAL_BOND, calc_fene_pair_force(), calc_harmonic_dumbbell_pair_force(), calc_harmonic_pair_force(), calc_overlap_bond_force(), calc_subt_lj_pair_force(), calc_tab_bond_force(), ParticleProperties::identity, Bond_parameters::overlap, OVERLAP_BOND_ANGLE, OVERLAP_BOND_DIHEDRAL, OVERLAP_BOND_LENGTH, Particle::p, Bonded_ia_parameters::p, runtimeError, Bond_parameters::tab, TAB_BOND_ANGLE, TAB_BOND_DIHEDRAL, TAB_BOND_LENGTH, Tabulated_bond_parameters::type, Overlap_bond_parameters::type, and Bonded_ia_parameters::type.
Referenced by add_bonded_virials(), and local_stress_tensor_calc().
void calc_three_body_bonded_forces (Particle * p1, Particle * p2, Particle * p3, Bonded_ia_parameters * iaparams, double force1[3], double force2[3], double force3[3]) inline
Definition at line 246 of file pressure.hpp.
References BONDED_IA_ANGLE_COSINE, BONDED_IA_ANGLE_COSSQUARE, BONDED_IA_ANGLE_HARMONIC, BONDED_IA_ANGLE_OLD, BONDED_IA_TABULATED, calc_angle_3body_forces(), calc_angle_3body_tabulated_forces(), calc_angle_cosine_3body_forces(), calc_angle_cossquare_3body_forces(), calc_angle_harmonic_3body_forces(), ParticleProperties::identity, Particle::p, Bonded_ia_parameters::p, runtimeError, Bond_parameters::tab, TAB_BOND_ANGLE, Tabulated_bond_parameters::type, and Bonded_ia_parameters::type.
Referenced by add_three_body_bonded_stress().
void init_p_tensor (Observable_stat * stat)
Initializes stat to be used by pressure_calc.
Definition at line 291 of file pressure.cpp.
References coulomb, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, Observable_stat::init_status, Coulomb_parameters::method, n_bonded_ia, n_particle_types, and obsstat_realloc_and_clear().
Referenced by observable_compute_stress_tensor(), pressure_calc(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
void init_p_tensor_non_bonded (Observable_stat_non_bonded * stat_nb)
Initializes stat_nb to be used by pressure_calc.
Definition at line 333 of file pressure.cpp.
References Observable_stat_non_bonded::init_status_nb, n_particle_types, and obsstat_realloc_and_clear_non_bonded().
Referenced by observable_compute_stress_tensor(), pressure_calc(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
void init_virials (Observable_stat * stat)
Initializes a virials Observable stat.
Definition at line 235 of file pressure.cpp.
References coulomb, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, Observable_stat::init_status, Coulomb_parameters::method, n_bonded_ia, n_particle_types, and obsstat_realloc_and_clear().
Referenced by observable_compute_stress_tensor(), pressure_calc(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
void init_virials_non_bonded (Observable_stat_non_bonded * stat_nb)
Initializes a virials Observable stat.
Definition at line 279 of file pressure.cpp.
References Observable_stat_non_bonded::init_status_nb, n_particle_types, and obsstat_realloc_and_clear_non_bonded().
Referenced by observable_compute_stress_tensor(), pressure_calc(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
int local_stress_tensor_calc (DoubleList * TensorInBin, int bins[3], int periodic[3], double range_start[3], double range[3])
implementation of 'analyse local_stress_tensor
Definition at line 910 of file pressure.cpp.
References Particle::bl, bonded_ia_params, box_l, calc_bonded_force(), CellPList::cell, DomainDecomposition::cell_inter, dd, distribute_tensors(), drem_down(), IntList::e, DoubleList::e, get_mi_vector(), get_nonbonded_interaction(), i, ParticleProperties::identity, incubewithskin(), local_cells, local_particles, Particle::m, max_cut, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, PairList::pair, ParticleList::part, PMASS, PTENSOR_TRACE, Particle::r, runtimeError, skin, this_node, time_step, ParticleMomentum::v, IA_Neighbor::vList, and whichbin().
Referenced by mpi_local_stress_tensor(), and mpi_local_stress_tensor_slave().
void master_pressure_calc (int v_comp)
on the master node: calc energies only if necessary
Parameters
v_comp flag which enables (1) compensation of the velocities required for deriving a pressure reflecting nptiso_struct::p_inst (hence it only works with domain decomposition); naturally it therefore doesn't make sense to use it without NpT.
Definition at line 343 of file pressure.cpp.
References Observable_stat::data, Observable_stat_non_bonded::data_nb, DoubleList::e, Observable_stat::init_status, Observable_stat_non_bonded::init_status_nb, and mpi_gather_stats().
Referenced by observable_compute_stress_tensor(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
int observable_compute_stress_tensor (int v_comp, double * A, unsigned int n_A)
function to calculate stress tensor for the observables
Definition at line 1037 of file pressure.cpp.
References Observable_stat::data, nptiso_struct::dimension, DoubleList::e, nptiso_struct::geometry, i, init_p_tensor(), init_p_tensor_non_bonded(), Observable_stat::init_status, init_virials(), init_virials_non_bonded(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso_struct::invalidate_p_vel, master_pressure_calc(), MPI_COMM_WORLD, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, DoubleList::n, nptiso_struct::nptgeom_dir, nptiso_struct::p_vel, and nptiso_struct::volume.
Referenced by observable_calc_stress_tensor_acf_obs(), and observable_stress_tensor().
void pressure_calc (double * result, double * result_t, double * result_nb, double * result_t_nb, int v_comp)
Calculates the pressure in the system from a virial expansion using the terms from calculate_verlet_virials or nsq_calculate_virials dependeing on the used cell system.
Parameters
result here the data about the scalar pressure are stored
result_t here the data about the stress tensor are stored
result_nb here the data about the intra- and inter- molecular nonbonded contributions to scalar pressure are stored
result_t_nb here the data about the intra- and inter- molecular nonbonded contributions to stress tensor are stored
v_comp flag which enables (1) compensation of the velocities required for deriving a pressure reflecting nptiso_struct::p_inst (hence it only works with domain decomposition); naturally it therefore doesn't make sense to use it without NpT.
Definition at line 83 of file pressure.cpp.
References box_l, build_verlet_lists(), calc_long_range_virials(), calculate_link_cell_virials(), calculate_verlet_virials(), cell_structure, CELL_STRUCTURE_DOMDEC, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, comm_cart, Observable_stat::data, Observable_stat_non_bonded::data_nb, dd, DoubleList::e, i, init_p_tensor(), init_p_tensor_non_bonded(), init_virials(), init_virials_non_bonded(), interactions_sanity_checks(), layered_calculate_virials(), MPI_DOUBLE, MPI_Reduce(), MPI_SUM, DoubleList::n, nsq_calculate_virials(), on_observable_calc(), rebuild_verletlist, time_step, CellStructure::type, DomainDecomposition::use_vList, Observable_stat::vs_relative, and vs_relative_pressure_and_stress_tensor().
Referenced by mpi_gather_stats(), and mpi_gather_stats_slave().
void update_pressure (int v_comp)
Definition at line 1502 of file statistics.cpp.
References Observable_stat::data, nptiso_struct::dimension, DoubleList::e, nptiso_struct::geometry, i, init_p_tensor(), init_p_tensor_non_bonded(), Observable_stat::init_status, init_virials(), init_virials_non_bonded(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso_struct::invalidate_p_vel, master_pressure_calc(), MPI_COMM_WORLD, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, nptiso_struct::nptgeom_dir, nptiso, nptiso_struct::p_vel, total_p_tensor, total_p_tensor_non_bonded, total_pressure, total_pressure_non_bonded, and nptiso_struct::volume.
void update_stress_tensor (int v_comp)
Definition at line 1072 of file pressure.cpp.
References Observable_stat::data, nptiso_struct::dimension, DoubleList::e, nptiso_struct::geometry, i, init_p_tensor(), init_p_tensor_non_bonded(), Observable_stat::init_status, init_virials(), init_virials_non_bonded(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso_struct::invalidate_p_vel, master_pressure_calc(), MPI_COMM_WORLD, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, nptiso_struct::nptgeom_dir, nptiso_struct::p_vel, and nptiso_struct::volume.
Variable Documentation
Observable_stat p_tensor
Definition at line 35 of file pressure.cpp.
Referenced by tclcommand_analyze_parse_and_print_stress_tensor().
Observable_stat_non_bonded p_tensor_non_bonded
Definition at line 42 of file pressure.cpp.
Observable_stat total_p_tensor
Definition at line 36 of file pressure.cpp.
Referenced by tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_stress_tensor_all(), and update_pressure().
Observable_stat_non_bonded total_p_tensor_non_bonded
Definition at line 43 of file pressure.cpp.
Referenced by tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_stress_tensor_all(), and update_pressure().
Observable_stat total_pressure
Definition at line 34 of file pressure.cpp.
Referenced by invalidate_obs(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_pressure_all(), and update_pressure().
Observable_stat_non_bonded total_pressure_non_bonded
Definition at line 41 of file pressure.cpp.
Referenced by tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_pressure_all(), and update_pressure().
Observable_stat virials
Definition at line 33 of file pressure.cpp.
Observable_stat_non_bonded virials_non_bonded
Definition at line 40 of file pressure.cpp.