ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: pressure.cpp File Reference
pressure.cpp File Reference
Implementation of pressure.h.
#include "pressure.hpp"
#include "cells.hpp"
#include "integrate.hpp"
#include "initialize.hpp"
#include "domain_decomposition.hpp"
#include "nsquare.hpp"
#include "layered.hpp"
#include "virtual_sites_relative.hpp"
Functions
void calc_long_range_virials ()
Calculate long range virials (P3M, MMM2d...).
void init_virials (Observable_stat *stat)
Initializes a virials Observable stat.
void init_virials_non_bonded (Observable_stat_non_bonded *stat_nb)
Initializes a virials Observable stat.
void master_pressure_calc (int v_comp)
on the master node: calc energies only if necessary
void init_p_tensor (Observable_stat *stat)
Initializes stat to be used by pressure_calc.
void init_p_tensor_non_bonded (Observable_stat_non_bonded *stat_nb)
Initializes stat_nb to be used by pressure_calc.
void pressure_calc (double *result, double *result_t, double *result_nb, double *result_t_nb, int v_comp)
Calculates the pressure in the system from a virial expansion using the terms from calculate_verlet_virials or nsq_calculate_virials dependeing on the used cell system.
int getintersection (double pos1[3], double pos2[3], int given, int get, double value, double *answer, double box_size[3])
int getlength (double pos1[3], double pos2[3], int d1, double val1, int d2, double val2, int l, double *answer)
int does_line_go_through_cube (double pos1[3], double pos2[3], double range_start[3], double range[3], int sign[3], double entry[3], double exit[3], int *facein, int *faceout)
int distribute_tensors (DoubleList *TensorInBin, double *force, int bins[3], double range_start[3], double range[3], double pos1[3], double pos2[3])
int reducepos (double pos[3], int bins[3], double centre[3], double range[3], int reducedpos[3])
int incubewithskin (double pos[3], double centre[3], double range[3])
int whichbin (double pos[3], int bins[3], double centre[3], double range[3], int *bin)
int get_nonbonded_interaction (Particle *p1, Particle *p2, double *force)
int local_stress_tensor_calc (DoubleList *TensorInBin, int bins[3], int periodic[3], double range_start[3], double range[3])
implementation of 'analyse local_stress_tensor
int observable_compute_stress_tensor (int v_comp, double *A, unsigned int n_A)
function to calculate stress tensor for the observables
void update_stress_tensor (int v_comp)
int analyze_local_stress_tensor (int *periodic, double *range_start, double *range, int *bins, DoubleList *local_stress_tensor)
Variables
Observable_stat virials = {0, {NULL,0,0}, 0,0,0,0,0}
Observable_stat total_pressure = {0, {NULL,0,0}, 0,0,0,0,0}
Observable_stat p_tensor = {0, {NULL,0,0},0,0,0,0,0}
Observable_stat total_p_tensor = {0, {NULL,0,0},0,0,0,0,0}
Observable_stat_non_bonded virials_non_bonded = {0, {NULL,0,0}, 0,0,0}
Observable_stat_non_bonded total_pressure_non_bonded = {0, {NULL,0,0}, 0,0,0}
Observable_stat_non_bonded p_tensor_non_bonded = {0, {NULL,0,0},0,0,0}
Observable_stat_non_bonded total_p_tensor_non_bonded = {0, {NULL,0,0},0,0,0}
nptiso_struct nptiso = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,{0.0,0.0,0.0},{0.0,0.0,0.0},1, 0 ,{NPTGEOM_XDIR, NPTGEOM_YDIR, NPTGEOM_ZDIR},0,0,0}
Detailed Description
Implementation of pressure.h.
Definition in file pressure.cpp.
Function Documentation
int analyze_local_stress_tensor (int * periodic, double * range_start, double * range, int * bins, DoubleList * local_stress_tensor)
Definition at line 1098 of file pressure.cpp.
References alloc_doublelist(), DoubleList::e, ES_ERROR, ES_OK, i, init_doublelist(), malloc, mpi_local_stress_tensor(), PTENSOR_TRACE, and this_node.
void calc_long_range_virials ()
Calculate long range virials (P3M, MMM2d...).
Definition at line 158 of file pressure.cpp.
References Observable_stat::coulomb, coulomb, COULOMB_ELC_P3M, COULOMB_EWALD_GPU, COULOMB_MMM1D, COULOMB_MMM1D_GPU, COULOMB_MMM2D, COULOMB_P3M, COULOMB_P3M_GPU, Observable_stat::dipolar, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_MDLC_DS, DIPOLAR_MDLC_P3M, DIPOLAR_P3M, Coulomb_parameters::Dmethod, and Coulomb_parameters::method.
Referenced by pressure_calc().
int distribute_tensors (DoubleList * TensorInBin, double * force, int bins[3], double range_start[3], double range[3], double pos1[3], double pos2[3])
Definition at line 528 of file pressure.cpp.
References box_l, does_line_go_through_cube(), drem_down(), dround(), DoubleList::e, free, get_mi_vector(), getintersection(), getlength(), i, malloc, PTENSOR_TRACE, runtimeError, sign(), and this_node.
Referenced by local_stress_tensor_calc().
int does_line_go_through_cube (double pos1[3], double pos2[3], double range_start[3], double range[3], int sign[3], double entry[3], double exit[3], int * facein, int * faceout)
Definition at line 416 of file pressure.cpp.
References box_l, get_mi_vector(), getintersection(), i, PTENSOR_TRACE, and this_node.
Referenced by distribute_tensors().
int get_nonbonded_interaction (Particle * p1, Particle * p2, double * force)
Definition at line 828 of file pressure.cpp.
References add_dh_coulomb_pair_force(), add_rf_coulomb_pair_force(), calc_non_bonded_pair_force(), checkIfParticlesInteract(), coulomb, COULOMB_DH, COULOMB_INTER_RF, COULOMB_MMM1D, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, COULOMB_RF, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, get_mi_vector(), i, ParticleProperties::identity, Coulomb_parameters::method, ParticlePosition::p, Particle::p, Particle::r, SQR(), and ParticleProperties::type.
Referenced by local_stress_tensor_calc().
int getintersection (double pos1[3], double pos2[3], int given, int get, double value, double * answer, double box_size[3])
Definition at line 360 of file pressure.cpp.
References drem_down(), i, and runtimeError.
Referenced by distribute_tensors(), does_line_go_through_cube(), and getlength().
int getlength (double pos1[3], double pos2[3], int d1, double val1, int d2, double val2, int l, double * answer)
Definition at line 394 of file pressure.cpp.
References box_l, drem_down(), and getintersection().
Referenced by distribute_tensors().
int incubewithskin (double pos[3], double centre[3], double range[3])
Definition at line 801 of file pressure.cpp.
References get_mi_vector(), i, max_cut, and skin.
Referenced by local_stress_tensor_calc().
void init_p_tensor (Observable_stat * stat)
Initializes stat to be used by pressure_calc.
Definition at line 291 of file pressure.cpp.
References coulomb, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, Observable_stat::init_status, Coulomb_parameters::method, n_bonded_ia, n_particle_types, and obsstat_realloc_and_clear().
Referenced by observable_compute_stress_tensor(), pressure_calc(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
void init_p_tensor_non_bonded (Observable_stat_non_bonded * stat_nb)
Initializes stat_nb to be used by pressure_calc.
Definition at line 333 of file pressure.cpp.
References Observable_stat_non_bonded::init_status_nb, n_particle_types, and obsstat_realloc_and_clear_non_bonded().
Referenced by observable_compute_stress_tensor(), pressure_calc(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
void init_virials (Observable_stat * stat)
Initializes a virials Observable stat.
Definition at line 235 of file pressure.cpp.
References coulomb, COULOMB_NONE, COULOMB_P3M, COULOMB_P3M_GPU, DIPOLAR_ALL_WITH_ALL_AND_NO_REPLICA, DIPOLAR_DS, DIPOLAR_NONE, DIPOLAR_P3M, Coulomb_parameters::Dmethod, Observable_stat::init_status, Coulomb_parameters::method, n_bonded_ia, n_particle_types, and obsstat_realloc_and_clear().
Referenced by observable_compute_stress_tensor(), pressure_calc(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
void init_virials_non_bonded (Observable_stat_non_bonded * stat_nb)
Initializes a virials Observable stat.
Definition at line 279 of file pressure.cpp.
References Observable_stat_non_bonded::init_status_nb, n_particle_types, and obsstat_realloc_and_clear_non_bonded().
Referenced by observable_compute_stress_tensor(), pressure_calc(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
int local_stress_tensor_calc (DoubleList * TensorInBin, int bins[3], int periodic[3], double range_start[3], double range[3])
implementation of 'analyse local_stress_tensor
Definition at line 910 of file pressure.cpp.
References Particle::bl, bonded_ia_params, box_l, calc_bonded_force(), CellPList::cell, DomainDecomposition::cell_inter, dd, distribute_tensors(), drem_down(), IntList::e, DoubleList::e, get_mi_vector(), get_nonbonded_interaction(), i, ParticleProperties::identity, incubewithskin(), local_cells, local_particles, Particle::m, max_cut, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, PairList::pair, ParticleList::part, PMASS, PTENSOR_TRACE, Particle::r, runtimeError, skin, this_node, time_step, ParticleMomentum::v, IA_Neighbor::vList, and whichbin().
Referenced by mpi_local_stress_tensor(), and mpi_local_stress_tensor_slave().
void master_pressure_calc (int v_comp)
on the master node: calc energies only if necessary
Parameters
v_comp flag which enables (1) compensation of the velocities required for deriving a pressure reflecting nptiso_struct::p_inst (hence it only works with domain decomposition); naturally it therefore doesn't make sense to use it without NpT.
Definition at line 343 of file pressure.cpp.
References Observable_stat::data, Observable_stat_non_bonded::data_nb, DoubleList::e, Observable_stat::init_status, Observable_stat_non_bonded::init_status_nb, and mpi_gather_stats().
Referenced by observable_compute_stress_tensor(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), update_pressure(), and update_stress_tensor().
int observable_compute_stress_tensor (int v_comp, double * A, unsigned int n_A)
function to calculate stress tensor for the observables
Definition at line 1037 of file pressure.cpp.
References Observable_stat::data, nptiso_struct::dimension, DoubleList::e, nptiso_struct::geometry, i, init_p_tensor(), init_p_tensor_non_bonded(), Observable_stat::init_status, init_virials(), init_virials_non_bonded(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso_struct::invalidate_p_vel, master_pressure_calc(), MPI_COMM_WORLD, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, DoubleList::n, nptiso_struct::nptgeom_dir, nptiso_struct::p_vel, and nptiso_struct::volume.
Referenced by observable_calc_stress_tensor_acf_obs(), and observable_stress_tensor().
void pressure_calc (double * result, double * result_t, double * result_nb, double * result_t_nb, int v_comp)
Calculates the pressure in the system from a virial expansion using the terms from calculate_verlet_virials or nsq_calculate_virials dependeing on the used cell system.
Parameters
result here the data about the scalar pressure are stored
result_t here the data about the stress tensor are stored
result_nb here the data about the intra- and inter- molecular nonbonded contributions to scalar pressure are stored
result_t_nb here the data about the intra- and inter- molecular nonbonded contributions to stress tensor are stored
v_comp flag which enables (1) compensation of the velocities required for deriving a pressure reflecting nptiso_struct::p_inst (hence it only works with domain decomposition); naturally it therefore doesn't make sense to use it without NpT.
Definition at line 83 of file pressure.cpp.
References box_l, build_verlet_lists(), calc_long_range_virials(), calculate_link_cell_virials(), calculate_verlet_virials(), cell_structure, CELL_STRUCTURE_DOMDEC, CELL_STRUCTURE_LAYERED, CELL_STRUCTURE_NSQUARE, comm_cart, Observable_stat::data, Observable_stat_non_bonded::data_nb, dd, DoubleList::e, i, init_p_tensor(), init_p_tensor_non_bonded(), init_virials(), init_virials_non_bonded(), interactions_sanity_checks(), layered_calculate_virials(), MPI_DOUBLE, MPI_Reduce(), MPI_SUM, DoubleList::n, nsq_calculate_virials(), on_observable_calc(), rebuild_verletlist, time_step, CellStructure::type, DomainDecomposition::use_vList, Observable_stat::vs_relative, and vs_relative_pressure_and_stress_tensor().
Referenced by mpi_gather_stats(), and mpi_gather_stats_slave().
int reducepos (double pos[3], int bins[3], double centre[3], double range[3], int reducedpos[3])
Definition at line 791 of file pressure.cpp.
References get_mi_vector(), and i.
Referenced by whichbin().
void update_stress_tensor (int v_comp)
Definition at line 1072 of file pressure.cpp.
References Observable_stat::data, nptiso_struct::dimension, DoubleList::e, nptiso_struct::geometry, i, init_p_tensor(), init_p_tensor_non_bonded(), Observable_stat::init_status, init_virials(), init_virials_non_bonded(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso_struct::invalidate_p_vel, master_pressure_calc(), MPI_COMM_WORLD, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, nptiso_struct::nptgeom_dir, nptiso_struct::p_vel, and nptiso_struct::volume.
int whichbin (double pos[3], int bins[3], double centre[3], double range[3], int * bin)
Definition at line 812 of file pressure.cpp.
References i, and reducepos().
Referenced by local_stress_tensor_calc().
Variable Documentation
nptiso_struct nptiso = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,{0.0,0.0,0.0},{0.0,0.0,0.0},1, 0 ,{NPTGEOM_XDIR, NPTGEOM_YDIR, NPTGEOM_ZDIR},0,0,0}
Definition at line 45 of file pressure.cpp.
Referenced by add_bonded_force(), add_non_bonded_pair_force(), calc_long_range_forces(), finalize_p_inst_npt(), init_forces(), integrate_ensemble_init(), integrate_sd(), integrate_set_npt_isotropic(), integrate_vv(), integrator_npt_sanity_checks(), mpi_bcast_nptiso_geom_slave(), on_parameter_change(), propagate_press_box_pos_and_rescale_npt(), propagate_vel(), rescale_forces_propagate_vel(), tclcallback_npt_p_diff(), tclcallback_npt_piston(), tclcallback_p_ext(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_integrate_print_status(), tclcommand_integrate_set_npt_isotropic(), thermo_init_npt_isotropic(), and update_pressure().
Observable_stat p_tensor = {0, {NULL,0,0},0,0,0,0,0}
Definition at line 35 of file pressure.cpp.
Referenced by tclcommand_analyze_parse_and_print_stress_tensor().
Observable_stat_non_bonded p_tensor_non_bonded = {0, {NULL,0,0},0,0,0}
Definition at line 42 of file pressure.cpp.
Observable_stat total_p_tensor = {0, {NULL,0,0},0,0,0,0,0}
Definition at line 36 of file pressure.cpp.
Referenced by tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_stress_tensor_all(), and update_pressure().
Observable_stat_non_bonded total_p_tensor_non_bonded = {0, {NULL,0,0},0,0,0}
Definition at line 43 of file pressure.cpp.
Referenced by tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_stress_tensor_all(), and update_pressure().
Observable_stat total_pressure = {0, {NULL,0,0}, 0,0,0,0,0}
Definition at line 34 of file pressure.cpp.
Referenced by invalidate_obs(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_pressure_all(), and update_pressure().
Observable_stat_non_bonded total_pressure_non_bonded = {0, {NULL,0,0}, 0,0,0}
Definition at line 41 of file pressure.cpp.
Referenced by tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_pressure_all(), and update_pressure().
Observable_stat virials = {0, {NULL,0,0}, 0,0,0,0,0}
Definition at line 33 of file pressure.cpp.
Observable_stat_non_bonded virials_non_bonded = {0, {NULL,0,0}, 0,0,0}
Definition at line 40 of file pressure.cpp.