ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: random.cpp File Reference
random.cpp File Reference
A random generator.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "utils.hpp"
#include "global.hpp"
#include "random.hpp"
#include "communication.hpp"
Functions
void init_random (void)
void init_random_seed (long seed)
void init_random_stat (RandomStatus my_stat)
long print_random_idum (void)
long print_random_seed (void)
RandomStatus print_random_stat (void)
double bit_random_generator ()
void init_bit_random (void)
void init_bit_random_generator (int iseed)
int print_bit_random_seed (void)
BitRandomStatus print_bit_random_stat (void)
void init_bit_random_stat (BitRandomStatus tmp_stat)
Variables
long idum = -1
long idumInit = -1
long iy =0
long iv [NTAB_RANDOM]
int bit_seed = -1
int rand_w_array [MERS_BIT_RANDOM]
int random_pointer_1 = -1
int random_pointer_2 = -1
Detailed Description
A random generator.
Be sure to run init_random() before you use any of the generators.
Definition in file random.cpp.
Function Documentation
double bit_random_generator (void)
Definition at line 122 of file random.cpp.
References FACTOR, MERS_BIT_RANDOM, rand_w_array, random_pointer_1, and random_pointer_2.
Referenced by init_bit_random_generator(), and tclcommand_bit_random().
void init_bit_random (void)
Definition at line 142 of file random.cpp.
References init_bit_random_generator(), and this_node.
Referenced by on_program_start().
void init_bit_random_generator (int iseed)
Definition at line 153 of file random.cpp.
References BIGFLOAT, BIGINTEGER, bit_random_generator(), bit_seed, FACTOR, i, MERS1, MERS_BIT_RANDOM, MULTIPLY, NBIT, NWARM, rand_w_array, random_pointer_1, and random_pointer_2.
Referenced by init_bit_random(), mpi_bit_random_seed(), and mpi_bit_random_seed_slave().
void init_bit_random_stat (BitRandomStatus tmp_stat)
Definition at line 215 of file random.cpp.
References i, MERS_BIT_RANDOM, rand_w_array, BitRandomStatus::rand_w_array, random_pointer_1, BitRandomStatus::random_pointer_1, random_pointer_2, and BitRandomStatus::random_pointer_2.
Referenced by mpi_bit_random_stat(), and mpi_bit_random_stat_slave().
void init_random (void)
Definition at line 46 of file random.cpp.
References init_random_seed(), and this_node.
Referenced by on_program_start().
void init_random_seed (long seed)
Definition at line 58 of file random.cpp.
References errexit(), IA, idum, idumInit, IM, IQ, IR, iv, iy, NTAB_RANDOM, RANDOM_TRACE, and this_node.
Referenced by init_random(), mpi_random_seed(), and mpi_random_seed_slave().
void init_random_stat (RandomStatus my_stat)
Definition at line 87 of file random.cpp.
References i, idum, RandomStatus::idum, iv, RandomStatus::iv, iy, RandomStatus::iy, and NTAB_RANDOM.
Referenced by mpi_random_stat(), and mpi_random_stat_slave().
int print_bit_random_seed (void)
Definition at line 196 of file random.cpp.
References bit_seed.
Referenced by mpi_bit_random_seed(), and mpi_bit_random_seed_slave().
BitRandomStatus print_bit_random_stat (void)
Definition at line 203 of file random.cpp.
References i, MERS_BIT_RANDOM, rand_w_array, BitRandomStatus::rand_w_array, random_pointer_1, BitRandomStatus::random_pointer_1, random_pointer_2, and BitRandomStatus::random_pointer_2.
Referenced by mpi_bit_random_stat(), and mpi_bit_random_stat_slave().
long print_random_idum (void)
Definition at line 97 of file random.cpp.
References idum.
long print_random_seed (void)
Definition at line 104 of file random.cpp.
References idumInit.
Referenced by mpi_random_seed(), and mpi_random_seed_slave().
RandomStatus print_random_stat (void)
Definition at line 111 of file random.cpp.
References i, idum, RandomStatus::idum, iv, RandomStatus::iv, iy, RandomStatus::iy, and NTAB_RANDOM.
Referenced by mpi_random_stat(), and mpi_random_stat_slave().
Variable Documentation
int bit_seed = -1
Definition at line 39 of file random.cpp.
Referenced by init_bit_random_generator(), and print_bit_random_seed().
long idum = -1
Definition at line 33 of file random.cpp.
Referenced by init_random_seed(), init_random_stat(), l_random(), print_random_idum(), print_random_stat(), and tclcommand_t_random().
long idumInit = -1
Definition at line 34 of file random.cpp.
Referenced by init_random_seed(), and print_random_seed().
long iv[NTAB_RANDOM]
Definition at line 36 of file random.cpp.
Referenced by init_random_seed(), init_random_stat(), l_random(), print_random_stat(), and tclcommand_t_random().
long iy =0
Definition at line 35 of file random.cpp.
Referenced by EwaldgpuForce::compute_k_AND_influence_factor(), EwaldgpuForce::compute_num_k(), create_free_volume_grid(), d_random(), get_DLC_dipolar(), get_DLC_energy_dipolar(), init_random_seed(), init_random_stat(), l_random(), maggs_calc_init_e_field(), maggs_check_curl_E(), maggs_setup_local_lattice(), maggs_setup_neighbors(), print_random_stat(), and tclcommand_t_random().
int rand_w_array[MERS_BIT_RANDOM]
Definition at line 40 of file random.cpp.
Referenced by bit_random_generator(), init_bit_random_generator(), init_bit_random_stat(), print_bit_random_stat(), and tclcommand_bit_random().
int random_pointer_1 = -1
Definition at line 41 of file random.cpp.
Referenced by bit_random_generator(), init_bit_random_generator(), init_bit_random_stat(), print_bit_random_stat(), and tclcommand_bit_random().
int random_pointer_2 = -1
Definition at line 42 of file random.cpp.
Referenced by bit_random_generator(), init_bit_random_generator(), init_bit_random_stat(), print_bit_random_stat(), and tclcommand_bit_random().