ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: random.hpp File Reference
random.hpp File Reference
A random generator.
#include "utils.hpp"
Data Structures
struct RandomStatus
struct BitRandomStatus
Functions
void init_random (void)
void init_random_seed (long seed)
void init_random_stat (RandomStatus my_stat)
long print_random_idum (void)
long print_random_seed (void)
RandomStatus print_random_stat (void)
long l_random (void)
classical RAN1 random number generator
int i_random (int maxint)
same as l_random, but for integer
double d_random (void)
double gaussian_random (void)
Generator for Gaussian random numbers.
double gaussian_random_cut (void)
Generator for Gaussian random numbers.
double bit_random_generator (void)
void init_bit_random (void)
void init_bit_random_generator (int iseed)
void init_bit_random_stat (BitRandomStatus my_stat)
int print_bit_random_seed (void)
BitRandomStatus print_bit_random_stat (void)
#define IA 16807
#define IM 2147483647
#define AM (1.0/2147483647.)
#define IQ 127773
#define IR 2836
#define NDIV ((double) (1+(2147483647-1)/NTAB_RANDOM))
#define RNMX (1.0-1.2e-7)
#define NTAB_RANDOM 32
long idum
long idumInit
long iy
long iv [NTAB_RANDOM]
#define MERS1 147
Stuff for Burkhards r250-generator.
#define MERS_BIT_RANDOM 250
#define NBIT 32
#define BIGINTEGER 2147483647
#define BIGFLOAT 2147483647.
#define FACTOR 4.6566128752457969e-10
#define MULTIPLY 16807.
#define NWARM 10000
int bit_seed
int rand_w_array [MERS_BIT_RANDOM]
int random_pointer_1
int random_pointer_2
Detailed Description
A random generator.
Definition in file random.hpp.
Macro Definition Documentation
#define AM (1.0/2147483647.)
Definition at line 37 of file random.hpp.
Referenced by d_random(), and i_random().
#define BIGFLOAT 2147483647.
Definition at line 56 of file random.hpp.
Referenced by init_bit_random_generator().
#define BIGINTEGER 2147483647
Definition at line 55 of file random.hpp.
Referenced by init_bit_random_generator().
#define FACTOR 4.6566128752457969e-10
Definition at line 57 of file random.hpp.
Referenced by bit_random_generator(), and init_bit_random_generator().
#define IA 16807
Definition at line 35 of file random.hpp.
Referenced by init_random_seed(), and l_random().
#define IM 2147483647
Definition at line 36 of file random.hpp.
Referenced by init_random_seed(), and l_random().
#define IQ 127773
Definition at line 38 of file random.hpp.
Referenced by init_random_seed(), and l_random().
#define IR 2836
Definition at line 39 of file random.hpp.
Referenced by init_random_seed(), and l_random().
#define MERS1 147
Stuff for Burkhards r250-generator.
Definition at line 52 of file random.hpp.
Referenced by init_bit_random_generator().
#define MERS_BIT_RANDOM 250
Definition at line 53 of file random.hpp.
Referenced by bit_random_generator(), init_bit_random_generator(), init_bit_random_stat(), print_bit_random_stat(), and tclcommand_bit_random().
#define MULTIPLY 16807.
Definition at line 58 of file random.hpp.
Referenced by init_bit_random_generator().
#define NBIT 32
Definition at line 54 of file random.hpp.
Referenced by init_bit_random_generator().
#define NDIV ((double) (1+(2147483647-1)/NTAB_RANDOM))
Definition at line 40 of file random.hpp.
Referenced by l_random().
#define NTAB_RANDOM 32
Definition at line 42 of file random.hpp.
Referenced by init_random_seed(), init_random_stat(), print_random_stat(), and tclcommand_t_random().
#define NWARM 10000
Definition at line 59 of file random.hpp.
Referenced by init_bit_random_generator().
#define RNMX (1.0-1.2e-7)
Definition at line 41 of file random.hpp.
Referenced by d_random().
Function Documentation
double bit_random_generator (void)
Definition at line 122 of file random.cpp.
References FACTOR, MERS_BIT_RANDOM, rand_w_array, random_pointer_1, and random_pointer_2.
Referenced by init_bit_random_generator(), and tclcommand_bit_random().
double d_random (void) inline
Definition at line 110 of file random.hpp.
References AM, iy, l_random(), and RNMX.
Referenced by add_dpd_thermo_pair_force(), add_inter_dpd_pair_force(), add_tunable_slip_pair_force(), calc_fene_pair_force(), calc_harmonic_dumbbell_pair_force(), calc_harmonic_pair_force(), calc_particle_lattice_ia(), counterionsC(), crosslinkC(), friction_therm0_nptiso(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), friction_thermV_nptiso(), gaussian_random(), gaussian_random_cut(), ghmc_mc(), integrate_reaction(), lb_thermalize_modes(), maxwell_velocitiesC(), polymerC(), saltC(), tclcommand_t_random(), and velocitiesC().
double gaussian_random (void) inline
Generator for Gaussian random numbers.
Uses the Box-Muller transformation to generate two Gaussian random numbers from two uniform random numbers.
Returns
Gaussian random number.
Definition at line 129 of file random.hpp.
References d_random().
double gaussian_random_cut (void) inline
Generator for Gaussian random numbers.
Uses the Box-Muller transformation to generate two Gaussian random numbers from two uniform random numbers. which generates numbers between -2 sigma and 2 sigma in the form of a Gaussian with standard deviation sigma=1.118591404 resulting in an actual standard deviation of 1.
Returns
Gaussian random number.
Definition at line 177 of file random.hpp.
References d_random().
int i_random (int maxint) inline
same as l_random, but for integer
Definition at line 99 of file random.hpp.
References AM, and l_random().
Referenced by find_particle_type(), find_particle_type_id(), gpu_change_number_of_part_to_comm(), lb_realloc_particles_gpu(), and tclcommand_t_random().
void init_bit_random (void)
Definition at line 142 of file random.cpp.
References init_bit_random_generator(), and this_node.
Referenced by on_program_start().
void init_bit_random_generator (int iseed)
Definition at line 153 of file random.cpp.
References BIGFLOAT, BIGINTEGER, bit_random_generator(), bit_seed, FACTOR, i, MERS1, MERS_BIT_RANDOM, MULTIPLY, NBIT, NWARM, rand_w_array, random_pointer_1, and random_pointer_2.
Referenced by init_bit_random(), mpi_bit_random_seed(), and mpi_bit_random_seed_slave().
void init_bit_random_stat (BitRandomStatus my_stat)
Definition at line 215 of file random.cpp.
References i, MERS_BIT_RANDOM, rand_w_array, BitRandomStatus::rand_w_array, random_pointer_1, BitRandomStatus::random_pointer_1, random_pointer_2, and BitRandomStatus::random_pointer_2.
Referenced by mpi_bit_random_stat(), and mpi_bit_random_stat_slave().
void init_random (void)
Definition at line 46 of file random.cpp.
References init_random_seed(), and this_node.
Referenced by on_program_start().
void init_random_seed (long seed)
Definition at line 58 of file random.cpp.
References errexit(), IA, idum, idumInit, IM, IQ, IR, iv, iy, NTAB_RANDOM, RANDOM_TRACE, and this_node.
Referenced by init_random(), mpi_random_seed(), and mpi_random_seed_slave().
void init_random_stat (RandomStatus my_stat)
Definition at line 87 of file random.cpp.
References i, idum, RandomStatus::idum, iv, RandomStatus::iv, iy, RandomStatus::iy, and NTAB_RANDOM.
Referenced by mpi_random_stat(), and mpi_random_stat_slave().
long l_random (void) inline
classical RAN1 random number generator
Definition at line 81 of file random.hpp.
References IA, idum, IM, IQ, IR, iv, iy, and NDIV.
Referenced by d_random(), and i_random().
int print_bit_random_seed (void)
Definition at line 196 of file random.cpp.
References bit_seed.
Referenced by mpi_bit_random_seed(), and mpi_bit_random_seed_slave().
BitRandomStatus print_bit_random_stat (void)
Definition at line 203 of file random.cpp.
References i, MERS_BIT_RANDOM, rand_w_array, BitRandomStatus::rand_w_array, random_pointer_1, BitRandomStatus::random_pointer_1, random_pointer_2, and BitRandomStatus::random_pointer_2.
Referenced by mpi_bit_random_stat(), and mpi_bit_random_stat_slave().
long print_random_idum (void)
Definition at line 97 of file random.cpp.
References idum.
long print_random_seed (void)
Definition at line 104 of file random.cpp.
References idumInit.
Referenced by mpi_random_seed(), and mpi_random_seed_slave().
RandomStatus print_random_stat (void)
Definition at line 111 of file random.cpp.
References i, idum, RandomStatus::idum, iv, RandomStatus::iv, iy, RandomStatus::iy, and NTAB_RANDOM.
Referenced by mpi_random_stat(), and mpi_random_stat_slave().
Variable Documentation
int bit_seed
Definition at line 39 of file random.cpp.
Referenced by init_bit_random_generator(), and print_bit_random_seed().
long idum
Definition at line 33 of file random.cpp.
Referenced by init_random_seed(), init_random_stat(), l_random(), print_random_idum(), print_random_stat(), and tclcommand_t_random().
long idumInit
Definition at line 34 of file random.cpp.
Referenced by init_random_seed(), and print_random_seed().
long iv[NTAB_RANDOM]
Definition at line 36 of file random.cpp.
Referenced by init_random_seed(), init_random_stat(), l_random(), print_random_stat(), and tclcommand_t_random().
long iy
Definition at line 35 of file random.cpp.
Referenced by EwaldgpuForce::compute_k_AND_influence_factor(), EwaldgpuForce::compute_num_k(), create_free_volume_grid(), d_random(), get_DLC_dipolar(), get_DLC_energy_dipolar(), init_random_seed(), init_random_stat(), l_random(), maggs_calc_init_e_field(), maggs_check_curl_E(), maggs_setup_local_lattice(), maggs_setup_neighbors(), print_random_stat(), and tclcommand_t_random().
int rand_w_array[MERS_BIT_RANDOM]
Definition at line 40 of file random.cpp.
Referenced by bit_random_generator(), init_bit_random_generator(), init_bit_random_stat(), print_bit_random_stat(), and tclcommand_bit_random().
int random_pointer_1
Definition at line 41 of file random.cpp.
Referenced by bit_random_generator(), init_bit_random_generator(), init_bit_random_stat(), print_bit_random_stat(), and tclcommand_bit_random().
int random_pointer_2
Definition at line 42 of file random.cpp.
Referenced by bit_random_generator(), init_bit_random_generator(), init_bit_random_stat(), print_bit_random_stat(), and tclcommand_bit_random().