ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: random_tcl.hpp File Reference
random_tcl.hpp File Reference
#include "parser.hpp"
Functions
int tclcommand_t_random (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl command tclcommand_t_random.
int tclcommand_bit_random (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl command tclcommand_bit_random.
Function Documentation
int tclcommand_bit_random (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl command tclcommand_bit_random.
Access to the parallel bit random number generator.
Implementation of the tcl command tclcommand_bit_random.
<seed(n_nodes-1)>] | stat [status-list] }]
Without further arguments, it returns a random double between 0 and 1.
If 'seed'/'stat' is given without further arguments, it returns a tcl-list with the current seeds/status of the n_nodes active nodes; otherwise it issues the given parameters as the new seeds/status to the respective nodes.
Definition at line 234 of file random_tcl.cpp.
References ARG_IS_I, ARG_IS_S, bit_random_generator(), free, i, malloc, MERS_BIT_RANDOM, mpi_bit_random_seed(), mpi_bit_random_stat(), n_nodes, rand_w_array, random_pointer_1, random_pointer_2, and RANDOM_TRACE.
Referenced by tcl_register_commands().
int tclcommand_t_random (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl command tclcommand_t_random.
Access to the parallel random number generator.
Implementation of the tcl command tclcommand_t_random.
<seed(n_nodes-1)>] | stat [status-list] }]
Without further arguments, it returns a random double between 0 and 1.
If 'int <n>' is given, it returns a random integer between 0 and n-1.
If 'seed'/'stat' is given without further arguments, it returns a tcl-list with the current seeds/status of the n_nodes active nodes; otherwise it issues the given parameters as the new seeds/status to the respective nodes.
Definition at line 43 of file random_tcl.cpp.
References ARG_IS_I, ARG_IS_S, d_random(), free, i, i_random(), idum, RandomStatus::idum, iv, RandomStatus::iv, iy, RandomStatus::iy, malloc, mpi_random_seed(), mpi_random_stat(), n_nodes, NTAB_RANDOM, and RANDOM_TRACE.
Referenced by tcl_register_commands().