ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: rattle.hpp File Reference
rattle.hpp File Reference
RATTLE Algorithm (Rattle: A "Velocity" Version of the Shake Algorithm for Molecular Dynamics Calculations, H.C Andersen, J Comp Phys, 52, 24-34, 1983)
#include "global.hpp"
#include "particle_data.hpp"
#include "integrate.hpp"
Functions
void save_old_pos ()
Transfers the current particle positions from r.p[3] to r.p_pold[3] of the Particle structure.
void correct_pos_shake ()
Propagate velocity and position while using SHAKE algorithm for bond constraint.
void correct_vel_shake ()
Correction of current velocities using RATTLE algorithm.
int rigid_bond_set_params (int bond_type, double d, double p_tol, double v_tol)
set the parameter for a rigid, aka RATTLE bond
Variables
int n_rigidbonds
number of rigid bonds
Detailed Description
RATTLE Algorithm (Rattle: A "Velocity" Version of the Shake Algorithm for Molecular Dynamics Calculations, H.C Andersen, J Comp Phys, 52, 24-34, 1983)
For more information see rattle.c.
Definition in file rattle.hpp.
Function Documentation
void correct_pos_shake ()
Propagate velocity and position while using SHAKE algorithm for bond constraint.
Ghost Positions Update
Definition at line 210 of file rattle.cpp.
References app_pos_correction(), cell_structure, check_resort_particles(), CellStructure::collect_ghost_force_comm, comm_cart, compute_pos_corr_vec(), ghost_communicator(), init_correction_vector(), MPI_Bcast(), MPI_INT, MPI_Reduce(), MPI_SUM, runtimeError, SHAKE_MAX_ITERATIONS, this_node, and CellStructure::update_ghost_pos_comm.
Referenced by integrate_sd(), and integrate_vv().
void correct_vel_shake ()
Correction of current velocities using RATTLE algorithm.
transfer the current forces to r.p_old of the particle structure so that velocity corrections can be stored temporarily at the f.f[3] of the particle structure
Puts back the forces from r.p_old to f.f[3]
Definition at line 394 of file rattle.cpp.
References apply_vel_corr(), cell_structure, CellStructure::collect_ghost_force_comm, comm_cart, compute_vel_corr_vec(), errexit(), ghost_communicator(), init_correction_vector(), MPI_Bcast(), MPI_INT, MPI_Reduce(), MPI_SUM, revert_force(), SHAKE_MAX_ITERATIONS, this_node, transfer_force_init_vel(), and CellStructure::update_ghost_pos_comm.
Referenced by integrate_vv().
int rigid_bond_set_params (int bond_type, double d, double p_tol, double v_tol)
set the parameter for a rigid, aka RATTLE bond
Definition at line 468 of file rattle.cpp.
References bonded_ia_params, BONDED_IA_RIGID_BOND, Rigid_bond_parameters::d2, ES_ERROR, ES_OK, FIELD_RIGIDBONDS, make_bond_type_exist(), mpi_bcast_ia_params(), mpi_bcast_parameter(), n_rigidbonds, Bonded_ia_parameters::num, Bonded_ia_parameters::p, Rigid_bond_parameters::p_tol, Bond_parameters::rigid_bond, time_step, Bonded_ia_parameters::type, and Rigid_bond_parameters::v_tol.
Referenced by tclcommand_inter_parse_rigid_bond().
void save_old_pos ()
Transfers the current particle positions from r.p[3] to r.p_pold[3] of the Particle structure.
Invoked from correct_pos_shake()
Definition at line 69 of file rattle.cpp.
References CellPList::cell, ghost_cells, i, local_cells, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleList::part, and Particle::r.
Referenced by integrate_sd(), and integrate_vv().
Variable Documentation
int n_rigidbonds
number of rigid bonds
Definition at line 30 of file rattle.cpp.
Referenced by on_ghost_flags_change(), and rigid_bond_set_params().