ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: reaction_field.hpp File Reference
reaction_field.hpp File Reference
Routines to calculate the Reaction Field Energy or/and force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "mol_cut.hpp"
Data Structures
struct Reaction_field_params
Structure to hold Reaction Field Parameters.
Functions
Functions
int rf_set_params (double kappa, double epsilon1, double epsilon2, double r_cut)
void add_rf_coulomb_pair_force_no_cutoff (Particle *p1, Particle *p2, double d[3], double dist, double force[3])
void add_rf_coulomb_pair_force (Particle *p1, Particle *p2, double d[3], double dist, double force[3])
Computes the Reaction Field pair force and adds this force to the particle forces (see tclcommand_inter).
double rf_coulomb_pair_energy_no_cutoff (Particle *p1, Particle *p2, double dist)
double rf_coulomb_pair_energy (Particle *p1, Particle *p2, double dist)
int interrf_set_params (int part_type_a, int part_type_b, int rf_on)
void add_interrf_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double force[3])
double interrf_pair_energy (Particle *p1, Particle *p2, IA_parameters *ia_params, double dist)
Variables
Reaction_field_params rf_params
Structure containing the Reaction Field parameters.
Detailed Description
Routines to calculate the Reaction Field Energy or/and force for a particle pair.
M. Neumann, J. Chem. Phys 82, 5663 (1985) forces.cpp
Definition in file reaction_field.hpp.
Function Documentation
void add_interrf_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double force[3]) inline
Definition at line 117 of file reaction_field.hpp.
References add_rf_coulomb_pair_force_no_cutoff(), check_id, CUTOFF_CHECK, ParticleForce::f, Particle::f, ParticleProperties::identity, ONEPART_TRACE, Particle::p, Reaction_field_params::r_cut, IA_parameters::rf_on, and this_node.
Referenced by calc_non_bonded_pair_force_parts().
void add_rf_coulomb_pair_force (Particle * p1, Particle * p2, double d[3], double dist, double force[3]) inline
Computes the Reaction Field pair force and adds this force to the particle forces (see tclcommand_inter).
Parameters
p1 Pointer to first particle.
p2 Pointer to second/middle particle.
d Vector pointing from p1 to p2.
dist Distance between p1 and p2.
force returns the force on particle 1.
Definition at line 84 of file reaction_field.hpp.
References add_rf_coulomb_pair_force_no_cutoff(), and Reaction_field_params::r_cut.
Referenced by add_non_bonded_pair_force(), add_non_bonded_pair_virials(), and get_nonbonded_interaction().
void add_rf_coulomb_pair_force_no_cutoff (Particle * p1, Particle * p2, double d[3], double dist, double force[3]) inline
Definition at line 62 of file reaction_field.hpp.
References Reaction_field_params::B, check_id, coulomb, ParticleForce::f, Particle::f, ParticleProperties::identity, ONEPART_TRACE, Particle::p, Coulomb_parameters::prefactor, ParticleProperties::q, Reaction_field_params::r_cut, and this_node.
Referenced by add_interrf_pair_force(), and add_rf_coulomb_pair_force().
double interrf_pair_energy (Particle * p1, Particle * p2, IA_parameters * ia_params, double dist) inline
Definition at line 131 of file reaction_field.hpp.
References CUTOFF_CHECK, Reaction_field_params::r_cut, rf_coulomb_pair_energy_no_cutoff(), and IA_parameters::rf_on.
Referenced by calc_non_bonded_pair_energy().
int interrf_set_params (int part_type_a, int part_type_b, int rf_on)
Definition at line 53 of file reaction_field.cpp.
References ES_ERROR, ES_OK, get_ia_param_safe(), mpi_bcast_ia_params(), and IA_parameters::rf_on.
Referenced by tclcommand_inter_parse_interrf().
double rf_coulomb_pair_energy (Particle * p1, Particle * p2, double dist) inline
Definition at line 102 of file reaction_field.hpp.
References Reaction_field_params::r_cut, and rf_coulomb_pair_energy_no_cutoff().
Referenced by add_non_bonded_pair_energy().
double rf_coulomb_pair_energy_no_cutoff (Particle * p1, Particle * p2, double dist) inline
Definition at line 92 of file reaction_field.hpp.
References Reaction_field_params::B, coulomb, Particle::p, Coulomb_parameters::prefactor, ParticleProperties::q, and Reaction_field_params::r_cut.
Referenced by interrf_pair_energy(), and rf_coulomb_pair_energy().
int rf_set_params (double kappa, double epsilon1, double epsilon2, double r_cut)
Definition at line 30 of file reaction_field.cpp.
References Reaction_field_params::B, Reaction_field_params::epsilon1, Reaction_field_params::epsilon2, Reaction_field_params::kappa, mpi_bcast_coulomb_params(), Reaction_field_params::r_cut, and rf_params.
Referenced by tclcommand_inter_coulomb_parse_rf().
Variable Documentation
Reaction_field_params rf_params
Structure containing the Reaction Field parameters.
Definition at line 87 of file interaction_data.cpp.
Referenced by mpi_bcast_coulomb_params_slave(), rf_set_params(), and tclprint_to_result_rf().