ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: reaction.cpp File Reference
reaction.cpp File Reference
#include "utils.hpp"
#include "reaction.hpp"
#include "initialize.hpp"
#include "forces.hpp"
#include "errorhandling.hpp"
#include "cells.hpp"
#include "domain_decomposition.hpp"
Functions
void reactions_sanity_checks ()
sanity checks for the reaction code
void local_setup_reaction ()
broadcasts reaction parameters and sets up an entry in the ia_params, so that the verlet radius is equal or bigger than the reaction range.
void integrate_reaction ()
Variables
reaction_struct reaction
Function Documentation
void integrate_reaction ()
Definition at line 89 of file reaction.cpp.
References ParticleProperties::catalyzer_count, reaction_struct::catalyzer_type, CellPList::cell, DomainDecomposition::cell_inter, reaction_struct::ct_rate, d_random(), dd, reaction_struct::eq_rate, get_mi_vector(), i, local_cells, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, on_observable_calc(), on_particle_change(), ParticlePosition::p, Particle::p, PairList::pair, ParticleList::part, reaction_struct::product_type, Particle::r, reaction_struct::range, reaction_struct::reactant_type, reaction_struct::sing_mult, sqrlen(), time_step, ParticleProperties::type, and IA_Neighbor::vList.
Referenced by integrate_sd(), and integrate_vv().
void local_setup_reaction ()
broadcasts reaction parameters and sets up an entry in the ia_params, so that the verlet radius is equal or bigger than the reaction range.
Definition at line 57 of file reaction.cpp.
References reaction_struct::catalyzer_type, comm_cart, reaction_struct::ct_rate, reaction_struct::eq_rate, get_ia_param_safe(), make_particle_type_exist(), MPI_Bcast(), mpi_bcast_ia_params(), MPI_DOUBLE, MPI_INT, reaction_struct::product_type, reaction_struct::range, reaction_struct::reactant_type, IA_parameters::REACTION_range, runtimeError, and reaction_struct::sing_mult.
Referenced by mpi_setup_reaction(), and mpi_setup_reaction_slave().
void reactions_sanity_checks ()
sanity checks for the reaction code
Definition at line 37 of file reaction.cpp.
References cell_structure, CELL_STRUCTURE_DOMDEC, reaction_struct::ct_rate, dd, max_cut, reaction_struct::range, runtimeError, CellStructure::type, and DomainDecomposition::use_vList.
Referenced by on_integration_start().
Variable Documentation
reaction_struct reaction
Definition at line 33 of file reaction.cpp.
Referenced by on_program_start(), tcl_command_reaction_print(), and tclcommand_reaction().