ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: readpdb_tcl.cpp File Reference
readpdb_tcl.cpp File Reference
#include <iostream>
#include <vector>
#include "readpdb.hpp"
#include "parser.hpp"
Functions
static void usage (Tcl_Interp *interp)
int tclcommand_readpdb (ClientData data, Tcl_Interp *interp, int argc, char *argv[])
Reads particles from pdb file, see readpdb.cpp.
Function Documentation
int tclcommand_readpdb (ClientData data, Tcl_Interp * interp, int argc, char * argv[])
Reads particles from pdb file, see readpdb.cpp.
Definition at line 35 of file readpdb_tcl.cpp.
References ARG0_IS_D, ARG0_IS_I, ARG0_IS_S, PdbLJInteraction::epsilon, n_part, PdbLJInteraction::other_type, pdb_add_particles_from_file(), PdbLJInteraction::sigma, and usage().
Referenced by tcl_register_commands().
static void usage (Tcl_Interp * interp) static
Definition at line 31 of file readpdb_tcl.cpp.
Referenced by tclcommand_readpdb().