ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: readpdb.hpp File Reference
readpdb.hpp File Reference
#include "PdbParser.hpp"
#include "particle_data.hpp"
Data Structures
struct PdbLJInteraction
Functions
int pdb_add_particles_from_file (char *pdb_file, int first_id, int type, std::vector< PdbLJInteraction > &ljInteractions, double lj_rel_cutoff=2.5, char *itp_file=NULL, int first_type=0, bool fit=false, bool lj_internal=false, bool lj_diagonal=false)
Call only on the master node: Parse pdb file and add contained particles.
Function Documentation
int pdb_add_particles_from_file (char * pdb_file, int first_id, int type, std::vector< PdbLJInteraction > & ljInteractions, double lj_rel_cutoff = 2.5, char * itp_file = NULL, int first_type = 0, bool fit = false, bool lj_internal = false, bool lj_diagonal = false)
Call only on the master node: Parse pdb file and add contained particles.
Parameters
pdb_file Filename of the pdb file. Id of the first particle to add. Type for the particles. Should lj iteractions be added from the itp file. Should the box be rescaled to hold the particles. Should LJ interactions within the molecule be added. Just the diagonal interaction terms oh lj_internal.
Returns
Number of particles that were added.
Definition at line 142 of file readpdb.cpp.
References add_lj_interaction(), add_lj_internal(), add_particles(), PdbParser::PdbParser::itp_atoms, PdbParser::PdbParser::itp_atomtypes, n_part, PdbParser::PdbParser::parse_itp_file(), and PdbParser::PdbParser::parse_pdb_file().
Referenced by tclcommand_readpdb().