ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: readpdb.cpp File Reference
readpdb.cpp File Reference
#include "readpdb.hpp"
#include "grid.hpp"
#include "lj.hpp"
#include <iostream>
#include <cmath>
#include <set>
Macros
#define READPDB_TRACE(A)
Functions
static void add_lj_interaction (std::set< PdbParser::itp_atomtype, PdbParser::itp_atomtype_compare > &types, std::vector< PdbLJInteraction > interactions, const double rel_cutoff)
static void add_lj_internal (std::set< PdbParser::itp_atomtype, PdbParser::itp_atomtype_compare > &types, const double rel_cutoff, bool only_diagonal)
static int add_particles (PdbParser::PdbParser &parser, int first_id, int default_type, std::set< PdbParser::itp_atomtype, PdbParser::itp_atomtype_compare > &seen_types, int first_type=0, bool fit=false)
int pdb_add_particles_from_file (char *pdb_file, int first_id, int type, std::vector< PdbLJInteraction > &ljInteractions, double lj_rel_cutoff, char *itp_file, int first_type, bool fit, bool lj_internal, bool lj_diagonal)
Call only on the master node: Parse pdb file and add contained particles.
Macro Definition Documentation
#define READPDB_TRACE (A)
Definition at line 12 of file readpdb.cpp.
Referenced by add_lj_interaction(), add_lj_internal(), and add_particles().
Function Documentation
static void add_lj_interaction (std::set< PdbParser::itp_atomtype, PdbParser::itp_atomtype_compare > & types, std::vector< PdbLJInteraction > interactions, const double rel_cutoff) static
Definition at line 17 of file readpdb.cpp.
References lennard_jones_set_params(), and READPDB_TRACE.
Referenced by pdb_add_particles_from_file().
static void add_lj_internal (std::set< PdbParser::itp_atomtype, PdbParser::itp_atomtype_compare > & types, const double rel_cutoff, bool only_diagonal) static
Definition at line 37 of file readpdb.cpp.
References lennard_jones_set_params(), and READPDB_TRACE.
Referenced by pdb_add_particles_from_file().
static int add_particles (PdbParser::PdbParser & parser, int first_id, int default_type, std::set< PdbParser::itp_atomtype, PdbParser::itp_atomtype_compare > & seen_types, int first_type = 0, bool fit = false) static
Definition at line 61 of file readpdb.cpp.
References box_l, PdbParser::PdbParser::calc_bounding_box(), ES_PART_CREATED, ES_PART_ERROR, ES_PART_OK, PdbParser::itp_atomtype::espresso_id, i, PdbParser::itp_atomtype::id, PdbParser::PdbParser::itp_atoms, PdbParser::PdbParser::itp_atomtypes, PdbParser::BoundingBox::llx, PdbParser::BoundingBox::lly, PdbParser::BoundingBox::llz, PdbParser::PdbParser::pdb_atoms, place_particle(), READPDB_TRACE, rescale_boxl(), set_particle_q(), set_particle_type(), PdbParser::BoundingBox::urx, PdbParser::BoundingBox::ury, and PdbParser::BoundingBox::urz.
Referenced by pdb_add_particles_from_file().
int pdb_add_particles_from_file (char * pdb_file, int first_id, int type, std::vector< PdbLJInteraction > & ljInteractions, double lj_rel_cutoff = 2.5, char * itp_file = NULL, int first_type = 0, bool fit = false, bool lj_internal = false, bool lj_diagonal = false)
Call only on the master node: Parse pdb file and add contained particles.
Parameters
pdb_file Filename of the pdb file. Id of the first particle to add. Type for the particles. Should lj iteractions be added from the itp file. Should the box be rescaled to hold the particles. Should LJ interactions within the molecule be added. Just the diagonal interaction terms oh lj_internal.
Returns
Number of particles that were added.
Definition at line 142 of file readpdb.cpp.
References add_lj_interaction(), add_lj_internal(), add_particles(), PdbParser::PdbParser::itp_atoms, PdbParser::PdbParser::itp_atomtypes, n_part, PdbParser::PdbParser::parse_itp_file(), and PdbParser::PdbParser::parse_pdb_file().
Referenced by tclcommand_readpdb().