ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: rotation.cpp File Reference
rotation.cpp File Reference
Molecular dynamics integrator for rotational motion.
#include <mpi.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include "utils.hpp"
#include "integrate.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "cells.hpp"
#include "verlet.hpp"
#include "rotation.hpp"
#include "ghosts.hpp"
#include "forces.hpp"
#include "p3m.hpp"
#include "thermostat.hpp"
#include "initialize.hpp"
#include "cuda_interface.hpp"
Functions
int convert_quatu_to_quat (double d[3], double quat[4])
convert quaternions to the director
void define_rotation_matrix (Particle *p, double A[9])
Here we use quaternions to calculate the rotation matrix which will be used then to transform torques from the laboratory to the body-fixed frames.
void propagate_omega_quat_particle (Particle *p)
propagate angular velocities and quaternions
void convert_torques_propagate_omega ()
convert the torques to the body-fixed frames and propagate angular velocities
void convert_initial_torques ()
convert the torques to the body-fixed frames before the integration loop
void convert_omega_body_to_space (Particle *p, double *omega)
convert from the body-fixed frames to space-fixed coordinates
void convert_torques_body_to_space (Particle *p, double *torque)
void convert_vel_space_to_body (Particle *p, double *vel_body)
convert velocity form the lab-fixed coordinates to the body-fixed frame
void multiply_quaternions (double a[4], double b[4], double result[4])
Multiply two quaternions.
Privat Functions
static void define_Qdd (Particle *p, double Qd[4], double Qdd[4], double S[3], double Wd[3])
define first and second time derivatives of a quaternion, as well as the angular acceleration.
Variables
static double I [3] = { 1, 1, 1}
moment of inertia.
Detailed Description
Molecular dynamics integrator for rotational motion.
A velocity Verlet algorithm using quaternions is implemented to tackle rotational motion. A random torque and a friction term are added to provide the constant NVT conditions. Due to this feature all particles are treated as 3D objects with 3 translational and 3 rotational degrees of freedom if ROTATION flag is set in config.h.
Definition in file rotation.cpp.
Function Documentation
void convert_initial_torques ()
convert the torques to the body-fixed frames before the integration loop
Convert torques to the body-fixed frame to start the integration loop.
Definition at line 376 of file rotation.cpp.
References CellPList::cell, check_id, define_rotation_matrix(), ParticleForce::f, Particle::f, friction_thermo_langevin_rotation(), i, INTEG_TRACE, local_cells, Particle::m, CellPList::n, ParticleList::n, ONEPART_TRACE, ParticleList::part, THERMO_LANGEVIN, thermo_switch, this_node, ParticleForce::torque, and ParticleMomentum::v.
Referenced by integrate_sd(), and integrate_vv().
void convert_omega_body_to_space (Particle * p, double * omega)
convert from the body-fixed frames to space-fixed coordinates
convert angular velocities and torques from the body-fixed frames to space-fixed coordinates
Definition at line 419 of file rotation.cpp.
References define_rotation_matrix(), Particle::m, and ParticleMomentum::omega.
Referenced by tclcommand_part_print_omega_lab_frame(), and update_mol_vel_particle().
int convert_quatu_to_quat (double d[3], double quat[4])
convert quaternions to the director
Convert director to quaternions.
Convert director to quaternions
Definition at line 76 of file rotation.cpp.
References PI, and ROUND_ERROR_PREC.
Referenced by convert_dip_to_quat(), and vs_relate_to().
void convert_torques_body_to_space (Particle * p, double * torque)
Definition at line 429 of file rotation.cpp.
References define_rotation_matrix(), Particle::f, and ParticleForce::torque.
Referenced by tclcommand_part_print_torque_lab_frame().
void convert_torques_propagate_omega ()
convert the torques to the body-fixed frames and propagate angular velocities
Convert torques to the body-fixed frame and propogate angular velocities.
Definition at line 242 of file rotation.cpp.
References CellPList::cell, check_id, copy_v_cs_from_GPU(), cross(), define_rotation_matrix(), ParticleParametersSwimming::dipole_length, ParticleForce::f, Particle::f, friction_thermo_langevin_rotation(), I, i, ifParticleIsVirtual(), INTEG_TRACE, LATTICE_LB_GPU, lattice_switch, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleMomentum::omega, ONEPART_TRACE, Particle::p, ParticleList::part, ParticlePosition::quatu, Particle::r, ParticleProperties::rinertia, ParticleParametersSwimming::rotational_friction, Particle::swim, THERMO_LANGEVIN, thermo_switch, this_node, time_step_half, ParticleForce::torque, ParticleMomentum::v, ParticleParametersSwimming::v_center, and ParticleParametersSwimming::v_source.
Referenced by integrate_vv().
void convert_vel_space_to_body (Particle * p, double * vel_body)
convert velocity form the lab-fixed coordinates to the body-fixed frame
Definition at line 439 of file rotation.cpp.
References define_rotation_matrix(), Particle::m, and ParticleMomentum::v.
Referenced by tclcommand_part_print_v_body().
void define_Qdd (Particle * p, double Qd[4], double Qdd[4], double S[3], double Wd[3]) static
define first and second time derivatives of a quaternion, as well as the angular acceleration.
calculate the second derivative of the quaternion of a given particle as well as Wd vector which is the angular acceleration of this particle
Definition at line 150 of file rotation.cpp.
References Particle::f, I, Particle::m, ParticleMomentum::omega, Particle::p, ParticlePosition::quat, Particle::r, ParticleProperties::rinertia, and ParticleForce::torque.
Referenced by propagate_omega_quat_particle().
void define_rotation_matrix (Particle * p, double A[9])
Here we use quaternions to calculate the rotation matrix which will be used then to transform torques from the laboratory to the body-fixed frames.
Definition at line 121 of file rotation.cpp.
References ParticlePosition::quat, and Particle::r.
Referenced by convert_initial_torques(), convert_omega_body_to_space(), convert_torques_body_to_space(), convert_torques_propagate_omega(), convert_vel_space_to_body(), observable_calc_particle_angular_momentum(), observable_calc_particle_body_velocities(), set_particle_omega_lab(), and set_particle_torque_lab().
void multiply_quaternions (double a[4], double b[4], double result[4])
Multiply two quaternions.
Definition at line 451 of file rotation.cpp.
Referenced by update_mol_pos_particle(), update_mol_vel_particle(), and vs_relate_to().
void propagate_omega_quat_particle (Particle * p)
propagate angular velocities and quaternions
Propagate angular velocities and update quaternions on a particle.
Todo:
implement for fixed_coord_flag
Definition at line 208 of file rotation.cpp.
References check_id, convert_quat_to_quatu(), convert_quatu_to_dip(), define_Qdd(), ParticlePosition::dip, ParticleProperties::dipm, ParticleProperties::identity, Particle::m, ParticleMomentum::omega, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticlePosition::quat, ParticlePosition::quatu, Particle::r, ParticleProperties::rotation, this_node, time_step, time_step_half, time_step_squared, time_step_squared_half, and ParticleMomentum::v.
Referenced by propagate_pos_sd(), propagate_vel(), and propagate_vel_pos().
Variable Documentation
double I[3] = { 1, 1, 1} static
moment of inertia.
Currently we define the inertia tensor here to be constant. If it is not spherical the angular velocities have to be refined several times in the convert_torques_propagate_omega. Also the kinetic energy in file statistics.cpp is calculated assuming that I[0] = I[1] = I[2] = 1
Definition at line 62 of file rotation.cpp.
Referenced by convert_torques_propagate_omega(), and define_Qdd().