ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: rotation.hpp File Reference
rotation.hpp File Reference
This file contains all subroutines required to process rotational motion.
#include "utils.hpp"
#include "particle_data.hpp"
#include "thermostat.hpp"
#include "gb.hpp"
Functions
void propagate_omega_quat_particle (Particle *p)
Propagate angular velocities and update quaternions on a particle.
void convert_torques_propagate_omega ()
Convert torques to the body-fixed frame and propogate angular velocities.
void convert_initial_torques ()
Convert torques to the body-fixed frame to start the integration loop.
void convert_omega_body_to_space (Particle *p, double *omega)
convert angular velocities and torques from the body-fixed frames to space-fixed coordinates
void convert_torques_body_to_space (Particle *p, double *torque)
void convert_vel_space_to_body (Particle *p, double *vel_body)
convert velocity form the lab-fixed coordinates to the body-fixed frame
void define_rotation_matrix (Particle *p, double A[9])
Here we use quaternions to calculate the rotation matrix which will be used then to transform torques from the laboratory to the body-fixed frames.
void convert_quat_to_quatu (double quat[4], double quatu[3])
void multiply_quaternions (double a[4], double b[4], double result[4])
Multiply two quaternions.
int convert_quatu_to_quat (double d[3], double quat[4])
Convert director to quaternions.
int convert_dip_to_quat (double dip[3], double quat[4], double *dipm)
convert a dipole moment to quaternions and dipolar strength
void convert_quatu_to_dip (double quatu[3], double dipm, double dip[3])
convert quaternion director to the dipole moment
Detailed Description
This file contains all subroutines required to process rotational motion.
Definition in file rotation.hpp.
Function Documentation
int convert_dip_to_quat (double dip[3], double quat[4], double * dipm) inline
convert a dipole moment to quaternions and dipolar strength
Definition at line 82 of file rotation.hpp.
References convert_quatu_to_quat().
Referenced by mpi_send_dip(), and mpi_send_dip_slave().
void convert_initial_torques ()
Convert torques to the body-fixed frame to start the integration loop.
Convert torques to the body-fixed frame to start the integration loop.
Definition at line 376 of file rotation.cpp.
References CellPList::cell, check_id, define_rotation_matrix(), ParticleForce::f, Particle::f, friction_thermo_langevin_rotation(), i, INTEG_TRACE, local_cells, Particle::m, CellPList::n, ParticleList::n, ONEPART_TRACE, ParticleList::part, THERMO_LANGEVIN, thermo_switch, this_node, ParticleForce::torque, and ParticleMomentum::v.
Referenced by integrate_sd(), and integrate_vv().
void convert_omega_body_to_space (Particle * p, double * omega)
convert angular velocities and torques from the body-fixed frames to space-fixed coordinates
convert angular velocities and torques from the body-fixed frames to space-fixed coordinates
Definition at line 419 of file rotation.cpp.
References define_rotation_matrix(), Particle::m, and ParticleMomentum::omega.
Referenced by tclcommand_part_print_omega_lab_frame(), and update_mol_vel_particle().
void convert_quat_to_quatu (double quat[4], double quatu[3]) inline
Definition at line 63 of file rotation.hpp.
Referenced by mpi_send_dip(), mpi_send_dip_slave(), mpi_send_quat(), mpi_send_quat_slave(), propagate_omega_quat_particle(), update_mol_pos_particle(), and update_mol_vel_particle().
void convert_quatu_to_dip (double quatu[3], double dipm, double dip[3]) inline
convert quaternion director to the dipole moment
Definition at line 94 of file rotation.hpp.
Referenced by mpi_send_dipm(), mpi_send_dipm_slave(), mpi_send_quat(), mpi_send_quat_slave(), and propagate_omega_quat_particle().
int convert_quatu_to_quat (double d[3], double quat[4])
Convert director to quaternions.
Convert director to quaternions.
Convert director to quaternions
Definition at line 76 of file rotation.cpp.
References PI, and ROUND_ERROR_PREC.
Referenced by convert_dip_to_quat(), and vs_relate_to().
void convert_torques_body_to_space (Particle * p, double * torque)
Definition at line 429 of file rotation.cpp.
References define_rotation_matrix(), Particle::f, and ParticleForce::torque.
Referenced by tclcommand_part_print_torque_lab_frame().
void convert_torques_propagate_omega ()
Convert torques to the body-fixed frame and propogate angular velocities.
Convert torques to the body-fixed frame and propogate angular velocities.
Definition at line 242 of file rotation.cpp.
References CellPList::cell, check_id, copy_v_cs_from_GPU(), cross(), define_rotation_matrix(), ParticleParametersSwimming::dipole_length, ParticleForce::f, Particle::f, friction_thermo_langevin_rotation(), I, i, ifParticleIsVirtual(), INTEG_TRACE, LATTICE_LB_GPU, lattice_switch, local_cells, Particle::m, CellPList::n, ParticleList::n, ParticleMomentum::omega, ONEPART_TRACE, Particle::p, ParticleList::part, ParticlePosition::quatu, Particle::r, ParticleProperties::rinertia, ParticleParametersSwimming::rotational_friction, Particle::swim, THERMO_LANGEVIN, thermo_switch, this_node, time_step_half, ParticleForce::torque, ParticleMomentum::v, ParticleParametersSwimming::v_center, and ParticleParametersSwimming::v_source.
Referenced by integrate_vv().
void convert_vel_space_to_body (Particle * p, double * vel_body)
convert velocity form the lab-fixed coordinates to the body-fixed frame
Definition at line 439 of file rotation.cpp.
References define_rotation_matrix(), Particle::m, and ParticleMomentum::v.
Referenced by tclcommand_part_print_v_body().
void define_rotation_matrix (Particle * p, double A[9])
Here we use quaternions to calculate the rotation matrix which will be used then to transform torques from the laboratory to the body-fixed frames.
Definition at line 121 of file rotation.cpp.
References ParticlePosition::quat, and Particle::r.
Referenced by convert_initial_torques(), convert_omega_body_to_space(), convert_torques_body_to_space(), convert_torques_propagate_omega(), convert_vel_space_to_body(), observable_calc_particle_angular_momentum(), observable_calc_particle_body_velocities(), set_particle_omega_lab(), and set_particle_torque_lab().
void multiply_quaternions (double a[4], double b[4], double result[4])
Multiply two quaternions.
Definition at line 451 of file rotation.cpp.
Referenced by update_mol_pos_particle(), update_mol_vel_particle(), and vs_relate_to().
void propagate_omega_quat_particle (Particle * p)
Propagate angular velocities and update quaternions on a particle.
Propagate angular velocities and update quaternions on a particle.
Todo:
implement for fixed_coord_flag
Definition at line 208 of file rotation.cpp.
References check_id, convert_quat_to_quatu(), convert_quatu_to_dip(), define_Qdd(), ParticlePosition::dip, ParticleProperties::dipm, ParticleProperties::identity, Particle::m, ParticleMomentum::omega, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticlePosition::quat, ParticlePosition::quatu, Particle::r, ParticleProperties::rotation, this_node, time_step, time_step_half, time_step_squared, time_step_squared_half, and ParticleMomentum::v.
Referenced by propagate_pos_sd(), propagate_vel(), and propagate_vel_pos().