ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: soft_sphere.hpp File Reference
soft_sphere.hpp File Reference
Routines to calculate the soft-sphere energy and/or force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "mol_cut.hpp"
Functions
int soft_sphere_set_params (int part_type_a, int part_type_b, double a, double n, double cut, double offset)
double soft_force_r (double a, double n, double r)
Resultant Force due to a soft-sphere potential between two particles at interatomic separation r.
double soft_energy_r (double a, double n, double r)
Potential Energy due to a soft-sphere potential between two particles at interatomic separation r.
void add_soft_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double force[3])
Calculate soft-sphere potential force between particle p1 and p2.
double soft_pair_energy (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist)
calculate soft-sphere energy between particle p1 and p2.
Detailed Description
Routines to calculate the soft-sphere energy and/or force for a particle pair.
forces.cpp
Definition in file soft_sphere.hpp.
Function Documentation
void add_soft_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double force[3]) inline
Calculate soft-sphere potential force between particle p1 and p2.
Definition at line 56 of file soft_sphere.hpp.
References check_id, CUTOFF_CHECK, ParticleForce::f, Particle::f, ParticleProperties::identity, ONEPART_TRACE, Particle::p, IA_parameters::soft_a, soft_force_r(), IA_parameters::soft_n, IA_parameters::soft_offset, and this_node.
Referenced by calc_non_bonded_pair_force_parts().
double soft_energy_r (double a, double n, double r) inline
Potential Energy due to a soft-sphere potential between two particles at interatomic separation r.
Definition at line 50 of file soft_sphere.hpp.
Referenced by soft_pair_energy().
double soft_force_r (double a, double n, double r) inline
Resultant Force due to a soft-sphere potential between two particles at interatomic separation r.
Definition at line 43 of file soft_sphere.hpp.
Referenced by add_soft_pair_force().
double soft_pair_energy (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist) inline
calculate soft-sphere energy between particle p1 and p2.
Definition at line 81 of file soft_sphere.hpp.
References CUTOFF_CHECK, IA_parameters::soft_a, soft_energy_r(), IA_parameters::soft_n, and IA_parameters::soft_offset.
Referenced by calc_non_bonded_pair_energy().
int soft_sphere_set_params (int part_type_a, int part_type_b, double a, double n, double cut, double offset)
Definition at line 30 of file soft_sphere.cpp.
References ES_ERROR, ES_OK, get_ia_param_safe(), mpi_bcast_ia_params(), IA_parameters::soft_a, IA_parameters::soft_cut, IA_parameters::soft_n, and IA_parameters::soft_offset.
Referenced by tclcommand_inter_parse_soft().