ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: soft_sphere.cpp File Reference
soft_sphere.cpp File Reference
Implementation of soft_sphere.hpp.
#include "soft_sphere.hpp"
#include "communication.hpp"
Functions
int soft_sphere_set_params (int part_type_a, int part_type_b, double a, double n, double cut, double offset)
Detailed Description
Implementation of soft_sphere.hpp.
Definition in file soft_sphere.cpp.
Function Documentation
int soft_sphere_set_params (int part_type_a, int part_type_b, double a, double n, double cut, double offset)
Definition at line 30 of file soft_sphere.cpp.
References ES_ERROR, ES_OK, get_ia_param_safe(), mpi_bcast_ia_params(), IA_parameters::soft_a, IA_parameters::soft_cut, IA_parameters::soft_n, and IA_parameters::soft_offset.
Referenced by tclcommand_inter_parse_soft().