ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: specfunc_cuda.hpp File Reference
specfunc_cuda.hpp File Reference
#include "config.hpp"
Functions
__device__ mmm1dgpu_real evaluateAsChebychevSeriesAt (mmm1dgpu_real *c, int n, mmm1dgpu_real x)
__device__ mmm1dgpu_real evaluateAsTaylorSeriesAt (mmm1dgpu_real *c, int n, mmm1dgpu_real x)
__device__ mmm1dgpu_real dev_K0 (mmm1dgpu_real x)
__device__ mmm1dgpu_real dev_K1 (mmm1dgpu_real x)
Variables
const mmm1dgpu_real M_LN2f = M_LN2
static __constant__ mmm1dgpu_real bk0_data [11]
static __constant__ int bk0_size = 11
static __constant__ mmm1dgpu_real ak0_data [17]
static __constant__ int ak0_size = 16
static __constant__ mmm1dgpu_real ak02_data [14]
static __constant__ int ak02_size = 13
static __constant__ mmm1dgpu_real bi0_data [12]
static __constant__ int bi0_size = 12
static __constant__ mmm1dgpu_real bk1_data [11]
static __constant__ int bk1_size = 11
static __constant__ mmm1dgpu_real ak1_data [17]
static __constant__ int ak1_size = 17
static __constant__ mmm1dgpu_real ak12_data [14]
static __constant__ int ak12_size = 14
static __constant__ mmm1dgpu_real bi1_data [11]
static __constant__ int bi1_size = 11
Function Documentation
__device__ mmm1dgpu_real dev_K0 (mmm1dgpu_real x)
Definition at line 187 of file specfunc_cuda.hpp.
References ak02_data, ak02_size, ak0_data, ak0_size, bi0_data, bi0_size, bk0_data, bk0_size, evaluateAsChebychevSeriesAt(), I0(), and M_LN2f.
Referenced by energiesKernel(), and forcesKernel().
__device__ mmm1dgpu_real dev_K1 (mmm1dgpu_real x)
Definition at line 201 of file specfunc_cuda.hpp.
References ak12_data, ak12_size, ak1_data, ak1_size, bi1_data, bi1_size, bk1_data, bk1_size, evaluateAsChebychevSeriesAt(), I1(), and M_LN2f.
Referenced by besselTuneKernel(), and forcesKernel().
__device__ mmm1dgpu_real evaluateAsChebychevSeriesAt (mmm1dgpu_real * c, int n, mmm1dgpu_real x)
Definition at line 164 of file specfunc_cuda.hpp.
References dd.
Referenced by dev_K0(), dev_K1(), I0(), I1(), K0(), and K1().
__device__ mmm1dgpu_real evaluateAsTaylorSeriesAt (mmm1dgpu_real * c, int n, mmm1dgpu_real x)
Definition at line 178 of file specfunc_cuda.hpp.
Referenced by dev_mod_psi_even(), dev_mod_psi_odd(), mod_psi_even(), and mod_psi_odd().
Variable Documentation
__constant__ mmm1dgpu_real ak02_data[14] static
Initial value:
= {
  2.5 -0.01201869826307592,
  -0.00917485269102569,
   0.00014445509317750,
  -0.00000401361417543,
   0.00000015678318108,
  -0.00000000777011043,
   0.00000000046111825,
  -0.00000000003158592,
   0.00000000000243501,
  -0.00000000000020743,
   0.00000000000001925,
  -0.00000000000000192,
   0.00000000000000020,
  -0.00000000000000002
}
Definition at line 61 of file specfunc_cuda.hpp.
Referenced by dev_K0().
__constant__ int ak02_size = 13 static
Definition at line 77 of file specfunc_cuda.hpp.
Referenced by dev_K0().
__constant__ mmm1dgpu_real ak0_data[17] static
Initial value:
= {
  2.5 -0.07643947903327941,
  -0.02235652605699819,
   0.00077341811546938,
  -0.00004281006688886,
   0.00000308170017386,
  -0.00000026393672220,
   0.00000002563713036,
  -0.00000000274270554,
   0.00000000031694296,
  -0.00000000003902353,
   0.00000000000506804,
  -0.00000000000068895,
   0.00000000000009744,
  -0.00000000000001427,
   0.00000000000000215,
  -0.00000000000000033,
   0.00000000000000005
}
Definition at line 40 of file specfunc_cuda.hpp.
Referenced by dev_K0().
__constant__ int ak0_size = 16 static
Definition at line 59 of file specfunc_cuda.hpp.
Referenced by dev_K0().
__constant__ mmm1dgpu_real ak12_data[14] static
Initial value:
= {
  2.5 +0.06379308343739001,
   0.02832887813049721,
  -0.00024753706739052,
   0.00000577197245160,
  -0.00000020689392195,
   0.00000000973998344,
  -0.00000000055853361,
   0.00000000003732996,
  -0.00000000000282505,
   0.00000000000023720,
  -0.00000000000002176,
   0.00000000000000215,
  -0.00000000000000022,
   0.00000000000000002
}
Definition at line 131 of file specfunc_cuda.hpp.
Referenced by dev_K1().
__constant__ int ak12_size = 14 static
Definition at line 147 of file specfunc_cuda.hpp.
Referenced by dev_K1().
__constant__ mmm1dgpu_real ak1_data[17] static
Initial value:
= {
  2.5 +0.27443134069738830,
   0.07571989953199368,
  -0.00144105155647540,
   0.00006650116955125,
  -0.00000436998470952,
   0.00000035402774997,
  -0.00000003311163779,
   0.00000000344597758,
  -0.00000000038989323,
   0.00000000004720819,
  -0.00000000000604783,
   0.00000000000081284,
  -0.00000000000011386,
   0.00000000000001654,
  -0.00000000000000248,
   0.00000000000000038,
  -0.00000000000000006
}
Definition at line 110 of file specfunc_cuda.hpp.
Referenced by dev_K1().
__constant__ int ak1_size = 17 static
Definition at line 129 of file specfunc_cuda.hpp.
Referenced by dev_K1().
__constant__ mmm1dgpu_real bi0_data[12] static
Initial value:
= {
  5.5 -.07660547252839144951,
  1.92733795399380827000,
   .22826445869203013390,
   .01304891466707290428,
   .00043442709008164874,
   .00000942265768600193,
   .00000014340062895106,
   .00000000161384906966,
   .00000000001396650044,
   .00000000000009579451,
   .00000000000000053339,
   .00000000000000000245
}
Definition at line 79 of file specfunc_cuda.hpp.
Referenced by dev_K0().
__constant__ int bi0_size = 12 static
Definition at line 93 of file specfunc_cuda.hpp.
Referenced by dev_K0().
__constant__ mmm1dgpu_real bi1_data[11] static
Initial value:
= {
  1.75 -0.001971713261099859,
   0.407348876675464810,
   0.034838994299959456,
   0.001545394556300123,
   0.000041888521098377,
   0.000000764902676483,
   0.000000010042493924,
   0.000000000099322077,
   0.000000000000766380,
   0.000000000000004741,
   0.000000000000000024
}
Definition at line 149 of file specfunc_cuda.hpp.
Referenced by dev_K1().
__constant__ int bi1_size = 11 static
Definition at line 162 of file specfunc_cuda.hpp.
Referenced by dev_K1().
__constant__ mmm1dgpu_real bk0_data[11] static
Initial value:
= {
  -.5 -0.03532739323390276872,
   0.3442898999246284869,
   0.03597993651536150163,
   0.00126461541144692592,
   0.00002286212103119451,
   0.00000025347910790261,
   0.00000000190451637722,
   0.00000000001034969525,
   0.00000000000004259816,
   0.00000000000000013744,
   0.00000000000000000035
}
Definition at line 25 of file specfunc_cuda.hpp.
Referenced by dev_K0().
__constant__ int bk0_size = 11 static
Definition at line 38 of file specfunc_cuda.hpp.
Referenced by dev_K0().
__constant__ mmm1dgpu_real bk1_data[11] static
Initial value:
= {
  1.5 +0.0253002273389477705,
  -0.3531559607765448760,
  -0.1226111808226571480,
  -0.0069757238596398643,
  -0.0001730288957513052,
  -0.0000024334061415659,
  -0.0000000221338763073,
  -0.0000000001411488392,
  -0.0000000000006666901,
  -0.0000000000000024274,
  -0.0000000000000000070
}
Definition at line 95 of file specfunc_cuda.hpp.
Referenced by dev_K1().
__constant__ int bk1_size = 11 static
Definition at line 108 of file specfunc_cuda.hpp.
Referenced by dev_K1().
const mmm1dgpu_real M_LN2f = M_LN2
Definition at line 21 of file specfunc_cuda.hpp.
Referenced by dev_K0(), and dev_K1().