ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: specfunc.cpp File Reference
specfunc.cpp File Reference
Special functions, see specfunc.h.
#include <cmath>
#include "utils.hpp"
#include "specfunc.hpp"
#include "polynom.hpp"
Functions
double hzeta (double s, double q)
Hurwitz zeta function.
double I0 (double x)
Modified Bessel function of first kind, order 0.
double K0 (double x)
Modified Bessel function of second kind, order 0.
double I1 (double x)
Modified Bessel function of first kind, order 1.
double K1 (double x)
Modified Bessel function of second kind, order 1.
double LPK0 (double x)
Besselfunctions K0 at x.
double LPK1 (double x)
Besselfunctions K1 at x.
void LPK01 (double x, double *K0, double *K1)
Besselfunctions K0 and K1 at x.
Variables
static double bk0_data [11]
static Polynom bk0_cs = { bk0_data, 11, 11 }
static double ak0_data [17]
static Polynom ak0_cs = { ak0_data, 16, 16 }
static double ak02_data [14]
static Polynom ak02_cs = { ak02_data, 13, 13 }
static double bi0_data [12]
static Polynom bi0_cs = { bi0_data, 12, 12 }
static double ai0_data [21]
static Polynom ai0_cs = { ai0_data, 21, 21 }
static double ai02_data [22]
static Polynom ai02_cs = { ai02_data, 22, 22 }
static double bk1_data [11]
static Polynom bk1_cs = { bk1_data, 11, 11 }
static double ak1_data [17]
static Polynom ak1_cs = { ak1_data, 17, 17 }
static double ak12_data [14]
static Polynom ak12_cs = { ak12_data, 14, 14 }
static double bi1_data [11]
static Polynom bi1_cs = { bi1_data, 11, 11 }
static double ai1_data [21]
static Polynom ai1_cs = { ai1_data, 21, 21 }
static double ai12_data [22]
static Polynom ai12_cs = { ai12_data, 22, 22 }
static double hzeta_c [15]
static int ak01_orders []
necessary orders for K0/1 from 2 up to 22 for 10^-14 precision.
Detailed Description
Special functions, see specfunc.h.
Definition in file specfunc.cpp.
Function Documentation
double hzeta (double order, double x)
Hurwitz zeta function.
This function was taken from the GSL code.
Definition at line 420 of file specfunc.cpp.
References hzeta_c.
Referenced by preparePolygammaEven(), and preparePolygammaOdd().
double I0 (double x)
Modified Bessel function of first kind, order 0.
This function was taken from the GSL code. Precise roughly up to machine precision.
Definition at line 457 of file specfunc.cpp.
References evaluateAsChebychevSeriesAt().
Referenced by dev_K0(), and K0().
double I1 (double x)
Modified Bessel function of first kind, order 1.
This function was taken from the GSL code. Precise roughly up to machine precision.
Definition at line 483 of file specfunc.cpp.
References evaluateAsChebychevSeriesAt().
Referenced by dev_K1(), and K1().
double K0 (double x)
Modified Bessel function of second kind, order 0.
This function was taken from the GSL code. Precise roughly up to machine precision.
Definition at line 469 of file specfunc.cpp.
References evaluateAsChebychevSeriesAt(), I0(), and M_LN2.
double K1 (double x)
Modified Bessel function of second kind, order 1.
This function was taken from the GSL code. Precise roughly up to machine precision.
Definition at line 499 of file specfunc.cpp.
References evaluateAsChebychevSeriesAt(), I1(), and M_LN2.
double LPK0 (double x)
Besselfunctions K0 at x.
The implementation has an absolute precision of around 10^(-14), which is comparable to the relative precision sqrt implementation of current hardware.
Definition at line 531 of file specfunc.cpp.
References ak01_orders, ak02_data, ak0_data, bi0_data, bk0_data, and M_LN2.
void LPK01 (double x, double * K0, double * K1)
Besselfunctions K0 and K1 at x.
The implementation has an absolute precision of around 10^(-14), which is comparable to the relative precision sqrt implementation of current hardware.
Definition at line 655 of file specfunc.cpp.
References ak01_orders, ak02_data, ak0_data, ak12_data, ak1_data, bi0_data, bi1_data, bk0_data, bk1_data, and M_LN2.
Referenced by add_mmm1d_coulomb_pair_force(), and add_mmm2d_coulomb_pair_force().
double LPK1 (double x)
Besselfunctions K1 at x.
The implementation has an absolute precision of around 10^(-14), which is comparable to the relative precision sqrt implementation of current hardware.
Definition at line 593 of file specfunc.cpp.
References ak01_orders, ak12_data, ak1_data, bi1_data, bk1_data, and M_LN2.
Variable Documentation
Polynom ai02_cs = { ai02_data, 22, 22 } static
Definition at line 222 of file specfunc.cpp.
double ai02_data[22] static
Initial value:
= {
  .75 +.05449041101410882,
   .00336911647825569,
   .00006889758346918,
   .00000289137052082,
   .00000020489185893,
   .00000002266668991,
   .00000000339623203,
   .00000000049406022,
   .00000000001188914,
  -.00000000003149915,
  -.00000000001321580,
  -.00000000000179419,
   .00000000000071801,
   .00000000000038529,
   .00000000000001539,
  -.00000000000004151,
  -.00000000000000954,
   .00000000000000382,
   .00000000000000176,
  -.00000000000000034,
  -.00000000000000027,
   .00000000000000003
}
Definition at line 198 of file specfunc.cpp.
Polynom ai0_cs = { ai0_data, 21, 21 } static
Definition at line 196 of file specfunc.cpp.
double ai0_data[21] static
Initial value:
= {
  .75 +.07575994494023796,
   .00759138081082334,
   .00041531313389237,
   .00001070076463439,
  -.00000790117997921,
  -.00000078261435014,
   .00000027838499429,
   .00000000825247260,
  -.00000001204463945,
   .00000000155964859,
   .00000000022925563,
  -.00000000011916228,
   .00000000001757854,
   .00000000000112822,
  -.00000000000114684,
   .00000000000027155,
  -.00000000000002415,
  -.00000000000000608,
   .00000000000000314,
  -.00000000000000071,
   .00000000000000007
}
Definition at line 173 of file specfunc.cpp.
Polynom ai12_cs = { ai12_data, 22, 22 } static
Definition at line 389 of file specfunc.cpp.
double ai12_data[22] static
Initial value:
= {
  .75 +0.02857623501828014,
  -0.00976109749136147,
  -0.00011058893876263,
  -0.00000388256480887,
  -0.00000025122362377,
  -0.00000002631468847,
  -0.00000000383538039,
  -0.00000000055897433,
  -0.00000000001897495,
   0.00000000003252602,
   0.00000000001412580,
   0.00000000000203564,
  -0.00000000000071985,
  -0.00000000000040836,
  -0.00000000000002101,
   0.00000000000004273,
   0.00000000000001041,
  -0.00000000000000382,
  -0.00000000000000186,
   0.00000000000000033,
   0.00000000000000028,
  -0.00000000000000003
}
Definition at line 365 of file specfunc.cpp.
Polynom ai1_cs = { ai1_data, 21, 21 } static
Definition at line 363 of file specfunc.cpp.
double ai1_data[21] static
Initial value:
= {
  .75 -0.02846744181881479,
  -0.01922953231443221,
  -0.00061151858579437,
  -0.00002069971253350,
   0.00000858561914581,
   0.00000104949824671,
  -0.00000029183389184,
  -0.00000001559378146,
   0.00000001318012367,
  -0.00000000144842341,
  -0.00000000029085122,
   0.00000000012663889,
  -0.00000000001664947,
  -0.00000000000166665,
   0.00000000000124260,
  -0.00000000000027315,
   0.00000000000002023,
   0.00000000000000730,
  -0.00000000000000333,
   0.00000000000000071,
  -0.00000000000000006
}
Definition at line 340 of file specfunc.cpp.
int ak01_orders[] static
Initial value:
= {
     11, 11, 10,
  10, 9, 9,
           6, 6,
  5, 5, 5, 4, 4,
  4, 3, 3, 2, 2,
  2, 2, 2
}
necessary orders for K0/1 from 2 up to 22 for 10^-14 precision.
Note that at 8 the expansion changes. From 23 to 26 order 2 is used, above order 1. For the latter cases separate implementations are necessary.
Definition at line 520 of file specfunc.cpp.
Referenced by LPK0(), LPK01(), and LPK1().
Polynom ak02_cs = { ak02_data, 13, 13 } static
Definition at line 131 of file specfunc.cpp.
double ak02_data[14] static
Initial value:
= {
  2.5 -0.01201869826307592,
  -0.00917485269102569,
   0.00014445509317750,
  -0.00000401361417543,
   0.00000015678318108,
  -0.00000000777011043,
   0.00000000046111825,
  -0.00000000003158592,
   0.00000000000243501,
  -0.00000000000020743,
   0.00000000000001925,
  -0.00000000000000192,
   0.00000000000000020,
  -0.00000000000000002
}
Definition at line 115 of file specfunc.cpp.
Referenced by LPK0(), and LPK01().
Polynom ak0_cs = { ak0_data, 16, 16 } static
Definition at line 113 of file specfunc.cpp.
double ak0_data[17] static
Initial value:
= {
  2.5 -0.07643947903327941,
  -0.02235652605699819,
   0.00077341811546938,
  -0.00004281006688886,
   0.00000308170017386,
  -0.00000026393672220,
   0.00000002563713036,
  -0.00000000274270554,
   0.00000000031694296,
  -0.00000000003902353,
   0.00000000000506804,
  -0.00000000000068895,
   0.00000000000009744,
  -0.00000000000001427,
   0.00000000000000215,
  -0.00000000000000033,
   0.00000000000000005
}
Definition at line 94 of file specfunc.cpp.
Referenced by LPK0(), and LPK01().
Polynom ak12_cs = { ak12_data, 14, 14 } static
Definition at line 300 of file specfunc.cpp.
double ak12_data[14] static
Initial value:
= {
  2.5 +0.06379308343739001,
   0.02832887813049721,
  -0.00024753706739052,
   0.00000577197245160,
  -0.00000020689392195,
   0.00000000973998344,
  -0.00000000055853361,
   0.00000000003732996,
  -0.00000000000282505,
   0.00000000000023720,
  -0.00000000000002176,
   0.00000000000000215,
  -0.00000000000000022,
   0.00000000000000002
}
Definition at line 284 of file specfunc.cpp.
Referenced by LPK01(), and LPK1().
Polynom ak1_cs = { ak1_data, 17, 17 } static
Definition at line 282 of file specfunc.cpp.
double ak1_data[17] static
Initial value:
= {
  2.5 +0.27443134069738830,
   0.07571989953199368,
  -0.00144105155647540,
   0.00006650116955125,
  -0.00000436998470952,
   0.00000035402774997,
  -0.00000003311163779,
   0.00000000344597758,
  -0.00000000038989323,
   0.00000000004720819,
  -0.00000000000604783,
   0.00000000000081284,
  -0.00000000000011386,
   0.00000000000001654,
  -0.00000000000000248,
   0.00000000000000038,
  -0.00000000000000006
}
Definition at line 263 of file specfunc.cpp.
Referenced by LPK01(), and LPK1().
Polynom bi0_cs = { bi0_data, 12, 12 } static
Definition at line 171 of file specfunc.cpp.
double bi0_data[12] static
Initial value:
= {
  5.5 -.07660547252839144951,
  1.92733795399380827000,
   .22826445869203013390,
   .01304891466707290428,
   .00043442709008164874,
   .00000942265768600193,
   .00000014340062895106,
   .00000000161384906966,
   .00000000001396650044,
   .00000000000009579451,
   .00000000000000053339,
   .00000000000000000245
}
Definition at line 157 of file specfunc.cpp.
Referenced by LPK0(), and LPK01().
Polynom bi1_cs = { bi1_data, 11, 11 } static
Definition at line 338 of file specfunc.cpp.
double bi1_data[11] static
Initial value:
= {
  1.75 -0.001971713261099859,
   0.407348876675464810,
   0.034838994299959456,
   0.001545394556300123,
   0.000041888521098377,
   0.000000764902676483,
   0.000000010042493924,
   0.000000000099322077,
   0.000000000000766380,
   0.000000000000004741,
   0.000000000000000024
}
Definition at line 325 of file specfunc.cpp.
Referenced by LPK01(), and LPK1().
Polynom bk0_cs = { bk0_data, 11, 11 } static
Definition at line 92 of file specfunc.cpp.
double bk0_data[11] static
Initial value:
= {
  -.5 -0.03532739323390276872,
   0.3442898999246284869,
   0.03597993651536150163,
   0.00126461541144692592,
   0.00002286212103119451,
   0.00000025347910790261,
   0.00000000190451637722,
   0.00000000001034969525,
   0.00000000000004259816,
   0.00000000000000013744,
   0.00000000000000000035
}
Definition at line 79 of file specfunc.cpp.
Referenced by LPK0(), and LPK01().
Polynom bk1_cs = { bk1_data, 11, 11 } static
Definition at line 261 of file specfunc.cpp.
double bk1_data[11] static
Initial value:
= {
  1.5 +0.0253002273389477705,
  -0.3531559607765448760,
  -0.1226111808226571480,
  -0.0069757238596398643,
  -0.0001730288957513052,
  -0.0000024334061415659,
  -0.0000000221338763073,
  -0.0000000001411488392,
  -0.0000000000006666901,
  -0.0000000000000024274,
  -0.0000000000000000070
}
Definition at line 247 of file specfunc.cpp.
Referenced by LPK01(), and LPK1().
double hzeta_c[15] static
Initial value:
= {
  1.00000000000000000000000000000,
  0.083333333333333333333333333333,
 -0.00138888888888888888888888888889,
  0.000033068783068783068783068783069,
 -8.2671957671957671957671957672e-07,
  2.0876756987868098979210090321e-08,
 -5.2841901386874931848476822022e-10,
  1.3382536530684678832826980975e-11,
 -3.3896802963225828668301953912e-13,
  8.5860620562778445641359054504e-15,
 -2.1748686985580618730415164239e-16,
  5.5090028283602295152026526089e-18,
 -1.3954464685812523340707686264e-19,
  3.5347070396294674716932299778e-21,
 -8.9535174270375468504026113181e-23
}
Definition at line 398 of file specfunc.cpp.
Referenced by hzeta().