ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_fluid_tcl.hpp File Reference
statistics_fluid_tcl.hpp File Reference
#include "parser.hpp"
Functions
int tclcommand_analyze_parse_fluid_cpu (Tcl_Interp *interp, int argc, char **argv)
Parser for fluid related analysis functions.
int tclcommand_analyze_parse_fluid_gpu (Tcl_Interp *interp, int argc, char **argv)
Parser for fluid related analysis functions.
int tclcommand_analyze_parse_fluid (Tcl_Interp *interp, int argc, char **argv)
Parser for fluid related analysis functions.
Function Documentation
int tclcommand_analyze_parse_fluid (Tcl_Interp * interp, int argc, char ** argv)
Parser for fluid related analysis functions.
Definition at line 299 of file statistics_fluid_tcl.cpp.
References LATTICE_LB_GPU, lattice_switch, tclcommand_analyze_parse_fluid_cpu(), and tclcommand_analyze_parse_fluid_gpu().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_fluid_cpu (Tcl_Interp * interp, int argc, char ** argv)
Parser for fluid related analysis functions.
Definition at line 193 of file statistics_fluid_tcl.cpp.
References ARG0_IS_S, err, tclcommand_analyze_fluid_parse_densprof(), tclcommand_analyze_fluid_parse_mass(), tclcommand_analyze_fluid_parse_momentum(), tclcommand_analyze_fluid_parse_temp(), and tclcommand_analyze_fluid_parse_velprof().
Referenced by tclcommand_analyze_parse_fluid().
int tclcommand_analyze_parse_fluid_gpu (Tcl_Interp * interp, int argc, char ** argv)
Parser for fluid related analysis functions.
Definition at line 267 of file statistics_fluid_tcl.cpp.
References ARG0_IS_S, err, tclcommand_analyze_fluid_mass_gpu(), tclcommand_analyze_fluid_parse_momentum_gpu(), and tclcommand_analyze_fluid_parse_temperature_gpu().
Referenced by tclcommand_analyze_parse_fluid().