ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_cluster_tcl.hpp File Reference
statistics_cluster_tcl.hpp File Reference
#include "parser.hpp"
Functions
int tclcommand_analyze_parse_necklace (Tcl_Interp *interp, int argc, char **argv)
Parser for the necklace cluster algorithm.
int tclcommand_analyze_parse_holes (Tcl_Interp *interp, int argc, char **argv)
Parser for Hole cluster algorithm.
Function Documentation
int tclcommand_analyze_parse_holes (Tcl_Interp * interp, int argc, char ** argv)
Parser for Hole cluster algorithm.
analyze holes <prob_part_type_number> <mesh_size>
Identifies free space in the simulation box via a mesh based cluster algorithm. Free space is defined via a probe particle and its interactions with other particles which have to be defined through LJ interactions with the other existing particle types via the inter command before calling this routine.
Definition at line 124 of file statistics_cluster_tcl.cpp.
References alloc_intlist(), ARG_IS_I, cluster_free_volume_grid(), cluster_free_volume_surface(), create_free_volume_grid(), free, i, malloc, n_particle_types, realloc_intlist(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_necklace (Tcl_Interp * interp, int argc, char ** argv)
Parser for the necklace cluster algorithm.
analyze necklace <pearl_treshold> <back_dist> <space_dist> <first> <length>
For more information see: Limbach H.J. and Holm C. Single-Chain Properties of Polyelectrolytes in Poor Solvent J. Phys. Chem. B, 107 (32), 8041 -8055, AUG 14 2003. The first three parameters are tune parameters for the algorithm: pearl_treshold is the minimal number of monomers in a pearl. back_dist is the number of monomers along the chain backbone which are excluded from the space distance criterion to form clusters. space_dist is the distance between two monomers up to which they are considered to belong to the same clusters. The three parameters may be connected by scaling arguments. Make sure that your results are only weakly dependent on the exact choice of your parameters. For the algorithm the coordinates stored in partCfg are used. The chain itself is defined by the identity first of its first monomer and the chain length length.
Definition at line 41 of file statistics_cluster_tcl.cpp.
References analyze_necklace(), ARG_IS_D, ARG_IS_I, backbone_distance, cluster, cluster_free(), StructCluster::first, first_cluster, last_cluster, n_part, StructCluster::next, partCfg, pearl_treshold, StructCluster::prev, StructCluster::size, sortPartCfg(), space_distance2, and SQR().
Referenced by tclcommand_analyze().