ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics.hpp File Reference
statistics.hpp File Reference
This file contains the code for statistics on the data.
#include <vector>
#include "grid.hpp"
#include "particle_data.hpp"
#include "interaction_data.hpp"
#include "utils.hpp"
#include "topology.hpp"
#include <string>
#include <map>
Data Structures
struct Observable_stat
struct Observable_stat_non_bonded
Structure used only in the pressure and stress tensor calculation to distinguish non-bonded intra- and inter- molecular contributions.
Functions
Exported Functions
double mindist (IntList *set1, IntList *set2)
the minimal distance of two particles with types in set1 rsp.
int aggregation (double dist_criteria2, int min_contact, int s_mol_id, int f_mol_id, int *head_list, int *link_list, int *agg_id_list, int *agg_num, int *agg_size, int *agg_max, int *agg_min, int *agg_avg, int *agg_std, int charge_criteria)
calculate the aggregate distribution for molecules.
void nbhood (double pos[3], double r_catch, IntList *il, int planedims[3])
returns all particles within a given radius r_catch around a position.
double distto (double pos[3], int pid)
minimal distance to point.
void calc_cell_gpb (double xi_m, double Rc, double ro, double gacc, int maxtry, double *result)
numerical solution for the integration constant in the cell model, determined by
from which the second integration constant, the Manning radius , follows to
Any value is allowed, the function will automatically ensure the analytical continuation required for , in which case becomes imaginary.
void analyze_append ()
appends particles' positions in 'partCfg' to onfigs
void analyze_configs (double *config, int count)
appends the configuration stored in 'config[3*count]' to configs
void analyze_activate (int ind)
Docs missing!
void analyze_push ()
removes configs[0], pushes all entries forward, appends current 'partCfg' to last spot
void analyze_replace (int ind)
replaces configs[ind] with current 'partCfg'
void analyze_remove (int ind)
removes configs[ind] and shrinks the array accordingly
void calc_part_distribution (int *p1_types, int n_p1, int *p2_types, int n_p2, double r_min, double r_max, int r_bins, int log_flag, double *low, double *dist)
Calculates the distribution of particles around others.
void calc_rdf (int *p1_types, int n_p1, int *p2_types, int n_p2, double r_min, double r_max, int r_bins, double *rdf)
Calculates the radial distribution function.
void calc_rdf_av (int *p1_types, int n_p1, int *p2_types, int n_p2, double r_min, double r_max, int r_bins, double *rdf, int n_conf)
Calculates the radial distribution function averaged over last n_conf configurations.
void calc_rdf_intermol_av (int *p1_types, int n_p1, int *p2_types, int n_p2, double r_min, double r_max, int r_bins, double *rdf, int n_conf)
Calculates the intermolecular radial distribution function averaged over last n_conf configurations.
double calc_vanhove (int ptype, double rmin, double rmax, int rbins, int tmax, double *msd, double **vanhove)
Calculates the van Hove auto correlation function and as a side product the mean sqaure displacement (msd).
void calc_structurefactor (int type, int order, double **sf)
Calculates the spherically averaged structure factor.
std::vector< std::vector< double > > modify_stucturefactor (int order, double *sf)
void density_profile_av (int n_conf, int n_bin, double density, int dir, double *rho_ave, int type)
Calculates the density profile in dir direction.
int calc_cylindrical_average (std::vector< double > center, std::vector< double > direction, double length, double radius, int bins_axial, int bins_radial, std::vector< int > types, std::map< std::string, std::vector< std::vector< std::vector< double > > > > &distribution)
int calc_radial_density_map (int xbins, int ybins, int thetabins, double xrange, double yrange, double axis[3], double center[3], IntList *beadids, DoubleList *density_map, DoubleList *density_profile)
void calc_diffusion_profile (int dir, double xmin, double xmax, int nbins, int n_part, int n_conf, int time, int type, double *bins)
double min_distance2 (double pos1[3], double pos2[3])
returns the minimal squared distance between two positions in the perhaps periodic simulation box.
double min_distance (double pos1[3], double pos2[3])
returns the minimal distance between two positions in the perhaps periodic simulation box.
void centermass (int type, double *com)
calculate the center of mass of a special type of the current configuration
void centermass_vel (int type, double *com)
Docs missing.
void angularmomentum (int type, double *com)
calculate the angular momentum of a special type of the current configuration
void centermass_conf (int k, int type_1, double *com)
calculate the center of mass of a special type of a saved configuration
void momentofinertiamatrix (int type, double *MofImatrix)
void calc_gyration_tensor (int type, double **gt)
void calculate_verlet_neighbors ()
void predict_momentum_particles (double *result)
returns the momentum of the particles in the simulation box.
void momentum_calc (double *momentum)
Docs missing.
std::vector< double > calc_linear_momentum (int include_particles, int include_lbfluid)
Calculate total momentum of the system (particles & LB fluid) inputs are bools to include particles and fluid in the linear momentum calculation.
double * obsstat_bonded (Observable_stat *stat, int j)
double * obsstat_nonbonded (Observable_stat *stat, int p1, int p2)
double * obsstat_nonbonded_intra (Observable_stat_non_bonded *stat, int p1, int p2)
double * obsstat_nonbonded_inter (Observable_stat_non_bonded *stat, int p1, int p2)
void invalidate_obs ()
void mark_neighbours (int type, int pa_nr, double dist, int *list)
Docs missing.
void obsstat_realloc_and_clear (Observable_stat *stat, int n_pre, int n_bonded, int n_non_bonded, int n_coulomb, int n_dipolar, int n_vsr, int chunk_size)
void obsstat_realloc_and_clear_non_bonded (Observable_stat_non_bonded *stat_nb, int n_nonbonded, int chunk_size_nb)
Variables
Exported Variables
Previous particle configurations (needed for offline analysis and correlation analysis in tclcommand_analyze)
double ** configs
Previous particle configurations (needed for offline analysis and correlation analysis in tclcommand_analyze)
int n_configs
int n_part_conf
Detailed Description
This file contains the code for statistics on the data.
Definition in file statistics.hpp.
Function Documentation
int aggregation (double dist_criteria2, int min_contact, int s_mol_id, int f_mol_id, int * head_list, int * link_list, int * agg_id_list, int * agg_num, int * agg_size, int * agg_max, int * agg_min, int * agg_avg, int * agg_std, int charge_criteria)
calculate the aggregate distribution for molecules.
Parameters
dist_criteria2 distance criteria squared
min_contact minimum number of contacts
s_mol_id start molecule id
f_mol_id finish molecule id
head_list
link_list
agg_id_list
agg_num
agg_size
agg_max
agg_min
agg_avg
agg_std
charge_criteria
Definition at line 125 of file statistics.cpp.
References build_verlet_lists(), DomainDecomposition::cell_inter, dd, i, local_cells, malloc, merge_aggregate_lists(), min_distance2(), ParticleProperties::mol_id, PairList::n, CellPList::n, n_molecules, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, on_observable_calc(), ParticlePosition::p, Particle::p, PairList::pair, ParticleProperties::q, Particle::r, and IA_Neighbor::vList.
Referenced by tclcommand_analyze_parse_aggregation().
void analyze_activate (int ind)
Docs missing!
Todo:
Docs missing
Definition at line 1392 of file statistics.cpp.
References configs, ES_ERROR, i, n_part, n_part_conf, place_particle(), and runtimeError.
Referenced by tclcommand_analyze_parse_activate().
void analyze_append ()
appends particles' positions in 'partCfg' to onfigs
Definition at line 1330 of file statistics.cpp.
References configs, i, malloc, n_configs, n_part, n_part_conf, ParticlePosition::p, partCfg, Particle::r, and realloc.
Referenced by tclcommand_analyze_parse_activate(), tclcommand_analyze_parse_append(), tclcommand_analyze_parse_push(), and tclcommand_analyze_parse_replace().
void analyze_configs (double * config, int count)
appends the configuration stored in 'config[3*count]' to configs
Parameters
config the configuration which should be added
count how many particles in 'config'
Definition at line 1379 of file statistics.cpp.
References configs, i, malloc, n_configs, n_part_conf, and realloc.
Referenced by tclcommand_analyze_parse_configs().
void analyze_push ()
removes configs[0], pushes all entries forward, appends current 'partCfg' to last spot
Definition at line 1343 of file statistics.cpp.
References configs, free, i, malloc, n_configs, n_part, n_part_conf, ParticlePosition::p, partCfg, and Particle::r.
Referenced by tclcommand_analyze_parse_push().
void analyze_remove (int ind)
removes configs[ind] and shrinks the array accordingly
Parameters
ind the entry in configs to be removed
Definition at line 1368 of file statistics.cpp.
References configs, free, i, n_configs, n_part_conf, and realloc.
Referenced by tclcommand_analyze_parse_push(), and tclcommand_analyze_parse_remove().
void analyze_replace (int ind)
replaces configs[ind] with current 'partCfg'
Parameters
ind the entry in configs to be replaced
Definition at line 1358 of file statistics.cpp.
References configs, i, n_part, n_part_conf, ParticlePosition::p, partCfg, and Particle::r.
Referenced by tclcommand_analyze_parse_replace().
void angularmomentum (int type, double * com)
calculate the angular momentum of a special type of the current configuration
Parameters
type type of the particle
com angular momentum vector
Definition at line 333 of file statistics.cpp.
References i, Particle::m, n_part, Particle::p, partCfg, PMASS, updatePartCfg(), ParticleMomentum::v, vector_product(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze_parse_angularmomentum().
void calc_cell_gpb (double xi_m, double Rc, double ro, double gacc, int maxtry, double * result)
numerical solution for the integration constant in the cell model, determined by
from which the second integration constant, the Manning radius , follows to
Any value is allowed, the function will automatically ensure the analytical continuation required for , in which case becomes imaginary.
Parameters
xi_m Manning parameter (with Bjerrum-length and charge distance)
Rc outer radius of the cylindrical cell around each polyelectrolyte
ro inner radius of the cylindrical cell around each polyelectrolyte
gacc the accuracy up to which should be determined
maxtry maximum number of interations to find a solution
result pointer to double array containing and , and a third entry which is -1.0 if is imaginary, +1.0 else.
Definition at line 501 of file statistics.cpp.
References i, and PI.
Referenced by tclcommand_analyze_parse_cell_gpb().
int calc_cylindrical_average (std::vector< double > center, std::vector< double > direction, double length, double radius, int bins_axial, int bins_radial, std::vector< int > types, std::map< std::string, std::vector< std::vector< std::vector< double > > > > & distribution)
Definition at line 1032 of file statistics.cpp.
References utils::cross_product(), utils::dot_product(), ES_OK, fold_coordinate(), i, ParticleLocal::i, Particle::l, Particle::m, M_PI, n_part, ParticlePosition::p, Particle::p, partCfg, Particle::r, updatePartCfg(), ParticleMomentum::v, utils::veclen(), utils::vecsub(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze_parse_cylindrical_average().
void calc_diffusion_profile (int dir, double xmin, double xmax, int nbins, int n_part, int n_conf, int time, int type, double * bins)
Definition at line 969 of file statistics.cpp.
References box_l, configs, fold_coordinate(), free, i, malloc, n_configs, n_part, and partCfg.
Referenced by tclcommand_analyze_parse_diffusion_profile().
void calc_gyration_tensor (int type, double ** gt)
Definition at line 386 of file statistics.cpp.
References calc_eigenvalues_3x3(), calc_eigenvector_3x3(), centermass(), i, n_part, ParticlePosition::p, partCfg, Particle::r, realloc, updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze_parse_gyration_tensor().
std::vector<double> calc_linear_momentum (int include_particles, int include_lbfluid)
Calculate total momentum of the system (particles & LB fluid) inputs are bools to include particles and fluid in the linear momentum calculation.
Parameters
momentum Result for this processor (Output)
Definition at line 266 of file statistics.cpp.
References mpi_gather_stats().
void calc_part_distribution (int * p1_types, int n_p1, int * p2_types, int n_p2, double r_min, double r_max, int r_bins, int log_flag, double * low, double * dist)
Calculates the distribution of particles around others.
Calculates the distance distribution of particles with types given in the p1_types list around particles with types given in the p2_types list. The distances range from r_min to r_max, binned into r_bins bins which are either aequidistant (log_flag==0)or logarithmically aequidistant (log_flag==1). The result is stored in the array dist.
Parameters
p1_types list with types of particles to find the distribution for.
n_p1 length of p1_types.
p2_types list with types of particles the others are distributed around.
n_p2 length of p2_types.
r_min Minimal distance for the distribution.
r_max Maximal distance for the distribution.
r_bins Number of bins.
log_flag Wether the bins are (logarithmically) aequidistant.
low particles closer than r_min
dist Array to store the result (size: r_bins).
Definition at line 600 of file statistics.cpp.
References box_l, i, min_distance2(), n_part, ParticlePosition::p, Particle::p, partCfg, Particle::r, and SQR().
Referenced by tclcommand_analyze_parse_distribution().
int calc_radial_density_map (int xbins, int ybins, int thetabins, double xrange, double yrange, double axis[3], double center[3], IntList * beadids, DoubleList * density_map, DoubleList * density_profile)
Definition at line 1140 of file statistics.cpp.
References IntList::e, DoubleList::e, errexit(), ES_OK, fold_coordinate(), free, i, ParticleLocal::i, Particle::l, Particle::m, malloc, IntList::n, n_part, Particle::p, partCfg, PI, scalar(), sqrlen(), ParticleProperties::type, updatePartCfg(), ParticleMomentum::v, vecsub(), vector_product(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze_parse_radial_density_map().
void calc_rdf (int * p1_types, int n_p1, int * p2_types, int n_p2, double r_min, double r_max, int r_bins, double * rdf)
Calculates the radial distribution function.
Calculates the radial distribution function of particles with types given in the p1_types list around particles with types given in the p2_types list. The range is given by r_min and r_max and the distribution function is binned into r_bin bins, which are equidistant. The result is stored in the array rdf.
Parameters
p1_types list with types of particles to find the distribution for.
n_p1 length of p1_types.
p2_types list with types of particles the others are distributed around.
n_p2 length of p2_types.
r_min Minimal distance for the distribution.
r_max Maximal distance for the distribution.
r_bins Number of bins.
rdf Array to store the result (size: r_bins).
Definition at line 656 of file statistics.cpp.
References box_l, i, min_distance(), n_part, ParticlePosition::p, Particle::p, partCfg, PI, Particle::r, and start.
Referenced by observable_calc_rdf(), and tclcommand_analyze_parse_rdf().
void calc_rdf_av (int * p1_types, int n_p1, int * p2_types, int n_p2, double r_min, double r_max, int r_bins, double * rdf, int n_conf)
Calculates the radial distribution function averaged over last n_conf configurations.
Calculates the radial distribution function of particles with types given in the p1_types list around particles with types given in the p2_types list. The range is given by r_min and r_max and the distribution function is binned into r_bin bins, which are equidistant. The result is stored in the array rdf.
Parameters
p1_types list with types of particles to find the distribution for.
n_p1 length of p1_types.
p2_types list with types of particles the others are distributed around.
n_p2 length of p2_types.
r_min Minimal distance for the distribution.
r_max Maximal distance for the distribution.
r_bins Number of bins.
rdf Array to store the result (size: r_bins).
n_conf Number of configurations from the last stored configuration.
Definition at line 708 of file statistics.cpp.
References box_l, configs, free, i, malloc, min_distance(), n_configs, n_part, partCfg, PI, and start.
Referenced by tclcommand_analyze_parse_rdf().
void calc_rdf_intermol_av (int * p1_types, int n_p1, int * p2_types, int n_p2, double r_min, double r_max, int r_bins, double * rdf, int n_conf)
Calculates the intermolecular radial distribution function averaged over last n_conf configurations.
Calculates the radial distribution function of particles with types given in the p1_types list around particles with types given in the p2_types list. The range is given by r_min and r_max and the distribution function is binned into r_bin bins, which are equidistant. The result is stored in the array rdf.
Parameters
p1_types list with types of particles to find the distribution for.
n_p1 length of p1_types.
p2_types list with types of particles the others are distributed around.
n_p2 length of p2_types.
r_min Minimal distance for the distribution.
r_max Maximal distance for the distribution.
r_bins Number of bins.
rdf Array to store the result (size: r_bins).
n_conf Number of configurations from the last stored configuration.
Definition at line 776 of file statistics.cpp.
References box_l, configs, free, i, malloc, min_distance(), ParticleProperties::mol_id, n_configs, n_part, Particle::p, partCfg, PI, and start.
Referenced by tclcommand_analyze_parse_rdf().
void calc_structurefactor (int type, int order, double ** sf)
Calculates the spherically averaged structure factor.
Calculates the spherically averaged structure factor of particles of a given type. The possible wave vectors are given by q = 2PI/L sqrt(nx^2 + ny^2 + nz^2). The S(q) is calculated up to a given length measured in 2PI/L (the recommended order of the wave vector is less than 20). The data is stored starting with q=1, and contains alternatingly S(q-1) and the number of wave vectors l with l^2=q. Only if the second number is nonzero, the first is meaningful. This means the q=1 entries are sf[0]=S(1) and sf[1]=1. For q=7, there are no possible wave vectors, so sf[2*(7-1)]=sf[2*(7-1)+1]=0.
Parameters
type the type of the particles to be analyzed
order the maximum wave vector length in 2PI/L
sf pointer to hold the base of the array containing the result (size: 2*order^2).
Definition at line 846 of file statistics.cpp.
References box_l, errexit(), i, n_part, n_particle_types, ParticlePosition::p, partCfg, PI, Particle::r, and realloc.
Referenced by tclcommand_analyze_parse_structurefactor().
double calc_vanhove (int ptype, double rmin, double rmax, int rbins, int tmax, double * msd, double ** vanhove)
Calculates the van Hove auto correlation function and as a side product the mean sqaure displacement (msd).
Calculates the van Hove auto correlation function (acf) G(r,t) which is the probability that a particle has moved a distance r after time t. In the case of a random walk G(r,t)/(4 pi r*r) is a gaussian. The mean square displacement (msd) is connected to the van Hove acf via sqrt(msd(t)) = int G(r,t) dr. This is very useful for the investigation of diffusion processes. calc_vanhove does the calculation for one particle type ptype and stores the functions specified by rmin, rmax and rbins in the arrays msd and vanhove.
Parameters
ptype particle type for which the analysis should be performed
rmin minimal distance for G(r,t)
rmax maximal distance for G(r,t)
rbins number of bins for the r distribution in G(r,t)
tmax max time, for which G(r,t) is computed, if omitted or set to zero, default tmax=n_configs-1 is used
msd array to store the mean square displacement (size n_configs-1)
vanhove array to store G(r,t) (size (n_configs-1)*(rbins))
Definition at line 1281 of file statistics.cpp.
References alloc_intlist(), configs, distance(), IntList::e, i, init_intlist(), IntList::n, n_configs, n_part, partCfg, and realloc_intlist().
Referenced by tclcommand_analyze_parse_vanhove().
void calculate_verlet_neighbors ()
void centermass (int type, double * com)
calculate the center of mass of a special type of the current configuration
Parameters
type type of the particle
com center of mass position
Definition at line 288 of file statistics.cpp.
References i, n_part, ParticlePosition::p, partCfg, PMASS, Particle::r, updatePartCfg(), and WITHOUT_BONDS.
Referenced by calc_comforce(), calc_gyration_tensor(), momentofinertiamatrix(), and tclcommand_analyze_parse_centermass().
void centermass_conf (int k, int type_1, double * com)
calculate the center of mass of a special type of a saved configuration
Parameters
k number of the saved configuration
type_1 type of the particle, -1 for all
com center of mass position
Definition at line 1479 of file statistics.cpp.
References configs, i, n_part, partCfg, and PMASS.
Referenced by tclcommand_analyze_print_MSD().
void centermass_vel (int type, double * com)
Docs missing.
Todo:
Docs missing
Definition at line 310 of file statistics.cpp.
References i, Particle::m, n_part, partCfg, updatePartCfg(), ParticleMomentum::v, and WITHOUT_BONDS.
Referenced by tclcommand_analyze_print_vel_distr().
void density_profile_av (int n_conf, int n_bin, double density, int dir, double * rho_ave, int type)
Calculates the density profile in dir direction.
Definition at line 921 of file statistics.cpp.
References box_l, configs, fold_coordinate(), i, n_configs, n_part, and partCfg.
Referenced by tclcommand_analyze_parse_density_profile_av().
double distto (double pos[3], int pid)
minimal distance to point.
Parameters
pos point
pid if a valid particle id, this particle is omitted from minimization (this is a good idea if the posx, posy, posz is the position of a particle).
Returns
the minimal distance of a particle to coordinates (<posx>, <posy>, <posz>).
Definition at line 482 of file statistics.cpp.
References box_l, dmin(), get_mi_vector(), i, mindist(), n_part, Particle::p, partCfg, SQR(), sqrlen(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze_parse_distto().
void invalidate_obs ()
Definition at line 1458 of file statistics.cpp.
References Observable_stat::init_status, total_energy, and total_pressure.
Referenced by ghmc_mc(), on_constraint_change(), on_coulomb_change(), on_integration_start(), on_lbboundary_change(), on_particle_change(), on_short_range_ia_change(), and tclcommand_load_state().
void mark_neighbours (int type, int pa_nr, double dist, int * list)
Docs missing.
Todo:
Docs missing
Definition at line 1466 of file statistics.cpp.
References mark_neighbours(), min_distance(), n_part, ParticlePosition::p, Particle::p, partCfg, and Particle::r.
Referenced by mark_neighbours(), and tclcommand_analyze_parse_cluster_size_dist().
double min_distance (double pos1[3], double pos2[3]) inline
returns the minimal distance between two positions in the perhaps periodic simulation box.
Parameters
pos1 Position one.
pos2 Position two.
Definition at line 347 of file statistics.hpp.
References min_distance2().
Referenced by analyze_rdfchain(), calc_rdf(), calc_rdf_av(), calc_rdf_intermol_av(), and mark_neighbours().
double min_distance2 (double pos1[3], double pos2[3])
returns the minimal squared distance between two positions in the perhaps periodic simulation box.
Parameters
pos1 Position one.
pos2 Position two.
Definition at line 60 of file statistics.cpp.
References get_mi_vector(), and sqrlen().
Referenced by aggregation(), calc_part_distribution(), min_distance(), and mindist().
double mindist (IntList * set1, IntList * set2)
the minimal distance of two particles with types in set1 rsp.
set2.
Parameters
set1 types of particles
set2 types of particles
Returns
the minimal distance of two particles
Definition at line 72 of file statistics.cpp.
References box_l, dmin(), i, intlist_contains(), min_distance2(), mindist(), n_part, ParticlePosition::p, Particle::p, partCfg, Particle::r, SQR(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by buf_mindist4(), calculate_hollow_cone_dist(), calculate_stomatocyte_dist(), distto(), mindist(), mindist4(), tclcommand_analyze_parse_mindist(), tclcommand_constraint_mindist_position(), and tclcommand_constraint_mindist_position_vec().
std::vector< std::vector<double> > modify_stucturefactor (int order, double * sf)
Definition at line 888 of file statistics.cpp.
References box_l, i, and PI.
void momentofinertiamatrix (int type, double * MofImatrix)
Definition at line 355 of file statistics.cpp.
References centermass(), i, n_part, ParticlePosition::p, partCfg, PMASS, Particle::r, updatePartCfg(), and WITHOUT_BONDS.
Referenced by calc_comforce(), tclcommand_analyze_parse_find_principal_axis(), and tclcommand_analyze_parse_momentofinertiamatrix().
void momentum_calc (double * momentum)
Docs missing.
Todo:
Docs missing
Docs missing.
Parameters
momentum Result for this processor (Output)
Definition at line 246 of file statistics.cpp.
References mpi_gather_stats().
Referenced by tclcommand_analyze_parse_and_print_momentum().
void nbhood (double pos[3], double r_catch, IntList * il, int planedims[3])
returns all particles within a given radius r_catch around a position.
Parameters
pos position of sphere of point
r_catch the radius around the position
il the list where to store the particles indices
planedims orientation of coordinate system
Definition at line 452 of file statistics.cpp.
References IntList::e, get_mi_vector(), i, ParticleProperties::identity, init_intlist(), IntList::n, n_part, ParticlePosition::p, Particle::p, partCfg, Particle::r, realloc_intlist(), sqrlen(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze_parse_nbhood().
double* obsstat_bonded (Observable_stat * stat, int j) inline
Definition at line 392 of file statistics.hpp.
References Observable_stat::bonded, and Observable_stat::chunk_size.
Referenced by add_bonded_energy(), add_bonded_virials(), add_three_body_bonded_stress(), tclcommand_analyze_parse_and_print_energy(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_all(), tclcommand_analyze_print_pressure_all(), and tclcommand_analyze_print_stress_tensor_all().
double* obsstat_nonbonded (Observable_stat * stat, int p1, int p2) inline
Definition at line 397 of file statistics.hpp.
References Observable_stat::chunk_size, n_particle_types, and Observable_stat::non_bonded.
Referenced by add_constraints_energy(), add_non_bonded_pair_energy(), add_non_bonded_pair_virials(), tclcommand_analyze_parse_and_print_energy(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_all(), tclcommand_analyze_print_pressure_all(), and tclcommand_analyze_print_stress_tensor_all().
double* obsstat_nonbonded_inter (Observable_stat_non_bonded * stat, int p1, int p2) inline
Definition at line 420 of file statistics.hpp.
References Observable_stat_non_bonded::chunk_size_nb, n_particle_types, and Observable_stat_non_bonded::non_bonded_inter.
Referenced by add_non_bonded_pair_virials(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_pressure_all(), and tclcommand_analyze_print_stress_tensor_all().
double* obsstat_nonbonded_intra (Observable_stat_non_bonded * stat, int p1, int p2) inline
Definition at line 408 of file statistics.hpp.
References Observable_stat_non_bonded::chunk_size_nb, n_particle_types, and Observable_stat_non_bonded::non_bonded_intra.
Referenced by add_non_bonded_pair_virials(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_print_pressure_all(), and tclcommand_analyze_print_stress_tensor_all().
void obsstat_realloc_and_clear (Observable_stat * stat, int n_pre, int n_bonded, int n_non_bonded, int n_coulomb, int n_dipolar, int n_vsr, int chunk_size)
Definition at line 1414 of file statistics.cpp.
References Observable_stat::bonded, Observable_stat::chunk_size, Observable_stat::coulomb, Observable_stat::data, Observable_stat::dipolar, DoubleList::e, i, DoubleList::n, n_bonded_ia, Observable_stat::n_coulomb, Observable_stat::n_dipolar, Observable_stat::n_non_bonded, Observable_stat::n_vs_relative, Observable_stat::non_bonded, realloc_doublelist(), and Observable_stat::vs_relative.
Referenced by init_energies(), init_p_tensor(), and init_virials().
void obsstat_realloc_and_clear_non_bonded (Observable_stat_non_bonded * stat_nb, int n_nonbonded, int chunk_size_nb)
Definition at line 1444 of file statistics.cpp.
References Observable_stat_non_bonded::chunk_size_nb, Observable_stat_non_bonded::data_nb, DoubleList::e, i, DoubleList::n, Observable_stat_non_bonded::n_nonbonded, Observable_stat_non_bonded::non_bonded_inter, Observable_stat_non_bonded::non_bonded_intra, and realloc_doublelist().
Referenced by init_p_tensor_non_bonded(), and init_virials_non_bonded().
void predict_momentum_particles (double * result)
returns the momentum of the particles in the simulation box.
Parameters
result Momentum of particles.
returns the momentum of the particles in the simulation box.
Parameters
result Result for this processor (Output)
Definition at line 216 of file statistics.cpp.
References CellPList::cell, comm_cart, ParticleForce::f, Particle::f, i, local_cells, Particle::m, momentum(), MPI_DOUBLE, MPI_Reduce(), MPI_SUM, CellPList::n, ParticleList::n, ParticleList::part, time_step, and ParticleMomentum::v.
Referenced by mpi_gather_stats(), and mpi_gather_stats_slave().
Variable Documentation
double** configs
Previous particle configurations (needed for offline analysis and correlation analysis in tclcommand_analyze)
Definition at line 54 of file statistics.cpp.
Referenced by analyze_activate(), analyze_append(), analyze_configs(), analyze_cwvac(), analyze_formfactor_av(), analyze_push(), analyze_remove(), analyze_replace(), calc_bond_dist_av(), calc_bond_l_av(), calc_diffusion_profile(), calc_g1_av(), calc_g2_av(), calc_g3_av(), calc_internal_dist_av(), calc_rdf_av(), calc_rdf_intermol_av(), calc_re_av(), calc_rg_av(), calc_rh_av(), calc_vanhove(), calc_wallmsdx(), calc_wallmsdyz(), centermass_conf(), density_profile_av(), tclcommand_analyze_parse_configs(), and tclcommand_analyze_print_MSD().
int n_configs
Definition at line 54 of file statistics.cpp.
Referenced by analyze_append(), analyze_configs(), analyze_cwvac(), analyze_formfactor_av(), analyze_push(), analyze_remove(), calc_bond_dist_av(), calc_bond_l_av(), calc_diffusion_profile(), calc_g1_av(), calc_g2_av(), calc_g3_av(), calc_internal_dist_av(), calc_rdf_av(), calc_rdf_intermol_av(), calc_re_av(), calc_rg_av(), calc_rh_av(), calc_vanhove(), calc_wallmsdx(), calc_wallmsdyz(), density_profile_av(), tclcommand_analyze_parse_activate(), tclcommand_analyze_parse_append(), tclcommand_analyze_parse_bond_dist(), tclcommand_analyze_parse_bond_l(), tclcommand_analyze_parse_configs(), tclcommand_analyze_parse_density_profile_av(), tclcommand_analyze_parse_formfactor(), tclcommand_analyze_parse_g_av(), tclcommand_analyze_parse_internal_dist(), tclcommand_analyze_parse_MSD(), tclcommand_analyze_parse_push(), tclcommand_analyze_parse_rdf(), tclcommand_analyze_parse_re(), tclcommand_analyze_parse_remove(), tclcommand_analyze_parse_replace(), tclcommand_analyze_parse_rg(), tclcommand_analyze_parse_rh(), tclcommand_analyze_parse_stored(), tclcommand_analyze_parse_vanhove(), tclcommand_analyze_print_MSD(), and tclcommand_analyze_wallstuff().
int n_part_conf
Definition at line 54 of file statistics.cpp.
Referenced by analyze_activate(), analyze_append(), analyze_configs(), analyze_push(), analyze_remove(), analyze_replace(), tclcommand_analyze_parse_activate(), tclcommand_analyze_parse_append(), tclcommand_analyze_parse_configs(), tclcommand_analyze_parse_push(), and tclcommand_analyze_parse_replace().