ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_correlation.hpp File Reference
statistics_correlation.hpp File Reference
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include "statistics_observable.hpp"
Data Structures
struct double_correlation
The struct that is used to calculate correlations *.
struct file_data_source
This struct allow to use a file as input for the correlation.
Macros
#define MAXLINELENGTH 2048
#define MIN(a, b) ((a)>(b)?(b):(a))
Functions
void autoupdate_correlations ()
int double_correlation_init (double_correlation *self, double dt, unsigned int tau_lin, double tau_max, unsigned int window_distance, unsigned int dim_A, unsigned int dim_B, unsigned int dim_corr, observable *A, observable *B, char *corr_operation_name, char *compressA_name, char *compressB_name, void *args)
The initialization procedure for the correlation object.
int double_correlation_read_data_from_file (double_correlation *self, const char *filename, bool binary)
Restore a correlation from a checkpoint - the observable has to be created first ordinary.
void write_double (FILE *fp, const double *data, unsigned int n, bool binary)
void write_uint (FILE *fp, const unsigned int *data, unsigned int n, bool binary)
int read_double (FILE *fp, double *data, unsigned int n, bool binary)
int read_uint (FILE *fp, unsigned int *data, unsigned int n, bool binary)
int double_correlation_write_data_to_file (const double_correlation *self, const char *filename, bool binary)
Write a checkpoint, saving all history buffers and other important variables of a correlation in a file.
int double_correlation_get_data (double_correlation *self)
The function to process a new datapoint of A and B.
int double_correlation_finalize (double_correlation *self)
At the end of data collection, go through the whole hierarchy and correlate data left there.
int correlation_get_correlation_time (double_correlation *self, double *correlation_time)
Return an estimate of the integrated correlation time.
int file_data_source_init (file_data_source *self, char *filename, IntList *columns)
int file_data_source_readline (void *xargs, double *A, unsigned int dim_A)
int identity (double *input, unsigned int n_input, double *A, unsigned int dim_A)
int compress_do_nothing (double *A1, double *A2, double *A_compressed, unsigned int dim_A)
The minimal version of compression function.
int compress_linear (double *A1, double *A2, double *A_compressed, unsigned int dim_A)
Compress computing arithmetic mean: A_compressed=(A1+A2)/2.
int compress_discard1 (double *A1, double *A2, double *A_compressed, unsigned int dim_A)
Compress discarding the 1st argument and return the 2nd.
int compress_discard2 (double *A1, double *A2, double *A_compressed, unsigned int dim_A)
Compress discarding the 2nd argument and return the 1st.
int scalar_product (double *A, unsigned int dim_A, double *B, unsigned int dim_B, double *C, unsigned int dim_corr, void *args)
int componentwise_product (double *A, unsigned int dim_A, double *B, unsigned int dim_B, double *C, unsigned int dim_corr, void *args)
int complex_conjugate_product (double *A, unsigned int dim_A, double *B, unsigned int dim_B, double *C, unsigned int dim_corr, void *args)
int tensor_product (double *A, unsigned int dim_A, double *B, unsigned int dim_B, double *C, unsigned int dim_corr, void *args)
int fcs_acf (double *A, unsigned int dim_A, double *B, unsigned int dim_B, double *C, unsigned int dim_corr, void *args)
int square_distance_componentwise (double *A, unsigned int dim_A, double *B, unsigned int dim_B, double *C, unsigned int dim_corr, void *args)
int square_distance (double *A, unsigned int dim_A, double *B, unsigned int dim_B, double *C, unsigned int dim_corr, void *args)
int square_distance_cond (double *A, unsigned int dim_A, double *B, unsigned int dim_B, double *C, unsigned int dim_corr, void *args)
int square_distance_cond_chain (double *A, unsigned int dim_A, double *B, unsigned int dim_B, double *C, unsigned int dim_corr, void *args)
Variables
unsigned int n_correlations
int correlations_autoupdate
double_correlation * correlations
const char init_errors [][64]
const char init_from_checkpoint_errors [][64]
const char file_data_source_init_errors [][64]
const char double_correlation_get_data_errors [][64]
Macro Definition Documentation
#define MAXLINELENGTH 2048
Definition at line 121 of file statistics_correlation.hpp.
#define MIN (a, b) ((a)>(b)?(b):(a))
Definition at line 123 of file statistics_correlation.hpp.
Referenced by double_correlation_finalize(), and double_correlation_get_data().
Function Documentation
void autoupdate_correlations ()
Definition at line 861 of file statistics_correlation.cpp.
References double_correlation_get_data(), i, double_correlation::last_update, n_correlations, and sim_time.
Referenced by mpi_integrate(), python_integrate(), tclcommand_integrate(), and tclcommand_integrate_sd().
int complex_conjugate_product (double * A, unsigned int dim_A, double * B, unsigned int dim_B, double * C, unsigned int dim_corr, void * args)
Definition at line 801 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_init().
int componentwise_product (double * A, unsigned int dim_A, double * B, unsigned int dim_B, double * C, unsigned int dim_corr, void * args)
Definition at line 785 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_init().
int compress_discard1 (double * A1, double * A2, double * A_compressed, unsigned int dim_A)
Compress discarding the 1st argument and return the 2nd.
Definition at line 753 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_init().
int compress_discard2 (double * A1, double * A2, double * A_compressed, unsigned int dim_A)
Compress discarding the 2nd argument and return the 1st.
Definition at line 760 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_init().
int compress_do_nothing (double * A1, double * A2, double * A_compressed, unsigned int dim_A)
The minimal version of compression function.
Definition at line 742 of file statistics_correlation.cpp.
Referenced by double_correlation_init().
int compress_linear (double * A1, double * A2, double * A_compressed, unsigned int dim_A)
Compress computing arithmetic mean: A_compressed=(A1+A2)/2.
Definition at line 746 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_init().
int correlation_get_correlation_time (double_correlation * self, double * correlation_time)
Return an estimate of the integrated correlation time.
We calculate the correlation time for each dim_corr by normalizing the correlation, integrating it and finding out where C(tau)=tau;
Definition at line 95 of file statistics_correlation.cpp.
Referenced by tclcommand_print_average_errorbars(), and tclcommand_print_correlation_time().
int double_correlation_finalize (double_correlation * self)
At the end of data collection, go through the whole hierarchy and correlate data left there.
This works pretty much the same as get_data, but does not feed on new data, just uses what is already available.
Definition at line 627 of file statistics_correlation.cpp.
References free, i, malloc, and MIN.
Referenced by tclcommand_correlation_parse_corr().
int double_correlation_get_data (double_correlation * self)
The function to process a new datapoint of A and B.
First the function finds out if it necessary to make some space for the new entries of A and B. Then, if necessary, it compresses old Values of A and B to make for the new value. Finally The new values of A and B are stored in A[newest[0]] and B[newest[0]], where the newest indices have been increased before. Finally the correlation estimate is updated. TODO: Not all the correlation estimates have to be updated.
Definition at line 397 of file statistics_correlation.cpp.
References free, i, malloc, MIN, and observable_calculate().
Referenced by autoupdate_correlations(), correlation_update(), correlation_update_from_file(), and tclcommand_correlation_parse_corr().
int double_correlation_init (double_correlation * self, double dt, unsigned int tau_lin, double tau_max, unsigned int window_distance, unsigned int dim_A, unsigned int dim_B, unsigned int dim_corr, observable * A, observable * B, char * corr_operation_name, char * compressA_name, char * compressB_name, void * args)
The initialization procedure for the correlation object.
All important parameters have to be speciefied at the same time. They can not be change later, so every instance of the correlation class has to be fed with correct data from the very beginning.
Parameters
self The pointer to the correlation class instance that should be initialized
dt The time interval between subsequent updates
tau_lin The linear part of the correlation function.
tau_max maximal time delay tau to sample
window_distance The distance in time domain between update of the correlation estimate
dim_A The dimension of the A vector
dim_B The dimension of the B vector
A First observable to correlate
B Second observable to correlate
dim_corr The dimension of the correlation to be calculated
corr_operation_name how to correlate the two observables A and B (this has no default)
compressA_name how the A values should be compressed (usually the linear compression method)
compressB_name how the B values should be compressed (usually the linear compression method)
args the parameters of the observables
Definition at line 138 of file statistics_correlation.cpp.
References complex_conjugate_product(), componentwise_product(), compress_discard1(), compress_discard2(), compress_do_nothing(), compress_linear(), fcs_acf(), i, malloc, scalar_product(), square_distance_componentwise(), tensor_product(), and time_step.
Referenced by tclcommand_correlation_parse_corr().
int double_correlation_read_data_from_file (double_correlation * self, const char * filename, bool binary)
Restore a correlation from a checkpoint - the observable has to be created first ordinary.
Definition at line 588 of file statistics_correlation.cpp.
References i, read_double(), and read_uint().
Referenced by tclcommand_correlation_parse_corr().
int double_correlation_write_data_to_file (const double_correlation * self, const char * filename, bool binary)
Write a checkpoint, saving all history buffers and other important variables of a correlation in a file.
Definition at line 523 of file statistics_correlation.cpp.
References i, write_double(), and write_uint().
Referenced by tclcommand_correlation_parse_corr().
int fcs_acf (double * A, unsigned int dim_A, double * B, unsigned int dim_B, double * C, unsigned int dim_corr, void * args)
Definition at line 840 of file statistics_correlation.cpp.
References DoubleList::e, and i.
Referenced by double_correlation_init().
int file_data_source_init (file_data_source * self, char * filename, IntList * columns)
int file_data_source_readline (void * xargs, double * A, unsigned int dim_A)
int identity (double * input, unsigned int n_input, double * A, unsigned int dim_A)
Definition at line 732 of file statistics_correlation.cpp.
References i.
int read_double (FILE * fp, double * data, unsigned int n, bool binary)
Definition at line 561 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_read_data_from_file(), and observable_read().
int read_uint (FILE * fp, unsigned int * data, unsigned int n, bool binary)
Definition at line 574 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_read_data_from_file(), and observable_read().
int scalar_product (double * A, unsigned int dim_A, double * B, unsigned int dim_B, double * C, unsigned int dim_corr, void * args)
Definition at line 771 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_init().
int square_distance (double * A, unsigned int dim_A, double * B, unsigned int dim_B, double * C, unsigned int dim_corr, void * args)
int square_distance_componentwise (double * A, unsigned int dim_A, double * B, unsigned int dim_B, double * C, unsigned int dim_corr, void * args)
Definition at line 828 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_init().
int square_distance_cond (double * A, unsigned int dim_A, double * B, unsigned int dim_B, double * C, unsigned int dim_corr, void * args)
int square_distance_cond_chain (double * A, unsigned int dim_A, double * B, unsigned int dim_B, double * C, unsigned int dim_corr, void * args)
int tensor_product (double * A, unsigned int dim_A, double * B, unsigned int dim_B, double * C, unsigned int dim_corr, void * args)
Definition at line 816 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_init().
void write_double (FILE * fp, const double * data, unsigned int n, bool binary)
Definition at line 503 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_write_data_to_file(), and observable_write().
void write_uint (FILE * fp, const unsigned int * data, unsigned int n, bool binary)
Definition at line 513 of file statistics_correlation.cpp.
References i.
Referenced by double_correlation_write_data_to_file(), and observable_write().
Variable Documentation
double_correlation* correlations
Definition at line 25 of file statistics_correlation.cpp.
Referenced by correlation_print_parameters_all(), tclcommand_correlation(), tclcommand_correlation_parse_autoupdate(), tclcommand_correlation_parse_corr(), and tclcommand_correlation_parse_print().
int correlations_autoupdate
Definition at line 75 of file statistics_correlation.cpp.
Referenced by mpi_integrate(), python_integrate(), tclcommand_correlation_parse_autoupdate(), tclcommand_integrate(), and tclcommand_integrate_sd().
const char double_correlation_get_data_errors[][64]
Definition at line 65 of file statistics_correlation.cpp.
Referenced by tclcommand_correlation_parse_corr().
const char file_data_source_init_errors[][64]
Definition at line 58 of file statistics_correlation.cpp.
const char init_errors[][64]
Definition at line 35 of file statistics_correlation.cpp.
Referenced by tclcommand_correlation_parse_corr().
const char init_from_checkpoint_errors[][64]
unsigned int n_correlations
Definition at line 26 of file statistics_correlation.cpp.
Referenced by autoupdate_correlations(), correlation_print_parameters_all(), correlation_update(), tclcommand_correlation(), tclcommand_correlation_parse_autoupdate(), and tclcommand_correlation_parse_corr().