ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_fluid.cpp File Reference
statistics_fluid.cpp File Reference
Fluid related analysis functions.
#include <mpi.h>
#include "utils.hpp"
#include "communication.hpp"
#include "lb.hpp"
#include "lb-boundaries.hpp"
#include "statistics_fluid.hpp"
Macros
#define REQ_DENSPROF 702
#define REQ_VELPROF 701
Functions
void lb_calc_fluid_mass (double *result)
Caclulate mass of the LB fluid.
void lb_calc_fluid_momentum (double *result)
Calculate momentum of the LB fluid.
void lb_calc_fluid_temp (double *result)
Calculate temperature of the LB fluid.
void lb_collect_boundary_forces (double *result)
void lb_calc_densprof (double *result, int *params)
Calculate a density profile of the fluid.
void lb_calc_velprof (double *result, int *params)
Calculate a velocity profile for the LB fluid.
Detailed Description
Fluid related analysis functions.
Implementation of statistics_fluid.hpp.
Definition in file statistics_fluid.cpp.
Macro Definition Documentation
#define REQ_DENSPROF 702
Definition at line 137 of file statistics_fluid.cpp.
Referenced by lb_calc_densprof().
#define REQ_VELPROF 701
Definition at line 218 of file statistics_fluid.cpp.
Referenced by lb_calc_velprof().
Function Documentation
void lb_calc_densprof (double * result, int * params)
Calculate a density profile of the fluid.
Definition at line 140 of file statistics_fluid.cpp.
References Lattice::agrid, box_l, comm_cart, free, get_linear_index(), Lattice::grid, Lattice::halo_grid, lb_calc_local_rho(), lblattice, malloc, Lattice::map_lattice_to_node(), map_node_array(), MPI_Bcast(), MPI_Comm_free(), MPI_Comm_rank(), MPI_Comm_split(), MPI_DOUBLE, MPI_Gather(), MPI_INT, MPI_Recv(), MPI_Send(), node_grid, node_pos, realloc, REQ_DENSPROF, and this_node.
void lb_calc_fluid_mass (double * result)
Caclulate mass of the LB fluid.
Parameters
result Fluid mass
Definition at line 40 of file statistics_fluid.cpp.
References comm_cart, get_linear_index(), Lattice::grid, Lattice::halo_grid, lb_calc_local_rho(), lblattice, MPI_DOUBLE, MPI_Reduce(), and MPI_SUM.
Referenced by mpi_gather_stats(), and mpi_gather_stats_slave().
void lb_calc_fluid_momentum (double * result)
Calculate momentum of the LB fluid.
Parameters
result Fluid momentum
Definition at line 63 of file statistics_fluid.cpp.
References LB_Parameters::agrid, comm_cart, LB_FluidNode::force, get_linear_index(), Lattice::grid, Lattice::halo_grid, lb_calc_local_j(), lbfields, lblattice, lbpar, momentum(), MPI_DOUBLE, MPI_Reduce(), MPI_SUM, and LB_Parameters::tau.
Referenced by mpi_gather_stats(), and mpi_gather_stats_slave().
void lb_calc_fluid_temp (double * result)
Calculate temperature of the LB fluid.
Parameters
result Fluid temperature
Definition at line 93 of file statistics_fluid.cpp.
References LB_Parameters::agrid, boundary, comm_cart, get_linear_index(), Lattice::grid, Lattice::halo_grid, lb_calc_local_fields(), lbfields, lblattice, lbpar, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, n_nodes, LB_Parameters::rho, scalar(), and LB_Parameters::tau.
Referenced by mpi_gather_stats(), and mpi_gather_stats_slave().
void lb_calc_velprof (double * result, int * params)
Calculate a velocity profile for the LB fluid.
Definition at line 221 of file statistics_fluid.cpp.
References Lattice::agrid, LB_Parameters::agrid, box_l, comm_cart, free, get_linear_index(), Lattice::grid, Lattice::halo_grid, lb_calc_local_fields(), lblattice, lbpar, malloc, Lattice::map_lattice_to_node(), map_node_array(), MPI_Bcast(), MPI_Comm_free(), MPI_Comm_rank(), MPI_Comm_split(), MPI_DOUBLE, MPI_Gather(), MPI_INT, MPI_Recv(), MPI_Send(), node_grid, node_pos, realloc, REQ_VELPROF, ROUND_ERROR_PREC, LB_Parameters::tau, and this_node.
void lb_collect_boundary_forces (double * result)
Definition at line 124 of file statistics_fluid.cpp.
References comm_cart, free, i, lb_boundaries, malloc, MPI_DOUBLE, MPI_Reduce(), MPI_SUM, and n_lb_boundaries.
Referenced by mpi_gather_stats(), and mpi_gather_stats_slave().