ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_cluster.cpp File Reference
statistics_cluster.cpp File Reference
This file contains the necklace cluster algorithm.
#include "statistics_cluster.hpp"
#include "grid.hpp"
Functions
Routines
void cluster_init (Particle *part, int size)
void cluster_free ()
void clusters_join (Cluster *cluster1, Cluster *cluster2)
int clusters_connected (Particle *part, Cluster cluster1, Cluster cluster2)
int clusters_interpenetrate (Cluster cluster1, Cluster cluster2)
int cluster_joincicle (Particle *part)
int cluster_join_to_substructures ()
int analyze_necklace (Particle *part, int np)
Perform necklace cluster algorithm.
int test_mesh_elements (double pos[3], int probe_part_type)
test if a mesh point belongs to free (return -1) or occupied (return -2) volume.
void create_free_volume_grid (IntList mesh, int dim[3], int probe_part_type)
Test which mesh points belong to the free and occupied volume.
void cluster_neighbors (int point, int dim[3], int neighbors[6])
int cluster_free_volume_grid (IntList mesh, int dim[3], int ***holes)
hole cluster algorithm.
void cluster_free_volume_surface (IntList mesh, int dim[3], int nholes, int **holes, int *surface)
Calculates the surface to volume ratios of the holes.
Variables
ClusterElement * element
NULL terminated linked list of elements of a cluster (indices in particle list)
Cluster * cluster
Double linked list of statistics_cluster::Cluster.
Cluster * first_cluster
first cluster in list of statistics_cluster::Cluster
Cluster * last_cluster
last cluster in list of statistics_cluster::Cluster
int backbone_distance
parameter of necklace cluster algorithm
double space_distance2
parameter of necklace cluster algorithm
int pearl_treshold
parameter of necklace cluster algorithm
Detailed Description
This file contains the necklace cluster algorithm.
It can be used to identify the substructures 'pearls' and 'strings' on a linear chain. See also statistics_cluster.hpp
Definition in file statistics_cluster.cpp.
Function Documentation
int analyze_necklace (Particle * part, int np)
Perform necklace cluster algorithm.
Parameters
part pointer to first particle
np Number of particles
Returns
Number of pearls in necklace structure
Definition at line 234 of file statistics_cluster.cpp.
References cluster_init(), cluster_join_to_substructures(), and cluster_joincicle().
Referenced by tclcommand_analyze_parse_necklace().
void cluster_free ()
Definition at line 73 of file statistics_cluster.cpp.
References free.
Referenced by tclcommand_analyze_parse_necklace().
int cluster_free_volume_grid (IntList mesh, int dim[3], int *** holes)
hole cluster algorithm.
returns the number of holes and a list of mesh points belonging to each of them
Definition at line 321 of file statistics_cluster.cpp.
References cluster_neighbors(), IntList::e, free, i, and malloc.
Referenced by tclcommand_analyze_parse_holes().
void cluster_free_volume_surface (IntList mesh, int dim[3], int nholes, int ** holes, int * surface)
Calculates the surface to volume ratios of the holes.
Definition at line 388 of file statistics_cluster.cpp.
References cluster_neighbors(), IntList::e, and i.
Referenced by tclcommand_analyze_parse_holes().
void cluster_init (Particle * part, int size)
Definition at line 54 of file statistics_cluster.cpp.
References StructCluster::first, i, StructClusterElement::id, StructCluster::id, malloc, StructClusterElement::next, StructCluster::next, StructCluster::prev, and StructCluster::size.
Referenced by analyze_necklace().
int cluster_join_to_substructures ()
Definition at line 176 of file statistics_cluster.cpp.
References clusters_join(), first_cluster, StructCluster::next, pearl_treshold, StructCluster::prev, and StructCluster::size.
Referenced by analyze_necklace().
int cluster_joincicle (Particle * part)
Definition at line 146 of file statistics_cluster.cpp.
References clusters_connected(), clusters_interpenetrate(), clusters_join(), first_cluster, StructCluster::next, and StructCluster::prev.
Referenced by analyze_necklace().
void cluster_neighbors (int point, int dim[3], int neighbors[6])
Definition at line 297 of file statistics_cluster.cpp.
References get_grid_pos(), and get_linear_index().
Referenced by cluster_free_volume_grid(), and cluster_free_volume_surface().
int clusters_connected (Particle * part, Cluster cluster1, Cluster cluster2)
Definition at line 96 of file statistics_cluster.cpp.
References backbone_distance, distance2(), StructCluster::first, StructClusterElement::id, StructClusterElement::next, ParticlePosition::p, Particle::p, Particle::r, and space_distance2.
Referenced by cluster_joincicle().
int clusters_interpenetrate (Cluster cluster1, Cluster cluster2)
Definition at line 117 of file statistics_cluster.cpp.
References StructCluster::first, StructClusterElement::id, and StructClusterElement::next.
Referenced by cluster_joincicle().
void clusters_join (Cluster * cluster1, Cluster * cluster2)
Definition at line 79 of file statistics_cluster.cpp.
References StructCluster::first, StructClusterElement::next, StructCluster::next, StructCluster::prev, and StructCluster::size.
Referenced by cluster_join_to_substructures(), and cluster_joincicle().
void create_free_volume_grid (IntList mesh, int dim[3], int probe_part_type)
Test which mesh points belong to the free and occupied volume.
Free volume is marked by -1 and occupied volume by -2. Needs feature LENNARD_JONES compiled in.
Definition at line 273 of file statistics_cluster.cpp.
References box_l, IntList::e, i, iy, and test_mesh_elements().
Referenced by tclcommand_analyze_parse_holes().
int test_mesh_elements (double pos[3], int probe_part_type)
test if a mesh point belongs to free (return -1) or occupied (return -2) volume.
Needs feature LENNARD_JONES compiled in.
Definition at line 251 of file statistics_cluster.cpp.
References get_ia_param(), get_mi_vector(), i, ia_params, IA_parameters::LJ_cut, IA_parameters::LJ_offset, n_part, Particle::p, partCfg, and sqrlen().
Referenced by create_free_volume_grid().
Variable Documentation
int backbone_distance
parameter of necklace cluster algorithm
Definition at line 43 of file statistics_cluster.cpp.
Referenced by clusters_connected(), and tclcommand_analyze_parse_necklace().
Cluster* cluster
Double linked list of statistics_cluster::Cluster.
Definition at line 36 of file statistics_cluster.cpp.
Referenced by tclcommand_analyze_parse_necklace().
ClusterElement* element
NULL terminated linked list of elements of a cluster (indices in particle list)
Definition at line 34 of file statistics_cluster.cpp.
Cluster* first_cluster
first cluster in list of statistics_cluster::Cluster
Definition at line 38 of file statistics_cluster.cpp.
Referenced by cluster_join_to_substructures(), cluster_joincicle(), and tclcommand_analyze_parse_necklace().
Cluster* last_cluster
last cluster in list of statistics_cluster::Cluster
Definition at line 40 of file statistics_cluster.cpp.
Referenced by tclcommand_analyze_parse_necklace().
int pearl_treshold
parameter of necklace cluster algorithm
Definition at line 47 of file statistics_cluster.cpp.
Referenced by cluster_join_to_substructures(), and tclcommand_analyze_parse_necklace().
double space_distance2
parameter of necklace cluster algorithm
Definition at line 45 of file statistics_cluster.cpp.
Referenced by clusters_connected(), and tclcommand_analyze_parse_necklace().