ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_chain_tcl.hpp File Reference
statistics_chain_tcl.hpp File Reference
#include "parser.hpp"
Functions
int tclcommand_analyze_parse_set_chains (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze_set_parse_chain_topology (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze_parse_re (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_rg (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_rh (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_internal_dist (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_bond_l (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_bond_dist (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_g123 (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_g_av (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_formfactor (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_rdfchain (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze_parse_cwvac (Tcl_Interp *interp, int argc, char **argv)
Function Documentation
int tclcommand_analyze_parse_bond_dist (Tcl_Interp * interp, int average, int argc, char ** argv)
Definition at line 223 of file statistics_chain_tcl.cpp.
References ARG_IS_I, ARG_IS_S, calc_bond_dist(), calc_bond_dist_av(), chain_length, free, i, n_configs, and tclcommand_analyze_set_parse_chain_topology_check().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_bond_l (Tcl_Interp * interp, int average, int argc, char ** argv)
Definition at line 203 of file statistics_chain_tcl.cpp.
References calc_bond_l(), calc_bond_l_av(), free, n_configs, and tclcommand_analyze_set_parse_chain_topology_check().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_cwvac (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 439 of file statistics_chain_tcl.cpp.
References analyze_cwvac(), ARG0_IS_I, ARG1_IS_I, chain_length, chain_n_chains, free, i, tclcommand_analyze_set_parse_chain_topology_check(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_formfactor (Tcl_Interp * interp, int average, int argc, char ** argv)
Definition at line 332 of file statistics_chain_tcl.cpp.
References analyze_formfactor(), analyze_formfactor_av(), ARG0_IS_D, ARG1_IS_D, ARG_IS_I, chain_length, chain_n_chains, free, i, n_configs, and tclcommand_analyze_set_parse_chain_topology_check().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_g123 (Tcl_Interp * interp, int average, int argc, char ** argv)
Definition at line 262 of file statistics_chain_tcl.cpp.
References ARG0_IS_S, calc_g123(), chain_n_chains, init_g123(), n_chains_g, n_part, n_part_g, partCM_g, partCoord_g, and tclcommand_analyze_set_parse_chain_topology_check().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_g_av (Tcl_Interp * interp, int average, int argc, char ** argv)
Definition at line 291 of file statistics_chain_tcl.cpp.
References ARG0_IS_S, ARG_IS_D, calc_g1_av(), calc_g2_av(), calc_g3_av(), free, i, n_configs, tclcommand_analyze_set_parse_chain_topology_check(), and weights.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_internal_dist (Tcl_Interp * interp, int average, int argc, char ** argv)
Definition at line 174 of file statistics_chain_tcl.cpp.
References calc_internal_dist(), calc_internal_dist_av(), chain_length, free, i, n_configs, and tclcommand_analyze_set_parse_chain_topology_check().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_rdfchain (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 385 of file statistics_chain_tcl.cpp.
References analyze_rdfchain(), ARG0_IS_D, ARG1_IS_D, ARG_IS_I, chain_length, chain_n_chains, free, i, tclcommand_analyze_set_parse_chain_topology_check(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_re (Tcl_Interp * interp, int average, int argc, char ** argv)
Definition at line 83 of file statistics_chain_tcl.cpp.
References calc_re(), calc_re_av(), free, n_configs, and tclcommand_analyze_set_parse_chain_topology_check().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_rg (Tcl_Interp * interp, int average, int argc, char ** argv)
Definition at line 115 of file statistics_chain_tcl.cpp.
References calc_rg(), calc_rg_av(), free, n_configs, and tclcommand_analyze_set_parse_chain_topology_check().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_rh (Tcl_Interp * interp, int average, int argc, char ** argv)
Definition at line 144 of file statistics_chain_tcl.cpp.
References calc_rh(), calc_rh_av(), free, n_configs, and tclcommand_analyze_set_parse_chain_topology_check().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_set_chains (Tcl_Interp * interp, int argc, char ** argv)
int tclcommand_analyze_set_parse_chain_topology (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 34 of file statistics_chain_tcl.cpp.
References ARG0_IS_I, ARG1_IS_I, ARG_IS_I, chain_length, chain_n_chains, chain_start, i, n_molecules, realloc_intlist(), realloc_topology(), tclcommand_analyze_set_parse_topo_part_sync(), topology, and Molecule::type.
Referenced by tclcommand_analyze_parse_set(), and tclcommand_analyze_set_parse_chain_topology_check().