ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_observable_tcl.cpp File Reference
statistics_observable_tcl.cpp File Reference
#include <cstring>
#include "tcl/statistics_observable_tcl.hpp"
#include "statistics_observable.hpp"
#include "particle_data.hpp"
#include "parser.hpp"
#include "lb.hpp"
#include "pressure.hpp"
Macros
#define REGISTER_OBSERVABLE(name, parser, id)
Functions
int tclcommand_observable_print_formatted (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs, double *values)
int tclcommand_observable_print (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_update (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
static int convert_types_to_ids (IntList *type_list, IntList *id_list)
int parse_id_list (Tcl_Interp *interp, int argc, char **argv, int *change, IntList **ids)
int tclcommand_parse_profile (Tcl_Interp *interp, int argc, char **argv, int *change, int *dim_A, profile_data **pdata_)
int tclcommand_parse_radial_profile (Tcl_Interp *interp, int argc, char **argv, int *change, int *dim_A, radial_profile_data **pdata)
int sf_print_usage (Tcl_Interp *interp)
int tclcommand_observable_print_profile_formatted (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs, double *values, int groupsize, int shifted)
int tclcommand_observable_print_radial_profile_formatted (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs, double *values, int groupsize, int shifted)
int tclcommand_observable_tclcommand (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_particle_velocities (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_particle_body_velocities (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_particle_angular_momentum (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_particle_body_angular_momentum (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_com_velocity (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_com_position (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_com_force (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_particle_positions (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_particle_forces (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_stress_tensor (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_stress_tensor_acf_obs (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_density_profile (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_force_density_profile (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_rdf (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_lb_velocity_profile (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_radial_density_profile (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_radial_flux_density_profile (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_flux_density_profile (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_lb_radial_velocity_profile (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_particle_currents (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_currents (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_dipole_moment (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_structure_factor (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_print_structure_factor_formatted (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs, double *values, int groupsize, int shifted)
int tclcommand_observable_structure_factor_fast (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_print_structure_factor_fast_formatted (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs, double *values, int groupsize, int shifted)
int tclcommand_observable_interacts_with (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable_average (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tcl_parse_radial_density_distribution (Tcl_Interp *interp, int argc, char **argv, int *change, int *dim_A, radial_density_data *r_data)
int tcl_command_radial_density_distribution (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tcl_parse_spatial_polymer_properties (Tcl_Interp *interp, int argc, char **argv, int *change, int *dim_A, spatial_polym_data *p_data)
int tcl_command_spatial_polymer_properties (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tcl_parse_persistence_length (Tcl_Interp *interp, int argc, char **argv, int *change, int *dim_A, spatial_polym_data *p_data)
int tcl_command_persistence_length (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tcl_parse_k_dist (Tcl_Interp *interp, int argc, char **argv, int *change, int *dim_obs, k_dist_data *k_data)
int tcl_command_k_dist (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs)
int tclcommand_observable (ClientData data, Tcl_Interp *interp, int argc, char **argv)
int observable_calc_tclcommand (observable *self)
Macro Definition Documentation
#define REGISTER_OBSERVABLE (name, parser, id)
Value:
if (ARG_IS_S(2,#name)) { \
    observables[id]=(s_observable*)malloc(sizeof(observable)); \
    observable_init(observables[id]); \
    observables[id]->obs_name = (char*)malloc((1+strlen(#name))*sizeof(char)); \
    strcpy(observables[id]->obs_name,#name); \
    if (parser(interp, argc-2, argv+2, &temp, observables[n_observables]) ==TCL_OK) { \
      n_observables++; \
      argc-=1+temp; \
      argv+=1+temp; \
      sprintf(buffer,"%d",id); \
      Tcl_AppendResult(interp,buffer,(char *)NULL);\
      return TCL_OK; \
    } else { \
      free(observables[n_observables]->obs_name);\
      free(observables[n_observables]);\
      Tcl_AppendResult(interp, "\nError parsing observable ", #name, "\n", (char *)NULL); \
      return TCL_ERROR; \
    } \
  }
Definition at line 1278 of file statistics_observable_tcl.cpp.
Referenced by tclcommand_observable().
Function Documentation
static int convert_types_to_ids (IntList * type_list, IntList * id_list) static
Definition at line 1419 of file statistics_observable_tcl.cpp.
References IntList::e, i, IntList::n, n_part, partCfg, realloc_intlist(), and sortPartCfg().
Referenced by parse_id_list().
int observable_calc_tclcommand (observable * self)
Definition at line 1801 of file statistics_observable_tcl.cpp.
References Observable_Tclcommand_Arg_Container::command, and Observable_Tclcommand_Arg_Container::interp.
Referenced by tclcommand_observable_tclcommand().
int parse_id_list (Tcl_Interp * interp, int argc, char ** argv, int * change, IntList ** ids)
Definition at line 35 of file statistics_observable_tcl.cpp.
References alloc_intlist(), ARG0_IS_S, convert_types_to_ids(), IntList::e, i, init_intlist(), malloc, IntList::n, n_part, parse_int_list(), and sortPartCfg().
Referenced by tcl_parse_k_dist(), tcl_parse_persistence_length(), tcl_parse_radial_density_distribution(), tcl_parse_spatial_polymer_properties(), tclcommand_observable_com_force(), tclcommand_observable_com_position(), tclcommand_observable_com_velocity(), tclcommand_observable_currents(), tclcommand_observable_dipole_moment(), tclcommand_observable_interacts_with(), tclcommand_observable_particle_angular_momentum(), tclcommand_observable_particle_body_angular_momentum(), tclcommand_observable_particle_body_velocities(), tclcommand_observable_particle_currents(), tclcommand_observable_particle_forces(), tclcommand_observable_particle_positions(), tclcommand_observable_particle_velocities(), tclcommand_parse_profile(), and tclcommand_parse_radial_profile().
int sf_print_usage (Tcl_Interp * interp)
Definition at line 1796 of file statistics_observable_tcl.cpp.
Referenced by tclcommand_observable_structure_factor(), and tclcommand_observable_structure_factor_fast().
int tcl_command_k_dist (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 1257 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, i, k_dist_data::k, s_observable::last_value, malloc, s_observable::n, k_dist_data::n_bins, k_dist_data::npoly, observable_polymer_k_distribution(), k_dist_data::poly_len, k_dist_data::r_max, k_dist_data::r_min, and tcl_parse_k_dist().
Referenced by tclcommand_observable().
int tcl_command_persistence_length (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 1178 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, spatial_polym_data::cut_off, s_observable::last_value, malloc, s_observable::n, spatial_polym_data::npoly, observable_persistence_length(), and tcl_parse_persistence_length().
Referenced by tclcommand_observable().
int tcl_command_radial_density_distribution (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 1081 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, observable_radial_density_distribution(), and tcl_parse_radial_density_distribution().
Referenced by tclcommand_observable().
int tcl_command_spatial_polymer_properties (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 1127 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, spatial_polym_data::npoly, observable_spatial_polymer_properties(), and tcl_parse_spatial_polymer_properties().
Referenced by tclcommand_observable().
int tcl_parse_k_dist (Tcl_Interp * interp, int argc, char ** argv, int * change, int * dim_obs, k_dist_data * k_data)
Definition at line 1197 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, k_dist_data::id_list, k_dist_data::k, k_dist_data::n_bins, k_dist_data::npoly, parse_id_list(), k_dist_data::poly_len, k_dist_data::r_max, and k_dist_data::r_min.
Referenced by tcl_command_k_dist().
int tcl_parse_persistence_length (Tcl_Interp * interp, int argc, char ** argv, int * change, int * dim_A, spatial_polym_data * p_data)
Definition at line 1143 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, spatial_polym_data::cut_off, spatial_polym_data::id_list, IntList::n, spatial_polym_data::npoly, and parse_id_list().
Referenced by tcl_command_persistence_length().
int tcl_parse_radial_density_distribution (Tcl_Interp * interp, int argc, char ** argv, int * change, int * dim_A, radial_density_data * r_data)
Definition at line 989 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, radial_density_data::end_point, radial_density_data::end_point_id, radial_density_data::id_flag, radial_density_data::id_list, radial_density_data::maxr, radial_density_data::minr, parse_id_list(), radial_density_data::rbins, radial_density_data::start_point, radial_density_data::start_point_id, and radial_density_data::type.
Referenced by tcl_command_radial_density_distribution().
int tcl_parse_spatial_polymer_properties (Tcl_Interp * interp, int argc, char ** argv, int * change, int * dim_A, spatial_polym_data * p_data)
Definition at line 1096 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, spatial_polym_data::id_list, IntList::n, spatial_polym_data::npoly, and parse_id_list().
Referenced by tcl_command_spatial_polymer_properties().
int tclcommand_observable (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1301 of file statistics_observable_tcl.cpp.
References ARG1_IS_I, ARG1_IS_S, ARG_IS_D, ARG_IS_S, s_observable::autoupdate, n_observables, observable_read(), observable_reset_average(), observable_update_average(), observable_write(), observables, observables_autoupdate, realloc, REGISTER_OBSERVABLE, tcl_command_k_dist(), tcl_command_persistence_length(), tcl_command_radial_density_distribution(), tcl_command_spatial_polymer_properties(), tclcommand_observable_average(), tclcommand_observable_com_force(), tclcommand_observable_com_position(), tclcommand_observable_com_velocity(), tclcommand_observable_currents(), tclcommand_observable_density_profile(), tclcommand_observable_dipole_moment(), tclcommand_observable_flux_density_profile(), tclcommand_observable_force_density_profile(), tclcommand_observable_interacts_with(), tclcommand_observable_lb_radial_velocity_profile(), tclcommand_observable_lb_velocity_profile(), tclcommand_observable_particle_angular_momentum(), tclcommand_observable_particle_body_angular_momentum(), tclcommand_observable_particle_body_velocities(), tclcommand_observable_particle_currents(), tclcommand_observable_particle_forces(), tclcommand_observable_particle_positions(), tclcommand_observable_particle_velocities(), tclcommand_observable_print(), tclcommand_observable_radial_density_profile(), tclcommand_observable_radial_flux_density_profile(), tclcommand_observable_rdf(), tclcommand_observable_stress_tensor(), tclcommand_observable_stress_tensor_acf_obs(), tclcommand_observable_structure_factor(), tclcommand_observable_structure_factor_fast(), tclcommand_observable_tclcommand(), and tclcommand_observable_update().
Referenced by tcl_register_commands().
int tclcommand_observable_average (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 919 of file statistics_observable_tcl.cpp.
References ARG_IS_I, AVERAGE, s_observable::calculate, s_observable::container, i, s_observable::last_value, malloc, s_observable::n, n_observables, observable_average_container::n_sweeps, observable_update_average(), observables, observable_average_container::reference_observable, s_observable::type, and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_com_force (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 389 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, s_observable::calculate, s_observable::container, i, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_blocked_com_force(), observable_calc_com_force(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_com_position (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 353 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, s_observable::calculate, s_observable::container, i, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_blocked_com_position(), observable_calc_com_position(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_com_velocity (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 318 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, s_observable::calculate, s_observable::container, i, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_blocked_com_velocity(), observable_calc_com_velocity(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_currents (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 696 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, observable_calc_currents(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_density_profile (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 476 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, profile_data::id_list, s_observable::last_value, malloc, s_observable::n, observable_calc_density_profile(), tclcommand_parse_profile(), s_observable::update, profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable().
int tclcommand_observable_dipole_moment (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 715 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, observable_calc_dipole_moment(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_flux_density_profile (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 640 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, profile_data::id_list, s_observable::last_value, malloc, s_observable::n, observable_calc_flux_density_profile(), tclcommand_parse_profile(), s_observable::update, profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable().
int tclcommand_observable_force_density_profile (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 494 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, profile_data::id_list, s_observable::last_value, malloc, s_observable::n, observable_calc_force_density_profile(), tclcommand_parse_profile(), s_observable::update, profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable().
int tclcommand_observable_interacts_with (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 878 of file statistics_observable_tcl.cpp.
References ARG_IS_D, s_observable::calculate, s_observable::container, iw_params::cutoff, free, iw_params::ids1, iw_params::ids2, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_interacts_with(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_lb_radial_velocity_profile (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 658 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, observable_calc_lb_radial_velocity_profile(), radial_profile_data::phibins, radial_profile_data::rbins, tclcommand_parse_radial_profile(), s_observable::update, and radial_profile_data::zbins.
Referenced by tclcommand_observable().
int tclcommand_observable_lb_velocity_profile (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 582 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, observable_calc_lb_velocity_profile(), tclcommand_parse_profile(), s_observable::update, profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable().
int tclcommand_observable_particle_angular_momentum (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 290 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_particle_angular_momentum(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_particle_body_angular_momentum (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 304 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_particle_body_angular_momentum(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_particle_body_velocities (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 276 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_particle_body_velocities(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_particle_currents (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 676 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_particle_currents(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_particle_forces (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 438 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_particle_forces(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_particle_positions (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 424 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_particle_positions(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_particle_velocities (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 262 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_particle_velocities(), parse_id_list(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_print (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 1727 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, i, s_observable::last_value, s_observable::n, s_observable::obs_name, observable_calculate(), and tclcommand_observable_print_formatted().
Referenced by tclcommand_observable().
int tclcommand_observable_print_formatted (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs, double * values)
Definition at line 1753 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, observable_calc_density_profile(), observable_calc_flux_density_profile(), observable_calc_force_density_profile(), observable_calc_lb_radial_velocity_profile(), observable_calc_lb_velocity_profile(), observable_calc_radial_density_profile(), observable_calc_radial_flux_density_profile(), observable_calc_structure_factor(), observable_calc_structure_factor_fast(), observable_update_average(), tclcommand_observable_print_profile_formatted(), tclcommand_observable_print_radial_profile_formatted(), tclcommand_observable_print_structure_factor_fast_formatted(), tclcommand_observable_print_structure_factor_formatted(), and s_observable::update.
Referenced by correlation_print_average1(), and tclcommand_observable_print().
int tclcommand_observable_print_profile_formatted (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs, double * values, int groupsize, int shifted)
Definition at line 107 of file statistics_observable_tcl.cpp.
References s_observable::container, i, profile_data::maxx, profile_data::maxy, profile_data::maxz, profile_data::minx, profile_data::miny, profile_data::minz, profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable_print_formatted().
int tclcommand_observable_print_radial_profile_formatted (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs, double * values, int groupsize, int shifted)
Definition at line 172 of file statistics_observable_tcl.cpp.
References s_observable::container, i, radial_profile_data::maxphi, radial_profile_data::maxr, radial_profile_data::maxz, radial_profile_data::minphi, radial_profile_data::minr, radial_profile_data::minz, radial_profile_data::phibins, radial_profile_data::rbins, and radial_profile_data::zbins.
Referenced by tclcommand_observable_print_formatted().
int tclcommand_observable_print_structure_factor_fast_formatted (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs, double * values, int groupsize, int shifted)
Definition at line 845 of file statistics_observable_tcl.cpp.
References box_l, s_observable::container, i, observable_sf_params::k_density, observable_sf_params::order, params, and PI.
Referenced by tclcommand_observable_print_formatted().
int tclcommand_observable_print_structure_factor_formatted (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs, double * values, int groupsize, int shifted)
Definition at line 768 of file statistics_observable_tcl.cpp.
References box_l, s_observable::container, i, s_observable::last_value, observable_sf_params::order, params, and PI.
Referenced by tclcommand_observable_print_formatted().
int tclcommand_observable_radial_density_profile (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 601 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, radial_profile_data::id_list, s_observable::last_value, malloc, s_observable::n, observable_calc_radial_density_profile(), radial_profile_data::phibins, radial_profile_data::rbins, tclcommand_parse_radial_profile(), s_observable::update, and radial_profile_data::zbins.
Referenced by tclcommand_observable().
int tclcommand_observable_radial_flux_density_profile (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 619 of file statistics_observable_tcl.cpp.
References s_observable::calculate, CONST_UNITITIALIZED, s_observable::container, radial_profile_data::container, radial_profile_data::id_list, s_observable::last_value, malloc, s_observable::n, IntList::n, observable_calc_radial_flux_density_profile(), radial_profile_data::phibins, radial_profile_data::rbins, tclcommand_parse_radial_profile(), s_observable::update, and radial_profile_data::zbins.
Referenced by tclcommand_observable().
int tclcommand_observable_rdf (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 513 of file statistics_observable_tcl.cpp.
References ARG0_IS_D, ARG0_IS_I, ARG0_IS_INTLIST, ARG1_IS_INTLIST, s_observable::calculate, s_observable::container, IntList::e, init_intlist(), s_observable::last_value, malloc, min_box_l, s_observable::n, IntList::n, rdf_profile_data::n_p1, rdf_profile_data::n_p2, observable_calc_rdf(), rdf_profile_data::p1_types, rdf_profile_data::p2_types, rdf_profile_data::r_bins, rdf_profile_data::r_max, rdf_profile_data::r_min, sortPartCfg(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_stress_tensor (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 454 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, observable_stress_tensor(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_stress_tensor_acf_obs (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 465 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, s_observable::last_value, malloc, s_observable::n, observable_calc_stress_tensor_acf_obs(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_structure_factor (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 734 of file statistics_observable_tcl.cpp.
References ARG1_IS_I, s_observable::calculate, s_observable::container, i, s_observable::last_value, malloc, s_observable::n, observable_calc_structure_factor(), observable_sf_params::order, params, and sf_print_usage().
Referenced by tclcommand_observable().
int tclcommand_observable_structure_factor_fast (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 792 of file statistics_observable_tcl.cpp.
References ARG0_IS_I, ARG1_IS_I, s_observable::calculate, s_observable::container, observable_sf_params::k_density, s_observable::last_value, malloc, s_observable::n, observable_calc_structure_factor_fast(), observable_sf_params::order, params, and sf_print_usage().
Referenced by tclcommand_observable().
int tclcommand_observable_tclcommand (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 236 of file statistics_observable_tcl.cpp.
References ARG1_IS_I, s_observable::calculate, Observable_Tclcommand_Arg_Container::command, s_observable::container, Observable_Tclcommand_Arg_Container::interp, s_observable::last_value, malloc, s_observable::n, Observable_Tclcommand_Arg_Container::n_A, observable_calc_tclcommand(), and s_observable::update.
Referenced by tclcommand_observable().
int tclcommand_observable_update (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs)
Definition at line 1788 of file statistics_observable_tcl.cpp.
References observable_update().
Referenced by tclcommand_observable().
int tclcommand_parse_profile (Tcl_Interp * interp, int argc, char ** argv, int * change, int * dim_A, profile_data ** pdata_)
Definition at line 1441 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, ARG1_IS_D, ARG1_IS_I, box_l, profile_data::id_list, malloc, profile_data::maxx, profile_data::maxy, profile_data::maxz, profile_data::minx, profile_data::miny, profile_data::minz, parse_id_list(), profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable_density_profile(), tclcommand_observable_flux_density_profile(), tclcommand_observable_force_density_profile(), and tclcommand_observable_lb_velocity_profile().
int tclcommand_parse_radial_profile (Tcl_Interp * interp, int argc, char ** argv, int * change, int * dim_A, radial_profile_data ** pdata)
Definition at line 1565 of file statistics_observable_tcl.cpp.
References ARG0_IS_S, ARG1_IS_D, ARG1_IS_I, ARG_IS_D, radial_profile_data::axis, box_l, radial_profile_data::center, radial_profile_data::id_list, malloc, radial_profile_data::maxphi, radial_profile_data::maxr, radial_profile_data::maxz, radial_profile_data::minphi, radial_profile_data::minr, radial_profile_data::minz, parse_id_list(), radial_profile_data::phibins, PI, radial_profile_data::rbins, and radial_profile_data::zbins.
Referenced by tclcommand_observable_lb_radial_velocity_profile(), tclcommand_observable_radial_density_profile(), and tclcommand_observable_radial_flux_density_profile().