ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_observable_tcl.hpp File Reference
statistics_observable_tcl.hpp File Reference
#include "config.hpp"
#include <tcl.h>
#include "statistics_observable.hpp"
Data Structures
struct Observable_Tclcommand_Arg_Container
Functions
int tclcommand_observable (ClientData data, Tcl_Interp *interp, int argc, char **argv)
int tclcommand_observable_print_formatted (Tcl_Interp *interp, int argc, char **argv, int *change, observable *obs, double *values)
int parse_id_list (Tcl_Interp *interp, int argc, char **argv, int *change, IntList **ids)
int observable_calc_tclcommand (observable *self)
Function Documentation
int observable_calc_tclcommand (observable * self)
Definition at line 1801 of file statistics_observable_tcl.cpp.
References Observable_Tclcommand_Arg_Container::command, and Observable_Tclcommand_Arg_Container::interp.
Referenced by tclcommand_observable_tclcommand().
int parse_id_list (Tcl_Interp * interp, int argc, char ** argv, int * change, IntList ** ids)
Definition at line 35 of file statistics_observable_tcl.cpp.
References alloc_intlist(), ARG0_IS_S, convert_types_to_ids(), IntList::e, i, init_intlist(), malloc, IntList::n, n_part, parse_int_list(), and sortPartCfg().
Referenced by tcl_parse_k_dist(), tcl_parse_persistence_length(), tcl_parse_radial_density_distribution(), tcl_parse_spatial_polymer_properties(), tclcommand_observable_com_force(), tclcommand_observable_com_position(), tclcommand_observable_com_velocity(), tclcommand_observable_currents(), tclcommand_observable_dipole_moment(), tclcommand_observable_interacts_with(), tclcommand_observable_particle_angular_momentum(), tclcommand_observable_particle_body_angular_momentum(), tclcommand_observable_particle_body_velocities(), tclcommand_observable_particle_currents(), tclcommand_observable_particle_forces(), tclcommand_observable_particle_positions(), tclcommand_observable_particle_velocities(), tclcommand_parse_profile(), and tclcommand_parse_radial_profile().
int tclcommand_observable (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1301 of file statistics_observable_tcl.cpp.
References ARG1_IS_I, ARG1_IS_S, ARG_IS_D, ARG_IS_S, s_observable::autoupdate, n_observables, observable_read(), observable_reset_average(), observable_update_average(), observable_write(), observables, observables_autoupdate, realloc, REGISTER_OBSERVABLE, tcl_command_k_dist(), tcl_command_persistence_length(), tcl_command_radial_density_distribution(), tcl_command_spatial_polymer_properties(), tclcommand_observable_average(), tclcommand_observable_com_force(), tclcommand_observable_com_position(), tclcommand_observable_com_velocity(), tclcommand_observable_currents(), tclcommand_observable_density_profile(), tclcommand_observable_dipole_moment(), tclcommand_observable_flux_density_profile(), tclcommand_observable_force_density_profile(), tclcommand_observable_interacts_with(), tclcommand_observable_lb_radial_velocity_profile(), tclcommand_observable_lb_velocity_profile(), tclcommand_observable_particle_angular_momentum(), tclcommand_observable_particle_body_angular_momentum(), tclcommand_observable_particle_body_velocities(), tclcommand_observable_particle_currents(), tclcommand_observable_particle_forces(), tclcommand_observable_particle_positions(), tclcommand_observable_particle_velocities(), tclcommand_observable_print(), tclcommand_observable_radial_density_profile(), tclcommand_observable_radial_flux_density_profile(), tclcommand_observable_rdf(), tclcommand_observable_stress_tensor(), tclcommand_observable_stress_tensor_acf_obs(), tclcommand_observable_structure_factor(), tclcommand_observable_structure_factor_fast(), tclcommand_observable_tclcommand(), and tclcommand_observable_update().
Referenced by tcl_register_commands().
int tclcommand_observable_print_formatted (Tcl_Interp * interp, int argc, char ** argv, int * change, observable * obs, double * values)
Definition at line 1753 of file statistics_observable_tcl.cpp.
References s_observable::calculate, s_observable::container, observable_calc_density_profile(), observable_calc_flux_density_profile(), observable_calc_force_density_profile(), observable_calc_lb_radial_velocity_profile(), observable_calc_lb_velocity_profile(), observable_calc_radial_density_profile(), observable_calc_radial_flux_density_profile(), observable_calc_structure_factor(), observable_calc_structure_factor_fast(), observable_update_average(), tclcommand_observable_print_profile_formatted(), tclcommand_observable_print_radial_profile_formatted(), tclcommand_observable_print_structure_factor_fast_formatted(), tclcommand_observable_print_structure_factor_formatted(), and s_observable::update.
Referenced by correlation_print_average1(), and tclcommand_observable_print().