ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_tcl.hpp File Reference
statistics_tcl.hpp File Reference
#include "parser.hpp"
Functions
int tclcommand_analyze (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implements the Tcl command tclcommand_analyze.
double tclcommand_analyze_print_MSD (Tcl_Interp *interp, int type_m, int n_time_steps, int n_conf)
return the approx diffusion constant of a special type of particle FIXME: this is not a smart way to compute D (very error-prone)!
Function Documentation
int tclcommand_analyze (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implements the Tcl command tclcommand_analyze.
This allows for basic system analysis, both online and offline.
Definition at line 2714 of file statistics_tcl.cpp.
References err, gather_runtime_errors(), REGISTER_ANALYSIS, REGISTER_ANALYSIS_W_ARG, REGISTER_ANALYZE_OPTION, REGISTER_ANALYZE_STORAGE, tclcommand_analyze_current(), tclcommand_analyze_parse_activate(), tclcommand_analyze_parse_aggregation(), tclcommand_analyze_parse_and_print_check_mol(), tclcommand_analyze_parse_and_print_dipmom_mol(), tclcommand_analyze_parse_and_print_dipole(), tclcommand_analyze_parse_and_print_energy(), tclcommand_analyze_parse_and_print_energy_kinetic(), tclcommand_analyze_parse_and_print_energy_kinetic_mol(), tclcommand_analyze_parse_and_print_momentum(), tclcommand_analyze_parse_and_print_p_IK1(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_pressure_mol(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_parse_angularmomentum(), tclcommand_analyze_parse_append(), tclcommand_analyze_parse_bilayer_density_profile(), tclcommand_analyze_parse_bilayer_set(), tclcommand_analyze_parse_bins(), tclcommand_analyze_parse_bond_dist(), tclcommand_analyze_parse_bond_l(), tclcommand_analyze_parse_cell_gpb(), tclcommand_analyze_parse_centermass(), tclcommand_analyze_parse_cluster_size_dist(), tclcommand_analyze_parse_configs(), tclcommand_analyze_parse_cwvac(), tclcommand_analyze_parse_cylindrical_average(), tclcommand_analyze_parse_density_profile_av(), tclcommand_analyze_parse_diffusion_profile(), tclcommand_analyze_parse_distribution(), tclcommand_analyze_parse_distto(), tclcommand_analyze_parse_find_principal_axis(), tclcommand_analyze_parse_fluid(), tclcommand_analyze_parse_formfactor(), tclcommand_analyze_parse_g123(), tclcommand_analyze_parse_g_av(), tclcommand_analyze_parse_get_folded_positions(), tclcommand_analyze_parse_get_lipid_orients(), tclcommand_analyze_parse_gyration_tensor(), tclcommand_analyze_parse_holes(), tclcommand_analyze_parse_internal_dist(), tclcommand_analyze_parse_lipid_orient_order(), tclcommand_analyze_parse_local_stress_tensor(), tclcommand_analyze_parse_mindist(), tclcommand_analyze_parse_modes2d(), tclcommand_analyze_parse_mol(), tclcommand_analyze_parse_momentofinertiamatrix(), tclcommand_analyze_parse_MSD(), tclcommand_analyze_parse_nbhood(), tclcommand_analyze_parse_necklace(), tclcommand_analyze_parse_push(), tclcommand_analyze_parse_radial_density_map(), tclcommand_analyze_parse_rdf(), tclcommand_analyze_parse_rdfchain(), tclcommand_analyze_parse_re(), tclcommand_analyze_parse_remove(), tclcommand_analyze_parse_replace(), tclcommand_analyze_parse_rg(), tclcommand_analyze_parse_rh(), tclcommand_analyze_parse_set(), tclcommand_analyze_parse_stored(), tclcommand_analyze_parse_structurefactor(), tclcommand_analyze_parse_vanhove(), tclcommand_analyze_parse_vel_distr(), tclcommand_analyze_parse_Vkappa(), and tclcommand_analyze_wallstuff().
Referenced by tcl_register_commands().
double tclcommand_analyze_print_MSD (Tcl_Interp * interp, int type_m, int n_time_steps, int n_conf)
return the approx diffusion constant of a special type of particle FIXME: this is not a smart way to compute D (very error-prone)!
Parameters
interp TCL interpreter handle
type_m type of the particle, -1 for all
n_time_steps number of timestep between saved configurations
n_conf number of saved contributions taken into account
Definition at line 2518 of file statistics_tcl.cpp.
References centermass_conf(), configs, distance2(), i, n_configs, n_part, partCfg, sortPartCfg(), and time_step.
Referenced by tclcommand_analyze_parse_MSD().