ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_observable.cpp File Reference
statistics_observable.cpp File Reference
#include "statistics_observable.hpp"
#include "statistics_correlation.hpp"
#include "particle_data.hpp"
#include "integrate.hpp"
#include "lb.hpp"
#include "pressure.hpp"
#include "rotation.hpp"
Functions
void observable_init (observable *self)
int observable_calculate (observable *self)
int observable_update (observable *self)
int observable_write (char *filename, observable *self, bool binary)
int observable_read (char *filename, observable *self, bool binary)
int observable_calc_particle_velocities (observable *self)
int observable_calc_particle_body_velocities (observable *self)
int observable_calc_particle_angular_momentum (observable *self)
int observable_calc_particle_body_angular_momentum (observable *self)
int observable_calc_particle_currents (observable *self)
int observable_calc_currents (observable *self)
int observable_calc_dipole_moment (observable *self)
int observable_calc_com_velocity (observable *self)
int observable_calc_blocked_com_velocity (observable *self)
int observable_calc_blocked_com_position (observable *self)
int observable_calc_com_position (observable *self)
int observable_calc_com_force (observable *self)
int observable_calc_blocked_com_force (observable *self)
int observable_calc_density_profile (observable *self)
int observable_calc_force_density_profile (observable *self)
int observable_calc_lb_velocity_profile (observable *self)
int observable_calc_lb_radial_velocity_profile (observable *self)
void mpi_observable_lb_radial_velocity_profile_slave_implementation ()
int mpi_observable_lb_radial_velocity_profile_parallel (void *pdata_, double *A, unsigned int n_A)
void transform_to_cylinder_coordinates (double x, double y, double z_, double *r, double *phi, double *z)
int observable_calc_radial_density_profile (observable *self)
int observable_calc_radial_flux_density_profile (observable *self)
int observable_calc_flux_density_profile (observable *self)
int observable_calc_particle_positions (observable *self)
Obtain the particle positions.
int observable_calc_particle_forces (observable *self)
int observable_stress_tensor (observable *self)
int observable_calc_stress_tensor_acf_obs (observable *self)
int observable_update_average (observable *self)
int observable_reset_average (observable *self)
int observable_calc_structure_factor (observable *self)
Calculate structure factor from positions and scattering length.
int observable_calc_structure_factor_fast (observable *self)
Calculate structure factor from positions and scattering length.
int observable_calc_interacts_with (observable *self)
See if particles from idList1 interact with any of the particles in idList2 input parameters are passed via struct iw_params.
int observable_calc_rdf (observable *self)
int observable_radial_density_distribution (observable *self)
int observable_spatial_polymer_properties (observable *self)
int observable_persistence_length (observable *self)
int observable_polymer_k_distribution (observable *self)
void autoupdate_observables ()
Variables
observable ** observables = 0
int n_observables = 0
int observables_autoupdate = 0
Function Documentation
void autoupdate_observables ()
Definition at line 1590 of file statistics_observable.cpp.
References i, n_observables, observable_update(), and sim_time.
Referenced by python_integrate(), tclcommand_integrate(), and tclcommand_integrate_sd().
int mpi_observable_lb_radial_velocity_profile_parallel (void * pdata_, double * A, unsigned int n_A)
Definition at line 692 of file statistics_observable.cpp.
References LB_Parameters::agrid, box_l, radial_profile_data::center, i, lb_lbfluid_get_interpolated_velocity(), lbpar, radial_profile_data::maxphi, radial_profile_data::maxr, radial_profile_data::maxz, radial_profile_data::minphi, radial_profile_data::minr, radial_profile_data::minz, my_left, my_right, radial_profile_data::phibins, radial_profile_data::rbins, and radial_profile_data::zbins.
Referenced by mpi_observable_lb_radial_velocity_profile_slave_implementation(), and observable_calc_lb_radial_velocity_profile().
void mpi_observable_lb_radial_velocity_profile_slave_implementation ()
Definition at line 681 of file statistics_observable.cpp.
References comm_cart, free, malloc, MPI_Bcast(), MPI_BYTE, MPI_DOUBLE, mpi_observable_lb_radial_velocity_profile_parallel(), MPI_Reduce(), MPI_SUM, radial_profile_data::phibins, radial_profile_data::rbins, and radial_profile_data::zbins.
Referenced by mpi_observable_lb_radial_velocity_profile_slave().
int observable_calc_blocked_com_force (observable * self)
Definition at line 465 of file statistics_observable.cpp.
References block(), IntList::e, ParticleForce::f, Particle::f, i, IntList::n, n_part, partCfg, runtimeError, sortPartCfg(), and time_step.
Referenced by tclcommand_observable_com_force().
int observable_calc_blocked_com_position (observable * self)
Definition at line 377 of file statistics_observable.cpp.
References block(), IntList::e, i, IntList::n, n_part, ParticlePosition::p, partCfg, PMASS, Particle::r, runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_com_position().
int observable_calc_blocked_com_velocity (observable * self)
Definition at line 341 of file statistics_observable.cpp.
References block(), IntList::e, i, Particle::m, IntList::n, n_part, partCfg, PMASS, runtimeError, sortPartCfg(), time_step, and ParticleMomentum::v.
Referenced by tclcommand_observable_com_velocity().
int observable_calc_com_force (observable * self)
Definition at line 440 of file statistics_observable.cpp.
References IntList::e, ParticleForce::f, Particle::f, i, IntList::n, n_part, partCfg, runtimeError, sortPartCfg(), and time_step.
Referenced by tclcommand_observable_com_force().
int observable_calc_com_position (observable * self)
Definition at line 413 of file statistics_observable.cpp.
References IntList::e, i, IntList::n, n_part, ParticlePosition::p, partCfg, PMASS, Particle::r, runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_com_position().
int observable_calc_com_velocity (observable * self)
Definition at line 315 of file statistics_observable.cpp.
References IntList::e, i, Particle::m, IntList::n, n_part, partCfg, PMASS, runtimeError, sortPartCfg(), time_step, and ParticleMomentum::v.
Referenced by tclcommand_observable_com_velocity().
int observable_calc_currents (observable * self)
Definition at line 262 of file statistics_observable.cpp.
References IntList::e, i, Particle::m, IntList::n, n_part, Particle::p, partCfg, ParticleProperties::q, runtimeError, sortPartCfg(), time_step, and ParticleMomentum::v.
Referenced by tclcommand_observable_currents().
int observable_calc_density_profile (observable * self)
Definition at line 496 of file statistics_observable.cpp.
References profile_data::container, IntList::e, fold_position(), i, ParticleLocal::i, profile_data::id_list, Particle::l, profile_data::maxx, profile_data::maxy, profile_data::maxz, profile_data::minx, profile_data::miny, profile_data::minz, IntList::n, n_part, ParticlePosition::p, partCfg, Particle::r, runtimeError, sortPartCfg(), profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable_density_profile(), and tclcommand_observable_print_formatted().
int observable_calc_dipole_moment (observable * self)
Definition at line 288 of file statistics_observable.cpp.
References IntList::e, i, IntList::n, n_part, ParticlePosition::p, Particle::p, partCfg, ParticleProperties::q, Particle::r, runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_dipole_moment().
int observable_calc_flux_density_profile (observable * self)
Definition at line 925 of file statistics_observable.cpp.
References profile_data::container, IntList::e, fold_position(), i, ParticleLocal::i, profile_data::id_list, Particle::l, Particle::m, profile_data::maxx, profile_data::maxy, profile_data::maxz, profile_data::minx, profile_data::miny, profile_data::minz, IntList::n, n_part, ParticlePosition::p, partCfg, Particle::r, runtimeError, sortPartCfg(), time_step, ParticleMomentum::v, profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable_flux_density_profile(), and tclcommand_observable_print_formatted().
int observable_calc_force_density_profile (observable * self)
Definition at line 534 of file statistics_observable.cpp.
References profile_data::container, IntList::e, ParticleForce::f, Particle::f, fold_position(), i, ParticleLocal::i, profile_data::id_list, Particle::l, profile_data::maxx, profile_data::maxy, profile_data::maxz, profile_data::minx, profile_data::miny, profile_data::minz, IntList::n, n_part, ParticlePosition::p, partCfg, Particle::r, runtimeError, sortPartCfg(), profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable_force_density_profile(), and tclcommand_observable_print_formatted().
int observable_calc_interacts_with (observable * self)
See if particles from idList1 interact with any of the particles in idList2 input parameters are passed via struct iw_params.
Definition at line 1287 of file statistics_observable.cpp.
References iw_params::cutoff, get_mi_vector(), i, iw_params::ids1, iw_params::ids2, n_part, ParticlePosition::p, params, partCfg, Particle::r, runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_interacts_with().
int observable_calc_lb_radial_velocity_profile (observable * self)
Definition at line 654 of file statistics_observable.cpp.
References comm_cart, ES_ERROR, ES_OK, free, LATTICE_LB, LATTICE_LB_GPU, lattice_switch, malloc, MPI_Bcast(), MPI_BYTE, MPI_DOUBLE, mpi_observable_lb_radial_velocity_profile(), mpi_observable_lb_radial_velocity_profile_parallel(), MPI_Reduce(), MPI_SUM, n_nodes, and statistics_observable_lbgpu_radial_velocity_profile().
Referenced by tclcommand_observable_lb_radial_velocity_profile(), and tclcommand_observable_print_formatted().
int observable_calc_lb_velocity_profile (observable * self)
Definition at line 574 of file statistics_observable.cpp.
References LB_Parameters::agrid, box_l, profile_data::container, i, lb_lbfluid_get_interpolated_velocity(), lbpar, profile_data::maxx, profile_data::maxy, profile_data::maxz, profile_data::minx, profile_data::miny, profile_data::minz, profile_data::xbins, profile_data::ybins, and profile_data::zbins.
Referenced by tclcommand_observable_lb_velocity_profile(), and tclcommand_observable_print_formatted().
int observable_calc_particle_angular_momentum (observable * self)
Definition at line 168 of file statistics_observable.cpp.
References define_rotation_matrix(), IntList::e, i, Particle::m, IntList::n, n_part, ParticleMomentum::omega, partCfg, runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_particle_angular_momentum().
int observable_calc_particle_body_angular_momentum (observable * self)
Definition at line 207 of file statistics_observable.cpp.
References IntList::e, i, Particle::m, IntList::n, n_part, ParticleMomentum::omega, partCfg, runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_particle_body_angular_momentum().
int observable_calc_particle_body_velocities (observable * self)
Definition at line 123 of file statistics_observable.cpp.
References define_rotation_matrix(), IntList::e, i, Particle::m, IntList::n, n_part, partCfg, runtimeError, sortPartCfg(), time_step, and ParticleMomentum::v.
Referenced by tclcommand_observable_particle_body_velocities().
int observable_calc_particle_currents (observable * self)
Definition at line 240 of file statistics_observable.cpp.
References IntList::e, i, Particle::m, IntList::n, n_part, Particle::p, partCfg, ParticleProperties::q, runtimeError, sortPartCfg(), time_step, and ParticleMomentum::v.
Referenced by tclcommand_observable_particle_currents().
int observable_calc_particle_forces (observable * self)
Definition at line 1003 of file statistics_observable.cpp.
References IntList::e, ParticleForce::f, Particle::f, i, IntList::n, n_part, partCfg, runtimeError, sortPartCfg(), and time_step.
Referenced by tclcommand_observable_particle_forces().
int observable_calc_particle_positions (observable * self)
Obtain the particle positions.
TODO: Folded or unfolded?
Definition at line 983 of file statistics_observable.cpp.
References IntList::e, i, IntList::n, n_part, ParticlePosition::p, partCfg, Particle::r, runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_particle_positions().
int observable_calc_particle_velocities (observable * self)
Definition at line 103 of file statistics_observable.cpp.
References IntList::e, i, Particle::m, IntList::n, n_part, partCfg, runtimeError, sortPartCfg(), time_step, and ParticleMomentum::v.
Referenced by tclcommand_observable_particle_velocities().
int observable_calc_radial_density_profile (observable * self)
Definition at line 791 of file statistics_observable.cpp.
References radial_profile_data::center, radial_profile_data::container, IntList::e, fold_position(), i, ParticleLocal::i, radial_profile_data::id_list, Particle::l, radial_profile_data::maxphi, radial_profile_data::maxr, radial_profile_data::maxz, radial_profile_data::minphi, radial_profile_data::minr, radial_profile_data::minz, IntList::n, n_part, ParticlePosition::p, partCfg, radial_profile_data::phibins, PI, Particle::r, radial_profile_data::rbins, runtimeError, sortPartCfg(), transform_to_cylinder_coordinates(), and radial_profile_data::zbins.
Referenced by tclcommand_observable_print_formatted(), and tclcommand_observable_radial_density_profile().
int observable_calc_radial_flux_density_profile (observable * self)
Definition at line 837 of file statistics_observable.cpp.
References radial_profile_data::center, CONST_UNITITIALIZED, radial_profile_data::container, IntList::e, ES_ERROR, fold_position(), i, ParticleLocal::i, radial_profile_data::id_list, Particle::l, radial_profile_data::maxphi, radial_profile_data::maxr, radial_profile_data::maxz, radial_profile_data::minphi, radial_profile_data::minr, radial_profile_data::minz, IntList::n, n_part, ParticlePosition::p, partCfg, radial_profile_data::phibins, PI, Particle::r, radial_profile_data::rbins, runtimeError, sim_time, sortPartCfg(), transform_to_cylinder_coordinates(), unfold_position(), and radial_profile_data::zbins.
Referenced by tclcommand_observable_print_formatted(), and tclcommand_observable_radial_flux_density_profile().
int observable_calc_rdf (observable * self)
Definition at line 1332 of file statistics_observable.cpp.
References calc_rdf(), rdf_profile_data::n_p1, rdf_profile_data::n_p2, rdf_profile_data::p1_types, rdf_profile_data::p2_types, rdf_profile_data::r_bins, rdf_profile_data::r_max, rdf_profile_data::r_min, and sortPartCfg().
Referenced by tclcommand_observable_rdf().
int observable_calc_stress_tensor_acf_obs (observable * self)
Definition at line 1036 of file statistics_observable.cpp.
References observable_compute_stress_tensor(), runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_stress_tensor_acf_obs().
int observable_calc_structure_factor (observable * self)
Calculate structure factor from positions and scattering length.
Definition at line 1079 of file statistics_observable.cpp.
References box_l, i, n_part, observable_sf_params::order, ParticlePosition::p, params, partCfg, PI, Particle::r, runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_print_formatted(), and tclcommand_observable_structure_factor().
int observable_calc_structure_factor_fast (observable * self)
Calculate structure factor from positions and scattering length.
Definition at line 1140 of file statistics_observable.cpp.
References box_l, i, observable_sf_params::k_density, n_part, observable_sf_params::order, ParticlePosition::p, params, partCfg, PI, Particle::r, runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_print_formatted(), and tclcommand_observable_structure_factor_fast().
int observable_calculate (observable * self)
Definition at line 38 of file statistics_observable.cpp.
References sim_time.
Referenced by double_correlation_get_data(), observable_reset_average(), observable_update_average(), observable_write(), and tclcommand_observable_print().
void observable_init (observable * self)
Definition at line 31 of file statistics_observable.cpp.
References OBSERVABLE.
int observable_persistence_length (observable * self)
Definition at line 1518 of file statistics_observable.cpp.
References spatial_polym_data::cut_off, i, spatial_polym_data::id_list, IntList::n, normr(), ParticlePosition::p, partCfg, Particle::r, runtimeError, scalar(), sortPartCfg(), and vecsub().
Referenced by tcl_command_persistence_length().
int observable_polymer_k_distribution (observable * self)
Definition at line 1554 of file statistics_observable.cpp.
References get_mi_vector(), i, k_dist_data::id_list, k_dist_data::k, k_dist_data::n_bins, normr(), k_dist_data::npoly, ParticlePosition::p, partCfg, Particle::r, k_dist_data::r_max, k_dist_data::r_min, runtimeError, and sortPartCfg().
Referenced by tcl_command_k_dist().
int observable_radial_density_distribution (observable * self)
Definition at line 1346 of file statistics_observable.cpp.
References angle(), TypeList::cur_size, radial_density_data::end_point, radial_density_data::end_point_id, free, GC_init, get_mi_vector(), i, ParticleLocal::i, radial_density_data::id_flag, radial_density_data::id_list, TypeList::id_list, Index, Particle::l, malloc, TypeList::max_entry, radial_density_data::maxr, radial_density_data::minr, IntList::n, normr(), ParticlePosition::p, partCfg, PI, Particle::r, radial_density_data::rbins, runtimeError, scalar(), sortPartCfg(), radial_density_data::start_point, radial_density_data::start_point_id, radial_density_data::type, IndexOfType::type, type_array, Type_array_init, unfold_position(), unit_vector(), and vecsub().
Referenced by tcl_command_radial_density_distribution().
int observable_read (char * filename, observable * self, bool binary)
Definition at line 80 of file statistics_observable.cpp.
References AVERAGE, ES_ERROR, ES_OK, OBSERVABLE, read_double(), and read_uint().
Referenced by tclcommand_observable().
int observable_reset_average (observable * self)
Definition at line 1068 of file statistics_observable.cpp.
References i, observable_average_container::n_sweeps, observable_calculate(), and observable_average_container::reference_observable.
Referenced by tclcommand_observable().
int observable_spatial_polymer_properties (observable * self)
Definition at line 1496 of file statistics_observable.cpp.
References i, spatial_polym_data::id_list, spatial_polym_data::npoly, Particle::p, partCfg, ParticleProperties::q, runtimeError, and sortPartCfg().
Referenced by tcl_command_spatial_polymer_properties().
int observable_stress_tensor (observable * self)
Definition at line 1024 of file statistics_observable.cpp.
References observable_compute_stress_tensor(), runtimeError, and sortPartCfg().
Referenced by tclcommand_observable_stress_tensor().
int observable_update (observable * self)
Definition at line 46 of file statistics_observable.cpp.
References sim_time.
Referenced by autoupdate_observables(), and tclcommand_observable_update().
int observable_update_average (observable * self)
Definition at line 1055 of file statistics_observable.cpp.
References i, s_observable::last_value, observable_average_container::n_sweeps, observable_calculate(), and observable_average_container::reference_observable.
Referenced by tclcommand_observable(), tclcommand_observable_average(), and tclcommand_observable_print_formatted().
int observable_write (char * filename, observable * self, bool binary)
Definition at line 56 of file statistics_observable.cpp.
References AVERAGE, ES_ERROR, OBSERVABLE, observable_calculate(), write_double(), and write_uint().
Referenced by tclcommand_observable().
void transform_to_cylinder_coordinates (double x, double y, double z_, double * r, double * phi, double * z)
Definition at line 785 of file statistics_observable.cpp.
Referenced by observable_calc_radial_density_profile(), and observable_calc_radial_flux_density_profile().
Variable Documentation
int n_observables = 0
Definition at line 28 of file statistics_observable.cpp.
Referenced by autoupdate_observables(), tclcommand_correlation_parse_corr(), tclcommand_observable(), and tclcommand_observable_average().
observable** observables = 0
Definition at line 27 of file statistics_observable.cpp.
Referenced by tclcommand_correlation_parse_corr(), tclcommand_observable(), and tclcommand_observable_average().
int observables_autoupdate = 0
Definition at line 29 of file statistics_observable.cpp.
Referenced by python_integrate(), tclcommand_integrate(), tclcommand_integrate_sd(), and tclcommand_observable().