ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_molecule.hpp File Reference
statistics_molecule.hpp File Reference
This file contains the code for statistics on the data using the molecule information set with analyse set, as it is described in the file topology.hpp.
#include "utils.hpp"
#include "statistics.hpp"
#include "topology.hpp"
Functions
int analyze_fold_molecules (float *coord, double shift[3])
Using the topology information stored in topology::topology this routine foldes all particles belonging to a molecule such that the center of mass of the molecule is inside the simulation box.
void calc_mol_center_of_mass (Molecule mol, double com[3])
Incorporates mass of each particle.
void mol_center_of_mass_ (Molecule mol, double com[3])
Detailed Description
This file contains the code for statistics on the data using the molecule information set with analyse set, as it is described in the file topology.hpp.
Definition in file statistics_molecule.hpp.
Function Documentation
int analyze_fold_molecules (float * coord, double shift[3])
Using the topology information stored in topology::topology this routine foldes all particles belonging to a molecule such that the center of mass of the molecule is inside the simulation box.
Parameters
coord is an array specifying the full coordinates of all particles. Particles must be stored in particle ID order in this array.
shift is a vector specifying a shift for the entire system coordinates that is applied prior to folding: This is used for visualization purposes.
Definition at line 30 of file statistics_molecule.cpp.
References box_l, box_l_i, calc_mol_center_of_mass(), IntList::e, errexit(), ES_ERROR, ES_OK, i, lees_edwards_offset, IntList::n, n_molecules, Molecule::part, PERIODIC, runtimeError, sortPartCfg(), and topology.
Referenced by tclcommand_analyze_parse_get_folded_positions(), and tclcommand_imd_parse_pos().
void calc_mol_center_of_mass (Molecule mol, double com[3])
Incorporates mass of each particle.
Definition at line 105 of file statistics_molecule.cpp.
References IntList::e, i, IntList::n, Particle::p, Molecule::part, partCfg, and PMASS.
Referenced by analyze_fold_molecules(), and calc_mol_gyr_radius2().
void mol_center_of_mass_ (Molecule mol, double com[3])