ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_tcl.cpp File Reference
statistics_tcl.cpp File Reference
#include <tcl.h>
#include <cstdlib>
#include <cstring>
#include "utils.hpp"
#include "statistics.hpp"
#include "statistics_chain_tcl.hpp"
#include "statistics_molecule.hpp"
#include "statistics_cluster_tcl.hpp"
#include "statistics_fluid_tcl.hpp"
#include "statistics_wallstuff_tcl.hpp"
#include "energy.hpp"
#include "modes.hpp"
#include "pressure_tcl.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "parser.hpp"
#include "particle_data.hpp"
#include "interaction_data.hpp"
#include "domain_decomposition.hpp"
#include "verlet.hpp"
#include "lb.hpp"
#include "virtual_sites_com_tcl.hpp"
#include "initialize.hpp"
#include <iostream>
#include <sstream>
#include <vector>
#include <string>
#include <map>
Macros
#define REGISTER_ANALYZE_OPTION(name, parser) else if (ARG1_IS_S(name)) err = parser(interp, argc - 2, argv + 2)
#define REGISTER_ANALYZE_STORAGE(name, parser) else if (ARG1_IS_S(name)) err = parser(interp, argc - 2, argv + 2)
#define REGISTER_ANALYSIS(name, parser) else if (ARG1_IS_S(name)) err = parser(interp, argc - 2, argv + 2)
#define REGISTER_ANALYSIS_W_ARG(name, parser, arg) else if (ARG1_IS_S(name)) err = parser(interp, arg, argc - 2, argv + 2)
Functions
int tclcommand_analyze_parse_set (Tcl_Interp *interp, int argc, char **argv)
Set the topology.
int tclcommand_analyze_parse_and_print_energy (Tcl_Interp *interp, int argc, char **argv)
write out energy.
static int tclcommand_analyze_parse_reference_point (Tcl_Interp *interp, int *argc, char ***argv, double pos[3], int *pid)
Parses a reference point, i.e.
void tclcommand_analyze_print_vel_distr (Tcl_Interp *interp, int type, int bins, double given_max)
static int tclcommand_analyze_parse_get_folded_positions (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_get_lipid_orients (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_modes2d (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_bilayer_set (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_cylindrical_average (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_radial_density_map (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_bilayer_density_profile (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_lipid_orient_order (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_aggregation (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_mindist (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_centermass (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_angularmomentum (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_cluster_size_dist (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_momentofinertiamatrix (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_gyration_tensor (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_find_principal_axis (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_nbhood (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_distto (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_cell_gpb (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_Vkappa (Tcl_Interp *interp, int argc, char **argv)
Has something to do with computing compressibility from volume fluctuations.
static int tclcommand_analyze_parse_distribution (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_vel_distr (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_rdf (Tcl_Interp *interp, int average, int argc, char **argv)
int tclcommand_analyze_parse_structurefactor (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_density_profile_av (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_diffusion_profile (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_vanhove (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze_current (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_append (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_push (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_replace (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_remove (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_stored (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_configs (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_activate (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_mol (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_and_print_momentum (Tcl_Interp *interp, int argc, char **argv)
static int acf_parse_init (Tcl_Interp *interp, int argc, char **argv, int slot_num)
EXPERIMENTAL [uschille].
static int acf_parse_append (Tcl_Interp *interp, int argc, char **argv, int slot_num)
EXPERIMENTAL [uschille].
static int acf_print (Tcl_Interp *interp, int slot_num)
int acf_cmd (ClientData data, Tcl_Interp *interp, int argc, char **argv)
EXPERIMENTAL [uschille].
double tclcommand_analyze_print_MSD (Tcl_Interp *interp, int type_m, int n_time_steps, int n_conf)
return the approx diffusion constant of a special type of particle FIXME: this is not a smart way to compute D (very error-prone)!
static int tclcommand_analyze_parse_and_print_dipole (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_MSD (Tcl_Interp *interp, int argc, char **argv)
static int tclcommand_analyze_parse_and_print_energy_kinetic (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implements the Tcl command tclcommand_analyze.
Variables
Vkappa_struct Vkappa = {0.0, 0.0, 0.0}
Macro Definition Documentation
#define REGISTER_ANALYSIS (name, parser) else if (ARG1_IS_S(name)) err = parser(interp, argc - 2, argv + 2)
Referenced by tclcommand_analyze().
#define REGISTER_ANALYSIS_W_ARG (name, parser, arg) else if (ARG1_IS_S(name)) err = parser(interp, arg, argc - 2, argv + 2)
Referenced by tclcommand_analyze().
#define REGISTER_ANALYZE_OPTION (name, parser) else if (ARG1_IS_S(name)) err = parser(interp, argc - 2, argv + 2)
Referenced by tclcommand_analyze().
#define REGISTER_ANALYZE_STORAGE (name, parser) else if (ARG1_IS_S(name)) err = parser(interp, argc - 2, argv + 2)
Referenced by tclcommand_analyze().
Function Documentation
int acf_cmd (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
EXPERIMENTAL [uschille].
Definition at line 2479 of file statistics_tcl.cpp.
References acf_parse_append(), acf_parse_init(), acf_print(), ARG1_IS_I, ARG_IS_S, and err.
static int acf_parse_append (Tcl_Interp * interp, int argc, char ** argv, int slot_num) static
EXPERIMENTAL [uschille].
Definition at line 2468 of file statistics_tcl.cpp.
Referenced by acf_cmd().
static int acf_parse_init (Tcl_Interp * interp, int argc, char ** argv, int slot_num) static
EXPERIMENTAL [uschille].
Definition at line 2462 of file statistics_tcl.cpp.
Referenced by acf_cmd().
static int acf_print (Tcl_Interp * interp, int slot_num) static
Definition at line 2473 of file statistics_tcl.cpp.
Referenced by acf_cmd().
int tclcommand_analyze (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implements the Tcl command tclcommand_analyze.
This allows for basic system analysis, both online and offline.
Definition at line 2714 of file statistics_tcl.cpp.
References err, gather_runtime_errors(), REGISTER_ANALYSIS, REGISTER_ANALYSIS_W_ARG, REGISTER_ANALYZE_OPTION, REGISTER_ANALYZE_STORAGE, tclcommand_analyze_current(), tclcommand_analyze_parse_activate(), tclcommand_analyze_parse_aggregation(), tclcommand_analyze_parse_and_print_check_mol(), tclcommand_analyze_parse_and_print_dipmom_mol(), tclcommand_analyze_parse_and_print_dipole(), tclcommand_analyze_parse_and_print_energy(), tclcommand_analyze_parse_and_print_energy_kinetic(), tclcommand_analyze_parse_and_print_energy_kinetic_mol(), tclcommand_analyze_parse_and_print_momentum(), tclcommand_analyze_parse_and_print_p_IK1(), tclcommand_analyze_parse_and_print_pressure(), tclcommand_analyze_parse_and_print_pressure_mol(), tclcommand_analyze_parse_and_print_stress_tensor(), tclcommand_analyze_parse_angularmomentum(), tclcommand_analyze_parse_append(), tclcommand_analyze_parse_bilayer_density_profile(), tclcommand_analyze_parse_bilayer_set(), tclcommand_analyze_parse_bins(), tclcommand_analyze_parse_bond_dist(), tclcommand_analyze_parse_bond_l(), tclcommand_analyze_parse_cell_gpb(), tclcommand_analyze_parse_centermass(), tclcommand_analyze_parse_cluster_size_dist(), tclcommand_analyze_parse_configs(), tclcommand_analyze_parse_cwvac(), tclcommand_analyze_parse_cylindrical_average(), tclcommand_analyze_parse_density_profile_av(), tclcommand_analyze_parse_diffusion_profile(), tclcommand_analyze_parse_distribution(), tclcommand_analyze_parse_distto(), tclcommand_analyze_parse_find_principal_axis(), tclcommand_analyze_parse_fluid(), tclcommand_analyze_parse_formfactor(), tclcommand_analyze_parse_g123(), tclcommand_analyze_parse_g_av(), tclcommand_analyze_parse_get_folded_positions(), tclcommand_analyze_parse_get_lipid_orients(), tclcommand_analyze_parse_gyration_tensor(), tclcommand_analyze_parse_holes(), tclcommand_analyze_parse_internal_dist(), tclcommand_analyze_parse_lipid_orient_order(), tclcommand_analyze_parse_local_stress_tensor(), tclcommand_analyze_parse_mindist(), tclcommand_analyze_parse_modes2d(), tclcommand_analyze_parse_mol(), tclcommand_analyze_parse_momentofinertiamatrix(), tclcommand_analyze_parse_MSD(), tclcommand_analyze_parse_nbhood(), tclcommand_analyze_parse_necklace(), tclcommand_analyze_parse_push(), tclcommand_analyze_parse_radial_density_map(), tclcommand_analyze_parse_rdf(), tclcommand_analyze_parse_rdfchain(), tclcommand_analyze_parse_re(), tclcommand_analyze_parse_remove(), tclcommand_analyze_parse_replace(), tclcommand_analyze_parse_rg(), tclcommand_analyze_parse_rh(), tclcommand_analyze_parse_set(), tclcommand_analyze_parse_stored(), tclcommand_analyze_parse_structurefactor(), tclcommand_analyze_parse_vanhove(), tclcommand_analyze_parse_vel_distr(), tclcommand_analyze_parse_Vkappa(), and tclcommand_analyze_wallstuff().
Referenced by tcl_register_commands().
int tclcommand_analyze_current (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 2102 of file statistics_tcl.cpp.
References i, Particle::m, n_part, Particle::p, partCfg, ParticleProperties::q, time_step, updatePartCfg(), ParticleMomentum::v, and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_activate (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2332 of file statistics_tcl.cpp.
References analyze_activate(), analyze_append(), ARG0_IS_I, i, n_configs, n_part, n_part_conf, and sortPartCfg().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_aggregation (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 920 of file statistics_tcl.cpp.
References aggregation(), ARG_IS_D, ARG_IS_I, cell_structure, CELL_STRUCTURE_DOMDEC, free, i, malloc, max_cut_nonbonded, n_molecules, n_nodes, and CellStructure::type.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_and_print_dipole (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2574 of file statistics_tcl.cpp.
References i, n_part, ParticlePosition::p, Particle::p, partCfg, ParticleProperties::q, Particle::r, runtimeError, sortPartCfg(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_and_print_energy (Tcl_Interp * interp, int argc, char ** argv)
write out energy.
See energy_tcl.cpp
Definition at line 137 of file energy_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, ARG_IS_I, Observable_stat::coulomb, Observable_stat::data, Observable_stat::dipolar, DoubleList::e, ExternalPotential::energy, external_potentials, i, init_energies(), Observable_stat::init_status, master_energy_calc(), DoubleList::n, n_bonded_ia, Observable_stat::n_coulomb, Observable_stat::n_dipolar, n_external_potentials, n_part, n_particle_types, obsstat_bonded(), obsstat_nonbonded(), tclcommand_analyze_print_all(), and total_energy.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_and_print_energy_kinetic (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2656 of file statistics_tcl.cpp.
References ARG0_IS_I, i, n_part, partCfg, PMASS, smaller_time_step, SQR(), sqrlen(), time_step, updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_and_print_momentum (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2431 of file statistics_tcl.cpp.
References ARG0_IS_S, momentum(), momentum_calc(), and mpi_gather_stats().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_angularmomentum (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1098 of file statistics_tcl.cpp.
References angularmomentum(), and ARG0_IS_I.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_append (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2136 of file statistics_tcl.cpp.
References analyze_append(), n_configs, n_part, n_part_conf, and sortPartCfg().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_bilayer_density_profile (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 742 of file statistics_tcl.cpp.
References alloc_doublelist(), ARG0_IS_D, ARG0_IS_I, ARG0_IS_INTLIST, ARG0_IS_S, ARG_IS_D, bilayer_density_profile(), bilayer_density_profile_sphere(), DoubleList::e, free, i, init_doublelist(), init_intlist(), malloc, IntList::max, IntList::n, realloc_doublelist(), realloc_intlist(), xdir, ydir, and zdir.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_bilayer_set (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 390 of file statistics_tcl.cpp.
References ARG0_IS_S, ARG_IS_D, ARG_IS_I, map_to_2dgrid(), mode_grid_3d, mode_grid_changed, STAT_TRACE, stray_cut_off, and this_node.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_cell_gpb (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1409 of file statistics_tcl.cpp.
References ARG_IS_D, ARG_IS_I, calc_cell_gpb(), and usage().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_centermass (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1073 of file statistics_tcl.cpp.
References ARG0_IS_I, and centermass().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_cluster_size_dist (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1123 of file statistics_tcl.cpp.
References ARG0_IS_I, ARG1_IS_D, i, mark_neighbours(), n_part, partCfg, updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_configs (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2281 of file statistics_tcl.cpp.
References analyze_configs(), ARG0_IS_I, ARG_IS_D, configs, free, i, malloc, n_configs, and n_part_conf.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_cylindrical_average (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 425 of file statistics_tcl.cpp.
References ARG_IS_D, ARG_IS_DOUBLELIST, ARG_IS_I, ARG_IS_INTLIST, calc_cylindrical_average(), IntList::e, DoubleList::e, i, init_doublelist(), init_intlist(), M_PI, IntList::n, DoubleList::n, and names.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_density_profile_av (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1830 of file statistics_tcl.cpp.
References ARG0_IS_I, ARG1_IS_D, box_l, density_profile_av(), free, i, malloc, n_configs, and sortPartCfg().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_diffusion_profile (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1906 of file statistics_tcl.cpp.
References ARG0_IS_D, ARG0_IS_I, ARG1_IS_D, box_l, calc_diffusion_profile(), free, i, malloc, n_part, and sortPartCfg().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_distribution (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1503 of file statistics_tcl.cpp.
References ARG0_IS_D, ARG0_IS_I, ARG0_IS_INTLIST, ARG1_IS_INTLIST, calc_part_distribution(), IntList::e, free, i, init_intlist(), malloc, IntList::max, min_box_l, n_part, updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_distto (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1377 of file statistics_tcl.cpp.
References distto(), n_part, tclcommand_analyze_parse_reference_point(), and usage().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_find_principal_axis (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1280 of file statistics_tcl.cpp.
References ARG0_IS_I, calc_eigenvalues_3x3(), calc_eigenvector_3x3(), and momentofinertiamatrix().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_get_folded_positions (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 189 of file statistics_tcl.cpp.
References analyze_fold_molecules(), ARG0_IS_S, ARG_IS_D, fold_position(), freePartCfg(), i, Particle::m, malloc, n_part, ParticlePosition::p, partCfg, Particle::r, runtimeError, sortPartCfg(), STAT_TRACE, this_node, updatePartCfg(), ParticleMomentum::v, and WITH_BONDS.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_get_lipid_orients (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 293 of file statistics_tcl.cpp.
References IntList::e, get_lipid_orients(), i, init_intlist(), n_molecules, realloc_intlist(), STAT_TRACE, this_node, xdir, ydir, and zdir.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_gyration_tensor (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1226 of file statistics_tcl.cpp.
References ARG0_IS_I, calc_gyration_tensor(), free, and n_particle_types.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_lipid_orient_order (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 866 of file statistics_tcl.cpp.
References ARG0_IS_S, free, i, malloc, n_molecules, n_part, and orient_order().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_mindist (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1032 of file statistics_tcl.cpp.
References ARG0_IS_INTLIST, ARG1_IS_INTLIST, init_intlist(), mindist(), and n_part.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_modes2d (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 324 of file statistics_tcl.cpp.
References free, i, malloc, mode_grid_3d, modes2d(), n_part, STAT_TRACE, this_node, xdir, ydir, and zdir.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_mol (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2370 of file statistics_tcl.cpp.
References ARG0_IS_I, ARG0_IS_S, Molecule::fav, Molecule::favcounter, i, n_molecules, and topology.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_momentofinertiamatrix (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1200 of file statistics_tcl.cpp.
References ARG0_IS_I, and momentofinertiamatrix().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_MSD (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2606 of file statistics_tcl.cpp.
References ARG0_IS_I, ARG1_IS_I, n_configs, and tclcommand_analyze_print_MSD().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_nbhood (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1311 of file statistics_tcl.cpp.
References ARG0_IS_D, ARG0_IS_S, ARG_IS_I, IntList::e, i, IntList::n, n_part, nbhood(), realloc_intlist(), tclcommand_analyze_parse_reference_point(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_push (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2164 of file statistics_tcl.cpp.
References analyze_append(), analyze_push(), analyze_remove(), ARG0_IS_I, i, n_configs, n_part, n_part_conf, and sortPartCfg().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_radial_density_map (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 572 of file statistics_tcl.cpp.
References alloc_doublelist(), alloc_intlist(), ARG_IS_D, ARG_IS_I, ARG_IS_INTLIST, calc_radial_density_map(), IntList::e, DoubleList::e, free, i, init_doublelist(), init_intlist(), malloc, IntList::max, IntList::n, realloc_doublelist(), and realloc_intlist().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_rdf (Tcl_Interp * interp, int average, int argc, char ** argv) static
Definition at line 1658 of file statistics_tcl.cpp.
References ARG0_IS_D, ARG0_IS_I, ARG0_IS_INTLIST, ARG1_IS_INTLIST, calc_rdf(), calc_rdf_av(), calc_rdf_intermol_av(), IntList::e, free, i, init_intlist(), malloc, IntList::max, min_box_l, n_configs, and sortPartCfg().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_reference_point (Tcl_Interp * interp, int * argc, char *** argv, double pos[3], int * pid) static
Parses a reference point, i.e.
either three doubles representing a position, or a particle id.
Definition at line 80 of file statistics_tcl.cpp.
References free_particle(), get_particle_data(), ParticlePosition::p, and Particle::r.
Referenced by tclcommand_analyze_parse_distto(), and tclcommand_analyze_parse_nbhood().
static int tclcommand_analyze_parse_remove (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2236 of file statistics_tcl.cpp.
References analyze_remove(), ARG0_IS_I, i, n_configs, and sortPartCfg().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_replace (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2198 of file statistics_tcl.cpp.
References analyze_append(), analyze_replace(), ARG0_IS_I, i, n_configs, n_part, n_part_conf, and sortPartCfg().
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_set (Tcl_Interp * interp, int argc, char ** argv)
Set the topology.
See topology_tcl.cpp
Definition at line 247 of file topology_tcl.cpp.
References ARG0_IS_S, tclcommand_analyze_parse_generic_structure(), tclcommand_analyze_set_parse_chain_topology(), tclcommand_analyze_set_parse_topo_part_sync(), tclcommand_analyze_set_parse_trapmol(), and tclcommand_analyze_set_print_all().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_stored (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 2268 of file statistics_tcl.cpp.
References n_configs.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_structurefactor (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 1798 of file statistics_tcl.cpp.
References ARG0_IS_I, ARG1_IS_I, box_l, calc_structurefactor(), free, i, PI, updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_vanhove (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1991 of file statistics_tcl.cpp.
References ARG0_IS_D, ARG0_IS_I, calc_vanhove(), free, i, malloc, n_configs, and sortPartCfg().
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_vel_distr (Tcl_Interp * interp, int argc, char ** argv) static
Definition at line 1615 of file statistics_tcl.cpp.
References ARG0_IS_I, ARG1_IS_I, ARG_IS_D, tclcommand_analyze_print_vel_distr(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
static int tclcommand_analyze_parse_Vkappa (Tcl_Interp * interp, int argc, char ** argv) static
Has something to do with computing compressibility from volume fluctuations.
Docs missing.
Definition at line 1465 of file statistics_tcl.cpp.
References ARG0_IS_S, ARG_IS_D, box_l, SQR(), and Vkappa.
Referenced by tclcommand_analyze().
double tclcommand_analyze_print_MSD (Tcl_Interp * interp, int type_m, int n_time_steps, int n_conf)
return the approx diffusion constant of a special type of particle FIXME: this is not a smart way to compute D (very error-prone)!
Parameters
interp TCL interpreter handle
type_m type of the particle, -1 for all
n_time_steps number of timestep between saved configurations
n_conf number of saved contributions taken into account
Definition at line 2518 of file statistics_tcl.cpp.
References centermass_conf(), configs, distance2(), i, n_configs, n_part, partCfg, sortPartCfg(), and time_step.
Referenced by tclcommand_analyze_parse_MSD().
void tclcommand_analyze_print_vel_distr (Tcl_Interp * interp, int type, int bins, double given_max)
Definition at line 117 of file statistics_tcl.cpp.
References centermass_vel(), i, Particle::m, n_part, partCfg, time_step, and ParticleMomentum::v.
Referenced by tclcommand_analyze_parse_vel_distr().
Variable Documentation
Vkappa_struct Vkappa = {0.0, 0.0, 0.0}
Definition at line 71 of file statistics_tcl.cpp.
Referenced by tclcommand_analyze_parse_Vkappa().