ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_correlation_tcl.hpp File Reference
statistics_correlation_tcl.hpp File Reference
#include "config.hpp"
#include "tcl.h"
#include "parser.hpp"
#include "statistics_correlation.hpp"
Macros
#define MAXLINELENGTH 2048
#define MIN(a, b) ((a)>(b)?(b):(a))
Functions
int tclcommand_correlation (ClientData data, Tcl_Interp *interp, int argc, char **argv)
This struct allow to use a file as input for the correlation.
int tclcommand_correlation_parse_corr (Tcl_Interp *interp, int no, int argc, char **argv)
int correlation_print_usage (Tcl_Interp *interp)
int parse_structure_factor (Tcl_Interp *interp, int argc, char **argv, int *change, void **A_args, int *tau_lin_p, double *tau_max_p, double *delta_t_p)
int tclcommand_correlation_parse_observable (Tcl_Interp *interp, int argc, char **argv, observable **obs)
int parse_corr_operation (Tcl_Interp *interp, int argc, char **argv, int *change, char **corr_operation_name, unsigned int *dim_corr, unsigned int dim_A, unsigned int dim_B, void **args)
int double_correlation_print_correlation (double_correlation *self, Tcl_Interp *interp)
writes the correlation to the TCL console
int double_correlation_write_to_file (double_correlation *self, char *filename)
int file_data_source_init (file_data_source *self, char *filename, IntList *columns)
int file_data_source_readline (void *xargs, double *A, unsigned int dim_A)
Macro Definition Documentation
#define MAXLINELENGTH 2048
Definition at line 27 of file statistics_correlation_tcl.hpp.
#define MIN (a, b) ((a)>(b)?(b):(a))
Definition at line 29 of file statistics_correlation_tcl.hpp.
Function Documentation
int correlation_print_usage (Tcl_Interp * interp)
int double_correlation_print_correlation (double_correlation * self, Tcl_Interp * interp)
writes the correlation to the TCL console
Definition at line 638 of file statistics_correlation_tcl.cpp.
Referenced by tclcommand_correlation_parse_print().
int double_correlation_write_to_file (double_correlation * self, char * filename)
Definition at line 730 of file statistics_correlation_tcl.cpp.
Referenced by tclcommand_correlation_parse_corr().
int file_data_source_init (file_data_source * self, char * filename, IntList * columns)
int file_data_source_readline (void * xargs, double * A, unsigned int dim_A)
int parse_corr_operation (Tcl_Interp * interp, int argc, char ** argv, int * change, char ** corr_operation_name, unsigned int * dim_corr, unsigned int dim_A, unsigned int dim_B, void ** args)
Definition at line 595 of file statistics_correlation_tcl.cpp.
References alloc_doublelist(), ARG0_IS_S, ARG_IS_D, ARG_IS_S_EXACT, DoubleList::e, i, malloc, and DoubleList::n.
Referenced by tclcommand_correlation_parse_corr().
int parse_structure_factor (Tcl_Interp * interp, int argc, char ** argv, int * change, void ** A_args, int * tau_lin_p, double * tau_max_p, double * delta_t_p)
int tclcommand_correlation (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
This struct allow to use a file as input for the correlation.
It is initalized and then just passed as extra argument to the file_data_source_readline function that extracts floating point values from the particular file.The TCL command parser
Definition at line 216 of file statistics_correlation_tcl.cpp.
References ARG0_IS_I, ARG0_IS_S, correlation_print_parameters_all(), correlations, i, n_correlations, tclcommand_correlation_parse_corr(), and tclcommand_correlation_print_usage().
Referenced by tcl_register_commands().
int tclcommand_correlation_parse_corr (Tcl_Interp * interp, int no, int argc, char ** argv)
Definition at line 306 of file statistics_correlation_tcl.cpp.
References ARG0_IS_S, ARG0_IS_S_EXACT, ARG1_IS_D, ARG1_IS_I, ARG_IS_S_EXACT, correlation_print_parameters(), correlations, double_correlation_finalize(), double_correlation_get_data(), double_correlation_get_data_errors, double_correlation_init(), double_correlation_read_data_from_file(), double_correlation_write_data_to_file(), double_correlation_write_to_file(), init_errors, malloc, s_observable::n, n_correlations, n_observables, observables, parse_corr_operation(), realloc, tclcommand_correlation_parse_autoupdate(), tclcommand_correlation_parse_print(), and tclcommand_correlation_print_usage().
Referenced by tclcommand_correlation().
int tclcommand_correlation_parse_observable (Tcl_Interp * interp, int argc, char ** argv, observable ** obs)