ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: statistics_wallstuff.cpp File Reference
statistics_wallstuff.cpp File Reference
#include "statistics_wallstuff.hpp"
#include "utils.hpp"
#include "grid.hpp"
Functions
void wall_sort_particles ()
sort particles into bins along the x-coordinate
void calc_wallmsdyz (double *g, int bin)
yz-MSD in a x-bin - use wall_sort_particles before
void calc_wallmsdx (double *g, int bin)
x-MSD in a x-bin - use wall_sort_particles before
void calc_wallbondyz (double *g, int bin, double rclocal, double rmax, int rbins)
bond order parameter G_6 in xy, in a x-bin - use wall_sort_particles before
void calc_scaling (double *g, int bin, int boxes, double rclocal)
scaling of the bond order parameter in xy, in a x-bin - use wall_sort_particles before
void calc_scaling2 (double *g, int bin, int boxes, double rclocal)
scaling of the bond order parameter in xy, in a x-bin - use wall_sort_particles before.
void calc_wallrdfyz (double *g, int bin, double rmin, double rmax, int rbins)
radial distribution function in xy, in a x-bin - use wall_sort_particles before
Variables
DoubleList wallstuff_boundaries = { NULL, 0 }
list of the currently specified box boundaries for layerwise analysis
IntList * wallstuff_part_in_bin = NULL
particles in the bins defined by wallstuff_boundaries.
Function Documentation
void calc_scaling (double * g, int bin, int boxes, double rclocal)
scaling of the bond order parameter in xy, in a x-bin - use wall_sort_particles before
Definition at line 211 of file statistics_wallstuff.cpp.
References box_l, fold_position(), get_mi_vector(), i, ParticleLocal::i, Particle::l, Particle::m, IntList::n, ParticlePosition::p, Particle::p, partCfg, Particle::r, SQR(), and ParticleMomentum::v.
Referenced by tclcommand_analyze_wallstuff().
void calc_scaling2 (double * g, int bin, int boxes, double rclocal)
scaling of the bond order parameter in xy, in a x-bin - use wall_sort_particles before.
This returns the raw values, to be processed later, e.g. to calculate the Binder cumulant.
Definition at line 304 of file statistics_wallstuff.cpp.
References box_l, fold_position(), get_mi_vector(), i, ParticleLocal::i, Particle::l, Particle::m, IntList::n, ParticlePosition::p, Particle::p, partCfg, Particle::r, SQR(), and ParticleMomentum::v.
Referenced by tclcommand_analyze_wallstuff().
void calc_wallbondyz (double * g, int bin, double rclocal, double rmax, int rbins)
bond order parameter G_6 in xy, in a x-bin - use wall_sort_particles before
Definition at line 100 of file statistics_wallstuff.cpp.
References get_mi_vector(), i, IntList::n, ParticlePosition::p, Particle::p, partCfg, Particle::r, and SQR().
Referenced by tclcommand_analyze_wallstuff().
void calc_wallmsdx (double * g, int bin)
x-MSD in a x-bin - use wall_sort_particles before
Definition at line 86 of file statistics_wallstuff.cpp.
References configs, IntList::e, i, IntList::n, n_configs, and SQR().
Referenced by tclcommand_analyze_wallstuff().
void calc_wallmsdyz (double * g, int bin)
yz-MSD in a x-bin - use wall_sort_particles before
Definition at line 66 of file statistics_wallstuff.cpp.
References configs, IntList::e, i, IntList::n, n_configs, and SQR().
Referenced by tclcommand_analyze_wallstuff().
void calc_wallrdfyz (double * g, int bin, double rmin, double rmax, int rbins)
radial distribution function in xy, in a x-bin - use wall_sort_particles before
Definition at line 411 of file statistics_wallstuff.cpp.
References box_l, IntList::e, DoubleList::e, get_mi_vector(), i, IntList::n, ParticlePosition::p, Particle::p, partCfg, PI, Particle::r, and SQR().
Referenced by tclcommand_analyze_wallstuff().
void wall_sort_particles ()
sort particles into bins along the x-coordinate
Definition at line 30 of file statistics_wallstuff.cpp.
References IntList::e, DoubleList::e, i, init_intlist(), IntList::n, DoubleList::n, n_part, ParticlePosition::p, partCfg, Particle::r, realloc, realloc_grained_intlist(), and realloc_intlist().
Referenced by tclcommand_analyze_wallstuff().
Variable Documentation
DoubleList wallstuff_boundaries = { NULL, 0 }
list of the currently specified box boundaries for layerwise analysis
Definition at line 26 of file statistics_wallstuff.cpp.
Referenced by tclcommand_analyze_wallstuff().
IntList* wallstuff_part_in_bin = NULL
particles in the bins defined by wallstuff_boundaries.
There is one less bin that boundaries.
Definition at line 28 of file statistics_wallstuff.cpp.
Referenced by tclcommand_analyze_wallstuff().