ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: steppot.hpp File Reference
steppot.hpp File Reference
Routines to calculate the smooth step potential energy and/or force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
#include "mol_cut.hpp"
Functions
int smooth_step_set_params (int part_type_a, int part_type_b, double d, int n, double eps, double k0, double sig, double cut)
void add_SmSt_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double dist2, double force[3])
Calculate smooth step force between particle p1 and p2.
double SmSt_pair_energy (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double dist2)
calculate smooth step potential energy between particle p1 and p2.
Detailed Description
Routines to calculate the smooth step potential energy and/or force for a particle pair.
forces.cpp
Definition in file steppot.hpp.
Function Documentation
void add_SmSt_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double dist2, double force[3]) inline
Calculate smooth step force between particle p1 and p2.
Definition at line 44 of file steppot.hpp.
References CUTOFF_CHECK, IA_parameters::SmSt_d, IA_parameters::SmSt_eps, IA_parameters::SmSt_k0, IA_parameters::SmSt_n, IA_parameters::SmSt_sig, and SQR().
Referenced by calc_non_bonded_pair_force_parts().
int smooth_step_set_params (int part_type_a, int part_type_b, double d, int n, double eps, double k0, double sig, double cut)
Definition at line 30 of file steppot.cpp.
References ES_ERROR, ES_OK, get_ia_param_safe(), mpi_bcast_ia_params(), IA_parameters::SmSt_cut, IA_parameters::SmSt_d, IA_parameters::SmSt_eps, IA_parameters::SmSt_k0, IA_parameters::SmSt_n, and IA_parameters::SmSt_sig.
Referenced by tclcommand_inter_parse_SmSt().
double SmSt_pair_energy (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double dist2) inline
calculate smooth step potential energy between particle p1 and p2.
Definition at line 62 of file steppot.hpp.
References CUTOFF_CHECK, IA_parameters::SmSt_d, IA_parameters::SmSt_eps, IA_parameters::SmSt_k0, IA_parameters::SmSt_n, and IA_parameters::SmSt_sig.
Referenced by calc_non_bonded_pair_energy().