ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: stretching_force.hpp File Reference
stretching_force.hpp File Reference
Routines to calculate the STRETCHING_FORCE Energy or/and STRETCHING_FORCE force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
Functions
int stretching_force_set_params (int bond_type, double r0, double ks)
set the parameters for the stretching_force potential
double KS (double lambda)
int calc_stretching_force_pair_force (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double force[3])
Computes the STRETCHING_FORCE pair force and adds this force to the particle forces (see tclcommand_inter).
Detailed Description
Routines to calculate the STRETCHING_FORCE Energy or/and STRETCHING_FORCE force for a particle pair.
(Dupin2007) forces.cpp
Definition in file stretching_force.hpp.
Function Documentation
int calc_stretching_force_pair_force (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double force[3]) inline
Computes the STRETCHING_FORCE pair force and adds this force to the particle forces (see tclcommand_inter).
Parameters
p1 Pointer to first particle.
p2 Pointer to second particle.
iaparams spring stiffness ks, initial distance between particles (see tclcommand_inter).
dx particle distance vector
force returns force of particle 1
Returns
true if the bond is broken
Definition at line 53 of file stretching_force.hpp.
References check_id, ParticleForce::f, Particle::f, i, ParticleProperties::identity, KS(), Stretching_force_bond_parameters::ks, ONEPART_TRACE, Particle::p, Bonded_ia_parameters::p, Stretching_force_bond_parameters::r0, sqrlen(), Bond_parameters::stretching_force, and this_node.
Referenced by add_bonded_force().
double KS (double lambda) inline
Definition at line 38 of file stretching_force.hpp.
Referenced by calc_stretching_force_pair_force().
int stretching_force_set_params (int bond_type, double r0, double ks)
set the parameters for the stretching_force potential
Definition at line 28 of file stretching_force.cpp.
References bonded_ia_params, BONDED_IA_STRETCHING_FORCE, ES_ERROR, ES_OK, Stretching_force_bond_parameters::ks, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Stretching_force_bond_parameters::r0, Bond_parameters::stretching_force, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_stretching_force().