ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: stretchlin_force.hpp File Reference
stretchlin_force.hpp File Reference
Routines to calculate the STRETCHLIN_FORCE Energy or/and STRETCHLIN_FORCE force for a particle pair.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
Functions
int stretchlin_force_set_params (int bond_type, double r0, double kslin)
set the parameters for the stretchlin_force potential
int calc_stretchlin_force_pair_force (Particle *p1, Particle *p2, Bonded_ia_parameters *iaparams, double dx[3], double force[3])
Computes the STRETCHLIN_FORCE pair force and adds this force to the particle forces (see #inter).
Detailed Description
Routines to calculate the STRETCHLIN_FORCE Energy or/and STRETCHLIN_FORCE force for a particle pair.
(Dupin2007) forces.cpp
Definition in file stretchlin_force.hpp.
Function Documentation
int calc_stretchlin_force_pair_force (Particle * p1, Particle * p2, Bonded_ia_parameters * iaparams, double dx[3], double force[3]) inline
Computes the STRETCHLIN_FORCE pair force and adds this force to the particle forces (see #inter).
Parameters
p1 Pointer to first particle.
p2 Pointer to second particle.
iaparams spring stiffness ks, initial distance between particles (see #inter).
dx particle distance vector
force returns force of particle 1
Returns
true if the bond is broken
Definition at line 48 of file stretchlin_force.hpp.
References check_id, ParticleForce::f, Particle::f, i, ParticleProperties::identity, Stretchlin_force_bond_parameters::kslin, ONEPART_TRACE, Particle::p, Bonded_ia_parameters::p, Stretchlin_force_bond_parameters::r0, sqrlen(), Bond_parameters::stretchlin_force, and this_node.
Referenced by add_bonded_force().
int stretchlin_force_set_params (int bond_type, double r0, double kslin)
set the parameters for the stretchlin_force potential
Definition at line 28 of file stretchlin_force.cpp.
References bonded_ia_params, BONDED_IA_STRETCHLIN_FORCE, ES_ERROR, ES_OK, Stretchlin_force_bond_parameters::kslin, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Stretchlin_force_bond_parameters::r0, Bond_parameters::stretchlin_force, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_stretchlin_force().