ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: s_observable Struct Reference
s_observable Struct Reference
#include <statistics_observable.hpp>
Data Fields
ObservableType type
char * obs_name
void * container
int n
int(* update)(struct s_observable *obs)
int(* calculate)(struct s_observable *obs)
double * last_value
double last_update
int autoupdate
double autoupdate_dt
Detailed Description
Definition at line 35 of file statistics_observable.hpp.
Field Documentation
int s_observable::autoupdate
Definition at line 44 of file statistics_observable.hpp.
Referenced by tclcommand_observable().
double s_observable::autoupdate_dt
Definition at line 45 of file statistics_observable.hpp.
int(* s_observable::calculate) (struct s_observable *obs)
Definition at line 41 of file statistics_observable.hpp.
Referenced by tcl_command_k_dist(), tcl_command_persistence_length(), tcl_command_radial_density_distribution(), tcl_command_spatial_polymer_properties(), tclcommand_observable_average(), tclcommand_observable_com_force(), tclcommand_observable_com_position(), tclcommand_observable_com_velocity(), tclcommand_observable_currents(), tclcommand_observable_density_profile(), tclcommand_observable_dipole_moment(), tclcommand_observable_flux_density_profile(), tclcommand_observable_force_density_profile(), tclcommand_observable_interacts_with(), tclcommand_observable_lb_radial_velocity_profile(), tclcommand_observable_lb_velocity_profile(), tclcommand_observable_particle_angular_momentum(), tclcommand_observable_particle_body_angular_momentum(), tclcommand_observable_particle_body_velocities(), tclcommand_observable_particle_currents(), tclcommand_observable_particle_forces(), tclcommand_observable_particle_positions(), tclcommand_observable_particle_velocities(), tclcommand_observable_print_formatted(), tclcommand_observable_radial_density_profile(), tclcommand_observable_radial_flux_density_profile(), tclcommand_observable_rdf(), tclcommand_observable_stress_tensor(), tclcommand_observable_stress_tensor_acf_obs(), tclcommand_observable_structure_factor(), tclcommand_observable_structure_factor_fast(), and tclcommand_observable_tclcommand().
void* s_observable::container
Definition at line 38 of file statistics_observable.hpp.
Referenced by tcl_command_k_dist(), tcl_command_persistence_length(), tcl_command_radial_density_distribution(), tcl_command_spatial_polymer_properties(), tclcommand_observable_average(), tclcommand_observable_com_force(), tclcommand_observable_com_position(), tclcommand_observable_com_velocity(), tclcommand_observable_currents(), tclcommand_observable_density_profile(), tclcommand_observable_dipole_moment(), tclcommand_observable_flux_density_profile(), tclcommand_observable_force_density_profile(), tclcommand_observable_interacts_with(), tclcommand_observable_lb_radial_velocity_profile(), tclcommand_observable_lb_velocity_profile(), tclcommand_observable_particle_angular_momentum(), tclcommand_observable_particle_body_angular_momentum(), tclcommand_observable_particle_body_velocities(), tclcommand_observable_particle_currents(), tclcommand_observable_particle_forces(), tclcommand_observable_particle_positions(), tclcommand_observable_particle_velocities(), tclcommand_observable_print_formatted(), tclcommand_observable_print_profile_formatted(), tclcommand_observable_print_radial_profile_formatted(), tclcommand_observable_print_structure_factor_fast_formatted(), tclcommand_observable_print_structure_factor_formatted(), tclcommand_observable_radial_density_profile(), tclcommand_observable_radial_flux_density_profile(), tclcommand_observable_rdf(), tclcommand_observable_stress_tensor(), tclcommand_observable_stress_tensor_acf_obs(), tclcommand_observable_structure_factor(), tclcommand_observable_structure_factor_fast(), and tclcommand_observable_tclcommand().
double s_observable::last_update
Definition at line 43 of file statistics_observable.hpp.
double* s_observable::last_value
Definition at line 42 of file statistics_observable.hpp.
Referenced by observable_update_average(), tcl_command_k_dist(), tcl_command_persistence_length(), tcl_command_radial_density_distribution(), tcl_command_spatial_polymer_properties(), tclcommand_observable_average(), tclcommand_observable_com_force(), tclcommand_observable_com_position(), tclcommand_observable_com_velocity(), tclcommand_observable_currents(), tclcommand_observable_density_profile(), tclcommand_observable_dipole_moment(), tclcommand_observable_flux_density_profile(), tclcommand_observable_force_density_profile(), tclcommand_observable_interacts_with(), tclcommand_observable_lb_radial_velocity_profile(), tclcommand_observable_lb_velocity_profile(), tclcommand_observable_particle_angular_momentum(), tclcommand_observable_particle_body_angular_momentum(), tclcommand_observable_particle_body_velocities(), tclcommand_observable_particle_currents(), tclcommand_observable_particle_forces(), tclcommand_observable_particle_positions(), tclcommand_observable_particle_velocities(), tclcommand_observable_print(), tclcommand_observable_print_structure_factor_formatted(), tclcommand_observable_radial_density_profile(), tclcommand_observable_radial_flux_density_profile(), tclcommand_observable_rdf(), tclcommand_observable_stress_tensor(), tclcommand_observable_stress_tensor_acf_obs(), tclcommand_observable_structure_factor(), tclcommand_observable_structure_factor_fast(), and tclcommand_observable_tclcommand().
int s_observable::n
Definition at line 39 of file statistics_observable.hpp.
Referenced by average_init(), tcl_command_k_dist(), tcl_command_persistence_length(), tcl_command_radial_density_distribution(), tcl_command_spatial_polymer_properties(), tclcommand_correlation_parse_corr(), tclcommand_observable_average(), tclcommand_observable_com_force(), tclcommand_observable_com_position(), tclcommand_observable_com_velocity(), tclcommand_observable_currents(), tclcommand_observable_density_profile(), tclcommand_observable_dipole_moment(), tclcommand_observable_flux_density_profile(), tclcommand_observable_force_density_profile(), tclcommand_observable_interacts_with(), tclcommand_observable_lb_radial_velocity_profile(), tclcommand_observable_lb_velocity_profile(), tclcommand_observable_particle_angular_momentum(), tclcommand_observable_particle_body_angular_momentum(), tclcommand_observable_particle_body_velocities(), tclcommand_observable_particle_currents(), tclcommand_observable_particle_forces(), tclcommand_observable_particle_positions(), tclcommand_observable_particle_velocities(), tclcommand_observable_print(), tclcommand_observable_radial_density_profile(), tclcommand_observable_radial_flux_density_profile(), tclcommand_observable_rdf(), tclcommand_observable_stress_tensor(), tclcommand_observable_stress_tensor_acf_obs(), tclcommand_observable_structure_factor(), tclcommand_observable_structure_factor_fast(), and tclcommand_observable_tclcommand().
char* s_observable::obs_name
Definition at line 37 of file statistics_observable.hpp.
Referenced by tclcommand_observable_print().
ObservableType s_observable::type
Definition at line 36 of file statistics_observable.hpp.
Referenced by tclcommand_observable_average().
int(* s_observable::update) (struct s_observable *obs)
Definition at line 40 of file statistics_observable.hpp.
Referenced by tclcommand_observable_average(), tclcommand_observable_com_force(), tclcommand_observable_com_position(), tclcommand_observable_com_velocity(), tclcommand_observable_currents(), tclcommand_observable_density_profile(), tclcommand_observable_dipole_moment(), tclcommand_observable_flux_density_profile(), tclcommand_observable_force_density_profile(), tclcommand_observable_interacts_with(), tclcommand_observable_lb_radial_velocity_profile(), tclcommand_observable_lb_velocity_profile(), tclcommand_observable_particle_angular_momentum(), tclcommand_observable_particle_body_angular_momentum(), tclcommand_observable_particle_body_velocities(), tclcommand_observable_particle_currents(), tclcommand_observable_particle_forces(), tclcommand_observable_particle_positions(), tclcommand_observable_particle_velocities(), tclcommand_observable_print_formatted(), tclcommand_observable_radial_density_profile(), tclcommand_observable_radial_flux_density_profile(), tclcommand_observable_rdf(), tclcommand_observable_stress_tensor(), tclcommand_observable_stress_tensor_acf_obs(), and tclcommand_observable_tclcommand().
The documentation for this struct was generated from the following file:
statistics_observable.hpp