ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: tab.cpp File Reference
tab.cpp File Reference
Implementation of tab.hpp.
#include "tab.hpp"
#include "communication.hpp"
Functions
int tabulated_set_params (int part_type_a, int part_type_b, char *filename)
Non-Bonded tabulated potentials: Reads tabulated parameters and force and energy tables from a file.
int tabulated_bonded_set_params (int bond_type, TabulatedBondedInteraction tab_type, char *filename)
Bonded tabulated potentials: Reads tabulated parameters and force and energy tables from a file.
void check_tab_forcecap (double forcecap)
check the tabulated forcecap to see that it is sensible
Detailed Description
Implementation of tab.hpp.
Definition in file tab.cpp.
Function Documentation
void check_tab_forcecap (double force_cap)
check the tabulated forcecap to see that it is sensible
Warning
This routine will probably give strange results if forcecap is applied before the table is loaded. Needs feature TABULATED compiled in (see config.hpp).
Definition at line 199 of file tab.cpp.
References DoubleList::e, errexit(), force_cap, get_ia_param(), i, DoubleList::max, n_particle_types, params, IA_parameters::TAB_maxval, IA_parameters::TAB_npoints, IA_parameters::TAB_startindex, and tabulated_forces.
int tabulated_bonded_set_params (int bond_type, TabulatedBondedInteraction tab_type, char * filename)
Bonded tabulated potentials: Reads tabulated parameters and force and energy tables from a file.
ia_params and force/energy tables are then communicated to each node.
Parameters
bond_type bond type for which the interaction is defined
tab_type table type, TAB_BOND_LENGTH, TAB_BOND_ANGLE, TAB_BOND_DIHEDRAL
filename from which file to fetch the data
Returns
0 on success
1 if wrong bond type
2 currently unused
3 cannot open the file
4 file too short
5 file broken, cannot parse numbers
6 parameter out of bounds
Definition at line 112 of file tab.cpp.
References bonded_ia_params, BONDED_IA_TABULATED, Tabulated_bond_parameters::e, ES_OK, Tabulated_bond_parameters::f, Tabulated_bond_parameters::filename, i, Tabulated_bond_parameters::invstepsize, make_bond_type_exist(), malloc, Tabulated_bond_parameters::maxval, Tabulated_bond_parameters::minval, mpi_bcast_ia_params(), Tabulated_bond_parameters::npoints, Bonded_ia_parameters::num, Bonded_ia_parameters::p, PI, ROUND_ERROR_PREC, Bond_parameters::tab, TAB_BOND_ANGLE, TAB_BOND_DIHEDRAL, TAB_BOND_LENGTH, Tabulated_bond_parameters::type, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_tabulated_bonded().
int tabulated_set_params (int part_type_a, int part_type_b, char * filename)
Non-Bonded tabulated potentials: Reads tabulated parameters and force and energy tables from a file.
ia_params and force/energy tables are then communicated to each node
Parameters
part_type_a particle type for which the interaction is defined
part_type_b particle type for which the interaction is defined
filename from which file to fetch the data
Returns
0 on success
1 on particle type mismatches
2 file name too long
3 cannot open the file
4 file too short
5 file broken, cannot parse numbers
6 number of points of existing potential changed
Definition at line 30 of file tab.cpp.
References DoubleList::e, force_cap, get_ia_param_safe(), i, DoubleList::max, MAXLENGTH_TABFILE_NAME, mpi_bcast_ia_params(), mpi_cap_forces(), realloc_doublelist(), IA_parameters::TAB_filename, IA_parameters::TAB_maxval, IA_parameters::TAB_minval, IA_parameters::TAB_npoints, IA_parameters::TAB_startindex, IA_parameters::TAB_stepsize, tabulated_energies, and tabulated_forces.
Referenced by tclcommand_inter_parse_tab().