ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: tab_tcl.hpp File Reference
tab_tcl.hpp File Reference
#include "parser.hpp"
#include "interaction_data.hpp"
Functions
int tclcommand_inter_parse_tabulated_bonded (Tcl_Interp *interp, int bond_type, int argc, char **argv)
parse parameters for the tabulated bonded potential
int tclprint_to_result_tabulated_bondedIA (Tcl_Interp *interp, Bonded_ia_parameters *params)
int tclcommand_inter_parse_tabforcecap (Tcl_Interp *interp, int argc, char **argv)
parser for the force cap
int tclcommand_inter_parse_tab (Tcl_Interp *interp, int part_type_a, int part_type_b, int argc, char **argv)
Function Documentation
int tclcommand_inter_parse_tab (Tcl_Interp * interp, int part_type_a, int part_type_b, int argc, char ** argv)
Definition at line 89 of file tab_tcl.cpp.
References tabulated_set_params().
Referenced by tclcommand_inter_parse_non_bonded().
int tclcommand_inter_parse_tabforcecap (Tcl_Interp * interp, int argc, char ** argv)
parser for the force cap
Definition at line 79 of file tab_tcl.cpp.
References tclcommand_inter_parse_forcecap().
Referenced by tclcommand_inter_parse_rest().
int tclcommand_inter_parse_tabulated_bonded (Tcl_Interp * interp, int bond_type, int argc, char ** argv)
parse parameters for the tabulated bonded potential
Definition at line 32 of file tab_tcl.cpp.
References ARG_IS_S, TAB_BOND_ANGLE, TAB_BOND_DIHEDRAL, TAB_BOND_LENGTH, TAB_UNKNOWN, and tabulated_bonded_set_params().
Referenced by tclcommand_inter_parse_bonded().
int tclprint_to_result_tabulated_bondedIA (Tcl_Interp * interp, Bonded_ia_parameters * params)
Definition at line 136 of file tab_tcl.cpp.
References Tabulated_bond_parameters::filename, Bonded_ia_parameters::p, Bond_parameters::tab, TAB_BOND_ANGLE, TAB_BOND_DIHEDRAL, TAB_BOND_LENGTH, and Tabulated_bond_parameters::type.
Referenced by tclprint_to_result_BondedIA().