ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: TclOutputHelper.hpp File Reference
TclOutputHelper.hpp File Reference
#include "tcl.h"
#include <iostream>
#include <sstream>
#include <vector>
Functions
template<typename T >
void Tcl_Append (Tcl_Interp *interp, const T &what, bool is_in_list=0)
In this file we define a few generic functions to make returning complex c++ data easy.
void Tcl_Append (Tcl_Interp *interp, const double &what, bool is_in_list=0)
Implementation for double, using TCL_PrintDouble, to make sure TCL is happy with the float representation.
template<size_t N>
void Tcl_Append (Tcl_Interp *interp, const char(&what)[N], bool is_in_list=0)
Implementation for fixed width char arrays: Usage Tcl_Append("Message for user")
template<typename T >
void Tcl_Append (Tcl_Interp *interp, const std::vector< T > what, bool is_in_list=0)
Implementation for Eigen::Vector3d.
template<class C >
void Tcl_Append_Iterable (Tcl_Interp *interp, const C &what, bool is_in_list=0)
Generic implemtation that supports everything which can be iterated over.
Function Documentation
template<typename T > void Tcl_Append (Tcl_Interp * interp, const T & what, bool is_in_list = 0)
In this file we define a few generic functions to make returning complex c++ data easy.
The idea is as follows:
We provide a set of functions void Tcl_Append(Tcl_Interp* interp, const T& what, bool is_in_list=0) that append what to the current result stored in the TCL interpreter.
We provide a generic Tcl_Append function that uses the << operator in combination with a stringstream. Any class that has an implentation of <<(ostream) can be converted into a TCL result.
For certain data types we have special implementation: E.G. For double we use Tcl_PrintDouble, and a Vector3d from Eigen creates a list with 3 entries. std::vector<T> is converted into a TCL list etc.
The usage of lists is particularly interesting as this generic programming technique allows us also to use lists of lists, without actually changing anything. One difficulty requires using a is_in_list flag: TCL lists require having no braces {} when on "top level", but lists in lists, need braces {}. Thus a simple list of list of integers looks like: "{ 1 2 } { 3 4 }", without outer braces.
Thus we pass the flag is_in_list to every Tcl_Append call, so that inside the function is is possible to decide weather braces are necessary: If is_in_list is set, outer braces are added, if the type itself is a list. Generic implementation for types that support << (ostream)
The is_in_list flag can not be used, as we can not know if the object passed is actually a list-type object or a simple object.
Definition at line 68 of file TclOutputHelper.hpp.
Referenced by Tcl_Append_Iterable().
void Tcl_Append (Tcl_Interp * interp, const double & what, bool is_in_list = 0)
Implementation for double, using TCL_PrintDouble, to make sure TCL is happy with the float representation.
Definition at line 78 of file TclOutputHelper.hpp.
template<size_t N> void Tcl_Append (Tcl_Interp * interp, const char(&) what[N], bool is_in_list = 0)
Implementation for fixed width char arrays: Usage Tcl_Append("Message for user")
Definition at line 90 of file TclOutputHelper.hpp.
template<typename T > void Tcl_Append (Tcl_Interp * interp, const std::vector< T > what, bool is_in_list = 0)
Implementation for Eigen::Vector3d.
Appends a result that can be interpreted as TCL list. Implementation for std::vector<T>
Simply calls the generic function Tcl_Append_Iterable. This then calls Tcl_Append for every member of the vector.
Definition at line 122 of file TclOutputHelper.hpp.
References Tcl_Append_Iterable().
template<class C > void Tcl_Append_Iterable (Tcl_Interp * interp, const C & what, bool is_in_list = 0)
Generic implemtation that supports everything which can be iterated over.
This requires typedef const_iterator const_reference begin() const_reference end()
Calls the Tcl_Append for every member of the iterable object.
Definition at line 137 of file TclOutputHelper.hpp.
References Tcl_Append().
Referenced by Tcl_Append().