ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: thermostat_tcl.cpp File Reference
thermostat_tcl.cpp File Reference
#include <cmath>
#include "utils.hpp"
#include "communication.hpp"
#include "lattice.hpp"
#include "npt.hpp"
#include "ghmc.hpp"
#include "particle_data.hpp"
#include "parser.hpp"
#include "random.hpp"
#include "global.hpp"
#include "integrate.hpp"
#include "cells.hpp"
#include "lb.hpp"
#include "dpd.hpp"
#include "dpd_tcl.hpp"
#include "virtual_sites.hpp"
#include "thermostat_tcl.hpp"
Functions
int tclcommand_thermostat_parse_off (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_thermostat_parse_langevin (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_thermostat_parse_sd (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_thermostat_parse_bd (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_thermostat_parse_npt_isotropic (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_thermostat_parse_ghmc (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_thermostat_parse_cpu (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_thermostat_print_all (Tcl_Interp *interp)
int tclcommand_thermostat_print_usage (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_thermostat (ClientData data, Tcl_Interp *interp, int argc, char **argv)
Implementation of the tcl command tclcommand_thermostat.
int tclcommand_thermostat_parse_lb (Tcl_Interp *interp, int argc, char **argv)
Function Documentation
int tclcommand_thermostat (ClientData data, Tcl_Interp * interp, int argc, char ** argv)
Implementation of the tcl command tclcommand_thermostat.
This function allows to change the used thermostat and to set its parameters.
Definition at line 426 of file thermostat_tcl.cpp.
References ARG1_IS_S, err, gather_runtime_errors(), tclcommand_thermostat_parse_bd(), tclcommand_thermostat_parse_cpu(), tclcommand_thermostat_parse_dpd(), tclcommand_thermostat_parse_ghmc(), tclcommand_thermostat_parse_inter_dpd(), tclcommand_thermostat_parse_langevin(), tclcommand_thermostat_parse_lb(), tclcommand_thermostat_parse_npt_isotropic(), tclcommand_thermostat_parse_off(), tclcommand_thermostat_parse_sd(), tclcommand_thermostat_print_all(), tclcommand_thermostat_print_usage(), THERMO_TRACE, and this_node.
Referenced by tcl_register_commands().
int tclcommand_thermostat_parse_bd (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 147 of file thermostat_tcl.cpp.
References ARG_IS_D, FIELD_TEMPERATURE, FIELD_THERMO_SWITCH, mpi_bcast_parameter(), temperature, THERMO_BD, and thermo_switch.
Referenced by tclcommand_thermostat().
int tclcommand_thermostat_parse_cpu (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 274 of file thermostat_tcl.cpp.
References ARG_IS_I, FIELD_TEMPERATURE, FIELD_THERMO_SWITCH, mpi_bcast_parameter(), temperature, THERMO_CPU, and thermo_switch.
Referenced by tclcommand_thermostat().
int tclcommand_thermostat_parse_ghmc (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 206 of file thermostat_tcl.cpp.
References ARG_IS_D, ARG_IS_I, ARG_IS_S, FIELD_GHMC_FLIP, FIELD_GHMC_NMD, FIELD_GHMC_PHI, FIELD_GHMC_SCALE, FIELD_TEMPERATURE, FIELD_THERMO_SWITCH, ghmc_mflip, GHMC_MFLIP_OFF, GHMC_MFLIP_ON, GHMC_MFLIP_RAND, ghmc_nmd, ghmc_phi, ghmc_tscale, GHMC_TSCALE_OFF, GHMC_TSCALE_ON, mpi_bcast_parameter(), temperature, THERMO_GHMC, and thermo_switch.
Referenced by tclcommand_thermostat().
int tclcommand_thermostat_parse_langevin (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 84 of file thermostat_tcl.cpp.
References ARG_IS_D, FIELD_LANGEVIN_GAMMA, FIELD_TEMPERATURE, FIELD_THERMO_SWITCH, langevin_gamma, mpi_bcast_parameter(), temperature, THERMO_LANGEVIN, and thermo_switch.
Referenced by tclcommand_thermostat().
int tclcommand_thermostat_parse_lb (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 484 of file thermostat_tcl.cpp.
References ARG_IS_D, FIELD_TEMPERATURE, FIELD_THERMO_SWITCH, mpi_bcast_parameter(), temperature, THERMO_LB, and thermo_switch.
Referenced by tclcommand_thermostat().
int tclcommand_thermostat_parse_npt_isotropic (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 177 of file thermostat_tcl.cpp.
References ARG_IS_D, FIELD_NPTISO_G0, FIELD_NPTISO_GV, FIELD_TEMPERATURE, FIELD_THERMO_SWITCH, mpi_bcast_parameter(), nptiso_gamma0, nptiso_gammav, temperature, THERMO_NPT_ISO, and thermo_switch.
Referenced by tclcommand_thermostat().
int tclcommand_thermostat_parse_off (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 45 of file thermostat_tcl.cpp.
References dpd_switch_off(), FIELD_GHMC_FLIP, FIELD_GHMC_NMD, FIELD_GHMC_PHI, FIELD_GHMC_SCALE, FIELD_LANGEVIN_GAMMA, FIELD_NPTISO_G0, FIELD_NPTISO_GV, FIELD_TEMPERATURE, FIELD_THERMO_SWITCH, ghmc_mflip, GHMC_MFLIP_OFF, ghmc_nmd, ghmc_phi, ghmc_tscale, GHMC_TSCALE_OFF, inter_dpd_switch_off(), langevin_gamma, mpi_bcast_parameter(), nptiso_gamma0, nptiso_gammav, temperature, THERMO_OFF, and thermo_switch.
Referenced by tclcommand_thermostat().
int tclcommand_thermostat_parse_sd (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 116 of file thermostat_tcl.cpp.
References ARG_IS_D, FIELD_TEMPERATURE, FIELD_THERMO_SWITCH, mpi_bcast_parameter(), temperature, THERMO_SD, and thermo_switch.
Referenced by tclcommand_thermostat().
int tclcommand_thermostat_print_all (Tcl_Interp * interp)
Definition at line 304 of file thermostat_tcl.cpp.
References ghmc_mflip, GHMC_MFLIP_OFF, GHMC_MFLIP_ON, GHMC_MFLIP_RAND, ghmc_nmd, ghmc_phi, ghmc_tscale, GHMC_TSCALE_ON, langevin_gamma, nptiso_gamma0, nptiso_gammav, tclcommand_thermostat_parse_and_print_dpd(), temperature, THERMO_BD, THERMO_DPD, THERMO_GHMC, THERMO_INTER_DPD, THERMO_LANGEVIN, THERMO_LB, THERMO_NPT_ISO, THERMO_OFF, THERMO_SD, and thermo_switch.
Referenced by tclcommand_thermostat().
int tclcommand_thermostat_print_usage (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 401 of file thermostat_tcl.cpp.
References tclcommand_thermostat_print_usage_dpd().
Referenced by tclcommand_thermostat().