ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: topology_tcl.hpp File Reference
topology_tcl.hpp File Reference
#include "tcl.h"
Functions
int tclcommand_analyze_set_parse_topo_part_sync (Tcl_Interp *interp)
Function Documentation
int tclcommand_analyze_set_parse_topo_part_sync (Tcl_Interp * interp)
Definition at line 79 of file topology_tcl.cpp.
References i, mpi_sync_topo_part_info(), IntList::n, n_molecules, n_part, Molecule::part, and topology.
Referenced by tclcommand_analyze_parse_generic_structure(), tclcommand_analyze_parse_set(), tclcommand_analyze_set_parse_chain_topology(), and tclcommand_analyze_set_parse_trapmol().