ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: topology_tcl.cpp File Reference
topology_tcl.cpp File Reference
#include "parser.hpp"
#include "topology.hpp"
#include "statistics_chain_tcl.hpp"
#include "particle_data.hpp"
#include "communication.hpp"
#include "tcl/topology_tcl.hpp"
Functions
int tclcommand_analyze_set_print_all (Tcl_Interp *interp)
int tclcommand_analyze_parse_generic_structure (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze_set_parse_topo_part_sync (Tcl_Interp *interp)
int tclcommand_analyze_set_parse_trapmol (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze_parse_set (Tcl_Interp *interp, int argc, char **argv)
Set the topology.
Function Documentation
int tclcommand_analyze_parse_generic_structure (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 55 of file topology_tcl.cpp.
References ARG_IS_INTLIST, IntList::e, init_intlist(), IntList::n, realloc_intlist(), realloc_topology(), tclcommand_analyze_set_parse_topo_part_sync(), topology, and Molecule::type.
Referenced by tclcommand_analyze_parse_set().
int tclcommand_analyze_parse_set (Tcl_Interp * interp, int argc, char ** argv)
Set the topology.
See topology_tcl.cpp
Definition at line 247 of file topology_tcl.cpp.
References ARG0_IS_S, tclcommand_analyze_parse_generic_structure(), tclcommand_analyze_set_parse_chain_topology(), tclcommand_analyze_set_parse_topo_part_sync(), tclcommand_analyze_set_parse_trapmol(), and tclcommand_analyze_set_print_all().
Referenced by tclcommand_analyze().
int tclcommand_analyze_set_parse_topo_part_sync (Tcl_Interp * interp)
Definition at line 79 of file topology_tcl.cpp.
References i, mpi_sync_topo_part_info(), IntList::n, n_molecules, n_part, Molecule::part, and topology.
Referenced by tclcommand_analyze_parse_generic_structure(), tclcommand_analyze_parse_set(), tclcommand_analyze_set_parse_chain_topology(), and tclcommand_analyze_set_parse_trapmol().
int tclcommand_analyze_set_parse_trapmol (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 111 of file topology_tcl.cpp.
References alloc_intlist(), ARG0_IS_D, ARG0_IS_DOUBLELIST, ARG0_IS_I, ARG0_IS_S, ARG_IS_INTLIST, COORD_FIXED, IntList::e, i, init_doublelist(), init_intlist(), n_molecules, realloc_doublelist(), realloc_intlist(), set_molecule_trap(), tclcommand_analyze_set_parse_topo_part_sync(), and usage().
Referenced by tclcommand_analyze_parse_set().
int tclcommand_analyze_set_print_all (Tcl_Interp * interp)
Definition at line 39 of file topology_tcl.cpp.
References i, IntList::n, n_molecules, Molecule::part, and topology.
Referenced by tclcommand_analyze_parse_set().