ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: tunable_slip.hpp File Reference
tunable_slip.hpp File Reference
Routines to generate tunable-slip boundary conditions.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
Functions
int tunable_slip_set_params (int part_type_a, int part_type_b, double temp, double gamma, double r_cut, double time, double vx, double vy, double vz)
void add_tunable_slip_pair_force (Particle *p1, Particle *p2, IA_parameters *ia_params, double d[3], double dist, double force[3])
Detailed Description
Routines to generate tunable-slip boundary conditions.
J.Smiatek, M.P. Allen, F. Schmid: "Tunable-slip boundaries for coarse-grained simulations of fluid flow", Europ. Phys. J. E 26, 115 (2008)
Definition in file tunable_slip.hpp.
Function Documentation
void add_tunable_slip_pair_force (Particle * p1, Particle * p2, IA_parameters * ia_params, double d[3], double dist, double force[3])
Definition at line 51 of file tunable_slip.cpp.
References check_id, d_random(), ParticleForce::f, Particle::f, ParticleProperties::identity, Particle::m, ONEPART_TRACE, Particle::p, this_node, IA_parameters::TUNABLE_SLIP_gamma, IA_parameters::TUNABLE_SLIP_r_cut, IA_parameters::TUNABLE_SLIP_temp, IA_parameters::TUNABLE_SLIP_time, IA_parameters::TUNABLE_SLIP_vx, IA_parameters::TUNABLE_SLIP_vy, IA_parameters::TUNABLE_SLIP_vz, and ParticleMomentum::v.
Referenced by add_constraints_forces().
int tunable_slip_set_params (int part_type_a, int part_type_b, double temp, double gamma, double r_cut, double time, double vx, double vy, double vz)
Definition at line 27 of file tunable_slip.cpp.
References ES_ERROR, ES_OK, get_ia_param_safe(), mpi_bcast_ia_params(), IA_parameters::TUNABLE_SLIP_gamma, IA_parameters::TUNABLE_SLIP_r_cut, IA_parameters::TUNABLE_SLIP_temp, IA_parameters::TUNABLE_SLIP_time, IA_parameters::TUNABLE_SLIP_vx, IA_parameters::TUNABLE_SLIP_vy, and IA_parameters::TUNABLE_SLIP_vz.
Referenced by tclcommand_inter_parse_tunable_slip().