ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: tuning.cpp File Reference
tuning.cpp File Reference
Implementation of tuning.hpp .
#include <sys/time.h>
#include <sys/resource.h>
#include "utils.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
Functions
void markTime ()
set a time marker.
double diffTime ()
calculate milliseconds between last two calls to markTime.
double time_force_calc (int default_samples)
returns the time for some force calculations.
Variables
int timing_samples = 0
if positive, the number of samples for timing
static struct rusage time1 time2
Detailed Description
Implementation of tuning.hpp .
Definition in file tuning.cpp.
Function Documentation
double diffTime ()
calculate milliseconds between last two calls to markTime.
Definition at line 41 of file tuning.cpp.
References time2.
Referenced by time_force_calc().
void markTime ()
set a time marker.
diffTime always gives the time in ms between the last two calls to markTime.
Definition at line 35 of file tuning.cpp.
References time2.
Referenced by time_force_calc().
double time_force_calc (int default_samples)
returns the time for some force calculations.
Actually performs mpi_integrate (0)
Parameters
default_samples the number of samples to take if timing_samples is not set.
Definition at line 47 of file tuning.cpp.
References diffTime(), i, markTime(), mpi_integrate(), and timing_samples.
Referenced by EwaldgpuForce::adaptive_tune(), mmm1d_tune(), and tclcommand_time_integration().
Variable Documentation
struct rusage time1 time2 static
Definition at line 33 of file tuning.cpp.
Referenced by calculate_hollow_cone_dist(), diffTime(), and markTime().
int timing_samples = 0
if positive, the number of samples for timing
Definition at line 30 of file tuning.cpp.
Referenced by tclcallback_timings(), and time_force_calc().