ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: tuning_tcl.cpp File Reference
tuning_tcl.cpp File Reference
Implements the callback for the timings global variable used during tuning of e.g.
#include "parser.hpp"
#include "tuning.hpp"
Functions
int tclcallback_timings (Tcl_Interp *interp, void *data)
callback for timing_samples.
int tclcommand_time_integration (ClientData data, Tcl_Interp *interp, int argc, char *argv[])
Returns runtime of the integration loop in seconds.
Detailed Description
Implements the callback for the timings global variable used during tuning of e.g.
P3M or mmm1d.
Definition in file tuning_tcl.cpp.
Function Documentation
int tclcallback_timings (Tcl_Interp * interp, void * data)
callback for timing_samples.
See tuning_tcl.cpp
Definition at line 29 of file tuning_tcl.cpp.
References timing_samples.
Referenced by tcl_register_global_variables().
int tclcommand_time_integration (ClientData data, Tcl_Interp * interp, int argc, char * argv[])
Returns runtime of the integration loop in seconds.
From tuning_tcl.cpp
Definition at line 38 of file tuning_tcl.cpp.
References ARG1_IS_I, and time_force_calc().
Referenced by tcl_register_commands().