ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: twist_stack.cpp File Reference
twist_stack.cpp File Reference
#include "twist_stack.hpp"
#include "communication.hpp"
Macros
#define COS_MAX (0.99999999)
#define COS_MIN (-0.99999999)
#define SQR(x) ((x)*(x))
#define PV(A)
#define PS(A)
Functions
double dot (double *x1, double *x2)
void cross (double *x1, double *x2, double *x3)
double norm2 (double *x)
double norm (double *x)
void normalize (double *x)
double cos_angle (double *x1, double *x2)
double angle (double *x1, double *x2)
int calc_twist_stack_energy (Particle *si1, Particle *bi1, Particle *bi2, Particle *si2, Particle *sj1, Particle *bj1, Particle *bj2, Particle *sj2, Bonded_ia_parameters *iaparams, double *_energy)
int calc_twist_stack_force (Particle *si1, Particle *bi1, Particle *bi2, Particle *si2, Particle *sj1, Particle *bj1, Particle *bj2, Particle *sj2, Bonded_ia_parameters *iaparams, double f_si1[3], double f_bi1[3], double f_bi2[3], double f_si2[3], double f_sj1[3], double f_bj1[3], double f_bj2[3], double f_sj2[3])
int twist_stack_set_params (int bond_type, DoubleList *params)
Macro Definition Documentation
#define COS_MAX (0.99999999)
Definition at line 28 of file twist_stack.cpp.
Referenced by calc_twist_stack_energy(), and calc_twist_stack_force().
#define COS_MIN (-0.99999999)
Definition at line 29 of file twist_stack.cpp.
Referenced by calc_twist_stack_energy(), and calc_twist_stack_force().
#define PS (A)
Definition at line 81 of file twist_stack.cpp.
Referenced by calc_twist_stack_force().
#define PV (A)
Definition at line 80 of file twist_stack.cpp.
Referenced by calc_twist_stack_force().
#define SQR (x) ((x)*(x))
Definition at line 31 of file twist_stack.cpp.
Referenced by calc_twist_stack_energy(), calc_twist_stack_force(), and norm2().
Function Documentation
double angle (double * x1, double * x2) inline
Definition at line 70 of file twist_stack.cpp.
References cos_angle().
int calc_twist_stack_energy (Particle * si1, Particle * bi1, Particle * bi2, Particle * si2, Particle * sj1, Particle * bj1, Particle * bj2, Particle * sj2, Bonded_ia_parameters * iaparams, double * _energy)
Definition at line 84 of file twist_stack.cpp.
References Cg_dna_stacking_parameters::a, Cg_dna_stacking_parameters::b, COS_MAX, COS_MIN, cross(), dot(), Cg_dna_stacking_parameters::epsilon, get_mi_vector(), i, norm(), ParticlePosition::p, Bonded_ia_parameters::p, Particle::r, Cg_dna_stacking_parameters::ref_pot, Cg_dna_stacking_parameters::rm, SQR, and Bond_parameters::twist_stack.
Referenced by add_bonded_energy().
int calc_twist_stack_force (Particle * si1, Particle * bi1, Particle * bi2, Particle * si2, Particle * sj1, Particle * bj1, Particle * bj2, Particle * sj2, Bonded_ia_parameters * iaparams, double f_si1[3], double f_bi1[3], double f_bi2[3], double f_si2[3], double f_sj1[3], double f_bj1[3], double f_bj2[3], double f_sj2[3])
Definition at line 243 of file twist_stack.cpp.
References Cg_dna_stacking_parameters::a, Cg_dna_stacking_parameters::b, COS_MAX, COS_MIN, cross(), dot(), Cg_dna_stacking_parameters::epsilon, get_mi_vector(), i, ParticleProperties::identity, norm(), ParticlePosition::p, Particle::p, Bonded_ia_parameters::p, PS, PV, Particle::r, Cg_dna_stacking_parameters::ref_pot, Cg_dna_stacking_parameters::rm, sim_time, SQR, time_step, and Bond_parameters::twist_stack.
Referenced by add_bonded_force().
double cos_angle (double * x1, double * x2) inline
Definition at line 66 of file twist_stack.cpp.
References dot(), and norm().
Referenced by angle().
void cross (double * x1, double * x2, double * x3) inline
Definition at line 42 of file twist_stack.cpp.
Referenced by calc_twist_stack_energy(), and calc_twist_stack_force().
double dot (double * x1, double * x2) inline
Definition at line 36 of file twist_stack.cpp.
Referenced by calc_twist_stack_energy(), calc_twist_stack_force(), and cos_angle().
double norm (double * x) inline
Definition at line 53 of file twist_stack.cpp.
References norm2().
Referenced by calc_twist_stack_energy(), calc_twist_stack_force(), cos_angle(), and normalize().
double norm2 (double * x) inline
Definition at line 49 of file twist_stack.cpp.
References SQR.
Referenced by norm().
void normalize (double * x) inline
Definition at line 57 of file twist_stack.cpp.
References norm().
int twist_stack_set_params (int bond_type, DoubleList * params)
Definition at line 643 of file twist_stack.cpp.
References Cg_dna_stacking_parameters::a, Cg_dna_stacking_parameters::b, BONDED_IA_CG_DNA_STACKING, bonded_ia_params, DoubleList::e, Cg_dna_stacking_parameters::epsilon, ES_ERROR, ES_OK, i, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, PI, Cg_dna_stacking_parameters::ref_pot, Cg_dna_stacking_parameters::rm, Bond_parameters::twist_stack, and Bonded_ia_parameters::type.
Referenced by tclcommand_inter_parse_twist_stack().