ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: umbrella.hpp File Reference
umbrella.hpp File Reference
Routines to calculate the umbrella energy and/or force for a particle pair: harmonic interaction in only one cartesian direction.
#include "utils.hpp"
#include "interaction_data.hpp"
#include "particle_data.hpp"
Functions
int umbrella_set_params (int bond_type, double k, int dir, double r)
double umbrella_force_r (double k, int dir, double r, double distn)
Resultant Force due to an umbrella potential.
int calc_umbrella_pair_force (Particle *p1, Particle *p2, Bonded_ia_parameters *ia_params, double d[3], double force[3])
Calculate umbrella potential force between particle p1 and p2.
int umbrella_pair_energy (Particle *p1, Particle *p2, Bonded_ia_parameters *ia_params, double d[3], double *_energy)
calculate umbrella energy between particle p1 and p2.
Detailed Description
Routines to calculate the umbrella energy and/or force for a particle pair: harmonic interaction in only one cartesian direction.
Useful for umbrella sampling simulations. forces.cpp
Definition in file umbrella.hpp.
Function Documentation
int calc_umbrella_pair_force (Particle * p1, Particle * p2, Bonded_ia_parameters * ia_params, double d[3], double force[3]) inline
Calculate umbrella potential force between particle p1 and p2.
Definition at line 49 of file umbrella.hpp.
References check_id, Umbrella_bond_parameters::dir, ParticleForce::f, Particle::f, ParticleProperties::identity, Umbrella_bond_parameters::k, ONEPART_TRACE, Particle::p, Bonded_ia_parameters::p, Umbrella_bond_parameters::r, this_node, and Bond_parameters::umbrella.
double umbrella_force_r (double k, int dir, double r, double distn) inline
Resultant Force due to an umbrella potential.
Definition at line 43 of file umbrella.hpp.
int umbrella_pair_energy (Particle * p1, Particle * p2, Bonded_ia_parameters * ia_params, double d[3], double * _energy) inline
calculate umbrella energy between particle p1 and p2.
Definition at line 66 of file umbrella.hpp.
References Umbrella_bond_parameters::dir, Umbrella_bond_parameters::k, Bonded_ia_parameters::p, Umbrella_bond_parameters::r, SQR(), and Bond_parameters::umbrella.
int umbrella_set_params (int bond_type, double k, int dir, double r)
Definition at line 30 of file umbrella.cpp.
References bonded_ia_params, BONDED_IA_UMBRELLA, Umbrella_bond_parameters::dir, ES_ERROR, ES_OK, Umbrella_bond_parameters::k, make_bond_type_exist(), mpi_bcast_ia_params(), Bonded_ia_parameters::num, Bonded_ia_parameters::p, Umbrella_bond_parameters::r, Bonded_ia_parameters::type, and Bond_parameters::umbrella.
Referenced by tclcommand_inter_parse_umbrella().