ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: uwerr_tcl.cpp File Reference
uwerr_tcl.cpp File Reference
Implements the uwerr command.
#include <cstdlib>
#include <cstring>
#include <cmath>
#include "uwerr.hpp"
#include "config.hpp"
#include <tcl.h>
Macros
#define UW_EPS 2.2204e-16
This is eps from matlab.
Functions
int uwerr_read_tcl_double_vector (Tcl_Interp *interp, char *data_in, double **nrep, int *len)
Reads a Tcl vector and returns a C vector.
int uwerr_create_tcl_vector (char **out, int in_len)
Create a string with enough space for in_len doubles.
int uwerr_write_tcl_vector (Tcl_Interp *interp, double *in, int in_len, char *out)
Write a vector of doubles as string.
int uwerr_free_tcl_vector (char *vec)
Free the resources for the given string.
int UWerr_proj (ClientData cd, Tcl_Interp *interp, int argc, char *argv[])
Projection of a vector to one entry.
int UWerr_f (Tcl_Interp *interp, Tcl_CmdInfo *cmdInfo, int argc, char **argv, double **data, int rows, int cols, int *n_rep, int len, double s_tau, int plot)
The main function.
int UWerr (Tcl_Interp *interp, double **data, int rows, int cols, int col_to_analyze, int *n_rep, int len, double s_tau, int plot)
The function for analyzing a column only.
int uwerr_read_matrix (Tcl_Interp *interp, char *data_in, double ***data, int *nrows, int *ncols)
Reads a Tcl matrix and returns a C matrix.
int uwerr_read_int_vector (Tcl_Interp *interp, char *data_in, int **nrep, int *len)
Reads a Tcl vector and returns a C vector.
int tclcommand_uwerr (ClientData cd, Tcl_Interp *interp, int argc, char *argv[])
The C implementation of the tcl function uwerr.
Detailed Description
Implements the uwerr command.
Definition in file uwerr_tcl.cpp.
Macro Definition Documentation
#define UW_EPS 2.2204e-16
This is eps from matlab.
Definition at line 34 of file uwerr_tcl.cpp.
Referenced by UWerr_f().
Function Documentation
int tclcommand_uwerr (ClientData data, Tcl_Interp * interp, int argc, char * argv[])
The C implementation of the tcl function uwerr.
See uwerr_tcl.cpp
Definition at line 786 of file uwerr_tcl.cpp.
References free, i, malloc, UWerr(), UWerr_f(), uwerr_read_int_vector(), and uwerr_read_matrix().
Referenced by tcl_register_commands().
int UWerr (Tcl_Interp * interp, double ** data, int rows, int cols, int col_to_analyze, int * n_rep, int len, double s_tau, int plot)
The function for analyzing a column only.
Definition at line 559 of file uwerr_tcl.cpp.
References free, malloc, UWerr_f(), and UWerr_proj().
Referenced by tclcommand_uwerr().
int uwerr_create_tcl_vector (char ** out, int in_len)
Create a string with enough space for in_len doubles.
Definition at line 54 of file uwerr_tcl.cpp.
References malloc.
Referenced by UWerr_f().
int UWerr_f (Tcl_Interp * interp, Tcl_CmdInfo * cmdInfo, int argc, char ** argv, double ** data, int rows, int cols, int * n_rep, int len, double s_tau, int plot)
The main function.
The function implementing the algorithm described in
arXiv:hep-lat/0306017 v1 13 Jun 2003 Wolff, U. Monte Carlo errors with less errors.
Definition at line 145 of file uwerr_tcl.cpp.
References free, gammaq(), i, malloc, UW_EPS, uwerr_create_tcl_vector(), UWerr_dsum_double(), UWerr_dsum_int(), uwerr_free_tcl_vector(), UWerr_sum(), and uwerr_write_tcl_vector().
Referenced by tclcommand_uwerr(), and UWerr().
int uwerr_free_tcl_vector (char * vec)
Free the resources for the given string.
Definition at line 90 of file uwerr_tcl.cpp.
References free.
Referenced by UWerr_f().
int UWerr_proj (ClientData cd, Tcl_Interp * interp, int argc, char * argv[])
Projection of a vector to one entry.
This function is a replacement for a tcl function like
proc proj {vec n} { return [lindex $vec $n] }
Therefor argc has to be 3 and argv has to consist of
a name of the function (e.g. in UWerr)
the vector as Tcl list
the coordinate to project to
Definition at line 108 of file uwerr_tcl.cpp.
References free, and uwerr_read_tcl_double_vector().
Referenced by UWerr().
int uwerr_read_int_vector (Tcl_Interp * interp, char * data_in, int ** nrep, int * len)
Reads a Tcl vector and returns a C vector.
Parameters
interp The Tcl interpreter
data_in String containing a Tcl vector of integers
nrep Pointer to the C vector
len Pointer to an int to store the length of the vector
Returns
TCL_OK if everything went fine TCL_ERROR otherwise and interp->result is set to an error message.
If TCL_OK is returned you have to make sure to free the memory pointed to by nrep.
Definition at line 701 of file uwerr_tcl.cpp.
References free, i, and malloc.
Referenced by tclcommand_uwerr().
int uwerr_read_matrix (Tcl_Interp * interp, char * data_in, double *** data, int * nrows, int * ncols)
Reads a Tcl matrix and returns a C matrix.
Parameters
interp The Tcl interpreter
data_in String containing a Tcl matrix of doubles
data Pointer to the C matrix
nrows Pointer to an int to store the height of the matrix
ncols Pointer to an int to store the width of the matrix
Returns
TCL_OK if everything went fine TCL_ERROR otherwise and interp->result is set to an error message.
If TCL_OK is returned you have to make sure to free the memory pointed to by data.
Definition at line 607 of file uwerr_tcl.cpp.
References free, i, and malloc.
Referenced by tclcommand_uwerr().
int uwerr_read_tcl_double_vector (Tcl_Interp * interp, char * data_in, double ** nrep, int * len)
Reads a Tcl vector and returns a C vector.
Parameters
interp The Tcl interpreter
data_in String containing a Tcl vector of doubles
nrep Pointer to the C vector
len Pointer to an int to store the length of the vector
Returns
TCL_OK if everything went fine TCL_ERROR otherwise and interp->result is set to an error message.
If TCL_OK is returned you have to make sure to free the memory pointed to by nrep.
Definition at line 750 of file uwerr_tcl.cpp.
References free, i, and malloc.
Referenced by UWerr_proj().
int uwerr_write_tcl_vector (Tcl_Interp * interp, double * in, int in_len, char * out)
Write a vector of doubles as string.
Definition at line 65 of file uwerr_tcl.cpp.
References i.
Referenced by UWerr_f().