ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: uwerr.hpp File Reference
uwerr.hpp File Reference
Functions
double UWerr_dsum_double (double *v, double *w, int len)
Sum up the product of two vectors.
double UWerr_dsum_int (int *v, double *w, int len)
Sum up the product of two vectors.
double UWerr_sum (double *v, int len)
Sum up a vector.
double gammaq (double a, double x)
The incomplete Gammafunction.
Function Documentation
double gammaq (double a, double x)
The incomplete Gammafunction.
This is the implementation of the incomplete Gammafunction as described in Nummerical Recepies in C++ The Art of Scientific Computing Second Edition.
The incomplete Gammafunction is defined as
Definition at line 155 of file uwerr.cpp.
References gammacf(), and gammaser().
Referenced by UWerr_f().
double UWerr_dsum_double (double * v, double * w, int len)
Sum up the product of two vectors.
Parameters
v A pointer to the first vector.
w A pointer to the second vector.
len The length of the shortest vector.
Returns
The sum of the products of vector elements.
Definition at line 200 of file uwerr.cpp.
References i.
Referenced by UWerr_f().
double UWerr_dsum_int (int * v, double * w, int len)
Sum up the product of two vectors.
Parameters
v A pointer to the first vector.
w A pointer to the second vector.
len The length of the shortest vector.
Returns
The sum of the products of vector elements.
Definition at line 221 of file uwerr.cpp.
References i.
Referenced by UWerr_f().
double UWerr_sum (double * v, int len)
Sum up a vector.
Parameters
v A pointer to the vector.
len The length of the vector.
Returns
The sum of all vector elements.
Definition at line 179 of file uwerr.cpp.
References i.
Referenced by UWerr_f().