ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: verlet.hpp File Reference
verlet.hpp File Reference
This file contains routines to setup and handle interaction pair lists (verlet pair lists) for the non bonded interactions.
#include "particle_data.hpp"
Data Structures
struct PairList
Verlet pair list.
Functions
Exported Functions
void init_pairList (PairList *list)
Initialize a Pair List.
void free_pairList (PairList *list)
Free a Pair List .
void build_verlet_lists ()
Fill verlet tables.
void calculate_verlet_ia ()
Nonbonded and bonded force calculation using the verlet list.
void build_verlet_lists_and_calc_verlet_ia ()
Fill verlet tables and Calculate nonbonded and bonded forces.
void calculate_verlet_energies ()
Nonbonded and bonded energy calculation using the verlet list.
void calculate_verlet_virials (int v_comp)
Nonbonded and bonded pressure calculation using the verlet list.
Detailed Description
This file contains routines to setup and handle interaction pair lists (verlet pair lists) for the non bonded interactions.
For the non-bonded interactions, the domain decomposition force calculation uses verlet pair lists which contain all particle pairs with a distance smaller than their maximal interaction range, based on their types, plus the skin. This allows one to use these verlet pair lists for several time steps, as long no particle has moved further than skin / 2.0. You can tune the verlet pair algorithm with the variable skin which you can set via the tclcommand_setmd command. You can also acces the average number of integration steps the verlet lists have been reused with tclcommand_setmd verlet_reuse.
The verlet algorithm uses the data type PairList to store interacting particle pairs.
To use verlet pair lists for the force calculation you can either use the functions build_verlet_lists and calculate_verlet_ia or a combination of those two build_verlet_lists_and_calc_verlet_ia.
For energy and pressure calculations using verlet pair lists use calculate_verlet_energies and calculate_verlet_virials.
For more information see verlet.c.
Definition in file verlet.hpp.
Function Documentation
void build_verlet_lists ()
Fill verlet tables.
Definition at line 95 of file verlet.cpp.
References add_pair(), box_l, CellPList::cell, DomainDecomposition::cell_inter, dd, distance2(), do_nonbonded(), errexit(), get_ia_param(), i, local_cells, IA_parameters::max_cut, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, n_nodes, n_part, neighbor, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, ParticleList::part, PI, IA_Neighbor::pList, Particle::r, rebuild_verletlist, resize_verlet_list(), skin, SQR(), this_node, ParticleProperties::type, DomainDecomposition::use_vList, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by aggregation(), energy_calc(), and pressure_calc().
void build_verlet_lists_and_calc_verlet_ia ()
Fill verlet tables and Calculate nonbonded and bonded forces.
This is a combination of build_verlet_lists and calculate_verlet_ia.
Definition at line 213 of file verlet.cpp.
References add_bonded_force(), add_constraints_forces(), add_external_potential_forces(), add_non_bonded_pair_force(), add_pair(), box_l, CellPList::cell, DomainDecomposition::cell_inter, check_id, current_time_step_is_small, dd, distance2vec(), do_nonbonded(), errexit(), get_ia_param(), i, ParticleProperties::identity, local_cells, IA_parameters::max_cut, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, n_nodes, n_part, neighbor, IA_Neighbor_List::nList, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticleList::part, PI, IA_Neighbor::pList, Particle::r, rebuild_verletlist, resize_verlet_list(), skin, smaller_time_step, ParticleProperties::smaller_timestep, SQR(), this_node, ParticleProperties::type, DomainDecomposition::use_vList, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by force_calc().
void calculate_verlet_energies ()
Nonbonded and bonded energy calculation using the verlet list.
Definition at line 313 of file verlet.cpp.
References add_bonded_energy(), add_constraints_energy(), add_external_potential_energy(), add_kinetic_energy(), add_non_bonded_pair_energy(), CellPList::cell, DomainDecomposition::cell_inter, dd, distance2vec(), i, ParticleProperties::identity, local_cells, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, PairList::pair, ParticleList::part, Particle::r, this_node, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by energy_calc().
void calculate_verlet_ia ()
Nonbonded and bonded force calculation using the verlet list.
Definition at line 165 of file verlet.cpp.
References add_bonded_force(), add_constraints_forces(), add_external_potential_forces(), add_non_bonded_pair_force(), CellPList::cell, DomainDecomposition::cell_inter, current_time_step_is_small, dd, distance2vec(), i, local_cells, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, PairList::pair, ParticleList::part, Particle::r, smaller_time_step, ParticleProperties::smaller_timestep, and IA_Neighbor::vList.
Referenced by force_calc().
void calculate_verlet_virials (int v_comp)
Nonbonded and bonded pressure calculation using the verlet list.
Parameters
v_comp flag which enables (1) compensation of the velocities required for deriving a pressure reflecting nptiso_struct::p_inst; naturally it doesn't make sense to use it without NpT.
Definition at line 362 of file verlet.cpp.
References add_bonded_virials(), add_kinetic_virials(), add_non_bonded_pair_virials(), add_three_body_bonded_stress(), CellPList::cell, DomainDecomposition::cell_inter, dd, distance2vec(), i, local_cells, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, PairList::pair, ParticleList::part, Particle::r, this_node, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by pressure_calc().
void free_pairList (PairList * list)
Free a Pair List .
Definition at line 88 of file verlet.cpp.
References PairList::max, PairList::n, PairList::pair, and realloc.
Referenced by dd_topology_release().
void init_pairList (PairList * list)
Initialize a Pair List.
Use with care and ONLY for initialization!
Definition at line 81 of file verlet.cpp.
References PairList::max, PairList::n, and PairList::pair.
Referenced by dd_init_cell_interactions(), and le_dd_init_cell_interactions().