ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: verlet.cpp File Reference
verlet.cpp File Reference
Verlet list.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "utils.hpp"
#include "verlet.hpp"
#include "cells.hpp"
#include "integrate.hpp"
#include "particle_data.hpp"
#include "interaction_data.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "forces.hpp"
#include "energy_inline.hpp"
#include "pressure.hpp"
#include "domain_decomposition.hpp"
#include "constraint.hpp"
#include "external_potential.hpp"
Macros
#define LIST_INCREMENT 20
Granularity of the verlet list.
Functions
void init_pairList (PairList *list)
Initialize a Pair List.
void free_pairList (PairList *list)
Free a Pair List .
void build_verlet_lists ()
Fill verlet tables.
void calculate_verlet_ia ()
Nonbonded and bonded force calculation using the verlet list.
void build_verlet_lists_and_calc_verlet_ia ()
Fill verlet tables and Calculate nonbonded and bonded forces.
void calculate_verlet_energies ()
Nonbonded and bonded energy calculation using the verlet list.
void calculate_verlet_virials (int v_comp)
Nonbonded and bonded pressure calculation using the verlet list.
Privat Functions
void add_pair (PairList *pl, Particle *p1, Particle *p2)
Add a particle pair to a verlet pair list.
void resize_verlet_list (PairList *pl)
Resizes a verlet pair list according to the actual content (*vl).n.
Detailed Description
Verlet list.
For more information see verlet.h
Definition in file verlet.cpp.
Macro Definition Documentation
#define LIST_INCREMENT 20
Granularity of the verlet list.
Definition at line 43 of file verlet.cpp.
Referenced by add_pair(), and resize_verlet_list().
Function Documentation
void add_pair (PairList * pl, Particle * p1, Particle * p2) inline
Add a particle pair to a verlet pair list.
Checks verlet pair list size and reallocates memory if necessary.
Parameters
p1 Pointer to particle one.
p2 Pointer to particle two.
pl Pointer to the verlet pair list.
Definition at line 59 of file verlet.cpp.
References LIST_INCREMENT, PairList::max, PairList::n, PairList::pair, and realloc.
Referenced by build_verlet_lists(), and build_verlet_lists_and_calc_verlet_ia().
void build_verlet_lists ()
Fill verlet tables.
Definition at line 95 of file verlet.cpp.
References add_pair(), box_l, CellPList::cell, DomainDecomposition::cell_inter, dd, distance2(), do_nonbonded(), errexit(), get_ia_param(), i, local_cells, IA_parameters::max_cut, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, n_nodes, n_part, neighbor, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, ParticleList::part, PI, IA_Neighbor::pList, Particle::r, rebuild_verletlist, resize_verlet_list(), skin, SQR(), this_node, ParticleProperties::type, DomainDecomposition::use_vList, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by aggregation(), energy_calc(), and pressure_calc().
void build_verlet_lists_and_calc_verlet_ia ()
Fill verlet tables and Calculate nonbonded and bonded forces.
This is a combination of build_verlet_lists and calculate_verlet_ia.
Definition at line 213 of file verlet.cpp.
References add_bonded_force(), add_constraints_forces(), add_external_potential_forces(), add_non_bonded_pair_force(), add_pair(), box_l, CellPList::cell, DomainDecomposition::cell_inter, check_id, current_time_step_is_small, dd, distance2vec(), do_nonbonded(), errexit(), get_ia_param(), i, ParticleProperties::identity, local_cells, IA_parameters::max_cut, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, n_nodes, n_part, neighbor, IA_Neighbor_List::nList, ONEPART_TRACE, ParticlePosition::p, Particle::p, ParticleList::part, PI, IA_Neighbor::pList, Particle::r, rebuild_verletlist, resize_verlet_list(), skin, smaller_time_step, ParticleProperties::smaller_timestep, SQR(), this_node, ParticleProperties::type, DomainDecomposition::use_vList, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by force_calc().
void calculate_verlet_energies ()
Nonbonded and bonded energy calculation using the verlet list.
Definition at line 313 of file verlet.cpp.
References add_bonded_energy(), add_constraints_energy(), add_external_potential_energy(), add_kinetic_energy(), add_non_bonded_pair_energy(), CellPList::cell, DomainDecomposition::cell_inter, dd, distance2vec(), i, ParticleProperties::identity, local_cells, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, PairList::pair, ParticleList::part, Particle::r, this_node, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by energy_calc().
void calculate_verlet_ia ()
Nonbonded and bonded force calculation using the verlet list.
Definition at line 165 of file verlet.cpp.
References add_bonded_force(), add_constraints_forces(), add_external_potential_forces(), add_non_bonded_pair_force(), CellPList::cell, DomainDecomposition::cell_inter, current_time_step_is_small, dd, distance2vec(), i, local_cells, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, Particle::p, PairList::pair, ParticleList::part, Particle::r, smaller_time_step, ParticleProperties::smaller_timestep, and IA_Neighbor::vList.
Referenced by force_calc().
void calculate_verlet_virials (int v_comp)
Nonbonded and bonded pressure calculation using the verlet list.
Parameters
v_comp flag which enables (1) compensation of the velocities required for deriving a pressure reflecting nptiso_struct::p_inst; naturally it doesn't make sense to use it without NpT.
Definition at line 362 of file verlet.cpp.
References add_bonded_virials(), add_kinetic_virials(), add_non_bonded_pair_virials(), add_three_body_bonded_stress(), CellPList::cell, DomainDecomposition::cell_inter, dd, distance2vec(), i, local_cells, max_cut_nonbonded, PairList::n, CellPList::n, ParticleList::n, IA_Neighbor_List::n_neighbors, IA_Neighbor_List::nList, ParticlePosition::p, PairList::pair, ParticleList::part, Particle::r, this_node, VERLET_TRACE, and IA_Neighbor::vList.
Referenced by pressure_calc().
void free_pairList (PairList * list)
Free a Pair List .
Definition at line 88 of file verlet.cpp.
References PairList::max, PairList::n, PairList::pair, and realloc.
Referenced by dd_topology_release().
void init_pairList (PairList * list)
Initialize a Pair List.
Use with care and ONLY for initialization!
Definition at line 81 of file verlet.cpp.
References PairList::max, PairList::n, and PairList::pair.
Referenced by dd_init_cell_interactions(), and le_dd_init_cell_interactions().
void resize_verlet_list (PairList * pl)
Resizes a verlet pair list according to the actual content (*vl).n.
Parameters
pl Pointer to the verlet pair list.
Definition at line 412 of file verlet.cpp.
References LIST_INCREMENT, PairList::max, PairList::n, PairList::pair, and realloc.
Referenced by build_verlet_lists(), and build_verlet_lists_and_calc_verlet_ia().