ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: virtual_sites.hpp File Reference
virtual_sites.hpp File Reference
This file contains routine to handle virtual sites Virtual sites are like particles, but they will be not integrated.
#include "particle_data.hpp"
#include "virtual_sites_com.hpp"
#include "virtual_sites_relative.hpp"
Functions
void update_mol_vel_pos ()
void update_mol_vel ()
void update_mol_pos ()
int update_mol_pos_cfg ()
int ifParticleIsVirtual (Particle *p)
Detailed Description
This file contains routine to handle virtual sites Virtual sites are like particles, but they will be not integrated.
Step performed for virtual sites:
update virtual sites
calculate forces
distribute forces
move no-virtual particles
update virtual sites
Definition in file virtual_sites.hpp.
Function Documentation
int ifParticleIsVirtual (Particle * p) inline
Definition at line 64 of file virtual_sites.hpp.
References ParticleProperties::isVirtual, and Particle::p.
Referenced by add_dpd_thermo_pair_force(), add_kinetic_energy(), calc_dipole_of_molecule(), calc_energy_kinetic_mol(), calc_kinetic(), calc_mol_pos(), calc_mol_pos_cfg(), calc_mol_vel(), calc_particle_lattice_ia(), convert_torques_propagate_omega(), distribute_mol_force(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), get_mol_com_particle(), get_mol_com_particle_from_molid_cfg(), propagate_pos(), propagate_pos_sd(), propagate_press_box_pos_and_rescale_npt(), propagate_vel(), propagate_vel_pos(), put_mol_force_on_parts(), rescale_forces_propagate_vel(), sd_get_particle_num(), simple_momentum_update(), steepest_descent_step(), tclcommand_analyze_parse_and_print_check_mol(), tscale_momentum_update(), update_mol_pos(), update_mol_pos_particle(), update_mol_vel(), update_mol_vel_particle(), and vs_relative_pressure_and_stress_tensor().
void update_mol_pos ()
Definition at line 57 of file virtual_sites.cpp.
References CellPList::cell, i, ifParticleIsVirtual(), local_cells, CellPList::n, ParticleList::n, ParticleList::part, and update_mol_pos_particle().
Referenced by update_mol_vel_pos().
int update_mol_pos_cfg ()
Definition at line 74 of file virtual_sites.cpp.
References i, n_part, partCfg, and update_mol_pos_particle().
void update_mol_vel ()
Definition at line 39 of file virtual_sites.cpp.
References CellPList::cell, i, ifParticleIsVirtual(), local_cells, CellPList::n, ParticleList::n, ParticleList::part, and update_mol_vel_particle().
Referenced by integrate_vv(), and update_mol_vel_pos().
void update_mol_vel_pos ()
Definition at line 30 of file virtual_sites.cpp.
References update_mol_pos(), and update_mol_vel().
Referenced by force_calc().