ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: virtual_sites_relative.cpp File Reference
virtual_sites_relative.cpp File Reference
#include "virtual_sites_relative.hpp"
#include "rotation.hpp"
Functions
Particle * vs_relative_get_real_particle (Particle *p)
void update_mol_pos_particle (Particle *p)
void update_mol_vel_particle (Particle *p)
void distribute_mol_force ()
int vs_relate_to (int part_num, int relate_to)
void vs_relative_pressure_and_stress_tensor (double *pressure, double *stress_tensor)
Function Documentation
void distribute_mol_force ()
Definition at line 145 of file virtual_sites_relative.cpp.
References CellPList::cell, ParticleForce::f, Particle::f, get_mi_vector(), i, ifParticleIsVirtual(), local_cells, CellPList::n, ParticleList::n, ParticlePosition::p, Particle::p, ParticleList::part, Particle::r, ParticleForce::torque, update_mol_pos_particle(), vector_product(), and vs_relative_get_real_particle().
void update_mol_pos_particle (Particle * p)
Definition at line 37 of file virtual_sites_relative.cpp.
References box_l, convert_quat_to_quatu(), i, multiply_quaternions(), ParticlePosition::p, Particle::p, PERIODIC, ParticlePosition::quat, Particle::r, runtimeError, sqrlen(), ParticleProperties::vs_relative_distance, and vs_relative_get_real_particle().
Referenced by distribute_mol_force(), and vs_relative_pressure_and_stress_tensor().
void update_mol_vel_particle (Particle * p)
Definition at line 95 of file virtual_sites_relative.cpp.
References convert_omega_body_to_space(), convert_quat_to_quatu(), i, Particle::m, multiply_quaternions(), Particle::p, ParticlePosition::quat, Particle::r, runtimeError, sqrlen(), time_step, ParticleMomentum::v, vector_product(), ParticleProperties::vs_relative_distance, and vs_relative_get_real_particle().
int vs_relate_to (int part_num, int relate_to)
Definition at line 193 of file virtual_sites_relative.cpp.
References convert_quatu_to_quat(), ES_ERROR, ES_OK, get_mi_vector(), get_particle_data(), i, min_global_cut, multiply_quaternions(), ParticlePosition::p, ParticlePosition::quat, Particle::r, runtimeError, runtimeWarning, set_particle_quat(), set_particle_vs_relative(), and sqrlen().
Referenced by handle_collisions(), and part_parse_vs_relate_to().
Particle* vs_relative_get_real_particle (Particle * p)
Definition at line 30 of file virtual_sites_relative.cpp.
References local_particles, Particle::p, and ParticleProperties::vs_relative_to_particle_id.
Referenced by distribute_mol_force(), update_mol_pos_particle(), update_mol_vel_particle(), and vs_relative_pressure_and_stress_tensor().
void vs_relative_pressure_and_stress_tensor (double * pressure, double * stress_tensor)
Definition at line 297 of file virtual_sites_relative.cpp.
References CellPList::cell, ParticleForce::f, Particle::f, get_mi_vector(), i, ifParticleIsVirtual(), local_cells, CellPList::n, ParticleList::n, ParticlePosition::p, ParticleList::part, Particle::r, time_step, update_mol_pos_particle(), and vs_relative_get_real_particle().
Referenced by pressure_calc().