ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: virtual_sites_com_tcl.cpp File Reference
virtual_sites_com_tcl.cpp File Reference
#include "virtual_sites_com.hpp"
#include "virtual_sites_com_tcl.hpp"
#include "parser.hpp"
#include "virtual_sites.hpp"
#include "topology.hpp"
#include "grid.hpp"
#include "errorhandling.hpp"
Functions
int tclcommand_analyze_parse_and_print_pressure_mol (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze_parse_and_print_energy_kinetic_mol (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze_parse_and_print_dipmom_mol (Tcl_Interp *interp, int argc, char **argv)
int tclcommand_analyze_parse_and_print_check_mol (Tcl_Interp *interp, int argc, char **argv)
Function Documentation
int tclcommand_analyze_parse_and_print_check_mol (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 193 of file virtual_sites_com_tcl.cpp.
References distance(), get_particle_data(), ParticleLocal::i, ifParticleIsVirtual(), Particle::l, n_part, ParticlePosition::p, Particle::p, partCfg, Particle::r, unfold_position(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_and_print_dipmom_mol (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 128 of file virtual_sites_com_tcl.cpp.
References ARG0_IS_S, ARG1_IS_I, calc_absolute_dipolmoment_mol(), calc_total_dipolmoment_mol(), n_molecules, runtimeError, sortPartCfg(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_and_print_energy_kinetic_mol (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 84 of file virtual_sites_com_tcl.cpp.
References ARG0_IS_I, calc_energy_kinetic_mol(), n_molecules, runtimeError, sortPartCfg(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().
int tclcommand_analyze_parse_and_print_pressure_mol (Tcl_Interp * interp, int argc, char ** argv)
Definition at line 32 of file virtual_sites_com_tcl.cpp.
References ARG0_IS_I, ARG1_IS_I, calc_pressure_mol(), n_molecules, runtimeError, sortPartCfg(), updatePartCfg(), and WITHOUT_BONDS.
Referenced by tclcommand_analyze().