ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: virtual_sites_com.hpp File Reference
virtual_sites_com.hpp File Reference
#include "config.hpp"
#include "particle_data.hpp"
Functions
void update_mol_pos_particle (Particle *)
void update_mol_vel_particle (Particle *)
void distribute_mol_force ()
Particle * get_mol_com_particle (Particle *calling_p)
double get_mol_dist (Particle *p1, Particle *p2)
double get_mol_dist_partcfg (Particle *p1, Particle *p2)
double calc_pressure_mol (int type1, int type2)
double calc_energy_kinetic_mol (int type)
void calc_total_dipolmoment_mol (int type, double total_dipole[4])
void calc_absolute_dipolmoment_mol (int type, double total_dipole[2])
Function Documentation
void calc_absolute_dipolmoment_mol (int type, double total_dipole[2])
Definition at line 408 of file virtual_sites_com.cpp.
References calc_dipole_of_molecule(), i, n_molecules, and topology.
Referenced by tclcommand_analyze_parse_and_print_dipmom_mol().
double calc_energy_kinetic_mol (int type)
Definition at line 385 of file virtual_sites_com.cpp.
References get_mol_com_particle_from_molid_cfg(), i, ifParticleIsVirtual(), Particle::m, n_molecules, PMASS, sqrlen(), time_step, topology, and ParticleMomentum::v.
Referenced by tclcommand_analyze_parse_and_print_energy_kinetic_mol().
double calc_pressure_mol (int type1, int type2)
Definition at line 334 of file virtual_sites_com.cpp.
References calc_force_between_mol(), get_mol_dist_vector_from_molid_cfg(), i, n_molecules, start, and topology.
Referenced by tclcommand_analyze_parse_and_print_pressure_mol().
void calc_total_dipolmoment_mol (int type, double total_dipole[4])
Definition at line 428 of file virtual_sites_com.cpp.
References calc_dipole_of_molecule(), i, n_molecules, and topology.
Referenced by tclcommand_analyze_parse_and_print_dipmom_mol().
void distribute_mol_force ()
Definition at line 21 of file ibm_main.cpp.
Particle* get_mol_com_particle (Particle * calling_p)
Definition at line 264 of file virtual_sites_com.cpp.
References IntList::e, i, ParticleProperties::identity, ifParticleIsVirtual(), local_particles, ParticleProperties::mol_id, IntList::n, Particle::p, Molecule::part, runtimeError, and topology.
Referenced by get_mol_dist().
double get_mol_dist (Particle * p1, Particle * p2)
Definition at line 300 of file virtual_sites_com.cpp.
References get_mi_vector(), get_mol_com_particle(), ParticleProperties::identity, ParticlePosition::p, Particle::p, Particle::r, runtimeError, and SQR().
Referenced by checkIfParticlesInteractViaMolCut().
double get_mol_dist_partcfg (Particle * p1, Particle * p2)
Definition at line 480 of file virtual_sites_com.cpp.
References get_mol_dist_vector_from_molid_cfg(), ParticleProperties::mol_id, Particle::p, and SQR().
Referenced by checkIfParticlesInteractViaMolCut_partcfg().
void update_mol_pos_particle (Particle *)
Definition at line 19 of file ibm_main.cpp.
void update_mol_vel_particle (Particle *)
Definition at line 20 of file ibm_main.cpp.