ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: vmdsock.cpp File Reference
vmdsock.cpp File Reference
This is from NAMD, DO NOT CHANGE!
#include <sys/types.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <strings.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netdb.h>
#include <cerrno>
#include "vmdsock.hpp"
Macros
#define VMDSOCKINTERNAL
Copyright (c) 1995, 1996, 1997, 1998, 1999, 2000 by The Board of Trustees of the University of Illinois.
Functions
int vmdsock_init (void)
void * vmdsock_create (void)
int vmdsock_connect (void *v, const char *host, int port)
int vmdsock_bind (void *v, int port)
int vmdsock_listen (void *v)
void * vmdsock_accept (void *v)
int vmdsock_write (void *v, const void *buf, int len)
int vmdsock_read (void *v, void *buf, int len)
void vmdsock_destroy (void *v)
int vmdsock_selread (void *v, int sec)
int vmdsock_selwrite (void *v, int sec)
Detailed Description
This is from NAMD, DO NOT CHANGE!
Definition in file vmdsock.cpp.
Macro Definition Documentation
#define VMDSOCKINTERNAL
Copyright (c) 1995, 1996, 1997, 1998, 1999, 2000 by The Board of Trustees of the University of Illinois.
All rights reserved.
Definition at line 50 of file vmdsock.cpp.
Function Documentation
void* vmdsock_accept (void * v)
Definition at line 144 of file vmdsock.cpp.
References malloc.
Referenced by tclcommand_imd_print_check_connect().
int vmdsock_bind (void * v, int port)
Definition at line 130 of file vmdsock.cpp.
Referenced by tclcommand_imd().
int vmdsock_connect (void * v, const char * host, int port)
Definition at line 108 of file vmdsock.cpp.
void* vmdsock_create (void)
Definition at line 92 of file vmdsock.cpp.
References free, and malloc.
Referenced by tclcommand_imd().
void vmdsock_destroy (void * v)
Definition at line 184 of file vmdsock.cpp.
References free.
Referenced by tclcommand_imd(), tclcommand_imd_print_check_connect(), and tclcommand_imd_print_drain_socket().
int vmdsock_init (void)
Definition at line 73 of file vmdsock.cpp.
Referenced by tclcommand_imd().
int vmdsock_listen (void * v)
Definition at line 139 of file vmdsock.cpp.
Referenced by tclcommand_imd().
int vmdsock_read (void * v, void * buf, int len)
Definition at line 174 of file vmdsock.cpp.
Referenced by imd_readn().
int vmdsock_selread (void * v, int sec)
Definition at line 197 of file vmdsock.cpp.
Referenced by imd_recv_handshake(), tclcommand_imd_print_check_connect(), and tclcommand_imd_print_drain_socket().
int vmdsock_selwrite (void * v, int sec)
Definition at line 214 of file vmdsock.cpp.
Referenced by tclcommand_imd_parse_pos().
int vmdsock_write (void * v, const void * buf, int len)
Definition at line 165 of file vmdsock.cpp.
Referenced by imd_writen().