ESPResSo 3.4-dev-1009-g69a2b86-dirty-git: vmdsock.hpp File Reference
vmdsock.hpp File Reference
DO NOT CHANGE !!!
Functions
int vmdsock_init (void)
void * vmdsock_create (void)
int vmdsock_bind (void *, int)
int vmdsock_listen (void *)
void * vmdsock_accept (void *)
int vmdsock_connect (void *, const char *, int)
int vmdsock_write (void *, const void *, int)
int vmdsock_read (void *, void *, int)
int vmdsock_selread (void *, int)
int vmdsock_selwrite (void *, int)
void vmdsock_destroy (void *)
Detailed Description
DO NOT CHANGE !!!
Copyright (c) 1995, 1996, 1997, 1998, 1999, 2000 by The Board of Trustees of the University of Illinois. All rights reserved.
Definition in file vmdsock.hpp.
Function Documentation
void* vmdsock_accept (void *)
Definition at line 144 of file vmdsock.cpp.
References malloc.
Referenced by tclcommand_imd_print_check_connect().
int vmdsock_bind (void * , int)
Definition at line 130 of file vmdsock.cpp.
Referenced by tclcommand_imd().
int vmdsock_connect (void * , const char * , int)
Definition at line 108 of file vmdsock.cpp.
void* vmdsock_create (void)
Definition at line 92 of file vmdsock.cpp.
References free, and malloc.
Referenced by tclcommand_imd().
void vmdsock_destroy (void *)
Definition at line 184 of file vmdsock.cpp.
References free.
Referenced by tclcommand_imd(), tclcommand_imd_print_check_connect(), and tclcommand_imd_print_drain_socket().
int vmdsock_init (void)
Definition at line 73 of file vmdsock.cpp.
Referenced by tclcommand_imd().
int vmdsock_listen (void *)
Definition at line 139 of file vmdsock.cpp.
Referenced by tclcommand_imd().
int vmdsock_read (void * , void * , int)
Definition at line 174 of file vmdsock.cpp.
Referenced by imd_readn().
int vmdsock_selread (void * , int)
Definition at line 197 of file vmdsock.cpp.
Referenced by imd_recv_handshake(), tclcommand_imd_print_check_connect(), and tclcommand_imd_print_drain_socket().
int vmdsock_selwrite (void * , int)
Definition at line 214 of file vmdsock.cpp.
Referenced by tclcommand_imd_parse_pos().
int vmdsock_write (void * , const void * , int)
Definition at line 165 of file vmdsock.cpp.
Referenced by imd_writen().